### ISSUE TITLE
НДС по НМА

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1043]
Originally reported on Google Code with ID 1043

```
Почему когда я приходую НМА, на входной НДС при вводе в эксплуатацию
ставится проводка Дт 01 Кт 18.01.03? НДС вроде должен приниматься к зачету
равными частями 1/12 как и по основным. 

```

Reported by `gs1994` on 2008-08-07 09:21:43

**Comment by NikolayUkleyko** [comment]
С @MIchaelShoihet мы данную тему обсуждали. Сейчас сумма входящего НДС в документах **ОС. Акт ввода** не рассматривается. Соответственно к зачету не берется.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
