### ISSUE TITLE
Структура справочника ТМЦ

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1050]
Originally reported on Google Code with ID 1050

```
На крупном предприятии каждое подразделение хочет видеть справочник ТМЦ со
своей структурой товарных групп и, зачастую, со своими наименованиями для
одних и тех же товаров.




```

Reported by `gs1994` on 2008-08-22 17:17:23

**Comment by gsbelarus** [comment]
```
Ну да одни работали с одной программой другие с другой и каждый хочет видеть товары

как были в тех программах - это ерунда. Вот другой вопрос с группировкой, она может

быть разной для различных служб и над этим стоит подумать. Сейчас мы в этом случае

создаем отдельные справочники, который привязываем к товарам для своей группировки
```

Reported by `mikleshoihet` on 2008-08-22 20:06:32

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2009-02-09 16:30:09
- **Labels added**: GedeminEXE

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by NikolayUkleyko** [comment]
@ilonaand  , пожалуйста, изложите Вашу точку зрения.

----

На волне новой разрабатываемой оборотной ведомости данный вопрос очень интересен.

**Comment by ilonaand** [comment]
Структура товарных групп должна быть едина для всех, постепенно оно унифицируется, когда отходят от предыдущих программ. Главный вопрос в данном случае- с группировкой, чтобы одни и те же товары не множились в геометрической прогрессии. Сейчас это решается либо созданием отдельных таблиц с привязкой,  конфигураций товаров для отчетов. Но чаще всего, к прискорбию, решается созданием пачки одинаковых товаров, но в разных группах.  Потом в документах приходится писать пачку кода для ограничения по группам, либо отчеты становятся мукой, чтобы свести идентичные товары из разных групп.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
