### ISSUE TITLE
xCalculatorEdit

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1051]
Originally reported on Google Code with ID 1051

```
После изменения данный компонент перестал правильно работать.
1. Если было сделано форматирование на 1000 , то зачем в данном случае 
заходить в в калькулятор.
2. После форматирования, текст число остаётся с пробелами, и после этого, 
сумма из него, или параметр (проверялось в SQL редакторе как пораметр поля 
типа NUMERIC) уже ну ни как не является float-ом.

Просьба вернуть всё на место.


```

Reported by `Alexander.GoldenSoft` on 2008-08-25 08:13:05

**Comment by gsbelarus** [comment]
```
Просто не совсем понятно, почему визуальное форматирование должно изменять реальное

значение.
```

Reported by `Alexander.GoldenSoft` on 2008-08-25 08:20:35

**Comment by gsbelarus** [comment]
```
"1. Если было сделано форматирование на 1000 , то зачем в данном случае 
заходить в в калькулятор."

В смысле, "заходить в в калькулятор" ??

"2. После форматирования, текст число остаётся с пробелами, и после этого, 
сумма из него, или параметр (проверялось в SQL редакторе как пораметр поля 
типа NUMERIC) уже ну ни как не является float-ом."

У калькулятора есть свойство Value, которое возвращает числовое значение,
ято здесь не так?

```

Reported by `gs1994` on 2008-08-25 10:42:18

**Comment by gsbelarus** [comment]
```
1. На форме лежит компонент TxCalculatorEdit. Сейчас, я так понял, было сделано, что

бы он отделял пробелами тысячи. Так вот, он форматирует, только когда вызываешь 
калькулятор (стрелочка вниз). Так и задумывалось?
2. Я про то, что в коде надо теперь просмотреть все места, где раньше просто бралось

свойство Text, а не Value. Вот например у нас в flt_dlgInputParam_unit при 
подстановке параметров такое. а ещё куча мест в настройках, где берётся именно Text.
```

Reported by `Alexander.GoldenSoft` on 2008-08-25 11:24:05

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2008-08-25 11:50:58
- **Status changed**: `Fixed`

**Comment by gsbelarus** [comment]
```
1. Не форматирует сразу после ввода значения (даже после открытия\закрытия
калькулятора). Форматирование происходит только при программном присвоении через
свойство.

2. При вводе хотелось бы опускать пробелы как будто их нет (перескакивать через них
как перескакиваем через точки в TxDateEdit).

3. Сделать свойство типа boolean CalculatorLikeFormat, при установке которого
начинала работать разбивка чисел.

4. Может, при включенной разбивке выводить числа прижатыми к правой стороне Edit'а,
как в калькуляторе.
```

Reported by `flakekun` on 2008-08-25 13:55:40
- **Status changed**: `Accepted`

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2008-08-25 14:01:10
- **Status changed**: `New`
- **Labels added**: Type-Enhancement, Priority-Low
- **Labels removed**: Type-Defect, Priority-High

**Comment by gsbelarus** [comment]
Reported by `hjamesGS` on 2008-08-27 09:54:40

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2009-02-09 16:30:09
- **Labels added**: GedeminEXE

**Comment by NikolayUkleyko** [comment]
Есть такая проблема, когда из Excel скопировав значение с **разрядами** пытаешься его вставить в ячейку Гедымина - программа отображает окно с сообщением об ошибке:

![1](https://cloud.githubusercontent.com/assets/11497453/13422415/bd2aebba-dfa5-11e5-9291-f65513d79b01.png)

  Это вызывает неудобства.
  Пожалуйста, предусмотрите такую возможность.

**Comment by gsbelarus** [comment]
В ячейку или в калькулятор?

**Comment by NikolayUkleyko** [comment]
В ячейку.

**Comment by gsbelarus** [comment]
Для ячейки сделано.

Остальное можно закрывать?

**Comment by NikolayUkleyko** [comment]
В режиме калькулятора при вводе значение пропадает и ставится 0. Ошибки при этом нет.

**Comment by NikolayUkleyko** [comment]
**_Скопировал значение ячейки > Вставил в ячейку > Кнопка Tab или курсор вниз, или Enter**_ и программа отображает следующее окно с сообщением об ошибке:
![2](https://cloud.githubusercontent.com/assets/11497453/13747599/155e0be6-ea0a-11e5-90b4-dc35dc6dd193.png)

**Comment by gsbelarus** [comment]
Я конечно сделаю, но тут какая то фигня. Ты же вставляешь не число а какую-то строку, начинающуюся с кавычки.

**Comment by NikolayUkleyko** [comment]
Кавычки отсутствуют. В Excele по копируемой ячейке указано **_Формат ячеек > Числовой > Разделитель групп разрядов**_.
