### ISSUE TITLE
Окно выбора порядка позиций настройки

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1085]
Originally reported on Google Code with ID 1085

```
1. Кривое и не информативное окно. Нету поиска, нельзя сразу позицию 
добавить в конец или в начало. 
```

Reported by `Alexander.GoldenSoft` on 2008-09-23 08:23:45

**Comment by gsbelarus** [comment]
Reported by `flakekun` on 2008-09-23 11:44:30
- **Labels added**: Type-Enhancement, Priority-Low
- **Labels removed**: Type-Defect, Priority-Medium

**Comment by NikolayUkleyko** [comment]
Пожалуйста, скажите, актуальна ли данная тема ? Есть, же механизм ПИ.
