### ISSUE TITLE
Формирование ТТН на основе отвес-накладной

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1110]
Originally reported on Google Code with ID 1110

```
Дата ТТН должна быть в диапазоне:

Дата отвеса <= Дата ТТН <= (Дата отвеса + 1)

а то на СМК выписали несколько ТТН за первое число по отвесам за десятое и 
потом долго разбирались в отчетах.


```

Reported by `gs1994` on 2008-11-03 14:10:58

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2009-02-09 16:29:27
- **Labels added**: Meat

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@ilonaand
