### ISSUE TITLE
Полосатая прорисовка грида

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1148]
Originally reported on Google Code with ID 1148

```
При скроллинге неверно работает полосатая прорисовка если колонок 
достаточно много.
```

Reported by `Alexander.GoldenSoft` on 2008-12-12 14:15:08

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2008-12-14 14:17:23
- **Labels added**: Priority-Low
- **Labels removed**: Priority-Medium

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , судя по всему данный вопрос не прост, так как он связан еще и с мастером установок, и прочим функционалом.
Была дискуссия.
Пришли к тому, чтобы решить вопрос на совесть, то необходимо полностью переписывать соответствующий функционал.
Сейчас этого делать не будем.

@gsbelarus , имеет смысл закрыть данную тему и рассмотреть данный вопрос в новой платформе (Gedemin v.3.0 Web).
