### ISSUE TITLE
Запрещать перетаскивание ветвей дерева

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1156]
Originally reported on Google Code with ID 1156

```
В формах просмотра мастер-дитэйл при открытии запрещать перетаскивание
ветвей дерева.

```

Reported by `gs1994` on 2008-12-24 16:45:11

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2010-05-21 16:38:18
- **Labels added**: Component-UI, Tree

**Comment by NikolayUkleyko** [comment]
В опциях древовидной формы есть пункт **Разрешать перетаскивание**. Что позволяет настраивать перетаскивание. Об этом ли данная тема ?

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
