### ISSUE TITLE
Отчеты по инвентаризации

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1191]
Originally reported on Google Code with ID 1191

```
Есть новые формы отчетов по инвентаризации ОС и материалов. Их надо 
добавить в эталоны склада и ОС. Примеры бланков - у меня


```

Reported by `alexandra.gsoftware` on 2009-01-15 12:15:25

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2009-01-15 12:18:14
- **Labels added**: FA
- **Labels removed**: OS

**Comment by gsbelarus** [comment]
```
Эти формы я для Минскоблгаза сделал еще в прошлом году. Буду в офисе - положу свежую
базу, оттуда можно эти отчеты выдрать настройками. Или не надо?
```

Reported by `kovli.gs` on 2009-01-15 13:39:13

**Comment by gsbelarus** [comment]
```
Конечно надо(
```

Reported by `Alexander.GoldenSoft` on 2009-01-15 13:45:36

**Comment by gsbelarus** [comment]
```
Нашли часть отчетов (спасибо kovli.gs). Ничего лишнего не затягивают.
Но у нас, кстати, нет документа инвентаризации ОС. Т.е. сличительной ведомости можно

только бланк сделать.


```

Reported by `alexandra.gsoftware` on 2009-02-10 09:48:54

<hr>
- _Attachment: [2009_02_10 Отчеты 2008.gsf](https://storage.googleapis.com/google-code-attachments/gedemin/issue-1191/comment-4/2009_02_10 Отчеты 2008.gsf)_

**Comment by gsbelarus** [comment]
```
Создали отчетам отдельное ПИ
GS.ОС.Отчеты.Инвентаризация
```

Reported by `M.Burakina` on 2014-09-09 17:34:28

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Пожалуйста, закройте данную тему.
