### ISSUE TITLE
Корректировка сч/ф и накладной на отпуск

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1292]
Originally reported on Google Code with ID 1292

```
При выписке сч/ф и накладной на отпуск нет возможности изменить р/сч при 
наличии у организации нескольких р/сч (Br).
```

Reported by `KlimenkoNM` on 2009-03-26 12:14:58

**Comment by gsbelarus** [comment]
```
Для накладных уже не актуально, так как в новых формах банковские реквизиты уже не указываются.
А для счета-фактуры можно сделать. Это актуально для складского счета, так как в бланках
это есть.
```

Reported by `danilchyk` on 2013-05-18 13:13:12

**Comment by NikolayUkleyko** [comment]
Как вариант выбор банковского счета можно предусмотреть не в диалоговой форме документа, а в параметрах формируемой печатной формы.
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
