### ISSUE TITLE
Разработать сводную ведомость расхода продуктов по всем категориям

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1297]
Originally reported on Google Code with ID 1297

```
Разработать сводную ведомость расхода продуктов по всем категориям
(категории в меню) за один день.

```

Reported by `gs1994` on 2009-03-27 12:38:32

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@yoannawx
