### ISSUE TITLE
Переход на методы формы

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1315]
Originally reported on Google Code with ID 1315

```
Сделать удобный переход на методы формы. Сейчас приходится копировать имя
формы и искать по нему в разделе APPLICATION \ ветке TgdcCreateableForm.
```

Reported by `flakekun` on 2009-04-10 10:58:02

**Comment by gsbelarus** [comment]
```
Может отображать их в том же месте где и события (по нажатию Ctrl+M)?
```

Reported by `flakekun` on 2009-04-10 12:57:30

**Comment by gsbelarus** [comment]
```
или сделать переход по правой кновке в окошке "Свойства". 
```

Reported by `hjamesGS` on 2009-04-10 13:13:54

**Comment by gsbelarus** [comment]
```
мне кажется, лучше ка James предлагает
В любом случае, быстрый переход очень бы упростил жизнь настройщиков :)
```

Reported by `alexandra.gsoftware` on 2009-04-10 13:41:36

**Comment by NikolayUkleyko** [comment]
Коллеги, пожалуйста, подскажите, актуальна ли данная тема ?

**Comment by ShlTanya** [comment]
Уточните, пожалуйста, кнопку доложить на форму Свойства объекта?

**Comment by NikolayUkleyko** [comment]
_> Уточните, пожалуйста, кнопку доложить на форму Свойства объекта?_

Добавить к существующим кнопкам **Методы класса**, **Методы родителя**.

**Comment by Polfath** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
