### ISSUE TITLE
Заполнение полей: Кем создан, Когда создан.  в справочниках

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1474]
Originally reported on Google Code with ID 1474

```
В Справочниках: ТМЦ, Организаций, Подразделений
Обязательно заполнять поля: Кем создан, Когда создан.
Необходимо для поиска виновных в дублировании данных справочников 
```

Reported by `hjamesGS` on 2009-07-12 00:13:42

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2009-07-12 16:50:05
- **Labels added**: Type-Enhancement

**Comment by gsbelarus** [comment]
```
+ Проводки
```

Reported by `hjamesGS` on 2009-07-18 09:38:23

**Comment by gsbelarus** [comment]
```
Для справочников сделано.
Для проводок, сформированных по документу, в окне свойств объекта эта информация также
есть.
А вот для ручных проводок через свойства объекта не видно, хотя информацию такую получить
можно, так как ссылка на gd_document для ручных проводок есть.

```

Reported by `danilchyk` on 2013-05-22 12:30:48

**Comment by gsbelarus** [comment]
```
Могу предложить макрос "Информация о документе текущей проводки". Будет в списке макросов
ЖХО.
```

Reported by `kovli.gs` on 2013-05-22 12:57:39

<hr>
- _Attachment: [ЖХО_Инфо_о_проводке.gsf](https://storage.googleapis.com/google-code-attachments/gedemin/issue-1474/comment-4/ЖХО_Инфо_о_проводке.gsf)_

**Comment by NikolayUkleyko** [comment]
Да. Не везде в свойствах содержится информация о том, кем и когда добавлена запись.
  Макрос для Журнала хоз. операций интересен.

**Comment by NikolayUkleyko** [comment]
Close.
