### ISSUE TITLE
Ошибка при печати накладных

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1541]
Originally reported on Google Code with ID 1541

```
УНП организации хранится в текстовом поле, но если внести туда текст, то
при распечатке накладных (в складе) возникает ошибка ‘is a not valid
floating point value’
```

Reported by `danilchyk` on 2009-09-02 12:47:40

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2009-09-02 15:03:49
- **Labels added**: Depot

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@gsbelarus , пожалуйста, закройте тему.
