### ISSUE TITLE
2.11.	Добавить колонку Цена поставщика

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1584]
Originally reported on Google Code with ID 1584

```
Добавить колонку «цена поставщика» в документ инвентаризации «ведомость
инвентаризации_» рядом с колонкой «цена».
```

Reported by `gs1994` on 2009-09-16 14:31:46

**Comment by gsbelarus** [comment]
```
Вид отчета
```

Reported by `alexandra.gsoftware` on 2009-10-09 15:27:38

<hr>
- _Attachment: [Инвентаризация.doc](https://storage.googleapis.com/google-code-attachments/gedemin/issue-1584/comment-1/Инвентаризация.doc)_

**Comment by alexandra-gsoftware** [comment]
неактуально
