### ISSUE TITLE
остатки склада в розничных ценах

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1662]
Originally reported on Google Code with ID 1662

```
1.  Создать отчет – «остатки склада в розничных ценах по 
подразделениям».
2.  Создать отчет – «остатки склада в розничных ценах с выбором 
подразделения».
3.  Создать отчет – «остатки склада в розничных ценах с разбивкой по 
товарным группам».
4.  Создать отчет – «остатки склада в розничных ценах с выбором 
товарной группы».

```

Reported by `alexandra.gsoftware` on 2009-10-09 14:42:22

<hr>
- _Attachment: [Остатки в розничных ценах.doc](https://storage.googleapis.com/google-code-attachments/gedemin/issue-1662/comment-0/Остатки в розничных ценах.doc)_

**Comment by alexandra-gsoftware** [comment]
неактуально
