### ISSUE TITLE
Компоненткалькулятора в гриде

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1688]
Originally reported on Google Code with ID 1688

```
1. Для поля currency вызываем калькулятор
2. Набираем число, нажимаем кнопку "+\-" переходим на следующую ячейку
3. Скидывается изменение знака.
```

Reported by `Alexander.GoldenSoft` on 2009-10-22 10:24:10

**Comment by gsbelarus** [comment]
Reported by `flakekun` on 2010-01-05 12:49:47

**Comment by NikolayUkleyko** [comment]
Для корректности работы сперва указываем знак, а потом вводим число. Все равно при переходе на следующую строку или ячейку скидывается знак. Но, если использовать клавишу **Tab**, то знак сохраняется.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
