### ISSUE TITLE
Учет ГСМ (и не только)

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1744]
Originally reported on Google Code with ID 1744

```
Надо просмотреть все документы там где выбираются сотрудники и
подразделения, что бы везде где надо стояло ограничение на рабочую компанию
(причем для случаев холдинга, отслеживать изменение рабочей организации).
```

Reported by `mikleshoihet` on 2009-12-09 13:15:11

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2009-12-10 11:53:01
- **Labels added**: Type-Defect, Priority-Medium, GSM

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by YRozmysl** [comment]
Конкретно для ГСМ, оказалось не актуально, для ЗП  решено. Для других модулей не знаю

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
