### ISSUE TITLE
Приходный кассовый ордер

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1745]
Originally reported on Google Code with ID 1745

```
При устанвки галки Любой человек органичение на рабочую компанию убирается,
а класс остается TgdcEmployee  а надо в этом случае TgdcContact.
```

Reported by `mikleshoihet` on 2009-12-09 13:23:25

**Comment by gsbelarus** [comment]
```
В поле основание - выбираем по чеку , но так как нужено указывать  номер чека то 
приходится каждый раз добавлять в справочник операций  номер чека или же 
редактировать уже внесенный.Это не очень удобно.    
```

Reported by `PogoSG` on 2009-12-10 07:36:45

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2009-12-10 11:52:11
- **Labels added**: Type-Defect, Priority-Medium, Bank

**Comment by gsbelarus** [comment]
```
"Это не очень удобно".  А как удобно?
```

Reported by `ilonaand` on 2010-01-05 14:12:12
- **Status changed**: `Started`

**Comment by gsbelarus** [comment]
```
Логично иметь дополнительное просто текстовое поле.
```

Reported by `mikleshoihet` on 2010-01-05 14:34:44

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.

@gsbelarus , пожалуйста, закройте тему.
