### ISSUE TITLE
Если в расходных кассовых ордерах  не заполнено поле ВЫДАТЬ

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1791]
Originally reported on Google Code with ID 1791

```
Если в расходных кассовых ордерах  не заполнено поле ВЫДАТЬ то такие 
ордера не попадают в журнал регистрации кассовых ордеров.Это поле у нас не 
заполняется если выдача идет по ведомости или списку.  
```

Reported by `PogoSG` on 2010-01-05 14:36:52

**Comment by gsbelarus** [comment]
```
Желательно добавить сотрудника По ведомости или По списку и все-таки заполнять это поле.
```

Reported by `mikleshoihet` on 2010-01-05 15:36:02

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2010-01-15 08:36:55
- **Labels added**: Type-Defect, Priority-Medium, Bank, Gorodok
- **Labels removed**: priority-medium

**Comment by gsbelarus** [comment]
```
Ситуация - выплата командировочных через кассу списком от 2-х человек и 
более.Расходный кассовый ордер оформляется на список,при этом сумма проводки на 71

счет тоже попадает общей по списку.Естественно при построении ЖО по 71 счету в 
разрезе сотрудников   этих сумм нет  ( они есть отдельной строкой на кассире ).
Можно конечно выписывать расходный на каждого сотрудника , а если их более 10 то это

как то не очень удобно.
Может есть возможность сделать это через позицию документа добавив туда сотрудников

и сумму к выплате.Сделать проверку если есть сотрудники то сумма  проводки  по 
позиции если их  нет то по шапке.    
```

Reported by `PogoSG` on 2010-03-25 11:45:28

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2012-10-09 18:30:07

**Comment by NikolayUkleyko** [comment]
Согласно вышеприведенной информации следующая информация:

**a**. В документе **Расходный ордер** в поле **_Подразделение**_ как вариант можно предусмотреть возможность выбора сотрудников. Если, в шапке данного документа не заполнено поле **_Выдать**_, то при загрузке в документ **Кассовая книга** в позицию в поле **_Сотрудник**_ подставлять значения из позиции ордера.

**b**. Проводки по кассовым документам (именно по 71-у счету) формируются по документу **Кассовая книга**, а не по ордерам.

**c**. Для получения красивого Журнала-ордера и других бухгалтерских отчетов по 71-у счету необходимо физическое заполнение сотрудников по кассовым документам, а не простой ввод общей суммы по кассиру.

  У кого какие предложения ?
  Если, нет - пожалуйста, закройте данную тему.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
