### ISSUE TITLE
Сумма НДС в накладных на возврат от покупателей

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#1830]
Originally reported on Google Code with ID 1830

```
При возврате товара от покупателей сумма НДС должна должна рассчитываться
исходя из ставки НДС, которая действовала на момент продажи. А сейчас сумма
рассчитывается исходя из ставки, которая действует на момент возврата.
```

Reported by `danilchyk` on 2010-01-27 10:26:16

**Comment by gsbelarus** [comment]
```
При возврате товара от покупателя, как и при возврате товара поставщику, по-хорошему,
проводки надо бы сторнировать, т.е. отыскивать проводки, которые были сделаны по
отпуску на сторону или по поступлению и сторнировать их пропорционально количеству
возвращаемого товара. Это было бы универсально и автоматически настраиваемо.
```

Reported by `kovli.gs` on 2010-01-27 14:42:07

**Comment by gsbelarus** [comment]
```
Первое сделано.
```

Reported by `alexandra.gsoftware` on 2010-01-29 16:25:03

**Comment by NikolayUkleyko** [comment]
В документ возврата товаров в признаки существующей карточки добавляем признак **ставка НДС отпуска (USR$INV_SELLNDS)**. Настраиваем типовые проводки согласно данной ставки. Так реализовано на эталонной БД и скинуто в ПИ.

  По поводу @kovli.gs

> по-хорошему,
> проводки надо бы сторнировать, т.е. отыскивать проводки, которые были сделаны по
> отпуску на сторону или по поступлению и сторнировать их пропорционально количеству
> возвращаемого товара

  Спорный момент. Зачем так усложнять ? Есть же признаки существующей карточки.
