### ISSUE TITLE
Добавить в USR$INV_BALANCE первичный ключ

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2055]
Originally reported on Google Code with ID 2055

```
У нас много кода, который считает что БД реляционная и обращается atDatabase... Relation.PrimaryKey.
На таблице без первичного ключа будет AV.
```

Reported by `gs1994` on 2010-06-16 17:29:05

**Comment by NikolayUkleyko** [comment]
Пожалуйста, скажите, это еще актуально ?

**Comment by MIchaelShoihet** [comment]
Это относиться только к ВМК и надо проверить

**Comment by NikolayUkleyko** [comment]
Посмотрел на Эталонной БД в IBExpert:
![image](https://user-images.githubusercontent.com/11497453/150775352-ff076f51-c953-4138-bf91-e59f03384943.png)
