### ISSUE TITLE
Проверить сохранение параметров округления на базе БМКК

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2062]
Originally reported on Google Code with ID 2062

```
Проверить.

```

Reported by `gs1994` on 2010-06-24 13:29:32

**Comment by NikolayUkleyko** [comment]
Тема перенеса в
Слетают параметры складского учета · Issue #358 · GoldenSoftwareLtd/gedemin-apps
https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/358

----

@gsbelarus , пожалуйста, закройте тему.
