### ISSUE TITLE
Ошибка при неверно введенном пути для экспорта

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2090]
Originally reported on Google Code with ID 2090

```
В экспорте платежек в Белгазпромбанк. Перед строкой: 

  FileName = Path & "pp" & q.FieldByName("Number").AsString & ".txt"

Добавить строку:

  if Right(Path, 1) <> "\" then Path = Path & "\"

```

Reported by `gs1994` on 2010-07-28 11:11:31

**Comment by NikolayUkleyko** [comment]
В стандартных ПИ похожей выгрузки нет.
Алгоритмы выгрузки данных по платежных поручениям усовершенствовались.

@gsbelarus , пожалуйста, закройте тему.
