### ISSUE TITLE
Доработка разноски по поставщикам и покупателям

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2160]
Originally reported on Google Code with ID 2160

```
  Для продолжения работ по внедрению на Витебском МПК материального склада, необходимо
доработать функцию разноски, в частности по поставщикам. Это особенно актуально для
предприятий работающих по оплате. 
  Основное требование. Наличие возможности ручного подбора кредитовых обязательств
для оплаты, возможность частичной оплаты конкретного документа. Ну и если прокатить
без позиционной оплаты.   Первые вариант моего предложения в присоединенном файле
```

Reported by `witthsl` on 2010-10-04 14:44:05

<hr>
- _Attachment: [Пример окна.doc](https://storage.googleapis.com/google-code-attachments/gedemin/issue-2160/comment-0/Пример окна.doc)_

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2010-11-06 13:13:01
- **Labels added**: Type-Enhancement, Priority-Medium, Depot, VMK, Bank

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
