### ISSUE TITLE
В документах ККЦ и ОТ обрабатывать отображение статуса рецептур

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2245]
Originally reported on Google Code with ID 2245

```
Если устарел то не отображать.
И, наверное, вообще отображать только те, которые имеют статус "Готов"
```

Reported by `stasgm` on 2010-11-15 09:15:22

**Comment by NikolayUkleyko** [comment]
@stasgm , если, на ,твой, взгляд данная тема уже неактуальна, пожалуйста, закрой ее.
