### ISSUE TITLE
Tgdc_frmInvSelectGoodRemains

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2280]
Originally reported on Google Code with ID 2280

```
Есть форма просмотра остатков по товару из складского документа.
Хотелось бы иметь такую же, но которая могла бы работать без привязки к документу склада,
что вы думаете на счёт этого (Tgdc_frmInvSelectGoodRemains и подобные этого не могут)
```

Reported by `Alexander.GoldenSoft` on 2010-12-08 13:47:46

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by alexandra-gsoftware** [comment]
Мне кажется, отдельный механизм не нужен. Если осень надо, люди сами руками рисуют форму
