### ISSUE TITLE
Учет 4 видов топлива

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2415]
Originally reported on Google Code with ID 2415

```
Возможность учета по 4 видам топлива по машине: ввод остатков, заправки автомобиля,
расчет норм списания, фактический расход, остатков на конец по каждому  виду топлива.

Для расчета норм списания в "Дополнительных нормах расхода ТСМ" добавить поле "вид
топлива"


```

Reported by `tatianawas3` on 2011-04-29 13:55:44

**Comment by gsbelarus** [comment]
```
а потом будет 5? делать сразу анлим.
```

Reported by `gs1994` on 2011-04-29 16:41:44
- **Labels added**: Type-Enhancement, Priority-Medium

**Comment by gsbelarus** [comment]
```
такая ситуация вполне вероятна, лучше сразу это учитывать
```

Reported by `tatianawas3` on 2011-05-04 10:20:07

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2011-05-06 09:57:48
- **Labels added**: Transport

**Comment by NikolayUkleyko** [comment]
Юра, пожалуйста, посмотри, актуальна ли данная тема ?
Если, нет - закрой ее.

**Comment by YRozmysl** [comment]
Можно закрывать,

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
