### ISSUE TITLE
ОБ УСТАНОВЛЕНИИ ФОРМ АКТА О ПРИЕМЕ-ПЕРЕДАЧЕ ОСНОВНЫХ СРЕДСТВ

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2464]
Originally reported on Google Code with ID 2464

```
Появилась новая форма ОС-1.
ПОСТАНОВЛЕНИЕ МИНИСТЕРСТВА ФИНАНСОВ РЕСПУБЛИКИ БЕЛАРУСЬ
22 апреля 2011 г. N 23

ОБ УСТАНОВЛЕНИИ ФОРМ АКТА О ПРИЕМЕ-ПЕРЕДАЧЕ ОСНОВНЫХ СРЕДСТВ, АКТА О ПРИЕМЕ-ПЕРЕДАЧЕ
НЕМАТЕРИАЛЬНЫХ АКТИВОВ И УТВЕРЖДЕНИИ ИНСТРУКЦИИ О ПОРЯДКЕ ЗАПОЛНЕНИЯ АКТА О ПРИЕМЕ-ПЕРЕДАЧЕ
ОСНОВНЫХ СРЕДСТВ И АКТА О ПРИЕМЕ-ПЕРЕДАЧЕ НЕМАТЕРИАЛЬНЫХ АКТИВОВ

```

Reported by `kovli.gs` on 2011-05-30 09:14:40

<hr>
- _Attachment: [акт_приема_передачи_2011.doc](https://storage.googleapis.com/google-code-attachments/gedemin/issue-2464/comment-0/акт_приема_передачи_2011.doc)_

**Comment by gsbelarus** [comment]
```
кстати да.
```

Reported by `hjamesGS` on 2011-06-01 08:01:24

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2011-06-01 12:05:23
- **Labels added**: Type-Task, Priority-Medium, FA

**Comment by gsbelarus** [comment]
```
Очень надо срочно. Даже вчера.
Ну как обычно.
```

Reported by `hjamesGS` on 2011-06-03 16:15:10
- **Labels added**: Priority-High
- **Labels removed**: Priority-Medium

**Comment by gsbelarus** [comment]
```
Есть уже что нибудь по этому пожеланию? Или всем самим переделывать?
```

Reported by `PogoSG` on 2011-06-28 13:09:58

**Comment by gsbelarus** [comment]
```
Есть настройка попрошу вам выслать ее
```

Reported by `mikleshoihet` on 2011-06-28 13:33:08

**Comment by gsbelarus** [comment]
```
После установки новой формы акта

ОС Внутренне перемещение 
ОС Отпуск на сторону
ñêðèïò-ôóíêöèÿ rp_Main148031619_164819474153968763_1630028950: 
body: Dynamic SQL Error
SQL error code = -206
Column unknown
A.USR$ACTBASE
At line 1, column 383, ñòðîêà: 124




```

Reported by `PogoSG` on 2011-07-01 05:29:01

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2011-07-01 06:15:46
- **Labels added**: Gorodok

**Comment by NikolayUkleyko** [comment]
Для того, чтобы быть в курсе обновлений форм, отчетов и прочего из законодательства и их реализации в Гедымине необходимо установить **_платное**_ программное обеспечение **Бизнес-инфо** или **Консультант-плюс**. В интернете найти ничего актуального бесплатного не получится. Так как, все ресурсы платные. В программном обеспечение **_Бизнес-инфо**_ или **Консультант-плюс** очень удобно реализована система поиска той или иной формы, отчета и прочих новостей в законодательстве.
  Если, я что-то не то написал, то можете самостоятельно попробовать найти в интернете  формы, отчета и прочих новостей в законодательстве.

**Comment by NikolayUkleyko** [comment]
Доработки выполнены давно.
  Проверено.
  Работает корректно.
  Пожалуйста, закройте данную тему.

**Comment by NikolayUkleyko** [comment]
Пожалуйста, закройте данную тему.
