### ISSUE TITLE
Отдел сбыта - прайс на готовую продукцию

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2481]
Originally reported on Google Code with ID 2481

```
При оформлении накладной на реализацию прайс в выборе отслеживается по дате актуальности.На
практике получается что прайсов с одинаковой датой актульности может больше одного
( один основной и несколько дополнительных) или же дата актуальности основного меньше
чем дополнительных.Операторам в таком случае приходится каждый раз в списке прайсов
искать основной.
Или же приходится менять дату актуальности ( повышается вероятность того продукцию
выпишут не по тем ценам).
Может есть смысл добавить признак основному прайсу что он основной
и в выборе учитывать два параметра.
При создании нового основного прайса в старом убираем этот признак.   

```

Reported by `PogoSG` on 2011-06-07 06:16:43

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2011-06-07 08:53:26
- **Labels added**: Type-Defect, Priority-Medium, Gorodok, Depot

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2011-06-07 08:53:39

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@ilonaand

**Comment by NikolayUkleyko** [comment]
Close.

**Comment by gsbelarus** [comment]
я имею ввиду поставить метку Close:

![image](https://user-images.githubusercontent.com/5175764/150556302-5eda6504-a17a-4d73-a086-69649d6686d6.png)

**Comment by NikolayUkleyko** [comment]
> я имею ввиду поставить метку Close:
> 
> ![image](https://user-images.githubusercontent.com/5175764/150556302-5eda6504-a17a-4d73-a086-69649d6686d6.png)

Андрей Петрович, это понятно.
В разделе https://github.com/GoldenSoftwareLtd/gedemin/issues у меня нет прав на работу с тэгами.
Как для своих тем, так и нет.
Поэтому помечаю по техническим возможностям.
