### ISSUE TITLE
В справочнике Норм расхода оболочек добавить возможность выбора округления

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2524]
Originally reported on Google Code with ID 2524

```
Добавить поле "кол-во знаков для округления" рядом с выбором оболочки\материала 
```

Reported by `stasgm` on 2011-07-11 10:38:30

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
