### ISSUE TITLE
Возможность сворачивания/разворачивания деревьев в выпадающем списке...

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2541]
Originally reported on Google Code with ID 2541

```

    Предложение.

    Добавить возможность сворачивания/разворачивания веток в выпадающем списке. То
есть, добавить возможность отображения в данной ситуации контекстного меню с пунктами
"Свернуть дерево", "Раскрыть дерево". Аналог, как при работе с Исследователем.


```

Reported by `NikolayUkleyko` on 2011-07-26 14:41:19

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2011-08-05 09:05:28
- **Labels added**: Type-Enhancement, Priority-Medium, GedeminEXE, Component-UI

**Comment by gsbelarus** [comment]
```

  Это реализуемо или нет ?

```

Reported by `NikolayUkleyko` on 2013-08-26 09:17:59

**Comment by gsbelarus** [comment]
```

  Кратко: да или нет.

```

Reported by `NikolayUkleyko` on 2013-10-25 06:47:13

**Comment by gsbelarus** [comment]
```

  Для древовидных выпадающих списков в шапочной части документов это реализовали. Хорошо
бы это сделать и для табличной части документов.
  В выпадающем списке на панели инструментов появилась кнопка ввиде плюса "Закрыть
дерево...".

```

Reported by `NikolayUkleyko` on 2013-11-12 09:49:46

**Comment by gsbelarus** [comment]
```

  Вообще, можно ли это реализовать и при работе с табличной частью документа ?

```

Reported by `NikolayUkleyko` on 2013-12-18 15:04:32

**Comment by gsbelarus** [comment]
```
В выпадающем списке работают следующие быстрые клавиши:

http://www.screenio.com/gui_screenio/gs_htmlhelp_subweb/controls/keyboard-treeview.htm

что тут еще надо?
```

Reported by `gs1994` on 2013-12-18 17:26:40

**Comment by gsbelarus** [comment]
```

  Спасибо !
  Закрываем тему.

```

Reported by `NikolayUkleyko` on 2014-01-16 07:03:08
- **Status changed**: `Fixed`

**Comment by NikolayUkleyko** [comment]
После сворачивания выпадающего списка при помощи соответствующей кнопки и последующий выбор верхнего уровня не фиксирует выбранный верхний уровень.
Что приводит к сохранению записи совершенно в другой ветке.
