### ISSUE TITLE
Ошибка при формировании книги покупок

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2604]
Originally reported on Google Code with ID 2604

```
При формировании книги покупок по материальному складу по учетной политике "По оплате"
сформировались позиции с суммой НДС 0,0001, в результате чего завышена стоимость покупок
без НДС. Такая ошибка появилась по позиции, где накладная на получение материала закрывалась
несколькими оплатами.
Витебский мясокомбинат.
```

Reported by `IrinaSpakoV` on 2011-10-21 13:27:13

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2011-10-21 13:29:37
- **Labels added**: Type-Defect, Priority-Medium, VMK

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2012-03-01 18:08:20
- **Labels added**: Depot

**Comment by NikolayUkleyko** [comment]
Пожалуйста, подскажите, данная тема актуальна ?
