### ISSUE TITLE
Округлить цену в фирменной торговле

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2622]
Originally reported on Google Code with ID 2622

```
Округлить цену в фирменной торговле-накладная на получение товара-подразделение 54.кафетерий-буфет
```

Reported by `stasgm` on 2011-11-23 07:58:16

**Comment by gsbelarus** [comment]
```
в накладной на получение товара - есть цена с наценкой общепита - так вот она тоже должна
округляться для кафетерия
```

Reported by `stasgm` on 2011-11-24 14:27:26

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@stasgm @yoannawx
