### ISSUE TITLE
Добавить ограничение в нормы оболочек

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2626]
Originally reported on Google Code with ID 2626

```
При вставке именной оболочки, проверять используется ли такая оболочка в других нормах..если
да то предупреждать и не вставлять в данную норму.
```

Reported by `stasgm` on 2011-11-29 14:33:30

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
