### ISSUE TITLE
Вопросы по колбасному. Часть 2

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2667]
Originally reported on Google Code with ID 2667

```
Зам ген директора по мясопереработке дала задание. Подредактировать отчет рецептурный
журнал. И еще один отчет добавить.
```

Reported by `stasgm` on 2012-01-24 12:52:07

<hr>
- _Attachment: [Книга1.xls](https://storage.googleapis.com/google-code-attachments/gedemin/issue-2667/comment-0/Книга1.xls)_

**Comment by gsbelarus** [comment]
Reported by `stasgm` on 2012-01-24 13:22:36

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
