### ISSUE TITLE
Доработка для Конструктора функций. Отображение границ процедуры по ширине блоков.

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2776]
Originally reported on Google Code with ID 2776

```

    Добавьте в Конструктор функций возможность отображение границ процедуры по ширине
блоков.
    При работе с ТХО и/или АХО иногда навзания блоков не полностью видны. Для удобства
приходится отодвигать границу процедуры немного вправо. Причем, при каждом входе в
Конструктор функций приходится отодвигать границу процедуры. При перемещении границы
можно случайно ее отпустить и проставить точку остановки.
    Сделайте так, чтобы границы процедуры автоматически растягивались по ширине блоков.

```

Reported by `NikolayUkleyko` on 2012-04-04 13:34:24

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2012-04-05 12:06:13
- **Labels added**: Type-Enhancement, Priority-Medium, GedeminEXE, Accountancy
- **Labels removed**: Gomeloboi

**Comment by gsbelarus** [comment]
```

  Это возможно или нет ? Было бы очень удобно.

```

Reported by `NikolayUkleyko` on 2013-05-18 08:00:21

**Comment by gsbelarus** [comment]
```
Да я то же очень поддерживаю
```

Reported by `mikleshoihet` on 2013-05-18 09:42:27

**Comment by gsbelarus** [comment]
```
Для начала можно просто колонку с блоками расширить в полтора-два раза. 
```

Reported by `gs1994` on 2013-05-18 09:50:25

**Comment by gsbelarus** [comment]
```

  Давайте попробуем пока так.

```

Reported by `NikolayUkleyko` on 2013-05-18 11:42:48

**Comment by gsbelarus** [comment]
```

  Как вариант, по двойному клику левой кнопкой мышки автоматическая подстройка ширины
процедуры по максимальной ширине блоков.
  Последнее состояние можно автоматически запоминать ?

```

Reported by `NikolayUkleyko` on 2013-10-18 07:47:13

**Comment by gsbelarus** [comment]
```

  Сделано и проверено.
  Работает корректно.
  Как работает ?
  Автоматическая подстройка ширины блока процедуры осуществляется при сохранении и
последующем реадктировании функции. То есть, не динамическая подстройка ширины блока
процедуры.

```

Reported by `NikolayUkleyko` on 2013-10-28 09:20:43
- **Status changed**: `Fixed`

**Comment by NikolayUkleyko** [comment]
По данной доработке выявлены напрягающие недочеты:

1. При большом количестве широких блоков не полностью растягивается блок процедуры.
2. Не совсем точно работает (с запаздыванием) выбор блоков. Особенно это наглядно при выборе  нескольких блоков, копировании и вставке.
3. Сохранение очередности блоков при перетаскивании и/или при копировании и вставке.

@ShlTanya , пожалуйста, посмотри и по возможности внеси доработки.
