### ISSUE TITLE
Доделать Брак в колбасном

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2792]
Originally reported on Google Code with ID 2792

```
В файле ТЗ
```

Reported by `stasgm` on 2012-04-13 12:35:30

<hr>
- _Attachment: [Брак.doc](https://storage.googleapis.com/google-code-attachments/gedemin/issue-2792/comment-0/Брак.doc)_

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2015-06-29 14:06:52
- **Labels added**: Meat
- **Labels removed**: meat

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@ilonaand
