### ISSUE TITLE
Константам Гедымина не помешал бы тип ссылка

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2839]
Originally reported on Google Code with ID 2839

```
и может даже множество.

```

Reported by `gs1994` on 2012-06-17 17:55:55

**Comment by gsbelarus** [comment]
```
Да, не помешало бы, так как отпадет необходимость рисовать формы для хранения параметров
определенной подсистемы. 
Но в этом случае надо также добавить возможность группировки констант по разделам (дерево).
Например, в настройке по производству МК есть форма параметров, в которой только параметров-ссылок
около 60 штук. Если все это хранить одним списком, то будет сложно найти нужную константу.


```

Reported by `danilchyk` on 2013-11-12 14:24:24

**Comment by gsbelarus** [comment]
```

  Кстати, не лишний функционал.

```

Reported by `NikolayUkleyko` on 2013-11-27 13:53:41

**Comment by NikolayUkleyko** [comment]
Приведу простой пример актуальности данной темы.
Подсистема ЗП и ОК. Формирование бухгалтерских проводок по счету **_76.02 (Расчеты по имущественному и личному страхованию)_**.
В типовой проводке по счету 76.02 по аналитике **Клиент** задается конкретное значение (Белгосстрах...области...району).
Со временем с определенной даты может быть выбрана совершенно другая организация.
Для того, чтобы в типовой проводке не прописывать условия на дату или не перебивать значение аналитики **Клиент** достаточно будет создать новую запись (**выбор из справочника Организаций**) в соответствующей константе и воспользоваться функцией **Acc_calcTaxRate**

```javascript
function Acc_calcTaxRate(taxname,enddate)
 set creator= new Tcreator
 set SQL1 = Creator.GetObject(nul, "TIBSQL", "")
 SQL1.Transaction = gdcBaseManager.ReadTransaction
 SQL1.SQL.Text = _
    " SELECT " + _
    " Z.CONSTVALUE, " + _
    " Z.CONSTDATE " + _
    " FROM   GD_CONSTVALUE Z " + _
    " JOIN GD_CONST T  ON  T.ID  =  Z.CONSTKEY " + _
    " LEFT JOIN GD_CONTACT U  ON U.ID  =  Z.USERKEY " + _
    " LEFT JOIN GD_CONTACT C  ON C.ID  =  Z.COMPANYKEY " + _
    "  " + _
    " where " + _
    " T.id=:constname and " + _
    " Z.CONSTDATE=(select max(cv.CONSTDATE) from GD_CONSTVALUE cv where  cv.constkey=:constname and cv.CONSTDATE<:enddate ) "
  SQL1.Prepare
  SQL1.ParamByName("constname").AsString = cstr(taxname)
  SQL1.ParamByName("enddate").AsString = cstr(cdate(enddate))
  SQL1.ExecQuery
  if SQL1.RecordCount > 0 then
    Acc_calcTaxRate = SQL1.FieldByName("CONSTVALUE").AsVariant
  else
    Acc_calcTaxRate = 0
  end if
 end function
```

Подобных примеров много.
Ссылки могут быть не только на GD_CONTACT, но и на другие таблицы, документы и т .д.
Пожалуйста, предусмотрите вышеприведенную возможность.

**Comment by NikolayUkleyko** [comment]
Данная тема рассматривается в https://github.com/GoldenSoftwareLtd/gedemin/issues/4028
@gsbelarus , пожалуйста, закройте здесь тему.
