### ISSUE TITLE
Сделать фильтр по полю как в разноске

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2848]
Originally reported on Google Code with ID 2848

```
Хорошо бы встроить в платформу (в формах с гридом) инструмент "фильтр по полю", который
есть у форм различных "разносок". Если база большая, то фильтр через шапку колонки
(где есть выбор "содержит") строится мучительно долго. А наш стандартный поиск через
"бинокль" не всегда отображает нужное поле.
```

Reported by `stasgm` on 2012-06-30 06:59:09

**Comment by NikolayUkleyko** [comment]
> _Если база большая, то фильтр через шапку колонки (где есть выбор "содержит") строится мучительно долго._

Сперва, лучше применять предопределенные фильтры и/или поиск при помощи бинокля, а затем выполнять автофильтрацию в гриде с данными.

-----

> _А наш стандартный поиск через "бинокль" не всегда отображает нужное поле._

Функционал поиска при помощи бинокля существенно доработан и он теперь более удобный.

Close.
