### ISSUE TITLE
Нужен промежуточный документ

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2863]
Originally reported on Google Code with ID 2863

```
При переносе заработной платы из путевых в документы зарплаты нужен промежуточный документ,
в который можно ввести готовые суммы по ремонтам, часы для расчета выслуги и сумму
выслуги(расчет по аналогу как  бригадных нарядах), процент премии и сумму премии, фазу
производства. 
```

Reported by `gs1994` on 2012-08-08 12:37:24

**Comment by NikolayUkleyko** [comment]
В документе **Путевой лист автомобиля** предусмотрен макрос **_Экспорт данных в документ 'Ручной ввод' для З/П**_ для выгрузки данных по заработной плате в документ учета заработной платы **Ручной ввод**. Впоследствии, в данном документе можно вводить любые данные.
  У кого какие есть предложения ?
  Если, предложений нет, пожалуйста, закройте данную тему.
