### ISSUE TITLE
Сделать в ОС амортизацию сезонных ОС 

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#2947]
Originally reported on Google Code with ID 2947

```
Читать тут http://www.primabalans.by/news/59.html

```

Reported by `stasgm` on 2012-11-28 07:54:41

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2012-11-29 10:08:31
- **Labels added**: FA
- **Labels removed**: OS

**Comment by NikolayUkleyko** [comment]
Тема переместилась в https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/89
  Можно здесь закрыть.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
