### ISSUE TITLE
Сделать команду Скопировать форму

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3]
Originally reported on Google Code with ID 3

```
Сделать команду Скопировать форму в окне Редактор форм.

```

Reported by `gs1994` on 2006-11-07 12:57:03

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2006-11-07 12:58:40

**Comment by gsbelarus** [comment]
Reported by `alexandra.gsoftware` on 2006-12-06 14:03:16
- **Labels added**: GedeminExe

**Comment by gsbelarus** [comment]
Reported by `sunnycreature` on 2008-03-06 10:13:12

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2015-06-29 13:10:40
- **Labels added**: Usability
- **Labels removed**: Forms

**Comment by gsbelarus** [comment]
```
а она нужна? Можно текст dfm скопировать...
```

Reported by `alexandra.gsoftware` on 2015-06-29 13:59:27

**Comment by NikolayUkleyko** [comment]
По-моему копирования **DFM как текста** достаточно.
  Решайте, закрыть данную тему или нет ?
