### ISSUE TITLE
Валютное платежной поручение.

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3032]
Originally reported on Google Code with ID 3032

```
Столкнулись с тем что при экспорте выгружаются не все данные.Да и в документе ввода
отсутвует возможность их внести.
Поэтому  приходится в клиент-банке  после импорта донабирать информацию.
Хорошо бы в гедемине иметь форму ввода информации идентичную клиент- банковской.
В приложеном файле формат для импорта в клиент-банк


```

Reported by `PogoSG` on 2013-02-08 08:23:54

<hr>
- _Attachment: [Формат для импорта (валюта).doc](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3032/comment-0/Формат для импорта %28валюта%29.doc)_

**Comment by gsbelarus** [comment]
```
подскажите почему мои новые собщения получаются с   Status:Accepted
```

Reported by `PogoSG` on 2013-02-08 08:28:57

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2013-02-19 15:07:24
- **Labels added**: Type-Defect, Priority-Medium, Bank

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
