### ISSUE TITLE
Автообновление в виде сервиса

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3043]
Originally reported on Google Code with ID 3043

```
добрый день!

неплохо бы было сделать автообновление в виде сервиса.
невсегда есть возможность или не всегда это удобно запускать Гедемин на сервере чтобы
он подтянул абновы ...

спасибо.
```

Reported by `poit2008.moved@tut.by` on 2013-02-25 11:58:54

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2013-02-28 11:01:19
- **Labels added**: Type-Enhancement, Priority-Low, GedeminEXE

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
