### ISSUE TITLE
Предустановленная форма ЖО

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3060]
Originally reported on Google Code with ID 3060

```
Есть возможность сохранить настроенную форму ЖО в виде конфигурации и пользоваться ей
в дальнейшем. Ситуация. Есть Холдинг. В холдинге настроили и сохранили конфигурацию
ЖО. Потом выбрали одну из компаний холдинга и выбрали эту сохраненную конфигурацию.
В итоге ЖО построился по ВСЕМУ холдингу, хотя текущей рабочей компанией он не является.
Так не годится. Как-то надо анализировать рабочую компанию, и если текущая компания
- не холдинг, а в сохраненной конфигурации - холдинг, то менять там компанию на рабочую.
```

Reported by `kovli.gs` on 2013-03-18 13:54:35

**Comment by gsbelarus** [comment]
```
Сделайте отдельную конфигурацию без рабочей компании, а если кому-то нельзя смотреть
холдинг настройте права доступа.
```

Reported by `mikleshoihet` on 2013-03-18 14:09:44

**Comment by gsbelarus** [comment]
```
Про конфигурацию без рабочей компании понятно. А на что настроить права доступа? На
конфигурацию ЖО?
```

Reported by `kovli.gs` on 2013-03-18 15:13:09

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2013-03-20 06:21:40
- **Labels added**: Type-Other, Priority-Medium, GedeminEXE, Accountancy, Component-UI

**Comment by gsbelarus** [comment]
```
Может в конфигурацию вообще не сохранять компанию? Т.е. выбрали конфигурацию, вы брали
компанию в параметрах ЖО и построили?
```

Reported by `gs1994` on 2013-11-19 14:39:22

**Comment by gsbelarus** [comment]
```
Я - за такое решение. Весьма разумно.
```

Reported by `kovli.gs` on 2013-11-20 12:09:59

**Comment by NikolayUkleyko** [comment]
В перечень доступных аналитических признаков добавлен служебный реквизит **Рабочая компания**.
Сохранение в конфигурацию должно работать корректно.

@MIchaelShoihet , Владимир Иванович, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
