### ISSUE TITLE
Доработка секций

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3237]
Originally reported on Google Code with ID 3237

```
Создание возможности пробивать на секции. ФР Спарк 115. В частности для клиента Арткук
ЧТУП
```

Reported by `dgromovenko.DG` on 2013-09-23 08:01:48

<hr>
- _Attachment: [Техническое задание.doc](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3237/comment-0/Техническое задание.doc)_

**Comment by gsbelarus** [comment]
Reported by `stasgm` on 2013-09-23 10:41:13
- **Status changed**: `Started`

**Comment by stasgm** [comment]
Неактуально.
