### ISSUE TITLE
Доработка

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3238]
Originally reported on Google Code with ID 3238

```
Доработка для ЧТУП АртКук, пивная "Пиуняры". Тех задание во вложении.
```

Reported by `dgromovenko.DG` on 2013-10-01 08:40:55

<hr>
- _Attachment: [Техническое задание.doc](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3238/comment-0/Техническое задание.doc)_

**Comment by gsbelarus** [comment]
```
Задача на первую часть №3237, еще доработать секции (3 пункт в данном задании)
```

Reported by `dgromovenko.DG` on 2013-10-01 08:48:01

**Comment by gsbelarus** [comment]
Reported by `dgromovenko.DG` on 2013-10-01 09:43:14

**Comment by stasgm** [comment]
Неактуально.
