### ISSUE TITLE
Логотип, счет

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3257]
Originally reported on Google Code with ID 3257

```
В новую версию: 
Переделать шаблон финального счета на fastreport, в частности, чтобы можно было вставлять
логотип как картинку
```

Reported by `dgromovenko.DG` on 2013-10-31 12:45:35

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2013-11-06 13:26:02
- **Labels added**: Type-Task, Priority-Medium

**Comment by stasgm** [comment]
Неактуально.
