### ISSUE TITLE
Анализ остатков склада

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#327]
Originally reported on Google Code with ID 327

```
В торговле есть аналитический отчет "Анализ остатков склада". Это один из
главных элементов подсистемы "Управление закупками" (если позиционировать
(или развивать) Гедымин, как ERP-систему, а  "Торговлю и склад", как
систему "Управление торговлей"). Отчетом пользуются достаточно редко, так
как не каждый разберется с его параметрами.
Наиболее "непонятным" параметром является "Критичный период". Если я
правильно понял его смысл - это промежуток времени (в днях) через который
ожидается поступление товара (отсчет идет от текущей даты).  Наверное, было
бы понятнее, если бы вместо указанного параметра был параметр "Дата
ожидаемого поступления", а в функции расчета заказа критичный период
рассчитывался бы как разница между "Датой ожидаемого поступления" и текущей
датой.
Кроме того, при расчете заказа не учитывается зарезервированный товар (т.е.
не учитываются заявки покупателей на товар - расход товара по
счетам-фактурам). Нужно добавить логический параметр "С учетом
счетов-фактур" и, соответственно, учитывать или нет в расходе счета-фактуры.

P.S. В материальном складе тоже есть анализ остатков. Только там не
выписываются счета-фактуры.
```

Reported by `danilchyk` on 2007-02-12 16:08:26

**Comment by gsbelarus** [comment]
```
Также не было бы хорошо добавить параметром выбор товарных групп, по которым будет
проводиться анализ.
```

Reported by `danilchyk` on 2007-02-13 09:43:59
- **Labels added**: Type-Enhancement
- **Labels removed**: Type-Defect

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-03-19 16:12:09
- **Labels added**: Depot
- **Labels removed**: Торговля

**Comment by NikolayUkleyko** [comment]
@yoannawx очень интересуется, а можно ли в параметры формирования добавить реквизит **Группа ТМЦ** ?
@alexandra-gsoftware , что скажешь ?

**Comment by alexandra-gsoftware** [comment]
Это не та штука, которую мы с Жанной  переделывали?

**Comment by NikolayUkleyko** [comment]
> Это не та штука, которую мы с Жанной переделывали?

Да, все верно, @alexandra-gsoftware .
Жанна плотно работает с формой для торговли:
**_Исследователь / Торговля / Отчеты по торговому складу / Анализ остатков склада._**

Однако, есть аналогичная форма и для материального склада:
**_Исследователь / Материальный склад / Отчеты по складу / Анализ остатков материального склада._**

Дополнительный параметр **Группа ТМЦ** (выбор из множества, не обязательный для заполнения) актуален для двух форм.
По возможности предусмотреть отображение групп ТМЦ в гриде рассматриваемых форм.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@alexandra-gsoftware @yoannawx

**Comment by NikolayUkleyko** [comment]
Close.
