### ISSUE TITLE
Банковские документы.

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3287]
Originally reported on Google Code with ID 3287

```
Для импорта документов (поручение и требование)в клиент-банк («BS-CLIENT») должны быть
заполнены все необходимые поля.
Однако в Гедемине они отсутствуют.

В приложенных скринах все видно.



```

Reported by `PogoSG` on 2014-01-08 07:15:21

<hr>
- _Attachment: [klbankplpr.JPG](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3287/comment-0/klbankplpr.JPG)_
- _Attachment: [gedeminplpr.JPG](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3287/comment-0/gedeminplpr.JPG)_
- _Attachment: [klbankptr.JPG](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3287/comment-0/klbankptr.JPG)_
- _Attachment: [gedeminpltr.JPG](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3287/comment-0/gedeminpltr.JPG)_

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-01-13 10:57:25
- **Labels added**: Type-Enhancement, Priority-Medium, Bank, Gorodok

**Comment by gsbelarus** [comment]
```
Регистрационный номер сделки - это реквизит валютного платежного поручения, и в Гедымине
он есть (в валютном платежном поручении).
```

Reported by `danilchyk` on 2014-01-16 07:43:41

**Comment by gsbelarus** [comment]
```
Так и в рублевом платёжном поручении тоже нужен.А его нет.
А с  не достающими полями требования рублевого как быть?  


```

Reported by `PogoSG` on 2014-01-21 13:01:03

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
