### ISSUE TITLE
  Доработка Мастера установок. Галка "Колонка отображается".

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3299]
Originally reported on Google Code with ID 3299

```

  Добавив новое поле в документ, переходим к визуальной настройке документа. Вызываем
Мастер установок > Колонки. Колонка нового поля будет расположена в самом низу. Ставим
галку "Колонка отображается". Тут же необходимо поменять наименование заглавия колонки,
например, с "Наименование" на "Клиент". Но !!! Проставив галку "Колонка отображается",
поле "Заглавие колонки" не активно ! Приходится выбрать другую колонку, а затем текущую
и тогда, поле "Заглавие колонки" станет активным. Вводим наименование.
  ТАКОГО БЫТЬ НЕ ДОЛЖНО !!!
  При простановке галки "Колонка отображается" поле "Заглавие колонки" должно стать
активным сразу же (без выбирания других колонок).

```

Reported by `NikolayUkleyko` on 2014-01-21 15:24:24

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2014-01-21 15:30:48

<hr>
- _Attachment: мастер установок - Галка Колонка отображается.png<br>![мастер установок - Галка Колонка отображается.png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3299/comment-1/мастер установок - Галка Колонка отображается.png)_

**Comment by gsbelarus** [comment]
```
И еще. Нельзя ли для числовых колонок сразу установить режим выравнивания к правой части.
```

Reported by `kovli.gs` on 2014-01-22 12:59:11

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-01-23 11:02:51
- **Labels added**: Type-Defect, Priority-Medium, GedeminEXE, Grid
- **Labels removed**: Etalon

**Comment by gsbelarus** [comment]
```

  Скажите, пожалуйста, по данной теме что-то дорабатывали ?

```

Reported by `NikolayUkleyko` on 2014-03-14 14:19:38

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
