### ISSUE TITLE
  Доработка Мастера установок. Ширина колонки.

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3305]
Originally reported on Google Code with ID 3305

```

  Встречаются ситуации, когда реальная ширина колонки больше, чем значение, указанное
в Мастере установок > Колонки > Свойства колонки > Ширина колонки.
  Приходиться перебивать значение в поле Ширина колонки.
  Такого быть не должно !

```

Reported by `NikolayUkleyko` on 2014-01-28 14:36:04

<hr>
- _Attachment: Мастер установок. Ширина колонки.png<br>![Мастер установок. Ширина колонки.png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3305/comment-0/Мастер установок. Ширина колонки.png)_

**Comment by gsbelarus** [comment]
```
Ширина колонки изначально берется из параметров поля таблицы. Проектировщик БД должен
устанавливать там подходящее значение. Или я что-то не то понимаю под словом "перебивать".
если же речь идет о том, чтобы прочитать все данные из бд и по ним выставить ширину,
то сразу отметаем.
```

Reported by `gs1994` on 2014-01-28 14:57:15

**Comment by gsbelarus** [comment]
```

  На практике так.
  Визуально ширина колонки более 200. В Мастере установок значение ширины колонки 10.
Приходиться перебить такое значение. При этом снята галка "Растягивать колонки по ширине
таблицы".
  Данный вопрос возник из-за невозможности изменения ширины колонки непосредственно
на форме документа (с помощью появляющейся стрелки).

```

Reported by `NikolayUkleyko` on 2014-01-29 10:39:56

**Comment by gsbelarus** [comment]
```
если это последняя колонка на экране и ее ширина больше ширины экрана, то так работает
грид. Так запрограммировано компанией Борланд в 1999 году.
```

Reported by `gs1994` on 2014-01-29 10:41:27

**Comment by gsbelarus** [comment]
```

  Об этом и шла речь.)

```

Reported by `NikolayUkleyko` on 2014-01-29 10:55:02
- **Status changed**: `Invalid`

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2014-01-29 10:55:18
- **Status changed**: `New`

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-02-03 10:04:52
- **Labels added**: Type-Enhancement, Priority-Medium, Grid, GedeminEXE
- **Labels removed**: Etalon

**Comment by NikolayUkleyko** [comment]
Если, по данному вопросу новостей нет, то, пожалуйста, закройте данную тему.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
