### ISSUE TITLE
Скорость расчета итогового начисления

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3332]
Originally reported on Google Code with ID 3332

```
Пришло время серьезно задуматься над ускорением итогового расчета. На некоторых клиентских
больших базах это занимает значительное время. Скорость расчета постепенно падает с
каждым итоговым расчетом. Проблема связана с тем, что при пересчете итогового еще по
каждому сотруднику рассчитывается сальдо на начало ("лопатятся" все обороты по сотруднику
с начала запуска зарплаты).

Возможно стоит попробовать сальдо на начало месяца из итогового предыдущего? Или каким-то
еще образом, но делать что-то определенно надо.

```

Reported by `roberto1813` on 2014-03-17 09:05:52

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-03-17 09:29:19

**Comment by gsbelarus** [comment]
```
надо смотреть на чем именно тормозит, может сальдо и не виновато
```

Reported by `alexandra.gsoftware` on 2014-03-17 10:04:21

**Comment by gsbelarus** [comment]
```
Возможно что-то по этому вопросу было поднято вот тут 
http://code.google.com/p/gedemin/issues/detail?id=2573&q=label%3DWage&colspec=ID%20Opened%20Closed%20Type%20Status%20Priority%20Reporter%20Owner%20Summary
```

Reported by `roberto1813` on 2014-03-17 12:32:06

**Comment by gsbelarus** [comment]
```
Issue 2573 has been merged into this issue.
```

Reported by `roberto1813` on 2014-03-17 12:44:01

**Comment by gsbelarus** [comment]
```
Сальдо можно и переделал, только смотри, сейчас если был вдруг какой косяк, только пересчёт
тебе покажет, что например расчитали оклад, потом сделали итоговый, а потом удалили
расчёт оклада и ничего не пересчитали. Если же не пересчитывать, то фиг такое отследишь.
С другой стороны за предыдущий месяц взять конечное сальдо и использовать как начальное
- очень просто сделать
```

Reported by `Alexander.GoldenSoft` on 2014-03-17 17:51:27

**Comment by gsbelarus** [comment]
```
Но проблема в базах для МК для рассчёта ЗП не в этом
```

Reported by `Alexander.GoldenSoft` on 2014-03-17 17:52:33

**Comment by gsbelarus** [comment]
```
А в чем там может быть вероятная проблема?
```

Reported by `roberto1813` on 2014-03-18 06:48:59

**Comment by gsbelarus** [comment]
```
1. Большое кадровое движение
2. Поиск начислений которые надо рассчитать
3. Всевозможные расчеты сальдо.
```

Reported by `Alexander.GoldenSoft` on 2014-03-18 07:00:33

**Comment by gsbelarus** [comment]
```
То, что там движение большое  - это да, как и то, что там очень много документов по
которым считается зп. 
```

Reported by `roberto1813` on 2014-03-18 07:18:00

**Comment by gsbelarus** [comment]
```
Опять поднимаю вопрос по ускорением итогового расчета. На примере одного предприятия
за месяц расчет увеличился с 1 часа 30 минут до 3-х часов (полгода назад он длился
40 мин). А есть предприятия где он длится более 4-х часов. Надо срочно что-то решать.
```

Reported by `WitaliaS` on 2014-06-09 06:36:14
- **Labels added**: Priority-Critical
- **Labels removed**: Priority-High

**Comment by gsbelarus** [comment]
```
Запустить расчёт и какой-нибудь FBScaner или trace или другой логгер SQL запросов. И
посмотреть, что чаще всего вызывается, что дольше всего выполняется и тогда будет ясна
картина. А сейчас только слова, что медленно, а что именно медленно - непонятно
```

Reported by `Alexander.GoldenSoft` on 2014-06-09 06:43:43

**Comment by NikolayUkleyko** [comment]
Пожалуйста, подскажите, актуальна ли данная тема ?

**Comment by YRozmysl** [comment]
нет, хотя очень хотелось бы , на мелких и средних предприятиях, это не видно, а вот на крупных -это уже не утаишь, как-то вот так.

**Comment by YRozmysl** [comment]
Я ошибся, конечно же вопрос очень актуальный. Подумал, что Коля спросил, решена ли проблема. Она очень актуальна. И он не решен.

**Comment by NikolayUkleyko** [comment]
Юрий упоминал, что **долгоиграющее** итоговое начисление имеет место быть из-за того, что каждый раз за прошлые периоды пересчитываются данные по всем видам начислений/удержаний. Полученные данные необходимы для выполнения других расчетов.
  Предлагаю выполнить доработки, чтобы каждый раз при расчете итогового начисления не пересчитывались за прошлые периоды данные по всем видам начислений/удержаний, а только по необходимым.
  Мое представление данной проблемы.
  Пусть, Юрий, четко распишет план действий.

**Comment by YRozmysl** [comment]
Чтобы расписывать план, тут надо выяснить проблему  точно  из -за чего  замедление,  я лишь высказал предположение.

**Comment by NikolayUkleyko** [comment]
Затратив время на данную доработку, выйграем его в будущем.

**Comment by YRozmysl** [comment]
это все имеет место там, где есть однодневные наряды, число которых может в месяц может доходить и до 1.5 тыс. И, когда идет итоговое перелопачивается много нарядов. Если это в принципе нельзя ускорить за счет оптимизации кода, а только за счет сервера, то надо однозначно это выяснить. И искать другие варианты. 
.

**Comment by NikolayUkleyko** [comment]
Если, наряды не рассчитываются, то проблемы в скорости итогового начисления нет ?  
  Надо качественный подход (код :bulb:), а не количественный (сервер :truck:).
  Тогда, будет :running::running::running::running::running: ускорение.

**Comment by YRozmysl** [comment]
дело в том, что  у нас все большие клиенты ведут однодневные наряды, поэтому проблема заметна в скорости в первую очередь у их. Там где таких нарядов нет - это вообще не заметно, но это организации до 300 человек, а это не показатель. Поэтому вопрос надо решать.

**Comment by YRozmysl** [comment]
И снова, здравствуйте. Надо решать вопрос со скоростью расчета итогового. Постоянно стоит этот вопрос на больших предприятиях,где и стоит зп,  люди спрашивали сначала постоянно, а потом просто смирились, но это в корне неправильно. Так и теперь тоже самое на БМКК, просто будем иметь "бледный вид".

**Comment by alexandra-gsoftware** [comment]
т.е. тормозит там, где не ведутся всяческие "сборные" бригадные, а много однодневных?

**Comment by YRozmysl** [comment]
однодневных  порядка 1 тыс ежемесячно

**Comment by alexandra-gsoftware** [comment]
а если есть и однодневные, и сборные, и зп считается только по сборным, тогда тормозит?

**Comment by YRozmysl** [comment]
просто сборный наряд - это тоже такой наряд, весьма специфический,  по своей сути, давно еще, мы просто собирали  их, но там это делалось совершенно из за других соображения, тогда это делалось  не для того, чтобы увеличить скорость. На ММК, например, этого не делают.

**Comment by alexandra-gsoftware** [comment]
нет, мне просто интересно: скорость увеличится, если вести сборные наряды и считать только по ним, или нет? Или их просто уже нигде не ведут?

**Comment by YRozmysl** [comment]
но по итогу, получилось, что скорость такого ведения зарплаты со сборными нарядами выше чем с однодневными нарядами. Но, просто, намеренно, собирать сборный наряд, для того, чтобы увеличить скорость не верно, и самое главное, бухгалтер не должен собирать наряд, для того, чтобы увелсить скорость

**Comment by YRozmysl** [comment]
такое ведение есть на бро и гмк, более нигде. Пока по крайней мере не возникало такой необходимости.

**Comment by alexandra-gsoftware** [comment]
> > > Но, просто, намеренно, собирать сборный наряд,

нене, я не предлагаю их собирать. Я обдумываю проблему

**Comment by alexandra-gsoftware** [comment]
Я думаю, что проблема связана с журналом начислений (это пользовательский документ без позиций). Он заполняется при расчете как бизнес-объект (а не запросами, как другие вспомогательные таблицы), чтобы создались проводки. По человеку на один бригадный порядка 15 записей может идти... А бригадных - один на рабочий день (или иногда два) на каждого сотрудника. У журнала этого сабсет "ByID", чтобы не тянулись все записи при открытии, но, видимо, все равно тормозит. У кого какие идеи?
@MIchaelShoihet , что думаете?

**Comment by YRozmysl** [comment]
А еще из бригадного может браться, например, не только сдельный заработок, а  вредность,  ночные  и т.д. и т.п и тогда получается 15X2, 15X3 ...

**Comment by alexandra-gsoftware** [comment]
я с ночными считала. 15 (разных начислений на один бригадный) \* 25 (бригадных по человеку в месяц) \* 2500 (человек на предприятии), как-то так

**Comment by YRozmysl** [comment]
ааа, ну теоретически так

**Comment by gsbelarus** [comment]
У нас практически готов профайлер. Завтра будет презентация. Начать надо с того, что на сервере у нас запустить полный расчет с профайлером и посмотреть собранную статистику.

(главное чтобы в это время этот сервер никто не дергал)

Правило парето подсказывает нам, что 20% кода/запросов занимают 80% времени. Выделим ключевые по производительности моменты и оптимизируем их.

Если эффект будет недостаточен, то будем думать.

**Comment by arthur-latunov** [comment]
@alexandra-gsoftware однозначно тормозит `call wg_EmployeeCharge.AddChargeReg(...)`, проверено

**Comment by alexandra-gsoftware** [comment]
спасибо @arthur-latunov, я так и думала. Но что с этим делать - вопрос(

**Comment by YRozmysl** [comment]
Ситуация становится уже такой, что бухгалтера предприятий просят запустить пересчет вечером, чтобы утром увидеть пересчитанный месяц. Причем на том же БМКК, где есть сборные наряды из однодневных (если бы рассчитывали без сборных..я лучше вообще промолчу) расчет идет 2  часа.  Ведь уже есть и профайлер, может уже наконец-то что-то попробуем сделать?

**Comment by MIchaelShoihet** [comment]
Профайлер есть. Запустили пересчет. Сохранили файл из профайлера. Можно анализировать.

**Comment by MIchaelShoihet** [comment]
Желательно именно на большой базе, на хорошем сервере. Что бы увидеть реальные задержки.

**Comment by YRozmysl** [comment]
Буду сбрасывать сюда логи профайлов с разных больших баз, где запускается профайлер.
 **ГМК**. Среди баз больших предприятий - самый относительно быстрый расчет.
   Выделен отдельный сервер. Установлены SSD. Кроме зп и путевых там нет ничего.  Количество пользователей 20-25. Пересчет запускался, когда пользователей не было. 
   **Характеристики сервера:**
 Название компьютера  = GGEDEMIN
 IP адрес             = 192.168.0.150
 ОЗУ всего            = 4 084 Мб
 ОЗУ свободно         = 1 587 Мб
 Версия ОС            = Windows Server (R) 2008 Enterprise

  **Характеристика ПК на котором запускался пересчет:**
 Название компьютера  = REZ-TERM
 IP адрес             = 192.168.0.205
 ОЗУ всего            = 3 071 Мб
 ОЗУ свободно         = 2 117 Мб
 Версия ОС            = Microsoft Windows XP, Service Pack 3

   Время расчета месяца  - 1:15:00, 
   Количество позиций(людей) в итоговом начислений - 1600 
   Сдельный заработок собирается в сборный наряд.

**Comment by YRozmysl** [comment]
[profile_GMK.zip](https://github.com/GoldenSoftwareLtd/gedemin/files/356457/profile_GMK.zip)

**Comment by gsbelarus** [comment]
4 гб памяти на сервере это не смешно. Для начала надо увеличить память. До
32 гб хотя бы. И не указывайте свободную память. Сто раз это обсуждалось.
Цифры из таск менеджера ни о чем не говорят.

В остальном, надо брать лог и смотреть в первую очередь запросы.

**Comment by YRozmysl** [comment]
Конечно не смешно. На березе 64 гб и в 2 раза дольше расчет.

15 июля 2016 г., 16:46 пользователь Andrej Kirejeŭ <notifications@github.com

> написал:
> 
> 4 гб памяти на сервере это не смешно. Для начала надо увеличить память. До
> 32 гб хотя бы. И не указывайте свободную память. Сто раз это обсуждалось.
> Цифры из таск менеджера ни о чем не говорят.
> 
> В остальном, надо брать лог и смотреть в первую очередь запросы.

**Comment by NikolayUkleyko** [comment]
Неужели на Витебск БПФ шустро выполняется расчет ?

**Comment by YRozmysl** [comment]
Часа 4 точно,  в след расчет будет и от их профайл для сравнения.

**Comment by MIchaelShoihet** [comment]
Оно нигде быстро не работает... И конечно с этим надо разбираться. При этом естественно, что на более мощном железе, правильно настроенном, расчет будет идти быстрее

**Comment by YRozmysl** [comment]
Это вопрос НОМЕР ОДИН среди всех. Пусть еще повисит

**Comment by YRozmysl** [comment]
Эту тему можно закрыть, тут устаревшая информация, едва ли она будет полезна сейчас
