### ISSUE TITLE
Установка ПИ

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3337]
Originally reported on Google Code with ID 3337

```
Возможно ли добавить кнопку для выделения всех различий при повторной установке, а кликать
на каждую, так как таких позиций может быть много. Пояснения 
```

Reported by `roberto1813` on 2014-03-18 10:48:40

<hr>
- _Attachment: [NS.jpg](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3337/comment-0/NS.jpg)_

**Comment by gsbelarus** [comment]
Reported by `roberto1813` on 2014-03-18 10:49:36

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-03-18 11:33:23
- **Labels added**: GedeminEXE, Namespace
- **Labels removed**: GedeminEXENamespace

**Comment by gsbelarus** [comment]
```

  Было бы хорошо предусмотреть возможность выбора сохранения не только текущей записи,
но и всех остальных. Будет удобнее. Не так ли ?

```

Reported by `NikolayUkleyko` on 2014-04-22 13:23:11

**Comment by gsbelarus** [comment]
```
Возможно.
```

Reported by `roberto1813` on 2014-04-22 13:33:43

**Comment by NikolayUkleyko** [comment]
По данной теме вроде бы, как выполнены доработки.
  Если, ни у кого нет вопросов, можно закрыть тему.
