### ISSUE TITLE
В Журнале-ордере не удаляется значение в поле отображений для группировки по аналитике

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3419]
Originally reported on Google Code with ID 3419

```

  Исследователь > Бухгалтерия > Журнал-ордер.
  Формруем Журнал-ордер по конфигурации, в которой на закладке "Дополнительно" в блоке
"Поля отображений для группировки по аналитике" в соотвествующем поле выбрано значение.
Если, необходимо на панели инструментов указать другой счет, то Журнал-ордер сформируется
с учетом вышеуказанного поля. Если, необходимо сформировать Журнал-ордер без такого
поля, то его никак не поменяешь. Помогает только закрытие-открытие Жрунала-ордера.
  Можно ли предусмотреть возможность, чтобы в данном случае не закрывать-открывать
Журнал-ордер ?

```

Reported by `NikolayUkleyko` on 2014-08-15 13:39:13

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-08-27 16:06:13
- **Labels added**: Type-Defect, Priority-Medium, GedeminEXE, Accountancy
- **Labels removed**: Gomeltree

**Comment by zholnerovich** [comment]
Либо я не разобрался либо доработка уже выполнена, потому как в диалоговом окне можно выбрать пустое поле

**Comment by NikolayUkleyko** [comment]
Проверено.
Обновлений не выявлено.

@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
Задача сводилась к тому, чтобы при очистке поля **Конфигурация** и/или при задании новых **параметров** при формировании Журнала-ордера не учитывать параметры из уже убранной конфигурации: **Дополнительно / Блок "Поля отображений для группировки по аналитике"**.

Вряд ли это будет правиться.

@gsbelarus , пожалуйста, закройте тему.
