### ISSUE TITLE
Выбор плана счетов в параметрах бухгалтерских отчетов

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3425]
Originally reported on Google Code with ID 3425

```
Сейчас бухгалтерские отчеты строятся только по счетам активного плана счетов организации.
Надо добавить возможность выбора плана счетов в параметрах бухгалтерских отчетов.
```

Reported by `danilchyk` on 2014-08-28 13:19:04

**Comment by gsbelarus** [comment]
```
  Тему про использование дополнительных планов счетов по одной организации я уже поднимал.
http://code.google.com/p/gedemin/issues/detail?id=2731&can=1&q=nikolayukleyko&colspec=ID%20Opened%20Closed%20Type%20Status%20Priority%20Reporter%20Owner%20Summary&start=200
```

Reported by `NikolayUkleyko` on 2014-08-28 14:39:57

**Comment by NikolayUkleyko** [comment]
Необходимо реализовать следующий механизм.
  В параметрах рабочей организации выбрать несколько счетов и один из них сделать активным. При формировании бухгалтерских отчетов предусмотреть возможность выбора счетов из **всех планов счетов, включая и активный**.

Алексей, так ли ? Пожалуйста, подскажи, в каких случаях это будет применимо ?

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.

**Comment by NikolayUkleyko** [comment]
Немного погодя к данной теме еще вернемся.
