### ISSUE TITLE
  После установки настроек и/или ПИ в древовидных справочниках снимается галка "Вложенные уровни".

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3426]
Originally reported on Google Code with ID 3426

```
  Достало, когда после установки настроек и/или ПИ в древовидных справочниках снимается
галка "Вложенные уровни".
  Пример, "План счетов".
  Галка вложенные уровни снимается даже в случае, если установленные настройки и ПИ
не содержали в себе обновления для соответствующего справочника.
```

Reported by `NikolayUkleyko` on 2014-08-29 14:25:21

<hr>
- _Attachment: Рис. 1. Галка 'Вложенные уровни'..png<br>![Рис. 1. Галка 'Вложенные уровни'..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3426/comment-0/Рис. 1. Галка 'Вложенные уровни'..png)_

**Comment by gsbelarus** [comment]
```
  Эта хрень уже давно наблюдается.
```

Reported by `NikolayUkleyko` on 2014-09-03 08:24:22

**Comment by gsbelarus** [comment]
```
Значение параметра находится в хранилище пользователя, в ветке для формы. Имя параметра
ShSG.

Я просканировал наши типовые пространства имен -- в файлах нигде нет такого параметра.

Нужен пример, когда что-то перезаписывается.

В настройках в любой случае уже смотреть не будем. Править код там уже нельзя.
```

Reported by `gs1994` on 2014-09-07 11:55:08
- **Labels added**: Type-Defect, Priority-Medium, GedeminEXE
- **Labels removed**: SmorgonKHP, BMKK

**Comment by gsbelarus** [comment]
```
  Пример. Исследователь > Бухгалтерия > План счетов. Устанавливаю настройку, содержающую
отчет для плана счетов. После установки данной настройки галка "Вложенные уровни" снята.
Возникают вопросы:
1. Осуществляется установка отчета, а не хранилища. Почему хранилище меняется ?
2. Снятие галки происходит и в других справочниках: Клиенты, Организации и т. д.
```

Reported by `NikolayUkleyko` on 2014-09-08 13:02:15

**Comment by gsbelarus** [comment]
```
Ставить через ПИ. Код настроек вряд ли кто-то будет уже править.
```

Reported by `gs1994` on 2014-09-08 13:05:21

**Comment by gsbelarus** [comment]
```
  Закрываем тему.
```

Reported by `NikolayUkleyko` on 2014-09-15 06:26:40
- **Status changed**: `Fixed`

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2015-01-20 09:36:17

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2015-01-20 09:44:07
- **Status changed**: `Accepted`

**Comment by gsbelarus** [comment]
Reported by `PZholnerovich` on 2015-01-26 12:55:44
- **Status changed**: `Fixed`

**Comment by gsbelarus** [comment]
```
  По данной теме выполнена доработка https://code.google.com/p/gedemin/source/detail?r=1965.
Пожалуйста, закиньте ее в http://gsbelarus.com/pw/downloads/?d=7117.

```

Reported by `NikolayUkleyko` on 2015-02-24 06:50:24
- **Status changed**: `Accepted`

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
