### ISSUE TITLE
  Необходимо доработать окно выбора из множества.

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3442]
Originally reported on Google Code with ID 3442

```
  Работать с таким типом параметра, как "Выбор из множества" не совсем удобно по следующим
причинам:
1. Окно выбора очень маленькое.
В случае работы с вложенными уровнями не всегда видно найденное значение (обрезается).
Необходимо увеличить окно.
2. Поcле того, как ввели текст в поле "Наименование" и нажатии на клавишу "Enter",
происходит выход из данного окна.
Сделайте так, чтобы в данной ситуации срабатывала кнопка "OK".
3. Пользователи не всегда могут все найти.
Да, есть такая кнопка "Вывести следующие 250 наименований". Но постоянно использовать
данную кнопку не очень удобно, да и забыть можно про нее.
Сделайте так, чтобы автоматически отображались все записи. Удалите кнопку "Вывести
следующие 250 наименований".
```

Reported by `NikolayUkleyko` on 2014-09-17 12:19:18

**Comment by gsbelarus** [comment]
```
Согласен, что окно не удобное, но может когда-нибудь наступит светлое будущее и мы его
совсем переделаем, сейчас возможно переделаем 1 и 2, а 3 - посмотрим как будет получаться,
оно было добавлено специально, так как большое кол-во данных может подвесить данное
окно.
```

Reported by `mikleshoihet` on 2014-09-17 12:29:04

**Comment by gsbelarus** [comment]
```
  Полностью с Вами согласен.
```

Reported by `NikolayUkleyko` on 2014-09-17 13:07:18

**Comment by gsbelarus** [comment]
```
  Обнаружена еще одна недоработка данной формы.
  4. Выбрав значения в данной форме, закрываем отчет. В результате выбранные значения
не сохраняться в форме. 
  Это не удобно. Пожалуйста, предусмотрите такую возможность.
```

Reported by `NikolayUkleyko` on 2014-09-22 13:57:05

**Comment by gsbelarus** [comment]
```
Если нажать Отмена то никакие параметры не сохраняться такова логика работы окна любого,
если нажмешь OK то все сохранится, ведь программа не знает вдруг ты случайно не то
выбрал и поэтому нажал Отмена

```

Reported by `mikleshoihet` on 2014-09-22 14:04:00

**Comment by gsbelarus** [comment]
```
  По пункту № 4 с Вами соглашусь.
```

Reported by `NikolayUkleyko` on 2014-09-23 06:30:19

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-09-26 12:45:20
- **Labels added**: Type-Enhancement, Priority-Medium, GedeminEXE, Usability, Component-UI
- **Labels removed**: BMKK, Gomeltree

**Comment by gsbelarus** [comment]
```
  С окном выбора из множества приходится часто работать. Хорошо бы его усовершенствовать.

```

Reported by `NikolayUkleyko` on 2014-10-30 14:47:06

**Comment by gsbelarus** [comment]
```
  Скажите, пожалуйста, по данной теме есть новости ?

```

Reported by `NikolayUkleyko` on 2014-11-12 14:27:55

**Comment by gsbelarus** [comment]
```
2. Поcле того, как ввели текст в поле "Наименование" и нажатии на клавишу "Enter", происходит
выход из данного окна.
Сделайте так, чтобы в данной ситуации срабатывала кнопка "OK".

Очень хочется чтобы доработали. 
```

Reported by `M.Burakina` on 2014-12-08 12:52:26

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2015-01-16 06:50:46

**Comment by gsbelarus** [comment]
```
  Я чего-то не понимаю. :-(
  Была выполнена некоторая доработка по теме http://code.google.com/p/gedemin/source/detail?r=1955
  Почему она не включена в gedemin.exe, расположенный на http://gsbelarus.com/pw/downloads/?d=7117
???
  Неужели тяжело решить вопрос с клавишей Enter ? 2. Поcле того, как ввели текст в
поле "Наименование" и нажатии на клавишу "Enter", происходит выход из данного окна.
Сделайте так, чтобы в данной ситуации срабатывала кнопка "OK".
  Опять 25.

```

Reported by `NikolayUkleyko` on 2015-02-20 10:19:19

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2015-03-25 13:07:15

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.

@ShlTanya , пожалуйста, предусмотри следующее:

1. При открытии формы по умолчанию позиционирование курсора в поле **Наименование**.

2. Не отображать выбранные записи в блоке доступных записей.

3. В заголовке каждого блока дописать **Доступные записи**, **Выбранные записи**.

Так будет удобнее работать с формой выбора из множества.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри пункты:
1, 3 - если, нет противоречий, то сделать;
2 - сделано.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, предусмотри блокировку на ввод текста в параметре **Условие**.
Необходимо предусмотреть только выбор варианта из выпадающего списка:
![image](https://user-images.githubusercontent.com/11497453/150369924-2ff837ff-a2fa-45e5-8204-c5a8eab6e703.png)
![image](https://user-images.githubusercontent.com/11497453/150369947-5380a6fe-f343-4f7a-a0c8-e364055dd419.png)

**Comment by ShlTanya** [comment]
Доработано пункты 1,3

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо !

-----

При нажатии на кнопку **Все** программа отображает сообщение об ошибке:
![image](https://user-images.githubusercontent.com/11497453/152318636-62b37bdf-4228-4c6c-88af-cb417469036f.png)

**Comment by ShlTanya** [comment]
Пересмотрела форму. Что сделано: 
1. Задание 4040 - Простые деревья отображаются в виде дерева.
2. Для интервального дерева была несогласованность вида между доступными и выбранными данными. Деревья отображались по-разному. Привела к виду выбранных данных (и данных, которые отображаются при поиске).
3. Добавлен перенос данных по нажатию на кнопку Пробел.
4. Добавлены кнопки полного раскрытия и закрытия дерева.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , большое спасибо !
Проверяю.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо !

По пункту **3** необходимо убрать автоматический переход на верхний уровень при поиске по записи.
Пример, таблица AC_ACCOUNT.
На таблице GD_CONTACT такого нет.

**Comment by NikolayUkleyko** [comment]
Дополнительно к существующему вопросу.
@ShlTanya , пожалуйста, предусмотри возможность отображения количества выбранных записей.

**Comment by NikolayUkleyko** [comment]
По данной теме были выполнены доработки.
Выше изложены предложения.
Внесите правки или закройте тему.

**Comment by ShlTanya** [comment]
Добавлено количество выбранных записей

**Comment by NikolayUkleyko** [comment]
> _По пункту 3 необходимо убрать автоматический переход на верхний уровень при поиске по записи.
Пример, таблица AC_ACCOUNT.
На таблице GD_CONTACT такого нет._

@ShlTanya , как быть с таким ?

**Comment by ShlTanya** [comment]
Я немного не понимаю.. про переход на верхний уровень при поиске записи. Можно точнее алгоритм действий узнать.

**Comment by NikolayUkleyko** [comment]
Пример, 
_Исследователь → Материальный склад → Отчеты по складу → Оборотная ведомость (счета и субсчета, цена учета)._

1. Параметр **Счета**. В строке поиска (Наименование) указываем счет **"10."** и нажимаем кнопку **Поиск**.
2. При помощи пробела выбираем необходимые счета. При выборе мышкой работает корректно.
3. Курсор не остается на выбранной записи, а автоматические переходит на самый верхний уровень справочника. Если, даже несколько планов счетов, то на самый верхний и будет выполнен переход.

**Comment by ShlTanya** [comment]
Открыла выбор из множества по счетам. Указала поиск. Из доступных записей делаю выбор (и двойным щелчком мыши и кнопкой Пробел). Курсор остается на выбранной записи в окне Доступные записи.

**Comment by NikolayUkleyko** [comment]
Пока данный вопрос неактуален.
@ShlTanya , большое спасибо !
