### ISSUE TITLE
  Удаление складских документов при инвентаризации ТМЦ.

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3445]
Originally reported on Google Code with ID 3445

```
  Пример.
  15.08.2014 г. оприходованы ТМЦ от поставщика.
  31.08.2014 г. отражена инвентаризация ТМЦ.
  Обнаружилось, что приход ТМЦ был ошибочно введен дважды. Необходимо удалить лишний
приход ТМЦ.
  При попытке удаления прихода ТМЦ программа на экране выдает соответствующие сообщение.
Сначала пробуем удалить весь документ (Рис. 1.), а потом - отдельно позиции документа
(Рис. 2.).
  При этом в карточке ТМЦ документ инвентаризации ТМЦ не отражается.
  Пожалуйста, предусмотрите для таких случаев сообщение: "Документ нельзя удалить !
Возможно ТМЦ выбраны в документе инвентаризации ТМЦ" или "Выбранные ТМЦ нельзя удалить
! Возможно они выбраны в документе инвентаризации ТМЦ".
  Мы то разберемся что к чему, а пользователи - нет.
```

Reported by `NikolayUkleyko` on 2014-09-23 14:01:45

<hr>
- _Attachment: Рис. 1. Удаление складских документов при инвентаризации ТМЦ..png<br>![Рис. 1. Удаление складских документов при инвентаризации ТМЦ..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3445/comment-0/Рис. 1. Удаление складских документов при инвентаризации ТМЦ..png)_
- _Attachment: Рис. 2. Удаление складских документов при инвентаризации ТМЦ..png<br>![Рис. 2. Удаление складских документов при инвентаризации ТМЦ..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3445/comment-0/Рис. 2. Удаление складских документов при инвентаризации ТМЦ..png)_

**Comment by gsbelarus** [comment]
```
  Неужели никто не сталкивался с такой ситуацией ?
```

Reported by `NikolayUkleyko` on 2014-09-25 09:06:43

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-09-26 12:43:58
- **Labels added**: Type-Defect, Priority-Medium, Depot, GedeminEXE
- **Labels removed**: Etalon

**Comment by NikolayUkleyko** [comment]
1. Если, в документе инвентаризации отражен **излишек или отклонение вовсе не отражено**, то при попытке удаления такой позиции из приходной накладной программа отобразит окно с сообщением об ошибке:

![2017-06-07_150157](https://user-images.githubusercontent.com/11497453/26877768-9f815ddc-4b93-11e7-8fb8-adcc40c6cf7d.png)

В случае отсутствия отклонения по инвентаризации в карточке ТМЦ документ инвентаризации ТМЦ не отражается.
Можно ли для данной ситуации предусмотреть отображение окна с соответствующим сообщением ?

Например.

#### Документ нельзя удалить !
#### Возможно ТМЦ выбраны в документе инвентаризации ТМЦ.
#### или
#### Выбранные ТМЦ нельзя удалить !
#### Возможно они выбраны в документе инвентаризации ТМЦ.

----

2. Если, в документе инвентаризации отражена **недостача**, то при попытке удаления такой позиции из приходной накладной программа отобразит окно с сообщением об ошибке:

![2017-06-07_150352](https://user-images.githubusercontent.com/11497453/26877786-b0625ba6-4b93-11e7-89b9-55afccce3582.png)

Вопрос: каково предназначение кнопок **Переместить все, Переместить позицию** ?

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , @ShlTanya , пожалуйста, изложите, ваши, точки зрения.

**Comment by MIchaelShoihet** [comment]
На самом деле кроме инвентаризации, это может быть любой документ, который не сформировал движение (документ у которого в позиции кол-во = 0 или отложенный документ).

**Comment by NikolayUkleyko** [comment]
Тогда, напрашивается нормальное сообщение для пользователей.
Например,
#### Выбранные записи удалить нельзя !
#### Возможно удаляемые ТМЦ выбраны в документе у которого в позиции кол-во = 0 или отложенный документ.

Согласитесь, что это куда понятнее для пользователей, чем INV_CARD и/или ID ?
Станет понятно, где и что посмотреть.

@MIchaelShoihet , все же, каково предназначение кнопок **Переместить все, Переместить позицию** ?
Общался с Жанной - она сказала, что никакого эффекта.

**Comment by MIchaelShoihet** [comment]
Согласен. Кнопки Переместить все или переместить позицию подразумевались для того что бы расход который шел по удаляемой позиции переместить на существующий другой остаток. Но сложно определить на какой можно переместить, поэтому она пытается переместить на полностью по признакам совпадающий остаток, а такого обычно нет...

**Comment by NikolayUkleyko** [comment]
>Но сложно определить на какой можно переместить, поэтому она пытается переместить на полностью по признакам совпадающий остаток, а такого обычно нет...

Так, может это скрыть ?

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
