### ISSUE TITLE
Сохранение настроек грида в параметрах журнала ордера

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3452]
Originally reported on Google Code with ID 3452

```
Такое впечатление, что настройки грида привязываются к имени конфигурации ЖО. Поскольку
после переименования слетают.
```

Reported by `gs1994` on 2014-10-01 11:42:07

**Comment by gsbelarus** [comment]
```
  Настройки грида привязываются к конкретной конфигурации Журнала-ордера.
  Не случайно на панели инструментов справа от поля "Конфигурация" есть соответствующие
кнопки:
- Сохранить настройки таблицы в текущую конфигурацию;
- Удалить настройки таблицы из текущей конфигурации.
```

Reported by `NikolayUkleyko` on 2014-10-01 12:52:10

<hr>
- _Attachment: Рис. 1. Журнал-ордер. Сохранение конфигурации..png<br>![Рис. 1. Журнал-ордер. Сохранение конфигурации..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3452/comment-1/Рис. 1. Журнал-ордер. Сохранение конфигурации..png)_

**Comment by gsbelarus** [comment]
```
  Все это имеет силу и для других бухгалтерских отчетов.
```

Reported by `NikolayUkleyko` on 2014-10-01 12:54:47

**Comment by gsbelarus** [comment]
```
Да я знаю к чему они привязываются. Вопрос в том, что если конфигурацию переименовать,
то настройки грида слетают на дефолтные. Были они до этого сохранены или нет.
```

Reported by `gs1994` on 2014-10-01 13:33:32

**Comment by gsbelarus** [comment]
```
  Менял название конфигурации - все в порядке. Настройки грида сохраняются.
```

Reported by `NikolayUkleyko` on 2014-10-01 14:12:07

**Comment by NikolayUkleyko** [comment]
Выявил такую недоработку.
  Для того, чтобы сохранить переименованную конфигурацию и настройки грида не слетели на дефолтные необходимо нажать на кнопку Сохранить настройки таблицы в текущую конфигурацию.
  Если, можно убрать это лишнее действие - хорошо. Нет - так нет.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
