### ISSUE TITLE
Смысл переменной Result в коде, генерируемом конструктором функций

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3458]
Originally reported on Google Code with ID 3458

```
Смысл переменной Result в коде, генерируемом конструктором функций?
```

Reported by `gs1994` on 2014-10-05 14:37:24

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-10-05 14:37:36
- **Labels added**: GedeminEXE

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, подскажите по данной теме. При необходимости внесите коррективы.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
