### ISSUE TITLE
  В приходных накладных различия при редактировании позиций через "F4" и "карандаш".

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3459]
Originally reported on Google Code with ID 3459

```
  В приходных накладных при редактировании (не перевыборе ТМЦ) позиции через "F4" значение
ставки НДС не меняется. Это правильно. 
  При редактировании (не перевыборе ТМЦ) позиции через "карандаш" значение ставки НДС
меняется и все остальные показатели пересчитываются. Это не правильно. Изменение ставки
НДС осуществляется если, даты начала действия налога НДС больше, чем дата документа.
  Казалось бы, какая разница при помощи чего редактировать позицию приходной накладной
? При редактировании ничего пересчитываться не должно.
```

Reported by `NikolayUkleyko` on 2014-10-06 13:07:45

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-10-08 09:51:33
- **Labels added**: Type-Defect, Priority-Medium, Depot
- **Labels removed**: Etalon

**Comment by yoannawx** [comment]
@ShlTanya очень актуально. касается не только ндс, но и торговой надбавки. такое ощущение, что при редактировании через карандаш переподставляется ид товара

**Comment by ShlTanya** [comment]
У меня получилось вот что:
1. Редактирование товара через карандаш и через F4 (выпадающий список скрыт) не изменяют запись.
2. Редактирование товара через F4 (выпадающий список открыт) и просто Tab с открытым выпадающим списком меняют запись. По поводу НДС. В накладную попадали ставки, даты установки которых, меньше даты накладной.

Проверьте, пожалуйста, еще раз ситуацию.

**Comment by stasgm** [comment]
@ShlTanya В документ копируются значения из карточки ТМЦ некоторых полей. Нас интересует ндс и торговая надбавка.
Клиенты, порой, не вносят значения в карточку ТМЦ, а вбивают напрямую в документ.
Потом они редактируют карандашиком, например название товара, и для них ндс\надбавка "слетает". Это мы знаем, что подставляются значения из карточки. Но поступают претензии, что программа затирает значения. Копирование значение из карточки должно идти только при выборе\перевыборе товара, а у нас выходит что простое редактирование карточки вызывает перевыбор товара.

Так что редактирование товара по F4 или карандашику не должно вызывать изменений в текущем документе

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
@yoannawx подтвердила, что проверила.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
