### ISSUE TITLE
При построении карты счета без выбора счета попадают счета из всех планов счетов

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3461]
Originally reported on Google Code with ID 3461

```
А надо бы только из активного.

```

Reported by `gs1994` on 2014-10-09 11:37:32

**Comment by gsbelarus** [comment]
```
  1. В карте счета даже при указании значения в поле "Счета" отображаются записи со
всеми планами счетов.
  2. Все вышесказанное из пункта № 1 имеет силу и по отношению к другим бухгалтерским
отчетам (журнал-ордер, анализ счета и другие).
  3. Тема выбора плана счетов и работы с ними уже поднималась https://code.google.com/p/gedemin/issues/detail?id=2731&can=1&q=nikolayukleyko&colspec=ID%20Opened%20Closed%20Type%20Status%20Priority%20Reporter%20Owner%20Summary&start=200

```

Reported by `NikolayUkleyko` on 2014-10-09 14:56:15

**Comment by zholnerovich** [comment]
Активный план счетов зависит от выбранной компании. А что должно происходить если стоит галка "все компании холдинга"? Какой тогда план счетов считается активным?

**Comment by gsbelarus** [comment]
активный план счетов ТЕКУЩЕЙ компании

**Comment by zholnerovich** [comment]
Скинул код. Это должно исправить проблему когда счет не выбран.

**Comment by zholnerovich** [comment]
справа от поля "Счета" есть кнопка, которая вызывает диалоговое окно выбора счетов. Мне кажется она работает не правильно. Она выводит план счетов компании выбранной в журнале ордере, а не в главном окне

**Comment by NikolayUkleyko** [comment]
Проверено.
Согласно вышеприведенной информации работает корректно.
@zholnerovich , спасибо ! :gift:

@gsbelarus , пожалуйста, закройте тему.
