### ISSUE TITLE
Теряется автофильтрация

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3462]
Originally reported on Google Code with ID 3462

```
В банковской выписке после открытия диалогового окна выписки слетает автофильтрация
в гриде позиций.

```

Reported by `gs1994` on 2014-10-09 11:38:33

**Comment by NikolayUkleyko** [comment]
Рассматриваемая тема перенесена сюда https://github.com/GoldenSoftwareLtd/gedemin/issues/3758
  Это касается не только документа **Банковская выписка**, но и всех остальных.
  Здесь можно закрыть.
