### ISSUE TITLE
Расход и приход в настройке типового документа

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3494]
Originally reported on Google Code with ID 3494

```
В диалоге редактирования типового документа есть закладки Расход и Приход, на которых
описывается откуда идет расход и куда приход. Там можно выбрать много чего: Нашу организацию,
Подразделение нашей организации, Сотрудника нашей организации и т.д. Это все хорошо,
но жизнь такова, что бывает, что расход идет и с подразделения, и с сотрудника нашей
организации. Если выберешь в настройках Подразделение, а в документ попал сотрудник,
то возникают сложности при просмотре этого сотрудника по F4 (настройки лукапа привязаны
к подразделению). Нельзя в этот список добавить Внутренний контакт нашей организации,
который бы подразумевал и Подразделение и Сотрудника?
```

Reported by `kovli.gs` on 2014-12-03 14:39:53

**Comment by gsbelarus** [comment]
Reported by `kovli.gs` on 2014-12-03 14:56:21

**Comment by gsbelarus** [comment]
```
можно, кстати, руками перенастраивать лукап в SetupDialog
```

Reported by `alexandra.gsoftware` on 2014-12-03 15:31:08

**Comment by gsbelarus** [comment]
```
Руками, конечно, можно, что сейчас и делается. Но, сомневаюсь, что каждому по силам.
А так все будет на уровне платформы.
```

Reported by `kovli.gs` on 2014-12-04 05:37:35

**Comment by gsbelarus** [comment]
```
Вообще хорошая идея. Сделаем.
```

Reported by `mikleshoihet` on 2014-12-04 06:00:57

**Comment by gsbelarus** [comment]
```
  Тяжело ли в редакторе объектов по определенному полю прописать условие в Condition
?

```

Reported by `NikolayUkleyko` on 2014-12-04 11:24:17

**Comment by gsbelarus** [comment]
```
  1. В типовом документе на закладках "Приход", "Расход" поле "Приход или расход оформляется
на" носит условный характер.
  2. Насколько мне известно, если в данном поле выбрать "Подразделение нашей организации",
то в документе в соответствующем поле можно выбрать и подразделение, и сотрудника.

```

Reported by `NikolayUkleyko` on 2014-12-05 10:06:35

**Comment by gsbelarus** [comment]
```
Да точно, я когда-то такое изменение вносил, уже сам забыл. (При выборе подразделения
 будет доступен и сотрудник и подразделение).
```

Reported by `mikleshoihet` on 2014-12-05 10:09:58

**Comment by gsbelarus** [comment]
```
Не совсем я прав, изменения касались только выбора остатков. 
```

Reported by `mikleshoihet` on 2014-12-05 13:00:04

**Comment by gsbelarus** [comment]
```
  Да, все верно - речь идет именно об остатках.
  Правильно будет отображать остатки по только выбранному контакту. Выбрав подразделение,
не показывать остатки по сотрудникам, входящим в данное подразделение.

```

Reported by `NikolayUkleyko` on 2014-12-05 14:19:01

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-12-11 18:36:32
- **Labels added**: Type-Defect, Priority-Medium, GedeminEXE, Depot

**Comment by NikolayUkleyko** [comment]
**_Исследователь > Материальный склад > 04. Отпуск материалов покупателям**_.

  По нему выполнены следующие настройки:
![1](https://cloud.githubusercontent.com/assets/11497453/13105211/fb30e32a-d572-11e5-88f9-163994cfec21.png)

![2](https://cloud.githubusercontent.com/assets/11497453/13105214/ff449d26-d572-11e5-996d-8961c9218bfa.png)

  Программа по-прежнему отображает следующее окно с сообщением:
![3](https://cloud.githubusercontent.com/assets/11497453/13105225/147ca814-d573-11e5-9bec-ceb1124c4fe6.png)

  Только, если в настройках look-up изменить класс с **TgdcDepartment** на **TgdcBaseContact**, тогда можно без проблем через кнопку **F4** открыть на редактирование как подразделение, так и сотрудника.
  Подобная ситуация встречалась и в основных средствах. В gedemin.exe что-то исправляли.
  Какие у кого будут предложения ? При необходимости, пожалуйста, устраните данную недоработку.

**Comment by gsbelarus** [comment]
В данном случае надо прописывать **TgdcBaseContact**.

**Comment by gsbelarus** [comment]
Указывать TgdcDepartment -- это ошибка, так как записи с contacttype = 2 -- это люди, а не подразделения.

**Comment by NikolayUkleyko** [comment]
Я понимаю.
  Так реализовано на эталоне и сохранено в ПИ.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
