### ISSUE TITLE
  Расчет курсовых разниц. Ошибка при выполнении расчета.

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3499]
Originally reported on Google Code with ID 3499

```
  Исследователь > Бухгалтерия > Автоматические хоз. операции > Расчет курсовых разниц.
  При выполнении расчета курсовых разниц появляется сообщение об ошибке.
  Предположительно, такая ошибка возникает, если, выбрано 2-а и более счета с наличием
одинаковой аналитики (например, клиент).
  Такого быть не должно.

```

Reported by `NikolayUkleyko` on 2014-12-12 14:09:16

<hr>
- _Attachment: Рис. 1. Расчет курсовых разниц. Ошибка..png<br>![Рис. 1. Расчет курсовых разниц. Ошибка..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3499/comment-0/Рис. 1. Расчет курсовых разниц. Ошибка..png)_

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
