### ISSUE TITLE
Типовой план счетов

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3504]
Originally reported on Google Code with ID 3504

```
В типову настройку надо включить:

http://www.minfin.gov.by/accounting/methodology/f265568f213002a5.html

```

Reported by `gs1994` on 2014-12-17 09:42:03

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2014-12-17 13:22:02

**Comment by gsbelarus** [comment]
```
Issue 2644 has been merged into this issue.
```

Reported by `NikolayUkleyko` on 2014-12-17 13:26:55

**Comment by gsbelarus** [comment]
```
Issue 2881 has been merged into this issue.
```

Reported by `NikolayUkleyko` on 2014-12-17 13:27:15

**Comment by NikolayUkleyko** [comment]
Перенесено в https://github.com/GoldenSoftwareLtd/gedemin/issues/3558.
  Закройте эту тему.

**Comment by NikolayUkleyko** [comment]
Если, ни у кого нет вопросов, тему можно закрыть.

**Comment by NikolayUkleyko** [comment]
Пожалуйста, закройте данную тему.
