### ISSUE TITLE
Форма просмотра Остатки по материалам и МБП

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3508]
Originally reported on Google Code with ID 3508

```
Если работать в холдинге, то в остатках очень хочется видеть не только контакт, у которого
эти остатки, но и рабочую компанию (наименование), которой принадлежит этот контакт.
Нельзя это встроить на уровне платформы? Для материального и торгового склада.

```

Reported by `kovli.gs` on 2014-12-31 08:46:11

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2015-01-08 12:19:05

**Comment by NikolayUkleyko** [comment]
Проверил.
  Такого функционала не обнаружил.

**Comment by MIchaelShoihet** [comment]
Я сам это посмотрю.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
Все же очень интересно - решен или не решен данный вопрос.
Иначе, закроем данный вопрос.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , такое можно предполагать, если, добавление такого реквизита не трудоемко и не замедлит работу формы остатков.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, подскажите, актуальна ли данная тема ?

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста, посмотри.

**Comment by Polfath** [comment]
сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

@gsbelarus , пожалуйста, закройте тему.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !

**Comment by NikolayUkleyko** [comment]
Если, нет вопросов, то данную тему можно закрывать.
