### ISSUE TITLE
Пользователь, который имеет право только на просмотр документа, может его перепровести

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3522]
Originally reported on Google Code with ID 3522

```
Пользователь, который имеет право только на просмотр документа, может его перепровести.
```

Reported by `gs1994` on 2015-01-29 11:52:18

**Comment by gsbelarus** [comment]
```
Issue 3467 has been merged into this issue.
```

Reported by `NikolayUkleyko` on 2015-01-29 12:06:03

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Если, ни у кого нет вопросов по данной теме, пожалуйста, закройте здесь.
