### ISSUE TITLE
ОС. После установки ПИ в документах доступны не все отчеты.

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3531]
Originally reported on Google Code with ID 3531

```
  После установки ПИ "06 Основные средства печатные формы" в документах "ОС. Акт ввода
в эксплуатацию" и "ОС. Акт ввода в эксплуатацию остатков доступны не все отчеты".
  В данных документах отчеты разбиты на группы. Отчеты доступны только из одной групп.
  В редакторе скрипт-объектов отчеты есть и в свойствах все реквизиты заполнены верно.

```

Reported by `NikolayUkleyko` on 2015-02-11 15:55:20

<hr>
- _Attachment: [ОС. После установки ПИ в документах доступны не все отчеты.pdf](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3531/comment-0/ОС. После установки ПИ в документах доступны не все отчеты.pdf)_

**Comment by gsbelarus** [comment]
```
Почему так происходит еще не разобралась. Как вариант скопировать отчеты в папку Obsolete.
Отчеты станут видны. Более того, можно создать вложенную папку в Obsolete и в новую
папку перенести отчеты из корневого каталога. 
```

Reported by `M.Burakina` on 2015-03-26 09:40:28

**Comment by gsbelarus** [comment]
```
Ветка "Отчеты TgdcInvDocument" находит или папку, или список отчетов в корневом каталоге.
 И папку, и список не видит.
Вариант 1 - логика программы верна, нужно создать подкаталог и перенести отчеты туда.
Варинат 2 - логика не верна, нужно исправлять exe.
```

Reported by `M.Burakina` on 2015-03-26 10:35:51
- **Labels added**: gedeminEXE

**Comment by gsbelarus** [comment]
```
Проверьте на уникальность имя группы. Наверняка есть еще в БД группа с таким же названием.
```

Reported by `gs1994` on 2015-03-26 11:47:30

**Comment by gsbelarus** [comment]
```
Да, были.
Переименовала, перегрузила, ничего не поменялось по вопросу.
Отчеты есть, в дереве видны, парент тот, но на форме их нет в выпадающем списке отчетов.
```

Reported by `M.Burakina` on 2015-03-27 12:49:31

**Comment by NikolayUkleyko** [comment]
Получается следующая ситуация.
  Удалив папку **Obsolete и ее отчеты**, главные отчеты становятся доступны (видны из документа). Но, стоит только обновить ПИ **06 Основные средства печатные формы** и главные отчеты опять недоступны.
  Это Сморгонь. Такое будет на любой БД.

**Comment by zholnerovich** [comment]
![qwe](https://cloud.githubusercontent.com/assets/11497757/12474927/083f40f0-c030-11e5-91b8-023004361f9e.jpg)

**Comment by zholnerovich** [comment]
это на последних исходниках

**Comment by NikolayUkleyko** [comment]
Да.
  Попробуй следующее. По документу **Исследователь > Основные средства > Акт ввода в эксплуатацию > ОС. Акт ввода в эксплуатацию остатков** удали все отчеты и папки отчетов. Потом установи ПИ **06 Основные средства печатные формы**. В результате будут доступны только отчеты, входящие в папку **_Obsolete**_. А вообще, что за хрень такая **_Obsolete**_ ??? Паша, ты не знаешь ?

**Comment by zholnerovich** [comment]
Коля, проверил два раза, вроде все работает. Возможно это связано стем, что последние несколько дней проводились доработки по наследованию отчетов и макросов. Насчет "Obsolete" не знаю, по моему это просто папка, каких либо упоминаний о ее исключительности в исходниках не найдено.

**Comment by gsbelarus** [comment]
ясное дело. причем тут исходники. кто-то создал папку и запихнул туда ненужные отчеты.

**Comment by NikolayUkleyko** [comment]
Какие практические действия по отношению БД Сморгонь КХП ?

**Comment by gsbelarus** [comment]
Покажи базу.

**Comment by gsbelarus** [comment]
Мне нужна база. Ту, которую дали -- там нет отчетов вообще по указанным документам. Ни в окне, ни в редакторе скрипт-объектов.

**Comment by NikolayUkleyko** [comment]
Пока можно взять и эту БД: india/3053:k:\Bases\Smorgon_KHP\GDBASE_2015_03_03.FDB

**Comment by NikolayUkleyko** [comment]
Вот и более новый вариант БД: Basel/3053:K:\Bases\SmorgonKhP\gdbase_2016_01_11.FDB

**Comment by NikolayUkleyko** [comment]
Пропала разделяющая черта.
  Было:
![1](https://cloud.githubusercontent.com/assets/11497453/12546661/5f177288-c35c-11e5-8458-92cc77b57406.png)

  Стало:
![2](https://cloud.githubusercontent.com/assets/11497453/12546679/6dea65ea-c35c-11e5-8ff5-a42394755f3f.png)

  Можно ли это реализовать ?

**Comment by gsbelarus** [comment]
Нет. сейчас все отчеты выводятся единым списком в алфавитном порядке.

**Comment by NikolayUkleyko** [comment]
Это просила Жанна.
  На счет вывода всех отчетов в алфавитном порядке не так. Сортировка какая была, такая и осталась. Внимательно сравните 2-а вышеприведенных скриншота. Очередность осталась прежней.

**Comment by NikolayUkleyko** [comment]
В целом работает корректно.
  Мелкая правка. Измените пиктограмку: чистый лист
![3](https://cloud.githubusercontent.com/assets/11497453/12577822/fc76f46e-c42d-11e5-9e73-d128f978b5a8.png)

замените на лист с данными (номер пиктограмки 176)
![4](https://cloud.githubusercontent.com/assets/11497453/12577825/009eda3e-c42e-11e5-952d-f6e6a2e37159.png)

  Подсказка, что это не пустые отчеты (бланки), а отчеты с данными. Мелочь, а приятно.
  Об этом просят многие сотрудники.
