### ISSUE TITLE
Сделать выбор нескольких признаков в поле счёта Аналитика для развёрнутого сальдо

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3534]
Originally reported on Google Code with ID 3534

```
К примеру, журнал-ордер заказчики строят в разрезе признаков "клиент" и "счёт затрат",
а в оборотной ведомости развёрнутое сальдо можно получить только по одному признаку.
В итоге сальдо расходится в двух формах.
```

Reported by `stasgm` on 2015-02-12 11:14:48

**Comment by gsbelarus** [comment]
Reported by `stasgm` on 2015-02-12 11:16:22
- **Labels added**: Accountancy

**Comment by gsbelarus** [comment]
```
  Да, такой функционал будет не лишним. Иногда требуется сформировать Оборотную ведомость
в развернутом виде более, чем по одной аналитике.
  Кстати, подобный функционал есть в другом программном обеспечении.

```

Reported by `NikolayUkleyko` on 2015-02-13 10:09:54

<hr>
- _Attachment: [Рис. 1. Оборотная ведомость. Развернутое сальдо по нескольким аналитикам.jpg](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3534/comment-2/Рис. 1. Оборотная ведомость. Развернутое сальдо по нескольким аналитикам.jpg)_
- _Attachment: [Рис. 2. Оборотная ведомость. Развернутое сальдо по нескольким аналитикам.jpg](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3534/comment-2/Рис. 2. Оборотная ведомость. Развернутое сальдо по нескольким аналитикам.jpg)_

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2015-06-29 14:12:38

**Comment by ShlTanya** [comment]
Хочется конкретики:
На данный момент:
1. В Плане счетов есть реквизит Аналитика для развернутого сальдо (активен только для активно-пассивного счета), в который можно ввести только 1 значение. 
2. Данный реквизит влияет на построение Журнал-ордера из Оборотной ведомости. К самой оборотной ведомости он отношения не имеет.

Что необходимо (как я поняла):
1. Сделать возможность выбора нескольких значений для Аналитики для развернутого сальдо (только из определенных для этого счета Аналитик).
2. Сделать формирование Оборотной ведомости в разрезе Аналитик для развернутого сальдо.

**Comment by MIchaelShoihet** [comment]
Как это к оборотной ведомости не имеет отношение - всегда имело. По счетам по которым указана главная аналитика сальдо строится в разрезе этой аналитики. И оно так работает. Запрос в оборотной ведомости формируется с учетом этой информации. На самом деле - это его главная функциональность (переход в журнал-ордер - это побочная функциональность). А хотят сделать, что бы была возможность указания нескольких полей аналитики для расчета этого сальдо.  Кстати надо проверить, что бы внутренние функции Гедемина которые рассчитывают сальдо учитывали эту информацию. При переходе в журнал-ордер, то же брать тот набор полей который будет указан в главной аналитике.

**Comment by NikolayUkleyko** [comment]
Полностью согласен с @MIchaelShoihet .

----

Небольшое уточнение.

> Что необходимо (как я поняла):

> Сделать возможность выбора нескольких значений для Аналитики для развернутого сальдо (только из определенных для этого счета Аналитик).

Какие аналитические признаки будет доступны при выборе значений по аналитике для развернутого сальдо:

**1.** Согласно выбранного перечня общих аналитических признаков.

**2.** Независимо от выбранного перечня общих аналитических признаков.

Я, предполагаю, что согласно пункта 1.

**Comment by ShlTanya** [comment]
А можно мне скрин оборотки с учетом главной аналитики. Я не нашла.

**Comment by MIchaelShoihet** [comment]
![default](https://cloud.githubusercontent.com/assets/11498750/22684464/885af254-ed2d-11e6-8668-b0d755510d7f.png)

**Comment by MIchaelShoihet** [comment]
Посмотрите на счета 60 и 62 по ним есть и дебетовое и кредитовое сальдо. Т.к. оно рассчитано как сумма дебетовых и кредитовых сальдо по клиентам.

**Comment by MIchaelShoihet** [comment]
Согласен c @NikolayUkleyko именно 1-й пункт.

**Comment by ShlTanya** [comment]
Вот как.. Но сами клиентов не видно. Тогда понятно. Я думала что здесь должна отображаться и сама аналитика.

**Comment by MIchaelShoihet** [comment]
Нет. Главная аналитика здесь участвует только для формирования сальдо.

**Comment by MIchaelShoihet** [comment]
Она еще используется в главной книге.

**Comment by ShlTanya** [comment]
Я видела оборотки, в которых раскрывается и аналитика.

**Comment by MIchaelShoihet** [comment]
У нас нет. Для это есть журнал ордер.

**Comment by ShlTanya** [comment]
Спасибо. Все понятно.

**Comment by ShlTanya** [comment]
Михаил, помогите разобраться. Я все сделала, но меня смущает :
1 -  оборотная ведомость формируется Всегда с учетом объектов аналитики развернутого сальдо (например, в Главной книге можно выбрать режим)
2 - внутренние функции Гедымина тоже всегда учитывают это, если не указана аналитика.

Это правильно??

И еще. Удалять ли сразу поле analyticalfield из ac_account в пакете с обновлением. Это поле уже не должно использоваться. (Значения из этого поля я сохраняю)

**Comment by NikolayUkleyko** [comment]
Вставлю свои 5-ть копеек.

>1 - оборотная ведомость формируется Всегда с учетом объектов аналитики развернутого сальдо (например, в Главной книге можно выбрать режим)

Развернутое сальдо имеет силу только для **активно-пассивных счетов**.
В плане счетов можно задать, а можно и не задавать аналитику для активно-пассивных счетов. С учетом этого и будет сформирована оборотная ведомость: развернутой или свернутой.

----

>2 - внутренние функции Гедымина тоже всегда учитывают это, если не указана аналитика.

На сколько мне известно алгоритм работы бухгалтерской формы **Оборотная ведомость** базируется на функционале заложенном в gedemin.exe. То есть, в так называемых **внутренних функциях**.
Выдумали: внутренние функции, внешние функции.

----

>И еще. Удалять ли сразу поле analyticalfield из ac_account в пакете с обновлением. Это поле уже не должно использоваться. (Значения из этого поля я сохраняю)

@ShlTanya , будет **создано новое поле** для хранения множества выбранных аналитических признаков для развернутого сальдо (для активно-пассивных счетов) ?

**Comment by ShlTanya** [comment]
Будет отдельная таблица

**Comment by MIchaelShoihet** [comment]
Старое поле вообще удалять не надо. На больших предприятиях возможна работа разных exe поэтому пусть работают. Как правильно написал @NikolayUkleyko развернутое сальдо должно формироваться только для активно-пасивных счетов если у них указана соответствующая аналитика. В оборотной ведомости и внутренних функциях (для @NikolayUkleyko внутренние функции - это функции расчета сальдо, и оборотов, которые доступны в типовых и автоматических операциях) расширенное сальдо должно формироваться именно исходя из этих условий. В главной книге если есть возможность расчета и так и так - оставить эту возможность.

**Comment by ShlTanya** [comment]
Так и реализовано. Значит поле не удаляю.

**Comment by ShlTanya** [comment]
Спасибо.

**Comment by ShlTanya** [comment]
Николай.. по поводу "внутренних функций". Возможно, я неверно их назвала. Имелось в виду то, что вы используете в скриптах. Например, gs.SK (SD) и т.п.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

У меня возникли следующие вопросы:

1. В плане счетов в блоке для развернутого сальдо, @MIchaelShoihet, есть ли смысл добавить еще и возможность задания **очередности** выбранных аналитических признаков, как это реализовано на панели инструментов в Журнале-ордере.

Смоделировал несколько примеров - как, результат, очередность не влияет на итоговые суммы.

@MIchaelShoihet , уточняю на всякий случай.

2. В Главной книге на панели инструментов в самом низу предусмотрен реквизит **Расширенное сальдо итого**.
Такой реквизит есть и на панели инструментов Журнала-ордера.
Но, в Журнале-ордере и в Главной книге это работает по-разному.
В Журнале-ордере - дополнительно отображаются итоговые суммы в промежуточных и конечных строках.
В Главной книге - данные формируются развернуто согласно указанных в плане счетов по активно-пассивным счетам аналитик для развернутого сальдо.

Вот и напрашивается, не мешало бы в Главной книге реквизит **Расширенное сальдо итого** переименовать в **Разворачивать сальдо**. @MIchaelShoihet , согласитесь, так будет более понятно и корректно.

**Comment by MIchaelShoihet** [comment]
1. Очередность вроде как не важно.
2. Да согласен.

**Comment by ShlTanya** [comment]
1. Очередность проверяла. Не увидела разницу.
2. Реквизит переименую.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

@gsbelarus , пожалуйста, закройте тему.
