### ISSUE TITLE
Бухгалтерия. Конструктор функций. Комбинация клавиш 'Ctrl+A'

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3540]
Originally reported on Google Code with ID 3540

```
  Исследователь > Бухгалтерия > Типовые хоз. операции, Автоматические хоз. операции.
  Сейчас для выделения всех элементов в строке доступна команда из контекстного меню
'Выделить все'. Пожалуйста, предусмотрите возможность выделения всех элементов при
помощи комбинации клавиш 'Ctrl+A'. Так будет гораздо удобнее работать в конструкторе
функций.

```

Reported by `NikolayUkleyko` on 2015-02-23 14:58:23

<hr>
- _Attachment: Рис. 1. Конструктор функций. Выделить все..png<br>![Рис. 1. Конструктор функций. Выделить все..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3540/comment-0/Рис. 1. Конструктор функций. Выделить все..png)_
- _Attachment: Рис. 2. Конструктор функций. Выделить все..png<br>![Рис. 2. Конструктор функций. Выделить все..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3540/comment-0/Рис. 2. Конструктор функций. Выделить все..png)_

**Comment by NikolayUkleyko** [comment]
Перенесено в https://github.com/GoldenSoftwareLtd/gedemin/issues/3629.
  Закройте текущую тему.
