### ISSUE TITLE
Контекстное меню и комбинация клавиш Ctrl+A' (выделить все) в документах, справочниках и т. д.

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3541]
Originally reported on Google Code with ID 3541

```
  При работе с документами, справочниками и т. д. часто приходится изменять данные.
Выделив значение в поле, контекстное меню остается прежним. При этом не работает комбинации
клавиш 'Ctrl+A' (выделить все).
  Пожалуйста, предусмотрите следующее:
1. При выделении поля должно отображаться соответствующее контекстное меню.
2. При выделении поля должна работать комбинации клавиш 'Ctrl+A' (выделить все).
  Сейчас для выделения всего значения в поле приходится выполнять незамысловатые действия.
Это не очень удобно.

```

Reported by `NikolayUkleyko` on 2015-02-23 15:15:55

<hr>
- _Attachment: Рис. 1. Контекстное меню и комбинация клавиш 'Ctrl+A' (выделить все)..png<br>![Рис. 1. Контекстное меню и комбинация клавиш 'Ctrl+A' (выделить все)..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3541/comment-0/Рис. 1. Контекстное меню и комбинация клавиш 'Ctrl+A' %28выделить все)..png)_
- _Attachment: Рис. 2. Контекстное меню и комбинация клавиш 'Ctrl+A' (выделить все)..png<br>![Рис. 2. Контекстное меню и комбинация клавиш 'Ctrl+A' (выделить все)..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3541/comment-0/Рис. 2. Контекстное меню и комбинация клавиш 'Ctrl+A' %28выделить все)..png)_

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
