### ISSUE TITLE
Бухгалтерия. Конструктор функций. Шрифты

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3542]
Originally reported on Google Code with ID 3542

```
  Исследователь > Бухгалтерия > Типовые хоз. операции, Автоматические хоз. операции.
  До недавнего времени в конструкторе функций шрифт на форме блока и в редакторе выражений
был единый. Теперь в редакторе выражений по-моему шрифт Tahoma, а на форме блока MS
Sans Serif (не я менял шрифты). Пожалуйста, приведите шрифты к одному знаменателю.
Сделайте в конструкторе функций отображение блоков и других элементов шрифтом Tahoma.

```

Reported by `NikolayUkleyko` on 2015-02-23 15:25:51

<hr>
- _Attachment: Рис. 1. Бухгалтерия. Конструктор функций. Шрифты..png<br>![Рис. 1. Бухгалтерия. Конструктор функций. Шрифты..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3542/comment-0/Рис. 1. Бухгалтерия. Конструктор функций. Шрифты..png)_
- _Attachment: Рис. 2. Бухгалтерия. Конструктор функций. Шрифты..png<br>![Рис. 2. Бухгалтерия. Конструктор функций. Шрифты..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3542/comment-0/Рис. 2. Бухгалтерия. Конструктор функций. Шрифты..png)_

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2015-02-23 15:26:43

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2015-02-24 06:46:07

<hr>
- _Attachment: Рис. 3. Бухгалтерия. Конструктор функций. Шрифты..png<br>![Рис. 3. Бухгалтерия. Конструктор функций. Шрифты..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3542/comment-2/Рис. 3. Бухгалтерия. Конструктор функций. Шрифты..png)_

**Comment by iamchrisep** [comment]
Сделано
