### ISSUE TITLE
Бухгалтерия. Конструктор функций. Выбор валюты в Редакторе выражений

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3544]
Originally reported on Google Code with ID 3544

```
  Исследователь > Бухгалтерия > Типов хоз. операции, Автоматические хоз. операции.
  Сейчас в конструкторе функций в поле 'Валюта' нельзя вызвать Редактор выражений.
Встречаются различные ситуации. Таким образом, нельзя выбрать переменную, SQL запрос
и др.
  Пожалуйста, предусмотрите такую возможность.

```

Reported by `NikolayUkleyko` on 2015-02-24 06:43:45

<hr>
- _Attachment: Рис. 1. Выбор валюты в Редакторе выражений..png<br>![Рис. 1. Выбор валюты в Редакторе выражений..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3544/comment-0/Рис. 1. Выбор валюты в Редакторе выражений..png)_

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@iamchrisep , спасибо !
:trophy:

@gsbelarus , пожалуйста, закройте тему.
