### ISSUE TITLE
Бухгалтерия. Конструктор функций. SQL переменная в полях типа 'Сумма'

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3546]
Originally reported on Google Code with ID 3546

```
  Исследователь > Бухгалтерия > Типовые хоз. операции, Автоматические хоз. операции.
  В конструкторе функций при вытягивании сумм в SQL запросе и дальнейшей выборе в поле
типа 'Сумма' SQL переменная заканчивается на 'Value'. Часто программа ругается на такой
тип данных. Необходимо, чтобы при выборе в поле типа 'Сумма' SQL переменная заканчивается
на 'AsCurrency'. Вручную править не удобно. Можно забыть.
  Пожалуйста, исправьте.

```

Reported by `NikolayUkleyko` on 2015-02-24 14:26:08

<hr>
- _Attachment: Рис. 1. SQL переменная в полях типа 'Сумма'..png<br>![Рис. 1. SQL переменная в полях типа 'Сумма'..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3546/comment-0/Рис. 1. SQL переменная в полях типа 'Сумма'..png)_

**Comment by gsbelarus** [comment]
Когда именно ругается? Это общий механизм для использования значения поля из выборки, а оно может быть NULL, чего не пепередашь через asCurrency.

Может имеет смысл в окно Выбор переменной добавить еще переключатели типов что бы программист сам мог указать AsCurrency, AsString, AsDateTime, AsFloat или Value.

Но, это спорный момент.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
