### ISSUE TITLE
Материальный склад. Сообщение 'По выбранному ТМЦ недостаточное количество остатков'

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3547]
Originally reported on Google Code with ID 3547

```
  В программе при работе со складскими остатками нередко можно встретить подобное сообщение
'При формировании движения по позиции произошла следующая ошибка. По выбранному ТМЦ
недостаточное количество остатков'. Опытного пользователя данное сообщение вводит в
ступор. Что уже говорить о менее опытных пользователях. Пожалуйста, при работе в материальном
складе замените данное сообщение на 'Данный ТМЦ нельзя выбрать, так как по данному
ТМЦ есть более позднее движение. Пожалуйста, сформируйте карточку ТМЦ и проверьте движение'.
При работе в основных средствах замените данное сообщение на 'Данный ОС нельзя выбрать,
так как по данному ОС есть более позднее движение. Пожалуйста, сформируйте полную карточку
ТМЦ и проверьте движение'.
  Или я не прав ?

```

Reported by `NikolayUkleyko` on 2015-02-25 14:35:35

<hr>
- _Attachment: Рис. 1. Сообщение 'По выбранному ТМЦ недостаточное количество остатков'..png<br>![Рис. 1. Сообщение 'По выбранному ТМЦ недостаточное количество остатков'..png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3547/comment-0/Рис. 1. Сообщение 'По выбранному ТМЦ недостаточное количество остатков'..png)_

**Comment by NikolayUkleyko** [comment]
Можно ли это реализовать ?

**Comment by MIchaelShoihet** [comment]
Про карточку можно добавить. Вставить ОС конечно нельзя, gedemin не знает про тип ТМЦ по которому идет движение.

**Comment by NikolayUkleyko** [comment]
Хорошо. Так будет лучше.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
