### ISSUE TITLE
Счета в ПИ

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3558]
Originally reported on Google Code with ID 3558

```
Стандартные счета из плана счетов (с XID < 147000000 и DBID = 17, есть на чистом эталоне,
без ПИ) входят во множество ПИ (некоторые - в несколько ПИ одновременно). Зачем так
сделано (все аналитики ac_account сейчас входят в Общие данные)? Может, как-то это
упростить?
```

Reported by `alexandra.gsoftware` on 2015-03-12 16:02:04

**Comment by gsbelarus** [comment]
```
Вообще так было сделано не специально, а как говорится так получилось... 
```

Reported by `mikleshoihet` on 2015-03-12 16:43:25

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2015-03-30 12:36:21
- **Labels added**: accountancy

**Comment by gsbelarus** [comment]
```
А можно их все скинуть в Бухгалтерские счета, например? Есть возражения?
```

Reported by `alexandra.gsoftware` on 2015-04-02 18:14:01

**Comment by gsbelarus** [comment]
```
Нет возражений.
```

Reported by `mikleshoihet` on 2015-04-02 18:18:08

**Comment by NikolayUkleyko** [comment]
1. На сегодняшний день все данные из плана счетов по-прежнему входят в различные ПИ или не входят вовсе ни в какое ПИ. Элементарно установить ПИ с отредактированным планом счетов не получиться.  Получается, как всегда "танцы с бубном".
2. Как закинуть все данные из плана счетов одним кликом в одно ПИ ? Есть такие инструменты ?
   ![1](https://cloud.githubusercontent.com/assets/11497453/8770815/d5ac96d4-2ec0-11e5-8e66-66b20fafc9c3.png)

**Comment by gsbelarus** [comment]
UPDATE-ом @alexandra-gsoftware пусть перенесет из разных ПИ позиции в одно. Только сначала SELECT-ом надо посмотреть что где лежит, чтобы ненужное не подхватить.

**Comment by alexandra-gsoftware** [comment]
нужно проверить целостность пи отчетом Неверные зависимости

**Comment by gsbelarus** [comment]
тут похоже на другое. в разных ПИ одинаковые счета лежат в разных планах счетов. вот и ругается. но, надо проверить. может это что-то и другое. как именно вызвать ошибку? на какую БД и что ставить?

**Comment by alexandra-gsoftware** [comment]
Некоторые счета действительно лежат в нескольких пи (см. описание проблемы из старого баг-бейза), но проблем с установкой не было. Вероятно, в пи Бухгалтерские счета на базе с разработками Николая нарушен порядок их следования. Это проверяется отчетом Неверные зависимости из пи GS.Пространство имен.Отчеты

**Comment by NikolayUkleyko** [comment]
ПИ Бухгалтерские счета можно попробовать установить на любую базу данных. На выходе будет ошибка.
  ПИ Бухгалтерские счета проверено при помощи отчета Неверные зависимости - передал Александре.
  Я не спорю, что, предположительно, как указала Александра, нарушен порядок следования счетов в ПИ. Для того, чтобы такого гемора не было необходимо все данные из одного справочника закидывать строго в одно ПИ - в данном случае ПИ Бухгалтерские счета. Получается, для того, чтобы элементарно установить план счетов необходимо установить все ПИ из комплексной автоматизации, начиная с подсистемы Банк и касса и заканчивая Учетом спецодежды. Это не разумно. Кто не согласен ? Посмотрите, как сделаны подсистемы на 1С. Можно безболезненно установить любую отдельную подсистему и она будет корректно работать. К сожалению, у нас такого нет. Вот и получаются не стыковки с зависимостями.
  Хотя, ПИ современная штука (XXI век все дела), навязанная для упрощения работы с файлами разработок, на практике выходит иное. Не надо усложнять там, где это не надо. Любая конструкция должна быть максимально простой и, как результат, надежной. Благо, Александра, периодически производит профилактику ПИ и их зависимостей. А без этого, вся технология со временем может потерять смысл.

**Comment by gsbelarus** [comment]
Причем здесь 1С. Механизм ПИ позволяет сделать как полностью независимую подсистему, которую ставь куда хочешь, так и зависимую, которая требует для установки других подсистем. Дальше все зависит от разработчика. Это как молоток, можно рамку с фотографией бабушки на стенку прибить, а можно палец себе от*рить. Все зависит от кривизны рук.

Но, даже в случае наличия зависимостей, все ставится как правило, без проблем, пока хитроумный настройщик не пытается ПРИНУДИТЕЛЬНО загрузить одно ПИ, без загрузки/обновления тех, от которых оно зависит. Тут конечно возможны ошибки, но ПИ здесь не причем.

**Comment by alexandra-gsoftware** [comment]
нужно просто поменять порядок следования...

**Comment by alexandra-gsoftware** [comment]
в продолжение темы. Вот этот запрос
    SELECT
      a.ALIAS,
      a.ID,
      COUNT(ns.ID) AS NSCount,
      LIST(ns.NAME, ', ') AS NSs
    FROM AC_ACCOUNT a
    LEFT JOIN GD_RUID r ON r.ID = a.ID
        LEFT JOIN AT_OBJECT o ON (o.XID = r.XID AND o.DBID = r.DBID ) OR (o.XID = a.ID AND o.DBID = 17)
    LEFT JOIN AT_NAMESPACE ns ON ns.ID = o.NAMESPACEKEY
    GROUP BY 1,2
    HAVING COUNT(ns.ID) > 1
    ORDER BY 1
покажет счета, которые входят в несколько ПИ. Там же можно кликнуть по полю ИД, зайти в редактирование счета, свойства, страничка ПИ, и выкинуть их из одного из ПИ.

Дальше (когда каждый счет входит только в одно ПИ) вот этот запрос:
    SELECT
      a.ALIAS,
      a.ID,
      LIST(ns.NAME, ', ') AS NSs
    FROM AC_ACCOUNT a
    LEFT JOIN GD_RUID r ON r.ID = a.ID
    LEFT JOIN AT_OBJECT o ON (o.XID = r.XID AND o.DBID = r.DBID ) OR (o.XID = a.ID AND o.DBID = 17)
    LEFT JOIN AT_NAMESPACE ns ON ns.ID = o.NAMESPACEKEY
    WHERE ns.ID <> <RUID XID = 147710959 DBID = 43451302/> OR ns.ID IS NULL
    GROUP BY 1,2
    ORDER BY 1

покажет, какие счета не входят в Бухгалтерские счета. Опять же, можно их прямо из sql-редактора перекинуть в другое ПИ.

Если стандартный счет никуда не входит, это нормально и ничего страшного.

Все ПИ, которые будут отредактированы, надо проверить на целостность отчетом Неверные зависимости

**Comment by NikolayUkleyko** [comment]
1. Ошибку выдает, когда я устанавливаю ПИ Бухгалтерские счета со всеми зависимыми ПИ.
2. Хитроумный настройщик не создавал новых ПИ. Все действия выполняются строго с существующими ПИ. Просто, при переводе настроек в ПИ необходимо было подумать, как грамотно сделать. Все данные из одного справочника вкинуть в одно ПИ. Это ж логично.
   На сегодняшний день обновить план счетов на любой базе данных никак не получиться. Только, делая индивидуальную корректировку плана счетов.

**Comment by alexandra-gsoftware** [comment]
> > > Все данные из одного справочника вкинуть в одно ПИ. Это ж логично.

Не всегда. Справочник контактов, справочник ТМЦ, справочник единиц измерения, справочник стран... Данные входят в разные ПИ и это нормально. Конвертация настройки в ПИ = все объекты настройки добавить в ПИ. 
Дальше ПИ живет своей жизнью. Иногда данные из ПИ переносятся в другие ПИ, иногда ПИ объединяются, иногда разделяются на два и тд. Это происходит в процессе разработки, когда разработчик видит, что такое действие необходимо. 

Вопрос со счетами висит почему? Потому что он неоднозначен. Есть пара счетов, используемых только в торговле. Куда они должны входить, вместе со своими аналитиками? В План Счетов или в Торговлю? Это только один пример. А есть еще ОСы, Путевые и прочие радости. Когда счет входит в два ПИ одновременно - это однозначно неправильно, да. И кучка мелких ПИ по налогам, которые в любом случае зависят от Плана Счетов, не должны содержать счета.... Возможно, нужны ПИ "План Счетов", "План счетов. Торговля", "План счетов. ОС" и тд, и связи между ними

**Comment by MIchaelShoihet** [comment]
В случае со счетами, я думаю все счета должны лежать в одном ПИ, и настроены по своему смыслу. Дело в том что план счетов так организован, что за разные виды деятельности отвечают в основном разные счета и их настройка (т.е. виды аналитик) зависит от их названия. Поэтому если мы сразу создадим настройку со всем набором счетов и соответственно аналитик, то ничего плохого в этом не будет.

**Comment by alexandra-gsoftware** [comment]
тогда проблемы вообще нет. Найти счета из других пи запросами, которые я написала выше. Закинуть все в План счетов. Проверить на целостность.

**Comment by MIchaelShoihet** [comment]
Чудесно. Значит вы знаете что нужно сделать :).

**Comment by NikolayUkleyko** [comment]
По хорошему данные из справочника контактов, справочника ТМЦ, справочник единиц измерения, справочника стран и т. д. я бы разместил в общих ПИ. В дальнейшем будет меньше проблем при установке дополнительных подсистем.
  Я вообще не знаю кто придумал идеологию включать несколько одних счетов в одну подсистему, а несколько других - в другую ? Получается бредятина. Вообще, независимо от количества подсистем и их особенностей для подсистемы Бухгалтерия данные из справочника План счетов должны входить в одно цельное ПИ.
  Я проанализировал в какие другие ПИ отличные от ПИ Бухгалтерские счета входит часть счетов. Оказалось так:
- Бухгалтерский баланс;
- Закрытие месяца;
- Статистические отчеты (1ф2ф5ф6ф5з);
- Налоговые регистры к налогу на прибыль;
- НДС;
- ФСЗН;
- Книга покупок(данные);
- Налог на содержание транспорта;
- Налог на недвижимость.
  
  Создавать счета под отчеты бухгалтерии, а не наоборот не правильно. План счетов не я придумал. На клиентской базе должно быть установлено только одно цельное ПИ для плана счетов. Остальные счета добавляются на усмотрение клиента.

**Comment by alexandra-gsoftware** [comment]
В общем, счета перенесены в ПИ Бухгалтерские счета. Так же проставлена зависимость от этого ПИ в Торговля-данные и Зарплата-данные

**Comment by alexandra-gsoftware** [comment]
Да, вот кстати. 
Счет 90.02 превратился 90.04, и не только:
90.02  ->  90.04
90.03  ->  90.02
90.04  ->  _90.04
90.05  ->  90.03
90.06 ->  _90.06
Появились новые счета 90.05, 90.06

91.02  ->  91.04
91.03  ->  91.02
91.04  ->  91.03

Так и надо?

**Comment by NikolayUkleyko** [comment]
Привет, Александра !
  Все верно.
  Так как, в новом плане счетов одни и те же счета поменяли числовое
обозначение. Некоторые существующие ушли в неиспользуемые и добавлены новые
счета. Потом, типовые проводки перенастроил.
  Александра, а что собственно ?

23 июля 2015 г., 17:00 пользователь alexandra-gsoftware <
notifications@github.com> написал:

> Да, вот кстати.
> Счет 90.02 превратился 90.04, и не только:
> 90.02 -> 90.04
> 90.03 -> 90.02
> 90.04 -> _90.04
> 90.05 -> 90.03
> 90.06 -> _90.06
> Появились новые счета 90.05, 90.06
> 
> 91.02 -> 91.04
> 91.03 -> 91.02
> 91.04 -> 91.03
> 
> Так и надо?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124117340
> .

## 

С уважением, Николай.

**Comment by alexandra-gsoftware** [comment]
надо, может, в скриптах формирования эталона поменять...

>  Александра, а что собственно ?
> твое сообщение при установке из-за этого возникало

**Comment by NikolayUkleyko** [comment]
Я переименовывал существующие счета, только при наличии аналогичных по
своему назначению счетов. Если, счет, предназначен для другой функции, то я
его убирал в неиспользуемые и добавлял новый счет со своим предназначением.
Даже, если цифровое обозначение в последних одинаковое.
  :-)

23 июля 2015 г., 17:36 пользователь Николай Уклейко <
nikolayukleyko@gmail.com> написал:

>   Привет, Александра !
>   Все верно.
>   Так как, в новом плане счетов одни и те же счета поменяли числовое
> обозначение. Некоторые существующие ушли в неиспользуемые и добавлены новые
> счета. Потом, типовые проводки перенастроил.
>   Александра, а что собственно ?
> 
> 23 июля 2015 г., 17:00 пользователь alexandra-gsoftware <
> notifications@github.com> написал:
> 
> Да, вот кстати.
> 
> > Счет 90.02 превратился 90.04, и не только:
> > 90.02 -> 90.04
> > 90.03 -> 90.02
> > 90.04 -> _90.04
> > 90.05 -> 90.03
> > 90.06 -> _90.06
> > Появились новые счета 90.05, 90.06
> > 
> > 91.02 -> 91.04
> > 91.03 -> 91.02
> > 91.04 -> 91.03
> > 
> > Так и надо?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124117340
> > .
> 
> ## 
> 
> С уважением, Николай.

## 

С уважением, Николай.

**Comment by NikolayUkleyko** [comment]
Да, Александра, это нужно сделать.
  Только, пожалуйста, на всякий случай, для уверенности уточни у МЮ и АП.

  Спасибо !

23 июля 2015 г., 17:39 пользователь Николай Уклейко <
nikolayukleyko@gmail.com> написал:

>   Я переименовывал существующие счета, только при наличии аналогичных по
> своему назначению счетов. Если, счет, предназначен для другой функции, то я
> его убирал в неиспользуемые и добавлял новый счет со своим предназначением.
> Даже, если цифровое обозначение в последних одинаковое.
>   :-)
> 
> 23 июля 2015 г., 17:36 пользователь Николай Уклейко <
> nikolayukleyko@gmail.com> написал:
> 
>   Привет, Александра !
> 
> >   Все верно.
> >   Так как, в новом плане счетов одни и те же счета поменяли числовое
> > обозначение. Некоторые существующие ушли в неиспользуемые и добавлены новые
> > счета. Потом, типовые проводки перенастроил.
> >   Александра, а что собственно ?
> > 
> > 23 июля 2015 г., 17:00 пользователь alexandra-gsoftware <
> > notifications@github.com> написал:
> > 
> > Да, вот кстати.
> > 
> > > Счет 90.02 превратился 90.04, и не только:
> > > 90.02 -> 90.04
> > > 90.03 -> 90.02
> > > 90.04 -> _90.04
> > > 90.05 -> 90.03
> > > 90.06 -> _90.06
> > > Появились новые счета 90.05, 90.06
> > > 
> > > 91.02 -> 91.04
> > > 91.03 -> 91.02
> > > 91.04 -> 91.03
> > > 
> > > Так и надо?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124117340
> > > .
> > 
> > ## 
> > 
> > С уважением, Николай.
> 
> ## 
> 
> С уважением, Николай.

## 

С уважением, Николай.

**Comment by gsbelarus** [comment]
Надо подумать, чем это вылезет. Счета при загрузке первым делом проверяются по номеру, а потом по РУИДу.

**Comment by NikolayUkleyko** [comment]
Александра, не должно. Но, надо уточнить.
  Еще один момент. Добавленные счета можно убрать и оставить существующие
(только эти 2-а счета):
90.04 -> _90.04
90.06 -> _90.06
  Так будет более грамотно.
  Александра, мне это сделать или что скажешь ?

23 июля 2015 г., 17:43 пользователь Andrej Kirejeŭ <notifications@github.com

> написал:
> 
> Надо подумать, чем это вылезет. Счета при загрузке первым делом
> проверяются по номеру, а потом по РУИДу.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124128551
> .

## 

С уважением, Николай.

**Comment by alexandra-gsoftware** [comment]
Давайте подождем мнение МЮ.

**Comment by NikolayUkleyko** [comment]
Потом, типовые проводки донастрою и пересохраню ПИ.

23 июля 2015 г., 17:49 пользователь Николай Уклейко <
nikolayukleyko@gmail.com> написал:

>   Александра, не должно. Но, надо уточнить.
>   Еще один момент. Добавленные счета можно убрать и оставить существующие
> (только эти 2-а счета):
> 90.04 -> _90.04
> 90.06 -> _90.06
>   Так будет более грамотно.
>   Александра, мне это сделать или что скажешь ?
> 
> 23 июля 2015 г., 17:43 пользователь Andrej Kirejeŭ <
> notifications@github.com> написал:
> 
> > Надо подумать, чем это вылезет. Счета при загрузке первым делом
> > проверяются по номеру, а потом по РУИДу.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124128551
> > .
> 
> ## 
> 
> С уважением, Николай.

## 

С уважением, Николай.

**Comment by gsbelarus** [comment]
Если клиента уже настроены ТХО на эти счета. После загрузки ПИ они переименуются, что произойдет?

Может существующие оставить как есть? Или я тут что-то не понимаю?

**Comment by gsbelarus** [comment]
Счета с системными РУИДами создаются в скриптах. Если переименовывать, то надо и там, чтобы чистая начальная база поставлялась с правильными счетами.

Но, остается вопрос, что произойдет у существующих клиентов, с существующими ТХО??

**Comment by NikolayUkleyko** [comment]
Лучше оставить существующие и убрать новые аналогичные.

23 июля 2015 г., 17:54 пользователь Andrej Kirejeŭ <notifications@github.com

> написал:
> 
> Если клиента уже настроены ТХО на эти счета. После загрузки ПИ они
> переименуются, что произойдет?
> 
> Может существующие оставить как есть? Или я тут что-то не понимаю?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124131256
> .

## 

С уважением, Николай.

**Comment by NikolayUkleyko** [comment]
В результате всех изменений в плане счетов у существующих клиентов картина будет такова. Для корректности данных необходима будет доработка типовых проводок - добавление условия на дату. То есть, с такой-то даты будет использоваться такой-то счета, а ниже этой даты - другой счет. Типовые проводки я исправил согласно нового плана счетов. Но без всяких условий на дату.

**Comment by NikolayUkleyko** [comment]
У существующих клиентов 2-а счета в проводках останутся. В бухгалтерских
отчетах они тоже останутся прежними. Необходимо только в типовых проводках
дописать условие на дату, что с такой-то даты вместо такого-то счета, будет
использоваться другой.

23 июля 2015 г., 17:56 пользователь Andrej Kirejeŭ <notifications@github.com

> написал:
> 
> Счета с системными РУИДами создаются в скриптах. Если переименовывать, то
> надо и там, чтобы чистая начальная база поставлялась с правильными счетами.
> 
> Но, остается вопрос, что произойдет у существующих клиентов, с
> существующими ТХО??
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124131841
> .

## 

С уважением, Николай.

**Comment by NikolayUkleyko** [comment]
Подробности.
  В старом плане счетов счет 90.04 - _Акцизы_. В новом плане счетов он
называется _Себестоимость реализованной продукции, товаров, работ, услуг_.
  В старом плане счетов счет 90.06 - _Экспортные пошлины_. В новом плане
счетов он называется _Расходы на реализацию_.
  Как видите, числовое обозначение одно и то же, но назначение счетов
совершенно другое.

23 июля 2015 г., 17:57 пользователь Николай Уклейко <
nikolayukleyko@gmail.com> написал:

>   Александра, тут всего 2-а счета перекинуть и проводки подчехлить.
> 
> 2015-07-23 17:51 GMT+03:00 alexandra-gsoftware notifications@github.com:
> 
> > Давайте подождем мнение МЮ.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124130630
> > .
> 
> ## 
> 
> С уважением, Николай.

## 

С уважением, Николай.

**Comment by NikolayUkleyko** [comment]
Александра, тут всего 2-а счета перекинуть и проводки подчехлить.

2015-07-23 17:51 GMT+03:00 alexandra-gsoftware notifications@github.com:

> Давайте подождем мнение МЮ.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124130630
> .

## 

С уважением, Николай.

**Comment by MIchaelShoihet** [comment]
Для всех здесь хорошо не сделаешь... У старых клиентов я все счета которые изменили наименование я делал устаревшими (добавлял _ в номер и переносил в отдельную ветку), и добавлял новые.... В этом случае оборотка за предыдущие года сохраняла старые счета, а за новые была с новыми счетами (по 90 счетам хорошо они на конец года закрываются).... И это было хорошо, но с одним условием это делалось в реальном режиме времени, т.е. в новом периоде новые проводки делались с новыми счетами. Если же сейчас делать так, то у старых клиентов, могут возникнуть проблемы у них появятся новые счета, аналогичые тем что у них уже наверняка есть... Но план счетов, поменялся 2 года назад и значит у таких клиентов и счета и проводки уже настроены, значит не счета, не проводки они обновлять не должны, а если хотят то уже делать это в индивидуальном порядке, а значит надо думать о том как удобней будет для новых клиентов. А для новых клиентов будет удобней так, как удобней нам. Т.е. с минимальным количеством изменений.

**Comment by NikolayUkleyko** [comment]
Я так все и сделал.
  Согласен, в приоритете новые клиенты, так как у существующих клиентов все
уже настроено и настраивается в индивидуальном порядке.
  Вот информация, как в 1С Бухгалтерии реализован переход на новый план
счетов http://www.misoft.by/news/detail.php?ID=9982.

24 июля 2015 г., 9:53 пользователь MIchaelShoihet notifications@github.com
написал:

> Для всех здесь хорошо не сделаешь... У старых клиентов я все счета которые
> изменили наименование я делал устаревшими (добавлял _ в номер и переносил в
> отдельную ветку), и добавлял новые.... В этом случае оборотка за предыдущие
> года сохраняла старые счета, а за новые была с новыми счетами (по 90 счетам
> хорошо они на конец года закрываются).... И это было хорошо, но с одним
> условием это делалось в реальном режиме времени, т.е. в новом периоде новые
> проводки делались с новыми счетами. Если же сейчас делать так, то у старых
> клиентов, могут возникнуть проблемы у них появятся новые счета, аналогичые
> тем что у них уже наверняка есть... Но план счетов, поменялся 2 года назад
> и значит у таких клиентов и счета и проводки уже настроены, значит не
> счета, не проводки они обновлять не должны, а если хотят то уже делать это
> в индивидуальном порядке, а значит надо думать о том как удобней будет для
> новых клиентов. А для новых клиентов будет удобней так, как удобней нам.
> Т.е. с минимальным количеством изменений.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124367494
> .

## 

С уважением, Николай.

**Comment by alexandra-gsoftware** [comment]
значит, оставляем как есть?
Николай, можешь написать список счетов, которые поменялись местами, чтобы обновить скрипты формирования чистого эталона

**Comment by NikolayUkleyko** [comment]
Оставляем как есть. Тем более Михаил Юрьевич дал добро.
  По поводу списка отчетов, поменявших места уточни, что к чему ?

24 июля 2015 г., 14:46 пользователь alexandra-gsoftware <
notifications@github.com> написал:

> значит, оставляем как есть?
> Николай, можешь написать список счетов, которые поменялись местами, чтобы
> обновить скрипты формирования чистого эталона
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124497392
> .

## 

С уважением, Николай.

**Comment by alexandra-gsoftware** [comment]
ну, такое:
90.02 -> 90.04
90.03 -> 90.02
и тд

**Comment by NikolayUkleyko** [comment]
Воспринял, как отчЕтов, а на деле речь о счетАх. )))
  Попробую:
_Было                                                                       Стало_
10.12 (Амортизация МБП)                                         10.13 (Износ инвентаря и хозяйственных принадлежностей, инструментов)
10.13 (Амортизация спецодежды)                            10.14 (Износ спецодежды)

90.02 (Себестоимость реализации)                          90.04 (Себестоимость реализованной продукции, товаров, работ, услуг)
90.03 (Налог на добавленную стоимость)                90.02 (Налог на добавленную стоимость, исчисляемый из выручки от реализации продукции,
товаров, работ, услуг)
90.05 (Прочие налоги и сборы из выручки)               90.03 (Прочие налоги и сборы, исчисляемые из выручки от реализации продукции, товаров, работ, услуг)

91.02 (Операционные расходы)                                91.04 (Прочие расходы)
91.03 (Налог на добавленную стоимость)                91.02 (Налог на добавленную стоимость)
91.09 (Сальдо операционных доходов и расходов) 91.05 (Сальдо прочих доходов
и расходов)

  Постарался вспомнить. Быть может, я что-то не указал.

2015-07-24 15:03 GMT+03:00 alexandra-gsoftware notifications@github.com:

> ну, такое:
> 90.02 -> 90.04
> 90.03 -> 90.02
> и тд
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124499791
> .

## 

С уважением, Николай.

**Comment by NikolayUkleyko** [comment]
Еще один
  90.05 (Прочие налоги и сборы из выручки)           90.03 (Прочие налоги и
сборы, исчисляемые из выручки от реализации продукции, товаров, работ,
услуг)


24 июля 2015 г., 15:19 пользователь Николай Уклейко <
nikolayukleyko@gmail.com> написал:

>   Воспринял, как отчЕтов, а на деле речь о счетАх. )))
>   Попробую:
> *Было
> Стало*
> 10.12 (Амортизация МБП)                                      10.13 (Износ
> инвентаря и хозяйственных принадлежностей, инструментов)
> 10.13 (Амортизация спецодежды)                          10.14 (Износ
> спецодежды)
>
> 90.02 (Себестоимость реализации)                         90.04
> (Себестоимость реализованной продукции, товаров, работ, услуг)
> 90.03 (Налог на добавленную стоимость)               90.02 (Налог на
> добавленную стоимость, исчисляемый из выручки от реализации продукции,
> товаров, работ, услуг)
>
> 91.02 (Операционные расходы)                              91.04 (Прочие
> расходы)
> 91.03 (Налог на добавленную стоимость)                91.02 (Налог на
> добавленную стоимость)
> 91.09 (Сальдо операционных доходов и расходов) 91.05 (Сальдо прочих
> доходов и расходов)
>
>   Постарался вспомнить. Быть может, я что-то не указал.
>
>
> 2015-07-24 15:03 GMT+03:00 alexandra-gsoftware <notifications@github.com>:
>
>> ну, такое:
>> 90.02 -> 90.04
>> 90.03 -> 90.02
>> и тд
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124499791>
>> .
>>
>
>
>
> --
> С уважением, Николай.
>
>


-- 
С уважением, Николай.

**Comment by NikolayUkleyko** [comment]
Данная тема рассмотрена в других темах.
  Поэтому, если ни у кого нет вопросов, то эту тему можно закрыть.

**Comment by NikolayUkleyko** [comment]
По данной теме выполнена большая работа. План счетов сохранен в ПИ. При этом часть счетов, где **ID < 147000000**, генерируемых скриптами соответственно в ПИ не хранится. 
  Если, ни у кого нет вопросов по данной теме, пожалуйста, закройте здесь.

**Comment by alexandra-gsoftware** [comment]
они все хранятся, даже со стандартными ид, но вопрос все равно можно закрыть.

**Comment by NikolayUkleyko** [comment]
Например, 02 (Счет)
Не входит в ПИ

**Comment by alexandra-gsoftware** [comment]
входит в пи бухгалтерские счета

**Comment by alexandra-gsoftware** [comment]
если б не входил - не переносились бы аналитики

**Comment by NikolayUkleyko** [comment]
Интересная ситуация получается.
  Если, по счету 02 в контекстном меню выбрать команду **_Пространство имен...**_, то видим, что данный счет не входит в ПИ. Если, же посмотреть непосредственно ПИ **Бухгалтерские счета**, то счет 02 присутствует. Как это понимать ?
  Еще вопрос. При генерировании БД **Комплексная автоматизация** все счета загружаются из ПИ **Бухгалтерские счета** или часть счетов по-прежнему генерируется скриптами ?

**Comment by gsbelarus** [comment]
Эталон комплит.
Иду в справочник счетов.
Счет 02 -- правая кнопка - ПИ.
Вверху диалогового окна надпись:

> 02 (Счет)
> Входит в ПИ: Бухгалтерские счета

**Comment by alexandra-gsoftware** [comment]
Один и тот же ехе. Две разные базы. На обеих в AT_OBJECT этот счет есть, т.е. он входит в ПИ Бухгалтерские счета. Сравнение с ПИ Бухгалтерские счета на обеих базах не показывает различий.

Однако на тестовой базе Николая в окне Свойства, или в окне добавления в ПИ Гедымин показывает, что счет не входит никуда. 

У этого счета стандартный РУИД (ДБИД = 17). Он не входит ни в какие ПИ кроме Бухгалтерских счетов. 

Какой-то глюк отображения?

**Comment by gsbelarus** [comment]
Киньте ссылку на БД
