### ISSUE TITLE
Бухгалтерия. Главная книга. Не корректное отображение сумм в валюте

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3571]
Originally reported on Google Code with ID 3571

```
  Исследователь > Бухгалтерия > Главная книга.
  Формируем данный отчет с параметрами:
- Расшифровка по дебету;
- Расшифровка по кредиту;
- Суммы в национальной валюте;
- Суммы в валюте.

  В отчете в полях-расшифровках "Валюта" отображаются значения в национальной валюте.
Это не верно. Должны отображаются значения в валюте.
  Хоть это не пожар, а основной функционал программы - пожалуйста, исправьте это.

```

Reported by `NikolayUkleyko` on 2015-04-14 12:08:55

<hr>
- _Attachment: Рис. 1. Бухгалтерия. Главная книга. Не корректное отображение сумм в валюте.png<br>![Рис. 1. Бухгалтерия. Главная книга. Не корректное отображение сумм в валюте.png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3571/comment-0/Рис. 1. Бухгалтерия. Главная книга. Не корректное отображение сумм в валюте.png)_

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2015-04-14 13:05:01

**Comment by NikolayUkleyko** [comment]
Пожалуйста, подправьте.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by MIchaelShoihet** [comment]
Исправлено. Смотреть в ближайших exe

**Comment by iamchrisep** [comment]
Доработано. Добавлено корректное отображение сумм в эквиваленте при установленом флаге "Корреспонденция с субсчетами" и отображение сумм в валюте и эквиваленте при снятом флаге.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !

Пожалуйста, закройте тему.
