### ISSUE TITLE
При добавлении с зависимостями в ПИ типового документа затягиваются данные о рабочей организации

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3572]
Originally reported on Google Code with ID 3572

```
И совершенно зря, т.к. если удалить директора, бухгалтера, счет, и т.д., и т.п., ПИ
не потеряет целостность

```

Reported by `alexandra.gsoftware` on 2015-04-14 17:27:32

**Comment by alexandra-gsoftware** [comment]
Посмотрите это кто-нибудь плз. Становится все более актуальным.

**Comment by alexandra-gsoftware** [comment]
То же самое с типовой операцией

**Comment by alexandra-gsoftware** [comment]
вот посмотрите, что затянулось в ПИ https://github.com/GoldenSoftwareLtd/gedemin-apps/commit/316e89e347e3e4f37fb364e2c689e361613f3ae2

**Comment by gsbelarus** [comment]
Через GD_LASTNUMBER лезет. Сейчас я его прибью.

**Comment by alexandra-gsoftware** [comment]
можно и без особой жестокости, просто поправьте, ибо достала эта побочная функциональность

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by alexandra-gsoftware** [comment]
Вроде исправлено это
