### ISSUE TITLE
Отдел кадров, личная карточка

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3576]
Originally reported on Google Code with ID 3576

```
Сотрудник уволился.Есть приказ.
Через какое-то время время вернулся обратно.Приказ о приеме на работу есть. 
Однако в личной карточке он выделен  как уволенный.
В таких ситуациях руками в карточке убирать дату увольнения?
Можно ли сделать что бы находясь в личных карточках была возможность видеть движение
сотрудника.На мой взгляд здесь намного удобней смотреть движение.


```

Reported by `PogoSG` on 2015-04-17 07:07:57

**Comment by gsbelarus** [comment]
```
  1. По уволенным не подскажу.  
  2. На сколько мне известно, то на эталонной базе данных в форме Личная карточка есть
кнопки Начисления, Движения. В кадровых документах кнопка Движения это своего рода
аналог кнопке Полная карточка ТМЦ в справочнике ТМЦ.

```

Reported by `NikolayUkleyko` on 2015-04-17 07:54:37
- **Status changed**: `New`

**Comment by gsbelarus** [comment]
Reported by `NikolayUkleyko` on 2015-04-28 14:11:00

**Comment by gsbelarus** [comment]
```
Дату увольнения убирать не надо. Все отслеживается по перемещению сотрудника, которое
можно увидеть по нажатии кнопки "Движение", которая находится в ЛК. 
```

Reported by `roberto1813` on 2015-04-28 14:19:43

**Comment by gsbelarus** [comment]
Reported by `roberto1813` on 2015-04-28 15:09:05
- **Status changed**: `Invalid`

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2015-06-29 15:29:31
- **Labels added**: Type-Defect, Priority-Medium, Wage

**Comment by Gedemin** [comment]
В печатной форме "Личная карточка форма Т-2" есть поле "дата заполнения".
Сотрудник уволился.Есть приказ.
Через какое-то время время вернулся обратно.Приказ о приеме на работу есть. 
Однако в личной карточке он выделен  как уволенный.
Для того чтобы тянулась новая дата заполнения нужно заходить и перебивать дату на новую? Или можно сделать автоматическое создание новой позиции в Личной карточке с новой датой заполнения, с пустой датой увольнения и пустой причиной?

**Comment by YRozmysl** [comment]
При построении отчета надо ввести дату на которую строится отчет. На дату и ищется личная карточка, т.е. если есть 2 карточки 01-08-2000 (по которой уже уволен сотрудник) и есть карточка 10-10-2014 (новый прием).  и при построени мы указали дату текущую, то в отчет вытащится дата 10-10-2014. А то, что по сотруднику есть 2 карточки с разными датами - это нормально и  не противоречит ничему.

**Comment by Gedemin** [comment]
Так в том и проблема что личная карточка ОДНА. и по ней стоит дата увольнения.
Создавалось бы 2, то и проблемы не было бы
