### ISSUE TITLE
Бухгалтерия. Количество десятичных знаков при переходе по валюте из Журнала-ордера в Карту счета

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3579]
Originally reported on Google Code with ID 3579

```
  Исследователь > Бухгалтерия > Журнал-ордер, Карта счета
  При переходе из Журнала-ордера по конкретной валюте в Карту счета количество десятичных
знаков берется из справочника Валюты. Это не правильно ! В данном случае количество
десятичных знаков должно браться из параметров формирования Журнала-ордера.
  Пример, сформировали Журнал-ордер по счету 62.01, указав в параметрах формирования
формы количество десятичных знаков по национальной валюте и по иностранной валюте 6
(шесть). По обороту в валюте EUR переходим в Карту счета и видим, что количество десятичных
знаков по иностранной валюте стало 2 (два). В справочнике Валюты по EUR в поле Кол-во
десятичных знаков указано 2 (два.).
  Все вышеприведенное имеет силу и для других бухгалтерских отчетов: Анализ счета,
Главная книга, Оборотная ведомость.


```

Reported by `NikolayUkleyko` on 2015-04-25 13:30:21

<hr>
- _Attachment: [Рис. 1..jpg](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3579/comment-0/Рис. 1..jpg)_
- _Attachment: [Рис. 2..jpg](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3579/comment-0/Рис. 2..jpg)_
- _Attachment: [Рис. 3..jpg](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3579/comment-0/Рис. 3..jpg)_

**Comment by gsbelarus** [comment]
```
  Добавлю. При переходе из Журнала-ордера не по конкретной валюте в Карту счета количество
десятичных знаков берется из параметров формирования Журнала-ордера. Это правильно
!
  Пожалуйста, исправьте.

```

Reported by `NikolayUkleyko` on 2015-04-27 06:26:07

**Comment by NikolayUkleyko** [comment]
Пожалуйста, подправьте.

**Comment by NikolayUkleyko** [comment]
Пожалуйста, подправьте.
  Это самым прямым образом относится к типовому решению **Бухгалтерия**.

**Comment by YRozmysl** [comment]
Так, может, есть смысл вообще в числовых полях в документах сделать разрядность при отображении? Это гораздо лучше воспринимается визуально.

**Comment by iamchrisep** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !

@gsbelarus , пожалуйста, закройте тему.
