### ISSUE TITLE
Дублирование ивентов в проводнике редактора скрипт-объектов

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3585]
Originally reported on Google Code with ID 3585

```
В момент создания ивента происходит дублирование в дереве

```

Reported by `PZholnerovich` on 2015-05-14 09:44:54

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2015-06-29 16:35:33
- **Labels added**: Type-Defect, GedeminExe

**Comment by zholnerovich** [comment]
Исправлено.
