### ISSUE TITLE
AT_P_SYNC 

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3593]
Originally reported on Google Code with ID 3593

```
Переделать вышеуказанную процедуру на MERGE и вставить в апдейт БД.

```

Reported by `gs1994` on 2015-05-19 14:57:30

**Comment by NikolayUkleyko** [comment]
![image](https://user-images.githubusercontent.com/11497453/149310684-82eefe87-7c0f-48e9-a8bb-663f98805761.png)

Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
