### ISSUE TITLE
Ошибка при дублировании записи

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3601]
Originally reported on Google Code with ID 3601

```
  Исследователь > Бухгалтерия > Взаиморасчеты > Взаимозачет, Договор перевода долга.
  При дублировании записи любого ПОЛЬЗОВАТЕЛЬСКОГО документа на экране отображается
окно с ошибкой.
Имя файла            = gedemin.exe
Дата файла           = 06.06.2015
Версия файла         = 2.8.0.8377
  Пожалуйста, исправьте.

```

Reported by `NikolayUkleyko` on 2015-06-25 12:54:29

<hr>
- _Attachment: Рис. 1. Ошибка при дублировании записи.png<br>![Рис. 1. Ошибка при дублировании записи.png](https://storage.googleapis.com/google-code-attachments/gedemin/issue-3601/comment-0/Рис. 1. Ошибка при дублировании записи.png)_

**Comment by NikolayUkleyko** [comment]
![1](https://cloud.githubusercontent.com/assets/11497453/8478498/8eaa7588-20da-11e5-842c-7f7d59975518.png)

**Comment by zholnerovich** [comment]
Исправлял. Так что в новой версии

**Comment by gsbelarus** [comment]
На сайте выложил экзешник с последними изменениями. Проверить на нем. Если повторяется ошибка, то разбираться дальше.

**Comment by NikolayUkleyko** [comment]
Проверил на gedemin.exe от 03.07.2015 г. (v.2.8.0.8385).
  Работает корректно.
  Спасибо !
