### ISSUE TITLE
Бухгалтерия. Отчеты бухгалтерии. Проблемы на gedemin.exe от 06.06.2015 г. и выше

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3605]
Исследователь > Бухгалтерия > Отчеты бухгалтерии > Расчет.
  Подключившись к базе данных через gedemin.exe (v.2.8.0.8377) от 06.06.2015 г. и выше в верхнем гриде отображается произвольное количество записей, которых не должно быть вообще. Кликнув по пустому расчету в нижнем гриде данных (результата расчета) нет. Фильтрация данных не используется.
  Пример, был выполнен один расчет по НДС. Здесь должен быть только !!! один этот расчет.
  Прикрепляю скриншоты: 1 - до (gedemin.exe (v.2.6.19.8358) от 11.03.2015 г.) и 2 - после.
![1 gedemin exe 06 06 2015](https://cloud.githubusercontent.com/assets/11497453/8479166/85ba7f28-20de-11e5-907a-6d6cd924569f.png)
![2 gedemin exe 06 06 2015](https://cloud.githubusercontent.com/assets/11497453/8479168/85c3013e-20de-11e5-84b0-676b35a48ec2.png)
![3 gedemin exe 06 06 2015](https://cloud.githubusercontent.com/assets/11497453/8479167/85c1cea4-20de-11e5-805e-1947908ac4ae.png)

**Comment by NikolayUkleyko** [comment]
Запрос SELECT \* FROM GD_TAXDESIGNDATE выдает только одну реально существующую запись.
  На некоторых записях посмотрел Свойства > Ссылки.
  При удалении записей, по которым нет ссылок программа может выдать сообщение: см. рис. № 4. Некоторые записи без ссылок программа позволяет удалить.
  По тем записям, у которых есть ссылки программа отображает ссылки на таблицы: INV_CARD, INV_MOVEMENT, AC_RECORD, AC_ENTRY, USR$INV_ADDWBILLLINE, USR$WG_CHARGEREG и другие: см. рис. № 5 и № 6.
  Складывается впечатление, что форма "Расчет отчетов бухгалтерии" отображает чуть ли не все записи по таблицам.
  Вопрос: как такое вообще произошло ?
  Данную проблему необходимо устранить.
![4](https://cloud.githubusercontent.com/assets/11497453/8519890/942b4c60-23de-11e5-866a-a119786d64cc.png)
![5](https://cloud.githubusercontent.com/assets/11497453/8519892/96e83936-23de-11e5-925e-a02a92bdfe21.png)
![6](https://cloud.githubusercontent.com/assets/11497453/8519893/99eb99f2-23de-11e5-973e-a722f7ac5fb2.png)

**Comment by zholnerovich** [comment]
Вроде уже поправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо !
