### ISSUE TITLE
Формат сумм

### ISSUE THREAD

**Issue by hirurg-lybitel** [GoldenSoftwareLtd/gedemin#3608]
Надо, чтобы на уровне экзешника присутствовало разбиение вводимого числа на тысячные при вводе его в компонент TxDBCalculatorEdit, т.е. форматирование числа в реальном времени, а не только после его сохранения.

**Comment by NikolayUkleyko** [comment]
Знаешь, Юрик, с предложением о доработке компонента TxDBCalculatorEdit я уже выступал. Знаешь, чем закончилось ?...

**Comment by gsbelarus** [comment]
Технически это сделать невозможно.

**Comment by gsbelarus** [comment]
Это не наш компонент. Это экранный элемент, предоставляемый микрософт виндоуз. Пишите билу гейтсу.

**Comment by gsbelarus** [comment]
И, Коля, об этом говорили уже. Зачем еще раз, и еще раз, поднимать один и тот де вопрос? В рамках этого компонента сделать нельзя. Новый компонент с нуля мы делать не будем. Даже если и сделаем, то потом придется ПЕРЕДЕЛАТЬ ВСЕ ЭКРАННЫЕ ФОРМЫ, как в экзешникн, так и в пи.

**Comment by stasgm** [comment]
Билл сказал, что очень занят. 
Придётся делать средствами Гедымина там, где это необходимо. А часто необходимо отделять тысячные при вводе наших белорусских рублей в кассах (общепит и розница).

**Comment by gsbelarus** [comment]
Это другое дело. Не надо под это стандартный эдит использовать. Надо или свой компонент создать, специфический, именно для такого случая. Или выкручиваться на форме самому обрабатывая клавиатурый ввод и отрисовывая (выводя) сумму с разделителями.

PS: кстати, бесплатную идею подогнать могу (сам видел в какой-то программе). Для ввода сумм доступна не только цифровая клавиатура, но и изображения купюр. Жмешь на изображение -- соответствующую сумма приплюсовывается Т.е для ленивого кассира даже не надо соображать сколько цифр нарисовано на дензнаке. Кликнул по похожей картинке и готово.

**Comment by stasgm** [comment]
Ок. Примем на вооружение идею

**Comment by gsbelarus** [comment]
Сделано. Форматирование работает при последовательном вводе символов, т.е. когда курсор в конце числа находится.
