### ISSUE TITLE
Формы поменяли свое название при переходе на множественное наследование

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3610]
Формы с деревом и гридом теперь называются по мастер объекту, т.е. по дереву, а раньше назывались по детальному или просто название было прописано. Подумать как решить эту проблему. Нужно какое-то понятие главного объекта, который может быть или мастер, как, например в накладной-позиция, или детальным, как в группы товаров-товары.

**Comment by zholnerovich** [comment]
Было решение, при котором все нормально работало и не возникало никаких логических противоречий.

**Comment by gsbelarus** [comment]
Костыль -- это не решение. Тут надо именно решение.

**Comment by zholnerovich** [comment]
не было никакого костыля, просто Вы не разобрались. Все было четко и просто.

**Comment by zholnerovich** [comment]
и в чем же по вашему костыль?

**Comment by NikolayUkleyko** [comment]
У меня вопрос: практическое применение Наследование нашло ?
  Жанна и Стас уже пользуются ?
  Уже столько было сделано всяких специализированных разработок и почти ни одно из них практического применения не нашло.
