### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Сохранение настроек таблицы в текущую конфигурацию

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3611]
Исследователь > Бухгалтерия > Журнал-ордер.
  Перестали быть доступными кнопки Сохранить настройки таблицы в текущую конфигурацию и Удалить настройки таблицы в текущую конфигурацию. То есть, нельзя сохранить настройки грида в текущую конфигурацию.
  Раньше все это работало.
  Что случилось ???

**Comment by MIchaelShoihet** [comment]
Настройки грида можно сохранить, только если не указана расшифровка по дебету и кредиту. Потому что если она указана, то количество колонок может меняться, а сохранив настройки грида мы новые колонки никогда не увидим, что переодически и происходило у клиентов. Поэтому сейчас это возможность осталась только для фиксированного варианта колонок.

**Comment by NikolayUkleyko** [comment]
Теперь понятно.
  Спасибо за консультацию.
