### ISSUE TITLE
Бухгалтерия. Анализ счета. Оборотная ведомость. Не правильно сохраняются настройки грида

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3612]
Исследователь > Бухгалтерия > Анализ счета, Оборотная ведомость.
  Сохраняем в конфигурацию параметры формирования формы. Потом запускаю конфигурацию - все хорошо. Скрываю поле Наименование и нажимаю на кнопку Сохранить настройки таблицы в текущую конфигурацию. Потом, запускаю конфигурацию - тоже все верно. Но, если запустить не конфигурацию, а исходную форму Анализ счета, Оборотная ведомость, то грид в ней будет отображаться согласно последнего сохранения настроек таблицы в текущую конфигурацию.  
  Такого быть не должно.
  Все вышеизложенное имеет силу только к формам Анализ счета, Оборотная ведомость.

**Comment by MIchaelShoihet** [comment]
Да есть такое, т.к. для оборотки и анализа счета грид сохраняется в любом случае при закрытии окна. Я сейчас подправил, если указана конфигурации то настройки грида при закрытии окна не будут сохраняться, они будут сохранены только при нажатии на кнопку Сохранить настройки грида....

**Comment by MIchaelShoihet** [comment]
Ага выявилась другая вещь для этих форм, если эти формы открыты без конфигурации то после их построения настройка грида все равно будет стандартная.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Но ! Почему, в Оборотной ведомости нельзя сохранить конфигурацию по разделу (счетам) ?
