### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Автофильтр и сообщение об ошибке

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3613]
Исследователь > Бухгалтерия > Журнал хоз. операций.
  При помощи автофильтра (другие инструменты фильтрации не используются) выполнил фильтрацию данных по колонке Счет (62.01). Вызываю запись на редактирование - меняю значение в поле Дата (можно в любом поле). Нажимаю на кнопку Ok и программа выдает сообщение об ошибке (см. рис. 1). Интерпретируя, можно сказать, что грид не может правильно отобразить данные. При этом внесенные изменения в данные сохраняются.
  Причиной происхождения данной ошибки является то, что когда-то была сделана доработка по автоматическому обновлению грида Журнала хоз. операций.
![1](https://cloud.githubusercontent.com/assets/11497453/8702397/3646c766-2b20-11e5-9b33-e85305f9a7d4.png)

**Comment by NikolayUkleyko** [comment]
Продолжаем тему.
  При попытке удаления записей при активном фильтре "Поиск" (бинокль), да и при предопределенном фильтре программа выдает сообщение об ошибке. Как раз-таки никаких ссылок нет - это обычная ручная проводка. Такого быть не должно.
![2](https://cloud.githubusercontent.com/assets/11497453/9550337/4aa3b2ea-4db3-11e5-92b2-be0eadb02295.png)

**Comment by MIchaelShoihet** [comment]
Ясное дело что фильтр и поиск для удаления документа никакой роли не играет. Я скажу больше даже проводка созданное по документу к такому сообщению не приведет. А вот если в какой-то другой проводке в качестве аналитики документ будет выбран данный документ (например при создании ручной проводки), то тогда будет такое сообщение и оно будет верным. Так что внимательно проверьте проводки. К первому посту данное сообщение не имеет ни какого отношения.

**Comment by MIchaelShoihet** [comment]
Я забыл написать, что ручная проводка - это то же документ, просто не явный. И этот документ, то же может быть объектом аналитики

**Comment by NikolayUkleyko** [comment]
Я Вас понял.
  Еще раз проверил, что ссылок на документы нет (как аналитики). Добавил новые записи в Журнале хоз. операций. При использовании фильтра "Поиск" при попытке удаления некоторых записей программа выдает аналогичное сообщение. Без фильтра "Поиск" записи удалятся без проблем.

> К первому посту данное сообщение не имеет ни какого отношения.

  Это другая история, но также по Журналу хоз. операций.

**Comment by MIchaelShoihet** [comment]
Не получается смоделировать такую ситуацию. Ввожу ручную проводку потом использую фильтр поиск по одному из счетов проводки получаю выборку удаляю введенную проводку, замечательно удаляется. Необходимо более  подробный набор действий при котором проводка не удаляется.

**Comment by gsbelarus** [comment]
Надо проверить на новейшем экзешнике. Возможно это уже исправлено.

**Comment by NikolayUkleyko** [comment]
Проверил.
  При использовании любой фильтрации **изменение даты** осуществляется без проблем.
  При использовании любой фильтрации при **удалении записи** программа отображает окно с ошибкой:

![3](https://cloud.githubusercontent.com/assets/11497453/12610937/6bf1fdc0-c4fb-11e5-8e63-27fa8f2992e8.png)

**Comment by NikolayUkleyko** [comment]
Сейчас в **Журнале хоз. операций** без фильтров и сортировок нельзя удалить запись. Вышеприведенное сообщение.

**Comment by MIchaelShoihet** [comment]
Разобрались с этим вопросом. Просто нельзя было удалить запись, потому что на нее была ссылка. Тут есть вопрос с визуализацией. Суть проблемы - создаем ручную проводку по счету по которому есть аналитика документ. При создании проводки поле номер оставляем не заполненный. Документ конечно создается (с пустым номером), при этом аналитика документ заполняется автоматически (ссылка на созданный документ). Потом копируем проводку. Проводка копируется полностью включая аналитику документ (которая конечно остается ссылкой на документ из первоначальной проводки). Теперь удалить первоначальную проводку нельзя. Но пользователь не видит, что у него заполнилась аналитика документ и то что скопировалась... Проблема не очень серьезная, но встречается. Возможно как вариант сделать для ручных проводок автоматическое присвоение номера документа и запрет оставлять его пустым... Но надо подумать...

**Comment by NikolayUkleyko** [comment]
Предлагаю для документов без номера автоматически присваивать значение **б/н**.

**Comment by NikolayUkleyko** [comment]
Как вариант, удалять действительно пустое значение присвоенное аналитике **Документ**.

**Comment by NikolayUkleyko** [comment]
Еще один наиболее верный вариант.
  В Журнале хоз. операций поле **Номер** сделать обязательным для заполнения через **CreateFields**, а не физически в структуре БД. БД с существующими записями без введенного номера разархивируются без проблем. Да и будет порядок при работе с такими данными. Пользователи увидят соответствующее сообщение и поймут что не так.
  Ведь в таблице **GD_DOCUMENT** поля **_DOCUMENTDATE**_ и **_NUMBER**_ обязательны для заполнения физически в структуре БД.

**Comment by NikolayUkleyko** [comment]
Сегодня очередной раз столкнулись с подобной ситуацией.

**Comment by MIchaelShoihet** [comment]
Поле номер в ЖХО - это и есть поле номер в GD_DOCUMENT и оно обязательное, просто если оно осталось пустым, то Гедемин его заполняет пробелом. Можно обязать вводить номер ... Проблему полностью не решит... но будет правильней.

**Comment by NikolayUkleyko** [comment]
Да, согласен.

```
Option Explicit
Sub TgdcAcctComplexRecordCreateFields(Self)
'*** Данный код необходим для вызова кода определенного в gdc-классе.***
'*** При его удаления  возможно нарушение  правильной работы системы.***
  Call Inherited(Self, "CreateFields", Array(Self))
'***               Конец кода поддержки gdc-класса.                  ***
Self.FieldByName("NUMBER").Required = True
End Sub
```

Желательно предусмотреть такое в gedemin.exe.

**Comment by NikolayUkleyko** [comment]
Если, будем использовать **CreateFields**, и других изменений в gedemin.exe не предполагается, пожалуйста, закройте тему.

**Comment by gsbelarus** [comment]
Так в исходниках гедымина надо что-то менять?

**Comment by MIchaelShoihet** [comment]
Я сделаю поле номер обязательным при вводе проводки.

**Comment by NikolayUkleyko** [comment]
Возвращаемся к первому пункту.

> **_Исследователь > Бухгалтерия > Журнал хоз. операций**_.
> При помощи автофильтра (другие инструменты фильтрации не используются) выполнил фильтрацию данных по колонке Счет (62.01). Вызываю запись на редактирование - меняю значение в поле Дата (можно в любом поле). Нажимаю на кнопку Ok и программа выдает сообщение об ошибке (см. рис. 1). Интерпретируя, можно сказать, что грид не может правильно отобразить данные. При этом внесенные изменения в данные сохраняются.
> Причиной происхождения данной ошибки является то, что когда-то была сделана доработка по автоматическому обновлению грида Журнала хоз. операций.
> ![1](https://cloud.githubusercontent.com/assets/11497453/16295311/bf37e074-392e-11e6-9181-d87d266c812b.png)

Пример.
Отключаем все фильтры. В **_автофильтре выбираем счет 41.02**_. Добавляем запись (сложную проводку):
Дт 41.02 = 5 000  - Кт 42.01 = 3 000
                               Кт 42.02 = 2 000

При сохранении и/или редактировании записи программа выдает вышеприведенное окно с сообщением об ошибке. Повторюсь, запись сохраняется, но это вызывает вопросы. @MIchaelShoihet , пожалуйста, устраните недоработку.
