### ISSUE TITLE
Создание команды в Исследователе, даже если сама таблица создана быть не может

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3615]
Если при создании новой наследованной таблицы указать папку в Исследователе, где будет размещена команда вызова, и установить что наследуется от GD_CONTACT, то при охранении появится предупреждение, что от GD_CONTACT наследовать нельзя. Это правильно, но команда вызова в Исследователе создастся при этом и вести она будет в никуда.

**Comment by zholnerovich** [comment]
поправим

**Comment by zholnerovich** [comment]
Вроде как не создается, может уже поправлено?
