### ISSUE TITLE
Выбор из остатков в акте переработки

### ISSUE THREAD

**Issue by kovli** [GoldenSoftwareLtd/gedemin#3616]
Создаем приход на Контакт1 22.07.2015.  Потом создаем акт переработки 21.07.2015, в шапке указываем один и тот же Контакт1. Идем в остатки, видим то, что ввели в приходе. Выбираем и сохраняем акт переработки. Никаких проблем, хотя на 21.07.2015 остатков еще нет и в установках типового документа стоит птичка "Осуществлять контроль остатков".

**Comment by MIchaelShoihet** [comment]
А какие еще галки стоят в типовом документе. Галка контроль остатков на текущую дату может стоит или на конец месца?

**Comment by kovli** [comment]
Стоят все галки кроме "Выбор из отрицательных остатков". Т.е. стоит 6  штук.

**Comment by MIchaelShoihet** [comment]
Тогда все правильно работает. Галка "Контроль только на текущие остатки" означает что контроль идет на дату последнего движения (только по остаткам inv_balance) без проверки остатка на дату документа. Если вам необходим жесткий контроль остаков (с учетом даты) то не обходимо снять эту галку и снять галку "Контроль остатков на конец месяца" - эта галка отличается от предыдущей тем, что она разрешает выписывать товар если в пределах месяца хватает остатка.

**Comment by kovli** [comment]
Точно. Без этой галки все работает правильно.
