### ISSUE TITLE
Бухгалтерия. Выбор документа. Слетает грид

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3617]
Исследователь > Бухгалтерия > Журнал хоз. операций.
  В режиме выбора документа, настроенный грид по документам периодически слетает.
![1](https://cloud.githubusercontent.com/assets/11497453/8856619/9593cb88-3174-11e5-8d8a-093f879ceba2.png)
![2](https://cloud.githubusercontent.com/assets/11497453/8856620/95c2672c-3174-11e5-9090-28aee9ebcd60.png)
![3](https://cloud.githubusercontent.com/assets/11497453/8856622/98af8320-3174-11e5-98d9-7f2bd05c5761.png)

**Comment by NikolayUkleyko** [comment]
Все вышесказанное имеет силу не только для Журнала хоз. операций, но и для других документов.

**Comment by iamchrisep** [comment]
https://github.com/GoldenSoftwareLtd/gedemin/issues/3852
