### ISSUE TITLE
Бухгалтерия. Ошибка при отображении документов типа шапка

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3618]
Исследователь > Бухгалтерия > Журнал хоз. операций.
В режиме выбора документа типа шапка программа выводит окно с сообщением об ошибке. При этом нажав на кнопку ОК, можно выбрать документ и все сохранить. Ошибка выявлена на gedemin.exe от 16.07.2015 г., версия файла 2.8.0.8394.
![1](https://cloud.githubusercontent.com/assets/11497453/8856927/9eda09e4-3176-11e5-836b-e2f5bdd2dcb2.png)
![2](https://cloud.githubusercontent.com/assets/11497453/8856929/9fec625a-3176-11e5-8bc5-c0ad4c6c55d0.png)
![3](https://cloud.githubusercontent.com/assets/11497453/8856961/d8bcf090-3176-11e5-9ec4-3d0a0d58537d.png)
![4](https://cloud.githubusercontent.com/assets/11497453/8856962/d8f761e4-3176-11e5-8c04-ca21fab1af7c.png)

**Comment by NikolayUkleyko** [comment]
Все вышесказанное имеет силу не только для Журнала хоз. операций, но и для других документов.

**Comment by zholnerovich** [comment]
Поправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо !
