### ISSUE TITLE
Типовой документ. Реквизит 'Движение без поиска остатков'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3621]
Складской типовой документ. Реквизит Движение без поиска остатков.
  Подскажите, зачем предусмотрен данный реквизит ?
![1](https://cloud.githubusercontent.com/assets/11497453/8958061/39ea700c-360b-11e5-918d-734cb346b411.png)

**Comment by MIchaelShoihet** [comment]
Для документов изменения свойств, которые работают без контроля остатков, для ускорения работы, когда нам нет необходимости что бы выбиралась карточка именно из остатков. Так работает документ Накладная на реализацию для мясокомбинатов.

**Comment by MIchaelShoihet** [comment]
В новой версии складского движения эта галка пропадет, потому что принимается за основу, если контроля остатков нет и позиция вводится в ручную то поиск остатков осуществляться не

**Comment by MIchaelShoihet** [comment]
будет

**Comment by NikolayUkleyko** [comment]
Спасибо !

2015-07-29 16:12 GMT+03:00 MIchaelShoihet notifications@github.com:

> будет
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GoldenSoftwareLtd/gedemin/issues/3621#issuecomment-125947115
> .

## 

С уважением, Николай.
