### ISSUE TITLE
Команды перехода по записям на кнопке Меню

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3622]
Пожалуйста, подскажите, по каким критериям в одних документах, справочниках переход по записям возможен при помощи разных комбинаций клавиш: Ctrl + N / Ctrl + Alt + N или Ctrl + P / Ctrl + Alt + P. Необходимо, чтобы везде были единые комбинации Ctrl + N и Ctrl + P. Зачем и спользовать клавишу Alt. Одновременно зажать 3-и клавиши не удобно (не осьминог). Одновременно зажать 2-е гораздо удобнее. Данный режим очень удобен при просмотре и редактировании записей по таким документам, как ОС. Акт ввода в эксплуатацию и ОС. Акт ввода в эксплуатацию остатков. Вся прелесть в том, что не надо тратить время на закрытие и открытие формы документа.
![1](https://cloud.githubusercontent.com/assets/11497453/8985467/43261560-36e0-11e5-9e70-c3575899d077.png)
![2](https://cloud.githubusercontent.com/assets/11497453/8985468/4343c70e-36e0-11e5-8651-f918a7732802.png)

**Comment by zholnerovich** [comment]
поправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо !
