### ISSUE TITLE
Автоматическое удаление нужных объектов

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3624]
Добавляем в ПИ объект О1, который зависит от О2. Запись об О2 добавится в позиции ПИ перед записью об О1. Тепепь добавляем О3, который также зависит от О2. Добавится только запись для О3, так как О2 уже есть в списке. Теперь удалим О1. О2 удалится автоматом, через связь. Но, О2 был нужен О3 и теперь ПИ не будет грузится.

**Comment by zholnerovich** [comment]
Можно уточнить что за объекты, потому что с таблицей и полями все прошло гладко

**Comment by alexandra-gsoftware** [comment]
например, о1 - отчет формы, о2 - ReportGroup формы, о3 - другой отчет той же формы

**Comment by gsbelarus** [comment]
Я пока закрою, так как не вижу простой технической возможности сделать учет всех связей. Конечно, можно ввести отдельную таблицу, но она будет содержать до N \* N записей, где N -- количество позицийв пространствах имен. Это много. Непонятно, как потом передавать эту инфорацию с Пи на другие базы. И еще более непонятно, как актуализировать в соответствии с изменениями.

Фактически тут то же, что и в Делфи. Два модуля используют класс из третьего. В первом он стал не нужен и класс удалили -- получили ошибку в момент компиляции второго модуля. В момент компиляции, но не в момент удаления класса.

**Comment by alexandra-gsoftware** [comment]
может, просто при удалении давать человеку выбирать, какие связанные объекты удалить, а какие оставить? Если честно, от этого headobjectkey больше вреда, чем пользы
