### ISSUE TITLE
Ошибка при сравнении ПИ с БД

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3625]
Сравниваем ПИ с базой, где этого ПИ нет. Например в ПИ есть запись TgdcAttrUserDefined, а таблицы такой нет. Тогда сравнение вылетит.

**Comment by zholnerovich** [comment]
А можно по подробнее, чтобы понятно было

**Comment by alexandra-gsoftware** [comment]
Ну представь. Есть 2 голых эталона, без никаких ПИ. На эталоне 1 ты создаешь таблицу USR$TEST  с единственным полем USR$NAME и функцию test_function. В таблицу добавляешь одну запись. Создаешь новое ПИ. Закидываешь в нее запись из таблицы и ф-ю. Сохраняешь ПИ. Сравниваешь это ПИ  с  базой 2 (где таблицы USR$TEST нет). Получаешь ошибку, потому что Гедымин пытается сравнить запись в таблице, а таблицы нет. А в идеале сравнение должно сработать и показать: записи нет, потому что возможно там есть другая версия test_function, и тебе надо это увидеть. А из-за записи в USR$TEST сравнение вылетает с ошибкой.
