### ISSUE TITLE
Бухгалтерия. Конструктор функций. Добавить команду 'Выделить все'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3627]
Исследователь > Бухгалтерия > Типовые хоз. операции, Автоматические хоз. операции, Настройка функций
  Пожалуйста, добавьте в контекстное меню команду 'Выделить все'. Встречаются ситуации, когда необходимо выбрать все блоки функции. Сейчас приходится это делать через выделение каждого блока, что не есть удобно (если блоков больше 100). Ситуации, когда необходимо удалить все блоки, чтобы добавить новые блоки и/или скопировать все блоки из одной функции и вставить их в другую функцию. Команда 'Дубликат' с функциями отчетов бухгалтерии работает не совсем корректно.
![1](https://cloud.githubusercontent.com/assets/11497453/9089852/fa841450-3b9f-11e5-9afb-fa7b89575843.png)

**Comment by NikolayUkleyko** [comment]
Что-то эта тема пока молчит...

**Comment by zholnerovich** [comment]
Тема не заглохла. Сделано. "Выделить все" добавлено. Немного своеобразно работает (выделяет все внутри выбранного блока) но этого должно хватить

**Comment by NikolayUkleyko** [comment]
Пока не видел.
  Как проверю, так и сообщу что и как.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Но ! В контекстном меню отображается команда 'Выделить все', а в меню, отображаемом при нажатии на кнопку 'Редактировать', такой команды нет. Сделайте, чтобы в контекстном меню отображались пиктограмки для команд 'Свойства', 'Удалить', как в меню по кнопке 'Редактировать'.
![2](https://cloud.githubusercontent.com/assets/11497453/9300027/8e01a5ca-44ca-11e5-8b3e-43a638609ae4.png)
![3](https://cloud.githubusercontent.com/assets/11497453/9300028/8e2ef0d4-44ca-11e5-83a3-f6c0e5be983f.png)

**Comment by zholnerovich** [comment]
Поправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо, Паша !

**Comment by NikolayUkleyko** [comment]
Выявлена недоработка.
  При повторном нажатии комбинации клавиш **Crtl + A** снимается выделение со всех блоков и становится выделенным самый нижний блок в конструкторе функций. Такого быть не должно. То есть, при повторном нажатии комбинации клавиш **Crtl + A** выделение на всех блоках должно остаться.
  Пожалуйста, исправьте.

**Comment by zholnerovich** [comment]
И тут если все устраивает, то можно закрывать

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Большое спасибо !
:trophy:
