### ISSUE TITLE
Бухгалтерия. Конструктор функций. К контекстному меню добавить горячие клавиши и другое

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3628]
Исследователь > Бухгалтерия > Типовые хоз. операции, Автоматические хоз. операции, Настройка функций.
  Пожалуйста, к контекстному меню добавьте горячие клавиши (с отображением не только команд, но и горячих клавиш):
- Удалить (необходимо Ctrl + Del, сейчас Del);
- Копировать (Ctrl + C);
- Вырезать (Ctrl + X);
- Вставить (Ctrl + V).
  
  Предусмотрите команду 'Отмена действия (Ctrl + Z)'.
  Необходимо, чтобы все это корректно работало не только с одним блоком, но и с несколькими блоками.
  Копирование и вставка не всегда корректно работают. Так как бывают ситуации, что выделенный блок не скопировался в буфер обмена. Предположительно это происходит из-за того, что в момент выполнения команды 'Копировать' курсор не был точно указан на названии блока.
  В итоге будет гораздо удобнее работать в конструкторе функций.

**Comment by zholnerovich** [comment]
Поправлены горячие клавиши

**Comment by NikolayUkleyko** [comment]
Команду 'Удалить' сделайте одной комбинацией Ctrl + Del. Сейчас блоки можно удалять и при помощи кнопки Del и/или при помощи комбинации клавиш Ctrl + Del. Таким образом, случайно удалить блоки будет затруднительно.
  Что по поводу команды 'Отмена действия (Ctrl + Z)' ?

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@iamchrisep , спасибо !
:trophy:
