### ISSUE TITLE
Бухгалтерия. Конструктор функций. Свойства блока. К контекстному меню добавить горячие клавиши Ctrl + A

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3629]
При работе непосредственно с блоком очень не хватает сочетания клавиш Ctrl + A.
  В контекстном меню доступна команда 'Выделить все'. Этого мало. С горячими клавишами работать с блоками (свойства) будет гораздо удобнее.
  Пожалуйста, предусмотрите, для контекстного меню в наименование еще и отображение горячих клавиш в скобках. Если, это возможно.
![1](https://cloud.githubusercontent.com/assets/11497453/9134424/b1c1a278-3d0c-11e5-9b4f-bae54dc84b30.png)
![2](https://cloud.githubusercontent.com/assets/11497453/9134425/b1f39c10-3d0c-11e5-9349-931587ee8178.png)

**Comment by zholnerovich** [comment]
Тут используется стандартное контекстное меню windows, поэтому что то менять мне кажется не целесообразно.

**Comment by NikolayUkleyko** [comment]
С описанием в контекстном меню понятно. Возможно ли сделать работоспособными горячие клавиши 'Ctrl + A' ?

**Comment by zholnerovich** [comment]
'Ctrl + A тож не получится, как вариант написать свое меню, прикрепить его к каждой компоненте, на каждой форме

**Comment by NikolayUkleyko** [comment]
Если, это возможно (не спеша и качественно сделать) и ничего не затронет будет отлично. При работе с блоками конструктора функций не очень удобно отображать контекстное меню и в нем выбирать нужную команду. Через горячи клавиши гораздо удобнее и быстрее.

**Comment by gsbelarus** [comment]
Меню стандартное и используется на миллиарде компьютеров под Windows во всем мире. Если билл гейтс не включал туда Ctrl-A, значит на это был особый умысел.

Пользователю известны следующие способы выделения всего текста в поле диалогового окна:

1) При установке на него курсора TAB. Если курсор уже находится в этом поле, то последовательность TAB, Shift-TAB выделит весь текст.

2) Home, Shift-End или End, Shift-Home.

Порождать непоследовательность, перекрывая в НЕКОТОРЫХ диалоговых окнах стандартное меню, не стоит. Это запутает программу, а не упростит ее.

Стоит задать вопрос: а для чего вообще понадобилась операция выделения всего текста в поле? Причем, понадобилась так часто, что это породило проблему. Может тут кроется совсем другая задача?

**Comment by NikolayUkleyko** [comment]
Часто необходимо быстро скопировать все выражение в одном блоке и вставить его в другой.
  Все, не надо.
