### ISSUE TITLE
Бухгалтерия. Конструктор функций. Переименовать блоки типа 'Позиция отчета'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3630]
Исследователь > Бухгалтерия > Отчеты бухгалтерии > Настройка функций.
  Пожалуйста, переименуйте отображение блоков типа 'Позиция отчета' с 'Переменная' на 'Позиция отчета'. Сейчас блоки типа 'Позиция отчета' и блоки типа 'Переменная' визуально отличаются цветом, это хорошо. Но, для наглядности еще необходимо отображать наименования блоков в соответствии с их типом.
![1](https://cloud.githubusercontent.com/assets/11497453/9151190/95c307f0-3e02-11e5-8865-fad2336b5cff.png)
![2](https://cloud.githubusercontent.com/assets/11497453/9151191/968d4600-3e02-11e5-82b9-a94323acf0c8.png)

**Comment by zholnerovich** [comment]
Поправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо !

**Comment by NikolayUkleyko** [comment]
А сейчас блоки с типом 'Переменная' отображаются с именем 'Позиция отчета'.

**Comment by zholnerovich** [comment]
Коля, надо как то все свести по конструктору функций в один иссуй

**Comment by NikolayUkleyko** [comment]
Хорошо. Сперва необходимо это решить.

**Comment by zholnerovich** [comment]
ок, сделаю. а ты когда к нам вернешься?

**Comment by zholnerovich** [comment]
теперь должно работать корректно

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо !
