### ISSUE TITLE
Бухгалтерия. Конструктор функций. Добавить возможность прокрутки блоков скроллом мышки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3631]
Исследователь > Бухгалтерия > Автоматические хоз. операции, Типовые хоз. операции, Отчеты бухгалтерии > Настройка функций.
  Пожалуйста, добавьте возможность прокрутки блоков скроллом мышки.
  Сейчас в качестве дополнительной прокрутки предусмотрено только контекстное меню на полосе прокрутки. Этого недостаточно для комфортной работы с большим количеством блоков (100 и больше).
![1](https://cloud.githubusercontent.com/assets/11497453/9151265/4f5392d2-3e05-11e5-81d9-292e492e4fc3.png)
![2](https://cloud.githubusercontent.com/assets/11497453/9151266/4f763e40-3e05-11e5-87d9-f536f8603ec6.png)

**Comment by zholnerovich** [comment]
Как не странно, но программно управлять позицией скролла не получается, наверное какой то глюк компоненты

**Comment by NikolayUkleyko** [comment]
Необходимо, выяснить, глюк это или так задумано.
  Если, реализуешь это - будет замечательно.

**Comment by zholnerovich** [comment]
Это наверное можно закрывать

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Большое спасибо, Паша !
:trophy:
