### ISSUE TITLE
Бухгалтерия. Конструктор функций. Исправить ошибки в описании параметров функции MonthName

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3632]
Пожалуйста, исправьте ошибки в описании параметров функции MonthName. Вместо слова 'Абривиатура' должно быть слово 'Аббревиатура'.
![1 monthname](https://cloud.githubusercontent.com/assets/11497453/9151338/1bd3c118-3e08-11e5-97b6-6f1cea4520b1.png)

**Comment by zholnerovich** [comment]
исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо !
