### ISSUE TITLE
Бухгалтерия. Доработки для формы 'Составляющие показателя' (QQ)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3633]
**_Исследователь / Бухгалтерия / Отчеты бухгалтерии / Справочник показателей / Составляющие показателей_.**

Пожалуйста, решите следующие вопросы по данной форме:

**1**. При добавлении/дублировании записи по-умолчанию выбрано 'Минус'.
Необходимо, чтобы по-умолчанию было 'Плюс'.
Постоянно перебивать ни к чему.
Я часто работаю с этой формой и могу сказать, что в большинстве случаев имеет место положительное значение.
Уже не первый раз прошу об этом.

**2**. Нажимаем на кнопку дублирования на запись с типом показателя 'Показатель'.
В новом окне поле 'Показатель' не активно.
Необходимо перевыбрать тип показателя и тогда поле 'Показатель' станет активным.

**3**. В поле 'Показатель' не корректно работает команда 'Закрыть дерево...'.
При нажатии на данную кнопку, все деревья не закрываются, а только часть.

**4**. При отсутствии соответствующей записи в форме 'Показатель на дату' (таблица USR$ACC_TAXPOSDATE) можно добавить запись в форму 'Составляющие показателя' (таблица USR$ACC_TAXPOSVALUE).
После нажатия на F5 или закрытия данной формы, запись пропадет.
Правильно.
Ведь не была добавлена родительская запись.
Поэтому, при отсутствии соответствующей записи в форме 'Показатель на дату' сделайте не активной панель инструментов и контекстное меню (все прочие варианты добавления записей) формы 'Составляющие показателя'.

![1](https://cloud.githubusercontent.com/assets/11497453/9179630/7d865430-3fa6-11e5-87c3-afb87a67e468.png)

![2](https://cloud.githubusercontent.com/assets/11497453/9179631/7dad1ebc-3fa6-11e5-8985-1b580d2035bd.png)

![3](https://cloud.githubusercontent.com/assets/11497453/9179634/804ab936-3fa6-11e5-96bd-cea1be228b10.png)

![4](https://cloud.githubusercontent.com/assets/11497453/9179635/82087e3e-3fa6-11e5-9ec5-2c90d51adffa.png)

**Comment by gsbelarus** [comment]
> 1. В поле 'Показатель' не корректно работает команда 'Закрыть дерево...'. При нажатии на данную кнопку, все деревья не закрываются, а только часть.

Насколько я помню Закрыть дерево -- закрывает текущую ветку дерева, а не все дерево вообще. Но. надо проверить посмотреть как в других деревьях работает и в операционной системе.

**Comment by AliakseiDanilchyk** [comment]
Часто пользуюсь командой "Закрыть дерево" в исследователе. Закрываются все ветки.

**Comment by gsbelarus** [comment]
Тогда надо делать, чтобы закрывались все.

**Comment by AliakseiDanilchyk** [comment]
Сейчас проверил Справочник показателей, там тоже закрываются все ветки по команде.

**Comment by NikolayUkleyko** [comment]
Я автор доработки по закрытию деревьев в выпадающем списке.
Ставилась задача, чтобы **закрывать все деревья**, а не ветви.
Давно Евгений Бриль это технически реализовал.
В ходе работы были выявлены недоработки.

**Comment by NikolayUkleyko** [comment]
Все пункты кроме 3-го по данной теме в разработке.

По 3-у пункту.
В выпадающем списке при нажатии на панели инструментов на кнопку **Закрыть дерево...** выбираем верхнего родителя, но по факту выбирается промежуточный родитель.
Подобное уже встречалось в других формах.

**Comment by iamchrisep** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Все пункты работают корректно.
За исключением 4-го.
Сейчас при отсутствии записи в гриде **_Показатель на дату_** не активны кнопки на панели инструментов грида **_Составляющие показателя_**.
При этом, можно добавить новую запись, нажав на клавишу **Ins** или дважды кликнув мышкой.

@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
5. При нажатии на кнопку **Дубликат** на панели инструментов грида **Показатель на дату**, пожалуйста, предусмотрите копирование записей из грида составляющие показателя.
Можно сказать, копирование с позициями.

6. В гриде **Показатель на дату** в контекстное меню добавить команду **Свойства**.
