### ISSUE TITLE
ПИ. Удаление объектов, отсутствующих в ПИ (ранее они были в ПИ) из базы данных

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3634]
При установки ПИ, содержащего отчеты, программа может отобразить окно о том, что ранее такой-то отчет входил в текущее ПИ, а потом его удалили из данного ПИ.
Программа предложит варианты удаления/не удаления таких объектов (отчетов).
Выбрав, удалить все объекты, отсутствующие в ПИ, в исследователе по-прежнему будет отображаться удаленный отчет.
При запуске отчета программы выдает окно с сообщением.
Такой объект (отчет) должен быть удален из исследователя автоматически.
Пожалуйста, предусмотрите возможность корректного удаления объектов, отсутствующих в ПИ из базы данных.
![1](https://cloud.githubusercontent.com/assets/11497453/9180102/3fdbdc10-3fa9-11e5-84fc-4d7aafcf2a4b.png)
![2](https://cloud.githubusercontent.com/assets/11497453/9180104/404aafaa-3fa9-11e5-9684-d8e1166c3370.png)

**Comment by gsbelarus** [comment]
Теперь тригером, при удалении отчета, будет удаляться запись из Исследователя.
