### ISSUE TITLE
Бухгалтерия. Конструктор функций. Выделение блоков через Shift и Ctrl

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3635]
Исследователь > Бухгалтерия > Автоматические хоз. операции, Типовые хоз. операции, Отчеты бухгалтерии > Настройка функций.
  При работе в конструкторе функций с блоками не редко приходится выделять некий перечень блоков и их копировать. Например, среди более 100 блоков необходимо выделить блоки с 50 по 85. Сейчас приходится держать клавишу Shift и с 50 блока каждый блок последовательно выделять. Это не удобно, так как можно случайно отпустить клавишу Shift и тогда заново придется выделять блоки. К тому же выделять каждый блок не есть хорошо.
  В конструкторе функций клавиша Shift работает, как клавиша Ctrl. Клавиша Ctrl вообще не работает при выделении блоков. По общепринятым стандартам клавиша Shift должна работать на выделение диапазона объектов (блоков), а клавиша Ctrl - на выделение конкретных объектов (блоки). Посмотрите, как в проводнике на выделение работают клавиши Shift и Crtl.
  Пожалуйста, предусмотрите такую возможность.

**Comment by zholnerovich** [comment]
Ctrl теперь работает как Ctrl. Shift + стрелки выделяют группу блоков

**Comment by NikolayUkleyko** [comment]
Проверил.
  Shift + стрелки хорошо. Но, когда необходимо выделить блоки с 50 по 80 и все это через стрелки, то не очень удобно. Придется 30 раз выделять каждый блок. Можно ли сделать выделение группы блоков через Shift (50-й блок) и клик мышкой по последнему выделяемому блоку (80-й блок) ?

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Большое спасибо !
:trophy:
