### ISSUE TITLE
Добавление документа vs Наследование

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3636]
Проблемы описаны вот здесь:
https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/45

**Comment by NikolayUkleyko** [comment]
Хорошо, что много и красиво написано про СОЗДАНИЕ документов при помощи механизма наследования. Про ИСПОЛЬЗОВАНИЕ документов, созданных при помощи механизма наследования написано мало. 
  Есть документ исходный "Книга покупок" и есть от него наследуемый документ "Книга продаж". Не надо, чтобы в документе "Книга покупок" отображались записи по документу "Книга продаж".

**Comment by zholnerovich** [comment]
у меня возникло чувство, что используете наследование не по назначению, отсюда и проблемы возникают. Запрос и кнопку поправить пять сек, только вот надо ли?

**Comment by NikolayUkleyko** [comment]
Механизм наследования мы используем корректно. На сколько мне известно, что одна из основных возможностей механизма наследования это БЫСТРОЕ и ПОЛНОЕ создание нового документа, справочника и прочего на базе существующего документа, справочника и прочего. Использование наследуемых документов, справочников и прочего будет отличаться от исходных документов, справочников и прочего.
  Пример, есть документ "01. Накладная на получение товара" и наследуемый от него документ "01. Накладная на получение товара (общепит)". Конструктивно документы схожи, но применение их будет отличаться. При этом по каждому документу должны отображаться СТРОГО свои записи. Про подобное Александра уже писала. Вообще, механизм наследования в теории хорош. Вот и пришло время и посмотреть практическую сторону механизма наследования.

**Comment by NikolayUkleyko** [comment]
> Запрос и кнопку поправить пять сек, только вот надо ли?

  Про это уже писали. Необходимо предусмотреть ГИБКУЮ настройку таких параметров.

**Comment by zholnerovich** [comment]
А как общепит собирается использовать документ "01. Накладная на получение товара"? Зачем он ему?

**Comment by NikolayUkleyko** [comment]
Я привел пример. Если, не общепит, то можно рассмотреть реализацию и такие документы, как:
- 03. Отпуск товара на сторону (оптовая торговля);
- 03. Отпуск товара на сторону (реализация).

**Comment by MIchaelShoihet** [comment]
Книга продаж это первый опыт и он не совсем корректный. Должен быть базовый класс Книги (предположим) от которого должны наследоваться классы Книга покупок и Книга продаж. При проектировании Общепита, мы об этом как раз и подумали. Нельзя делать наследование и потом предполагать что оно будет какое-то не много не такое.

**Comment by NikolayUkleyko** [comment]
По данному вопросу с Александрой не спорю.

**Comment by gsbelarus** [comment]
Реализован механизм объектно-ориентированного наследования. В природе другого нет. Перед тем как использовать, хотя бы в википедии почитайте что это такое и не дергайте Павла.

Еще раз:
1. Есть накладная просто. Есть список накладных.
2. Делаем наследника Накладная-общепит.
3. Накладная общепит ЯВЛЯЕТСЯ накладной просто, точно также, как, например, кошка ЯВЛЯЕТСЯ млекопитающим,  а панельный жилой дом ЯВЛЯЕТСЯ строением и т.п.
4. В списке просто накладных будут отображаться и, собственно, просто накладные, и накладные-общепит.
5. В списке накладных-общепит отображаются ТОЛЬКО накладные общепит. Точно так же как в списке КОШЕК отображаются только кошки, но не отображаются дикообразы.

Кто не знаком с азбукой программирования -- это не повод, требовать переделки того, что по определению работает правильно.

Наверное, кто то спутал наследование с КОПИРОВАНИЕМ (ДУБЛИРОВАНИЕМ). Так вот -- это не оно.
