### ISSUE TITLE
Экспорт HTML, ODF, BIFF

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3637]
Сейчас недоступен. Проработать вопрос, что нам будет стоить добавить.

**Comment by zholnerovich** [comment]
Добавлены форматы: text, html, ODF, ODS
Нужно добавить мадефай на базу

**Comment by zholnerovich** [comment]
если файл один и его формат txt либо htm, то дублируем его в тело сообщения
