### ISSUE TITLE
Синхронизация ПИ

### ISSUE THREAD

**Issue by PiuPauTralala** [GoldenSoftwareLtd/gedemin#3640]
Обновила ПИ, синхронизировала с удалением всех отсутствующих объектов. 
При повторной попытке синхронизации выдается ошибка 
![123](https://cloud.githubusercontent.com/assets/11497771/9377494/391c645a-4722-11e5-894e-f011699bbffc.png)

**Comment by gsbelarus** [comment]
Так ясно же пишет. Нет в бд такого класса с таким подтипом. А в файле пи есть запись с данными, которые не могут загрузиться. Это ни разу не ошибка.

**Comment by gsbelarus** [comment]
Разработчик должен посмотреть, где находится данный класс, почему он не загружен на базу.

**Comment by PiuPauTralala** [comment]
Некорректно написала сначала, сообщение возникает при попытке сравнения содержимого базы с файлами на диске.
