### ISSUE TITLE
Невозможно добавить складской документ

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3642]
Добавляем складской документ. Таблицы, на которых он базируется, уже подготовлены (они называются USR$INV_ADDWBILL и USR$INV_ADDWBILLLINE). Других складских документов на базе нет (таблицы перенесены с другой базы посредством ПИ).
В момент добавления в диалоговом окне доступны только странички Общие и Нумерация.
Указываем Наименование, Наименование на английском (INV_ADDWBILL), шаблон (обычный складской документ), таблицу шапки и позиции. Появляются нужные для складского документа вкладки. Пытаемся перейти на Приход - получаем ошибку Failed to get object at index (индекс может быть индексом любой из страничек). В результате часть страничек исчезают. После нескольких попыток перевыбрать таблицу позиции, странички становятся доступны. Однако на странице Приход недоступен лукап для выбора поля, на который идет приход. Можно использовать поле Из другого документа вместо выбора таблиц вручную, но все кончается так же.

**Comment by gsbelarus** [comment]
В этом коде явная ошибка:

```
  if gdcObject.State = dsInsert then
    DocID := (gdcObject as TgdcTree).Parent
  else
    DocID := gdcObject.ID;

  CE := gdClassList.FindDocByTypeID(DocID, Part);

  if CE <> nil then
    CE := CE.GetRootSubType;
```

Если складской документ добавляется просто в папку, не наследуется от другого складского документа, то Parent -- это ИД папки, а не ИД родительского документа и ничего не работает.

ТАКОЕ ВПЕЧАТЛЕНИЕ, ЧТО КОД НИКТО НЕ ТЕСТИРОВАЛ ПЕРЕД ТЕМ КАК СКИНУТЬ.

Я поправил, но надо теперь сесть и методично протестировать:

1) для простого документа
2) для складского документа
3) для прайс-листа

следующее:

1) создание в корневой соответствующей папке
2) создание наследованного
3) создание наследованного от наследованного 
4) создание на основе таблиц от другого документа

для каждого:

1) настройка параметров при создании
2) настройка параметров при редактировании
3) проверить, чтобы у дочернего объекта можно было настроить параметры по иному, нежелди чем у родительского

тестировать здесь означает не просто открыл-закрыл диалог -- значит все работает, а вдумчиво пройтись по всем вкладкам и посмотреть как там взаимодействуют параметры.

И еще. Меня очень настораживает использование GetRootRelation и GetRelation. Как-то оно выглядит непоследовательно. В одном месте так, в другом так... Осоенно при настройке параметров складского документа я не пойму почему всегда берется RootRelation. Получается что для самого документа нельзя настроить? Это кто-то проверял вообще?

**Comment by gsbelarus** [comment]
@alexandra-gsoftware это еще актуально?

**Comment by alexandra-gsoftware** [comment]
вроде уже работает
