### ISSUE TITLE
А почему бы не сделать в Справке пункт - открыть документацию в интернете

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#3643]
Сделать открытие страницы на wiki gedemin - Документация. Golden Software of Belarus, Ltd
И для себя удобно и клиентам не надо ссылки диктовать или отправлять

**Comment by gsbelarus** [comment]
Главное окно - Справка - Руководство пользователя -- открывает наш сайт документации.В чем проблема?
