### ISSUE TITLE
Создание нового типа складского документа

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3644]
в идеале:
1. перевести двоичное хранение признаков в текст, в YAML
2. признаки типа документа вычислять как объединение признаков родителя (рекурсивно до самого низа) и признаков текущего типа
3. код создания нового типа вынести из диалогового окна на уровень БО (концепция MVC)

прямо сейчас можно быстро сделать:
1. в момент создания нового типа признаки копируются от родителя (так как и было, только без ошибки, когда не проверялось что там в поле Parent, папка или тип документа)
2. при изменении признаков наследника не позволяем удалять признаки, которые установлены у родителя. Должно быть понятное объяснение разработчику.
3. При изменении признаков у родителя выдаем предупреждение со списком наследников в которых надо подправить признаки (либо автоматически производить изменения в наследниках. Если же реализовать п.1.2, то данный пункт вообще не придется делать).
4. Приход\Расход добавляем возможность выбирать поля таблиц наследников.

@MIchaelShoihet

**Comment by alexandra-gsoftware** [comment]
сделайте тогда чтоб все признаки легко можно было посмотреть из кода, плз.

> > > Приход\Расход добавляем возможность выбирать поля таблиц наследников.
> > > думаете, это понадобится?

**Comment by zholnerovich** [comment]
План по доработке наследования типовых документов:
1. считывание настроек складских документов в gdClassList при загрузке
2. доработка Б-Классов для работы с настройками из gdClassList
3. доработка диалоговой формы складского документа (типовые документы)
4. тестирование
5. при необходимости провести такую же доработку для прайс листов.

Плюсы:
1. Быстрый доступ к настройкам без дергания БД
2. Легко организовать выборку признаков от всех предков
3. не нужно будет организовывать дополнительные пляски с бубном, чтобы проверять признаки. В наследниках будут храниться только их специфические признаки

Минусы:
1. незначительно будет увеличено время на загрузку, но так как это не дополнительные запросы в БД а только выполнение делфи кода, то не критично

**Comment by gsbelarus** [comment]
Очень даже может быть критично на сетях с большой латентностью, так как БЛОБы не поступают с данными выборки, а дергаются по отдельности потом. Надо на комплексной автоматизации и на реальной БД большого клиента посмотреть сколько типов складских документов, какой размер суммарный блобов, какой средний.

Возможно стоит загружать только по потребности.

**Comment by gsbelarus** [comment]
> сделайте тогда чтоб все признаки легко можно было посмотреть из кода, плз.

переведем в YAML и можно будет тогда обращаться к признакам стандартным парсером.

**Comment by zholnerovich** [comment]
В настройках не только признаки хранятся. Если будем их переводить на YAML то мне понадобится информация как это сделать

**Comment by gsbelarus** [comment]
> План по доработке наследования типовых документов

Плана особого тут не видно. Скорее декларация о намерениях. Вот что надо сделать сначала:
1. Разобраться что такое признаки
2. Когда они возникают, кем, когда создаются
3. Где, когда и как используются
4. Как хранятся в БД. На примере действующих баз оценить сколько их, сколько занимают места.
5. В какой момент и кем считываются. Где хранятся в процессе работы программы. Как идет к ним обращение.

После этого  можно делать план. План должен быть конкретным. Т.е. не "доработка Б-Классов для работы с настройками из gdClassList", а что-то вроде такого:

"сейчас признаки считываются в таком-то методе, в такой-то момент, и используются так-то. предлагается перенести их в ... и использовать следующим образом ... "

по итогам реализации оформить все в документацию на gsbelarus.com/wiki

**Comment by zholnerovich** [comment]
да это почти как обратная разработка

**Comment by alexandra-gsoftware** [comment]
а у нас нигде нет описания структуры блоба, где храняться признаки?

**Comment by gsbelarus** [comment]
Во все времена, для НОРМАЛЬНОГО программиста, наилучшей документацией являлось чтение ИСХОДНОГО КОДА. Он у нас, по случаю, открыт.

**Comment by zholnerovich** [comment]
Вода кипит при 100 градусах и пельмени варятся при 100 градусах. Как бы мы жили, если бы не это случайное совпадение? извиняюсь что не по теме

**Comment by MIchaelShoihet** [comment]
Все настройки складского документа хранятся в двоичном потоке. Сначала идет номер версии - строка, затем строка наименование таблицы шапки, строка наименование таблицы позиции, потом целое число - тип складского документа, ключ на группу отчетов - целое число, потом 4 строки - информация по закладке Приход, Далее 2 списка предустановленных контактов по приходу, Потом 4 строковых поля по расходу, потом 2 списка предустановленных контактов по расходу. Затем идет список признаков существующей карточки (наименование полей из INV_CARD), затем список признаков новой карточки (так же наименование полей INV_CARD) дальше я так понимаю не очень интересно - там идут оставшиеся настройки складского документа.

**Comment by gsbelarus** [comment]
Раскладываем по полочкам как для посетителя воскресного кружка по программированию для младших классов.

Берем тестовую БД и настраиваем складской документ. Задействуем все опции, доступные в окне. Для взамоисключающих опций -- сделаем второй тип документа. В одном настроим так, в другом -- эдак.

Теперь запускаем Гедымин в отладчике, ставим точку останова в начало кода считывания опций и методично выписываем на бумажку что, в каком порядке, какого типа и т.п.

Документируем формат двоичного потока здесь. Для проверки надо трасировать и считывание, и запись.

На основании выявленного двоичного формата предлагаем и утверждаем формат YAML документа.

Параметры типа складского документа определяют его поведение, вместе с методами и свойствами. Логично держать их в таком случае в соответствующем объекте в gdClassList.

Теперь стоит оценить объем данных на реальных базах: количество типов складских документов, суммарный размер БЛОБов с параметрами, средний размер. Оценить на сколько увеличится размер параметров, при сохранении не в двоичном потоке, а в текстовом YAML.

Когда считывать? БЛОБы считываются отдельно. С выборкой приходит только ИД блоба, который затем используется в вызовах соответствующих функций. На медленных сетях (например, VPN канал между двумя офисами через интернет) считывание большого количества БЛОБов займет существенное время.

Что делать:
1. Спросить у разработчиков ФБ (например, на форумах) не сделаны ли тут улучшения в версии 3.0. Может быть эта проблема уже отпала сама собой, тогда нам можно не пераймацца.
2. Если нет (а скорее всего так и будет), то грузить надо по мере обращения, а не сразу, при загрузке списка типов документов.
3. Альтернативный вариант -- оценить возможный максимальный размер параметров и хранить их в текстовом поле. Текстовое поле создать в таблице типов рядом с двоичным. Тогда, при считывании мы смотрим, есть ли текстовые данные и берем из них. Старые экзешники будут брать из двоичного поля. Дополнительный плюс такого подхода -- легкий апгрейд, когда конвертация параметров в текст не становит рабочие места, на которых не успели обновить экзешник.

Далее, переделываем окно типа складского документа на работу с gdClassList.

Стоит проработать всю идеологию создания/изменения/удаления типа складского документа, так как у нас есть соответствующий бизнес-класс и объект в gdClassList. Их взаимные изменения должны быть синхронизированы.

Далее, изменить код складского документа на работу с параметрами из gdClassList.

Сразу смотреть вперед. Если мы собираемся переносить логику в хранимые процедуры/триггеры, то, возможно, понадобится доступ к параметрам на стороне сервера. Как мы будем его осуществлять? Добавим в gudf.dll функции для работы с YAML? Или будем парсить параметры на клиенте и помещать их в GTT, доступную для использования в коде на сервере?

Далее, определяем надо ли, и, если да, то как будет предоставлен доступ к параметрам из макросов.

**Comment by zholnerovich** [comment]
Есть проблема с методом TgdcInvDocumentLine.GetSelectClause:
Метод возвращает какие то стандартные поля + поля признаков.

допустим есть такая иерархия складских документов: Inv1 и его наследник Inv2. и они отличаются признаками.

на уровне Inv 1 перекрыт метод GetSelectClause

Если будет вызван метод GetSelectClause на уровне Inv1 то в перекрытый метод Inv1 придет результат  стандартные поля + поля признаков Inv1

Если будет вызван метод GetSelectClause на уровне Inv2 то в перекрытый метод Inv1 придет результат  стандартные поля + поля признаков Inv1 + поля признаков Inv2

Так быть не должно. Вне зависимости каким наследником был вызван метод GetSelectClause результат в перекрытом методе Inv1.GetSelectClause должен прийти одинаковым

**Comment by gsbelarus** [comment]
Почему?

С точки зрения объектно-ориентированного программирования все работает правильно. Нарисуйте схему, подобную этой:

http://gsbelarus.com/gs/images/gs/2014/polymorphism.png

(взято тут: http://gsbelarus.com/gs/wiki/index.php/%D0%9D%D0%B0%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%BE%D0%B2_%28%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0%29)

И покажите пальцем где именно будет проблема. С тем местом и надо будет разобраться.

**Comment by alexandra-gsoftware** [comment]
если признаки в наследованом док-те  могут меняться (не добавляться, а удаляться), то да, есть проблема. Но разве так может быть?

**Comment by gsbelarus** [comment]
В наследованном документе могут ТОЛЬКО ДОБАВИТЬСЯ признаки.

**Comment by alexandra-gsoftware** [comment]
и в блобе/ямле будут только добавленные? Тогда все ок.

**Comment by zholnerovich** [comment]
Разбор потока складского документа
http://gsbelarus.com/gs/wiki/index.php/%D0%A0%D0%B0%D0%B7%D0%B1%D0%BE%D1%80_%D0%BF%D0%BE%D1%82%D0%BE%D0%BA%D0%B0_%D1%81%D0%BA%D0%BB%D0%B0%D0%B4%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0

**Comment by zholnerovich** [comment]
http://www.sql.ru/forum/1172213-a/firebird-3-vyborka-i-blob

**Comment by gsbelarus** [comment]
В вики нельзя ни удалить, ни переименовать. Согласовывайте название пернд тем как создать страницу. Потому что это никакой не поток складского документа. И описать можно по нормальному, создав страничку юнита, прописав там типы, классы и т.п.

**Comment by gsbelarus** [comment]
Сейчас не трогайте. Опять все самому делать придется.

**Comment by zholnerovich** [comment]
Как жаль что здесь нет смайлика, который бьется головой о стену

**Comment by gsbelarus** [comment]
Я смотрю на данные, и такой вопрос: а зачем нам вообще бинарный поток. Там же не так много параметров -- переделать все в поля в таблице с типами. Или создать доп таблицу для признаков типов складских документов. Тогда и YAML никакой не нужен и в файле ПИ сразу будут видны все настройки и все изменения, и вручную (их макросов) можно спокойно править параметры.

**Comment by MIchaelShoihet** [comment]
Да это было бы идеально. Причем не просто сделать отдельную таблицу, но и свой класс, что бы в случае необходимости можно было бы сделать ПИ содержащее только конкретные настройки документа, а не весь документ. Сейчас если необходимо добавить отдельный признак сохраняется весь типовой документ и если у пользователя что-то менялось, то все затрется.

**Comment by gsbelarus** [comment]
Напрашивается создание отдельного бизнес-класса для опции типа документа:

```
CREATE TABLE gd_documenttype_option (
  id                    dintkey,
  dtkey                 dintkey,
  op                    CHAR(1) NOT NULL,
  option_name           dname,
  int_value             dinteger,
  str_value             dtext255,
  relationkey           dforeignkey,
  relationfieldkey      dforeignkey,
  disabled              ddisabled,

  CONSTRAINT gd_dt_option_chk_op CHECK (op IN ('A', 'S'))
);
```

Тогда отпадают все проблемы с хранением, отображением, переносом через ПИ и т.п. Упрощается, точнее сводится к стандартным манипуляциям, работа с базой данных.

Загружать можно отдельно от типов документов, что ускорит начальную загрузку системы.

Операция A или S будет показывать как опция применяется: добавляется или вычитается из результирующего значения. Т.е. мы сможем через ПИ передать признаки документа, которые ДОБАВЯТСЯ к тем, что есть в БД клиента, или, наоборот, уберутся из них. Надо ли это, стоит обсудить.

Код загрузки признаков будет проверять на дублирование (а оно будет после конвертации бинарных потоков на клиентских БД и последующей загрузке настроенных ПИ). Дублирующиеся записи удаляются, причем оставляются те, которые связаны с ПИ.

Опции, помеченные через disabled, не используются, но и не удаляются из таблицы.

**Comment by zholnerovich** [comment]
Тут надо еще обсудить прайсы, и их опции, возможно тогда надо делать два бизнес-класса

**Comment by gsbelarus** [comment]
ЗАЧЕМ? каждая опция хранится отдельной строкой в привязке к типу документа. Никаких отдельных классов не надо. Их вообще не надо привязывать к складскому документу, а просто к типу документа, самому корневому.

**Comment by zholnerovich** [comment]
А можно расшифровать поля, а то если честно, то не понятно что это за структура

**Comment by alexandra-gsoftware** [comment]
а можно пример?
есть документ. Приход оформляется на usr$todepotkey в позиции, расход - на usr$fromdepotkey в шапке. Используются остатки. Есть выбор из отрицательных остатков. Нет выбора из справочника. Фром-поле -usr$inv_costaccncu. Ту-поля: usr$inv_costretailncu, usr$inv_barcode. Как это будет храниться?

**Comment by gsbelarus** [comment]
Подумайте. все же очевидно.

**Comment by alexandra-gsoftware** [comment]
Я бы добавила почти все поля в GD_DOCUMENTTYPE, а в дополнительной таблице хранила бы только признаки старой и новой карточки, и признаки для выбора из отрицательных остатков.

**Comment by gsbelarus** [comment]
Для каждого признака отдельная запись в таблице gd_documenttype_option. Т.е. для ОДНОГО типа складского документа в этой таблице будет 5-7-20... записей.

**Comment by MIchaelShoihet** [comment]
Если уже делать отдельную таблицу так выносить туда все признаки. Тогда вы сможете сделать отдельное ПИ и убрать у документа скажем контроль остатков и точно не затронув никакие другие настройки.

**Comment by alexandra-gsoftware** [comment]
А как перенести с эталонной базы куда-нибудь факт, что признак "вычитается"? В любом другом механизме мы бы просто удалили его из ПИ, а теперь его всегда надо хранить с признаком "S" или Disabled?

**Comment by gsbelarus** [comment]
в обычной жизни -- просто удалить. это такой же бо, как и все остальное. признак S задумывается как возможность принудительно убрать признак у клиента, даже если до этого он там, непосредственно на базе клиента, был установлен.

**Comment by alexandra-gsoftware** [comment]
мне кажется это не нужно. С клиентами, которые уже есть, все равно придется руками что-то править, а с новыми договорились использовать наследование. Кстати, в этом случае вызывает сомнение факт, что у наследника признаки только добавляются....

**Comment by MIchaelShoihet** [comment]
Какая разница где оно хранится, более того в этом случае контроль можно сделать и на уровне базы данных и потом поля настройки складского документа совсем не нужны простому документу или прайс-листу. Я однозначно за предложенную структуру.

**Comment by alexandra-gsoftware** [comment]
я про признак S

**Comment by gsbelarus** [comment]
Пока план такой:
1. таблица для бизнес класса TgdcDocumentTypeOption в скриптах
2. делаем бизнес-класс
3. при загрузке списка типов документов Options не грузим. даже из запроса его исключить надо.
4. делаем TgdInvDocumentEntry = class(TgdDocumentEntry) где определяем и храним все признаки. При этом, при обращении к признаку проверяем а были ли признаки прочитаны из бд. Если нет, то смотрим: а есть ли признаки в новой таблице. Если есть, то читаем из нее и заполняем внутренние поля в объекте. Если нет, то читаем поле options, разбираем его, заполняем внутренние поля, сохраняем в новую таблицу.
5. у TgdInvDocumentEntry должно быть свойство, которое показывает, что признаки были изменены и метод для записи в БД.
6. Диалоговое окно типа складского документа внешне оставить как есть, только теперь оно будет работать не с двоичным потоком options, а с TgdInvDocumentEntry.
7. стоит подумать над упрощением добавления опций в ПИ, так как после редактирования типа документа в диалоговом окне не совсем очевидно какие изменения произошли в списке опций и что надо не забыть добавить в ПИ.
8. По аналогии -- TgdInvPriceEntry

**Comment by gsbelarus** [comment]
Остается вопрос с множествами. Точнее, надо ли нам манипулировать отдельными элементами множества? Например, к тому что установлена у клиента вручную, установить настройкой еще какой-то флаг.

Если не надо, то формируем строку из имен элементов множества, через запятую, и храним как один параметр. Соответственно, при загрузке из ПИ будет устанавливаться строго значение, которое есть в ПИ.

Если надо, то тогда на каждый элемент множества -- отдельная запись в gd_documenttype_option c булевским флагом. True -- входит во множество. False -- не входит.

**Comment by alexandra-gsoftware** [comment]
Если Использовать справочник и Использовать остатки - это сейчас элементы множества, сделайте их отдельными записями

**Comment by gsbelarus** [comment]
Скорее всего все лучше булевскими флагами хранить и не дурить себе голову с преобразованием в строку и обратно.

**Comment by gsbelarus** [comment]
Признаки складского документа будут оформлены ввиде свойств класса TgdInvDocumentEntry. Скорее всего внутри следует держать флаг прочитаны они или нет, и исчитывать при знаки для конкретного типа складского документа при первом обращении к ним. Хотя тут надо эксперементировать, и, в первую очередь, знать общее количество признаков на рабочих базах. Поскольку, возможно, окажется быстрее считать все признаки, для всех типов скопом, вместо того, чтобы дергать их для каждого типа по-одному.

Плохо, что такая оценка, хотя о ней и говорилось, так и не была произведена.

Теперь про изменение и запись в БД. Для каждого признака, внутренне, можно завести два поля: для хранения текущего значения и предыдущего. При считывании из БД оба поля заполняются одним значением. При изменении -- пишется в текущее. 

Тогда можно предусмотреть два метода: Revert и Save. Первый выполняет откат всех изменений, т.е. присваивает текущие значения из предыдущих. Второй -- записывает изменения в БД. На вход второго метода должна передаваться транзакция на которой выполнять запись. Если транзакция не передана, то создается внутренняя для выполнения операции.

Вызывать эти методы будет бизнес объект типа документа.

Вызывать эти методы сможет и программист непосредственно, например, если начнет менять признаки из макросов.

**Comment by zholnerovich** [comment]
1) Предлагаю создать отдельный класс для признаков TgdInvOptions, в TgdInvDocumentEntry добавить свойство InvOptions: TgdInvOptions и метод GetInvOptions(т.е если объекта нет, то он создается)
плюсы: 
  один объект будет спокойно обслуживать два объекта шапку и позицию, не надо для них        держать дубляж
  вся реализация будет вынесена за пределы TgdInvDocumentEntry, где она собственно и не нужна

2) gdClassList не должен заниматься сохранением опций (кроме момента когда требуется пересохранить опции в новый формат). Его задача считывать и поддерживать опции в актуальном состоянии и передавать их для работы классам TgdcInvDocument и TgdcInvDocumentLine

3) Для изменения опций или создания новых есть класс TgdcInvDocumentType, это его непосредственная задача. После изменения опций он найдет соответствующий объект TgdInvOptions и поменяет в нем опции или даст команду их перечитать 

Вообщем я за то чтобы каждый занимался своим делом

**Comment by gsbelarus** [comment]
Можно и так. Только все равно надо держать новое и старое значение. Чтобы сохранять в БД только то, что надо.

**Comment by gsbelarus** [comment]
Как давно у нас headerrelkey, linerelkey переместились из потока опций в отдельные поля в таблице gd_documenttype? Т.е. можно ли их игнорировать при считывании потока, полагаясь на значения из полей таблицы?

**Comment by MIchaelShoihet** [comment]
Они туда переместились очень давно, когда появились документы пользователя. Исторически у нас сначала были только складские документы, потом появились прайсы и только потом документы пользователя, тогда и появились отдельные поля, т.к. для документа пользователя ничего больше не надо было.

**Comment by gsbelarus** [comment]
Надо ли делать возможность устанавливать на клиентской бд признаки типа складского документа, которые нельзя будет затереть/переопределить загружая ПИ?

**Comment by gsbelarus** [comment]
На предыдущий вопрос надо дать ответ.

И еще вопрос: в признаках, которые массивы (полей, контактов), порядок имеет значение или нет?

**Comment by MIchaelShoihet** [comment]
По второму вопросу - значения нет, по первому теоретически такого не должно быть, что бы были такие признаки,
