### ISSUE TITLE
Банк. Ошибка при добавлении документов в выписку типа 'Платежное поручение'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3645]
Исследователь > Банк и касса > Банковская выписка.
  При попытке добавления документов в выписку типа "Платежное поручение" появляется окно с сообщением об ошибке.
  Пожалуйста, устраните.

  Ошибка выявлена на gedemin.exe:
- Дата файла = 18.08.2015
- Версия файла = 2.9.0.8415

Ошибки нет на gedemin.exe:
- Дата файла = 11.03.2015
- Версия файла = 2.6.19.8358

![1](https://cloud.githubusercontent.com/assets/11497453/9462708/3afd10ce-4b20-11e5-8f75-ea974d7d5a8a.png)

**Comment by gsbelarus** [comment]
У платежного поручения нет позиций. Естественно что при попытке создать TgdcUserDocumentLine -- будет ошибка. Так как она в макросе это не сюда, а к @alexandra-gsoftware в проект gedemin-apps.

**Comment by alexandra-gsoftware** [comment]
странно. мы исправляли это несколько  месяцев назад

**Comment by NikolayUkleyko** [comment]
Исправляли в ПИ, а не gedemin.exe ?
  Суть в том, что в некоторых случаях не желательно устанавливать новые ПИ (в данном случае по Банку): все затрет. А здесь просто gedemin.exe обновили.
:worried:

**Comment by alexandra-gsoftware** [comment]
там косяк в пи. Старый экзешник гасил ошибку в этом месте

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
