### ISSUE TITLE
ReadOnly у полей новой карточки в гриде складского документа

### ISSUE THREAD

**Issue by flakekun** [GoldenSoftwareLtd/gedemin#3647]
В конце 2013 года были сделаны изменения в форме `gdc_dlgInvDocument_unit` из-за которых у приходного документа, выбирающего позиции из справочника ТМЦ недоступны для редактирования поля с префиксом `CARD_` (хотя эти поля созданы для ссылок из `TO_` признаков). Чтобы появилась возможность изменять их необходимо поставить галочку `Разрешить изменять признаки существующей карточки`.
Так и задумывалось? Может галочка должна влиять только на ReadOnly у `CARD_` полей созданных для `FROM_` признаков? Ведь галочка не влияет на простые `TO_` признаки, а только на вспомогательные поля созданные для `TO_`-ссылок.

**Comment by MIchaelShoihet** [comment]
Галка вообще не влияет на to признаки. Изменения являются исправлением. Теперь поведение программы полностью отвечает названию признаков, что бы их можно было изменять надо поставить соответствующие галки и правильная настройка приходной накладной как раз в том что бы их поставить. Тут конечно было разночтение - в приходной накладной эти признаки являются признаками новой карточки, но так было сделано, что в программе они остаются FROM признаками и поэтому на них действую общие правила. Поэтому для правильной настройки приходной накладной надо поставить эти галки, так же как надо убрать галку контроля остатков, добавить галку выбора из справочника товаров и т.д....

**Comment by MIchaelShoihet** [comment]
Согласитесь, что если переделать в приходной накладной FROM признаки на TO это приведет к тому что придется переписать половину кода, а так только поставить галки...

**Comment by flakekun** [comment]
Хм. Но в приходной накладной и есть `TO_` признаки (новой карточки). `FROM_` полей в гриде там нет (не выбираем из остатков). И даже если эту галочку ставить обязательно, то смущает ее поведение: 
- снята - простые `TO_` можно менять, ссылки `TO_` (`CARD_`) - нельзя
- поставлена - все можно менять

Странно что 'Разрешить изменять признаки **существующей карточки**' влияет на принаки новой карточки.

Хотя, может я просто придираюсь - будем ставим галочки.
