### ISSUE TITLE
Бухгалтерия. Уровни аналитики. Предупреждение о некорректных параметрах

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3648]
**_Исследователь > Бухгалтерия > Журнал-ордер**_.
  Пожалуйста, предусмотрите возможность отображения соответствующего сообщения (до нажатия на кнопку F5 или "Построить отчет") при вводе некорректных параметров в блоке **Уровни аналитики**. Сейчас при вводе некорректных значений параметров в блок **Уровни аналитики** программа отображает очень страшное сообщение об ошибке. Не каждому пользователю может быть известно, что в блоке **Уровни аналитики** в качестве значений параметров необходимо вводить **только !!!** цифры через запятую в необходимой последовательности.
![1](https://cloud.githubusercontent.com/assets/11497453/9548870/9a5cde36-4dab-11e5-9ab8-e6ab1c17cac2.png)
![2](https://cloud.githubusercontent.com/assets/11497453/9548873/9ddbc4fa-4dab-11e5-8163-027a7e036f4c.png)

**Comment by NikolayUkleyko** [comment]
Сейчас, даже не заполняя реквизит **Уровни аналитики** и формируя **Журнал-ордер** программа выдает окно с сообщением об ошибке:

![3](https://cloud.githubusercontent.com/assets/11497453/12373061/16285996-bc7e-11e5-80dd-cbdeb423a541.png)

  Так не должно быть. По-умолчанию в реквизите **Уровни аналитики** ничего не введено. Соответственно и "ругаться" программе не на что. Только, при вводе некорректных значений (отличных от 1 или 1, 2, 3 и т.п.) программа должна ругаться.

**Comment by gsbelarus** [comment]
Новейший экзешник надо взять.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо !
