### ISSUE TITLE
Не срабатывает ивент из родительской формы

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3649]
Есть наследованная форма. В родительской для кнопки определен ивент. В наследованной он не срабатывает, пока мы не определим ивент (хотя бы и пустой).

**Comment by alexandra-gsoftware** [comment]
иногда срабатывает. Там более сложная комбинация.

**Comment by gsbelarus** [comment]
какая?

**Comment by alexandra-gsoftware** [comment]
а чтоб я знала)) Я так и не поняла, но там надо было открыть родительскую форму, а потом наследованную форму, и еще какой-то неизвестный фактор. А на последнем ехе точно осталась эта проблема? Может, уже починили?

**Comment by alexandra-gsoftware** [comment]
вроде починили.
