### ISSUE TITLE
Relation и RelationLine у документа.

### ISSUE THREAD

**Issue by PiuPauTralala** [GoldenSoftwareLtd/gedemin#3651]
У объекта типового пользовательского документа есть два свойства Relation и RelationLine.
На старом exe там были имена таблиц шапки и позиций соответственно. Сейчас пусто.

**Comment by MIchaelShoihet** [comment]
Имеется ввиду наверное класс TgdcUserDocument, потому что у класса типового пользовательского документа TgdcUserDocumentType эти свойства называются DocRelationName DocLineRelationName и они работают

**Comment by PiuPauTralala** [comment]
Вы правы.

**Comment by gsbelarus** [comment]
Восстановлено, но для совместимости со складскими документами лучше использовать RelationName и RelationLineName.
