### ISSUE TITLE
RelationName vs DocRelationName

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3652]
На уровне TgdcBaseDocumentType есть свойства:

```
    property DocRelationName: String read GetDocRelationName;
    property DocLineRelationName: String read GetDocLineRelationName;
```

На уровне TgdcInvDocumentType:

```
    property RelationName: String read FRelationName write FRelationName;
    property RelationLineName: String read FRelationLineName write FRelationLineName;
```

Они могут отличаться чем-то? В чем смысл свойст и там, и там?

**Comment by MIchaelShoihet** [comment]
Я так понимаю чисто исторически. Т.к. класс TgdcInvDocumentType был создан раньше... конечно надо оставить только одно свойство... Но возможно для совместимости лучше уже ничего не трогать.

**Comment by zholnerovich** [comment]
вот что есть во враперах по этому поводу:

function TwrpGdcUserDocumentType.Get_DocLineRelationName: WideString;
begin
  Result := GetGdcUserDocumentType.DocLineRelationName;
end;

function TwrpGdcUserDocumentType.Get_DocRelationName: WideString;
begin
  Result := GetGdcUserDocumentType.DocRelationName;
end;

Больше вроде ничего (100% ручаться не буду)
Так что не вижу проблемы избавиться от любой пары свойств

**Comment by gsbelarus** [comment]
Это уже закрыто.
