### ISSUE TITLE
Неработает подстановка типовой операции в позиции банковской выписки

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#3654]
Если для позиции банковской выписки в типовых документах была прописана функция установки типовой операции, то на новом exe она не работает. Вообще не вызывается. Для других документов все нормально.

**Comment by MAliaksandr** [comment]
+

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Закройте тему.
