### ISSUE TITLE
Системные поля и триггеры  в справочниках

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3656]
Возможно ли в следующие справочники добавить системные поля и триггеры, чтобы в будущем  при обновлении ПИ избежать проблемы затирания:
1. Тип отработанных часов USR$WG_HOURTYPE
2. Виды отпуска USR$WG_VACATIONTYPE
3. Должности 
4. Типы больничных USR$WG_ILLTYPE

**Comment by AliakseiDanilchyk** [comment]
Вероятно, имеются в виду поля EDITIONDATE, EDITORKEY

**Comment by YRozmysl** [comment]
Да, именно эти поля. Но, чтобы при редактировании они соответственно менялись, на триггерах или как то-то там еще

**Comment by NikolayUkleyko** [comment]
Вопрос ?
  Если, пользователь вызвал на редактирование запись в справочнике и ничего не меняя, нажал клавишу **ОК**. В результате поменяются значения в полях EDITIONDATE, EDITORKEY. В ходе разработки ЗП и ОК выполнены некоторые доработки для данного справочника и прочих расчетов. То есть, необходимо обновить записи в справочнике. При очередной установке ПИ, такая запись в справочнике не обновится.

**Comment by gsbelarus** [comment]
В этом и вопрос, что автоматически сделать невозможно. Или так, или так будет плохо. А не автоматически -- ну, кто будет читать сотни предупреждений/вопросов в процессе загрузки?

**Comment by YRozmysl** [comment]
При обновление будет  сервисное окно "Конфликт обновления данных" в данном случае, где будет все видно, что поменялось в репозитории, а что в базе. И пользователь, которые устанавливает ПИ сам выбирает, оставить или затереть. Это гораздо лучше, чем просто молча все затрет.

**Comment by NikolayUkleyko** [comment]
Когда будет это сделано, тогда и посмотрим.

**Comment by YRozmysl** [comment]
В твоем примере все будет хорошо. При обновлении ПИ сравниваются версия ПИ + editiondate. Т.е. если на базе поменяется просто только editiondate  версия ПИ на базе в которое оно входит не сменится. Следовательно, при загрузке нового ПИ, версия которого будет выше, все эти ситуации сразу будут отслеживаться.

**Comment by NikolayUkleyko** [comment]
ОК !

**Comment by gsbelarus** [comment]
При создании таблицы справочника разработчик выбирает: создавать со служебными полями, в числе которых EDITIONDATE, EDITORKEY или без них.

Я могу сделать апгрейд, чтобы изменить тип указанных выше таблиц. Если есть еще такие -- напишите.

> Но, чтобы при редактировании они соответственно менялись, на триггерах или как то-то там еще

Меняет бизнес-объект. Триггером менять не всегда желательно.

> Вопрос ?
> Если, пользователь вызвал на редактирование запись в справочнике и ничего не меняя, нажал > клавишу ОК. В результате поменяются значения в полях EDITIONDATE, EDITORKEY. 

Если в окне ничего не менялось, то указанные поля меняться не будут. Однако, стоит учесть, что:
1. Программист мог написать код в окне, который меняет объект. Т.е. объект изменится, хотя непосредственно пользователь своими руками ничего не менял.
2. Программист мог написать код, который будет сообщать Гедымину, что объект изменился (хотя на самом деле он не менялся).

**Comment by gsbelarus** [comment]
Можно и вручную сделать:
1. В окне SQL редактора добавляем поля в таблицу-справочник:

```
ALTER TABLE t ADD editiondate deditiondate
ALTER TABLE t ADD editorkey deditorkey
```
1. В позиции ПИ находим данную таблицу и меняем ее класс с **TgdcPrimeTable** на **TgdcSimpleTable**.
2. Меняем дату редактирования объекта (или окно диалоговое открываем, что-нибудь меняем и сохраняем, или в таблицe at_relations для нужной записи увеличиваем дату).
3. Пересохраняем ПИ.

**Comment by gsbelarus** [comment]
Для TgdcPrimeTable теперь будет создаваться поле editiondate. Апгрейд базы данных создаст такие поля на существующих таблицах.
