### ISSUE TITLE
Не перепроводится документ при удалении позиции

### ISSUE THREAD

**Issue by igor6003** [GoldenSoftwareLtd/gedemin#3657]
Если проводка в складском документе настроена по шапке, то при удалении позиции не из диалоговой, а из основной формы проводка не изменяется.

**Comment by MIchaelShoihet** [comment]
Да есть такое. Вы сами должны отслеживать такую ситуацию.

**Comment by NikolayUkleyko** [comment]
Можно попробовать воспользоваться макросом **Перепровести количество**.

**Comment by MIchaelShoihet** [comment]
Макрос - это понятно. Если проводка настроена на шапку и сумма проводки зависит от позиции (это не всегда бывает так), То на удаление позиции (DoAfterCustomProcess или DoAFterDelete позиции) надо вызывать метод CreateEntry для шапки.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
