### ISSUE TITLE
Обновления функций, методов через ПИ

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3658]
Хотелось бы знать четкие правила и условия по которых при обновлении ПИ происходит обновление ф-ций "по-тихому". Так как на практике, есть вопросы. Пример. Есть база, в которой ф-ция имеет editiondate 01.02.2014 и которая входит в  ПИ версии 100 от 01.03.2014. Далее.  Через некоторое время на базе обновляется это же ПИ, версия которого 101 от 01.01.2015, а функция о которой идет речь в этом новом ПИ имеет editiondate 01.12.2014 (там были изменения в коде). Должно ли при таких условиях, при обновлении возникать "конфликт обновления", когда надо принимать решения оставлять или же затирать ф-цию/метод, или нет? Так, как есть конкретные примеры, когда при аналогичных условиях этот конфликт есть, а есть , когда  его нет.

**Comment by gsbelarus** [comment]
При загрузке на базу из ПИ запоминается editiondate объекта и сохраняется в поле, в таблице AT_OBJECT. Назовем ее исходной датой.

Допустим, через некоторое время грузим ПИ обновилось и мы загружаем его на БД.

Тогда проверяем:

1) если текущая editiondate у объекта в базе данных равна ИСХОДНОЙ ДАТЕ, то значит объект в базе данных не менялся. Тогда смотрим на дату объекта в файле ПИ. Если она равна ИСХОДНОЙ, то значит что объект вообще не менялся, ни в базе, ни в файле и его трогать не надо. Если дата в файле новее, чем ИСХОДНАЯ, то значит что объект поменялся в файле и его надо загрузить на базу. При этом никаких сообщений дополнительных не будет.

2) если текущая editiondate новее ИСХОДНОЙ ДАТЫ -- т.е. объект был изменен в базе данных. Тогда смотрим на дату в файле ПИ. Если она равна ИСХОДНОЙ, т.е. объект в файле не менялся, то ничего не грузим и не сообщаем. Если же в файле дата новее ИСХОДНОЙ, значит объект был изменен и тут, и там. Только в этом случае возникнет окно и вопрос к пользователю какие изменения принять, а какие отклонить.

Проверь на своем примере. Если не соответствует этой логике, значит ошибка -- будем искать и исправлять.

**Comment by YRozmysl** [comment]
А  какое поле в таблице AT_OBJECT будет соответствовать понятию "исходной даты" т.е.  куда будет запоминаться editiondate объекта?

**Comment by alexandra-gsoftware** [comment]
1) как называется поле ИСХОДНАЯ ДАТА в AT_OBJECT?
2) что сохраняется в AT_OBJECT.ИСХОДНАЯ_ДАТА, если
а) ПИ обновляется, и на базе объект менялся, а в файле ПИ - нет
б) Объект менялся там и там, и юзер вручную разрешает конфликт (например, обновляет только часть полей данными из файла)?

**Comment by YRozmysl** [comment]
Вроде со всем разобрались и логика понятна.

Есть еще и 3 ситуация: если у объекта в базе данных текущая editiondate(CURR_MODIFIED) = ИСХОДНОЙ ДАТЕ(MODIFIED), но дата в файле < чем ИСХОДНАЯ ДАТА(MODIFIED). 

Спрашивается, как могла возникнуть вот такая ситуация? Скорее всего, тут был один из 2 вариантов.

1.Мы установили первый раз на базу ПИ. В момент установки CURR_MODIFIED = MODIFIED = 01-01-2016 (дата, что была в файле ПИ).
Затем пользователь делает изменение у обьекта в базе + на компьютере, где мы делали изменения, стояло время 01-01-2017.
Соответственно в базе становится MODIFIED = 01-01-2016, а CURR_MODIFIED = 01-01-2017
У меня вопрос, в случае повторного обновления ПИ, когда мы видим окно "конфликта обновления данных" в котором мы выбираем пункт оставить вариант, который теперь в базе, что происходит с датой MODIFIED? 
Она перезапишется и станет MODIFIED = 01-01-2017 = CURR_MODIFIED? Если все так, то тогда  понятно, как возникла 3 ситуация, и понятно почему нет окна "конфликта обновления данных", и почему это ПИ не обновляется. Можно, конечно изменить CURR_MODIFIED в базе, либо пересохранить ПИ  в файле с датой > 01-01-2017, но этот пример был обнаружен совершенно случайно, а объектов грузится и обновляется очень много, когда  обновления ПИ идут пакетом. Если все, что описано выше так, то вопрос можно закрывать.

2.Самый простой вариант - это, когда ПИ пересохранилось в репозиторий с неверным часовым поясом.

**Comment by YRozmysl** [comment]
Выявился следующий момент при обновлении ПИ.
Пример, есть OBJECTCLASS (TgdcAcctTransactionEntry) у которого MODIFIED(01.01.2000)  и
 CURR_MODIFIED(02.12.2014 12:59:15)  По этим датам видно, что этот объект изменялся в базе.
Далее загружается ПИ из файла в котором этот объект имеет дату 21.03.2016 16:51:51.
При загрузке у нас есть предупреждение о конфликте, все как и положено, в соответствии с 
вышеописанным алгоритмом. Мы выбираем оставить этот объект, т.е. не перезаписывать. После загрузки у нас у этого объекта даты становятся MODIFIED(02.12.2014 12:59:15) = CURR_MODIFIED(02.12.2014 12:59:15). По итогу у нас все обновилось корректно и ничего не затерлось т.е. мы увидели  различие и приняли в процессе обновления верное решение для конкретных объектов, о которых мы знаем, разумеется, что они были сделаны намеренно, учитывая пожелания заказчика - не перезаписывать.

А вот теперь самое интересное. Через некоторое время нам снова надо обновить ПИ из файла 
в котором этот же объект имеет все ту же дату т.е. он не изменялся в файле 21.03.2016 16:51:51 
На этот раз уже при загрузке видно, что в базе объект не изменялся т.е. MODIFIED(02.12.2014 12:59:15) = CURR_MODIFIED(02.12.2014 12:59:15), НО в файле дата  21.03.2016 16:51:51, поэтому в соответствии с алгоритмом все  "втихую", без каких либо предупреждений перезапишется данными из файла, ну а мы получаем головную боль.

Я даже скорее всего и предполагаю из за чего это все. Просто в процессе разработки эталонных ПИ периодически бывает необходимость разработчику пересохранять все ПИ из-за каких-то изменений в платформе, exe и так далее, когда скрипты и прочее фактически не меняется, а изменяются какие-то другие, более глубинные вещи, которые имеют больше отношение к пллатформе, механизму загрузки ПИ и т.д.
Как вот, что произошло в данном конкретном случае  [https://github.com/GoldenSoftwareLtd/gedemin-apps/commit/a4377ec5b61ae2efb62f79c78b4d4ae26a9dd8d0](url) И в процессе этих пересохранений изменятся дата объекта в файле ПИ. 
Я, конечно, понимаю, что это общепринятые алгоритмы работы с ПИ, но тогда сам 
процесс обновления ПИ будет постоянно сопровождаться затираниями и как следствие сбоем,или некорректной работы программы после обновления, таких моментов мало, может теоретически и не возникнуть вообще, но может и критично сказаться, зацепив единичные,
важные вещи, о которых уже узнаешь от бухгалтера и бывает на повышенных тонах.

Наверное, как-то иначе тут надо обрабатывать даты в случае, когда мы выбираем не перезаписывать. Повторюсь, что все вышеописанное имеет отношение ТОЛЬКО к обновлению ПИ, в моем конкретном случае - это пакет ЗПиОК.

**Comment by gsbelarus** [comment]
Да, тут надо что-то делать:
1. Или не трогать даты и тогда при каждом очередном обновлении будет задавать вопрос.
2. Или установить даты как в файле и тогда не будет спрашивать. Будет считать, что объекты идентичные, хотя это не так и будет видно на сравнении ПИ с файлом.

Первый вариант наверное правильнее.

**Comment by YRozmysl** [comment]
Тут надо, видимо, попробовать тот и тот вариант. Просто если использовать 1 вариант, то у нас со временем при обновлении будет увеличится таких вот конфликтных записей, хоть это и не так страшно, так как мы сможем все различия видеть.
А во втором варианте, у нас будет все выравниваться по датам и будем с каждым разом будет меньше конфликтных ситуаций. Но, тут  действительно при равнении, будет видно "=", хоть на самом деле нет. 
В общем я за то, чтобы протестировать на практике 2 вариант (**установить даты как в файле и тогда не будет спрашивать. Будет считать, что объекты идентичные, хотя это не так и будет видно на сравнении ПИ с файлом.**). а потом уже по итогу и определяться.

**Comment by YRozmysl** [comment]
Есть какие-нибудь подвижки по вопросу? Просто совсем скоро в связи с деноминацией на всех мелких и средних  клиентах будет обновляться ПИ пакетно. И этот вопрос всплывет в любом случае.

**Comment by gsbelarus** [comment]
Вариант 2 не пройдет. После загрузки ПИ пересчитывается контрольная сумма и если она отличается, то у файла уже будет статус не ==, а >>.

Попробую сейчас первый вариант сделать.

Тут вопрос в несколько другом. Из ПИ должна собираться база 1 в 1. Так же как из исходников на паскале компилируется всегда один и тот же гедымин. В данном случае, правильная организация должна выглядеть так:
1. Общая для всех часть зарплаты.
2. Те объекты, которые настраиваются под клиента выносятся в отдельные ПИ. Но, при загрузке эти ПИ грузятся без всяких исключений и разногласий с базой данных. Т.е. в итоге у нас будет общая зарплата + проводки вмк. Общая зарплата + проводки бмкк и т.п.

Важно, чтобы изменения из бд попадали в пи. Иначе это все равно вылезете боком рано или поздно.

**Comment by YRozmysl** [comment]
ОК, можно и первый вариант сделать, хуже точно не будет. 
 Тут понятно, что в идеале не надо править на клиентской базе стандартные вещи, которые общие для всех клиентов. Но на практике бывает, редко но бывает, когда правится стандартная вещь, например, ф-ция, которая рассчитывает пенсионный и которая одновременно делает записи  в один документ, и вот этот уже документ может содержать разную структура данных на разных клиентских базах, в зависимости от местных положений об оплате труда.  А проводки у нас теперь выделены вообще в отдельное ПИ и их можно вообще не трогать, с проводками, тут как раз вообще нет никаких проблем.  Данная проблема касается в 90% не проводок, а макросов.

**Comment by gsbelarus** [comment]
Все равно как только выявляется такая вещь, надо ее оформлять в отдельное пи.

**Comment by YRozmysl** [comment]
Да, теперь так  и делается, по мере выявления таких вот ситуаций.  Дорабатывается, по возможности, до гибкой  настройки таких вот моментов  в рамках существующего ПИ, либо выделяется в отдельное.

**Comment by gsbelarus** [comment]
По первому варианту сделано.
