### ISSUE TITLE
GetBaseClassForRelation

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3659]
Сейчас сканирует все дерево классов. Причем в процессе определения GetDistinctRelation дергается atDatabase для поиска таблицы по ИД (тоже перебор).

**Comment by gsbelarus** [comment]
В продолжение темы о внутренней оптимизации. Нуждаются во внутреннем ускорении:

atDatabase:
- Relations.ByRelationName
- Relations.ByRelationID
- RelationFields.ByFieldName
- Fields.ByFieldName

gdClassList:
- DocByTypeID
- DocByRUID

**Comment by zholnerovich** [comment]
Этим кто-то занимается?

**Comment by gsbelarus** [comment]
Там все нормально вроде. Уже оптимизировано.

**Comment by zholnerovich** [comment]
Так может тогда закрыть, чтобы в заблуждение не вводило? А то много чего оказывается сделанным, а висит открытое

**Comment by gsbelarus** [comment]
Так закрыто же.
