### ISSUE TITLE
данные в ПИ vs циклические ссылки

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3661]
у нас есть ситуации, когда 2 объекта зависят друг от друга циклично. Пример:
Компания ссылается на директора, который ссылается на подразделение, которое ссылается на компанию.
Компания ссылается на главный счет, который ссылается на компанию.
Как развязать эти зависимости при сохранении в пи?

**Comment by gsbelarus** [comment]
Сохраняйте в одном ПИ. Циклические ссылки нормально обрабатываются.

**Comment by NikolayUkleyko** [comment]
Все сделано согласно инструкции. Александра проверила.
  По-прежнему, при установке ПИ со справочниками Гедымин ругается:
![1](https://cloud.githubusercontent.com/assets/11497453/10510680/ffaec644-733c-11e5-8408-81538dd6ed4f.png)

  Посмотрите, что в отчете Неверные зависимости:
![2](https://cloud.githubusercontent.com/assets/11497453/10510833/ea1c1b0a-733d-11e5-90e1-0fa45c2579fe.png)

  Данная проблема стопорит дальнейшие работы по сохранению из демобазы данных в ПИ. Как говорится "Вам не надо - нам не надо".

**Comment by NikolayUkleyko** [comment]
По данной теме есть какие-нибудь новости и пути решения проблемы ?
  Сохранили в ПИ клиенты и банковские счета (пробовали с зависимым и без). При попытке установки данного ПИ программа выдает сообщение об ошибке.

**Comment by gsbelarus** [comment]
В пространстве имен для банка указан тип TgdcCompany. Зайти, найти в позициях ПИ такую запись, поправить тип на TgdcBank. Пересохранить ПИ и все будет работать ОК.

**Comment by gsbelarus** [comment]
Говорят, что банк может сохраниться в ПИ как TgdcCompany. Если кто сможет повторить -- проставлюсь. У меня не получилось.

**Comment by NikolayUkleyko** [comment]
Пожалуйста, две базы данных:
1. i...\Etalon\Demobase\DB\BUSINESS2015071620151006_12_02.FDB - эталонная демобаза. Содержит данные за 2014 г. На данной БД сохраняются данные в ПИ.
2. i...\Etalon\Demobase\DB\Clear\BUSINESS20151008_11_42.FDB - эталонная база данных без данных. Специально для установки ПИ с данными и дальнейшей проверки.
  Простой пример: сохранение клиентов и их расчетных счетов в одно ПИ (или несколько отдельных) осуществится без проблем. При установке такого ПИ на тестовую БД вылезет ошибка. См. выше.

**Comment by alexandra-gsoftware** [comment]
у меня только что поставились о_О
счета и клиенты в одном пи. Счета идут после клиентов.

**Comment by NikolayUkleyko** [comment]
Очень интересно, как это удалось ?

**Comment by alexandra-gsoftware** [comment]
еще раз проверила.
если в ПИ идут компания, потом счет - то ставится
если счет, потом компания - то нет (кстати, именно так сам гедымин добавляет, если добавлять компанию с зависимыми)

**Comment by gsbelarus** [comment]
Все. Теперь будут и такие кольцевые ссылки нормально обрабатываться. При условии, что все связанные в кольцо объекты в одном файле ПИ находятся.

**Comment by NikolayUkleyko** [comment]
А где новый gedemin.exe ?

**Comment by NikolayUkleyko** [comment]
На новейшем gedemin.exe пересохранил ПИ с данными. При дальнейшей установке таких ПИ возникли другие ошибки. Завтра с Александрой проработаем такие вопросы.
