### ISSUE TITLE
Перечень файлов рядом с gedemin.exe

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3662]
Здесь http://gsbelarus.com/gs/wiki/index.php/%D0%9F%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4_%D0%BD%D0%B0_Firebird_2.5._%D0%9C%D0%BD%D0%BE%D0%B3%D0%BE%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B9_%D1%80%D0%B5%D0%B6%D0%B8%D0%BC указано, что для работы программы рядом с gedemin.exe необходимо расположить следующие файлы:

**fbclient.dll
icuuc30.dll
icuin30.dll
icudt30.dll
ib_util.dll
msvcr80.dll
msvcp80.dll
Microsoft.VC80.CRT.manifest**

  Но ! В архиве gedemin (здесь http://gsbelarus.com/pw/downloads/?d=7117) возле gedemin.exe расположено больше файлов:

![1 gedemin exe](https://cloud.githubusercontent.com/assets/11497453/10659083/bb41f79c-78a5-11e5-9b21-c73a879afd78.jpg)

  Зачем добавлены две библиотеки: **libeay32** и **ssleay32** ?

**Comment by gsbelarus** [comment]
http://gsbelarus.com/gs/wiki/index.php/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2_%D0%B4%D0%B8%D1%81%D1%82%D1%80%D0%B8%D0%B1%D1%83%D1%82%D0%B8%D0%B2%D0%B0_%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D1%8B_%D0%93%D0%B5%D0%B4%D1%8B%D0%BC%D0%B8%D0%BD

Это библиотеки SSL. Используются когда Гедымин в качестве веб сервера работает.

https://ru.wikipedia.org/wiki/SSL
