### ISSUE TITLE
В Карту счета добавить поле 'Дата изменения'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3664]
**_Исследователь > Бухгалтерия > Карта счета**_.
  Пожалуйста, добавьте в **Карту счета** поле **Дата изменения**.
  Так будет гораздо удобнее и быстрее анализировать и редактировать проводки за необходимый период и за указанное количество дней внесения изменений. Достаточно указать отчетный период, не указывая счета и в Карту счета попадут все проводки. Затем, через автофильтр выявить требуемые проводки.
  Поле **Дата изменения** присутствует в **Журнале хоз. операций**. В свою очередь, в Журнале хоз. операций фильтровать (даже с заранее настроенными фильтрами) все проводки очень-очень-очень длительный процесс (все ляжет колом на том же ВМК, БМКК и т. д.).

**Comment by NikolayUkleyko** [comment]
![1](https://cloud.githubusercontent.com/assets/11497453/10728731/657d74dc-7bf5-11e5-9a21-61e45268c6cd.jpg)

**Comment by zholnerovich** [comment]
Сделано, Коля проверил.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
