### ISSUE TITLE
Обновление ПИ

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3667]
При обновлении ПИ на базе, на котрой они уже были установлены ранее возникают ошибки. Вот одна из их.

18:22:09  Добавляется объект: TgdcAttrUserDefinedUSR_MONTH_CHARGESLINE_SUBCheckSubSet, 157706968_1912201015, GD_FUNCTION
[Предупреждение] 18:22:09  Для поля MODULECODE использовано временное значение 1010001
18:22:09  Создан объект: TgdcAttrUserDefinedUSR_MONTH_CHARGESLINE_SUBCheckSubSet (TgdcFunction, 155503851)
18:22:09  Не найден объект для параметра OBJECTKEY, 157706965_1912201015 TgdcBase\TgdcAttrUserDefined\TgdcAttrUserDefinedUSR_MONTH_CHARGESLINE_SUB
18:22:09  Возможно, следует поменять порядок объектов в ПИ.
18:22:09  Добавляется объект: 157706966_1912201015, EVT_OBJECTEVENT
[Предупреждение] 18:22:09  Для поля OBJECTKEY использовано временное значение 1010001
[Ошибка] 18:22:09
попытка сохранить дублирующиеся значения (видимые в активной транзакции) в уникальном индексе "EVT_IDX_OBJECTEVENT"
Problematic key value is ("EVENTNAME" = 'CHECKSUBSET', "OBJECTKEY" = 1010001)

**Comment by alexandra-gsoftware** [comment]
Возможно, не подтянулось ПИ Зарплата - Evt_Object

**Comment by YRozmysl** [comment]
Возможно, ставил я отдельно ПИ Зарплата -макросы, при котором возникла эта ошибка. но даже если я ставлю все зависимые ПИ из папки Зарплата (23 ПИ), то возникает все равно ошибка и ругается уже вот на это 
8:29:07
Поиск объекта по потенциальному ключу:
SELECT id FROM gd_function WHERE UPPER(name) = UPPER(:name) AND modulecode = :modulecode
NAME: wg_RoundHourWage
MODULECODE: 1010001
18:29:07  Изменяется объект: wg_RoundHourWage, 147819941_375143752, GD_FUNCTION
18:29:07  Изменен объект: wg_RoundHourWage (TgdcFunction, 147041846)
[Ошибка] 18:29:07
Нарушение условий первичного или уникального ключа "AT_PK_OBJECT" в таблице "AT_OBJECT"
Problematic key value is ("ID" = 155503891)

**Comment by YRozmysl** [comment]
Если надо, есть весь лог обновления ПИ  ЗПиОК

**Comment by alexandra-gsoftware** [comment]
кстати, такое еще видела. В одном ПИ два тмц с одинаковым названием (но из разных групп). При установке Гедымин будто бы пытается их объединить (один руид пытается заменить на другой). Разве это правильно?

**Comment by gsbelarus** [comment]
Надо посмотреть какой там CheckTheSameStatement.

**Comment by gsbelarus** [comment]
Если задан, то пытается сопоставить по штрих-коду, если штрих-код не заполнен, то по имени.

Два одноименных товара в БД это огромное зло.
