### ISSUE TITLE
ПИ vs триггер vs метод БО

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3671]
В позиции приказа о приеме на работу (отдел кадров) есть поле USR$FIRSTMOVE. Это поле заполняется на _DoOnNewRecord значением Self.FieldByName("documentkey").AsInteger.

На таблицу позиции приказа о приеме на работу есть триггер AfterInsert, который обращается к USR$FIRSTMOVE. При загрузке документа из ПИ поле USR$FIRSTMOVE в триггере NULL.

Можно это как-то обойти (не меняя ПИ ЗП и ОК)?

**Comment by gsbelarus** [comment]
Заполняется в VBScript?

**Comment by alexandra-gsoftware** [comment]
да

**Comment by gsbelarus** [comment]
Проверить еще раз новешим экзешником.

**Comment by alexandra-gsoftware** [comment]
на последнем ехе приказ грузится
