### ISSUE TITLE
Бухгалтерия. Форма 'Оборотная ведомость'. Округление сумм

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3672]
**_Исследователь > Бухгалтерия > Оборотная ведомость**_.

  Сформировал форму за первый месяц - получил на конец периода одни суммы. Сформировал за форму за следующий месяц - получил на конец периода суммы, расходящиеся с суммами на конец предыдущего периода. Расхождение около 1-2 рублей. Сформировал форму с 4-я знаками после запятой - суммы без расхождений. В результате расхождения за периоды накапливаются, что не есть хорошо.
  Почему такое происходит ? Так задумано или я что-то путаю ?
![1](https://cloud.githubusercontent.com/assets/11497453/10904381/ce7fe530-8223-11e5-8ed3-010cf8df110a.jpg)
![2](https://cloud.githubusercontent.com/assets/11497453/10904386/d552b824-8223-11e5-8755-9d83b17ba71f.jpg)
![3](https://cloud.githubusercontent.com/assets/11497453/10904389/d9b9592c-8223-11e5-8436-a468945bf7a6.jpg)
![4](https://cloud.githubusercontent.com/assets/11497453/10904393/de3c94fa-8223-11e5-8a0c-bf22e0666b57.jpg)

**Comment by MIchaelShoihet** [comment]
Оно так не задумано, это простая математика. Если было три суммы с остатком скажем 0,4 то в итоге это даст 1,2 к сумме, если же мы округлим до целого то получим везде 0 и в итоге то же 0.
Для примера - 60, 10 0,4 60 - 76 0,4 60 62 0,4 в итоге на 60 1,2 в сумме при округлении останется 1 а на 10 останется 0, 76, 0 и 62 0. Если округлять каждую проводку, то баланс наверное сохранится, но тогда общая сумма может значительно отличаться... при большом количестве проводок разница может пойти и на 1000 рублей в сумме.

**Comment by NikolayUkleyko** [comment]
Благодарю Вас за ответ !
