### ISSUE TITLE
Бухгалтерия. В формы 'Журнал-ордер', 'Анализ счета' и 'Карта счета' добавить аналитику 'Типовой документ' (E/V)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3673]
**_Исследователь / Бухгалтерия / Журнал-ордер, Анализ счета и Карта счета_.**

Для удобства формирования бухгалтерских отчетов по определенным типам документов предлагаю добавить аналитику **Типовой документ**.

Это будет очень удобно при создании конфигураций по определенным типам документов.
Не будет необходимости создавать отчеты с нуля и т. д.
Например, конфигурация по амортизации ОС (будут выбраны документы **ОС. Начисление амортизации**, **ОС. Начисление амортизации (лизинг)**), конфигурация по реализации товаров (будет выбран документ **03. Отпуск товара на сторону (оптовая торговля)**).

Скажите, это возможно ?
Иначе придется делать это вручную через добавление аналитики **Типовой документ**, настройку типовых хоз. операций и перепроведение проводок по документам.

**Comment by NikolayUkleyko** [comment]
Что думаете по данной теме ?

**Comment by MIchaelShoihet** [comment]
Возможно. Но не прямо сейчас.

**Comment by NikolayUkleyko** [comment]
ОК !

**Comment by zholnerovich** [comment]
Правильно ли я понимаю, что эта аналитика будет всегда доступна для всех счетов?

**Comment by gsbelarus** [comment]
Ясное дело.

**Comment by NikolayUkleyko** [comment]
Аналитика **Типовой документ** будет всегда доступна для всех счетов, как и аналитики: **_Валюта, Года, Дата проводки, Месяц, Рабочая компания_**. То есть, такая аналитика не задается в плане счетов для счетов.

**Comment by zholnerovich** [comment]
Кто-нибудь может мне популярно объяснить что такое уровни аналитики в ЖО?

**Comment by MIchaelShoihet** [comment]
Решили пока от этой идее отказаться.

**Comment by NikolayUkleyko** [comment]
Взвесив все **за** и **против**, решил все же предложить вариант, при котором в Журнале-ордере и других бухгалтерских формах при выборе одного или нескольких значений предопределенной аналитики **_Типовой документ_** будут представлены **только обороты без отображения сальдо или с нулевым отображением сальдо**.

Следует предусмотреть вышеизложенные изменения и при работе с конфигурациями бухгалтерских форм.

Это удобно.
Отпадет необходимость в создании отдельных отчетов.

@gsbelarus , пожалуйста, откройте тему.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , сегодня вновь столкнулся с ситуацией, при которой не хватает такого функционала.
@ShlTanya , пожалуйста, изложи свою точку зрения и выполни соответствующие доработки.

**Comment by ShlTanya** [comment]
Насколько я поняла, речь идет именно о группировке по новой аналитике Типовой документ. Иначе я не вижу, чтобы, например, в форме Журнал-ордер в отборе по аналитике можно было выбрать предопределенной аналитике  Валюта, Года, Дата проводки, Месяц, Рабочая компания.

**Comment by NikolayUkleyko** [comment]
>Насколько я поняла, речь идет именно о группировке по новой аналитике Типовой документ

@ShlTanya , это не совсем аналитика Типовой документ.
Это рассматривается, как некий реквизит, параметр проводки.

>Иначе я не вижу, чтобы, например, в форме Журнал-ордер в отборе по аналитике можно было выбрать предопределенной аналитике Валюта, Года, Дата проводки, Месяц, Рабочая компания.

В форме Журнала-ордера можно задать конкретную валюту.
Рабочая компания добавлена с целью получения сгруппированных данных в разрезе рабочих предприятий.
При этом не ставилась целью возможность выбора в Look-up конкретного значения рабочей организации.

**Comment by ShlTanya** [comment]
Обсудите, пжст, данную тему с MIchaelShoihet. Именно механизм реализации. 
Журнал-ордер: достаточно ли только добавить Типовой документ в выбор Группировать по аналитике. Или нужна еще и возможность отбора по данной аналитике (то что я подумала, читая 1-й пост).

**Comment by NikolayUkleyko** [comment]
@ShlTanya , здесь все очевидно.
Необходимо добавить **Типовой документ** в выбор **_Группировать по аналитике_** и предусмотреть возможность отбора по данной аналитике.
Необходимо учесть, что при выборе группировки по типовому документу и/или отбору по конкретным документам сальдо на начало и на конец периода формирования не рассчитывать.
Так требуется, ввиду того, что сальдо в данном случае будет некорректное.
Да и не ставится целью получение еще и достоверного сальдо.
Основная идея в том, чтобы получить обороты за период по выбранным документам.

Необходимо предусмотреть рассматриваемый функционал и для конфигураций.

@ShlTanya , все вышеприведенное имеет силу только для бухгалтерских форм Журнал-ордер, Анализ счета и Карта счета.

**Comment by ShlTanya** [comment]
Если с группировкой все понятно.. то отбор по аналитике в данных журналах строится на основе реальных аналитик по счету. И в этом месте мне надо точные указания по реализации (интерфейсу).

**Comment by NikolayUkleyko** [comment]
>то отбор по аналитике в данных журналах строится на основе реальных аналитик по счету.

В Карте счета при существующем функционале выводится типовой документ.
Это не является реальной аналитикой, а дополнительным признаком, свойством проводки.

Все это делается, для того, чтобы не добавлять отдельную аналитику Типовой документ и монотонно настраивать ее по документам.
С перепроведением и прочим.

**Comment by ShlTanya** [comment]
Я все это понимаю :) 
Но.. отбор по аналитике строится автоматически из реальных аналитик.. (там нет выбора по раб. организации.. году и т.п.). Поэтому и спрашиваю.. Как правильно реализовать. 
Очень хотелось, что вы обсудили этот вопрос с @MIchaelShoihet.

**Comment by NikolayUkleyko** [comment]
>Очень хотелось, что вы обсудили этот вопрос с @MIchaelShoihet.

Хорошо, @ShlTanya !

**Comment by MIchaelShoihet** [comment]
В отбор добавить наравне с аналитиками Типовой документ и так же в отбор хорошо добавить валюту. Тогда можно построить по конкретной валюте только в бел.рублях. Получается что в отборе всегда будет 2 постоянные группы Типовой документ и Валюта. Единственно, стандартную аналитику делать всегда перед этими группами.

**Comment by ShlTanya** [comment]
Хорошо.. Значит в отбор по аналитике всегда добавляем 2 группы..

**Comment by MIchaelShoihet** [comment]
Да. Но если по счету есть аналитика, то она сначала должна идти она, а потому уже валюта и типовой документ.

**Comment by ShlTanya** [comment]
Хорошо

**Comment by NikolayUkleyko** [comment]
>Тогда можно построить по конкретной валюте только в бел.рублях.

Что очень удобно при работе с валютой и расчетом курсовых разниц.
Не так ли, @MIchaelShoihet ?

**Comment by ShlTanya** [comment]
@MIchaelShoihet нужен Ваш совет.. таблица ac_entry не содержит поля documenttypekey.. 2 выхода:
1. Добавить это поле .. проапдейтить данные (понимаю.. что таблица большаяяя). Плюсы - гораздо меньше изменений в коде и экономия времени выполнения запроса.
2. Обращаться к этому полю через gd_document.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , при 2-м варианте скорость формирования будет ли отличаться от 1-го варианта ?
Какие плюсы у 2-го варианта ?

**Comment by ShlTanya** [comment]
Не меняем текущую таблицу..

**Comment by MIchaelShoihet** [comment]
Работаем через gd_document. При этом надо формировать запрос без расчета остатков.

**Comment by ShlTanya** [comment]
ок

**Comment by NikolayUkleyko** [comment]
@ShlTanya , привет !
Есть ли новости по данной теме ?

**Comment by ShlTanya** [comment]
@MIchaelShoihet проверьте, пжст, на разных базах. Я проверила на всем что у меня было.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , большое спасибо за приятную новость.

**Comment by NikolayUkleyko** [comment]
Проверено.
В целом работает корректно.

Однако, выявлен ряд недоработок:
1. При сохранении параметров формы в конфигурацию не сохраняется выбранный (ые) типовые документы.
Только, после запуска конфигурации, выбора типового документа (ов) и пересохранении конфигурации алгоритм работает корректно.
Аналогично и для аналитики **Валюта**.

2. В форме конфигурации на закладке **Значение аналитик** не отображаются реквизиты **Валюта**, **Типовой документ**.

3. В перечне аналитик (на основной панели параметров, в конфигурации на соответствующей закладке и другое) поменять очередность с **_Типовой документ, Валюта_** на **_Валюта, Типовой документ_**.

4. В случае формирования конфигурации Журнала-ордера с выбранной аналитикой **Валюта** и выполнении перехода **_из Журнала-ордера на Карту счета_** программа отображает окно с сообщением об ошибке:
![2018-04-26_174419](https://user-images.githubusercontent.com/11497453/39313504-d283add0-497a-11e8-9f29-1e24df3d909e.jpg)

5. Аналогичное сообщение также в **Анализе счета** при сохранении в конфигурацию нескольких значений аналитики **Валюта**.

@ShlTanya , пожалуйста, устрани недоработки.

**Comment by ShlTanya** [comment]
Хорошо.. Все исправлю

**Comment by NikolayUkleyko** [comment]
При формировании Журнала-ордера по счету с субсчетами, с расшифровкой по дебету и/или по кредиту, выбранной аналитикой Типовой документ программа отображает окно с ошибкой:

![2018-05-02_175059](https://user-images.githubusercontent.com/11497453/39531002-db430d82-4e32-11e8-9c89-30b79279fe2a.jpg)

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
>Исправила

@ShlTanya , подскажи, пожалуйста, где можно увидеть сделанные изменения ?
:smile:

**Comment by YRozmysl** [comment]
Да, хотелось бы проверить. Как показала практика очень удобная аналитика для работы с ЖО

**Comment by gsbelarus** [comment]
Проверяйте новейшим экзешником и закрывайте.

**Comment by YRozmysl** [comment]
,Отлично, все работает, спасибо

**Comment by NikolayUkleyko** [comment]
>Проверяйте новейшим экзешником и закрывайте.

На сайте старая версия.

**Comment by YRozmysl** [comment]
Напиши в gedemin.ini   
[WEB CLIENT]
Token = BETA
AutoUpdate=1

**Comment by NikolayUkleyko** [comment]
>Напиши в gedemin.ini
[WEB CLIENT]
Token = BETA
AutoUpdate=1

Это я знаю.

**Comment by gsbelarus** [comment]
уже должен быть новый

**Comment by NikolayUkleyko** [comment]
@gsbelarus , благодарю !

**Comment by NikolayUkleyko** [comment]
@ShlTanya , проверил.
Работает корректно.
:ok_hand: :trophy:
Спасибо, @ShlTanya !

**Comment by NikolayUkleyko** [comment]
Переговорили с @MIchaelShoihet .
@ShlTanya , пожалуйста, убери из Журнала хоз. операций добавленные реквизиты **Типовой документ**, **Валюта**.
Они не нужны в этой форме.
Так как, любой (ручной и не только) записи в Журнале хоз. операций присваивается тип документа - **Хозяйственная операция**.
Реквизит **Валюта** существует уже давно.

**Comment by MIchaelShoihet** [comment]
Очень надо сделать. Людей раздражает лишняя аналитика.

**Comment by ShlTanya** [comment]
А можно мне скрин того, что убрать.. что-то в журнале хоз. операций я такого не вижу.

**Comment by ShlTanya** [comment]
Наверное Вы имели в виду Реквизит, который отображается как колонка.. появляется поле Описание( с операцией) и Дебет(кредит), вал ??

**Comment by MIchaelShoihet** [comment]
Поля Валюта и Типовой документ
![default](https://user-images.githubusercontent.com/11498750/41153000-1f909eca-6b1e-11e8-9967-155c32ebc6f9.jpg)

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:

**Comment by NikolayUkleyko** [comment]
Существует документ **Банковская выписка**.
У этого документа есть дочерний документ **Разноска выписки**.
При формировании проводки через документ Разноска выписки, а не через документ Банковская выписки (позиция), то в Журнал-ордер в качестве служебной аналитики **Типовой документ** попадает **_Банковская выписка_**.
Это неверно, должен быть документ **_Разноска выписки_**.

Обратите внимание, как неверно **Карта счета** отображает данную ситуацию:
![2018-09-07_165636](https://user-images.githubusercontent.com/11497453/45223277-81254080-b2bf-11e8-8986-ffc8f0ba2a87.jpg)

@ShlTanya , пожалуйста, внеси правки.

**Comment by MIchaelShoihet** [comment]
Это не стандратная ситуация. Потому что на самом деле разноска выписки - это не документ, а позиция позиции выписки. На уровне платформы такую ситуацию сложно обработать.

**Comment by NikolayUkleyko** [comment]
Хорошо.

**Comment by NikolayUkleyko** [comment]
При формировании приведенных форм по аналитике **Типовой документ** и с **количественными показателями** рассчитывается сальдо на начало и на конец периода (по сумме и по количеству).
Такого быть не должно, т.к. приняли за основу, что при использовании аналитики **Типовой документ** сальдо на начало и на конец периода не рассчитывается.

_____

![Рис  1  Количественный показатель](https://user-images.githubusercontent.com/11497453/93218269-b304f380-f772-11ea-9361-bd9b99cf3570.jpg)

![Рис  2  Количественный показатель](https://user-images.githubusercontent.com/11497453/93218295-b7c9a780-f772-11ea-8e5b-8e66abb5dcf5.jpg)

@ShlTanya , пожалуйста, поправь.

**Comment by NikolayUkleyko** [comment]
> При формировании приведенных форм по аналитике **Типовой документ** и с **количественными показателями** рассчитывается сальдо на начало и на конец периода (по сумме и по количеству).
> Такого быть не должно, т.к. приняли за основу, что при использовании аналитики **Типовой документ** сальдо на начало и на конец периода не рассчитывается.
> 
> ![Рис 1 Количественный показатель](https://user-images.githubusercontent.com/11497453/93218269-b304f380-f772-11ea-9361-bd9b99cf3570.jpg)
> 
> ![Рис 2 Количественный показатель](https://user-images.githubusercontent.com/11497453/93218295-b7c9a780-f772-11ea-8e5b-8e66abb5dcf5.jpg)
> 
> @ShlTanya , пожалуйста, поправь.

@ShlTanya , пожалуйста, поправь.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
