### ISSUE TITLE
Бухгалтерия. Форма 'Оборотная ведомость'. Не корректно работает опция 'Масштаб'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3676]
**_Исследователь > Бухгалтерия > Оборотная ведомость**_.

  При выборе масштаба 1 000 или 1 000 000 сальдо на конец периода по дебету счетов и сальдо по кредиту счетов отображаются не корректно. Сравните суммы при выборе масштаба 1 и все станет очевидно.
![1](https://cloud.githubusercontent.com/assets/11497453/11029923/5bbed53a-86db-11e5-9b7f-867efa8c7ffb.jpg)
![2](https://cloud.githubusercontent.com/assets/11497453/11029924/5f2abba8-86db-11e5-95d7-d676a3d532a9.jpg)
![3](https://cloud.githubusercontent.com/assets/11497453/11029926/63f15f20-86db-11e5-90f3-d1f495e63a7a.jpg)

  Это одна из основных бухгалтерских форм программы. Опция масштаб должна работать корректно без оговорок.

**Comment by MIchaelShoihet** [comment]
Да сальдо на конец масштабировалось дважды... Подправил. Будет в новом exe.

**Comment by NikolayUkleyko** [comment]
Программа выдает сообщение об ошибке.
  Проверено на gedemin.exe:
Дата файла           = 18.11.2015
Версия файла         = 2.9.1.8459
![4](https://cloud.githubusercontent.com/assets/11497453/11243892/b86515dc-8e1b-11e5-8381-aa28205186ef.jpg)

**Comment by NikolayUkleyko** [comment]
Форма **Оборотная ведомость** не функционирует и в обычном режиме (без масштабирования).

**Comment by MIchaelShoihet** [comment]
Исправлено.

**Comment by gsbelarus** [comment]
Код скидывали в гит?

**Comment by MIchaelShoihet** [comment]
Да вчера именно его я скинул

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Большое спасибо !
