### ISSUE TITLE
Бухгалтерия. Форма 'Главная книга'. Масштабирование сумм оборотов в корреспонденциях по счетам

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3677]
**_Исследователь > Бухгалтерия > Главная книга**_.

  При выборе в параметре Масштаб значений 1 000 или 1 000 000 суммы оборотов **в корреспонденциях по счетам** соответственно не пересчитываются. При этом сальдо на начало и конец периода по дебету и по кредиту, а также общие обороты по дебете и по кредиту пересчитываются корректно.
  Пожалуйста, исправьте.

**Comment by NikolayUkleyko** [comment]
По данной теме доработок не обнаружено.

**Comment by iamchrisep** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@iamchrisep , спасибо !
:trophy:
