### ISSUE TITLE
Нельзя сохранить типовой документ - конвертация

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3681]
Что-то стряслось, что сохранение изменений (да и без внесения изменений) в типовых документах невозможно из-за окна со следующим сообщением:
![1](https://cloud.githubusercontent.com/assets/11497453/11245325/3e955e08-8e23-11e5-8c2b-0a2e36cde711.png)

  Проверено на gedemin.exe:
Дата файла = 18.11.2015
Версия файла = 2.9.1.8459

  Пожалуйста, изложите порядок действий в связи с инновациями в области типовых документов.
  Спасибо !

**Comment by alexandra-gsoftware** [comment]
Кстати, создать новый типовой документ можно. Но поменять потом нельзя.

**Comment by NikolayUkleyko** [comment]
**Beta** версия, как минимум подразумевает новый не корректно работающий функционал и при это корректно работающий существующий функционал. В данном случае все очевидно.

**Comment by gsbelarus** [comment]
На днях будет сообщение по этому поводу и подробная инструкция что делать.

**Comment by NikolayUkleyko** [comment]
Почему-то нельзя выполнить однократно команду **gedemin.exe / cdo** на одном компьютере для разных баз данных.

**Comment by gsbelarus** [comment]
В смысле нельзя? Что пишет?

**Comment by NikolayUkleyko** [comment]
Для первой базы данных конвертация типовых документов осуществляется успешно (в таблицу GD_DOCUMENTTYPE_OPTION добавлены записи), а для последующих баз данных по типовым документам ничего не меняется (в таблицу GD_DOCUMENTTYPE_OPTION не были добавлены записи). При успешной и провальной попытке сообщений нет вовсе.

**Comment by gsbelarus** [comment]
что значит последующих? надо каждый раз гедымин перезапускать для конвертации.

**Comment by NikolayUkleyko** [comment]
Отбой !
  Пока, работает корректно.
  Дальше будет видно.
