### ISSUE TITLE
Синхронизация ПИ: грид

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3682]
А можно сделать, чтоб сохранялись настройки грида в форме синхронизации ПИ?
Очень нужно:)

**Comment by NikolayUkleyko** [comment]
Я за.

**Comment by alexandra-gsoftware** [comment]
работает, спасибо!

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо !
