### ISSUE TITLE
Склад. В карточке ТМЦ баланс по документу инвентаризации

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3683]
Пожалуйста, подскажите, почему в стандартной карточке ТМЦ баланс ТМЦ по документам инвентаризации отображается только как **приход** без отображения **расхода** на одно тоже количество ? Хотя, в карточке ТМЦ по холдингу баланс ТМЦ отображается и как **приход**, и, как **расход** на одно и тоже количество ? Ведь в настройках типового документа на закладках **_Приход**_, **_Расход**_ указано одно и тоже.
  На практике при работе с материальным складом, торговлей удобнее использовать стандартную карточку ТМЦ.

**Comment by NikolayUkleyko** [comment]
**_Карточка по ТМЦ**_:
![1](https://cloud.githubusercontent.com/assets/11497453/11338975/2adf2e1e-9208-11e5-9212-d9aef46bcb59.png)

  **_Карточка по холдингу**_:
![2](https://cloud.githubusercontent.com/assets/11497453/11338995/45ae4cfc-9208-11e5-8748-05593320085a.png)

  Суть в том, что по документу **09. Переоценка товаров** одновременно отражается и приход и расход на одно и то же количество на одном и том же подразделении. То есть баланс = 0. **_Карточка по ТМЦ**_ и **_Карточка по холдингу**_ отличаются. Учет в базе данных ведется строго по одной организации без филиалов, холдингов и прочей структуры.
  Пожалуйста, объсните.
  При необходимости, устраните проблему.

**Comment by MIchaelShoihet** [comment]
Все очень просто. Первая карточка строится по товару в разрезе признаков существующей карточки документа из которого она строится (или в разрезе признаков карточки которые указаны в настройке остатков, если строится оттуда), и если в признаке есть цена, то в документе переоценка она изменилась и соответственно товар со старой ценой закончился. Вторая карточка строится без привязки к признакам, а только по товару и для нее конечно переоценка является внутренним документом. Так что обе карточки работают абсолютно правильно.

**Comment by MIchaelShoihet** [comment]
Плюс еще первая карточка строится в привязке к конкретному подразделению, а вторая в целом по предприятию или если есть холдинг, то в целом по холдингу (только если ее строить из холдинга).

**Comment by NikolayUkleyko** [comment]
Напрашивается вопрос, а зачем в программе существует 2-е карточки ТМЦ ? Была б одна карточка по холдингу и не было б вопросов. Все это вводит пользователей в заблуждение.

**Comment by MIchaelShoihet** [comment]
Смотреть карточку по холдингу очень часто не удобно, удобней смотреть то что происходило именно с данным товаром в разрезе его значимых признаков. Лично я в основном пользуюсь этой карточкой. И кстати она была изначально, вторая карточка появилась именно для холдинга. А пользователям просто надо объяснять что происходит если кого-то это путает.
