### ISSUE TITLE
В форме документов не с первого раза открываются 'Свойства'. Прочие ошибки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3685]
В форме **пользовательских документов** не с первого раза открываются **Свойства**. Например, для просмотра и копирования данных.
  Такая проблема выявлена давно.
  Пожалуйста, устраните недоработку.

**Comment by NikolayUkleyko** [comment]
Аналогично и для **складских документов**.

**Comment by NikolayUkleyko** [comment]
Давно замечено, что по складским документам, созданным на основе шаблонов **Обычный складской документ, Инвентаризационный документ, Документ трансформации ТМЦ** меню отличное от всех других складских документов, созданных на основе шаблона **Документ и с изменением свойств ТМЦ**:
![1](https://cloud.githubusercontent.com/assets/11497453/11467468/54f35256-9759-11e5-8fdc-8efadbcf12fa.png)
![2](https://cloud.githubusercontent.com/assets/11497453/11467471/581535da-9759-11e5-826a-b71a5e070e2f.png)
1. В начале списка меню должна быть указано не **Доступ**, **Свойства**. Это описка, так как это все команда **Свойства**. Это вводит в заблуждение.
2. Напротив команды **Сохранить** укажите соответствующее сочетание клавиш **Ctrl+S**.
   
   Пожалуйста, устраните недоработки.

**Comment by NikolayUkleyko** [comment]
Исправьте эти небольшие недоработки.

**Comment by NikolayUkleyko** [comment]
Баг с открытием свойств документа не с первого раза устранили. Устраните остальные недоработки согласно вышеприведенной информации.

**Comment by zholnerovich** [comment]
Раньше меню имело другой вид как на первом скрине. В таком виде оно и сохранилось в перекрытых настройках формы.

**Comment by MIchaelShoihet** [comment]
Все правильно.  В exe это уже не исправишь. Меню с такими названиями сохранилась в хранилище. Это надо менять в ПИ.

**Comment by NikolayUkleyko** [comment]
Необходимо довести до конца рассматриваемый вопрос.

**Comment by zholnerovich** [comment]
"Баг с открытием свойств документа не с первого раза устранили"

Остальное к exe не относится. Костыль никто делать не будет. Здесь надо закрывать. А если вопрос критичный (сомневаюсь) то переносить его в ПИ.

**Comment by NikolayUkleyko** [comment]
Хорошо. Переговорим с Александрой.
  Большое спасибо !
