### ISSUE TITLE
Бухгалтерия. План счетов. При добавлении субсчета нельзя выбрать родительский счет

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3688]
**_Исследователь > Бухгалтерия > План счетов**_.

  При добавлении субсчета нельзя выбрать родительский счет. В результате нельзя добавить субсчет.
  Работало-работало и сломалось.

[Гедымин]
Имя файла            = gedemin.exe
Дата файла           = 25.11.2015
Версия файла         = 2.9.1.8463

**Comment by NikolayUkleyko** [comment]
Неужели это так фиолетово ?

**Comment by MIchaelShoihet** [comment]
Исправлено.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Большое спасибо !
