### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Предусмотреть параметр для скрытия повторяющихся значений аналитики

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3689]
**_Исследователь > Бухгалтерия > Журнал-ордер**_.

  Пожалуйста, предусмотрите параметр для скрытия повторяющихся значений аналитики.
  Например, при формировании Журнала-ордера по счетам 60, 62 не надо отображать на каждой строке одно и тоже значение аналитики (счет, наименование счета). **Если, значения аналитики повторяются одно за одним, тогда необходимо отображать только первое значение**. По возможности отобразить это значение сверху или по центру.

![1](https://cloud.githubusercontent.com/assets/11497453/11585825/c703def0-9a7f-11e5-9f5b-0dd5a71a55e4.png)

**Comment by MIchaelShoihet** [comment]
Я понимаю что есть некоторое неудобство, но затраты на реализацию превзойдут полученную пользу. Я не думаю, что этим надо заниматься. Если только в печатной форме.

**Comment by NikolayUkleyko** [comment]
Я, так и предполагал, что доделать форму это не просто. Хотя бы реализуйте это в отчетах.

**Comment by NikolayUkleyko** [comment]
А вообще, жаль, что так получается.
