### ISSUE TITLE
Бухгалтерия. Оборотная ведомость. Предусмотреть параметр 'Отобразить только главные счета'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3691]
**_Исследователь / Бухгалтерия / Оборотная ведомость_**.

Пожалуйста, предусмотрите параметр **Отобразить только главные счета**. При выборе данного параметра будут отображены только главные счета без отображения входящих в них субсчетов.
![1](https://cloud.githubusercontent.com/assets/11497453/11627051/ccae8b0e-9cf8-11e5-8ea8-7dd4b16ea4dd.png)

Таким образом, будет проще и нагляднее анализировать оборотную ведомость, искать расхождения в данных. Плюс, для печати такой режим формирования данных будет не лишним.

**Comment by gsbelarus** [comment]
```

procedure Tgdv_frmAcctCirculationList.DoSaveConfig(Config: TBaseAcctConfig);
var
  C: TAccCirculationListConfig;
begin
  inherited;
  if Config is TAccCirculationListConfig then
  begin
    C := Config as TAccCirculationListConfig;
    C.ShowDebit := False;
    C.ShowCredit := False;
    C.ShowCorrSubAccounts := False;
    C.SubAccountsInMain:= cbSubAccount.Checked;
    C.SubAccountsInMain:= False;
    C.DisplaceSaldo:= cbDisplaceSaldo.Checked;
    C.OnlyAccounts := cbOnlyAccounts.Checked;
  end;
end;
```

сначала одно присваивается. затем сразу же False.

и уже есть же чекбокс включать субсчета. в чем смысл еще одного?

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Большое спасибо !
:trophy:

**Comment by NikolayUkleyko** [comment]
Продолжение данной темы в теме
https://github.com/GoldenSoftwareLtd/gedemin/issues/3992
