### ISSUE TITLE
Бухгалтерия. Форма 'Результат расчета автоматической операции'. Добавить отображение количественных показателей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3692]
**_Исследователь > Бухгалтерия > Автоматические хоз. операции.**_

  Пожалуйста, в форму **Результат расчета автоматической операции** добавьте отображение количественных показателей. Так, как в форме абсолютно не виден результат по количественным показателям. Отображение количественных показателей реализовано в **Журнале хоз. операций**.

![1](https://cloud.githubusercontent.com/assets/11497453/11837291/00556438-a3f1-11e5-8731-5e33693b6fcd.png)
![2](https://cloud.githubusercontent.com/assets/11497453/11837324/2e7f1eda-a3f1-11e5-80d8-d4cf76a6ec8e.png)

**Comment by zholnerovich** [comment]
название формы на первом скрине usrf_acc_viewdelayedentry. это вопрос не к exe. Надо переносить в ПИ.

**Comment by NikolayUkleyko** [comment]
Перенесено в https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/81

**Comment by alexandra-gsoftware** [comment]
Эта технология особенная. Форма юзерская, но вызывается в автоматически сгенерированных ф-ях. И во всех этих ф-ях идет вот такой код:
  set usrg_gdcAcctEntryRegister1 = ViewEntryForm.FindComponent("usrg_gdcAcctViewEntryRegister1")
  usrg_gdcAcctEntryRegister1.Transaction = Transaction
  usrg_gdcAcctEntryRegister1.ReadTransaction = Transaction

Не логичнее было бы сначала закрывать usrg_gdcAcctEntryRegister1, а уже потом менять ему транзакцию? Может добавить это в генерацию кода?
