### ISSUE TITLE
ПИ на базе помечены знаком >>, хотя сравнение с файлом показывает, что разницы нет

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3693]
Дата, версия, мд5, текст - все совпадает...
сейчас можно посмотреть на эталоне на примере мат.склад - метаданные

**Comment by gsbelarus** [comment]
Взять новейший экзешник. Те ПИ, которые уже получили такой статус надо или сохранить (можно без инкремента номера версии) или вручную, SQL запросом, снять у них флаг CHANGED. В будущем такого уже не должно быть, но на всякий случай стоит проверить.

Пока закрываю.

**Comment by alexandra-gsoftware** [comment]
хммм. На той же базе Учет в автопарке - хранилище. CHANGED = 0, сравнение не показывает разницу, статус = "?".

**Comment by alexandra-gsoftware** [comment]
Там, где статус был ">>", снятие флажка CHANGED помогло, статус теперь правильный.

**Comment by alexandra-gsoftware** [comment]
Опять не работает. Сохранила 4 ПИ. Два из них после этого продолжают иметь статус ">>" ((

**Comment by gsbelarus** [comment]
Не могу повторить. Как будет свежий пример -- сразу зовите. На дату файла не смотрите. она не используется при сравнении, т.к. git внутри своей базы не хранит даты файлов. При чекауте у файла будет дата чекаута. Т.е на каждом компьютере у каждого файла будет своя дата.

**Comment by alexandra-gsoftware** [comment]
И снова ситуация. Сохраняю два ПИ. У одного остается флажок CHANGED(
У другого все в порядке
