### ISSUE TITLE
Долго открывается конструктор функции для ТХО

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3694]
Проблема возникающая систематически  при открытии ТО через конструктор .

![image](https://cloud.githubusercontent.com/assets/11496938/11950819/a72a9894-a894-11e5-9335-57dae1ec99eb.png)
Влияющая на работоспособность всего сервера . Допустим есть отчет "Х" который формируется меньше 1 минуты , то при открытии Администратором ТО на редактирование , этот же отчет "Х" может грузиться до 5 минут .  
- Время открытия типовой операции ориентировочно от  15 до 20 минут . 
- Кол-во типовых операции на которых вылазит "seScript"  увеличилось 

Как можно от этого избавиться или хотя бы уменьшить время загрузки ТО ?

**Comment by NikolayUkleyko** [comment]
Все это имеет место любом на gedemin.exe: новом, новейшем и любом старом.
