### ISSUE TITLE
Странное поведение формы остатков

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3695]
Если в SelectClause остатков есть ошибка, то при открытии формы вываливается аксес виолейшн, который нельзя закрыть (тут же вылазит новый), и приходится перегружать гедымин. По идее, он должен один раз внятно ругнуться и предложить не сохранять настройки формы, и всё.

**Comment by NikolayUkleyko** [comment]
Я с таким сталкивался.
  При этом, при принудительном закрытии программы выполненные настройки будут потеряны, что не есть хорошо.

**Comment by gsbelarus** [comment]
TgdcInvRemains -- перекрыл GetSelectClause. Возвращаю неверный запрос. При открытии формы остатков никаких AV.

**Comment by NikolayUkleyko** [comment]
На Береза МКК такая ошибка была.

**Comment by alexandra-gsoftware** [comment]
TgdcInvRemains -- перекрыла GetSelectClause. Возвращаю неверный запрос - добавляю туда ", www". При открытии формы остатков зацикленный AV, как и раньше
