### ISSUE TITLE
поле не попадает в SelectSQL бизнес-объекта. Почему?!

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3696]
Таблица на эталоне USR$ETTN_GOODS.
В ней есть поле-ссылка USR$GOODGROUPKEY. Почему-то оно не попадает в запрос БО для USR$ETTN_GOODS. Два других поля-ссылки нормально себя ведут.
Почему так??

**Comment by zholnerovich** [comment]
Нужна база, чтобы посмотреть в чем дело.

**Comment by alexandra-gsoftware** [comment]
я сегодня еще сама посмотрю, если не выйдет, то пришлю на почту бэкап.

**Comment by gsbelarus** [comment]
IgnoreAliases или как там их?

**Comment by alexandra-gsoftware** [comment]
нет. Игнорсы игнорят таблицу, которая приджойнилась во фром клаузе по алиасу. Они не могут пробросить главную таблицу, тем более, ее конкретное поле. Можете заглянуть на эталон...

**Comment by alexandra-gsoftware** [comment]
Нашла. Поле не добавляется в SelectSQL, если неудачно записалось блоб-значение для него в AT_RELATION_FIELDS.OBJECTS.
Закрываем.

**Comment by gsbelarus** [comment]
Пока не закрываем. Надо найти как туда попало это левое значение.

**Comment by alexandra-gsoftware** [comment]
это в скрипте был косяк, я уже исправила
