### ISSUE TITLE
Отчеты. Доработать окно шаблонов параметров (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3697]
1. При открытии окна шаблонов параметров и выборе одного из параметров необходимо предусмотреть сообщение о том, что был выполнен выбор и окно шаблонов параметров должно автоматически закрыться.
Сейчас при выборе параметров программа "молчит" и окно шаблонов параметров "висит".

2. Необходимо добавить поиск по списку шаблонов.

3. Добавить кнопки **Свернуть**, **Развернуть**.
Сейчас размер окна можно менять только растягиваем правого нижнего угла, что не очень удобно.

![1](https://cloud.githubusercontent.com/assets/11497453/12356058/98b44fbe-bbb1-11e5-814f-7cd8b61f3e4d.png)

**Comment by NikolayUkleyko** [comment]
Очередной раз столкнулся с данным функционалом.

**Comment by Polfath** [comment]
Сейчас посмотрю

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
