### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Некорректное растягивание колонок. Смещение итоговой строки (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3699]
**_Исследователь > Бухгалтерия > Журнал-ордер**_.

  Сформируйте форму со следующими параметрами:
- Счета - 60, 62, 76;
- Включая субсчета;
- Аналитика - Счета и субсчета, Клиент;
- Уровни аналитик - Клиент = 1.
  
  Недоработки:
1. После одного нажатия на кнопку F5 **первая** колонка **Клиент** будет слишком растянута. При повторном нажатии на кнопку F5 **первая** колонка **Клиент** примет верную ширину. Не должно быть повторных нажатий. Форма должна корректно формироваться при первом же ее обновлении.
2. После одного нажатия на кнопку F5 итоговая строка смещена. Такого быть не должно. При повторном нажатии на кнопку F5 итоговая строка примет корректное расположение.
   
   Такое я наблюдая давно. С разными параметрами формирования формы. Не обязательно использовать реквизит **Уровни аналитики**.

![1](https://cloud.githubusercontent.com/assets/11497453/12385067/7912c306-bdc9-11e5-8a8d-55cfd1451512.png)
![2](https://cloud.githubusercontent.com/assets/11497453/12385068/79e3e4cc-bdc9-11e5-922c-7c6ca4081692.png)

**Comment by zholnerovich** [comment]
Проблема есть, но воспроизвести ее получилось только один раз.

**Comment by NikolayUkleyko** [comment]
Маловероятно, что гриды будут дорабатываться.
