### ISSUE TITLE
Бухгалтерия. Справочник показателей. Добавить перенос типов аналитик

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3702]
**_Исследователь > Бухгалтерия > Отчеты бухгалтерии > Справочник показателей**_.

  Пожалуйста, предусмотрите в диалоговом окне **Составляющая показателя** перенос аналитик. То есть, разные типы аналитик со своими значениями должны начинаться с новой строки. А перечень значений аналитики выводится через запятую. Так, будет гораздо нагляднее.

![1](https://cloud.githubusercontent.com/assets/11497453/12507120/af06fe12-c104-11e5-981d-c33f5905fce8.png)

**Comment by zholnerovich** [comment]
Компоненты на этой форме пользовательские и заполнятся через скрипты. Поэтому это в ПИ.

**Comment by NikolayUkleyko** [comment]
Перенесено в https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/85
