### ISSUE TITLE
Материальный склад. Полная карточка ТМЦ. Ошибка при прокрутке

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3703]
При формировании полной карточки ТМЦ с включенным режимом **Редактирование в таблице** и прокрутив вниз мышку или курсор с нижней позиции программа отображает окно с сообщением:

![1](https://cloud.githubusercontent.com/assets/11497453/12510925/8ff3f57e-c11e-11e5-8d15-4b276195f323.png)

**Comment by MIchaelShoihet** [comment]
В ближайшем exe будет исправлено.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо !
