### ISSUE TITLE
Торговля. Запись удалена, но видна в гриде. Редактирование записи. F5

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3704]
**_Исследователь > Торговля**_.

  При работе с документами подсистемы пользователь добавляет запись по документу и ее не сохраняет. В результате эта запись видна в гриде. При нажатии на F5 такая запись пропадает. Вся проблема в том, что пользователь редактирует такую запись, продолжая вводить данные (выбор из остатков) и при этом программа отображает окна с сообщениями об ошибках.
  Замечено не первый раз.
  У кого какие предложения ?

**Comment by alexandra-gsoftware** [comment]
бывает, но не всегда. Непонятно почему ((

**Comment by gsbelarus** [comment]
F... Outlet\base.fdb Внут.перем. Добавить, Выбрать остатки, потом отмена. Потом в гриде сорт по дате.

**Comment by NikolayUkleyko** [comment]
На любой базе это есть. Возможно ли это учесть в gedemin.exe ? Как вариант использовать сортировку при помощи преодпределенных фильтров, или при помощи GetOrderClause.
