### ISSUE TITLE
Основные средства. Грид позиции. Слетает форматирование чисел

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3706]
**_Исследователь / Основные средства_.**

По документам **ОС. Допоступление/Списание затрат** и **ОС. Переоценка** выявлено следюущее. При открытии формы остатков ТМЦ и нажатии кнопки ОК в гриде числа отображаются без форматирования.
Стоит только нажать F5 и числа примут корректное форматирование.
Хотя, формат чисел был задан заранее и работал корректно - #,##0.##
Такое наблюдается не только по документам учета основных средств.
Пожалуйста, устраните данную недоработку.

**Comment by zholnerovich** [comment]
Да есть такое. Форматирование слетает в момент открытия формы остатков.

**Comment by zholnerovich** [comment]
Поправил, но возможно не тем способом что надо

**Comment by NikolayUkleyko** [comment]
Паша, наскоком не надо - уточни и сделай корректно.

**Comment by NikolayUkleyko** [comment]
Пока по-старому.
Вышеприведенное выявлено и в документах **_Исследователь / Материальный склад / Доработка сторонними организациями / 10. Отпуск  на доработку (переработку), 11. Возврат с доработки (переработки), 12. Возврат сырья от переработчика_**.
Это напрягает.
Пожалуйста, исправьте.

**Comment by alexandra-gsoftware** [comment]
а это именно только с форматированием проблема?

**Comment by NikolayUkleyko** [comment]
Александра, скажи, пожалуйста, что имеешь в виду ?

**Comment by alexandra-gsoftware** [comment]
в смысле, не слетает ли там ширина колонок, название, шрифт, цвет?

**Comment by NikolayUkleyko** [comment]
Нет-нет.
Слетает только форматирование числовых значений.
Стоит только нажать клавишу **F5** и все становится на место.
Могу показать.
:bicyclist:

**Comment by alexandra-gsoftware** [comment]
загадочная загадка.

**Comment by NikolayUkleyko** [comment]
Вопрос не решен.
Например, **на любой БД** в **_Исследователь / Материальный склад / 07. Списание материалов_** нажмите на кнопку **Остатки ТМЦ** и **ОК**.
В позиции суммы будут отображены без применения настроек форматирования, то есть слитно. Потом, клавиша **F5** и грид отображается корректно.
Аналогичное в **_Исследователь / Основные средства / ОС. Допоступление/Списание затрат_**.
Все это относится к стандартным документам **Комплексной автоматизации**.
На одних документах есть, на других нет.

**Comment by AliakseiDanilchyk** [comment]
Я сталкивался с ситуацией, когда форматирование вывода числового поля в гриде не сохранялось при настройке через мастер установок. Происходило это из-за настройки формата вывода для поля таблицы.
То есть в таблице было поле с типом DCURRENCY. Для этого поля на вкладке "Визуальные" был указан формат вывода #,##0.##
При этом в гриде это поле отображалось без форматирования. При настройке форматирования через мастер установок форматирование сбрасывалось после переоткрытия формы.

**Comment by NikolayUkleyko** [comment]
Попробуйте документ **_Исследователь / Материальный склад / 02. Внутренние перемещения материалов, МБП_**.
Домен и формат аналогичные.
Проблем не наблюдается.

**Comment by NikolayUkleyko** [comment]
Проблема наблюдается не просто при переоткрытии формы, а при открытии **формы выбора остатков** и нажатии на кнопку **ОК**.

**Comment by gsbelarus** [comment]
Сейчас вообще поменяем систему визуальных настроек и такие проблемы решатся.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
Вопрос решен.
Смотрите здесь https://github.com/GoldenSoftwareLtd/gedemin/issues/3706
