### ISSUE TITLE
Имена новых методов теперь генерируются капслоком. Зачем?? 

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3707]
Это же нечитабельно.

**Comment by gsbelarus** [comment]
Не надо тут ничего делать. В БД хранится в верхнем регистре для быстрого поиска по индексу. Когда все остальное исправим можно тут будет посмотреть.

**Comment by alexandra-gsoftware** [comment]
все ок. там проблема только с одной формой. наверно, она просто неудачная.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
