### ISSUE TITLE
Ошибка при попытке смены ПИ для объекта

### ISSUE THREAD

**Issue by PiuPauTralala** [GoldenSoftwareLtd/gedemin#3708]
При попытке сменить ПИ для методов формы gdc_frmInvDocument147080092_570734625OnLoadSettingsAfterCreate вываливается окно с ошибкой.
![untitled](https://cloud.githubusercontent.com/assets/11497771/12583219/adfc604c-c452-11e5-8486-7fa4b687e22c.jpg)

**Comment by PiuPauTralala** [comment]
Ошибка возникает при смене ПИ для второго и последующих методов. Для первого все срабатывает.

**Comment by alexandra-gsoftware** [comment]
это похоже связано с рекурсией в ПИ.
В том случае, когда перемещение срабатывает, в ПИ тихо добавляется рекурсивная зависимость.

Сейчас проблема такая. Объект А добавляем в ПИ-А. Объект А зависит от объекта Б. Объект Б входит в ПИ-Б, которое зависит от ПИ-А. Гедымин тихо добавляет в ПИ-А зависимость от ПИ-Б. Получаем рекурсию. Добавьте проверку на рекурсию в этот момент.
