### ISSUE TITLE
В базе etalon.fdb в исследователе присутствует пункт "Материальный склад"

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#3709]
Наверное, он там не нужен.

**Comment by NikolayUkleyko** [comment]
Я думаю, что не нужен.

**Comment by gsbelarus** [comment]
Я сам добавлял в скрипты. Уже не помню зачем. Но, помню, что какая-то такая ситуация была, что он нужен.

**Comment by alexandra-gsoftware** [comment]
так она останется?
