### ISSUE TITLE
Новое окно ПИ - невозможно посмотреть, куда входит объект

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3711]
Раньше из окна добавления объекта в ПИ можно было удалить объект из ПИ либо переместить его в другое ПИ (если нет главного объекта). А сейчас даже нельзя увидеть, в какое ПИ объект входит

![ns2](https://cloud.githubusercontent.com/assets/11487200/12622894/a86a5e5e-c538-11e5-8c34-349adf68f0a6.JPG)
![ns](https://cloud.githubusercontent.com/assets/11487200/12622895/a87313d2-c538-11e5-84e1-6bc5b9651394.JPG)

**Comment by alexandra-gsoftware** [comment]
UPD: в некоторых случаях все ок, в других - нет.

**Comment by YRozmysl** [comment]
Да, согласен. Раньше можно было сразу увидеть, куда входит  объект, что было удобно
