### ISSUE TITLE
Складской учет. Полная карточка ТМЦ. Ограничение на отображение подразделений

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3713]
Пожалуйста, предусмотрите в **Полной карточке ТМЦ** в выпадающем списке поля **Подразделение** отображение только тех подразделений / сотрудников, которые отобраны в гриде. Так будет гораздо удобнее работать с данной формой.
  Предусмотрите в выпадающем списке поля **Подразделение** отображение подразделений / сотрудников по возрастанию.

**Comment by MIchaelShoihet** [comment]
По возрастанию сделаю, а только тех - это проблематично, потому что карточка может быть очень большой и время затраченное на получение всех подразделений, может быть достаточно большим.

**Comment by NikolayUkleyko** [comment]
Жаль...
  Было бы вообще прекрасно. Например, работаю с 5-ю подразделениями приходится вручную вводить искомое наименование. А так бы выбрал - и все.
  Нет, так нет.

**Comment by MIchaelShoihet** [comment]
Для облегчения добавил кнопку, которая подставляет подразделение из текущей строчки.

**Comment by NikolayUkleyko** [comment]
Как вариант.
  Хорошо.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Большое спасибо !
