### ISSUE TITLE
Общие настройки. Настройка шрифта, цвета и прочего в гридах

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3714]
Возможно ли предусмотреть в общих настройках платформы параметр для указания настроек шрифта, цвета и прочего в гридах ?
  Предполагается окно параметров, где помимо основных настроек будет предусмотрено обновить настройки грида везде или не обновлять вовсе ? При первичной настроке программы удобно. А потом, по ходу работы каждый пользователь под себя настроит грид.
  Это не моя прихоть, а реальная потребность. МХП просили Евгения.

**Comment by alexandra-gsoftware** [comment]
так да... а потом кто-то будет плакать, что бесценный документик, который он три дня настраивал, поломался

**Comment by NikolayUkleyko** [comment]
Предусмотреть, что если, грид менялся под пользователем, тогда ничего не менять. Или параметр и сообщение о **Принудительном применении настроек грида**.
  Это одно.
  Второе. У нас в **Комплексной автоматизации** полным полно документов и справочников, у которых в гридах разные шрифта, цвета и прочее. Числовые поля отображаются без форматирования. Неоднократно просили Юрий по ЗП и ОК.

**Comment by alexandra-gsoftware** [comment]
ну, если уж делать, то по списку выбранных док-тов и гридов к ним. У меня, например, многое настроено через цвет/шрифт, я не хочу, чтобы это поломалось.

**Comment by NikolayUkleyko** [comment]
Гибкая настройка по каждому документу, справочнику будет очень кстати.

**Comment by gsbelarus** [comment]
Сейчас вообще переделываем эту систему.

**Comment by NikolayUkleyko** [comment]
И будет "сказка" :green_book:.
