### ISSUE TITLE
Обновление базы

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3716]
При обновлении клиентской базы новым ехе возникает вот такое сообщение. Это нормальная ситуация, или нет?
![default](https://cloud.githubusercontent.com/assets/11507129/12745736/f15e02e2-c9ab-11e5-8737-1c3c11ad050c.jpg)

**Comment by gsbelarus** [comment]
Покажешь эту базу.

**Comment by alexandra-gsoftware** [comment]
а склад там на днях не обновлялся?

**Comment by YRozmysl** [comment]
Не думаю - это база КИС

**Comment by NikolayUkleyko** [comment]
Что в итоге ?

**Comment by gsbelarus** [comment]
хз. не повторяется больше.
