### ISSUE TITLE
Модифай и замена доменов.

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3719]
Замечено следующее, что после модифая поменялись тип домена в некоторых полях. Так, например, всегда поле USR$AGELIMIT в таблице USR$WG_CHILDCAT  имело домен USR$WG_D_CHILDCAT,  после модифая стало DCURRENCY

**Comment by gsbelarus** [comment]
1. Одно это поле или есть еще поля?
2. точно поменялось? Найти старую БД, к которой не прикасались новым экзешником, подключиться IBExpert и посмотреть тип. Старая БД -- это такая к которой не прикасались актуальным экзешником за последние 12 месяцев.
3. Посмотреть другие БД, которые смодифаены новейшим экзешником. Тот же эталон.

**Comment by gsbelarus** [comment]
Это кто-то из разработчиков поменял на домен dcurrency так как появились дробные коэффициенты. Спрашивается: какого лешего? **dcurrency** -- это домен для ДЕНЕГ. Как теперь мы будем проводить деноминацию?

В данной ситуации надо было изменить домен **USR$WG_D_CHILDCAT**.

На ровном месте создаем себе проблемы.

**Comment by NikolayUkleyko** [comment]
Я бы не полагался на домен **DCURRENCY** при деноминации на 100 % Так, как кроме вышеприведенной ситуации полным полно, где этот домен используется не только для денежных средств.

**Comment by gsbelarus** [comment]
Так мы и не будем полагаться. Просто зачем усложнять то, что и так сложное. Есть же домен для этой колонки с ним и надо было разбираться.

**Comment by alexandra-gsoftware** [comment]
dcurrency это numeric (15,4). Он используется для любых числовых значений, подпадающих под этот формат.
на эталоне и в пи ни с полем, ни с доменом ничего не делали. если поле поменялось через модифай, то он почему-то не затронул эталон.

и да, в фб можно поменять домен, но через пи это не переносится... а хотелось бы

**Comment by gsbelarus** [comment]
Плохо, что используется, потому что изначально:

```
INSERT INTO at_fields
  (fieldname, lname, description, reftable, reflistfield, refcondition, settable, setlistfield, setcondition,
   alignment, format, visible, colwidth, disabled, reserved)
VALUES (
  'DCURRENCY',
  'Сумма в валюте',
  'Сумма в валюте',
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  'R',
  '#,##0.##',
  1,
  10,
  0,
  NULL
);
```

**Comment by gsbelarus** [comment]
но перенеслось же...

**Comment by alexandra-gsoftware** [comment]
если бы перенеслось, то перенеслось бы на эталон, и фигурировало в пи..

**Comment by YRozmysl** [comment]
Вопрос снимается. Это поле почему-то на базе КИС еще до модифая уже было DCURRENCY, почему так, я точно не скажу.

**Comment by NikolayUkleyko** [comment]
Закрывай тему.
