### ISSUE TITLE
Бухгалтерия. Доработки для конструктора функций

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3720]
**_Исследователь > Типовые хоз. операции > Автоматические хоз. операции > Отчеты бухгалтерии > Настройка функций**_.

  Пожалуйста, для конструктора функций реализуйте следующее:
**а**. Предусмотрите прокрутку списка скроллом мышки. Так будет удобнее работать со списком.
![1](https://cloud.githubusercontent.com/assets/11497453/12841567/984e3272-cbfd-11e5-88f8-7304b66cfad2.png)

**b**. Окно выбора переменных по размерам мало. Сразу не видны полные наименования переменных. Каждый раз необходимо изменять размер окна. Крайне не удобно. Сделайте запоминание размера окна и/или просто увеличьте его.
![2](https://cloud.githubusercontent.com/assets/11497453/12841615/01adcade-cbfe-11e5-9e30-5658d7ad697d.png)

**Comment by zholnerovich** [comment]
Прокрутка диалоговое окно ЖО

**Comment by zholnerovich** [comment]
А может наследника на scrollbox создать?

**Comment by NikolayUkleyko** [comment]
Паша, я не сторонник наследников и подобного.
  Лучше уточни у знающих людей.

**Comment by zholnerovich** [comment]
Коля это не к тебе вопрос.

**Comment by gsbelarus** [comment]
А какой размер окна? Может его увеличить просто?

**Comment by zholnerovich** [comment]
увеличил с 400 до 571

**Comment by gsbelarus** [comment]
800*600 уже не поддерживается гедымином. И тем более на таком экране никто не будет бухучет настраивать. Так что смело можно ставить начальную высоту 768 - высота главн окна \* 2.

**Comment by gsbelarus** [comment]
Где то 620-640 будет

**Comment by zholnerovich** [comment]
Тут вопрос про ширину а не высоту, ширины не хватает

**Comment by gsbelarus** [comment]
1024 не хватает?

**Comment by zholnerovich** [comment]
Вполне хватит, даже много, будет пусто смотреться

**Comment by NikolayUkleyko** [comment]
**c**. Окно выбора функций по размерам мало.
![3](https://cloud.githubusercontent.com/assets/11497453/13136001/b8005266-d626-11e5-8c2e-98cb84503f16.png)

  Пожалуйста, увеличьте его так, как и увеличили окно выбора переменных.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Большое спасибо !
:trophy:
