### ISSUE TITLE
Бухгалтерия. Процедура. Свойства параметров. Искажение формы

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3722]
**_Исследователь > Бухгалтерия > Автоматические хоз. операции**_.

  Искажается форма в процедуре > свойства блока.
  Пожалуйста, исправьте.
  **_Искажено:**_
![1](https://cloud.githubusercontent.com/assets/11497453/12848700/82c6843e-cc2c-11e5-8287-57c3d54a5718.png)

  **_Не искажено**_:
![2](https://cloud.githubusercontent.com/assets/11497453/12848705/86de2176-cc2c-11e5-836b-eec5c5247684.png)

**Comment by alexandra-gsoftware** [comment]
мне кажется, обе картинки одинаковые. В чем разница?

**Comment by NikolayUkleyko** [comment]
Паша знает о чем речь.
:smile:

**Comment by zholnerovich** [comment]
на вин 10 не обнаружено
