### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Ограничение на ввод значений после запятой

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3723]
**Исследователь / Бухгалтерия / Журнал хоз. операций**.

В Журнале хоз. операций для числовых полей **сумма, рубли; сумма, эквивалент; сумма, валюта** предусмотрен домен DCURRENCY (формат 15, 4). На практике введя 4-е цифры до запятой, то после запятой можно ввести только 3-и цифры. Чем больше ввести цифр до запятой, тем меньше можно ввести цифр после запятой. Введя 10 цифр, после запятой уже ничего не введешь.

Так задумано ?

**Comment by zholnerovich** [comment]
Есть еще такая вещь как выход за диапазон. Что с этим делать?

**Comment by gsbelarus** [comment]
Для чего надо вводить руками ДЕСЯТЬ цифр после запятой??

**Comment by gsbelarus** [comment]
Еще актуален этот вопрос?

**Comment by NikolayUkleyko** [comment]
Данный вопрос актуален.

Проверено.
Работает корректно.
@gsbelarus , спасибо !
