### ISSUE TITLE
Бухгалтерия. Суммы в эквиваленте

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3724]
**_Исследователь > Бухгалтерия > Автоматические хоз. операции, Типовые хоз. операции, Отчеты бухгалтерии > Настройка функций**_.

  Я проверил, программа допускает в конструкторе функций ввод по дебетовой и кредитовой частям **разных** значений в поле **Сумма в эквиваленте**.
  Так задумано или нет ?
  Если нет, тогда имеет смысл в типовых хоз. операциях предусмотреть проверку на заполнение поля **Сумма в эквиваленте**, как по дебету так и по кредиту счета. То есть, если по одной из сторон заполнено поле **Сумма в эквиваленте**, а по другой - нет, то при формировании бухгалтерских проводок выводить сообщение: **Сумма в эквиваленте по дебету не равна сумме в эквиваленте по кредиту. Проверьте настройку типовой хоз. операции !**

**Comment by gsbelarus** [comment]
Если делать, то так же как проверяется соответствие сумм в рублях и валюте. Но, может был за этим какой-то смысл? @MIchaelShoihet

**Comment by MIchaelShoihet** [comment]
Вообще программа проверяет корректность только рублевых сумм, т.к. только для них относится правило двойной записи. Для валютных сумм это никак не относится. Эквивалент - то же является побочным продуктом и может использоваться настройщиком для его целей, поэтому на него то же ограничение не накладывается.

**Comment by NikolayUkleyko** [comment]
Я так, понимаю, что в части работы **эквивалента** конструктор функций работает корректно. Если, ни у кого нет вопросов, закрываю данную тему.
