### ISSUE TITLE
Шаблоны. Удаленное подключение. Программа закрывается при попытке обращения к папке

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3726]
Подключение к удаленное рабочему столу через RDP.
  При попытке открытия папки с шаблонами программа закрывается без предупреждений. При этом **теряются все выполненные визуальные настройки**. Предполагается, что причиной тому является запрет на доступ к выбираемой папке.
  Пожалуйста, предусмотрите, чтобы в данной ситуации программа отображала окно с сообщением:

**Политикой безопасности доступ к данной папке закрыт. Пожалуйста, попросите системного администратора сети открыть доступ к данной папке или выберите другую папку.**

  Такое выявлено не первый раз. Напрягает.

**Comment by gsbelarus** [comment]
Для начала надо выяснить что именно является причиной. Надо посмотреть журнал событий операционной системы на сервере, которому подключаемся через RDP.

Без установления причины что-то сделать невозможно.

**Comment by arthur-latunov** [comment]
Было такое при попытке сохранить скрипт-объект в файл.
Правая кнопка мыша на иконке Гедымин и Запуск от имени администратора, всё заработало.

**Comment by MIchaelShoihet** [comment]
Это скорее всего проблема не Гедемина. Потому что объект открыть файл - это стандартный Windows элемент и именно он закрывает программу

**Comment by NikolayUkleyko** [comment]
Как настроить Windows, чтобы в подобной ситуации были сообщения о предупреждении и выбор другой папки ?
