### ISSUE TITLE
Реально ли создать конструктор пересчетов по документу и конструктор отчетов ? (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3727]
Сейчас простейший расчет по позиции документа требует навыков программирования. При этом, если, алгоритм пересчета сложный, то при попытке внесения небольшой доработки, например, округления, может быть нарушена работоспособность существующего алгоритма. Так как, данный алгоритм где-то (документах, функциях, методах) еще используется.
  Напрашивается вопрос: реально ли по аналогии с конструктором бухгалтерских проводок создать конструктор пересчетов по документу ? Как по позиции, так и по шапке документа.
  Где-то были ссылки:
- http://allsoft.by/program_page.php?grp=141305
- http://allsoft.by/program_page.php?grp=142490

**Comment by MIchaelShoihet** [comment]
Об этом мы сейчас думаем. Но отдельная большая задача.

**Comment by NikolayUkleyko** [comment]
Хорошо бы еще создать и конструктор отчетов. Отчеты бухгалтерии имеют существенный недостаток в том, что в них данные статичны. Подобные конструкторы пересчетов и отчетов есть у конкурентов.
