### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Округление сумм

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3728]
**_Исследователь > Бухгалтерия > Журнал-ордер**_.

  **Минскхлебпром**.

![image](https://cloud.githubusercontent.com/assets/11497453/12944625/5c46363a-cff9-11e5-86ea-8d0d21133cb3.png)

  На предприятии бухгалтера утверждают, что в данном примере сумма должна составить

![image](https://cloud.githubusercontent.com/assets/11497453/12944842/dc69a4fe-cffa-11e5-8429-50e23de1da29.png)

  В Журнале-ордере выводится

![image](https://cloud.githubusercontent.com/assets/11497453/12944875/170147ca-cffb-11e5-9982-4b28a5d76b4c.png)

  Бухгалтера сверяют дебетовые и кредитовые обороты по счетам. В результате из-за округления вылазит не закрытое сальдо.
  Я объяснял, что это простая математика. В Excel результат, как в Гедымине.
  Бухгалтера не дают спокоя Евгению.

  Возможно ли для таких бухгалтеров предусмотреть в Журнале-ордере реквизит, который бы округлял бы суммы без знаков после запятой ?

**Comment by gsbelarus** [comment]
То есть встроить в гедымин ошибку, чтобы потом нас где нибудь на разборках сношали "смотрите какая херовая программа она даже 2+2 правильно сложить не может".

Почему бы не написать официальное письмо, приложить пример, и правила округления. И закрыть этот вопрос.

**Comment by MIchaelShoihet** [comment]
тут ничего не получится. @EugeneFedorov  надо округлять суммы по проводкам по его счетам до рублей и тогда все будет строится красиво.
