### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Добавить прокрутку скроллом диалоговой формы

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3732]
**Исследователь / Бухгалтерия / Журнал хоз. операций**.

Пожалуйста, добавьте прокрутку **скроллом** диалоговой формы. Сейчас не удобно работать с **минимизированной** формой диалога.

![1](https://cloud.githubusercontent.com/assets/11497453/13044548/ce8a080e-d3df-11e5-8986-fb4c85d7b435.png)

Прокрутка должна работать **только по выделенной части (или дебет, или кредит)**.

**Comment by NikolayUkleyko** [comment]
По данной теме доработок не обнаружил.

**Comment by iamchrisep** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Доработок не выявлено.

**Comment by NikolayUkleyko** [comment]
Выполнена доработка.

На Windows 10 работает.
На Windows 7 не работает.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
Я отправила изменения. Ждем проверки Андрея.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
