### ISSUE TITLE
ПИ. Что-то не так...

### ISSUE THREAD

**Issue by hirurg-lybitel** [GoldenSoftwareLtd/gedemin#3733]
Собрал базу.

Сразу лезу в синхронизацию ПИ и вижу такую картину:
![image](https://cloud.githubusercontent.com/assets/11502258/13056085/baeaecc8-d41b-11e5-90c8-8095d782b58b.png)

Как-то многовато хочет сохранить обратно, учитывая, что я базу только собрал и ничего не делал.  
Начинаю сравнивать ПИ в базе и на диске.

Картина везде разная: 
- то в ПИ на диске есть поля, которые так и не появились в базе
  ![image](https://cloud.githubusercontent.com/assets/11502258/13056120/10314e7a-d41c-11e5-8dad-ca886f8cc0f2.png)
- то вопросы с EDITIONDATE 
  ![image](https://cloud.githubusercontent.com/assets/11502258/13056194/80a91afc-d41c-11e5-9660-a572aaf83cfd.png)
- то  вот такие вещи
  ![image](https://cloud.githubusercontent.com/assets/11502258/13056147/3bf939aa-d41c-11e5-873b-ce04e02755cb.png)

Всё это в итоге очень усложняет сохранение больших доработок, потому что приходится вручную проверять, что куда входит, и отдельно сохранять эти ПИ.

Может я чего-то не понимаю, и это нормально. Тогда, пожалуйста, объясните.

**Comment by alexandra-gsoftware** [comment]
По ходу, это одни и те же даты, только по разному представлены. Непонятно, почему так. Может, зависит от настроек винды?

**Comment by alexandra-gsoftware** [comment]
С должностями ничего не поделаешь - это долго и нудно обсуждалось, и решили ничего не делать

**Comment by alexandra-gsoftware** [comment]
А исчезнувшие макросгруп и репортгруп - мне кажется, что-то не добавлено в пи...

**Comment by gsbelarus** [comment]
У нас в минске часовой пояс GMT +3 часа. У тебя на компьютере выбран НЕРАВИЛЬНЫЙ часовой пояс. В чем проблема? Исправь и все будет ок.

**Comment by hirurg-lybitel** [comment]
Ладно, живите пока...
