### ISSUE TITLE
Изменение прав доступа

### ISSUE THREAD

**Issue by hirurg-lybitel** [GoldenSoftwareLtd/gedemin#3735]
Торговля  - >09 Переоценка товаров -> Свойство объекта

При попытке изменить права доступа:
![image](https://cloud.githubusercontent.com/assets/11502258/13076390/f5ccc3a0-d4c2-11e5-83fb-9869fe6484f7.png)

**Comment by gsbelarus** [comment]
Подправили на уровне экзешника.
