### ISSUE TITLE
Бухгалтерия. Журнал-ордер и Карта счета. Формат отображение дат (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3739]
**_Исследователь / Бухгалтерия / Журнал-ордер, Карта счета_.**

Давайте посмотрим, как в **Журнале-ордере** в гриде выводятся даты:
![1](https://cloud.githubusercontent.com/assets/11497453/13136970/e9c1b59e-d62e-11e5-8bea-bfbfe663c443.png)

Теперь, аналогичное в **Карте счета**:
![2](https://cloud.githubusercontent.com/assets/11497453/13136985/fbbda5dc-d62e-11e5-9e2d-302bd6016929.png)

Давайте посмотрим, как в **Журнале-ордере** в гриде выводится **_список значений автофильтра_** поля дата:
![3](https://cloud.githubusercontent.com/assets/11497453/13137011/2f271aca-d62f-11e5-9b9c-3208d652aca2.png)

Теперь, аналогичное в **Карте счета**:
![4](https://cloud.githubusercontent.com/assets/11497453/13137012/345e4086-d62f-11e5-96b8-9e195b00fd42.png)

К чему все это ?
При анализе данных по датам не очень удобно воспринимать одни формат дат в **Журнале-ордере** (**2014-01-01**) и другой формат дат в **Карте счета** (**01.01.2014**).
Не удобно работать с автофильтром.
В **Карте счета** в списке значений автофильтра видим **2014.01.01**.
Все наоборот.
Зачем ?
Пожалуйста, в данных формах (предположительно везде... в документах, справочниках и т. д.) приведите отображение дат в гриде и в списке значений автофильтра к **одному формату**. Предлагаю сделать как в **Журнале-ордере**.

**Comment by gsbelarus** [comment]
Привычный формат из повседневной жизни это **дд.мм.гг**, но в журнале ордере идет группировка и сортировка записей по дате. В этом случае гораздо удобнее видеть даты как **гггг-мм-дд**.

**Comment by NikolayUkleyko** [comment]
Я согласен.
Я помню, Вас, давно просили в списке значений автофильтра сделать по-умолчанию сортировку **по убыванию**, Вы, сказали, что не стоит.
Мы согласились.
Не просим об этом.
Но, надо прийти к одному формату отображения дат при прочих равных условиях.
Возможно это или нет ?
