### ISSUE TITLE
Бухгалтерия. На gedemin.exe от 18.02.2016 г. недоступны отчеты по бухгалтерским формам

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3741]
После обновления gedemin.exe (Дата файла = 18.02.2016, Версия файла = 2.9.2.8541) стали недоступны отчеты по бухгалтерским формам. Отчеты реально существуют в редакторе скрипт-объектов.
  Пожалуйста, исправьте.

**Comment by gsbelarus** [comment]
@zholnerovich я не совсем понимаю этот код в gd_reportmenu.pas:

```
  if LocId > 0 then
 begin
    q := TIBSQL.Create(nil);
   try
     q.Transaction := gdcBaseManager.ReadTransaction;
      q.SQL.Text := 'SELECT macrosgroupkey FROM evt_object WHERE id = :id';
      q.ParamByName('id').AsInteger := LocId;
      q.ExecQuery;
      if not q.Eof then
        MGK := q.FieldByName('macrosgroupkey').AsInteger;
    finally
      q.Free;
     end;
```

Речь же идет о меню отчетов. Причем тут макросы?

Срочно надо поправить.

**Comment by alexandra-gsoftware** [comment]
из Пространства имен тоже отчеты исчезли. Щелчок по молнии перекидывает в APPLICATION. Сделайте что-нибудь!!

**Comment by alexandra-gsoftware** [comment]
воот, сейчас в форме ПИ все ок с отчетами. Спасибо.
