### ISSUE TITLE
Общие. Поиск по биноклю. Доработки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3742]
**a**.  Инструментов поиска и фильтрации в программе много.
Одним из удобных инструментов является поиск при помощи **Бинокля (Ctrl+S)**.
При первом использовании бинокля и/или для поиска требуемого поля необходимо нажать на кнопку **Все поля**.
Программа отобразит много-много полей.
Приходится при помощи ползунка прокручивать список полей.
Не совсем удобно при наличии большого перечня полей.
Можно легко проскочить искомое поле.
Потом, опять выполнять поиск сначала списка.
Пожалуйста, добавьте возможность прокрутки списка полей скроллом мышки.

**b**. Как удалить из перечня полей поля, по которым выполнялся поиск ?

**c**. Предусмотрите возможность поиска полей на панели поиска.
Например, команда в контекстном меню и/или комбинация клавиш Ctrl+F3.

**d**. При нажатии на кнопку **Все поля** отображать только поля, отображаемые в гриде.
Как вариант предусмотреть отдельную кнопку, например, **Поля из грида**.
Много ненужных полей.

**e**. Форма, состоящая из шапки и позиции.
Активируем поиск по шапке **Бинокля (Ctrl+S)** и по позиции **Бинокля (Ctrl+Alt+F)**.
При нажатии на кнопку **Enter** не работает фильтрация.
Работает только принудительное нажатие на кнопку **Найти**, расположенную в шапке (верхнем гриде).

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by MIchaelShoihet** [comment]
Давайте сильно не углубляться. Мы можем придумать очень красивую систему, но на существующих предприятиях ее будет уже проблематично внедрять. На самом деле идея простая для некоторых специализированных документов выгодней выбрать все товары с ограничением на вид этого товара, без других ограничений (в смысле использования индекса). Эта работает в тех случаях когда есть большое движение прочих товаров и относительно небольшое наших специализированных. Тут и возникают задачи: Спецодежда, ОС... Признак который мы можем задействовать должен обязательно иметь индекс, в противном случае выигрыш мы не получим. Давайте не будем усложнять. А добавим в настройку типового документа и в настройку остатков  - возможность указания признака по которому будет идти основное ограничение и на основании этого формировать запрос  с остатками.

**Comment by gsbelarus** [comment]
Это наверное в другую ветку.

**Comment by MIchaelShoihet** [comment]
Да это я перепутал.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.
Для начала, хотя бы пункт **b**.

**Comment by ShlTanya** [comment]
Сделано: а, b (удаление через контекстное меню на поле), e

**Comment by NikolayUkleyko** [comment]
Проверено.
Пункты **a, b, e** работают корректно.
Взвесил все **за** и **против** пункты **c, d** можно не делать.
@ShlTanya , спасибо ! :trophy:

----

Отличная реализация !

**Comment by NikolayUkleyko** [comment]
Есть замечание по пункту **b**.

Если, одно или несколько полей заполнены, то при удалении любого поля (заполнено или нет) очищаются данные из всех полей.
Неудобно.
Приходиться заново вводить данные.
В данном случае данные не должны удаляться.

**Comment by NikolayUkleyko** [comment]
Выявлена еще недоработка.

1. Например, выполняем поиск по 2-м полям.
2. В одно поле введем реально существующую искомую запись, а во второе - произвольный набор данных.
3. В гриде ничего не будет отображен. Верно.
3. Через контекстное меню удаляем поле, в которое была введена некорректное значение.
4. Закрываем поиск по биноклю.

**В гриде пусто.
Помогает только закрыть-открыть форму документа.**

В данном случае ключевой момент - это удаление через контекстное меню одного из полей при некорректных введенных данных.

@ShlTanya , пожалуйста, посмотри.

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
**f**. Выявлено неполное отображение наименований полей:

![1](https://cloud.githubusercontent.com/assets/11497453/26415147/275c5f0c-40ba-11e7-90fe-ed5362ad6d30.png)

@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
Думаю в данном случае надо установить "читаемое" заглавие колонки в Мастере установок (F10)

**Comment by NikolayUkleyko** [comment]
@ShlTanya , скажи, пожалуйста, можно ли предусмотреть поиск среди полей, отображаемых при поиске по **Биноклю (Ctrl+S)** ?

**Comment by ShlTanya** [comment]
Поиск по поиску?? Не уверена, что это стоит делать..

**Comment by NikolayUkleyko** [comment]
У других коллег было аналогичное предложение.
Вся проблема в том, что не хватает режима отображения только тех колонок, которые отображаются в гриде.
@ShlTanya , можно ли это предусмотреть ?

**Comment by ShlTanya** [comment]
Я посмотрю как это можно реализовать.

**Comment by NikolayUkleyko** [comment]
Так, будет очень-очень удобно.
Коллеги подтвердят.

**Comment by ShlTanya** [comment]
Добавила опцию режима поиска только по видимым полям таблицы. Режим поиска сохраняется для каждой формы.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , данная доработка commit ?

**Comment by gsbelarus** [comment]
Не надо никаких опций. Про них 99.999999999999999999% ничего не знают. Поступайте как Apple -- минимум настроек, минимум непонятного для конечного пользователя.

Я против:

```
    FSearchDetailVisibleCol := UserStorage.ReadBoolean(BuildComponentPath(chbSearchDetailVisibleCol),
      'ShowVisibleColumns', False);

```

**Comment by gsbelarus** [comment]
Если правильнее искать только по видимым -- ищите по ним.

**Comment by gsbelarus** [comment]
Не надо мусорить хранилище. В крайнем случае сделайте переключатель "только видимые". Он включен при открытии формы. Его можно переключить, но состояние его нигде не сохраняется.

**Comment by NikolayUkleyko** [comment]
>Если правильнее искать только по видимым -- ищите по ним.

Про это и шла речь.
?

**Comment by ShlTanya** [comment]
Тогда может лучше Всегда показывать видимые поля таблицы + историю поиска??

**Comment by NikolayUkleyko** [comment]
>Тогда может лучше Всегда показывать видимые поля таблицы + историю поиска??

Если, показывать всегда видимые поля, то это уже включает в себя уже выбранные поля, по которым выполнялся поиск.
?
Противоречие.

Сейчас фильтрация по Биноклю работает корректно.
Я бы вместо стандартной кнопки **_Все поля_** предусмотрел кнопку **_Видимые поля_**.
Нажав которую, отображались бы поля строго из грида формы.
Это поля, по которым в **_Мастере установок_** проставлена галка по реквизиту **Колонка отображается**.

**Comment by ShlTanya** [comment]
Поле будет отображаться 1 раз. Либо оно было уже в истории поиска, либо видимо в таблице.

**Comment by NikolayUkleyko** [comment]
>Поле будет отображаться 1 раз. Либо оно было уже в истории поиска, либо видимо в таблице.

Хорошо.
Посмотрим на практике.

**Comment by gsbelarus** [comment]
1. Сделайте две кнопки **Видимые** и **Все**.
2. Сразу панель открывается только с полями, которые ранее были задействованы в поиске.
3. Нажатие на Видимые выводит список видимых полей.
4. Нажатие на Все выводит список всех полей.

**Comment by ShlTanya** [comment]
Хорошо

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
Приятно, слышать @ShlTanya .
Татьяна, скажи, пожалуйста, данная новация commit ?

**Comment by ShlTanya** [comment]
да

**Comment by NikolayUkleyko** [comment]
Проверено.
В целом работает корректно.
Необходимо предусмотреть следующее:

1. При нажатии на кнопку **Видимые** очередность полей поиска должна соответствовать очередности полей в гриде.
Так удобнее воспринимать данные и их анализировать.

2. Если, уже была нажата кнопка **Видимые**, то делать ее неактивной для выбора.

3. В случае корректных названий колонок в гриде некоторые названия колонок на панели поиска не влазят.
Можно ли предусмотреть перенос названий колонок ?

**Comment by ShlTanya** [comment]
1. Можно сделать.
2. Нажали кнопку Видимые (по Вашему варианту кнопка скрылась ).. Изменили в гриде колонки. Что сделать пользователю чтобы отобразить заново видимые поля??
3. Надо обсуждать. Сделать то можно, но все равно д.б. ограничение.. например максимум 2 строки.

**Comment by ShlTanya** [comment]
По 3 пункту.. на поле есть хинт.. думаю его и достаточно.

**Comment by NikolayUkleyko** [comment]
По пункту № 1.
Решили, что это можно сделать.
Хорошо.

По пункту № 2.
Случай, когда пользователь меняет очередность колонок в гриде связано и с пунктом № 1.
Хорошо, @ShlTanya , можно придумать дополнительные проверки на изменения.
Не будем усложнять конструкцию.
@ShlTanya меня убедила.
Поэтому, данный пункт оставляем без изменений.

По пункту № 3.
Пожалуйста, скриншот **Исследователь / Основные средства / ОС. Остатки на дату**:

![2017-06-15_105115](https://user-images.githubusercontent.com/11497453/27171221-7ae577ac-51b9-11e7-975b-966091ab7980.png)

Почему идет речь о переносе, так как панель, на которой расположены поля поиска шире делать не будем.
Ограничение должно быть.
Какие варианты, @ShlTanya ?

**Comment by gsbelarus** [comment]
Давайте поставим здесь точку. Перенос невозможен.

**Comment by NikolayUkleyko** [comment]
>Давайте поставим здесь точку. Перенос невозможен.

Хорошо.
Только не забудьте пункт № 1.
Обновите gedemin.exe.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , привет !
Проверил на Newest gedemin.exe не выявил соответствие **очередности** колонок на панели поиска и в гриде.
@ShlTanya , скажи, пожалуйста, вносила ли, ты, правки ?
Если, да, то они commit ?

**Comment by NikolayUkleyko** [comment]
Выявлено следующее.
При поиске по биноклю по шапке и по позиции при нажатии в **шапке** кнопки **Найти** курсор в гриде шапки и в гриде позиции уходит с найденной записи вверх списка.

Добавлю к этом.
Если, в позиции дважды нажать на кнопку **Enter**.

Соответственно теряются найденные записи не только по шапке, но и по позиции.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, скажи, можно ли предусмотреть вышеприведенное ?

**Comment by NikolayUkleyko** [comment]
**Исследователь / Материальный склад / 04. Отпуск материалов покупателям.**
Такое имеет место быть по формам и гридам других документов, объектов и т.д.

1. В шапке нажать на кнопку поиска **Бинокль**. При этом ничего не прописываем для фильтрации и прочих кнопок не нажимаем.
2. Сдвигаем вверх границу между позицией и шапкой документа.
3. Кликаем по гриду и на экране программа отображает сообщение об ошибке:

![2020-10-28_184159](https://user-images.githubusercontent.com/11497453/97460612-f8aa0400-194d-11eb-9ba2-8f6988d98c95.jpg)

@ShlTanya , пожалуйста, посмотри.
