### ISSUE TITLE
Выпадающий список. Запретить прокрутку значений скроллом мышки (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3743]
Пожалуйста, в выпадающих полях запретите прокрутку значений списка скроллом мышки. Пользователь может случайно выбрать другое значение. Это может быть и в документах (в шапке документа выбор счета, клиента и т. д.), и в бухгалтерских формах (выбор конкретных значений аналитики) и т. д.
  Пожалуйста, изложите свои точки зрения на данную тему ?

**Comment by gsbelarus** [comment]
А как запретить? Это стандартное поведение Windows. Курсор установлен в поле и естественно что поле обрабатывает ввод.

Точно также ты поставь в Excel курсор на клетку и введи какую-нибудь букву. Старое значение сотрется -- новое введется. Так и тут.

**Comment by NikolayUkleyko** [comment]
Если, стандартно как в Windows, тогда не вносите правки.
  Я просто предложил.

**Comment by AliakseiDanilchyk** [comment]
Стандартное поведение - это когда прокрутка меняет значение при раскрытом списке. У нас местами значения меняются и при свернутом списке. Например, список рабочих столов на главном окне. В списке аналитик журнала-ордера прокрутка меняет значение ранее выбранной аналитики на пустое.

**Comment by gsbelarus** [comment]
Нет. проверь на любом диалоговом окне, например в Microsoft Office, список закрыт, но скролмышки будет его прокручивать.

**Comment by AliakseiDanilchyk** [comment]
На списках сделанных через TComboBox такое поведение

**Comment by NikolayUkleyko** [comment]
Так и есть.
