### ISSUE TITLE
Грид. Добавить возможность копирования сумм из итоговой строки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3744]
Пожалуйста, предусмотрите возможность копирования сумм из итоговой строки. На практике это **крайне необходимо** для анализа данных из разных форм, отчетов и т. д. (копирование в Excel и выявление расхождений). При этом копирование должно корректно работать и по составным полям.

**Comment by NikolayUkleyko** [comment]
Проверено.
При копировании итогов из форм складских остатков или из бухгалтерских форм и при последующей вставке в Excel добавляются нелокализованные наименования колонок. Однако, при работе с формами документов - переносятся локализованные наименования колонок.
@iamchrisep , пожалуйста, поправь.

**Comment by gsbelarus** [comment]
Это не так просто исправить. При сложной настройке в одной клетке может быть несколько итоговых значений и не так легко установить какое к какой колонке относится.

**Comment by gsbelarus** [comment]
Я бы не тратил пока время. Работает правильно.

**Comment by NikolayUkleyko** [comment]
> Я бы не тратил пока время. Работает правильно.

Ладно-ладно. Я просто выявил такое и спросил.

**Comment by NikolayUkleyko** [comment]
Проверено.
@iamchrisep , спасибо !
:trophy:
