### ISSUE TITLE
Бухгалтерия. Произвольное отображение ###### в итоговых строках (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3746]
**_Исследователь / Бухгалтерия / Журнал-ордер, Оборотная ведомость, Карта счета, Главная книга, Анализ счета_.**

При формировании вышеприведенных форм в итоговых строках произвольно отображаются не суммы, а **######**.
При повторном обновлении формы итоги отображаются корректно.  
Пожалуйста, устраните данную **_напрягающую_** недоработку.
Программа должна работать четко и надежно по одному клику.
Пользователям не понять бубнов с 2-я кликами и т. д.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
исправлено

**Comment by NikolayUkleyko** [comment]
Проверено на следующем gedemin.exe:
Дата файла           = 27.04.2017
Версия файла         = 2.9.3.9088

Изменений не выявлено.

**Comment by ShlTanya** [comment]
да.. там еще нет

**Comment by ShlTanya** [comment]
Проверьте

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

----

Вообще отлично сделано !

**Comment by NikolayUkleyko** [comment]
Сегодня увидел, что сформировав Журнал-ордер за год без выбора счета (то есть, по всем счетам), местами имеет место некорректное отображение значений в итоговых строках.
В Оборотной ведомости, сформированной за год также есть такое.
@ShlTanya , пожалуйста, при возможности посмотри.

**Comment by gsbelarus** [comment]
Не трогайте это! 3 часа вчера потерял возвращая код обратно. Со сделанными
изменениями грид иногда попадает в бесконечный цикл перерисовки.

**Comment by NikolayUkleyko** [comment]
>Не трогайте это! 3 часа вчера потерял возвращая код обратно. Со сделанными
изменениями грид иногда попадает в бесконечный цикл перерисовки.

Вот, собрались и обсудили.
Теперь понятно что да как.
@gsbelarus , спасибо !
