### ISSUE TITLE
Запретить выполнение автозадач при установке ПИ / настроек

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3747]
Пожалуйста, запретите выполнение автозадач при установке ПИ / настроек. При установке ПИ в некоторых случаях требуется **перезагрузка программы**. При этом есть автозадачи, запускаемые при перезагрузке программы. В результате, установка ПИ откладывается на время выполнения той или иной автозадачи.

**Comment by gsbelarus** [comment]
Это автоматическая перезагрузка или ты сам вручную ее делаешь?

**Comment by NikolayUkleyko** [comment]
Автоматическая перезагрузка.
  Такое точно имеет место при работе с **настройками**. Настройки никто не отменял, так как при помощи данного механизма на базы данных крупных клиентов выполняется установка доработок.

**Comment by gsbelarus** [comment]
Для ПИ теперь точно ни при каких условиях не будут дергаться автозадачи. Для настроек править нет возможности. Код слишком устарел. У большинства даже больших клиентов уже обновили экзешники. Если есть что-то, что невозможно перенести с помощью ПИ (по сравнению с настройками), то надо писать -- исправим.

PS: Настройки более опасный механизм. Особенно для крупных клиентов, так как переносят все состояние объектов. Переписать (затереть) с помощью них что-то важное гораздо проще, чем через ПИ.

**Comment by NikolayUkleyko** [comment]
Спасибо и за это.
