### ISSUE TITLE
Свойства -> методы класса vs Наследование

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3748]
Для наследованных док-тов TgdcUserDocument и TgdcUserDocumentLine не находится веточка методов по кнопке **Методы класса**. Хотя сама ветка есть, и даже есть методы. Исправьте плз, бесит.

**Comment by NikolayUkleyko** [comment]
@alexandra-gsoftware слабо сказано - **бесит**.

**Comment by iamchrisep** [comment]
Сделано

**Comment by alexandra-gsoftware** [comment]
Работает, спасибо!
