### ISSUE TITLE
Информация о БД. Доработки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3749]
Предлагаю следующее:

1. На панель инструментов программы в место, где отображается путь к БД добавить отображение **названия текущей БД**.

2. В список БД добавить поле **Дата и время предыдущего подключения**.
Это будет не лишним при работе с несколькими тестовыми БД.

3. В диалоговое окно реквизитов БД добавить вкладки **Основное** и **Справка**:

    **а**. На вкладку **Основное** перенести регистрационные данные БД.

    **b**. На вкладке **Справка** - предусмотреть область (RichEdit или Memo) для ввода справочной информации о БД.

4. Добавить возможность **копирования в буфер обмена** записи из списка зарегистрированных БД.

**Comment by gsbelarus** [comment]
Под Админом будет путь, под не админом -- название БД. Копирование в буфер из списка добавлено. Вставка из буфера с разбором полного имени БД на составляющие добавлена в диалоговое окно регистрации новой бд.

**Comment by NikolayUkleyko** [comment]
По пунктам 1 и 4 все прекрасно работает. Спасибо !
@gsbelarus, скажите, пожалуйста, что по поводу пунктов 2 и 3 ?
