### ISSUE TITLE
Юзерский документ: Шапка не постится при добавлении позиции.

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3752]
Может, так и задумано, но мне кажется, что раньше шапка постилась сама, если сделать Edit \ Insert позиции?

**Comment by MIchaelShoihet** [comment]
Шапке пост делается только перед Insert, перед Edit он никогда не делался. Притом пост шапке делается только в случае если она находится в состоянии вставки. Для складского документа Post шапке делает в любом случае, т.к. принципиально для формирования складского движения.

**Comment by alexandra-gsoftware** [comment]
да, шапка постится при добавлении позиции, если состояние было инсерт. Спасибо
