### ISSUE TITLE
Бухгалтерия. Автоматическая и ручная проводка. Карта счета. Отображение наименований в поле 'Типовая проводка' (E/V)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3753]
**Исследователь > Бухгалтерия > Карта счета**.

Сейчас проводки, созданные **вручную** в Журнале хоз. операций и проводки, созданные при помощи **автоматических хоз. операций** в колонке **Типовая проводка** отображаются **одинаково**, как - **Произвольная проводка**. Не совсем это корректно. Так как, при анализе данных не понятно какая проводка действительно ручная, а какая не ручная.

Предлагаю следующее. Проводки, созданные через автоматические хоз. операции в Карте счета в колонке **Типовая проводка** отображать непосредственно, как наименование автоматической проводки (например, Перевод в НДС оплаченный, а не Произвольная проводка) или просто **Автоматическая проводка**. При этом, если, проводки, созданные при помощи автоматических хоз. операций впоследствии были отредактированы, то возможен один из вариантов:

**1**. В поле **Типовая проводка** к наименованию проводки добавить слово **(ред.)** или **(испр.)**;

**2**. В поле **Типовая проводка** отображать оригинальное наименованию типовой проводки по автоматической хоз. операции;

**3**. В поле **Типовая проводка** отображать **Произвольная проводка**.

Я за **1-й** вариант. Если нельзя, тогда - **3-й** вариант.
**2-й** вариант не подойдет потому, что исправленная проводка уже не является оригинальной проводкой, созданная при помощи автоматических хоз. операций. То есть, по сути это уже ручная проводка.

**Comment by NikolayUkleyko** [comment]
Очередной раз столкнулся с вышеизложенной проблемой.
@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by MIchaelShoihet** [comment]
На самом деле это просто ошибка формирования Автоматической операции. Надо исправить и сделать, что бы в автоматическую проводку подставлялась название типовой проводки из автоматической операции. И это я сделаю.

**Comment by MIchaelShoihet** [comment]
Я конечно подправил и теперь автоматическая операция будет подставлять правильную типовую проводку. Но надо зайти и пересохранить все используемые автоматические операции... Но и старые результаты так уже и останутся с Произвольной проводкой.

**Comment by MIchaelShoihet** [comment]
Все это появится в ближайшем exe.

**Comment by NikolayUkleyko** [comment]
Проверено.
Есть вопросы.

По вновь созданным автоматическим хоз. операциям в карте счета в поле **Типовая проводка**   значения отображаются **корректно**.

Попробовал на примере, автоматических хоз. операций **Формирование нулевого сальдо по выбранным счетам**: пересохранял автоматическую хоз. операцию, делал копию и т. д.
В карте счета в поле **Типовая проводка** значения отображаются **некорректно**: *Произвольная проводка*.

@MIchaelShoihet , пожалуйста, изложите, Вашу, точку зрения.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@MIchaelShoihet , большое спасибо !
