### ISSUE TITLE
Отчёты из ПИ "GS.Пространство имен.Отчеты" не отображаются в форме "Пространство имен"

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#3756]
Вот теперь так:
![image](https://cloud.githubusercontent.com/assets/8355925/13381475/2298fa66-de6e-11e5-9cb4-41f6e51441f7.png)

![image](https://cloud.githubusercontent.com/assets/8355925/13381479/3231232c-de6e-11e5-9fb3-354f0f9d5ec1.png)

**Comment by NikolayUkleyko** [comment]
Стас, обнови gedemin.exe.

**Comment by stasgm** [comment]
Это проблема  была на exe, которую скачивал днём в всокр. Обновлю сейчас снова и попробую.

**Comment by alexandra-gsoftware** [comment]
это еще на той неделе поправили. может, опять поломали??

**Comment by stasgm** [comment]
Проверил. Работает.
