### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Доступность реквизита 'Корреспонденция с субсчетами' (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3757]
**Исследователь / Бухгалтерия / Журнал-ордер**.

Для удобства работы и не заведения пользователей в заблуждение предлагаю реквизит **Корреспонденция с субсчетами** делать **доступным** только в том случае, если хотя бы один и/или два реквизита **Расшифровка по дебету**, **Расшифровка по кредиту** были выбраны.
В противном случае, реквизит **Корреспонденция с субсчетами** должен быть недоступным.
Незачем позволять выбирать реквизит, не влияющий на формирование формы.

![1](https://cloud.githubusercontent.com/assets/11497453/13388148/abcf3d44-dece-11e5-81eb-f1250bc88564.png)

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by MIchaelShoihet** [comment]
Исправлено. Проверяйте.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, предусмотрите аналогичную возможность и для **Главной книги**.

![2017-06-13_194655](https://user-images.githubusercontent.com/11497453/27094241-1ec130c6-5072-11e7-9274-ee7b55676043.png)
