### ISSUE TITLE
Грид. При переходе по записям в шапке слетает сортировка значений в позиции

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3759]
В случае, когда **в позиции грида** выполнена сортировка записей по клику по колонке, то **при переходе по записям в шапке** слетает **сортировка в позиции**.
Не удобно, так как каждый раз приходится кликать по колонке и/или сортировать данные в колонке при помощи предопределенных фильтров.
Пожалуйста, предусмотрите возможность.

**Comment by NikolayUkleyko** [comment]
@iamchrisep , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by MIchaelShoihet** [comment]
Что бы сортировка не слетала надо использовать фильтр. А так сортировка работает с записями в памяти и естественно что она будет слетать.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , получается, что данную тему можно смело закрыть ?

**Comment by MIchaelShoihet** [comment]
Да. Есть нужда в какой-то постоянной сортировке - сделали фильтр и все

3 мая 2017 г. 9:34 ДП пользователь "NikolayUkleyko" <
notifications@github.com> написал:

**Comment by NikolayUkleyko** [comment]
OK !
