### ISSUE TITLE
Период дат. Нельзя выбрать неограниченный период

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3760]
Как сформировать форму, отчет и т. д. за неограниченный период времени ? Для анализа данных за неограниченный период. Затем, в выявленном периоде выполнять дальнейшие работы с данными.
  В компоненте **TgsPeriodEdit** нельзя выбрать неограниченный период времени. Пустым оставить данный компонент программа не позволяет, так как, вставляет текущий день.
  В тоже время, возможность выбора неограниченного периода времени реализована в карточке ТМЦ, карточке по холдингу.
  Пожалуйста, предусмотрите возможность.

**Comment by alexandra-gsoftware** [comment]
хм, я бы ввела 1900-2100 гг, например, и все построится за неограниченный период.

**Comment by NikolayUkleyko** [comment]
Возможен и такой вариант.
  На практике встречаются ситуации, когда хозяйственная операция была **_случайно (ошибочно)**_ отражена некорректной датой. То есть, < 1900 или > 2100 гг. Сейчас приходится подбирать временной период. Для выявления некорректно введенных данных не мешал бы реквизит **Неограниченный период**. 
  Это моя точка зрения.
  Решайте.

**Comment by MIchaelShoihet** [comment]
Может быть. Но я считаю что его необходимость достаточна мала, поэтому предлагаю закрыть тему.
