### ISSUE TITLE
Мастер установок. Увеличить размер формы по умолчанию

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3763]
**a**.  Пожалуйста, увеличьте размер формы Мастера установок по умолчанию.

**b**.  Предусмотрите, чтобы по умолчанию ширина колонок **Колонка** и **Поле таблицы** были на максимальную ширину соответствующих значений.

  Сейчас приходится **каждый раз** увеличивать размер формы мастера установок и делать больше ширину колонок **Колонка** и **Поле таблицы**.
  Это крайне неудобно.

![1](https://cloud.githubusercontent.com/assets/11497453/13424687/5e79dd84-dfb3-11e5-8464-861a3effeaeb.png)

**Comment by gsbelarus** [comment]
Скоро будет другая система настроек в принципе.

**Comment by NikolayUkleyko** [comment]
Мастер установок сменится иным механизмом визуальных настроек ?
  "Скоро" может затянутся на несколько месяцев, лет.
  Мастер установок проверенное временем решение. Если, не сложно, то поправьте.

**Comment by gsbelarus** [comment]
@zholnerovich обещает, что скоро

**Comment by NikolayUkleyko** [comment]
@gsbelarus , скажите, пожалуйста, новости можно ожидать ?

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения на следующий материал ?

Сохранение параметров грида — GedeminWiki
http://gsbelarus.com/gs/wiki/index.php/%D0%A1%D0%BE%D1%85%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2_%D0%B3%D1%80%D0%B8%D0%B4%D0%B0

**Comment by NikolayUkleyko** [comment]
> _a. Пожалуйста, увеличьте размер формы Мастера установок по умолчанию._

> _Сейчас приходится каждый раз увеличивать размер формы мастера установок..._

@ShlTanya , пожалуйста, хотя бы такое предусмотри.

**Comment by gsbelarus** [comment]
@NikolayUkleyko проверяй

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@gsbelarus , большое спасибо !

**Comment by NikolayUkleyko** [comment]
Данные на всех закладках отлично масштабированы.
При возможности можно увеличить окно с запросом на закладке **Запрос**:
![image](https://user-images.githubusercontent.com/11497453/183040316-30ffa3c0-92fc-4689-9d22-f8d4404e8c1b.png)
