### ISSUE TITLE
ПИ. Предусмотреть горячие клавиши для выполнения/снятия пометки файлов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3764]
Пожалуйста, предусмотрите горячую клавишу для выполнения пометки файлов:
- **Ins** - для пометки только текущего файла;
- **Ins + A** - для пометки текущего файла и всех зависимых;
- **Shift + A** - для снятия пометки со всех файлов.
  
  Сейчас приходится каждый раз обращаться на панель инструментов и выбирать соответствующую команду. Случайно можно выбрать не ту команду. Потом отмена. Это требует выполнения лишних действий. Не удобно.

**Comment by arthur-latunov** [comment]
**Shift + A** - для снятия пометки со всех файлов => **Ctrl+A, Shift+Del**

**Comment by arthur-latunov** [comment]
"Сейчас приходится каждый раз **обращаться на панель инструментов** и выбирать соответствующую команду." **Есть ещё и правый клик мыша.**

**Comment by alexandra-gsoftware** [comment]
а я бы попросила еще убрать из всплывающего меню на гриде пункт "снять пометку со всех записей". когда-то давно ее не было, золотые были времена. или пусть оно хотя бы спрашивает перед тем, как выполниться.

**Comment by NikolayUkleyko** [comment]
@arthur-latunov 

> Shift + A - для снятия пометки со всех файлов => Ctrl+A, Shift+Del

  Несколько действия. Усложняет процесс. При выполнении всего одной комбинации клавиш будет гораздо удобнее.

> Есть ещё и правый клик мыша.

  По удобству проигрывает горячим клавишам. Необходимо время на поиск нужной команды в контекстном меню. Можно промахнуться и опять повтор.

@alexandra-gsoftware 

  Тебе не нравится наличие команды **Снять отметку со всех записей** в контекстном меню ?

![1](https://cloud.githubusercontent.com/assets/11497453/13488164/9a7efb6a-e130-11e5-9d90-ac95f1e9494e.png)

  Я бы оставил данную команду в контекстном меню и добавил предупреждение при выборе такой команды. Чтобы **_случайно**_ не снять отметки со всех записей.

**Comment by alexandra-gsoftware** [comment]
я постоянно промахиваюсь, они ведь рядом(
Предупреждение - тоже ок.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@iamchrisep , спасибо !
:trophy:
