### ISSUE TITLE
Бухгалтерия. В грид типовой проводки добавить локализованные наименования полей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3765]
**Исследователь > Бухгалтерия >Типовые хоз. операции**.

  Пожалуйста, в грид типовой проводки добавьте **локализованное** наименование документа.
  Сейчас для просмотра документа приходится каждый раз открывать на редактированию типовую проводку. Не удобно.

**Comment by MIchaelShoihet** [comment]
Да это полезно.

**Comment by NikolayUkleyko** [comment]
Еще хорошо бы оперативно видеть значения из полей:
- План счетов (при использовании нескольких планов счетов будет удобно);
- Функция.

**Comment by NikolayUkleyko** [comment]
Пожалуйста, еще добавьте локализованное отображение поля **Типовая опер.**.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@iamchrisep , спасибо ! :trophy:
