### ISSUE TITLE
Бухгалтерия. Журнал-ордер, Карта счета, Анализ счета. Выбор счетов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3766]
**_Исследователь / Бухгалтерия / Журнал-ордер, Карта счета, Анализ счета_**.

**a**.  При вводе счета в поле **Счета** (TComboBox) автоматически подставляется близкий счет из уже выбранных до текущего момента счетов.
Не совсем удобно.
Пример. Требуется сформировать форму по 10-у счету с проставленной галкой по реквизиту **Включать субсчета**.
Введя 10, автоматически будет выбран счет 10.01.
Зачем ?
Может пользователь желает ввести счет 10.10, как программа помешает вводу и автоматически перебъет на счет 10.01.
Сейчас приходится удалять фрагмент счета и вводить требуемый.
**Лишние напрягающие действия**.

**b**. Пример. При вводе счета 10.01 в блоке аналитика автоматически **_отображаются не все аналитические признаки**_ по выбранному счету.
Необходимо перевыбрать такой счет еще раз, чтобы по выбранному счету автоматически были **_отображены корректные аналитические признаки_**.

@yoannawx может подтвердить.

Пожалуйста, оперативно устраните вышеприведенные проблемы.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by MIchaelShoihet** [comment]
Подстановка убрана. Она меня то же раздражала, но руки не доходили убрать. Проверяйте.

**Comment by NikolayUkleyko** [comment]
Сейчас счета автоматически не подставляются. Это прекрасно.

Но, введя счет в поле **Счета** (TComboBox) автоматически не обновляется перечень доступных аналитических признаков. Сейчас, для обновления перечня доступных аналитических признаков необходимо кликнуть мышкой по блоку аналитик. Это плохо.

@MIchaelShoihet , пожалуйста, посмотрите.

**Comment by NikolayUkleyko** [comment]
Можно ли при нынешнем функционале Журнала-ордера, при заполнении реквизита **Счет** автоматически обновлять перечень доступных аналитик по указанным счетам ?

Сейчас, после ввода счета и переходе к блокам аналитик они автоматически перестраиваются, что приводит к сбиванию перечня аналитик и в отдельных случаях, к формированию Журнала-ордера по не соответствующим аналитическим признакам.

Сейчас, для корректного обновления перечня аналитик необходимо сперва ввести счет, потом кликнуть в любом реквизите (например, **Период**). Это не крайне не удобно. Если, нельзя, то - нельзя.

**Comment by iamchrisep** [comment]
Сделано. Теперь аналитики будут втоматически обновляться при выборе счета из выпадающего списка, из дерева, а при вводе с клавиатуры нужно просто нажать Enter после ввода

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@iamchrisep , спасибо !

**Comment by NikolayUkleyko** [comment]
Почему-то снова замечена рассматриваемая недоработка.
Вроде бы вопрос уже был решен.

@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.
