### ISSUE TITLE
Сохранение/разворачивание структуры БД

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3767]
Реально ли реализовать возможность сохранения всей структуры БД (метаданные, функции и т. д.) с дальнейшей возможностью создания новой чистой БД с существующей структурой ? Далее в новую чистую БД будут переброшены остатки (склад, бухгалтерия и т. д.).
  Такой функционал будет использоваться в следующих  случаях:
1. Учет в БД велся без контроля вводимых данных на корректность. Для того, чтобы не занулять сальдо по счетам. Пользователи решили с определенной даты вести корректно весь учет в нашей программе. Зачем видеть старые некорректные данные ?
2. При деноминации.
3. При изменение учетной политики, методов ведения учета.
4. При возникновении непоправимого сбоя и невозможности работы в текущей БД.
5. Для уменьшения размера БД. Увеличивается скорость работы с БД. Требуется меньше времени на восстановление БД из архива.
6. Другие ситуации и причины.
   
   При возможности реализации подобного функционала отпадет потребность в применении утилиты по сжатию БД. Для работы утилиты по сжатию БД на большом предприятии требуется немало времени. Вот при использовании возможности сохранения/разворачивания структуры БД и загрузки остатков потребуется гораздо меньше времени.
   У конкурентов (1С) такое реализовано.
   
   Это моя точка зрения.

**Comment by alexandra-gsoftware** [comment]
думаю, реально

**Comment by gsbelarus** [comment]
Я же уже отвечал на подобный вопрос. тут проще не сохранение структуры, а сделать удаление ВСЕХ проводок, ВСЕХ документов, ВСЕГО складского дв. Вот тебе готовая бд с функционалом и справочниками. если это актуально, то сделаем быстро.

**Comment by NikolayUkleyko** [comment]
@alexandra-gsoftware рассмотрю твой вариант.

@gsbelarus Это актуально. Рассмотрю и этот вариант. Как вариант, через командную строку.

  Потом со временем определимся какому варианту отдать предпочтение.

**Comment by MIchaelShoihet** [comment]
Процедура наверняка полезная, но вместо сжатия данных ее использовать нельзя будет. Никто из больших предприятий не хочет начинать с нуля... Хотя бы предыдущий год все хотят видеть и проводить с ним сравнения, опять же зарплата нужна...

**Comment by NikolayUkleyko** [comment]
> опять же зарплата нужна...

  Не спорю. Как вариант, временно обращаться к старой БД. Ведь, любое предприятие начинало с 0.

**Comment by NikolayUkleyko** [comment]
Большой объем данных не кстати при проведении деноминации и других мероприятий. Так как, требуется гораздо больше времени и вычислительной мощности сервера на выполнение той или иной операции.

Я считаю, самый корректный вариант с сохранением/разворачиванием структуры БД с последующим переносом остатков.

**Comment by NikolayUkleyko** [comment]
>Я же уже отвечал на подобный вопрос. тут проще не сохранение структуры, а сделать удаление ВСЕХ проводок, ВСЕХ документов, ВСЕГО складского дв. Вот тебе готовая бд с функционалом и справочниками. если это актуально, то сделаем быстро.

У Евгения сейчас как раз такая ситуация по предприятию **Пицца-Лисица**.
У них сейчас 5 и будет больше филиалов. Работа на отдельной БД, а не как новая рабочая организация.
Необходимо на основании основной БД создать новую БД идентичной структуры, но без данных.
То есть, справочную информацию сохранить, а записи в документах удалить.

@gsbelarus , скажите, пожалуйста, как решить данный вопрос ?

**Comment by gsbelarus** [comment]
Все изменения должны включаться в ПИ и переноситься с помощью ПИ. Никакого другого механизма не будет.

**Comment by alexandra-gsoftware** [comment]
эта штука нужна как раз для баз, где пи не стоят

>>>То есть, справочную информацию сохранить, а записи в документах удалить.

ты имеешь в виду, должны остаться тмц, сотрудники, автомобили, etc?
в старые времена база заново собиралась из настроек, а нужные справочники\документы переносились потоком (ясное дело, это была не база бмкк)

**Comment by YRozmysl** [comment]
Да, имеется это ввиду. И еще, чтобы весь функционал и доработки для этой новой чистой  базы остались точно такими же, как и на той с которой делается вот такая вот пустая (без данных по бухгалтерии, ЖО, складу и т.д.)

**Comment by alexandra-gsoftware** [comment]
есть несколько вариантов решения
1) создается новая бд, и на нее грузятся недостающие данные
1.1)переносить все метаданные (под метаданными имеются в виду еще и макросы, хранилище и тд) на голый эталон. 
1.2) или на старой бд добавить все метаданные, макросы и тд, которые никуда не входят, в новое пи, и снять пи
Первый вариант красивый, но его никто не будет делать, хотя второй вариант тоже никто не будет делать. Проблема обоих вариантов в том, что в скриптах наверняка будут использоваться руиды или даже ид не-метаданных (например, товаров, групп контактов и тд). 

Данные справочников, которые нужны, можно перенести через пи

2) на текущей бд удаляются док-ты, проводки, движения. Проблема в том, что достаточно сложно удалить часть данных, а не всё.

Так а как наша обрезка базы? Она работает?

**Comment by gsbelarus** [comment]
Данные -- это богатство предприятия. Во всем мире системы [BI](https://en.wikipedia.org/wiki/Business_intelligence) стоят огромных денег. Мы же, своими руками, собираемся эти данные удалить? В чем тогда суть нашей работы. Ведь и она при таком подходе полностью невелируется. Получается, что все чем мы занимаемся это херня, так как ее можно абсолютно безболезненно удалить.

Я против таких механизмов.

**Comment by gsbelarus** [comment]
> У Евгения сейчас как раз такая ситуация по предприятию Пицца-Лисица.
> У них сейчас 5 и будет больше филиалов. Работа на отдельной БД, а не как новая рабочая организация.
> Необходимо на основании основной БД создать новую БД идентичной структуры, но без данных.
> То есть, справочную информацию сохранить, а записи в документах удалить.

Еще раз:

1. Если для лисицы сделано что-то такое, что будет полезным всем в общепите -- это должно быть оформлено в ПИ и включено в стандартный пакет **Ресторан Бэк**.
2. Если сделано что-то специфическое именно для этого клиента -- оно должно быть включено в ПИ, в отдельный пакет, назовем его **Лисица**, который зависит от пакета **Ресторан Бэк**.
3. Когда надо будет тиражировать, берем чистую БД и ставим на него пакет **Лисица**. 

Всё. Что тут сложного и непонятного?

**Comment by alexandra-gsoftware** [comment]
@gsbelarus  это как в анекдоте про сферического коня в вакууме. Вы живете в идеальном мире.
У гипотетической лисицы могут быть свои пересчеты в документах, перекрывающие стандартные пи; могут быть вещи, сделанные 10 лет назад, которые кто-то не добавил в пи или настройку. Могут быть скрипты с прописанными там ид-шниками. Если бы на момент начала Гедымина у нас были пи, наследование, сравнение баз, и тд, и тп, то проблем у гипотетической лисицы было бы меньше, но они бы все равно были.

**Comment by gsbelarus** [comment]
Это как сказать "я пил десять лет назад и буду продолжать...". мало ли что там было (конкретно лисица, чтоб ей икалось, это не старый клиент). если мы не разгребем сейчас, то будем и через следующие 10 лет причитать. Когда то надо начинать жить по новому.

**Comment by alexandra-gsoftware** [comment]
я не спорю, но чтобы начать жить по-новому, нужно
1) переписать все документы через наследование. Пересмотреть все скрипты и процедуры, где используются руиды док-тов, ведь теперь мы должны выбирать не из приходной накладной, а из накладной и всех наследников. И это все равно не решит основную проблему: у всех сумма считается как цена на кол-во, а у гипотетической лисицы - как цена на кол-во на * 0,666 (коэффициент лисицы). Даже если для лисицы сделать документ-наследник, для него будет вызываться сначала родительский пересчет. Никто не возьмется переписывать склад с нуля, зная, что проблема всё равно останется.
2) сделать механизм, выщемляющий использование айдишников и руидов в скриптах и процедурах
3) сделать поиск всего, что не входит в ПИ, с добавлением в новые пи для лисицы.
Это первое, что приходит в голову.

**Comment by NikolayUkleyko** [comment]
ПИ это замечательная штука.
В теории все хорошо ложится.
На практике никто не делает детальное формирование ПИ под каждого клиенту (под его специфику).
Повседневные доработки делаются вручную по частям.
Это имеет силу абсолютно для любого предприятие одной сферы деятельности.
На каждом мясокомбинате полно своей специфики.
@MIchaelShoihet подтвердит.

**Comment by gsbelarus** [comment]
И ничего хорошего в этом нет. Надо делать как правильно.

**Comment by NikolayUkleyko** [comment]
Если, у СУБД Firebird большие возможности, то не может быть, что нет запроса или прочих инструментов для получения чистой БД с сохраненной структурой и данными в справочниках ?

**Comment by alexandra-gsoftware** [comment]
есть. Но в гедымине же еще хранилище, макросы, отчеты и тд, и тп, которые тоже нужно сохранить\перенести

**Comment by NikolayUkleyko** [comment]
Если, мы знаем, что необходимо отдельно сохранить данные в таких категориях, как:

>хранилище, макросы, отчеты и тд, и тп,

хорошо бы предусмотреть данную возможность.

**Comment by gsbelarus** [comment]
Перенос/тиражирование функционала только через ПИ. Иначе мы на всю жизнь останемся на уровне детского сада.

**Comment by NikolayUkleyko** [comment]
Хорошо бы предусмотреть возможность нажатия по одной кнопке для сохранения всех объектов БД в ПИ.
Кроме записей по документам, разумеется.
@gsbelarus , скажите, пожалуйста, это реально ?

**Comment by gsbelarus** [comment]
Нет.

**Comment by NikolayUkleyko** [comment]
OK.
