### ISSUE TITLE
Обновление ПИ vs RDB$FIELD_POSITION

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3774]
Пример, есть база, которая прошла модифай последним exe, на которой потом обновляется зарплата через пакет, разумеется, что без галки перезаписывать все поверх. 
Начинаются грузится метаданные, где при загрузке постоянно постоянно выскакивает окно "конфликт изменения данных объекта" , в котором видно, что после модифая поменялось во многих метаданных  RDB$FIELD_POSITION, было раньше, например, 4 , а после модифая стало  5. Внимание вопрос. Это что, для чего это, и как быть при обновлении ПИ?
Я могу, конечно, каждый такой конфликт разрешать, нажимая "не изменять объект в базе", но таких ситуаций ОЧЕНЬ много.

**Comment by gsbelarus** [comment]
Модифай не причем тут. Завтра вернусь со слуцка -- сделаю новый экзешник. Этим экзешником никому ничего не грузи.

**Comment by NikolayUkleyko** [comment]
Все одно и тоже. Танцы с бубнами.
  Ставим галку **Всегда перезаписывать** и нет никаких окон сравнения и прочее. С такими окна установка ПИ превращается в извращение. Сравнение затянется на часы, сутки...

**Comment by alexandra-gsoftware** [comment]
галка - это хорошо, я ее сама вчера использовала против field_position. Но т.к. наши пи идут большими блоками (например, ок-макросы), велика вероятность, что разные люди их одновременно поменяют в разных местах. Объединить их можно только без галки(

**Comment by YRozmysl** [comment]
Какой еще галкой NikolayUkleyko?? ты себе представляешь, как по итогу все станет? чтобы не быть голословным, ты просто обнови с такой галкой на базе мясокомбината ОС, склад, реализацию. А установка без перезаписывания именно дает возможность  увидеть  изменения, которые есть на любой базе, где же установлено ранее было ПИ и далее уже идет "профилактическое обновление", назовем  эту процедуру так. Благодаря такому режиму обновления, ВСЕГДА база находится в актуальном состоянии, касаемо законодательства и прочего. Все проверено неоднократно и имеет практическое применение, а не теоретическое.

**Comment by YRozmysl** [comment]
@gsbelarus последний exe (Дата файла = 11.03.2016 Версия файла = 2.9.2.8569) решил проблему.  Спасибо.

**Comment by NikolayUkleyko** [comment]
@YRozmysl все это известно. В каждой ситуации есть свои особенности.
