### ISSUE TITLE
Документа нет, а запись в GD_DOCUMENT есть

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3776]
Пока возилась с демобазой, видела штук сорок таких. Типы документов разные, есть складские и пользовательские, но только шапки (может, просто повезло и позиции не попались). Демоданные вносились не последним ехе, но я не помню, чтобы в последнее время такая проблема всплывала. Такое случалось и раньше, но сорок документов на практически пустой базе - это много. Кто-нибудь сталкивался?

**Comment by NikolayUkleyko** [comment]
Close.
