### ISSUE TITLE
gd_aiu_companyaccount

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3777]
Пока придется отключить данный триггер так как у людей ошибки при автоматическом импорте выписки. Возможно стоит не блокировать, а переименовывать дублирующиеся счета.

```
CREATE OR ALTER TRIGGER gd_aiu_companyaccount FOR gd_companyaccount
  INACTIVE
  AFTER INSERT OR UPDATE
  POSITION 30000
AS
BEGIN
  IF (EXISTS(
    SELECT
      b.bankcode, b.bankbranch, a.account, COUNT(*)
    FROM
      gd_companyaccount a JOIN gd_bank b 
        ON b.bankkey = a.bankkey
    WHERE
      a.account = NEW.account
    GROUP BY
      b.bankcode, b.bankbranch, a.account
    HAVING
      COUNT(*) > 1)) THEN
  BEGIN      
    EXCEPTION gd_e_exception 'Дублируется номер банковского счета!'; 
  END
END
```

**Comment by NikolayUkleyko** [comment]
Как вариант, можно предусмотреть чистку справочника банковских счетов на уровне **_Modify**_ или через **_командную строку**_. По аналогии, как со справочником **План счетов**.

**Comment by gsbelarus** [comment]
Можно и так. но, там проблема может быть в том, что сам импорт из банк клиента двоит счета. Строгий запрет приведет к тому, что остановится импорт. Если бы он был с самого начала, то ошибку бы вычислили сразу.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
