### ISSUE TITLE
Тип поля. Предусмотреть более наглядное окно выбора бизнес-класса

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3780]
Пожалуйста, в доменах предусмотрите более **наглядное** окно выбора бизнес-класса.

  Сейчас сделано так:
![1](https://cloud.githubusercontent.com/assets/11497453/13746200/56c1a25c-ea03-11e5-8a15-142d997d40ec.png)

  Надо сделать так, как сделано во многих местах программы:
![2](https://cloud.githubusercontent.com/assets/11497453/13746218/659fe0b8-ea03-11e5-9279-077732d563ab.png)

**Comment by NikolayUkleyko** [comment]
Сейчас реально неудобно искать требуемый бизнес-класс.

@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
Коллеги , пожалуйста, изложите ваши точки зрения.

**Comment by alexandra-gsoftware** [comment]
а можно еще заодно сделать эту штуку  (окно выбора) доступной из скриптов?

**Comment by NikolayUkleyko** [comment]
@ShlTanya .

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Если, позже будет возможность, пожалуйста, предусмотрите более наглядный и удобный выбор бизнес-классов для **доменов** и для **полей таблиц**.

**Comment by Polfath** [comment]
Добавил дублирующую кнопку рядом с ComboBox-ом. Можно выбирать бизнес-класс либо через ComboBox, либо через отдельную форму.

**Comment by NikolayUkleyko** [comment]
Проверено.
@Polfath , пожалуйста, добавь возможность заполнения и **_Бизнес-класса_** и **_подтипа_**.
Сейчас ни одно из полей не заполняется.
Пример, Бизнес-класс **TgdcAttrUserDefinedLBRBTree** и подтип **USR$ACC_EXPENSES**.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
