### ISSUE TITLE
загрузка из пи vs gdcc.exe

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3783]
добавьте pls сохранение лога в текстовый файл

**Comment by alexandra-gsoftware** [comment]
Еще такое. Gdcc 6 мин назад заявил, что ПИ загрузилось, а база висит. Уж не знаю, что она делает, at_p_sync выполняет или еще что, но в окне этого не видно(

**Comment by alexandra-gsoftware** [comment]
а теперь окно загрузки пи выглядит вот так:
![gdcc](https://cloud.githubusercontent.com/assets/11487200/13766901/ecb823f8-ea76-11e5-99f6-462582b571d0.jpg)

**Comment by alexandra-gsoftware** [comment]
подвисание окна возможно связано с тем, что ранее были проблемы с сетью. К базе пришлось переподключаться, и, когда после этого запустилась синхронизация с пи, окно уже висело намертво

**Comment by alexandra-gsoftware** [comment]
стало намного лучше!
добавьте плз в фильтр запоминание нескольких предыдущих значений

**Comment by YRozmysl** [comment]
проблема с зависанием осталась. Повторить можно, выбрав пакет ЗПиОК  - это 26 ПИ и установить на базу, на которой уже ранее были установлены ПИ. Есть и база для примера, надо - могу повторить.

**Comment by alexandra-gsoftware** [comment]
сделайте опциональным это зависание. Не знаю, что он с чем сверяет, но при синхронизации с каталогом пи помечено >>, а сравнение с файлом показывает 0 отличий
