### ISSUE TITLE
Ручные проводки

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3784]
А если сделать на уровне платформы документ, который будет создавать ручные проводки (тогда они перестанут быть ручными)?

**Comment by NikolayUkleyko** [comment]
> А если сделать на уровне платформы документ, который будет создавать ручные проводки (тогда они перестанут быть ручными)?

  Да, они будут приручены, как когда-то давно одомашнили животных :cat2: :dog2: :-) 
  Создание такого универсального документа кажется простым на первый взгляд, но не просто для начала его разработки.

**Comment by ilonaand** [comment]
Оно и на первый взгляд кажется не простым. Особенно для сложных проводок. 50 процентов ошибок - от ручных проводок

**Comment by NikolayUkleyko** [comment]
> 50 процентов ошибок - от ручных проводок

  Особенно когда, пользователи **не заполняют** соответствующую аналитику.

**Comment by alexandra-gsoftware** [comment]
Надо кому-нибудь?

**Comment by MIchaelShoihet** [comment]
На самом деле проводка и есть такой документ. На другие случае имеет смысл создавать специализированные документы... Я думаю не надо что-то еще...

**Comment by NikolayUkleyko** [comment]
Если, достаточно существующего функционала и нет необходимости в новом дополнительном функционале, тогда, пожалуйста, закрывайте тему.
