### ISSUE TITLE
Поля-ссылки, добавленные через SelectClause vs ПИ

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3786]
в объекте TgdcTaxResult в SQL-запросе есть строка 

T.ID AS IDTAX

(это стандартный запрос).
В новой книге покупок есть 
  BDT.ID AS BUYDOCTYPEKEY, 
  PDT.ID AS PAYDOCTYPEKEY, 
(добавлено через SelectClause).

Можно ли такие поля-ссылки заменять на РУИДы или вообще не сохранять в ПИ?

**Comment by gsbelarus** [comment]
Взять последний экзешник. Пересохранить ПИ с такими полями. Проверить.
