### ISSUE TITLE
В базе данных не найден объект в конце загрузки списка ПИ

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3789]
После установки демоданных (или, скорее всего, просто после установки большого ПИ), Гедымин повисает. GDCC.exe говорит "Закончена загрузка: Демобаза", и больше ничего, а база висит. Через 25 мин(!) появляется сообщение:
![ns4](https://cloud.githubusercontent.com/assets/11487200/13793055/140f007c-eb06-11e5-903c-b8c6351415d0.JPG)
Нажимаем ОК. База продолжает висеть. Еще через 5 мин мое терпение заканчивается, и я закрываю GDCC. Вылазит новое окно:
![ns5](https://cloud.githubusercontent.com/assets/11487200/13793073/35379066-eb06-11e5-9fb1-1bcaf703d3d9.JPG)
По кнопке Остановить оно не закрывается. Кнопка становится на пару секунд неактивной, потом снова активной. Закрываю иконку GDCC в трее. Прошло уже 34 мин с момента сообщения "Закончена загрузка"!
Еще 5 мин база висит. Диспетчер задач утверждает, что Гедымин что-то усиленно делает, загрузив проц на 30%. И потом отвисает.

По итогу: 2 ч на установку и 40 мин непонятно на что. Что я делаю не так??

**Comment by alexandra-gsoftware** [comment]
После этого ищу на базе РУИД 147161744_467086792. И что же? Объект существует и входит в ПИ, хотя сообщение утверждало, будто бы его нет, и я нажала "удалить из ПИ". Возможно, на исходной БД этот объект входит в несколько ПИ? Но нет, только в одно.
Что бы это значило?

**Comment by alexandra-gsoftware** [comment]
поставила еще раз, подождала дольше. База висит, пока не закроешь gdcc, и еще 5-7 мин после этого. Кстати, документ с РУИДом 147161744_467086792 вполне существует. после загрузки

**Comment by gsbelarus** [comment]
Ничего не висит. Идет работа.

В процессе загрузки ПИ могут меняться данные -- в методах, в скрипах, в триггерах. Чтобы на будущее понять, поменялось что-то относительно файла на диске или нет, надо пересчитать MD5. Сделать это можно только пересохранив ПИ в поток в памяти компьютера, посчитать по нему MD5 и записать в таблицу at_namespace. Для демо базы, сами понимаете, процесс не быстрый.

Можно не пересчитывать, но вы сразу же прибежите в этот багбэйз с записью "показывает ПИ равными, но при сравнении видны различия".

Единственное, что я сделаю, буду выводить в лог ход этого процесса.

**Comment by gsbelarus** [comment]
Пока переоткрою, потому что первое окно "В базе данных не найден объект" совсем из другой оперы.

**Comment by alexandra-gsoftware** [comment]
> > > Можно не пересчитывать, но вы сразу же прибежите в этот багбэйз 

да, да. Посмотрела б я на вас, когда работы по новой базе выше крыши, а она висит час, и непонятно, почему

**Comment by gsbelarus** [comment]
Вот в чем проблема. Таблица USR$WG_TBLCHARGE джоинится на GD_DOCUMENT,
причем в загружаемом документе COMPANYKEY=650001 а рабочая организация
у нас другая -- та которая создана при подключении к БД.

Внутри объекта есть такой код:

```
  dim clause
  clause = TgdcAttrUserDefinedUSR_WG_TBLCHARGEGETWHERECLAUSE
  if clause = "" then
    clause = clause + " WHERE doc.companykey = " & IBLogin.CompanyKey
  else
    clause = clause + " AND doc.companykey = " & IBLogin.CompanyKey
  end if
  TgdcAttrUserDefinedUSR_WG_TBLCHARGEGETWHERECLAUSE = clause

```

Естественно, что он ничего не находит. О чем и предупреждает.

Похоже, аналогичная проблема с USR$WG_SOCINSURANCEINFO, USR$WG_CHREGADDINFO

Вопрос, почему в ПИ сохранено с организацией 650 001???

**Comment by alexandra-gsoftware** [comment]
действительно, ведь наверняка было точное тз, где сказано "создать новую рабочую организацию".  На исходной базе поменяю ей руид и пересохраню всё

**Comment by alexandra-gsoftware** [comment]
но даже если я поменяю руид компании, проблема с TgdcAttrUserDefinedUSR_WG_TBLCHARGEGETWHERECLAUSE не решится

**Comment by alexandra-gsoftware** [comment]
по идее, если мы будем ставить пи куда-то, где установлен фильтр, тоже будет такое сообщение? И почему только по 1 объекту, если их несколько сотен?

**Comment by gsbelarus** [comment]
Ну я же не буду несколько сотен в гіт кідать.

**Comment by alexandra-gsoftware** [comment]
так я только одно сообщение видела когда ставила

**Comment by gsbelarus** [comment]
это у вас был сокращенный режим

**Comment by alexandra-gsoftware** [comment]
сообщение пропало.
