### ISSUE TITLE
Древовидные справочники. Некорректный поиск через комбинацию клавиш 'Ctrl+F'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3792]
На практике в древовидных справочниках выявлен некорректный поиск при помощи клавиш **Ctrl+F**. Пишет, что значение не найдено. Выявлено в справочнике подразделений, клиентов, типовых хоз. операций и. т. д. Потом вручную находишь требуемое значение.
  Пожалуйста, исправьте.

**Comment by NikolayUkleyko** [comment]
Достал такой бесполезный поиск:

![1](https://cloud.githubusercontent.com/assets/11497453/14671263/8a0b2c24-06f9-11e6-8486-8856ddb860d8.png)

![2](https://cloud.githubusercontent.com/assets/11497453/14671266/8edc809a-06f9-11e6-8a4a-057b31aba958.png)

**Comment by MIchaelShoihet** [comment]
Данный поиск не обрабатывает знак % как и другие любые знаки подстановки. Это простой поиск перебором по подстроке и все. Нельзя от всего требовать всего. Есть какие-то ограничения и возможности.

**Comment by MIchaelShoihet** [comment]
Этот поиск так работает во всех местах и в гриде то же.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , благодарю за комментарий.
Закрываем тему.
