### ISSUE TITLE
Позиция документа. Не работают вручную заданные параметры в TgsIBColumnEditors

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3793]
В позиции документа в **TgsIBColumnEditors** задаем сортировку по возрастанию. При сохранение и переоткрытии документа сортировка слетает. Приходится заниматься писаниной в скриптах ради такой мелочи, предусмотренной в параметрах объектов.
  Такое замечено в складских документах. Возможно и в других местах программы.
  Пожалуйста, предусмотрите такую возможность.

![1](https://cloud.githubusercontent.com/assets/11497453/13883381/3560cd06-ed3a-11e5-9a7c-9395856a8fe5.png)

**Comment by alexandra-gsoftware** [comment]
Я думаю, это связано с тем, что поле у тебя - признак складского документа. С ними, насколько я помню, все сложно.

**Comment by NikolayUkleyko** [comment]
@alexandra-gsoftware да, есть и такое. Необходимо "научить" грид вести себя согласно заданных параметров.

**Comment by NikolayUkleyko** [comment]
Оно некорректно работает **не только** в отношении складских признаков.

**Comment by MIchaelShoihet** [comment]
Это только в складских документах. Дело в том что грид там создается в коде, к сожалению этого уже переделать нельзя, поэтому вся настройка грида осуществляется только через скрипты.

**Comment by alexandra-gsoftware** [comment]
так закройте наверно это исъю.

**Comment by NikolayUkleyko** [comment]
Вот и решили.
  Закрываем ?

**Comment by MIchaelShoihet** [comment]
Да
