### ISSUE TITLE
Бухгалтерия. Создать новую форму Журнала-ордера (расширенный)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3794]
**_Исследователь / Бухгалтерия._**

Пожалуйста, предусмотрите новую дополнительную форму **Журнала-ордера (расширенный)** с дополнительными параметрами по второй стороне.
Такое частично реализовано в формах **Анализ счета** и **Карта счета** в блоках **_Корреспондентский счет_**.
По сути в новом Журнале-ордере будет 2-е панели инструментов для ввода параметров.
Тогда, можно будет формировать гораздо большее количество корректных бухгалтерских отчетов. Отпадет необходимость в создании отдельных отчетов.

**Comment by NikolayUkleyko** [comment]
Возможно ли это реализовать **не** в gedemin.exe, а через ПИ ?

**Comment by MIchaelShoihet** [comment]
Нет такие вещи нельзя реализовывать настройками. И я не понял, для чего нужна вторая панель. Надо более подробно. Плюс подумать насколько это точно важно -  ведь такие изменения нужно будет потом протестировать во всех комбинациях...

**Comment by NikolayUkleyko** [comment]
Пример № 1. Сформировать Журнал-ордер по 18-м счетам по аналитике **Статья затрат**.
При этом в качестве корреспондирующих счетов выводить только выбранные счета: 18..., 60... и 68.... При этом по 18-у счету нужен только оборот Дт 18... - Кт 60...

----

Пример № 2. Сформировать Журнал-ордер по 70-у счету по аналитике **Счет и субсчета**.
При этом в качестве корреспондирующих счетов выводить только выбранные счета: 68..., 69..., 76..., 84..., 97....
То есть, исключить затратные счета.

Таких примеров можно приводить много.
На первое время на второй панели настроек предусмотрите, хотя бы реквизит **Кор. счет**.
Так реализовано в формах **Анализ счета**, **Карта счета**.

----

Пример № 3. Сформировать Журнал-ордер в дебет затратных счета с субсчетами по аналитике **Подразделение** и/или **Статья затрат** с кредита 10-х счетов.
При этом не выводить колонки сальдо.
Поэтому необходимо в Журнал-ордер добавить следующие реквизиты:
- корреспондентский счет 
  ![1](https://cloud.githubusercontent.com/assets/11497453/14274996/53fbd3b4-fb1d-11e5-8da8-cfe8d824904d.png);
- не выводить сальдо.

**Comment by NikolayUkleyko** [comment]
Пример № 3. Сформировать Журнал-ордер в дебет затратных счета с субсчетами по аналитике **Подразделение** и/или **Статья затрат** с кредита 10-х счетов. При этом не выводить колонки сальдо. Поэтому необходимо в Журнал-ордер добавить следующие реквизиты:

- корреспондентский счет 
![1](https://cloud.githubusercontent.com/assets/11497453/14274996/53fbd3b4-fb1d-11e5-8da8-cfe8d824904d.png);

- не выводить сальдо.

**Comment by NikolayUkleyko** [comment]
Очередной раз убеждаюсь в актуальности данной темы.

Простая ситуация, Дт 44  (аналитика **Подразделение**) - Кт 60.03.
Бухгалтеру не нужны колонки (сальдо).
Необходимо видеть только кредитовый оборот по счету 60.03 с итогами по подразделениям.
Было бы достаточно сохранить в конфигурацию и распечатать, а вот и нет.
Приходится каждый раз при формировании Журнала-ордера скрывать ненужные колонки.

Все это приводит к созданию нового отчета не в Журнале-ордере.
Зачем, когда все почти есть.

**Comment by NikolayUkleyko** [comment]
По-хорошему не мешало бы сделать **новую** более гибкую форму Журнала-ордера (в перспективе может и Карту счета и т. д.).
С возможностью выбора конкретных параметров (переменных) по оси X и оси Y.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
Коллеги, что, вы, думаете по данной теме ?

**Comment by YRozmysl** [comment]
Да, вот лично для меня было бы актуально, если бы был какой то параметр в котором можно было указать корреспонд. счета и по им бы и построилось. А если там пусто, режим построения остается, как и теперь на данный момент. Можно было бы и сообщение  с предупреждением, что при построении выбраны корр. счета конкретные

**Comment by MIchaelShoihet** [comment]
Это вопрос на перспективу и достаточно не простой. Мне в 99% случаев хватает и текущего. Иногда хочется большего, но это слишком дорого.

**Comment by NikolayUkleyko** [comment]
>Иногда хочется большего, но это слишком дорого.

В тоже время, в **Карте счета** предусмотрен реквизит **Корреспондирующий счет**.
Как это понимать ?

**Comment by MIchaelShoihet** [comment]
Что это уже сделано.

**Comment by NikolayUkleyko** [comment]
ОК.
Спасибо, всем за общение.
