### ISSUE TITLE
ПИ. Количество файлов в окне синхронизации пространств имен

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3795]
В окне синхронизации пространств имен выявлено несоответствие в части количества файлов:
в строке **Выбрано для загрузки файлов** и в окне **Список файлов для загрузки**.

![1](https://cloud.githubusercontent.com/assets/11497453/13982113/2eb37450-f0f9-11e5-93c2-bc962fc37574.png)

  Выбрано 4-е файла, а программа показывает, что выбрано 8-м файлов.
  Так и должно быть ?
  Если, нет, пожалуйста, устраните недоработку.

**Comment by ShlTanya** [comment]
Проверено. Работает корректно.
![2](https://cloud.githubusercontent.com/assets/24572314/21776314/f56621f0-d6aa-11e6-9696-7e9182ade310.jpg)

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает некорректно.

Для наглядности рассматривал **Name_space_new\gedemin-apps\Склад**:

![2017-01-10_140242](https://cloud.githubusercontent.com/assets/11497453/21803968/aa1f3964-d73d-11e6-9a56-cc09c0fc4877.png)

**Comment by gsbelarus** [comment]
А точно последний экзешник?

**Comment by NikolayUkleyko** [comment]
Вот-вот горячий с сайта )

Дата файла           = 09.01.2017
Версия файла         = 2.9.3.8944

**Comment by PiuPauTralala** [comment]
В примерах Николая 8 строчек и отображает как 8 ПИ(фактически 4 ПИ), во втором строчек 4, и пишет 4 ПИ(фактически 2 ПИ).
В примере Татьяны 5 строчек и 5 ПИ.
Выходит кол-во ПИ считается построчно? 1 строка = 1 ПИ?

**Comment by gsbelarus** [comment]
Там скорее всего выводится от мемо Lines.Count а их становится больше из-за переносов строки. Надо брать наверное от изначального списка.

**Comment by NikolayUkleyko** [comment]
Могу предположить, что такое расхождение еще может быть из-за связанных (зависимых) файлов ПИ.
