### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Информационное сообщение

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3798]
**_Исследователь > Бухгалтерия > Журнал-ордер**_.

  Пожалуйста, подскажите, в каком случае при формировании формы программа выдает следующее сообщение:
![1](https://cloud.githubusercontent.com/assets/11497453/14042811/93ab0fda-f28e-11e5-8a27-814c1f0293e1.png)

  Какой заложен лимит/предел на количество выбранных аналитических признаков и количественных показателей ? По какому алгоритму выполняется проверка на корректность выбранных параметров ?

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by MIchaelShoihet** [comment]
Ограничение наложено на размер получаемого запроса. Сколько это уровней аналитики, точно сказать нельзя. Но если оно появляется, значит сформировать такой журнал не возможно и надо уменьшать количество уровней аналитики.
