### ISSUE TITLE
Обновление статистики индексов и окно выполнения

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3800]
**_База данных > Обновление статистики индексов...**_.

![1](https://cloud.githubusercontent.com/assets/11497453/14243460/60287616-fa5e-11e5-8a16-6510dfbd5f9d.png)

Сейчас, в Гедымине при выполнении обновления статистики индексов не отображается окно выполнения. Неудобно и непонятно, что делается и результат. Раньше окно выполнения было.
Пожалуйста, предусмотрите.

**Comment by NikolayUkleyko** [comment]
Выяснил.
Сейчас все логи отображается в GDCC.

**Comment by gsbelarus** [comment]
Кроме лога надо сделать, чтобы бежало окошко с процентами.

**Comment by NikolayUkleyko** [comment]
С отображением % будет замечательно.
