### ISSUE TITLE
GDCC. Доработки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3801]
**1**. Выявлено, что при просмотре лога и активной опции **Обновлять автоматически лог** полностью автоматически лог не обновляется. Для полного обновления лога требуется нажать кнопку **Обновить**. Противоречивая ситуация.

**2**. В трее при 2-й клике по пиктрограммке окно программы не раскрывается. Было бы кстати. Сейчас необходимо обязательно в контекстном меню выбрать **Показать GDCC**. Не совсем удобно.

**Comment by NikolayUkleyko** [comment]
**3**. Пожалуйста, предусмотрите отображение итогов по совокупности процессов. Например, сколько всего времени потребовалось на загрузку платформы и подключение к БД. Сейчас итоги выводятся по каждому процессу по горизонтали.

![1](https://cloud.githubusercontent.com/assets/11497453/14274698/94b64bca-fb1b-11e5-9df7-568df30d7285.png)

**Comment by NikolayUkleyko** [comment]
**4**. При очередном запуске GDCC не сохраняется реквизит **Обновлять лог автоматически**.

**Comment by gsbelarus** [comment]
1. В смысле лог не обновляется? Отлично обновляется. Только лог, а не профайлер. Профайлер и не будет обновляться. Так сделано специально, что только по нажатию на кнопку.
2. Если получится -- сделаем.
3. Для этого -- выгрузка в эксел и там любой анализ. Изначально лог -- это маленькая невесомая программка. Если мы начнем сюда тянуть функционал эксела, то только этим и будем заниматься. 
4. И не должен.

**Comment by gsbelarus** [comment]
И перед тем, как просить, загляните в лог операционной системы и задайтесь вопросом, почему 16 000 программистов Microsoft сделали так и не стали делать так. Был для этого резон. Так же и у нас он есть.

**Comment by NikolayUkleyko** [comment]
1. Можно ли предусмотреть по-умолчанию активный параметр **Параметры / Обновлять лог автоматически** ?

*На практике постоянно вручную выбираешь данный параметр + кнопка **Обновить**.*
*Как вариант предусмотреть дополнительную настройку в gdcc.exe.*

2. Можно ли в строке подключений дополнительно через () или / отображать наименование БД из списка БД в Гедымине ?

*Так будет гораздо удобнее визуализировать БД.
Сейчас, только перебирая подключения можно найти искомую БД.*

3. Можно ли предусмотреть автоматический переход на самое новое подключение к БД ?

*Как вариант предусмотреть дополнительную настройку в gdcc.exe.*

4. Можно ли предусмотреть возможность очистки строки подключений по отключенным БД ?

*При большом перечне БД не очень удобно переключаться.*

![2017-02-21_155411](https://cloud.githubusercontent.com/assets/11497453/23165653/475f58f4-f84e-11e6-8508-7bd44b143c9e.png)
