### ISSUE TITLE
Таблицы. Вычисляемые поля

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3802]
Пожалуйста, подскажите, работает ли данный функционал ?
Если, да, пожалуйста, изложите как его использовать.

![1](https://cloud.githubusercontent.com/assets/11497453/14254233/7fb2e9ce-fa97-11e5-9bd6-76e0306a3419.png)

**Comment by alexandra-gsoftware** [comment]
Если текущее поле является результатом вычисления (в котором обычно участвуют другие поля)
Например, USR$WG_BRIGADEORDERLINE.USR$ALLSUM

Но вычисляемые поля в любом случае лучше не использовать. Потому что поменять им формулу расчета куда сложнее, чем поменять код триггера или метода

**Comment by gsbelarus** [comment]
Зато они не хранятся в БД.

**Comment by alexandra-gsoftware** [comment]
SelectClause рулит!
Но если вы сделаете простое редактирование таких полей и доменов, и чтоб переносилось через пи...)

**Comment by NikolayUkleyko** [comment]
Я предполагал, что есть механизм задания алгоритма пересчета того или иного поля гораздо проще: по формуле. То есть, не на уровне программиста, а на уровне пользователя. Сейчас в нашей программе поменяешь один алгоритм, как придется менять другой и все связанное. Что не есть хорошо. Все это приводит к танцам с бубном.
Надежна та конструкция, которая проста. У нас конструкция очень не проста.

Нельзя ли предусмотреть вариантность при работе пересчета по тому или иному документу:
- использовать только существующий алгоритм;
- использовать только пересчет по формуле.

Таким образом, ничего не будет конфликтовать.
Это сугубо мои предположения по данной теме.

**Comment by alexandra-gsoftware** [comment]
не знаю, что ты имеешь в виду под формулой, но с вычисляемыми полями это не связано.

**Comment by NikolayUkleyko** [comment]
Благодарю за информацию !
Спасибо !
