### ISSUE TITLE
Нельзя создать наследника бизнес-класса Человек

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3803]
Проверить.

**Comment by gsbelarus** [comment]
Сделана возможность наследования для класса TgdcContact. @stasgm

**Comment by gsbelarus** [comment]
@stasgm обнови экзешник. Наследуй сотрудника от таблицы GD_EMPLOYEE.

**Comment by stasgm** [comment]
@gsbelarus Проверил, работает. А если нужен наследник для TgdcDepartment, то как поступить?
