### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Предусмотреть множественное редактирование записей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3804]
**Исследователь / Бухгалтерия / Журнал хоз. операций**.

Пожалуйста, предусмотрите корректное редактирование записей при множественном выделении. Пример, выделил 100 записей > вызвал их на редактирование > изменил реквизит (например, счет, подразделение и т. д.) > нажал на кнопку OK. В результате внесенное изменение будет только по той записи, на которой был указан курсор. Остальные 99 записей не изменились.

**Comment by MIchaelShoihet** [comment]
В Журнале хоз операций множественное редактирование не работает и пока не планируется (есть техническая сложность). Сделаем предупреждение.

**Comment by NikolayUkleyko** [comment]
Жаль. Пусть, хоть будет предупреждение.

**Comment by NikolayUkleyko** [comment]
Большое спасибо, @MIchaelShoihet !
Проверено.

Теперь, при вышеприведенной ситуации сперва программа отобразить такое окно:
![2018-10-25_153213](https://user-images.githubusercontent.com/11497453/47500469-8fc5b800-d86b-11e8-951e-f8c8cde60646.jpg)

Затем, программа отобразит такое окно:
![2018-10-25_153243](https://user-images.githubusercontent.com/11497453/47500489-9ce2a700-d86b-11e8-81f4-f9bdd97fdf4b.jpg)

Может все это пустяки, но в данном случае 2-е окно лишнее.
Я так, понимаю, что оно перекочевало издавна.
