### ISSUE TITLE
Бухгалтерия. Сообщение при попытке перехода в Журнал хоз. операций

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3805]
**_Исследователь / Бухгалтерия / Карта счета, Журнал хоз. операций_**.

Если, в Журнале хоз. операций выбран фильтр, то при попытке перехода на соответствующую запись из Карты счета программа выдает соответствующее сообщение:

![1](https://cloud.githubusercontent.com/assets/11497453/14276110/4f21eb00-fb25-11e5-941c-84b174d4e0be.png)

Однако, в любом документе на панели инструментов есть кнопка **Перейти на проводку**.
Если, в Журнале хоз. операций выбран фильтр, то при попытке перехода на соответствующую проводку из документа по выбранной записи программа не выдает соответствующее сообщение.
В данной ситуации тоже не мешало бы вышеприведенное сообщение.

Заголовок окна не мешало бы переименовать с **_Warning_**_ на **_Внимание !_**.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by NikolayUkleyko** [comment]
По данной теме доработок не обнаружил.

**Comment by iamchrisep** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !
