### ISSUE TITLE
Удаляется запись. А не должна.

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3806]
По мойму это уже исправляли то туда, то сюда по нескольку раз. Сейчас в простом справочнике если дублировать запись, затем в диалоге нажать Новый, затем отмена, то сдублированная запись пропадет. Хотя, по идее, кнопка Новый соответствует Сохранению текущей записи. Т.е. должна остаться.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
