### ISSUE TITLE
Береза МКК. Банковская выписка. Недоступны отчеты

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3808]
**_Исследователь > Банк > Банковская выписка или Выписки по р/с**_.

На новейшем gedemin.exe по данному документу недоступны отчеты. Копирование и вставка не помогает. На эталоне с этим порядок.

Пожалуйста, предусмотрите возможность.

**Comment by gsbelarus** [comment]
А они есть в базе? Что значит недоступны?

**Comment by MIchaelShoihet** [comment]
Печать выписки, Разноска выписки, Распределение картотеки по очередности платежа.

**Comment by gsbelarus** [comment]
Надо создать отчет в этом окне, посмотреть какое значение reportgroupkey он получит и присвоить это значение через SQL UPDATE "пропавшим" отчетам.

**Comment by PiuPauTralala** [comment]
Сделано.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !

**Comment by alexandra-gsoftware** [comment]
То же самое теперь с отчетами в форме просмотра ПИ. Последние недели, если их ставить на чистую базу, то они отображались только после переоткрытия гедымина. Теперь @YRozmysl заметил, что и после переоткрытия они не появляются (а в редакторе скрипт-объектов они видны)
