### ISSUE TITLE
Не присваивается значение Variables

### ISSUE THREAD

**Issue by PiuPauTralala** [GoldenSoftwareLtd/gedemin#3811]
В документе Материальный склад. 11. Возврат с доработки (переработки) при изменениие приходного колличества на поле "USR$ADDSUMNCU" перестает корректно работать присвоение значения вариэйблу. От этого весь механизм пересчетов летит в тартарары.

**Comment by gsbelarus** [comment]
? Какому вариэйблу. Код надо показать, то ничего не понятно.

**Comment by gsbelarus** [comment]
1. Обновить экзешник и gdcc.exe
2. Запустить проблемный код
3. В логе (источник debug) смотреть записи о присвоении значения переменной
4. При необходимости поставить точки останова на присвоении и посмотреть когда, откуда, что вызывается и какие значения присваиваются

**Comment by PiuPauTralala** [comment]
Нет такого источника, exe 2.9.2.8622.

**Comment by gsbelarus** [comment]
Значит просто поставьте брейкпоинты в коде. Где то еще у вас присваивается. Или вы разные имена проверяете.

**Comment by gsbelarus** [comment]
И должна быть включена отладка в редакторе со.
