### ISSUE TITLE
Бухгалтерия. Разное содержание в конструкторе функций и в тексте функции в редакторе скрипт-объектов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3812]
**_Исследователь > Бухгалтерия > Типовые хоз. операции, Автоматические хоз. операции, Отчеты бухгалтерии, Настройка функций**_.

Не первый раз выявлено. При редактировании текста функции из редактора-скрипт объектов (обновлении из ПИ), внесенные изменения, не видны в конструкторе функций: как в блоках, так и в тексте. Возникают проблемы. Поэтому, необходимо предусмотреть следующее:
1. При возникновении ошибки **запретить переброску** в редактор скрипт-объектов или если, не запрещать переброску, то сделать текст функции **только на чтение**.
2. Предусмотреть глобальный механизм проверки целостности (соответствия) между конструктором (блоки, текст функции) и текстом функции в редакторе скрипт-объектов. При выявлении расхождений при необходимости **приводить в соответствие**, взяв за основу данные из конструктора функций.

Это крайне важно !!!
Пожалуйста, устраните недоработку.

**Comment by YRozmysl** [comment]
Да, недавно столкнулся с вышеописанным. Как оно получилось это уже второй вопрос, но такие вещи очень непросто выявить. Чаще всего это может заметить только конечный пользователь.

**Comment by NikolayUkleyko** [comment]
Помимо добавления в ПИ типовой хоз. операции и типовой проводки отдельно в ПИ добавляется еще и **функция типовой проводки из редактора скрипт-объектов**.

При изменении функции типовой проводки из редактора скрипт-объектов и закрытии редактора скрипт-объектов при формировании проводок срабатывает текст функции из редактора скрипт-объектов, а не из конструктора функций. Тексты функций разные.

При установке ПИ, если **_обновить только типовую проводку**_ и **_не обновлять функцию из редактора скрипт-объектов**_, то за основу будет взята функция из редактора скрипт-объектов. Для приведения в соответствие текстов функций между типовой проводкой и редактором скрипт-объектов необходимо вызвать на редактирование типовую проводу и пересохранить, нажав ОК.

**Comment by gsbelarus** [comment]
**При изменении функции типовой проводки из редактора скрипт-объектов** функцию типовой проводки НЕЛЬЗЯ менятьв редакторе скрипт-объектов. Только через конструктор функций.

**Comment by NikolayUkleyko** [comment]
Это самом собой разумеется.
На практике встречаются вышеприведенные ситуации.
