### ISSUE TITLE
Прогресс бар в gdcc

### ISSUE THREAD

**Issue by hirurg-lybitel** [GoldenSoftwareLtd/gedemin#3813]
Если запустить gdcc после подключения к базе, то в нём не будет активного подключения, а значит и форма прогресса не отобразится при попытке её использовать.
Надо бы как-то через метод устанавливать подключение в gdcc

**Comment by gsbelarus** [comment]
А зачем ее запускать после, если она автоматом запускается при старте гедымина?

**Comment by hirurg-lybitel** [comment]
Если есть возможность закрыть gdcc при активном подключении к базе данных, то должна быть и обработка этого случая.

**Comment by gsbelarus** [comment]
Я уберу команду закрыть. Не хочется утяжелять лог. Его задача логировать и не загружать процессор. Лишнюю проверку еще делать не хочется.

**Comment by hirurg-lybitel** [comment]
Тогда надо решить вопрос с бесконечно растущим количеством закладок. Через неделю работы будет невозможно ничего проанализировать в gdcc.

**Comment by NikolayUkleyko** [comment]
Меня тоже бесит

> бесконечно растущим количеством закладок.

@hirurg-lybitel , ответ будет просто: 16 000 программистов из Microsoft...
