### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Ошибка при редактировании и сохранении конфигурации

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3814]
**_Исследователь > Бухгалтерия > Журнал-ордер**_.

При сохранении и редактировании конфигурации в случае дублирующихся значений по одной аналитике программа выдает окна с сообщениями об ошибке:

![1](https://cloud.githubusercontent.com/assets/11497453/14601513/12f154a4-056b-11e6-84ea-7d963897a103.png)
![2](https://cloud.githubusercontent.com/assets/11497453/14601515/15e170d6-056b-11e6-9af7-8957b5c92d5f.png)

При попытке задания дублирующихся значений по одной аналитике на панели инструментов программа позволяет это сделать и сформировать отчет. При попытке сохранения в конфигурацию программа автоматически удаляет дублирующиеся значения по одной аналитике.

Имеет силу и для Карты счета, и для Анализа счета.

Пожалуйста, предусмотрите блокировку и/или локализованные сообщения для вышеприведенной ситуации.

**Comment by NikolayUkleyko** [comment]
Как вариант, при выборе уже выбранного значения аналитики выдавать сообщение типа **Нельзя выбрать дублирующееся значение аналитики** и запрещать выбор.

@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by MIchaelShoihet** [comment]
Сделано так: при вводе в конфигурацию дублирующего значения программа будет выдавать предупреждение о том что оно не будет сохранено с возможностью остаться в диалоге и изменить его (возможно просто по ошибке указано то же значение). Проверять на ближайших exe.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !
