### ISSUE TITLE
Бухгалтерия. Переход из Журнала-ордера на пустую Карту счета

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3815]
**_Исследователь > Бухгалтерия > Журнал-ордер, Карта счета**_.

При формировании Журнала-ордера согласно параметров, указанных в рис. 1

![1](https://cloud.githubusercontent.com/assets/11497453/14641935/1bd6fbdc-0651-11e6-9725-f7df9027d472.png)

, получаем пустую Карту счета (рис. 2).

![2](https://cloud.githubusercontent.com/assets/11497453/14641946/2826b512-0651-11e6-85d3-c86710f7c260.png)

Такого быть не должно. В данном случае в Карте счета в блоке **Корреспондентский счет** должен быть указан счет 10, а не субсчет 10.01 и в реквизите **Включать субсчета** проставлена галка.

Это вызывает вопросы у бухгалтеров. Это является грубейшей недоработкой. Такое выявлено не первый раз.

Конкретная ситуация смоделирована на демобазе: india/3053:k:\Etalon\Demobase\DB\Test\BUSINESS_11_30.FDB

Пожалуйста, устраните недоработку.

**Comment by NikolayUkleyko** [comment]
Как будто никто не работает с данным функционалом ?

**Comment by MIchaelShoihet** [comment]
Будет исправлено.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , заранее спасибо ! На самом деле сейчас сложнее анализировать данные.

**Comment by MIchaelShoihet** [comment]
Исправлено. Проверяйте в ближайших exe.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !
