### ISSUE TITLE
Бухгалтерия. Переход из Анализа счета в Карту счета по кредитовому обороту

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3816]
**_Исследователь > Бухгалтерия > Анализ счета, Карта счета**_.

При переходе из Анализа счета в Карту счета по **кредитовому обороту** (рис. 1)

![1](https://cloud.githubusercontent.com/assets/11497453/14642308/aa61502c-0652-11e6-9dd1-b3d3b19c3ccd.png)

программа формирует расшифровку по **дебетовому обороту** (рис. 2.).

![2](https://cloud.githubusercontent.com/assets/11497453/14642332/be5b7706-0652-11e6-8fc1-0da609e131a8.png)

Такого быть не должно. В данном случае в Карте счета должна быть расшифровка по кредиту. То есть, в Карте счета в блоке **Корреспондентский счет** должно быть выбрано **Кредит** и по реквизиту **Включать субсчета** проставлена галка.

Это вызывает вопросы у бухгалтеров. Это является грубейшей недоработкой. Такое выявлено не первый раз.

Конкретная ситуация смоделирована на демобазе: india/3053:k:\Etalon\Demobase\DB\Test\BUSINESS_11_30.FDB

Пожалуйста, устраните недоработку.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, здесь посмотрите.

**Comment by MIchaelShoihet** [comment]
Исправлено. Проверяйте в ближайших exe.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !
