### ISSUE TITLE
Бухгалтерия. Не сразу формируется проводка по шапке, если есть еще и проводка по позиции

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3817]
**_Исследователь / Бухгалтерия / Типовые хоз. операции_.**

Если, по документу настроено формирование проводки и по шапке, и по позиции документа, то при сохранении документа сразу формируется только проводка по позиции, а по шапке - нет.
В данном случае для формирования проводки по шапке необходимо **_перепровести запись по документу_**.
Все вызывает **большие вопросы со стороны пользователей**.
На самом деле, зачем дергать записи по документу ?
На практике встречаются различные документы с самым разным объемом данных.

**Очень актуально для Жанны и Атланта**.

Пожалуйста, предусмотрите возможность.

**Comment by MIchaelShoihet** [comment]
На самом деле не правда. Такая ситуация возможно только в случае, если проводки по шапке зависят от позиции и есть проводки по позиции. При редактировании документа в диалоговом окне если проводка установлена только по шапке, то при сохранении документа, проводка формируется заново, но если есть проводки по позициям то такого пересохранения не вызывается, что бы не сохранение документа не вызывало большой паузы (будут пересозданы проводки по позициям). Однако если разработчику такое вдруг понадобилось, то он сам в методе окна BeforePost должен вызвать метод CreateEntry у объекта шапки.
