### ISSUE TITLE
Снова пропал автозапуск gcc при указании параметров подключения к базе в gedemin.exe

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#3820]
Снова пропал автозапуск gcc при явном указании параметров подключения (например в ярлыке прописаны параметры подключения)

**Comment by gsbelarus** [comment]
Проверяю -- работает. Надо повторить, чтобы разобраться. Там случаем программа не из сетевой папки запускается?

**Comment by gsbelarus** [comment]
И полный текст командной строки приведи. может там еще какие ключи указаны.

**Comment by stasgm** [comment]
Например
"c:\Program Files (x86)\Golden Software\Gedemin\gedemin.exe" /sn "localhost:f:\Work\Bases\Atlant\SERVER.FDB" /user Administrator /password Administrator
