### ISSUE TITLE
Грид. Складские документы. Не стабильно работает форматирование

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3821]
**_Исследователь / Материальный склад / 07. Списание материалов_.**

В диалоговой форме в гриде в поле **Количество (QUANTITY)** указали формат **#,####0.0000**. При изменении значения в данной колонке тут же **_произвольно**_ меняется формат отображаемых данных, то с 2-я знаками, то с 4-я знаками после запятой. Пользователи в недоумении.
При этом, вернув настройки форматирования к  #,##0.00, как при изменении данных также наблюдается произвольная смена формата отображаемых данных.

Пробовали различные варианты - ничего не помогло.
Вышеприведенная информация распространяется на складские документы. В пользовательских документах такое не выявлено.

Пожалуйста, подскажите, что не так. При необходимости устраните недоработку.

**Comment by NikolayUkleyko** [comment]
Жанна, подтвердит.
Кстати, это для Атланта, а не для меня.

**Comment by MIchaelShoihet** [comment]
Настройка грида должна быть одинаковая в форме просмотра и в диалоговом окне, тогда должно быть все хорошо.

**Comment by NikolayUkleyko** [comment]
Я предпочитаю настраивать грид снаружи и внутри документа 1 к 1. Подобный вопрос может возникнуть у любого специалиста и у любого пользователя. Что приводит в заблуждение.
Не знаю, является ли это недоработкой или нет.
По вашему, @MIchaelShoihet , @gsbelarus, усмотрению закройте данную тему.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
Данная ситуация возникает при выборе товаров из Остатков ТМЦ. Для исключения данной ошибки установите соответствующий формат поля Количество  в таблице  с выбранными значениями в форме  Остатков ТМЦ.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , проверил.
Ничего не помогает.
Пожалуйста, для примера можно посмотреть здесь
**Исследователь / Основные средства / ОС. Начисление амортизации.**

Обрати внимание на значения в колонках:
- Баланс. цена;
- Старый износ;
- Начисленный износ;
- Новый износ.

@ShlTanya , учти, что по документам по учету основных средств фигурирует количество равное 1.
Соответствующая колонка скрыта.

**Comment by ShlTanya** [comment]
Николай.. проверила.. Работает все хорошо, когда формат редактируемой колонки в документе совпадает с форматом такой же колонки в таблице **Выбранные значения** (внизу формы Остатки ТМЦ)

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

----

Вот все дело было в настройках грида **Выбранные записи** (внизу формы Остатки ТМЦ).
