### ISSUE TITLE
невозможно выйти из системы, пока не закрыт gdcc

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3822]
А закрыть его можно только из диспетчера задач

**Comment by hirurg-lybitel** [comment]
А разве "Файл - Выйти" не работает?

**Comment by alexandra-gsoftware** [comment]
когда я это  увидела, опции выйти не было (раньше была)

**Comment by gsbelarus** [comment]
Не могу повторить. Выходити так и эдак.

**Comment by gsbelarus** [comment]
Словил такой случай. Почему такое происходит пока не понятно.

**Comment by gsbelarus** [comment]
Надо проверить вариант, когда gdcc запускается из бат файла до гедымина. На сервере такая ситуация и похоже не дает потом перегружать комп.
