### ISSUE TITLE
Автоматом сформировать корректирующие проводки

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3823]
Я бы добавил в утилиту такой функционал:
1. Указываем деноминированную и неденоминированную БД.
2. Утилита подсчитывет конечное сальдо в неденоминированной БД, в разрезе аналитик, и формирует корректирующие проводки в деноминированной.

Аналогично можно сделать для складских остатков.

@MIchaelShoihet

**Comment by NikolayUkleyko** [comment]
@gsbelarus что имеете в виду под

> Утилита подсчитывет конечное сальдо в неденоминированной БД, в разрезе аналитик, и формирует корректирующие проводки в деноминированной.

то есть, какие именно проводки ?

**Comment by gsbelarus** [comment]
Хотя бы со счетом 00. Чтобы остатки сходились.

**Comment by NikolayUkleyko** [comment]
На практике складские и бухгалтерские остатки не сходятся в следующих случаях:
1. На копейки из-за округлений.
2. На значительные суммы, из-за того, что учет не ведется должным образом. Здесь пользователи ведут:
- только складской или бухгалтерский учет. Не преследуют цель синхронизации остатков.
- и складской или бухгалтерский учет. Преследуют цель синхронизации остатков.

Функционал корректировки складского и бухгалтерского выходит за рамки предназначения утилиты ( / 10 000).

Функционал корректировки складского и бухгалтерского рассматривается здесь https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/111

**Comment by gsbelarus** [comment]
Речь не о схождении складских и бухг данных. Речь о том, чтобы сходились числа до деноминации и после.

Например,  в старой базе по счету Х, по аналитике А были три проводки в Дебет:

23.12
10.46
12.18

В сумме, дебетовый остаток:

45.76 -- округленно 46 руб.

После деноминированиябудет:

0.0023
0.0010
0.0012

В сумме -- 0.0045.

Задача добавить проводкой с забалансовым счетом 0.0001

Чтобы, если человек построит сальдо на 01.07.2016 в старой БД
и в новой -- они совпадут.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
