### ISSUE TITLE
dnmn.exe

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3825]
Утилита должна:
1. Проверить тип dcurrency и если у него не 4 знака, а меньше -- скорректировать.
2. В процессе деноминации проверять у таблицы поля (подлежайшие деноминации) и если у них целочисленный домен или тип с менее чем 4-мя знаками после запятой, то корректировать.
3. Проверять и менять домен для полей с курсами валют.
4. По завершении процесса обнулять DBID.

**Comment by iamchrisep** [comment]
1, 2, 3. Просто скорректировать тип не получается. Выдержка из руководства Firebird:
Не допустимы любые изменения типа, которые могут привести к потере данных. Например, количество символов в новом типе для столбца не может быть меньше, чем было установлено ранее.
Действительно, если домен DCURRENCY у нас DECIMAL(15,2), то изменить его на DECIMAL(15,4) невозможно. Или же если поле в таблице имеет тип не DCURRENCY, а, например, DCURR - DECIMAL(15,2), изменить его тип на DCURRENCY уже не получится. В утилите я преобразование полей к DCURRENCY в случае, если они имеют другой тип, оставила, но если встретится такое вот поле, то будет ошибка. Как с этим поступить?

**Comment by MIchaelShoihet** [comment]
Всегда есть решение. Добавляется temp поле туда переносятся данные из изменяемого поля, изменяемое поле удаляется, создается заново с новым типом и туда переносятся данные из tmp поля, которое потом удаляется. Слов много но на самом деле получается 6 запросов достаточно простых.

**Comment by iamchrisep** [comment]
Да, тогда, может, еще проще - просто tmp-поле переименовать?

**Comment by gsbelarus** [comment]
А можно переименовывать?

**Comment by iamchrisep** [comment]
Судя по руководству - да, существующие столбцы можно переименовывать. Но есть на это ограничения:

Ключевое слово TO переименовывает существующий столбец. Новое имя столбца не должно присутствовать в таблице.
Невозможно  изменение  имени  столбца,  если  этот  столбец  включён  в  какое-либо ограничение — первичный или уникальный ключ, внешний ключ, ограничение столбца или проверочное ограничение таблицы CHECK. Имя столбца также нельзя изменить, если этот столбец таблицы используется в каком-либо триггере, в хранимой процедуре или представлении.

**Comment by MIchaelShoihet** [comment]
Тогда переименовывайте. Я думаю что те же ограничения есть и у удаления поля.

**Comment by gsbelarus** [comment]
Если вы не сможете переименовать, то удалить и подавно не сможете.

Давайте вернемся к началу:
1. Домен dcurrency у вас получилось поменять? Что с существующими полями будет вы протестировали? На граничных значениях?

Протестировали, значит взяли бд. сделали там dcurrency(15,2). Сделали таблицу с полем с этим доменом. Ввели значения: 10, 10.1, 10.01, 10.001. С помощью INSERT INTO.

Прогнали утилиту на этой бд и сделали бэкап-восстановление.

Смотрим что получилось. Тип перевелся в новый? Ничего не потерялось?

Теперь остаются поля, которые денежные, но не на основе домена dcurrency. С ними придется через временное поле разбираться.

**Comment by iamchrisep** [comment]
1. Домен поменять не получается. Как проверяла: взяла БД с DCURRENCY DECIMAL(15,4), сделала ALTER DOMAIN DCURRENCY TYPE DECIMAL(15,2) - прошло, следом ALTER DOMAIN DCURRENCY TYPE DECIMAL(15,4) - ошибка
   Неудачное обновление метаданных:; New scale specified for column DCURRENCY must be at most 2
   GDSCode = 335544351

**Comment by gsbelarus** [comment]
Так почему вы говорите что все сделано. Это же ключевой момент. Фактически НИЧЕГО не работает.

**Comment by gsbelarus** [comment]
Получается так:
1. Перед деноминированием надо перевести типы полей в нужную точность.
2. Для этого проверяем заданный список полей и смотрим какая у каждого ФИЗИЧЕСКАЯ ТОЧНОСТЬ. Неважно какой у этого поля домен. Поля, которые не подходят по точности (какую мы приняли? 4 знака после запятой?) попадают в специальный список.
3. Обрабатываем этот список. А именно: 1) группируем поля по таблицам 2) для каждой таблицы из этого списка, для каждого поля подлежащего обработке создаем временное с нормальным типом и переносим туда данные. Группируем для того, чтобы сделать перенос одним запросом. 3) после переноса и коммита -- удаляем все исходные поля. 4) после обработки всех таблиц. по идее. мы сможем скорректировать домен dcurrency удалив и воссоздав его, если понадобится. 5) теперь создаем исходные поля и переносим данные в обратную сторону. даже страшно подумать сколько по времени будет это работать. и скорее всего весь процесс надо вести в подключении с отключенной сборкой мусора.
4. Кроме триггеров изначально надо будет сохранить и удалить все чеки, а после завершенеия процесса восстановить их.

**Comment by alexandra-gsoftware** [comment]
А почему бы не сделать это через апдейт системных таблиц? Все будет хорошо, если в поле (15,2) нет значений, которые не влезли бы в (15,4). А это можно предварительно проверить (программка Кристины, которая собирает статистику по числовым полям, определяет в том числе максимальное и минимальное значение каждого поля)

**Comment by iamchrisep** [comment]
3.4) Я так понимаю, что корректировку через перенос во временное поле будем проводить только для тех полей, которые есть в списке. В таком случае, что делать, если домен DCURRENCY используется в тех полях, которые в этом списке не указаны? Делать дополнительную проверку на присутствие таких полей в базе и корректировать их аналогично, путем переноса через временное поле? 
И еще, из руководства:
Оператор DROP DOMAIN удаляет домен, существующий в базе данных. Невозможно удалить домен, на который ссылаются столбцы таблиц базы данных или если он был задействован  в  одном  из  PSQL  модулей.  Чтобы  удалить  такой  домен  необходимо удалить из таблиц все столбцы, ссылающиеся на домен и удалить все ссылки на домен из PSQL модулей.
У нас такая ситуация возможна, с PSQL модулями?

Дополнительно Андрей Петрович сказал сделать:
1) Список триггеров, которые нужно отключить, хранить в отдельно созданной таблице на случай сбоя при деноминации. Таблица создается в деноминируемой БД.
2) Логирование вести более подробное, по каждому действию, например, на каждое отключение каждого триггера.

@MIchaelShoihet , в списке полей для деноминации есть поля с именами "Месяц", "Долг в месяцах", "Погашено месяцев", "Документ переоценки" и т.п. Так должно быть, или их случайно отметили?

**Comment by MIchaelShoihet** [comment]
Я выверку еще до конца не закончил. Так что возможны ошибки.

**Comment by MIchaelShoihet** [comment]
Вообще надо провести простой анализ на сколько много есть полей которые имеют тип с плохой точностью. На какой базе DCURRENCY 15, 2  - есть разве такие базы? Может просто если тип DCURRENCY 15, 2 то не проводить деноминацию. И если встретились поля с плохой точностью (не DCURRENCY) то эти поля сохранять и не деноминировать?

**Comment by iamchrisep** [comment]
Если поля с плохой точностью не деноминировать, то их можно просто изначально не включать в список полей, который будет в утилите.

**Comment by MIchaelShoihet** [comment]
Может быть ситуация, когда одно и то же поле имеет на разных базах разную размерность. А второй попробуйте проверить у всех 2000 полей для деноминации их размерность. То что можно проверить программно, лучше так и проверить. Плюс мы можем сказать пользователю какие поля не деноминированы, что бы их можно было в ручную обработать.

**Comment by iamchrisep** [comment]
Да, согласна, да и пользователь может добавить в список свои поля, а они тоже могут быть с неподходящей точностью

**Comment by gsbelarus** [comment]
Когда запускается процесс Деноминирования, то сначала проверяются заданные поля на точность. Если есть хоть одно неправильное, то исправляем типы:
1. Проверяем и правим, если надо, dcurrency
2. Все денежные поля, у которых неправильный тип, не 4 знака после запятой, переводим на dcurrency.

После этого сообщаем пользователю, что он ОБЯЗАТЕЛЬНО должен провести бэкап-ресторе и только потом снова запускать деноминирование. Завершаем программу.
