### ISSUE TITLE
Слишком много вкладок в редакторе скрипт-объектов

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3826]
Появляется вот такая ошибка:
frmGedeminProperty. EWin32Error: Win32 Error.  Code: 1158.
Текущий процесс использовал все системные разрешения по управлению объектами диспетчера окон
После этого все кнопки, меню и тд перестают работать. Может, можно как-то отслеживать эту ситуацию и не давать открывать новые вкладки?

**Comment by gsbelarus** [comment]
А сколько вкладок вы открыли?

**Comment by gsbelarus** [comment]
Эту ситуацию можно повторить?

**Comment by alexandra-gsoftware** [comment]
много)). Можем завтра попробовать

**Comment by gsbelarus** [comment]
Скорее всего в коде надо проставить лимит на открытые вкладки. Штук 20 должно хватить нормальным людям.
