### ISSUE TITLE
Поиск в редакторе скрипт-объектов

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3827]
Ищу слово "Round" в тексте по полному совпадению. Ф-я wg_RoundSum не находится, хотя в ней есть строка:

wg_RoundSum = **Round**((Sum + Delta) / RoundValue) \* RoundValue

(можно увидеть на эталоне)

**Comment by alexandra-gsoftware** [comment]
Еще странность. Если делать поиск в имени и искать по имени ф-и отчета, то ничего не найдется - нужен поиск в тексте.

**Comment by iamchrisep** [comment]
Сделано
