### ISSUE TITLE
У компьютера нет сетевой карты

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3829]
При запуске гедымина, при WEB CLIENT Active = 1, кидает ошибку с WinSocket. Дальше работает нормально.

Надо как-то повторить, чтобы определить где именно ошибка происходит в коде.

@stasgm

**Comment by stasgm** [comment]
Проверено, что и с [WEB CLIENT] Active = 0 продолжает кидать ошибку винсокета

**Comment by gsbelarus** [comment]
В окне О Программе что показывает в секции Компьютер? MAC адреса там есть?

**Comment by gsbelarus** [comment]
Возьми с сайта экзешник с отладочной информацией и как выскочит ошибка -- скинь мне стек вызовов.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
