### ISSUE TITLE
исчезают данные из database.ini

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3830]
Работаю с сервером. Сервер отваливается. Из ини-файла исчезает путь к текущей базе и еще несколько путей

**Comment by gsbelarus** [comment]
Ini файл на сервере?

**Comment by alexandra-gsoftware** [comment]
Нет, локально. Причем гедымин каждый раз чуть-чуть подвисает при выборе новой базы на считывании сохраненного пароля. windows 10.

**Comment by gsbelarus** [comment]
Мистика.

**Comment by alexandra-gsoftware** [comment]
Жанна тоже такое видела. Похоже, исчезает новый добавленный путь и пути, находящиеся рядом с ним.

**Comment by alexandra-gsoftware** [comment]
Сегодня повторилось у меня и Жанны. Исчезла половина путей((

**Comment by NikolayUkleyko** [comment]
Спросите, Мишу Васильева - может он подскажет.

**Comment by gsbelarus** [comment]
Databases.ini локально лежит или где-то в сети?

**Comment by alexandra-gsoftware** [comment]
локально

**Comment by alexandra-gsoftware** [comment]
а к имени компа пароли привязаны? Позавчера были проблемы с сетью, переименовали комп, обновили винду. В database.ini исчезли все пароли....

**Comment by gsbelarus** [comment]
конечно привязаны. иначе похитил .ini файл и все пароли у тебя в руках. так
сделано специально. на другом
компе пароли уже не расшифруются.

2017-02-23 16:55 GMT+03:00 alexandra-gsoftware <notifications@github.com>:

**Comment by alexandra-gsoftware** [comment]
тогда отдельное спасибо за переименование компа)))

**Comment by gsbelarus** [comment]
нормальные люди пароли на бумажке пишут и на монитор клеят.

**Comment by alexandra-gsoftware** [comment]
у нормальных людей есть скрипт быстрого считывания паролей))

**Comment by gsbelarus** [comment]
это еще актуально?

**Comment by gsbelarus** [comment]
единственное что я могу представить это несколько одновременно загруженных гедыминов, каждый из которых перезаписывает INI файл другого.

**Comment by YRozmysl** [comment]
я, вроде, с таким не сталкивался

**Comment by yoannawx** [comment]
у меня периодически проблема возникает

**Comment by gsbelarus** [comment]
скорее всего когда одновременно несколько гедыминов загружены, которые с
одним ini работают. тут ничего простого не сделаешь, а сложности городить
не будем.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by gsbelarus** [comment]
Надо в коде глянуть где идет сохранение databse.ini. По идее, должно идти только при выборе другой БД или при изменении списка зарегистрированных БД. Надо перед любой операцией изменения списка поставить его перечитывание с диска и это решит проблему с перезаписью файла, когда несколько гедыминов локально открыты из одной папки.

**Comment by Polfath** [comment]
Взял в работу

**Comment by Polfath** [comment]
В Tgd_DatabasesList.ShowViewForm добавил загрузку из database.ini перед отображением списка БД

**Comment by gsbelarus** [comment]
Надо протестировать сделанные изменения.

У нас возможна загрузка, когда считывается только из ini файла список баз и активная база, а возможно когда база прописана в командной строке.

Надо протестировать:

1. при работе с .ini файлом: добавление, изменение, удаление баз.
2. при работе из командной строки. чтобы возникало окно ввода логина и пароля, но сама база не попадала в список, в ini файл.

Проверить ситуацию, когда два гедымина параллельно к одному ini файлу подключены и что происходит при его одновременном изменении.

@NikolayUkleyko протестируешь? если все ок, то можно закрывать.

**Comment by NikolayUkleyko** [comment]
Проверено:
1. при работе с .ini файлом: добавление, изменение, удаление баз.
2. Два гедымина параллельно к одному ini файлу подключены и что происходит при его одновременном изменении.

Моделирование с командной строкой не выполнялось.

В результате.
Данные сохраняются в .ini файле корректно.
В форме списке баз данных информация верная.
