### ISSUE TITLE
Бухгалтерия. Закрытие месяца. Переход на новый месяц. Аналитики присутствуют в AC_ACCOUNT, но не в AC_ENTRY и AC_ENTRY_BALANCE

### ISSUE THREAD

**Issue by iamchrisep** [GoldenSoftwareLtd/gedemin#3831]
После установки нескольких ПИ (Показатели, Книга покупок и пр.) на чистую БД при попытке перехода на новый месяц возникает ошибка SQL-запроса в момент расчета бухгалтерских остатков в связи с присутствием некоторых аналитик в таблице AC_ACCOUNT и их же отсутсвием в таблицах AC_ENTRY и AC_ENTRY_BALANCE.

**Comment by alexandra-gsoftware** [comment]
Все понятно.
Аналитики в счетах лежат вместе в ПИ "Аналитики в счетах". Поля в AC_ENTRY входят каждое в свое ПИ, а поля в AC_ENTRY_BALANCE создаются автоматически при добавлении поей в AC_ENTRY (но весь этот механизм входит в мат. склад!). Допустим, я перенесу создание полей в AC_ENTRY_BALANCE в общие данные, но что делать с AC_ENTRY?

@MIchaelShoihet , что скажете?

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
