### ISSUE TITLE
Бухгалтерия. Главная книга. Переход по дате в Журнал-ордер и Карту счета

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3832]
**Исследователь > Бухгалтерия > Главная книга, Журнал-ордер, Карта счета**.

Сфомировали Главную книгу за **конкретный день** > выполняем переход в Журнал-ордер и/или карту счета. При этом переход в такие формы будет **не за день**, указанный в параметрах Главной книги, а **за целый месяц**. Это усложняет анализ и исправление данных.

@MIchaelShoihet , скажите, пожалуйста, так задумано или нет ?

**Comment by MIchaelShoihet** [comment]
Нет думаю так не было задумано. Надо исправить

**Comment by iamchrisep** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Переход по дате работает корректно.

Необходимо предусмотреть **синхронизацию параметров** (**Расшифровка по дебету**, **Расшифровка по кредиту**) при переходе из Главной книги в Журнал-ордер.

**Comment by NikolayUkleyko** [comment]
@iamchrisep , пожалуйста, посмотри вопрос по **синхронизации параметров**.

**Comment by NikolayUkleyko** [comment]
Доработок не выявлено.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@iamchrisep  , спасибо ! :trophy:
