### ISSUE TITLE
Бухгалтерия. Оборотная ведомость. Форматирование в итоговых строках

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3833]
**_Исследователь / Бухгалтерия / Оборотная ведомость_**.

Пожалуйста, предусмотрите форматирование (разряды) в итоговых строк для всех показателей (валюта, эквивалент). Сейчас с форматированием выводятся только итоги по сумма в национальной валюте.

**Comment by gsbelarus** [comment]
Форматирование итого берется из форматирования колонки соответствующей.

**Comment by NikolayUkleyko** [comment]
> Форматирование итого берется из форматирования колонки соответствующей.

Само собой разумеется.

Не все так просто. В бухгалтерских формах настройка форматирования не помогает. Впечатление, что все зашито в gedemin.exe. Пожалуйста, несколько скриншотов:

![1](https://cloud.githubusercontent.com/assets/11497453/15607262/38660f7c-241a-11e6-9dfd-b99e600cec51.png)

![2](https://cloud.githubusercontent.com/assets/11497453/15607265/3f450992-241a-11e6-80c9-d8ba70d5ec0e.png)

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !
