### ISSUE TITLE
Бухгалтерия. Очень длительный переход на проводку из документа

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3834]
При работе с большими базами данных кнопка **Переход на проводку** бесполезна, так как переход на проводку в Журнал хозяйственных операций затягивается на очень длительно время и появляется окно с таймером. Это изрядно напрягает и нас и пользователей.

@gsbelarus , скажите, пожалуйста, можно ли усовершенствовать данный функционал ?

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , скажите, пожалуйста, что Вы думаете по данной теме ?

**Comment by MIchaelShoihet** [comment]
Можно сделать, наверное. Я посмотрю

**Comment by ShlTanya** [comment]
NikolayUkleyko можно ли уточнить.. данная ситуация появляется Всегда при переходе на проводку (в больших базах) или только при первом вызове данной функции.
И можно ли как то получить копию такой базы.. На имеющейся у меня проблемы не увидела.

**Comment by NikolayUkleyko** [comment]
Привет, @ShlTanya !

>данная ситуация появляется Всегда при переходе на проводку (в больших базах) или только при первом вызове данной функции.

Всегда.

>И можно ли как то получить копию такой базы.. На имеющейся у меня проблемы не увидела.

Смотреть это лучше на больших БД.
Размер которых зашкаливает за 100 Гб.
На офис и скинуть на внешний HDD.

**Comment by igor6003** [comment]
Наблюдал такое при включенном фильтре в позиции Журнала хоз. операций.
Был включен фильтр “Отобразить записи за период”. При этом переход на проводку по документу длился больше минуты. Если же фильтр отключить, то переход происходит быстро.

**Comment by gsbelarus** [comment]
> 1. Проблема возникает только если к Журналу применен любой фильтр.
> 2. С фильтром в Журнале при вызове проводок из документов сначала обрабатывается запрос для фильтра. Затем только в запрос передаются параметры по документу и запрос выполняется заново.
> 
> Результат запроса возвращает проводки только по данному документу (Z.DOCUMENTKEY = :dk) (с учетом фильтра) и необходимости выбора периода для проводок и Locate там нет.
> 
> Почему я выбрала способ отключить фильтр в данном месте:
> 1. Не всегда отбор по фильтру, установленный пользователем, содержит проводки, которые необходимо увидеть. В таком случае пользователь их не увидит и ему надо еще догадаться или отменить фильтр, или его изменить.
> 
> 2. С отключенным фильтром пользователь всегда увидит свои данные, при этом в Журнале хоз. операций (который вызывается из Исследователя) останется настройка на его фильтр.
> 
> 
> Например: Я создала фильтр в Журнале За текущий день
> можно отследить даже профайлером, что изначально выполнился запрос (причем не 1 раз) с

> 
> 
> WHERE
> Z.COMPANYKEY + 0 IN ( 147061132 )
> AND
> T.LB >= :LB
> AND
> T.RB <= :RB
> AND (
> (DOC.DOCUMENTDATE >= '26.01.2017' AND
> DOC.DOCUMENTDATE < '27.01.2017'))
> 
> и только потом 
> 
> WHERE
> Z.COMPANYKEY + 0 IN ( 147061132 )
> AND
> T.LB >= :LB
> AND
> T.RB <= :RB
> AND
> Z.DOCUMENTKEY = :dk
> AND (
> (DOC.DOCUMENTDATE >= '26.01.2017' AND
> DOC.DOCUMENTDATE < '27.01.2017'))

Тогда ясно. Проблема, что фильтры неправильно реализованы. Они подключаются в цепочке операций конструктора и влезть туда возможно, не придумав какой-то костыль. По хорошому, они должны активироваться позже формы и через посылку сообщения. Но... что есть то есть. Вариант с новым конструктором плох тем, что любой другой код про этот конструктор ничего не знает....

Я переделал через глобальный флаг. По степени плохости это тоже самое, или даже хуже, но требует меньше кода ))

Посмотрим, поможет ли.

**Comment by ShlTanya** [comment]
Единственное, у Вас после открытия проводок из документа при вызове  Журнала из Исследователя не применяется последний фильтр..

**Comment by gsbelarus** [comment]
а так?

**Comment by ShlTanya** [comment]
А так хорошо

**Comment by NikolayUkleyko** [comment]
Проверено.
В первом приближении работает корректно.
Тему, пока, не закрываем.
Поживем - увидим.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
