### ISSUE TITLE
Деноминация - временный период. Утилита деноминации.

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3835]
Во всех пи (например, при печати ТТН) временный период определяется так:
Если дата меньше 01.07.2016 - НЕ временный период
Если дата НЕ меньше 01.07.2016, временный период определяется по галочке в хранилище  "Была деноминация" **GLOBAL\Options\dnmn**.
Временный период длится, если галочки нет вообще, либо она ложь.
Значит, **утилита в конце должна обновлять\создавать эту галочку, и присваивать ей значение истина**
Весь механизм описан здесь. https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/137

**Comment by alexandra-gsoftware** [comment]
А сделайте чтобы в скриптах формирования чистого эталона эта галочка сразу была true - для новых клиентов

**Comment by gsbelarus** [comment]
Так просто добавьте эту галку в ПИ.

**Comment by alexandra-gsoftware** [comment]
Она и так там есть. Но нужно разделять обновление для старых клиентов и для новых. У старых она должна быть фолс по умолчанию, у новых - тру. Поэтому я удалю ее из пи, а вы добавьте в чистый эталон

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
