### ISSUE TITLE
Утилита деноминации. Ошибка из-за разницы в полях AC_ACCOUNT и AC_ENTRY

### ISSUE THREAD

**Issue by iamchrisep** [GoldenSoftwareLtd/gedemin#3836]
При установленной галке "Сохранить сальдо по бухгалтерским счетам до деноминации на 30.06" на моменте расчета сальдо возникает ошибка вследствие разницы между структурами таблиц AC_ACCOUNT и AC_ENTRY. Возникает это, по всей видимости, из-за криво установленных ПИ. Что-то похожее было в этой ситуации: 
https://github.com/GoldenSoftwareLtd/gedemin/issues/3831

**Comment by gsbelarus** [comment]
Это относится к gedemin-apps, а не к gedemin. И потом, почему криво? Просто так сделаны ПИ.

**Comment by gsbelarus** [comment]
Четко пишите:

1) взят эталон с сайта
2) установлены такие-то ПИ (какие???)
3) после этого несоответствие полей аналитик в таких-то таблицах.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by NikolayUkleyko** [comment]
В ПИ есть отчет для отображения несоответствий полей аналитик в таблицах.
@gsbelarus , пожалуйста, закройте тему.
