### ISSUE TITLE
Счет готовой продукции, проводки по которому не надо деноминировать

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3837]
ALIAS = ГП
RUID = 147170231_1234867257

Могилевский МК
# ID = 510549335

Витебский МК
# ID = 463189879

Бройлеры
# ID = 204251685

Березовский МКК
# ID = 412249115

Белкалий
ID = 148253567

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, уточните в чем же суть ?

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
