### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Чрезвычайно длительное открывание при активном фильтре

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3838]
**_Исследователь > Бухгалтерия > Журнал хоз. операций**_.

При этом **Параметры > Опции > Всегда запрашивать параметры для текущего фильтра и предупреждать о фильтрации данных**. Это **обязательное** условие для того, чтобы программа при подключении к БД не задавала вопросов о параметрах уже выбранных фильтров.

Из Исследователя вызываем Журнал хоз. операций с **активным фильтром**. Процесс открывания по времени весьма длительный. Переход на другую ветку (типовую хоз. операцию) затягивается на длительное время. Порой и окно таймера отображается. Порой можно и не дождаться результата. Возникают вопросы у пользователей и у внедренцев.

На практике на больших БД (более 100 Гб) работа в Журнале хоз. операций превращается в **неработу**.

Если, наша программа позиционируется как **одна из самых самых** для крупных и не только предприятий, то почему бы не предусмотреть более грамотное функционирование Журнала хоз. операций.

Опять-таки, если в БД учет ведется около 10 и более лет, то напрашивается вопрос, а зачем тогда ж хранить старые ненужные проводки, тормозящие работу Журнала хоз. операций ?

**Comment by alexandra-gsoftware** [comment]
а что за фильтр?

**Comment by MIchaelShoihet** [comment]
Журнал хозяйственных операций - только для экстренных случаев. Не надо приучать пользователей в нем работать. И потом если стоит нормальный фильтр за день - максимум за неделю даже на ВМК и Бройлерах журнал работает нормально. Еще раз - давайте решать вопросы по которым бухгалтер идет и делает ручные проводки, которые не возможно контролировать... которые потом вылазят , потом в других подсистемах боком. Если же все-таки надо работать с журналом, приучайте работать с фильтром за день. Даже на самых больших базах он будет быстро выводить информацию. Наша программа позиционируется как раз, как программа которая работает от документов, а не от журнала хозяйственных операций.

**Comment by NikolayUkleyko** [comment]
Спасибо !
