### ISSUE TITLE
Деноминация кассовых ордеров

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3841]
Может деноминировать их в утилите отдельным запросом? Только записи с ИД валюты белорусского рубля?

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by alexandra-gsoftware** [comment]
неактуально.
