### ISSUE TITLE
Out of memory на новейшем gedemin.exe

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3844]
С Гомельобоев жалуются на следующие часто возникающие ошибки:

![image](https://cloud.githubusercontent.com/assets/11497453/16522121/5aba1474-3fa4-11e6-980e-e683e319941f.png)

![image](https://cloud.githubusercontent.com/assets/11497453/16522126/62a6ff62-3fa4-11e6-99e3-47ea52cffc4c.png)

Подобные ошибки возникают при различных режимах работы: работа с документами, формирование отчетов и форм и т. д. и т. п.

Имя файла            = gedemin.exe
Дата файла           = 30.06.2016
Версия файла         = 2.9.2.8729

**Comment by gsbelarus** [comment]
Надо ставить экзе с отладочной информацией и скинуть сюда стек вызовов когда выскочит ошибка.

**Comment by NikolayUkleyko** [comment]
Есть и еще одна давно замеченная ошибка и на Береза МКК

![image](https://cloud.githubusercontent.com/assets/11497453/16522471/a7b92100-3fa6-11e6-97ad-e2b869047a50.png)

Данная ошибка мешает переподключиться к БД при установке ПИ, настроек. Приходится снимать процесс и заново подключаться к БД. При этом обновления становятся полностью.

**Comment by alexandra-gsoftware** [comment]
последняя и у меня бывает (после этого умирает control center)

**Comment by gsbelarus** [comment]
на новейшем экзе не должно быть. но надо посмотреть.

**Comment by ilonaand** [comment]
Последняя ошибка на новейшем экзе на Могилеве, но не на всех компьютерах. Не дает подключиться к базе при удаленном подключении - склад-магазин не может работать, мы не можем подключиться к базе. Надо очень срочно посмотреть

**Comment by YRozmysl** [comment]
На exe (Дата файла = 04.07.2016 Версия файла         = 2.9.2.8739) к локальной базе ммк подключается, возможно есть смысл заменить его.

**Comment by YRozmysl** [comment]
На могилеве стоит exe от 01.07.2016

**Comment by ilonaand** [comment]
Да, вчера скачивал и ставил. Там работает при локальном подключении похоже у всех, во всякос случае пока никто не жаловался, и на удаленке по одному ай-пи. По остальным ай-пи не работает, начинает грузить гедемин, выкидывает эту ошибку и вылетает. Иногда кидает ошибку что file contains no version information. Может, и есть смысл заменить на сегодняшний

**Comment by alexandra-gsoftware** [comment]
Вот опять Connection Refused, и Control Center молча отваливается.

**Comment by NikolayUkleyko** [comment]
На **Береза МКК** по-прежнему такая ошибка:

![image](https://cloud.githubusercontent.com/assets/11497453/16522471/a7b92100-3fa6-11e6-97ad-e2b869047a50.png)

Смена gedemin.exe ничего не меняет.

**Comment by NikolayUkleyko** [comment]
Я бы не торопился закрывать данную тему, так как на Береза МКК (gedemin.exe / Дата файла = 27.01.2017 / Версия файла = 2.9.3.8971), Витебск МК и на других предприятиях с актуальным gedemin.exe встречается такое сообщение мешающее работе.

**Comment by gsbelarus** [comment]
Уже решено. Надо обновить экзешник сегодняшним послеобеденным.
