### ISSUE TITLE
Неправильные счета в БД

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3845]
Я нахожу на базах некорректные счета. например, есть счет 18, субсчет 18.01. И 18.01.02, но последний помечен не как субсчет, а как счет и parent у него напрямую 18, а не 18.01.

Стоит ли апгрейдом поправить такие счета? Т.е. указать правильно их тип и правильно присвоить parent?

Если не сделать этого, то возможны ошибки при загрузке ПИ, как, например у найттрампа.

Какие тут могут бытьподводные камни?

Запрос для поиска таких счетов:

```

SELECT
  p.id, p.alias, a.parent, a.alias, a.accounttype
FROM
  ac_account p JOIN ac_account a
    ON a.alias LIKE p.alias || '._%'
      AND NOT a.alias LIKE p.alias || '.%._%'
  JOIN ac_account a_root
    ON a_root.lb < a.lb AND a_root.rb >= a.rb
      AND a_root.parent IS NULL
  JOIN ac_account p_root
    ON p_root.lb < p.lb AND p_root.rb >= p.rb
      AND p_root.parent IS NULL
WHERE
  (a.ID <> p.id)
  AND
  (a_root.id = p_root.id)
  AND
  (
    a.parent <> p.id
    OR
    a.accounttype <> 'S'
   )
```

@MIchaelShoihet @alexandra-gsoftware

**Comment by alexandra-gsoftware** [comment]
мне кажется, вы это уже правили, но этот апдейт затерялся в веках. Я думаю, надо править, да

**Comment by NikolayUkleyko** [comment]
Я бы лихо автоматом не менял входимость счетов. Лучше пройти и поправить требуемые счета через **_Свойства > Данные: Parent, Accountype**_.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
