### ISSUE TITLE
не работает sumfullrubstr в шаблонах на старом fr... 

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3849]
... а может, и в новом fr тоже.
Проблема появляется в ехе, который сейчас выложен на сайте, для сумм с дробной частью, где дробная часть больше 0.5
Например,
S = 49 230 576.6
SUMFULLRUBSTR(ROUND( S \* 100) / 100) ->
сорок девять миллионов двести тридцать тысяч пятьсот семьдесят **семь целых** шесть **десятых** рублей шестьдесят копеек 

SUMFULLRUBSTR(ROUND( S \* 100, 2) / 100) ->
сорок девять миллионов двести тридцать тысяч пятьсот семьдесят **семь** рублей шестьдесят копеек

**Comment by alexandra-gsoftware** [comment]
Все оказалось куда сложнее. Создаем отчет, набор данных с одним полем и одной записью, значение S = 49 230 576.6
1. Выводим SUMFULLRUBSTR(S), получаем вот такое:
   ![1](https://cloud.githubusercontent.com/assets/11487200/16666241/6e539b0a-448f-11e6-96b2-799b3af1b550.png)
   Как видите, рублевая часть округлена (там 7 вместо 6), но в остальном все хорошо.
2. Строим отчет еще один раз - ничего не поменялось.
3. Добавляем в отчет SUMSTR(S, 3). Получаем 
   ![2](https://cloud.githubusercontent.com/assets/11487200/16666286/a7d88b88-448f-11e6-9b99-76655f1ffeb6.png)
   Значение SUMFULLRUBSTR не поменялось.
4. Ничего не меняем, строим отчет еще один раз. Получаем
   ![3](https://cloud.githubusercontent.com/assets/11487200/16666333/d53f0a16-448f-11e6-8e2e-e3f0aa638e83.png)

Всё. Теперь SUMFULLRUBSTR будет выводить слова целых и десятых, пока не переподключимся к базе.

**Comment by gsbelarus** [comment]
Первым делом проверьте настройки валюты в справочнике валют. И перегрузите экзешник.

Если трогаете отчет -- используйте новую функцию. Документация в вики.

**Comment by gsbelarus** [comment]
Не используйте старые функции. Вместо них есть одна новая на все случаи.

**Comment by gsbelarus** [comment]
Gd_convert.getnumeral -- это функция которая делает преобразование в строку.

**Comment by alexandra-gsoftware** [comment]
все старые отчеты, использующие эти 2 функции, показывают неверные данные на новом ехе. На старом все ок.

**Comment by gsbelarus** [comment]
И пожалуйста, используйте новые функции. Они создавались, чтобы избавиться от этого бреда 
SUMFULLRUBSTR(ROUND( S \* 100) / 100)

**Comment by gsbelarus** [comment]
Подскажите кристине, что в gd_convert в функциях getfullrubstr и проч надо закоментировать код и подставить вызов getcurrnumeral с соответствующей маской.

Потом надо на индию перенести эти изм и м.ю. знает как на сайте обновить экзешник.

**Comment by gsbelarus** [comment]
Док по getcurrnumeral в вики

**Comment by gsbelarus** [comment]
Или просто @Michaelshoihet попросите.

**Comment by alexandra-gsoftware** [comment]
и сделайте кто-нибудь плз ф-ю сохранения шаблона старого фр в формате xml в поток, если поиска принципиально не будет

**Comment by gsbelarus** [comment]
В старом фр по мойму нет сохр шаблона в xml

**Comment by alexandra-gsoftware** [comment]
есть. Если кто-то сделает ф-ю выгрузки в поток в этом формате, то я сделаю поиск.
![4](https://cloud.githubusercontent.com/assets/11487200/16687927/1a61935e-4524-11e6-990a-607b0f55e92b.png)
