### ISSUE TITLE
Ошибка при попытке сменить тип платежа PositiveCheck

### ISSUE THREAD

**Issue by testkkc** [GoldenSoftwareLtd/gedemin#3850]
Ошибка при попытке сменить тип платежа PositiveCheck
![pay](https://cloud.githubusercontent.com/assets/20344214/16666088/cc851b78-448e-11e6-9583-bdd695d6d297.jpg)

**Comment by stasgm** [comment]
Исправлено. Будет в следующем релизе или качать из гитхаба
