### ISSUE TITLE
Выбор аналитики в ЖХО

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#3854]
Лукап для выбора договора - обрабатывается как обычный документ, хотя на поле настроено визуальное отображение привязывающего его именно  к документу договор. В старых exe это ограничение работало, сейчас нет. Надо посмотреть. Срочно.

**Comment by NikolayUkleyko** [comment]
Я так понимаю, что речь не идет о том, чтобы в Журнале хоз. операций в выпадающем списке отображались актуальные договора строго по клиенту ?

**Comment by MIchaelShoihet** [comment]
Нет. Об этом речь не идет, в журнале хоз операций это не осуществимо. Речь идет о том, что в поле договора отображались только договора, а не все документы системы.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , ок. Но у нас есть волшебная комбинация **Ctrl+D**.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@MIchaelShoihet , спасибо !

Пожалуйста, закройте данную тему.
