### ISSUE TITLE
Пароль на кнопку закрыть

### ISSUE THREAD

**Issue by testkkc** [GoldenSoftwareLtd/gedemin#3855]
Пароль на кнопку закрыть (можно закрыть программу, случайно нажав на кнопку, м.б. есть возможность установить проверку паролем действия - не нашел).

Другие вопросы перенесены сюда:

https://github.com/gsbelarus/check-and-cash/issues

**Comment by gsbelarus** [comment]
Зато как этот вопрос будет раздражать 99% остальных пользователей.

**Comment by testkkc** [comment]
Пользователь утверждает, что часто случайно нажимает на эту кнопку, в результате программа закрывается. Если она установлена как оболочка, приходится каждый раз перезагружать комп. Если не пароль, то можно хотя бы переспрашивать - да/нет.

**Comment by stasgm** [comment]
Вот так настраивается запрос пароля
![image](https://cloud.githubusercontent.com/assets/8355925/16957890/f6386356-4de6-11e6-9fab-778010110213.png)
Я добавлю ещё вопрос к операции"Закрыть программу?"
