### ISSUE TITLE
Предопределенные фильтры. Предусмотреть обработку регулярных выражений

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3856]
Пожалуйста, в предопределенных фильтрах предусмотрите обработку регулярных выражений.

![1](https://cloud.githubusercontent.com/assets/11497453/17021938/e5d2d500-4f53-11e6-8fa3-4dcb21e0cf8c.png)

**Comment by iamchrisep** [comment]
В запросе с параметром для поиска вхождения используется оператор CONTAINING, а не LIKE, поэтому символы, используемые в регулярных выражениях, расцениваются как подстрока. Использование регулярных выражений с этим оператором невозможно. Править это не имеет смысла. Например, непонятно, что пользователь хотел найти, введя такой параметр: 50% - то ли значения, начинающееся на 50, то ли значения, содержащие 50%. С нижним подчеркиванием то же самое. Лучше не усложнять, а для фильтрации с регулярными выражениями можно использовать другие способы (формула -> ввести условия, например).

**Comment by NikolayUkleyko** [comment]
Взвесив все, оставили как есть.
Спасибо !
