### ISSUE TITLE
Некорректная работа банковской выписки с курсом валюты

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#3857]
Сейчас курс российского рубля 6 знаков после запятой. Надо что бы выписка это поддерживала. Проверить пересчет из валюты в рубли. Округлять рубли до кол-во знаков указанных в настройках белорусского рубля. Вообще убрать расчет валюты от рублей.

**Comment by gsbelarus** [comment]
Поскольку это в экзешнике сделано, то после проверки и исправления надо написать тест.

**Comment by igor6003** [comment]
Может лучше убрать из экзешника и пересчет из валюты в рубли и вынести это в
DoFieldChange, тем более что теперь есть функция GS.MulDiv для правильного округления.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by alexandra-gsoftware** [comment]
вроде сейчас все правильно?

**Comment by NikolayUkleyko** [comment]
Актуальна ли данная тема ?
