### ISSUE TITLE
Журнал хоз операций

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#3858]
Курс валют подставляется только 4 знака - надо 6. При установленной галке округлять, округлять до столько знаков, сколько установлено в настройках бел рубля в справочнике валют. Пересчеты из рублей в валюту и обратно - проверить.

**Comment by NikolayUkleyko** [comment]
Если, в диалоге ЖХО зайти в дизайнер и исправить DecDigits на 6, то всё ОК. Cтоит только переоткрыть диалог и оно опять 4.

**Comment by MIchaelShoihet** [comment]
Это уже исправлено еще в августовском exe (где-то от 20 числа). И Ctrl_E  в ЖХО не имеет смысла нажимать, там все контролы не хранятся, а создаются.

**Comment by NikolayUkleyko** [comment]
Проверил.
Нельзя в поле **Курс** ввести больше 4-х знаков после запятой.

**Comment by MIchaelShoihet** [comment]
В ручную может быть, это наверное пропустил. Но автоматически все подставляется.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@MIchaelShoihet , спасибо !

Пожалуйста, закройте данную тему.
