### ISSUE TITLE
Функция SUMCURRSTR2. Отображение разделителя

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3859]
Сейчас функция SUMCURRSTR2 работает следующим образом.
Прописали: [SUMCURRSTR2(200010, [NEWPAYMENT."USR$BN_SUMNCU"], true)].
Получили: 
![2](https://cloud.githubusercontent.com/assets/11497453/17302144/81a23caa-5823-11e6-8a2f-b96d854ebd93.png)

На практике необходимо в отчетах получать **_сумму рублей в текстовой интерпретации, потом разделитель (точка или запятая), потом сумма копеек в цифровой интерпретации**_.

Пожалуйста, доработайте существующую функцию **SUMCURRSTR2**, добавив еще один параметр **Разделитель**. Если, он пустой, то оставляем как есть - без разделителя. В противном случае, указываем **.** (точка) или **,** (запятая):
![1](https://cloud.githubusercontent.com/assets/11497453/17302145/81e97d04-5823-11e6-9528-67ddda4a19f0.png)

Если, нет возможности доработать существующую функцию **SUMCURRSTR2** (не нарушив работоспособность **_существующих**_ отчетов с использованием такой функции), тогда создайте новую функцию, учитывающую вышеприведенное.

**Это крайне важно**.

**Comment by gsbelarus** [comment]
Эту функции дорабатывать не будем. Есть GetCurrNumeral она позволяет выполнить вышеуказанную задачу.
