### ISSUE TITLE
Как хранить курсы валют

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3860]
Есть такая идея, как остаться в пределах типа **Currency**. Что, если все курсы в базе данных (в таблице курсов, в полях в документов и т.п.) мы будем указывать не за 1, а за 10 000 (можно и за 1000 или за 100, но 10 000 чисто визуально возвращает нас к цифрам до деноминации).

Т.е. курс бел рублей за доллар будет в базе храниться как 20 000, а не 2. 

`20 000 BYN = 10 000 USD.
`

Курс долларов за бел рубль будет храниться как 5 000, а не 0.5. 

`5 000 USD = 10 000 BYN.
`

Дальше:
1. На уровне диалоговых окон справочника валют можно выполнять преобразования. Т.е. человек будет вводить как за 1, но в базу будет сохраняться как за 10 000.
2. В таблицу курсов валют можно добавить вычисляемое поле для отображения курса за 1 для вывода на экран в гриде. Существующее поле теперь будет хранить курс за 10 000.
3. Весь код внутри платформы, который выполняет пересчеты от курса, мы правим, чтобы он учитывал масштаб.
4. Делаем на уровне платформы функцию, которая выполняет на заданную дату пересчет из одной валюты в другую.
5. Эту функцию используем внутри скрипт-функции, которую сейчас все используют  пространствах имен для получения курса валюты.
6. Остальной код ПИ, который напрямую обращается к таблице с курсами, правим.

@MIchaelShoihet @alexandra-gsoftware

**Comment by alexandra-gsoftware** [comment]
у нас много полей, хранящих курс. Собственно, со станlдартными курсами из gd_currate код уже поправлен. Как быть с остальными полями?

**Comment by gsbelarus** [comment]
Какой код поправлен? Перешли с точного currency на double? Где число это
степень e? И дальше что? При любом делении будут лезть малые величины,
малые расхождения.

Тут суть в том, чтобы сохранить тип currency.

**Comment by gsbelarus** [comment]
У нас использовался double в секрете анжелики. И это был ад адов. Для фин величин ТОЛЬКО currency (в БД numeric) иначе вы концов в программе не сведете никогда. Итак нареканий к нам выше крыши, а когда отчеты не будут идти с проводками, а проводки с документами....

**Comment by alexandra-gsoftware** [comment]
variant, а не double +проверки на нулл

**Comment by gsbelarus** [comment]
Variant внутри содержит double с теми же последствиями. И огребете вы с
такой заменой в будущем по самые помидоры.

**Comment by alexandra-gsoftware** [comment]
откуда такие сведения?

**Comment by gsbelarus** [comment]
Какие?

**Comment by gsbelarus** [comment]
For example, if you store values with decimal fractions in a Variant
variable, Visual Basic always uses the Double internal representation. If
you know that your application does not need the high accuracy (and slower
speed) that a Double value supplies, you can speed your calculations by
converting the values to Single, or even to Currency:

https://msdn.microsoft.com/en-us/library/aa261347(v=vs.60).aspx

**Comment by gsbelarus** [comment]
Value = Variant = Double

PS: проблем будет меньше, чем в свое время с Секретом, так как в БД хранится как нумерик. Но, они будут (

**Comment by alexandra-gsoftware** [comment]
c 6 знаками после запятой не вылазят проблемы с дабл. А вот если 10 знаков - то да.

**Comment by igor6003** [comment]
Можно если надо преобразовать.
Sometimes you want to use a specific representation for a number. For example, you might want a Variant variable to store a numeric value as Currency to avoid round-off errors in later calculations. Visual Basic provides several conversion functions that you can use to convert values into a specific type (see "Converting Data Types" earlier in this chapter). To convert a value to Currency, for example, you use the CCur function:
PayPerWeek = CCur(hours * hourlyPay)

**Comment by gsbelarus** [comment]
Да дело все в том, что CCur дает **ЧЕТЫРЕ** знака после запятой, которых нам не хватает.

**Comment by gsbelarus** [comment]
Я хочу вас всех дико расстроить. Сколько будет сто раз просумировать 0.1? Должно быть 10, правильно?

Теперь выполните вот этот элементарный код:

```
Option Explicit
Sub Macros147002861_625181804

  Dim Sum, I
  Sum = 0
  For I = 1 To 100
    Sum = Sum + 0.1
  Next

  MsgBox Sum
End Sub
```

Получили результат? Удивились?

Вот это тот ад который начнется в самом скором времени, если мы не вернем
все назад к типу Currency и не придумаем что делать с малыми величинами курсов.

**Comment by gsbelarus** [comment]
Приведенный выше пример можно вылечить только приведением к **Currency**:

```
Sub Macros147002861_625181804

  Dim Sum, I
  Sum = 0
  For I = 1 To 100
    Sum = CCur(Sum) + 0.1
  Next

  MsgBox Sum
End Sub
```

Теперь получим правильный результат.

**Comment by gsbelarus** [comment]
Я бы сейчас вернул назад использование **AsCurrency** где менялось на **AsVariant** или **Value**.

И подумал бы как решить проблему. Иначе мы в такие дебри залезем из которых будем долго-долго выбираться.

Тип **DOUBLE** никаким концом не предназначен для выполнения финансовых и складских расчетов. 

https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by igor6003** [comment]
Option Explicit
Sub Macros147026754_1784588601()
Dim Sum, S, I
  Sum = 0.000001
  S = Ccur(Sum * 100)
  For I = 1 To 1000
    S = S + 0.1
  Next

  MsgBox "Sum = " & S * 0.01
End Sub

**Comment by kovli** [comment]
А может не изобретать велосипед? Посмотрите как установлены курсы на сайте НБРБ. Там, помимо курса, указан коэффициент - за сколько. Сам курс указан с 4-мя знаками после запятой. То, что нам и нужно. Полностью вписываемся в Currency.  А коэффициент (множитель) - указывает за какое количество валюты установлен курс. За 1, 10, 100 и т.д.  Давайте и мы добавим в наш справочник валют этот коэффициент-множитель. И сделаем на уровне платформы функцию, которая будет переводить сумму из одной валюты на заданную дату в сумму в другой валюте. Ведь сами курсы, как таковые, нам в функционале не нужны. Только как справочно где-то отразить. А нужно именно результат конвертации суммы из одной валюты в сумму в другой валюте. Например, заплатили бел.рубли, нужно их пересчитать в USD. Или наоборот. Эта функция, назовем ее, например, ExchangeCurrency, будет иметь 4 параметра: OnDate - дата конвертации, CurrKeyIn - код (ID) исходной валюты (из чего конвертируем), SumCurrIn - сумма в исходной валюте (что конвертируем), CurrKeyOut - код (ID) конечной валюты (во что конвертируем), SumCurrOut - сумма в конечной валюте (результат конвертации). Возвращает эта функция результат - True или False. Если на заданную дату был найден курс исходной валюты, то результат - True, иначе - False. Чтобы знать, был ли точно определен курс конвертации и не нужно ли сообщить пользователю, что не введены актуальные курсы валют. Так, я думаю, мы навсегда закроем проблему с курсами.

**Comment by kovli** [comment]
В дополнение к предыдущему посту. С коэффициентом  (множителем) и курсы валют с сайте загружать легче. Ничего не нужно пересчитывать. Закгрузил коэффициент и курс на дату. И все.

**Comment by gsbelarus** [comment]
я бы добавил два поля amount и value. с пересчетом на триггере. если задан коэфф, то value = amount * coeff. Если value не задан, то берем 1. Если задан value и amount, то наоборот -- высчитываем коэф от них.

Это сохранит весь действующий код в неизменном виде.

Новый код уже можно писать исходят из этих двух полей.

и как предлагается выше, можно на уровне платформы ввести функцию получения курса (если такой еще нет у нас).

**Comment by kovli** [comment]
На эту функцию можно возложить и расчет кросс-курса входной валюты относительно выходой (6-й параметр - CrossRate). Например, сегодня 22.12.2016, курс USD = 1,9577. Если я обратился к этой функции и задал в качестве CurrKeyIn (входная валюта) = 200020 (USD), а в качестве выходной валюты CurrKeyOut = 200010 (бел.рубль), то CrossRate д.б. равно 1,9577.  Если CurrKeyIn (входная валюта) = 200050 (RUB - росс.рубль), то CrossRate д.б. равно 3.2040  / 100, т.е. 0,032040.
А насчет 2-х полей я не очень понял.  Amount - это будет множитель (1, 10, 100, т.е. за сколько валюты установлен курс). А Value? Это будет курс за количество (за 1, 10, 100)? Т.е. Coeff остатется, как и сейчас, курс за единицу валюты. Amount - это множитель (за сколько валюты). А Value - это курс за это (Amount) количество валюты. Так надо понимать?

**Comment by gsbelarus** [comment]
Да (про поля). Существующие оставляем и их логику не меняем. Тогда ничего не сломается. А функция (и все остальные желающие) могут начинать работать с новыми полями.

**Comment by kovli** [comment]
После подключения к базе новым EXE (18.01.2017) эти поля (amount и value) не появились. Их нужно добавлять вручную или все-таки это будет сделано централизовано в процессе модификации структуры базы?

**Comment by gsbelarus** [comment]
Это еще в работе. На днях будет.

**Comment by NikolayUkleyko** [comment]
> Например, заплатили бел.рубли, нужно их пересчитать в USD. Или наоборот.

Добавлю, что по этой тематике есть еще документ *Исследователь / Бухгалтерия / Взаиморасчеты / Перевод валют*.
Он позволяет отражать *погашение* задолженности в валюте отличной от валюты *возникновения* задолженности.

**Comment by kovli** [comment]
Попробовал как работает новая функция. System.GetCurrRate. Загрузил курсы валют по 24.01.2017 включительно. USD, EUR.  Взял предложенный пример 
 ' Курс Доллара США в белорусских рублях
 ' MsgBox System.GetCurrRate(Date, 31, -1, 200020, 200010, -1, 1, False, False, False)
Все работает, выдает курс USD на 24.01.2017. Потом решил перевести 10000 BYN в USD.
MsgBox System.GetCurrRate(Date, 31, -1, 200010, 200020, -1, 10000, False, False, False).
Выдала 0. Если обратиться так
MsgBox System.GetCurrRate(Date, 31, -1, 200010, 200020, -1, 10000, False, False, True)
то выдает сообщение, что курс не найден.  Пришлось хорошо подумать, прежде чем догадался, что ей нужен курс BYN. Мы его вообще вводим? Он же всегда = 1. Т.е. теперь нужно искусственно загружать курс BYN, чтобы эта штука работала корректно.  Вещь сделана неплохая, а сходу использовать ее не получится.

**Comment by kovli** [comment]
Скажу больше. Задать курс BYN по отношению к BYN тоже не получится. Триггер на дает.

**Comment by igor6003** [comment]
Ещё обнаружилось, что курс выдаётся не на дату, которая указана как в примере ниже,
а на последнюю в справочнике.

Sub Macros264511180_626854055(OwnerForm, dt)
  Dim D
  D = DateSerial(2017, 01, 21)

  ' Курс Доллара США в белорусских рублях
  MsgBox System.GetCurrRate(dt, 0, -1, 200020, 200010, -1, 1, False, False, False)

  ' тоже самое, валюты задаются кодами
  MsgBox System.GetCurrRate(D, 31, -1, "USD", "BYN", -1, 1, False, False, False)
End Sub
Т.е. вместо курса на 21.01.2017 = 1,9423 выдаётся курс на на 25.01.2017 = 1,931.

**Comment by kovli** [comment]
Верно. И почему-то курс выдает 19310, хотя в справочнике курсов курс стоит 1,931.

**Comment by gsbelarus** [comment]
> Потом решил перевести 10000 BYN в USD.
> MsgBox System.GetCurrRate(Date, 31, -1, 200010, 200020, -1, 10000, False, False, False).
> Выдала 0. Если обратиться так
> MsgBox System.GetCurrRate(Date, 31, -1, 200010, 200020, -1, 10000, False, False, True)
> то выдает сообщение, что курс не найден. 

естественно, у вас в базе нет курса рубля к доллару. Поставьте параметр UseInverted = True и система, если не найден курс из одной валюты в другую, попытается найти обратный курс и разделить единицу на него. Это в документации описано.

**Comment by kovli** [comment]
С параметром UseInverted согласен. Не дочитал. Но, вот нужно перевести 1 рос.рубль в доллар США.
Если обратиться так
MsgBox System.GetCurrRate(Date, 31, -1, 200050, 200020, -1, 1, True, True, True)
то кинет ошибку: не найден курс. Если обратиться вот так (указали валюту кросс-курса)
MsgBox System.GetCurrRate(Date, 31, -1, 200050, 200020, 200010, 1, True, True, True),
то все нормально.
А если надо перевести 1 доллар США в бел.рубль, то предыдущий вызов
MsgBox System.GetCurrRate(Date, 31, -1, 200020, 200010, 200010, 1, True, True, True),
кидает ошибку, нужно обращаться так (не указывать валюту кросс-курса)
MsgBox System.GetCurrRate(Date, 31, -1, 200020, 200010, -1, 1, True, True, True),
Тогда ошибку не кидает. Т.е. если одна из валют (входная или выходная) - BYN, то набор параметров один, а если BYN-а нет, то набор параметров другой. И я это должен отслеживать, прежде чем обратиться к функции?  Проще нельзя сделать? Слишком много телодвижений приходится делать. Приведите один универсальный пример использования этой функции для конвертации любой валюты в любую.

**Comment by gsbelarus** [comment]
Значит так:

1. Я переписал процедуру загрузки курсов. Теперь работает быстро и подхватывает параметр Scale так, как его задает НацБанк.

http://gsbelarus.com/gs/wiki/index.php/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0_%D0%BA%D1%83%D1%80%D1%81%D0%BE%D0%B2_%D0%B2%D0%B0%D0%BB%D1%8E%D1%82_%D1%81_%D1%81%D0%B0%D0%B9%D1%82%D0%B0_%D0%9D%D0%91%D0%A0%D0%91_(XML)

2. Надо обновить экзешник.

3. Проверил. Загрузил все курсы и эксперементирую:

```
  Dim D
  D = DateSerial(2017, 01, 24)
  MsgBox System.GetCurrRate(D, 31, -1, "USD", "BYN", -1, 1, False, False, False)
```` 

Выдает 1.935. Этот курс дал нам нацбанк и мы его поместили в базу данных.

`  MsgBox System.GetCurrRate(D, 31, -1, "BYN", "USD", -1, 10000, False, False, False)`

Получим 0. Естественно, потому что в базе нет такого курса. Там есть курс сколько рублей дают
за доллар, а сколько долларов за рубль -- такого курса нет у нац банка.

Что делать? Один из вариантов -- посчитать обратный курс. Для этого в функции предусмотрен специальный параметр:

```
MsgBox System.GetCurrRate(D, 31, -1, "BYN", "USD", -1, 10000, False, True, False)
                                                                      ^^^
```

0.51786639047125841532884515794925

Это результат расчета обратного курса 1 / 1.931. Округляйте как считаете нужным.

Если же в базе будет отдельно введен курс перевода BYN -> USD, то возьмется он,
а не обратный курс. Обратите внимание, что теперь мы можем на одну дату записать в базу
несколько курсов -- каждый для своего банка.

Теперь попробуем USD -> EUR:

`  MsgBox System.GetCurrRate(D, 31, -1, "USD", "EUR", -1, 1, False, True, False)`

Получаем 0. Естественно, так как национальный банк республики беларусь
не устанавливает курс доллара к евро. Что делать? Один из вариантов -- вести 
в БД курс пересчета. Второй -- посчитать через кросс-курс, через третью валюту,
курсы к которой есть в БД. Например, через белорусский рубль:

`MsgBox System.GetCurrRate(D, 31, -1, "USD", "EUR", "BYN", 1, True, True, False)`

Работает!

Обратите внимание. Сначала USD переведутся в BYN. Такой курс задается нацбанком.
Затем BYN -- в EUR. Такой курс НЕ ЗАДАЕТ нацбанк, он дает нам только ОБРАТНЫЙ курс
из EUR в BYN. Именно по этому я указал UseInverted = True.

**Comment by igor6003** [comment]
>Выдет 1.931. Этот курс дал нам нацбанк и мы его поместили в базу данных.
На 24.01.2017 курс USD = 1,9350

**Comment by gsbelarus** [comment]
> Выдет 1.931. Этот курс дал нам нацбанк и мы его поместили в базу данных.
> На 24.01.2017 курс USD = 1,9350

В данном случае цифры условные. И, пожалуйста, имейте совесть, заключите хотя бы минимальный договор на абонентское сопровождение на вашем предприятии. Так совсем некрасиво получается...
