### ISSUE TITLE
ЭСЧФ. Вопросы

### ISSUE THREAD

**Issue by hjamesgs** [GoldenSoftwareLtd/gedemin#3862]
1. При передаче на сайт xml файла, необходимо начинать нумерацию позиций в документе с  "0". (В самом xml файле нумерация позиций начинается с 1... , а при передаче на сайте уже с №2. Если сохранить с сайта ЭСЧФ, созданную вручную, то там номер позиции начинается с "0")
2. Заполнение реквизитов Грузополучатель Грузоотправитель необходимо только для Накладных. Для Актов выполненных работ эти реквизиты заполнять не надо. Необходимо сделать параметр, по которому "включать/выключать" заполнение.

**Comment by NikolayUkleyko** [comment]
Эрюжев Саша сказал, что данные вопросы решены.
@gsbelarus , пожалуйста, закройте тему.

**Comment by hjamesgs** [comment]
К сожалению портал не работал, не было возможности проверить.
