### ISSUE TITLE
Типовые документы. Ошибка при конвертации

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3863]
При выполнении конвертации типовых документов на экране отображается окно с сообщением
 об ошибке

![image](https://cloud.githubusercontent.com/assets/11497453/17553986/6b6cd6f8-5f11-11e6-83c5-fe593fa4b176.png)

Пожалуйста, подскажите, как устранить проблему ?

**Comment by NikolayUkleyko** [comment]
@alexandra-gsoftware меня направила к @gsbelarus .
Пожалуйста, подскажите, как решить проблему ?
Бухгалтера желают отражать движение ОС за июЛь 2016 г.

**Comment by gsbelarus** [comment]
А что за конвертация?

**Comment by gsbelarus** [comment]
И не надо выкладывать пароли клиентов на всеобщее обозрение в интернет. Это же открытй репозиторий.

**Comment by NikolayUkleyko** [comment]
> А что за конвертация?

gedemin.exe /cdo

> И не надо выкладывать пароли клиентов на всеобщее обозрение в интернет. Это же открытй репозиторий.

Я, Вам, писал письмо с аналогичным содержанием.

**Comment by alexandra-gsoftware** [comment]
и к чему пришли?

**Comment by NikolayUkleyko** [comment]
Пока ничего.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !
