### ISSUE TITLE
Профайлер

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3864]
Неплохо было бы еще видеть в профайлере и subtype  документа в котором вызывается метод

![default](https://cloud.githubusercontent.com/assets/11507129/17597201/80f03d02-5ffd-11e6-864d-78082007b60f.jpg)

**Comment by NikolayUkleyko** [comment]
Еще. Не мешало бы закрывать в профайлере коннект в списке коннектов, если соответствующая база данных была отключена. Получается, что пока не закроешь профайлер список коннектов не очистится. Таким образом, собираются уже ненужные коннекты, что при анализе весьма неудобно.

**Comment by gsbelarus** [comment]
Специально так делалось, чтобы можно было провести анализ/сравнение и после закрытия программы. Введено ограничение на количество вкладок со статистикой и логом -- 10.
