### ISSUE TITLE
POSitive Check - при попытке сделать возврат аванса ( в окне бронирования) в нефискальном режиме ошибка.

### ISSUE THREAD

**Issue by testkkc** [GoldenSoftwareLtd/gedemin#3865]
При попытке сделать возврат аванса ( в окне бронирования) в нефискальном режиме ошибка. - "Не установлен фискальный регистратор, система находится в нефискальном режиме." 
Можно ли сделать некое подобие виртуального фискального регистратора, чтобы все функции (нефискальные) фискального регистратора выполнял чековый принтер и этот режим можно было бы явно установить? Чтобы "Самурай без меча подобен самураю с мечом, но только без меча."

**Comment by gsbelarus** [comment]
Перенесено:

https://github.com/gsbelarus/check-and-cash/issues/33
