### ISSUE TITLE
POSitive Cash - при печати X, Z-отчетов на чеке вместо Кассир - Иван Иванов, печатается Кассир - кассир.

### ISSUE THREAD

**Issue by testkkc** [GoldenSoftwareLtd/gedemin#3866]
POSitive Cash - при печати X, Z-отчетов на чеке вместо Кассир - Иван Иванов, печатается Кассир - кассир. При этом на фискальных чеках оплаты данные кассира печатаются правильно.

**Comment by gsbelarus** [comment]
Этот репозиторий для ЯДРА платформы. Касса и ресторанный фронт в другом репозитории.

Перенесено:

https://github.com/gsbelarus/check-and-cash/issues/32

**Comment by testkkc** [comment]
Извиняюсь, не знал структуры.
