### ISSUE TITLE
Бухгалтерия. Форма 'Карта счета'. Доработка в части корреспондирующих аналитик

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3870]
**Исследователь / Бухгалтерия / Карта счета**.

Для реквизита **Счет** предусмотрен блок **Аналитика** для ввода аналитических признаков.
![1](https://cloud.githubusercontent.com/assets/11497453/18520049/d55427d4-7aae-11e6-98c1-1f196a6f570f.png)

Пожалуйста, предусмотрите аналогичный отдельный блок для ввода аналитических признаков по счету в блоке **Корреспондентский счет**.

**Comment by NikolayUkleyko** [comment]
Тем более, в карте счета **_отображаются_** значения по аналитикам корреспондирующих счетов. Это очень удобно при работе с конфигурациями.

**Comment by NikolayUkleyko** [comment]
На больших БД выявлено следующее.
Если, в блоке **Корреспонденсткий счет** в реквизите **Корр. счета** указать счет, например, 18.03.01, и не вводить счетов в реквизите **Счет**, то  программа начинает "задумываться" и появляется счетчик. При обратной ситуации, программа формирует карту счета значительно быстрее.
Неужели такая разница в скорости формирования формы возникает из-за того, что в блоке **Корреспонденсткий счет** всегда выбран **RadioButton** или **Дебет**, или **Кредит** ?

**Comment by MIchaelShoihet** [comment]
Разница в сути. Счет вверху является основным ограничением, а внизу дополнительным, не влияющим на план построения запроса.

**Comment by NikolayUkleyko** [comment]
Большое спасибо за информацию, @MIchaelShoihet !
