### ISSUE TITLE
Проводки vs вычисляемые поля

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3871]
При создании типовых операций, в случае, если поля вычисляемые, то  генерируется и присваивается ему тип AsInteger, хотя по-идее, наверное, нужно AsCurrency. Или я ошибаюсь?

**Comment by NikolayUkleyko** [comment]
> если поля вычисляемые, то генерируется и присваивается ему тип AsInteger, хотя по-идее, наверное, нужно AsCurrency

Значение из SQL-запроса ?

**Comment by YRozmysl** [comment]
Поле имеет домен, в котором в свою очередь  и вычисляется выражение на SQL

**Comment by YRozmysl** [comment]
В зарплате, например, это таблица USR$WG_BRIGADEORDERLINE  и в нем поле USR$ALLSUM имеет такую структуру

**Comment by NikolayUkleyko** [comment]
В таком случае можно создать SQL-запрос и в нем попробовать присвоить тип AsCurrency.

**Comment by YRozmysl** [comment]
локально я это уже все решил.  Это вопрос общей обработки таких полей в любых типовых проводках проводках. Ведь такое поле может же быть не 1-2 в базе

**Comment by gsbelarus** [comment]
Вычисляемое поле может любой тип иметь. например дата или строка. 

Тут два варианта решения проблемы. Можно просто **Value** использовать. Можно смотреть на тип в системных таблицах и нужное подставлять. **Value** может и лучше. А может и не лучше. В зависимости от того, что мы хотим с NULL делать.

Посмотреть, сможем ли мы тип поднять из системных таблиц.

**Comment by NikolayUkleyko** [comment]
> Посмотреть, сможем ли мы тип поднять из системных таблиц.

Было бы хорошо.

**Comment by gsbelarus** [comment]
Новым экзешником переформировать код.

**Comment by alexandra-gsoftware** [comment]
все проводки перекомпилировать, или какие-то конкретные?

**Comment by YRozmysl** [comment]
у меня, например, такое было в одной, которую заметили бухгалтера, сколько их и есть ли еще не знаю даже.

**Comment by alexandra-gsoftware** [comment]
ок, тогда чуть позже перекомпилирую все....

**Comment by NikolayUkleyko** [comment]
> ок, тогда чуть позже перекомпилирую все....

Только, ЗП и ОК ?

**Comment by alexandra-gsoftware** [comment]
нет, всё что в эталоне

**Comment by NikolayUkleyko** [comment]
> нет, всё что в эталоне

Хорошо.
Их там немало, но и нельзя сказать, что огромное множество.
