### ISSUE TITLE
Кнопка 'Закрыть все окна'. Предусмотреть горячие клавиши

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3872]
На практике встречаются ситуации, когда при подключении к БД по-умолчанию формы закрывают доступ к главной панели программы. Приходится вручную закрывать каждую форму и по итогу нажать на кнопку **Закрыть все окна**. Это не удобно. На каждой БД под разными пользователями свои настройки рабочего стола Гедымина.

@gsbelarus , пожалуйста, предусмотрите горячие клавиши для команды **Закрыть все окна**.
В Гедымине предусмотрены горячие клавиши для вызова Исследователья **Ctrl+F11**.
В Windows же есть горячие клавиши для сворачивания всех окон **Win+D**.
Это удобно ! :+1::+1::+1:

**Comment by NikolayUkleyko** [comment]
@iamchrisep , пожалуйста, укажи соответствие горячих клавиш выполняемым командам ?

**Comment by iamchrisep** [comment]
Свернуть форму просмотра - Ctrl+F3
Свернуть все формы просмотра - Shift+Ctrl+F3
Закрыть форму просмотра - Ctrl+F4
Закрыть все формы просмотра - Shift+Ctrl+F4

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@iamchrisep , спасибо !
:trophy:
