### ISSUE TITLE
Справочники. В справочник единиц измерения добавить поле 'К-во десятичных знаков' (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3878]
Перенесено из https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/221

**Comment by NikolayUkleyko** [comment]
В справочник единиц измерения параметр добавлен. Это хорошо.
![1](https://cloud.githubusercontent.com/assets/11497453/21685788/fad81060-d373-11e6-8fca-7d51627beab0.png)

----

Однако, в Журнале-ордере при выборе определенного количественного показателя динамически не заполняется реквизит **Количество знаков после запятой**. Это не хорошо.
![2](https://cloud.githubusercontent.com/assets/11497453/21685850/2aef042a-d374-11e6-80d5-af9f781c6c1f.png)

**В Журнале-ордере в случае одновременного выбора нескольких количественных показателей, то не заполнять данный реквизит**.

**Comment by gsbelarus** [comment]
А если выбраны несколько количественных показателей и у каждого разное кол-во дес знаков?

**Comment by NikolayUkleyko** [comment]
> А если выбраны несколько количественных показателей и у каждого разное кол-во дес знаков?

Я про это писал:

> В Журнале-ордере в случае одновременного выбора нескольких количественных показателей, то не заполнять данный реквизит.

Тогда, не заполнять данный реквизит.

**Comment by ShlTanya** [comment]
Поле "Кол-во десятичных знаков" отсутствует как в системных полях, так и в ПИ.

**Comment by alexandra-gsoftware** [comment]
>>>Поле "Кол-во десятичных знаков" отсутствует как в системных полях, так и в ПИ.

может, оно добавлено для конкретного клиента?
@NikolayUkleyko , на какой БД ты смотришь?

**Comment by NikolayUkleyko** [comment]
>Поле "Кол-во десятичных знаков" отсутствует как в системных полях, так и в ПИ.

Суть в том, что я изложил материал.
Обсудили.
Потом была выполнена доработка. Кто делал - не знаю.
:smile:

**Comment by ShlTanya** [comment]
На текущий момент в этом есть неоходимость??

**Comment by NikolayUkleyko** [comment]
> На текущий момент в этом есть неоходимость??

Да.
Надо сделать качественно.

**Comment by gsbelarus** [comment]
@shltanya
http://gsbelarus.com/gs/wiki/index.php/%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F_%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D1%8B_%D0%B1%D0%B0%D0%B7%D1%8B_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85

**Comment by ShlTanya** [comment]
Куда на форме добавить новое поле "Кол-во десятичных зн.", так чтобы не возникло наложение с уже добавленными полями пользователей.
И что будет с конфигурациями, где это поле уже создано как пользовательское.

**Comment by gsbelarus** [comment]
А где оно создано как пользовательское?

Я таких не видел баз.

**Comment by ShlTanya** [comment]
1-й скриншот 
И поле "Код для электр. документов" тоже не системное, но есть комплексной конфигурации, например.

**Comment by MIchaelShoihet** [comment]
Раз в стандартных настройках нет этого поля, то это будет локальная проблема конкретного клиента и будет решена в частном порядке. Об этом можно не волноваться.

**Comment by gsbelarus** [comment]
Выше я вижу поле Код для электронного документа. Это случайно не ЭСЧФ?

**Comment by ShlTanya** [comment]
Код электронного документа есть в ПИ, значит м.б. у многих

**Comment by gsbelarus** [comment]
Это плохо. В каком пи?

**Comment by gsbelarus** [comment]
Надо было и его в гедымине делать.

**Comment by ShlTanya** [comment]
GS.Общее.Единицы измерения

**Comment by gsbelarus** [comment]
Надо разобраться. Где то же это поле используется. Надо найти автора. Пока
делать другой вопрос.

**Comment by ShlTanya** [comment]
хорошо.. пока это отложила

**Comment by alexandra-gsoftware** [comment]
есть 2 кода: для электронных документов и для ЭСЧФ. В розничной торговле есть еще свои коды для ед.изм., т.е. везде в GD_VALUE есть юзерские поля, как и в GD_GOOD, и в GD_DOCUMENT, и в GD_CONTACT.

**Comment by aer1k** [comment]
Код для электронных документов -- не моё.
Код для ЭСЧФ - моё.

**Comment by alexandra-gsoftware** [comment]
Код для электронных документов - моё.

**Comment by NikolayUkleyko** [comment]
В справочник единиц измерения я ничего не добавлял.
Я делал постановку задачи, а кто-то ее реализацию. Неизвестно.
Надо сделать едино и верно: требуемые поля создать на уровне gedemin.exe, а дублирующиеся поля удалить.

**Comment by gsbelarus** [comment]
Пока ничего не делать по этому вопросу.
