### ISSUE TITLE
Глобальный прогресс-бар. Добавить формат для отображаемых записей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3880]
Пожалуйста, для большей наглядности прогресс-бара добавьте формат для отображаемых записей.

![1](https://cloud.githubusercontent.com/assets/11497453/19605365/4385e00a-97c2-11e6-80cf-40a11a96ae4d.png)

**Comment by gsbelarus** [comment]
Не всегда один шаг равен одному )) Для неравномерных процессов будет разное количество и тогда некорректно писать **Обработка позиции 1157**.

**Comment by PiuPauTralala** [comment]
Я так понимаю, что просят возможность писать "1 156 из 3 009" вместо "1156 из 3009".
Если нижний подстрочник пишет сам программист, и можно использовать FormatNumber, то верхняя строчка вне власти.

**Comment by gsbelarus** [comment]
Это сделано уже давно.
