### ISSUE TITLE
Типовой документ. Складской документ. Справочники. Доступность реквизитов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3881]
**Типовой документ / Складской документ / Справочники. Доработки**.

Пожалуйста, предусмотрите автоматический запрет выбора галок по противоречащим параметрам.
То есть, при выборе одного параметра сделать **недоступным для заполнения** другой связанный параметр.
Например, некорректен одновременный выбор галок по реквизитам **Осуществлять контроль остатков**, **Контроль только на текущие остатки**, **Контроль остатков на конец месяца**. Параметров немало, не всегда помнишь что-к-чему.

![1](https://cloud.githubusercontent.com/assets/11497453/19725919/0115efc6-9b91-11e6-8661-b4290896081a.png)

![2](https://cloud.githubusercontent.com/assets/11497453/19725931/19a034c0-9b91-11e6-93f2-36c46d128603.png)

@MIchaelShoihet , пожалуйста, изложите, Вашу, точку зрения.

**Comment by MIchaelShoihet** [comment]
Сделаем

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , Вы, обещали.
Пожалуйста, решите вопрос.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, по возможности посмотрите данный вопрос.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, обсуждаемая тема.

**Comment by NikolayUkleyko** [comment]
Связанная тема https://github.com/GoldenSoftwareLtd/gedemin/issues/3621.

**Comment by ShlTanya** [comment]
Чтобы выполнить задание, надо знать список связанных параметров. Буду благодарна за предоставление данной информации.

**Comment by NikolayUkleyko** [comment]
Параметры делаем неактивными при следующих сочетаниях:

1. В случае выбора галки по реквизиту **_Осуществлять контроль остатков_** доступными становятся два реквизита **_Контроль только на текущие остатки_** и **_Контроль остатков на конец месяца_**.
При этом, можно выбрать только один из них.

2. Для типовых документов категории **Документ с изменением свойств ТМЦ** (например, 04. Отпуск материалов покупателям, 03. Отпуск товара на сторону (оптовая торговля) и т.д.) реквизит **_Движение без поиска остатков_** активен при снятой галке на реквизите **_Осуществлять контроль остатков_**.

**Comment by ShlTanya** [comment]
п. 2 Какое поведение данного реквизита для других категорий?

**Comment by NikolayUkleyko** [comment]
Статус реквизита **_Движение без поиска остатков_** не зависит от реквизитов **_Контроль только на текущие остатки_** и **_Контроль остатков на конец месяца_**.

**Comment by NikolayUkleyko** [comment]
Внесите правки или закройте тему.

**Comment by ShlTanya** [comment]
п.2.  
1. Документ с изменением свойств ТМЦ - это документ с выставленными признаками Разрешить изменять признаки сущ. карточки и/или Разрешить добавлять признаки сущ. карточки?
2. Не нашла реквизит Движение без поиска остатков.

**Comment by NikolayUkleyko** [comment]
1. Нет. Это указанное значение реквизита **Шаблон документа**. Потом, его нельзя менять.
![image](https://user-images.githubusercontent.com/11497453/161266818-c13c69ea-9c57-4fb2-aa2b-71adb0370f10.png)
2. Достаточно снять галку с реквизита **Осуществлять контроль остатков** и реквизит **Движение без поиска остатков** отобразится.

**Comment by MIchaelShoihet** [comment]
Если Осуществлять контроль остатков стоит - то доступны галки Контроль только на текущие остатки и Контроль остатков на конец месяца. При этом они обе могут быть не установлены, а установлена может быть только одна. Осуществлять контроль остатков не стоит - эти 2 галки не доступны должны быть.
Остальное не важно.

**Comment by ShlTanya** [comment]
Спасибо

**Comment by Polfath** [comment]
Посмотрю

**Comment by Polfath** [comment]
@NikolayUkleyko я поправил, посмотрите пожалуйста правильно ли.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
