### ISSUE TITLE
Глобальный прогресс-бар. Подготовка данных для расчета

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3883]
На больших объемах данных при запуске расчета окно глобального прогресс-бара отображается не сразу. Спустя минут 5-10, программа отображает данное окно с ходом пошагового выполнения расчетов.
**Так не должно быть. Не понятно, работает ли программа или нет**. Как предполагается, в момент от начала расчета до появления окна с выполнением расчета программа выполняет подготовку данных. Поэтому, предлагается отображение окна глобального прогресс-бара сразу же после запуска расчета с отображением формулировки **Подготовка данных. Пожалуйста, ожидайте** + бегущая строка состояния.

**Comment by gsbelarus** [comment]
Это не к гедымину, а к разработчику конкретного решения. Пусть он вызывает прогресс бар с самого начала процесса. Как я понимаю такая ситуация возникает когда сначала запускается SQL запрос, а потом уже обрабатываются его выборка.
