### ISSUE TITLE
Создать глобальную форма ошибок (error list)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3884]
Существующая форма не совсем информативна. Порой она отображается пустой. Поиск ошибок значительно затрудняется.
## 
## ![1](https://cloud.githubusercontent.com/assets/11497453/19809111/7a6eb0d8-9d30-11e6-9f64-d46b54ab4ed9.png)

Предлагается, по аналогии глобального прогресс-бара добавить **глобальную форму отображения ошибок**. Перечень предполагаемых достоинств новой глобальной формы ошибок:

**1**. Унифицированность для всех документов. Каждый раз не надо **_лепить**_ что-то.
**2**. Простота написания в коде.
**3**. Большая скорость формирования по сравнению с существующей формой.
**4**. Отображение большего количества реквизитов. Соответственно, большая информативность и наглядность.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by alexandra-gsoftware** [comment]
пока у меня есть ПИ GS.Общее.Форма с текстом
выглядит так:
![image](https://cloud.githubusercontent.com/assets/11487200/25236548/c9daf1f6-25f0-11e7-8637-d8d5f2ea09d2.png)
В мемо пишешь что хочешь. Юзер может менять этот текст. Можно обрабатывать ОК и отмена, можно сохранять в текстовый файл....

**Comment by NikolayUkleyko** [comment]
@alexandra-gsoftware , хороший вариант.
Только сделать размер формы шире.
Необходимо взвесить все **за** и **против**.
Принять решение: создать глобальную форма ошибок (error list) в gedemin.exe или в ПИ.
Надо не откладывать решение данного вопроса.

**Comment by gsbelarus** [comment]
Есть отдельный инструмент, который не блокируется и выполняется в отдельном
процессе -- gdcc. Что еще надо?

Любое окно в гедымине зависнет, когда зависнет и сама программа.

**Comment by stasgm** [comment]
Наверное @NikolayUkleyko  имеет в виду вывод журнала после выполнения операции, а не отображение какого-либо процесса. 
Например, у нас есть операция выдачи сырья со склада в производство под заданные блюда. И если не хватает остатков то мы записываем сколько и чего не хватило в txt файл и открываем пользователю в конце этот список в блокноте. 
Использовать gdcc в данном случае не лучший вариант, т.к. обычный пользователей не будет открывать его и что-то искать.

**Comment by NikolayUkleyko** [comment]
>Использовать gdcc в данном случае не лучший вариант, т.к. обычный пользователей не будет открывать его и что-то искать.

Верно.
На практике никто из пользователей не полезет в Gdcc.
К тому же, в Gdcc для рядового пользователя информация сугубо по предметной части ненаглядная.
Gdcc хороша для продвинутых пользователей.

----

В gedemin.exe создан замечательный унифицированный Progress bar.
Почему бы не создать и Error list ?

**Comment by alexandra-gsoftware** [comment]
я доработала форму с текстом,  добавила класс.  если хотите, могу сделать настраиваемым размер и скроллы

**Comment by NikolayUkleyko** [comment]
>я доработала форму с текстом, добавила класс. если хотите, могу сделать настраиваемым размер и скроллы

да

**Comment by gsbelarus** [comment]
давайте пока сконцентрируемся на самых приоритетных вещах.

все равно у этого списка будет существеннейший недостаток. он привязан к основной нити визуального интерфейса гедымина. т.е. он зависнет вместе с гедамином или в процессе выполнения долгих операций.

по этому и создавался gdcc -- как отдельный процесс.

может его стоит доработать под эту задачу. это будет лучше, чем отдельное окно из макросов.
