### ISSUE TITLE
Обнуление признаков в складском документе

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#3885]
Если в обычном складском документе (например, Накладная на получение) выбрать признак существующей карточки, то сбросятся все признаки новой карточки.
Если такой документ не должен работать с FROM признаками, то надо сделать невозможным их выбор.

**Comment by MIchaelShoihet** [comment]
Простой складской документ, может работать либо только с существующими карточками либо с новыми. Поэтому при выборе одного из вида, сбрасывается другой.

**Comment by AliakseiDanilchyk** [comment]
Это понятно. Здесь ситуация была такая. Клиент пожаловался, что у него при заполнении позиций документа выскакивает ошибка об отсутствии FROM поля.  Я без задней мысли посоветовал добавить этот признак в настройках сладского документа. После чего все стало намного хуже, потому что это была приходная накладная, и в ней какая-то ошибка в коде.
Как минимум предупреждение о последствиях таких действий было бы не лишним. Хотя ситуация, конечно, не распространенная.

**Comment by NikolayUkleyko** [comment]
> Простой складской документ

@MIchaelShoihet , что подразумевается под этим ?

Приведенное здесь было давно и никто не обращал на это внимания или этот новый вопрос ?

**Comment by MIchaelShoihet** [comment]
Складские документы бывают 4 типов - простой складской (используется только для прихода нового ТМЦ либо для перемещения без изменения св-в, Документ изменения св-в - используется для перемещения с изменением св-в, Документ трансформации, Инвентаризационный документ). Так вот в простом складском документе - если он используется для прихода, то только новый признаки, если для перемещения - то только существующие - так было всегда. Т.к. с документом работает настройщик то особых предупреждений нет. Хотя конечно надо добавить

**Comment by NikolayUkleyko** [comment]
> Хотя конечно надо добавить

Абсолютно согласен. Само собой разумеется.

**Comment by NikolayUkleyko** [comment]
Рассмотрим стандартную приходную накладную по товарам.
В типовом документе указано, что возможен выбор товаров **как из справочника ТМЦ, так и из справочника остатков по ТМЦ**.
Раз предусмотрен выбор товаров из **остатков** значит речь идет не только **о признаках новой карточки, но и о признаках существующей карточки.**

----

При выбранных признаках существующей карточки, выбрали признак новой карточки и все признаки существующий карточки очищены.
Пожалуйста, предусмотрите адекватную обработку приведенной ситуации.
Случайно забыл про это и заново выбирай признаки.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by NikolayUkleyko** [comment]
Актуальна ли данная тема ?
