### ISSUE TITLE
SQL-редактор/Таблицы. Предусмотреть поиск

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3888]
Пожалуйста, в SQL-редакторе предусмотрите возможность поиска для таблиц, как это предусмотрено для бизнес-классов. Поиск должен быть с учетом регулярных выражений.

**Таблицы**
![1](https://cloud.githubusercontent.com/assets/11497453/20142658/bf531200-a6a6-11e6-92ee-fd05889ed5c8.png)

---

**Бизнес-классы**
![2](https://cloud.githubusercontent.com/assets/11497453/20142670/cba1a30a-a6a6-11e6-958d-73afd1aee129.png)

**Comment by ShlTanya** [comment]
В SQL-редакторе уже реализована возможность поиска для таблиц (без учета регулярных выражений) 
![tbl](https://cloud.githubusercontent.com/assets/24572314/21751115/a37d1d22-d5d2-11e6-8566-2596afa794ee.jpg)

**Comment by gsbelarus** [comment]
Отлично. Значит уже было сделано. Закрываем.

**Comment by NikolayUkleyko** [comment]
> Отлично. Значит уже было сделано. Закрываем.

@gsbelarus , не забыть закинуть данные изменения в gedemin.exe на сайте.
