### ISSUE TITLE
Редактор скрипт-объектов. Пропадает полоса прокрутки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3889]
Уже не первый раз замечено, что в Редактор скрипт-объектов пропадает полоса прокрутки. Это уже чрезмерно многих напрягает.

![1](https://cloud.githubusercontent.com/assets/11497453/20174101/5b661d76-a74d-11e6-9e7d-e736dffa42c6.png)

Пожалуйста, исправьте.

**Comment by NikolayUkleyko** [comment]
Пожалуйста, посмотреть можно, подключившись на удаленный рабочий стол **Береза МКК**.

**Comment by gsbelarus** [comment]
У нас в офисе повторяется? Какая версия экзешника у них?

**Comment by NikolayUkleyko** [comment]
Пробовал моделировать подобное на офисной БД - работает четко и без проблем.

----

На удаленном рабочем столе:
Дата файла           = 14.11.2016
Версия файла         = 2.9.2.8890

**Comment by AliakseiDanilchyk** [comment]
Полоса прокрутки появится, если подвигать границу между проводником и редактором функции

**Comment by NikolayUkleyko** [comment]
> Полоса прокрутки появится, если подвигать границу между проводником и редактором функции

Пробовали такое. Не всегда помогает и полоса прокрутки может снова скрыться.
По итогу это нездоровое явление, которое следует полностью устранить.
