### ISSUE TITLE
БМКК. Торговля. Не работает глобальная блокировка периода

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3890]
***Исследователь / Торговля / Все документы***.

Не работает глобальная блокировка периода.

![1](https://cloud.githubusercontent.com/assets/11497453/20215598/5ea536e6-a826-11e6-9aac-4d641d63da68.png)

**Comment by NikolayUkleyko** [comment]
Бухгалтера по торговле уже **не первый раз** интересуются данным вопросом. Актуальность вопроса повышается немалым количеством бухгалтеров по торговле. Вследствие неразбериха, кто да что.
Сверив данные и выполнив печать, спустя непродолжительное время (1-2 дня) выявляются расхождения. Данные расхождения, предположительно, получаются из-за ***лишнего*** перепроведения проводок по документам (того хуже, если запустить ***лишний*** раз макрос **Перепровести количество**).

**Comment by gs7600300** [comment]
**Проблема актуальна** на Сморгонском КХП.

**Comment by MIchaelShoihet** [comment]
На БМКК кто-то закомментировал все триггера блокировки. Причем закомментированы в IBExpert.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@MIchaelShoihet , спасибо !
