### ISSUE TITLE
Сморгонь КХП. Не работают исключения по документу в глобальной блокировке периода (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3891]
Не работают исключения по документу в глобальной блокировке периода.

![1](https://cloud.githubusercontent.com/assets/11497453/20215734/59d53c28-a827-11e6-9fbe-16ddf60be297.png)

**Comment by gsbelarus** [comment]
Надо сравнить триггеры блокировки с эталонными. Может там какая очень старая версия бд.

**Comment by NikolayUkleyko** [comment]
Аналогичная ситуация есть и на Гомельобоях.
Вопрос: **где-нибудь вообще работает исключение по типовым документам в глобальной блокировке периода ?**

**Comment by MIchaelShoihet** [comment]
Везде работает.

**Comment by gsbelarus** [comment]
Где не работает -- проверьте все триггеры блокировки. Или отключены они, или повреждены.

**Comment by NikolayUkleyko** [comment]
> Где не работает -- проверьте все триггеры блокировки. Или отключены они, или повреждены.

Проверил на эталоне.
Не работает исключение по типовым документам в глобальной блокировке периода.

Я давно выявил данную проблему. Никому не интересно.
