### ISSUE TITLE
Витебск МК. ЭСЧФ. Ручная разноска ЭСЧФ. Invalid parent subtype

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3893]
***Исследователь / ЭСЧФ / 6. Ручная разноска ЭСЧФ***.

При попытке установки ПИ (настройки) с типовым документом, таблицей и т. д. программа выдает окно с ошибкой и, нажав на кнопку **OK** закрывается:

![1](https://cloud.githubusercontent.com/assets/11497453/20627773/4831b7c8-b333-11e6-9aa3-05ca89751b80.png)

При следующих попытках подключения к БД программа снова выдает аналогичное окно и закрывается. К БД не добраться. Выручает подключение к БД старым gedemin.exe / в типовой проводке для смены ссылки указать другой документ / удаление типового документа **6. Ручная разноска ЭСЧФ**. Тогда, можно подключиться новый gedemin.exe, но документ не работает.

С @iamchrisep моделировали данную ситуацию. В gedemin.exe в коде намеренно прописано такое поведение:
Invalid parent subtype и **жесткое** захлопывание БД. Какой смысл был в таком ?

Данную проблему разбирали @MIchaelShoihet , @alexandra-gsoftware . Результата нет.
@gsbelarus  пожалуйста, оперативно устраните недоработку.

**Comment by NikolayUkleyko** [comment]
Я уже ничему не удивляюсь.

**Comment by alexandra-gsoftware** [comment]
от себя добавлю: документ юзерский, только шапка, веточка в документтайпах, куда он входит, на базе уже есть. Остальное (таблица, типовой док, события, хранилище) вместе находятся в пи / настройке . На копии базы, что есть у нас, все хорошо  ставится.

**Comment by gsbelarus** [comment]
Тут не надо удивляться. Или поставить им новейший экзешник, или (если не поможет) то взять их БД, на которой вылазит ошибка и посмотреть из-под отладчика.

**Comment by gsbelarus** [comment]
> Invalid parent subtype и жесткое захлопывание БД. Какой смысл был в таком ?

Отсутствует класс. Как программа может работать? Например, если в исходниках Делфи не будет класса, который где-то используется, то такие исходники вообще не откомпилируются.

База где? чтобы посмотреть.

И еще вариант, в ПИ все что надо включено? А то может наследника включили, а родительский класс забыли.

**Comment by alexandra-gsoftware** [comment]
там обычный юзерский документ, его таблички, события и хранилище. На другие бд ставится.

**Comment by gsbelarus** [comment]
Тогда точно нужна дефективная база.

**Comment by NikolayUkleyko** [comment]
> Тогда точно нужна дефективная база.

Удаленно рабочая БД.

**Comment by gsbelarus** [comment]
Удаленно не поможет. BK=> RAR => FTP.

**Comment by NikolayUkleyko** [comment]
Заявка отправлена.

**Comment by gsbelarus** [comment]
Есть база посмотреть этот момент?

**Comment by NikolayUkleyko** [comment]
@gsbelarus , БД достигли больших размеров. Удаленно на сервере сделают тестовые версии БД.

**Comment by alexandra-gsoftware** [comment]
так а что, поправили?

**Comment by NikolayUkleyko** [comment]
Коллеги, не будем ссориться.
