### ISSUE TITLE
Общие таблицы/локальные таблицы в БД

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3894]
В свое время **Гедымин** создавался с оглядкой на существующие системы и со взгядом на будущее. Предположительно, поэтому и были предусмотрены общие таблицы такие, как: AC_ENTRY, AC_RECORD, GD_DOCUMENT, INV_CARD и другие. До сих пор такие таблицы используются по их назначению.
  В случае ухода от общих таблиц и соответственно их использования в сторону локальных таблиц напрашивается вопрос, на сколько изменится структура БД с точки зрения пользователя ? Быстродействие. Надежность. Конвертирование существующих БД.
  В части настройки типовых проводок, что кардинально изменится ?

**Comment by NikolayUkleyko** [comment]
Вопрос можно сформулировать иначе: зачем было изначально брать за основу общие таблицы, чтобы сейчас от них отказаться ?

**Comment by gsbelarus** [comment]
Пока никто ни от чего не отказывается. Идут эксперименты. У общих таблиц есть плюсы и минусы. 20 лет назад не было ех возможностей SQL (cte, window functions) которые бы позволяли сводить разрозненные таблицы в единое целое.
