### ISSUE TITLE
Падение производительности при выполнении запроса в FB 3.0

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3895]
При пересчете в итоговом начислениии  ОЧЕНЬ долго выполняется запрос 
В 3.0
![3_0](https://cloud.githubusercontent.com/assets/11507129/20750892/14b838b0-b70a-11e6-98b6-b53d3766930a.jpg)

В 2_5
![2_5](https://cloud.githubusercontent.com/assets/11507129/20750899/1bdc21b0-b70a-11e6-9fa6-4b904a49a334.jpg)

 SELECT doc.documentdate, card.*  FROM usr$wg_taxation card  JOIN USR$WG_P_EMPLTAXSTATE(:emplkey, :carddate) state ON card.documentkey = state.id  JOIN gd_document doc ON doc.id = card.documentkey AND doc.companykey = <companykey/>

**Comment by gsbelarus** [comment]
Надо сравнить план и статистику в 2.5 и 3.0.

**Comment by YRozmysl** [comment]
ФБ 2.5
![plan_2_5](https://cloud.githubusercontent.com/assets/11507129/20755475/31e9b358-b720-11e6-8b04-2040442db319.jpg)
![stat_2_5](https://cloud.githubusercontent.com/assets/11507129/20755481/36f848c8-b720-11e6-8e85-1ee5ae4d1eda.jpg)
ФБ 3.0
![plan_3_0](https://cloud.githubusercontent.com/assets/11507129/20755493/40268f7c-b720-11e6-836a-8389a59506ea.jpg)
![stat_3_0](https://cloud.githubusercontent.com/assets/11507129/20755500/4649a11e-b720-11e6-9118-a9adad28b0b4.jpg)

**Comment by gsbelarus** [comment]
Подождем, что скажут мудрые люди:

http://www.sql.ru/forum/1240993-a/neoptimalnyy-plan-v-fb-3-po-sravneniu-s-fb-2-5

**Comment by gsbelarus** [comment]
Пока они там у себя будут разбираться, мы можем внести маленькое исправление, которое решит проблему -- + 0 для отключения индекса:

```
  SELECT FIRST(1) doc.id, doc.documentdate
  FROM usr$wg_taxation card
  JOIN gd_document doc ON doc.id = card.documentkey
  WHERE card.usr$emplkey = :emplkey AND
    doc.documentdate <= :begindate
  ORDER BY doc.documentdate + 0 DESC
```

**Comment by YRozmysl** [comment]
Да, отключение помогло, проверено.

**Comment by gsbelarus** [comment]
Будем ждать резолюции разработчиков:

http://tracker.firebirdsql.org/browse/CORE-5421

**Comment by gsbelarus** [comment]
В новой версии ФБ должно быть уже исправлено. Надо будет проверить.

**Comment by YRozmysl** [comment]
У нас на vkl версия FB 3.0 обновленная?

**Comment by gsbelarus** [comment]
Еще нет. Вечером обновлю. Завтра можно будет проверить.

**Comment by YRozmysl** [comment]
На последнем фб 3 вопрос решился
