### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Отображение нулевых данных по валюте и эквиваленту

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3896]
**Исследователь / Бухгалтерия / Журнал-ордер**.

За месяц (10.2016 г.) сальдо по валюте ***закрыто в 0***, а по национальной валюте (белорусский рубль) сальдо ***не закрыто в 0***.
За месяц (11.2016 г.) формируем форму только ***по валюте***.
При этом форма отображает строку по валюте ***с нулевым сальдо и с нулевыми оборотами***.
Не логично получается.
Намеренно формируем форму только по валюте без национальной валюты (белорусский рубль) и такой результат.
На мой взгляд нулевая строка не должно отображаться.

Вышеприведенное имеет силу и для эквивалента.

@MIchaelShoihet , пожалуйста, изложите, Вашу, точку зрения.

**Comment by NikolayUkleyko** [comment]
Аналогично проверил ситуацию, когда по национальной сальдо валюте закрыто, но есть сальдо в валюте и/или в эквиваленте.
В результате Журнал-ордер формируется без отображения нулевой строки по национальной валюте.
На мой взгляд это правильно.

Надо предусмотреть проверку согласно писаний в первом посте.

@MIchaelShoihet , пожалуйста, изложите, Вашу, точку зрения.

**Comment by MIchaelShoihet** [comment]
Да надо будет поправить.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , хорошо бы и это реализовать.

**Comment by ShlTanya** [comment]
Николай. Воспроизвела Вашу ситуацию, описанную в п.1
1. Сальдо на конец декабря по валюте нулевое:
![3896-1](https://cloud.githubusercontent.com/assets/24572314/22583501/fb35e4ba-e9fd-11e6-9107-acd14489f53a.JPG)

2. Журнал-ордер за январь.. не вижу я строку с нулевым сальдо и нулевыми оборотами (если их не было) по валюте:
![3896-2](https://cloud.githubusercontent.com/assets/24572314/22583571/6fb3750a-e9fe-11e6-964f-67593d87a73c.JPG)
![3896-3](https://cloud.githubusercontent.com/assets/24572314/22583578/778127a0-e9fe-11e6-95af-9839b12760e6.JPG)

**Comment by NikolayUkleyko** [comment]
@ShlTanya , сейчас разберемся.

----

Конечно, живое обсуждение вопросов не заменит облачное. :-)

**Comment by NikolayUkleyko** [comment]
Почему-то 90 и более % пользователей, кто желает сформировать Журнал-ордер по умолчанию в качестве аналитики выбирают **Месяц**.
Убеждаюсь не первый раз. :smile: 

Следует помнить, что есть особенности формирования Журнала-ордера по аналитикам, носящим периодический (временнОй) характер.

----

@ShlTanya , у себя еще раз смоделировал изложенный здесь пример. На новейшем gedemin.exe вопрос не решен.

@ShlTanya . пожалуйста, вместо аналитики **Месяц** выбери аналитику **Счет**.

**Comment by ShlTanya** [comment]
![3896-4](https://cloud.githubusercontent.com/assets/24572314/22585553/6f24fa04-ea09-11e6-878b-13175c272e36.JPG)
 А у Вас нет нулевых проводок ??  по валюте

**Comment by NikolayUkleyko** [comment]
@ShlTanya , может удаленно могу к тебе подключиться ?

**Comment by ShlTanya** [comment]
Мне лучше увидеть на Вашей базе. Можно скрины..

**Comment by NikolayUkleyko** [comment]
Для полноты картины в качестве аналитики выбрал:
- Счет;
- Клиент.

![2017-02-03_155926](https://cloud.githubusercontent.com/assets/11497453/22592276/f561ccb2-ea29-11e6-9073-066acaa21984.png)

Отображение сумм **в рублях и и валюте**.
Период: октябрь 2016 г.

----

![2017-02-03_155957](https://cloud.githubusercontent.com/assets/11497453/22592309/2f18875c-ea2a-11e6-8c73-58536b83a98b.png)

Отображение сумм **в рублях и и валюте**.
Период: ноябрь 2016 г.

----

![2017-02-03_160008](https://cloud.githubusercontent.com/assets/11497453/22592317/3a15eda2-ea2a-11e6-9859-ad6a190f441c.png)


Отображение сумм **в валюте**.
Период: ноябрь 2016 г.

**Comment by ShlTanya** [comment]
И последний вопрос.. что показывает Карта счета по этой строке.

**Comment by NikolayUkleyko** [comment]
![2017-02-03_164929](https://cloud.githubusercontent.com/assets/11497453/22593671/ca304d5a-ea30-11e6-8eb1-d58abfbe8f78.png)

**Comment by ShlTanya** [comment]
Николай, попробуйте убрать галочку "Показывать нули в таблице" в Параметрах.

**Comment by ShlTanya** [comment]
Выполнила.

**Comment by ShlTanya** [comment]
Николай, проверьте, пожалуйста этот вопрос.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
