### ISSUE TITLE
Автозадача перестает выполняться при переходе на новые сутки

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#3897]
Редко, но бывает, что автозадача перестает выполняться в районе 12 часов ночи. (чуть раньше или чуть позже). Автозадача выполняется с частотой 3 минуты.

**Comment by MBurakina** [comment]
Ещё автозадачи перестают работать после режима сна. Т.е. компютер работает - работают автозадачи, отправляем в сон - компьютер спит, автозадачи не выполняются; компьютер разбудили - работает, а автозадачи нет, нужна перезагрузка платформы.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
