### ISSUE TITLE
ПИ. Окно синхронизации. Добавить реквизит 'Отобразить только корневые файлы'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3899]
Пожалуйста, предусмотрите в *форме синхронизации ПИ* реквизит **Отобразить только корневые файлы**. Пример, ПИ из папки Бухгалтерия, Склад. В данные папки входит перечень папок и **перечень файлов** не входящих в какие либо папки. Из перечня только корневых файлов необходимо выбрать требуемые. Таким образом, при установке ПИ добавится удобство работы с формой и минимизируется выбор лишних ПИ.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает некорректно.

1. Для наглядности рассмотрим папку **Name_space_new\gedemin-apps\Склад**.
Выполнили сравнение с файлами по умолчанию. То есть, без выбора галки по реквизиту **Скрыть каталоги**:

![2017-01-10_133339](https://cloud.githubusercontent.com/assets/11497453/21803290/8416c442-d73a-11e6-9122-ab0c0133a56d.png)

----

2. По реквизиту **Скрыть каталоги** проставили галку:

![2017-01-10_133545](https://cloud.githubusercontent.com/assets/11497453/21803338/b24c1a56-d73a-11e6-8ad6-37041afb768d.png)

----

3. Проверяем реальные файлы, не входящие в папки:

![2017-01-10_133925](https://cloud.githubusercontent.com/assets/11497453/21803356/c8c83648-d73a-11e6-890c-746d51a805da.png)

----

Итог: согласно данного примера в форме синхронизации пространств имен в правой части (файлы на диске) при выбранной галке по реквизиту должны быть отображены только файлы, отображенные согласно пункта 3.

**Comment by gsbelarus** [comment]
Так работает или нет? Закрывать?

**Comment by NikolayUkleyko** [comment]
> Так работает или нет? Закрывать?

Не работает.
Не закрывать.

**Comment by ShlTanya** [comment]
На данной форме добавлено 2 галки: 
1 - Подкат. (возле параметра Сущ.) - в выключенном состоянии отображает только корневые файлы (то, что Вы хотели)
2 - Скрыть каталоги - это фильтр, который отображает/скрывает строки с наименованием только каталогов в выборке.

**Comment by NikolayUkleyko** [comment]
> 1 - Подкат. (возле параметра Сущ.) - в выключенном состоянии отображает только корневые файлы (то, что Вы хотели)

Из-за сильно сокращенных названий реквизитов не сразу заметил данный реквизит.
Пожалуйста, перенесите все реквизиты типа Boolean на одну панель и предусмотрите не сокращенные названия таких реквизитов.

Проверено.
Работает корректно.

> 2 - Скрыть каталоги - это фильтр, который отображает/скрывает строки с наименованием только каталогов в выборке.

Проверено.
Работает корректно.

@ShlTanya , спасибо ! :trophy:

**Comment by gsbelarus** [comment]
не надо никуда ничего переносить. экономим место на экране. там хинты всплывающие содержат подробную информацию.

**Comment by NikolayUkleyko** [comment]
> не надо никуда ничего переносить. экономим место на экране. там хинты всплывающие содержат подробную информацию.

OK !

**Comment by NikolayUkleyko** [comment]
Жаль, что перенос слов здесь не предусмотрен.
