### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. В диалоговой форме неактивна кнопка 'Удалить'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3900]
**Исследователь / Бухгалтерия / Журнал хоз. операций**.

В диалоговой форме при работе со сложными проводками неактивна кнопка **Удалить**. При этом, горячие клавиши здесь не предусмотрены. Вроде бы, раньше эта кнопка была доступна. @MIchaelShoihet , скажите, пожалуйста, так, задумано или нет ?

**Comment by ShlTanya** [comment]
Кнопка Удалить активна при выполнении условий:
1. Кол-во проводок  больше 1
и
2. Сумма по проводке = 0 (пусто)

**Comment by MIchaelShoihet** [comment]
Так и было задумано. Возможно удалить только сложную часть проводки

**Comment by NikolayUkleyko** [comment]
>Кнопка Удалить активна при выполнении условий:
>
>Кол-во проводок больше 1
>и
>Сумма по проводке = 0 (пусто)

>Так и было задумано. Возможно удалить только сложную часть проводки

Проверено.
Так и есть.
