### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Сторнировать проводку. Мелкие правки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3902]
**Исследователь / Бухгалтерия / Журнал хоз. операций**.

----

**1.**

![2017-01-09_171353](https://cloud.githubusercontent.com/assets/11497453/21769629/c11ad55e-d690-11e6-9f83-7338c3731650.png)

![2017-01-09_171805](https://cloud.githubusercontent.com/assets/11497453/21769630/c1269f9c-d690-11e6-985d-f8e9fae1f1f1.png)

В параметре **Привязать к типовой операции** предусмотреть сортировку по возрастанию.

----

**2.**

![2017-01-09_172324](https://cloud.githubusercontent.com/assets/11497453/21769631/c12b4e52-d690-11e6-9ea5-06b04759d777.png)

В поле описание, где выводится номер документа предусмотреть **знак № - пробел - номер**. Где выводится год предусмотреть **отображение года - пробел - г.**.

**Comment by ShlTanya** [comment]
Выполнено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.

----

Возник вопрос.
Например, по документу сформированы 3-и **простые** бухгалтерские проводки.
Затем, в Журнале хоз. операций через соответствующий макрос выполняем сторнирование таких проводок с выбором реквизита **Все проводки по документу**.
Удаляем одну из сторнирующих проводок - удаляются все сторнирующие проводки.
Не совсем понятен алгоритм работы программы.
Одно дело, когда была бы аналитика **Документ**, а здесь нет такой аналитики.

Согласно данного примера, на мой взгляд, должна быть удалена лишь одна выбранная сторнирующая проводка.

@MIchaelShoihet , пожалуйста, изложите, Вашу, точку зрения.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.

----

Возник вопрос.
Например, по документу сформированы 3-и **простые** бухгалтерские проводки.
Затем, в Журнале хоз. операций через соответствующий макрос выполняем сторнирование таких проводок с выбором реквизита **Все проводки по документу**.
Удаляем одну из сторнирующих проводок - удаляются все сторнирующие проводки.
Не совсем понятен алгоритм работы программы.
Одно дело, когда была бы аналитика **Документ**, а здесь нет такой аналитики.

Согласно данного примера, на мой взгляд, должна быть удалена лишь одна выбранная сторнирующая проводка.

@MIchaelShoihet , пожалуйста, изложите, Вашу, точку зрения.

**Comment by MIchaelShoihet** [comment]
Аналитика документ здесь не играет никакой роли. При сторнировании необходимо для каждой проводки свой документ делать. Тогда можно будет удалить одну проводку.

**Comment by NikolayUkleyko** [comment]
OK !

Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
