### ISSUE TITLE
Отчеты по торговому складу. Платежный календарь.

### ISSUE THREAD

**Issue by MAliaksandr** [GoldenSoftwareLtd/gedemin#3903]
В отчетах по торговому складу есть отличная форма **"Платежный календарь"**. Буквально на днях столкнулся с недовольством клиента:
**1. Не суммируются колонки.**(данная проблема решаема через переделывания TClienDataSet на TIBDataset)
**2. Отсутствуют какие-либо печатные формы**
3. И самое интересное. **"Почему он не показывает по каким накладным проходили оплаты?"** 

Поковыряв саму форму, было определено, что данная форма отображает только суммы по документам отгрузки или поступления. Логично, что данная форма не отобразит оплаченные или частично оплаченные документы. Поэтому, думаю стоит переименовать его в какой-нибудь "Календарь будущих платежей" или "Предстоящие оплаты по документам" или что-то в этом духе. 
Конечно, было бы идеально отображать здесь полные или частичные оплаты документов, но это уже другая история, связанная с разноской, выпиской и т.п.
Данная форма неплохо работает при адекватной настройке договоров... однако хотелось бы качества.
Очень трудно объяснить директору магазина, что данный календарь работает как он работает и для полной картины нужен блок **"Бухгалтерия"**

![image](https://cloud.githubusercontent.com/assets/11478712/21819749/077fe0b4-d77e-11e6-834f-76e8e45457af.png)

P.S. Если нужна документация для работы с данной формой, могу своять. Мне не жалко, а другим будет полезно.

**Comment by gsbelarus** [comment]
Это не оно?

http://gsbelarus.com/pw/articles/post/platezhnyi-kalendar-upravlencheskii-uchet-na-platforme-gedymin/

Внизу там и ссылка на документацию.

**Comment by MAliaksandr** [comment]
Похоже на то, что оно самое. За исключением функционала. Видно он куда-то затерялся. Гляньте эталон. Или я чего-то не вижу?

**Comment by MIchaelShoihet** [comment]
Это отдельная настройка, которая разрабатывалась для бройлеров, но ей так и не пользовались. Та что идет в стандарте, она примитивна и идет как бонус... В любом случае полноценный платёжный календарь это отдельная задача, причем в общем случае достаточно сложная.

**Comment by MIchaelShoihet** [comment]
Даже нет, то что описано это экспериментальная версия для других клиентов... То же не стали пользоваться. Я работаю над одной из версий плат.календаря но в очередной раз вижу, что в общем виде достаточно сложная задача. Предварительную версию могу показать при случае.

**Comment by MAliaksandr** [comment]
Отлично! И все таки с тем что есть надо либо что-то сделать(в виде мелких доделок:итогов,отчетов), либо убрать вообще, чтобы не ломать психику клиентов)

**Comment by MIchaelShoihet** [comment]
Мелкие доделки делать не имеет смысл. Лучше тогда убрать.

**Comment by MAliaksandr** [comment]
Тогда убираем с эталона и снимаем вопрос до релиза адекватного календаря

**Comment by MIchaelShoihet** [comment]
Но полноценный платёжный календарь будет работать по хорошему только на комплексной автоматизации.

**Comment by gsbelarus** [comment]
Я переоткрою, пока не будет решено.

**Comment by alexandra-gsoftware** [comment]
я выкидываю существующую версию из КА

**Comment by MIchaelShoihet** [comment]
да

**Comment by gsbelarus** [comment]
конечно. ломать не строить.

**Comment by alexandra-gsoftware** [comment]
ну не скажите. Сломать так, чтобы остальное не сломалось, достаточно сложно...)

**Comment by alexandra-gsoftware** [comment]
ой, в этом гитхабе еще и лайки есть. Ужас.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
