### ISSUE TITLE
Не синхронизируется номер документа между позициями и шапкой

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3904]
@kovli пишет:

Столкнулся с интересной ситуацией. Клиент строит карточку движения по позиции складского документа и в карточке в качестве номера документа видит Мядель. Стали смотреть этот документ, оказалось в шапке номер один, а в позициях - другой. Но есть же триггер **GD_AU_DOCUMENT**, который, собственно и приводит в соответствие ряд полей шапки и позиций, в том числе и номер документа. Т.е. такой ситуации случиться не должно. А вот запрос
```
Select
dt.name,
d.number as dh_number,
dl.number as dl_number,
dl.*
from gd_document d
join gd_document dl on dl.PARENT = d.id
left join gd_documenttype dt on dt.id = d.documenttypekey
where dl.NUMBER <> d.number and dt.id <> 800300
```
выдал кучу записей, что говорит о наличии проблемы в базе. Никто не сталкивался с подобным?

**Comment by NikolayUkleyko** [comment]
> выдал кучу записей, что говорит о наличии проблемы в базе. Никто не сталкивался с подобным?

Сталкивался. Такое видел редко и особенно на винтажных БД (Береза МКК).

> Т.е. такой ситуации случиться не должно.

Абсолютно с Вами согласен. Нездоровая ситуация.

> Но есть же триггер GD_AU_DOCUMENT

Чего у нас только нет.

**Comment by alexandra-gsoftware** [comment]
>>> Но есть же триггер GD_AU_DOCUMENT

мне кажется, этот триггер меняет номер у позиций при изменении номера в шапке. А потом можно спокойно поменять номер в позиции.

**Comment by alexandra-gsoftware** [comment]
да, проверила, так и есть, так всегда было....

**Comment by gsbelarus** [comment]
Я закрою. Так всегда работало. Лишняя проверка потребует выполнение запроса, что скажется плохо на производительности.
