### ISSUE TITLE
удаление объекта, на который есть ссылки, при установке ПИ

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3905]
Только что столкнулась с такой ситуацией. Грузится ПИ. Гедымин пытается удалить какой-то устаревший объект. Вылазит окошко, говорящее, что на объект ссылаются другие объекты. Там же список этих ссылок, с возможностью их  удалить. Удаляю их. Остается висеть само окошко с пустым списком зависимостей. Сам объект удалить из него нельзя.  Если бы я удаляла объект из его формы просмотра, то я бы закрыла окошко зависимостей и попробовала бы удалить снова. Но сейчас происходит установка ПИ. Закрываю окошко. Установка ПИ прерывается. Смотрю лог в Гедымин контрол центре. Никаких сообщений об ошибке. Просто "загрузка завершена".

Может, как-то переделать этот момент? Или загрузку, или окно с зависимостями, или и то и другое?

**Comment by gsbelarus** [comment]
Не только можно, но и нужно.

**Comment by NikolayUkleyko** [comment]
@alexandra-gsoftware , это случаем не Береза МКК и ОС ?

**Comment by alexandra-gsoftware** [comment]
>>> это случаем не Береза МКК и ОС ?

да, именно))

**Comment by YRozmysl** [comment]
точно с такой же проблемой сталкивался  при обновления пакета ПИ. Ей решили в последнем exe. По крайнем  мере, в моем случае разрешилось.

**Comment by gsbelarus** [comment]
@alexandra-gsoftware решилась проблема? проверить
