### ISSUE TITLE
Интервал дат для ТП

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3906]
1. Добавить в **AT_TRRECORD** два необязательных поля ссылки на таблицу **GD_CONST**: cdbkey, cdekey. Добавить поля в соответствующее диалоговое окно.
2. Первое -- дата начала действия типовой проводки. Второе -- дата окончания.
3. Дата берется из поля **documentdate** записи, для которой формируется проводка. Т.е. для сложного докумена, для шапки -- берется из записи шапки. Для каждой позиции -- из соответствующей записи позиции.
4. Ссылки на константы типа Дата.
5. Если оба поля не заполнены, то ТП проводка формируется (если она не отключена).
6. Если заполнено только поле cdbkey, проводка формируется начиная с указанной даты.
7. Если заполнено только поле cdekey, проводка формируется до указанной даты.
8. При сравнении используются операции >=, <=. Временная часть отбрасывается.
9. Отразить изменение структуры таблицы в wiki.
10. Проверить: а) формирование проводок, попадающих в заданный период. б) Неформирование проводок, не попадающих. в) Создан документ, сформированы проводки. Меняем дату документа так, что она не попадает в заданный интервал -- проводки должны исчезнуть. г) Создан документ, по нему нет проводок, так как они не попадают в интервал. Меняем дату документа так, чтобы он попал в интервал -- проводки должны появиться. д) создан документ с проводками. Меняем интервал в ТП и перепроводим проводки. Проводки должны исчезнуть. е) создан документ без проводок. Меняем интервал ТП и перепроводим. Проводки должны появиться.
11. интервал дат должен кэшироваться. Чтобы система не лазила в базу данных каждый раз, когда будет проводиться ТП. Это будет слишком накладно по времени.

Если @MIchaelShoihet не будет возражать, то можно приступать.

**Comment by MIchaelShoihet** [comment]
А зачем ссылка на константу? Может просто период в типовую проводку добавить? Не усложняем ли мы этим? Я если честно даже не совсем представляю как будет это использоваться?

**Comment by gsbelarus** [comment]
Некоторые говорят что без этого прямо невозможно жить.

ТП, зависящих от даты может быть много, поменял в одной константе и везде отразилось сразу.

**Comment by MIchaelShoihet** [comment]
Посовещались и решили все-таки просто добавить дату начала и дату окончания в таблицу AC_TRRECORD. Все остальное как описано выше можно делать.

**Comment by ShlTanya** [comment]
Принято

**Comment by ShlTanya** [comment]
Можно ли уточнить, что Вы имеете в виду под понятием "сложный документ" :
- документ, имеющий 1 "детайл", а позиции - это строки в документе-позиции
или
- документ, имеющие несколько детайлов.

**Comment by gsbelarus** [comment]
Шапка и несколько позиций (в частном случае может быть и ноль, и одна).

**Comment by NikolayUkleyko** [comment]
Необходимо уточнить следующее.

1.
> Первое -- дата начала действия типовой проводки. Второе -- дата окончания.
Если оба поля не заполнены, то ТП проводка формируется (если она не отключена).
Если заполнено только поле cdbkey, проводка формируется начиная с указанной даты.
Если заполнено только поле cdekey, проводка формируется до указанной даты.

На практике достаточно одного поля **Дата**. Обычно, с даты >= действует такой-то набор проводок (новый), иначе - другой (прежний).
Я не вижу большой потребности в 2-х параметрах типа *Дата*.

2.
> Проверить: а) формирование проводок, попадающих в заданный период. б) Неформирование проводок, не попадающих. .... Меняем интервал в ТП и перепроводим проводки. Проводки должны исчезнуть. е) создан документ без проводок. Меняем интервал ТП и перепроводим. Проводки должны появиться.

Как в данном случае будет реализован механизм перепроведения проводок: достаточно нажатия кнопки **Провести проводки по документу** или еще надо будет запустить макрос типа **Перепровести количество** ?

**Comment by ShlTanya** [comment]
1. Обычно - не значит всегда. А вдруг надо будет реализовать ситуацию.. когда совсем не проводятся проводки.
2. Достаточно кнопки Провести проводки по документам.

**Comment by gsbelarus** [comment]
Делаем **ДВЕ ДАТЫ**. Как описано в постановке.

**Comment by gsbelarus** [comment]
Единственная корректировка, которую внесли -- вместо ссылок на константы две непосредственных даты. 

Поля:

```
...
dbegin  ddate,
dend  ddate,
...
ALTER TABLE at_trrecord ADD CONSTRAINT at_chk_trrecord_date
  CHECK ((dbegin IS NULL) OR (dend IS NULL) OR (dbegin <= dend))
...
```

Хотя, я считаю, что вариант с константами более гибок и позволит группе ТП назначить период и легко менять его в одном месте, вместо того, чтобы лазить по каждой ТП и менять для нее одной.

**Comment by gsbelarus** [comment]
Берите новейший экзешник. Тестируйте.
