### ISSUE TITLE
Общее. Ограничить одновременное подключение к БД с gedemin.exe разных версий

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3907]
На практике довольно часто встречаются ситуации, когда к одной БД пользователи подключаются с разных gedemin.exe.
Это они могут делать по незнанию и потому, что местные специалисты корректно не настроили всем пользователям работу с **единого** gedemin.exe.
Порой это может привести к некоторым поломкам в БД (интервальные деревья) и другим нежелательным последствиям.

Для решения данного вопроса предлагаю следующее:

**1. Сервис / Параметры / Аудит и безопасность**.
Добавить реквизит **Запретить одновременное подключение к БД gedemin.exe разных версий**.
Проставив галку по данному реквизиту, при попытке подключения к БД с gedemin.exe более старой версии по отношению подключения новейшего gedmin.exe на экране пользователя будет отображено окно с соответствующим сообщением и блокировка конечного подключения.

**2. База данных / Подключенные пользователи**.
В форму добавить колонки с отображением версии и даты релиза gedemin.exe.
Так будет проще выявить некорректное подключение к БД.
Потом, выполнить настройку корректного подключения через единый gedemin.exe.

----

По-умолчанию значение данного реквизита **False**.
Важно предусмотреть рассматриваемый здесь механизм **настраиваемым**.
Делать по-умолчанию жесткий запрет нельзя.

**Comment by YRozmysl** [comment]
Полностью поддерживаю.

**Comment by alexandra-gsoftware** [comment]
да.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by kovli** [comment]
Да, надо сделать. А то может быть совсем плохо. Сейчас вот конструктор проводок сделали дата-зависимым. Чувствительным к дате проводки. Если им пользоваться и работать со старым EXE, то могут быть задвоенные проводки. Это совсем плохо и трудно отыскивается. Или как-то дайте возможность из скрипта получить версию запущенного EXE-шника. Дальше мы сами вычислим негодяев.

**Comment by ShlTanya** [comment]
Пункт 1. Ограничение запуска программы не совсем хороший вариант. Возможно изменение Exe-шника без существенных изменений, влияющих на работу. И не всегда есть в нужный момент сисадмин, готовый заменить файл.

Пункт 2. Хороший вариант. 
Для его реализации можно использовать **Журнал событий**. Сейчас в нем регистрируется событие Log on (с почти всей необходимой информацией). Но д.б. соотв. настройки в Опциях системы и у пользователя. Как вариант, можно выделить регистрацию входа-выхода пользователя отдельным параметром в Опциях системы (без привязки к пользователю). С определенными доработками можно будет получить текущую версию Exe-шника в **Подключенных пользователях** и плюс возможность увидеть историю подключений в Журнале событий.

**Comment by NikolayUkleyko** [comment]
>Пункт 1. Ограничение запуска программы не совсем хороший вариант....

Спорный вариант.
Если, один раз выполнили корректную настройку, то преимущественно не потребуется старый gedemin.exe.

>Пункт 2. Хороший вариант.
Для его реализации можно использовать Журнал событий....

Журнал событий увеличивает размер БД.
Отчасти это может сказаться на скорости работы БД.
К тому же потребуется проанализировать записи в Журнале событий.
Это время и не так наглядно, как было бы гораздо нагляднее в окне Подключенных пользователей.

**Comment by stasgm** [comment]
А что понимается под "старым" gedemin.exe? У нас каждую неделю идёт сборка exe файла.

**Comment by stasgm** [comment]
На скорость работы Гедымина журнал никак не повлияет. Если, конечно, не подключить просмотр журнала из всех документов

**Comment by YRozmysl** [comment]
Тут  суть не "старый - новый", а в том, чтобы все работали с одного и того же exeю И в том, чтобы оперативно  все это видеть в **Подключенные пользователи**

**Comment by NikolayUkleyko** [comment]
>А что понимается под "старым" gedemin.exe? У нас каждую неделю идёт сборка exe файла.

@stasgm , реально на крупных промышленных комбинатах (МК) в отличие от мелких торговых и общепитовских препдриятий бардак в части файлов Гедымина (exe и прочие), Firebird на сервере.

**Comment by kovli** [comment]
А может сделать так. Запускается самый первый Гедымин. Он вычисляет свою версию (версия EXE-шника) и записывает ее (версию) в спец.табличку.  Запускается второй или  очередной Гедымин. Он сравнивает свою версию с версией в той спец.табличке. Если его версия меньше, то он выдает сообщение пользователю, что в системе есть версии более свежие и советует обратиться к сисадмину. Дальше можно продолжать работу этого старого EXE-шника или прекратить ее (нужно пообсуждать реакцию).  И все. Простенько и надежно.

**Comment by kovli** [comment]
Да, забыл еще. Если версия очередного запущенного Гедымина больше, чем версия в спец.табличке, то он ее (версию) обновляет своей. Таким образом в этой спец.табличке будет храниться максимальная версия, т.е. самого свежего EXE-шника.

**Comment by kovli** [comment]
Можно еще в то спец.табличке хранить дату записи версии. И дать пользователю, работающему со старой версией, фору дней на 5. Если в течении 5 (или сколько придумаем) дней он не заменил EXE-шник, то принудительно завершать работу старого EXE.

**Comment by ShlTanya** [comment]
1. Важно знать какой пользователь, когда, с какой машины и с какого каталога запускал программу. Для таких целей необходимо хранить историю подключений(хотя бы за какой то период), т.е. по сути делать такую же таблицу как журнал операций. Можно ограничить период хранения подключений. 
2. Можно реализовать оповещение пользователей о более новой версии в сети.

**Comment by kovli** [comment]
А для чего "Важно знать какой пользователь, когда, с какой машины и с какого каталога запускал программу"?  Как я понимаю, нужно добиться того, чтобы все пользователи работали с одним EXE. Одной версии. Пусть и не самой современной, но с одной. Меньше знаешь - крепче спишь.

**Comment by ShlTanya** [comment]
А если в данный момент не запущена программа. Как узнать что там плохо.

**Comment by YRozmysl** [comment]
@kovli  Совершенно верно! Тут не важно хранить все эти вещи и знать   что, где , когда. Нужно добиться того, чтобы все пользователи работали с одним EXE  У нас же не следственное бюро.

**Comment by kovli** [comment]
А если не запущена программа, то и проблем нет. Как начнут работать, так и увидим проблемы.

**Comment by YRozmysl** [comment]
Как правило узнается, что плохо спустя время, 1-3 месяца, Когда что-то делалось сторонним exe, после чего приходится разгребать авгиевы конюшни.

**Comment by kovli** [comment]
А чем старый EXE-шник может нагадить в базе? Новые EXE-шники, как я понимаю, приводят к созданию новых таблиц, новых полей в таблицах. Может, поддерживают новые бизнес-процессы, классы и т.д. Старый просто не будет работать с новыми структурами. Что он может нагадить? Я не сталкивался с такой проблемой, хотя не все мои работают с одним EXE. Вот с последней версией появились новые поля (долгота, широта), обработка которых попала в новые настройки и старые EXE просто не смогли работать, т.к. в таблицах не оказалось новых полей. Настройки не загрузились.

**Comment by stasgm** [comment]
После раздумий я пришёл к выводу, что доработка gedemin.exe не требуется.
Выход такой.

1. Заводится юзерская таблица, например,USR$LOGINFO со следующими полями 
- дата\время входа в систему 
- ip\имя компьютера
- Версия гедымина
- Путь к gedemin.exe

2. Перекрывается метод frmGedeminMainOnCreate в котором идёт заполнение вышеуказанных данных в таблицу.

**Comment by gsbelarus** [comment]
Не надо так усложнять простой вопрос. Есть автообновление в экзешнике, есть
сисадмины на предприятии.

Не тратьте дорогое время на ерунду. Максимум что можно предложить в пи
добавить мин версию экзе и если она не соблюдается, то блокировать загрузку
программы и давать инструкции как обновить.

Пожалуйста, есть первоочередные, горящие задачи, а таких мелочей можно
придумать миллион и тысячи жизней не хватит их реализовать.

С чего все началось? С какого предприятия и вопроса? Может это единичный
частный случай из-за которого не стоит городить огород.

On Apr 21, 2017 16:51, "Stanislau Shliakhtsich" <notifications@github.com>
wrote:

После раздумий я пришёл к выводу, что доработка gedemin.exe не требуется.
Выход такой.

   1. Заводится юзерская таблица, например,USR$LOGINFO со следующими полями


   - дата\время входа в систему
   - ip\имя компьютера
   - Версия гедымина
   - Путь к gedemin.exe


   1. Перекрывается метод frmGedeminMainOnCreate в котором идёт заполнение
   вышеуказанных данных в таблицу.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoldenSoftwareLtd/gedemin/issues/3907#issuecomment-296212740>,
or mute the thread

**Comment by NikolayUkleyko** [comment]
>Максимум что можно предложить в пи
добавить мин версию экзе и если она не соблюдается, то блокировать загрузку
программы и давать инструкции как обновить.

Просто и понятно.

**Comment by NikolayUkleyko** [comment]
Просто добавьте в окно подключенных пользователей версию gedemin.exe без блокировок и этого будет достаточно.

**Comment by kovli** [comment]
И добавьте возможность получения из скрипта номера текущей версии Gedemin.exe. Типа IbLogin.CurrentExeVersion.

**Comment by ShlTanya** [comment]
В подключенных пользователях отображается информация о пользователях самого Fireberda. Для того, чтобы туда добавить еще и информацию о версии Гедемина.. надо ее как минимум записать в базу.. поэтому и предлагала вариант Журнал событий. Но не учла, что работать будет только на обновленном экзе. 

Поэтому вариант получения номера текущей версии из скрипта более оптимальный в данной ситуации. Пример, как сейчас можно ее получить (на стороне клиента):

Function ApplVersion

dim FPath, FSO, FV, FD, F
FPath = Application.ExeName
Set FSO = CreateObject("Scripting.FileSystemObject")
Set F = FSO.GetFile(FPath)

FV = FSO.GetFileVersion(FPath)
FD = F.DateLastModified

MsgBox(FV & " от " & FD)

End Function

**Comment by kovli** [comment]
За скрипт большое спасибо! Дальше мы сами вычислим негодяев!

**Comment by kovli** [comment]
А как из скрипта завершить работу Гедымина? Вот запустили Гедымин, проверили версию EXE, нам она не понравилась и нужно текущий Гедымин закрыть.

**Comment by MIchaelShoihet** [comment]
Application.terminate

3 мая 2017 г. 10:20 ДП пользователь "kovli" <notifications@github.com>
написал:

**Comment by gsbelarus** [comment]
В журнал событий версия пишется и сейчас, если установлено в параметрах Гедымина **Регистрировать действия** пользователя и соответствующая галка установлена для учетной записи пользователя.

Для того, чтобы ее извлечь придется в окне со списком пользователей, для каждого выполнять запрос к журналу. Это замедлит работу.

Если писать информацию о версии всегда и для каждого пользователя -- это тоже замедлит работу.

Т.е. мы решаем локальную проблему, возникшую у какого-то конкретного одного клиента, но начнем замедлять работу всем остальным ни в чем не повинным.

Может проще включить автообновление экзешника?

**Comment by kovli** [comment]
А если рабочее место не подключено к интернету? Что даст автообновление? Да и каждая новая версия EXE - это кот в мешке. Сейчас, правда, получше, но все равно, нужно самому потестировать, прежде чем предложить пользователю.

**Comment by NikolayUkleyko** [comment]
>Может проще включить автообновление экзешника?

OK !

**Comment by NikolayUkleyko** [comment]
**_База данных / Подключенные пользователи_**.

Просто добавьте в окно подключенных пользователей **информационное отображение версии gedemin.exe без блокировок**.
Это же не должно сказаться на быстродействии работы программы.

@gsbelarus  , пожалуйста, изложите Вашу точку зрения ?

**Comment by gsbelarus** [comment]
Так ее там просто не откуда взять.
