### ISSUE TITLE
Общее. После отмены глобальной блокировки данных и ее активации не сохраняется дата блокировки (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3908]
**Сервис / Параметры / Аудит и безопасность**.

После отмены глобальной блокировки данных и ее активации не сохраняется до этого веденная дата блокировки.
По умолчанию дата становится равной 10.10.2003. ???
В случае временного отключения блокировки это крайне неудобно.

![2017-01-20_135428](https://cloud.githubusercontent.com/assets/11497453/22147123/42beb44c-df18-11e6-80c0-8ab0bcb9fdd3.png)

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
@DonPhantom000 , пожалуйста, посмотри.

**Comment by DonPhantom000** [comment]
Теперь сохраняется

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@DonPhantom000 , спасибо !
