### ISSUE TITLE
Ошибка модифая на СМК новым exe

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3909]
На тестовой базе СМК при модифае последним exe  возникает ошибка
![default](https://cloud.githubusercontent.com/assets/11507129/22248522/fee755c2-e24f-11e6-8dc3-41b04864be53.jpg)

**Comment by gsbelarus** [comment]
А точно под 3 фб идет модифай?

**Comment by YRozmysl** [comment]
Странно, судя по всему тот exe, который у их на рабочем столе запускается под 2.5  Возможно из-за этого и проблема.

**Comment by YRozmysl** [comment]
На Гомельобоях тестовой тоже самое, и  тоже модифай идет  под 3 фб

**Comment by YRozmysl** [comment]
на вкл новая база смк, можете экспериментировать

**Comment by NikolayUkleyko** [comment]
Скорее всего проблема именно в разных версиях FB.

**Comment by YRozmysl** [comment]
На базе гомельобоях тестовой под фб 3.0 при модифае на самом последнем exe вот такие вот вещи
![1](https://cloud.githubusercontent.com/assets/11507129/22560373/62c757cc-e985-11e6-8c19-eca0cbb856f5.jpg)
![2](https://cloud.githubusercontent.com/assets/11507129/22560383/68cbe390-e985-11e6-9041-e4ade9d58e42.jpg)

**Comment by YRozmysl** [comment]
На последнем exe вопрос решился положительно.
