### ISSUE TITLE
Ошбка в Control Center при синхронизации

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3910]
При синхронизации ПИ (не загрузки) сразу возникает ошибка на новом exe.
Повторить можно просто, выбрав, например, D:\golden\gedemin-apps\  и нажать синхронизация.
![1](https://cloud.githubusercontent.com/assets/11507129/22413822/049e9ffe-e6cc-11e6-86a2-1080129a32d6.jpg)

**Comment by NikolayUkleyko** [comment]
На Береза МКК аналогичная ошибка при загрузке ПИ по ОС.
По итогу ПИ установлены успешно.

**Comment by YRozmysl** [comment]
Да, на установку это не повлияет, просто это окно вываливается каждый раз когда грузится очередное пи

**Comment by gsbelarus** [comment]
Сейчас гляну.

**Comment by YRozmysl** [comment]
Если грузит пакетом, то она раз 50 будет (50 пространств)
