### ISSUE TITLE
перемещение объектов из одного пи в другое

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3911]
мы можем в форме просмотра ПИ выделить несколько позиций, нажать "редактировать" и выбрать другое ПИ. Можно ли сделать так, чтобы в новое ПИ они переместились в том порядке, в каком следуют в исходном ПИ (т.е. в соответствии с objectpos) ?

**Comment by YRozmysl** [comment]
Да, такая некорректность имеет место быть. Хорошо, что есть отчет неверных последовательностей в котором  неверные последовательности сразу и обнаружились.

**Comment by gsbelarus** [comment]
Я могу при переносе группы объектов сохранять их относительный порядок и
помещать в конец списка в новом пи. Это имеется ввиду?

**Comment by YRozmysl** [comment]
Это и имелось ввиду
