### ISSUE TITLE
Бухгалтерия. Отображение нулевых сумм в сложной проводке

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3912]
**Исследователь / Бухгалтерия / Журнал-ордер, Карта счета, Анализ счета, Журнал хоз. операций и т. д.**

Например, создана сложная проводка (два и более счета по дебету и один счет по кредиту, или наоборот):

Дт  |  Кт | Сумма
------------ | ------------- | -------------
10....            | 60....              | Сумма без НДС
18....            |                      | Сумма НДС

В случае, если поле **Сумма НДС** не заполнено, то и не формируется проводка на НДС.
Это видно в гриде проводок по текущей записи документа.
Хотя, проводка со счетом НДС (18....) на **нулевую сумму** отображается, как в Журнале-ордере, Карте счета, Анализе счета, в Журнале хоз. операций и в других формах.

Это так задумано ?

На мой взгляд нелогично получается: реально существуют одни данные, а отображаются еще и ненужные нулевые.
Порой это усложняет анализ данных.

С другой стороны - простые проводки (один счет по дебету и один счет по кредиту) работают корректно.
То есть, не отображают счетов на нулевые суммы.

@MIchaelShoihet , пожалуйста, изложите, Вашу, точку зрения.

**Comment by MIchaelShoihet** [comment]
Простые проводки с 0 суммами не сохраняются. В сложной проводке сохраняются все ее части, даже с нулями и мне кажется что ничего страшного в этом нет. Более того видно, что проводка формируется правильно.

**Comment by MIchaelShoihet** [comment]
Если в сложной проводке общая сумма = 0 то она то же не сохранится. И нигде не будет отображаться

**Comment by NikolayUkleyko** [comment]
Тему закроем.
Но, пожалуйста, еще раз взгляните на нулевые суммы:

![2017-02-02_105438](https://cloud.githubusercontent.com/assets/11497453/22541310/aa1cd02e-e936-11e6-9a4e-de884fd4f5ce.png)

![2017-02-02_105521](https://cloud.githubusercontent.com/assets/11497453/22541311/aa3893ae-e936-11e6-8072-73ef9c724fde.png)

![2017-02-02_105638](https://cloud.githubusercontent.com/assets/11497453/22541312/aa46c942-e936-11e6-8b3c-1d8fa861e80c.png)

По-хорошему, нули не нужны.
Я предполагаю, что при желании это решаемо.
Но, не будем.

**Comment by MIchaelShoihet** [comment]
Я писал про саму проводку. А в отчетах это надо поправить.

**Comment by MIchaelShoihet** [comment]
Поэтому открыл еще раз.

**Comment by NikolayUkleyko** [comment]
> А в отчетах это надо поправить.

То есть, и в форме Журнала хоз. операций не будут отображаться нулевые значения ?

**Comment by MIchaelShoihet** [comment]
Нет в самом журнале будет отображаться, то что есть в базе. А в отчетах нулевые суммы не нужны.

**Comment by NikolayUkleyko** [comment]
> Нет в самом журнале будет отображаться, то что есть в базе. А в отчетах нулевые суммы не нужны.

Отлично.
Тогда, не будем откладывать в долгий ящик данный немаловажный вопрос.

**Comment by NikolayUkleyko** [comment]
Попутно можно поправить и это
https://github.com/GoldenSoftwareLtd/gedemin/issues/3896

**Comment by NikolayUkleyko** [comment]
В бухгалтерских отчетах по-прежнему отображаются проводки на нулевые суммы по сложным проводкам.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
Изменений на gedemin.exe

Дата файла = 01.05.2017
Версия файла = 2.9.3.9100

не выявлено.

**Comment by NikolayUkleyko** [comment]
Еще раз сталкиваюсь с данной проблемой на Витебск МК.
Приходится перенастраивать типовые проводки со сложных на простые.
Тема-то, очевидная и актуальная.

**Comment by NikolayUkleyko** [comment]
Благодарю за беседу, @MIchaelShoihet !
