### ISSUE TITLE
Пропало свойство FirstColumn у CheckBox грида

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#3913]
Куда-то пропало свойство FirstColumn у CheckBox грида

В коде использовать нет возможности
![image](https://cloud.githubusercontent.com/assets/8355925/22520562/d9fa8456-e8c5-11e6-9e3f-8b55edc86c05.png)

А в дизайнере есть
![image](https://cloud.githubusercontent.com/assets/8355925/22520586/f0bb7038-e8c5-11e6-9d99-d56bfb355fd9.png)

**Comment by gsbelarus** [comment]
Не могло пропасть то, чего не было. Но теперь будет.

**Comment by alexandra-gsoftware** [comment]
вроде было, и из кода доступно было....
