### ISSUE TITLE
Action для SpeedButton

### ISSUE THREAD

**Issue by PiuPauTralala** [GoldenSoftwareLtd/gedemin#3914]
По клику не заходит в action, привязанный к speedbutton.
Тот же action на BitBtn отлично работает.  
Что делаю не так?

**Comment by gsbelarus** [comment]
Кинул на форму TSpeedButton. Выбрал Action. Проверяю -- все срабатывает нормально.

**Comment by PiuPauTralala** [comment]
Значит, глюк какой-то был.
