### ISSUE TITLE
невозможно добавить объект в ПИ

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3915]
есть простая таблица с полями USR$CODE, USR$NAME. Оба НЕ имеют атрибут not null. 

В таблице есть несколько записей. Поле USR$CODE заполнено, поле  USR$NAME - нет. Выделяем несколько записей, пытаемся добавить в ПИ, получаем ошибку "Internal error."

Пытаемся добавить одну запись в ПИ, получаем ошибку "Поле "OBJECTNAME" ("AT_OBJECT"."OBJECTNAME") должно быть заполнено."

Делаем поле USR$CODE Required через CreateFields. Переподключаемся. Ошибка остается.

В Таблицах указываем в качестве поля для отображения USR$CODE. Переподключаемся.
Теперь одну запись можно добавить в ПИ, но если попробовать добавить сразу несколько, опять получим "Internal error."

Проверяем другие БО. При попытке добавить в ПИ несколько записей одновременно получаем  "Internal error."

1. Почему система не сгененрировала сама имена для объектов пи?
2. Можно ли что-нибудь сделать с этой internal error?

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by gsbelarus** [comment]
Более понятное сообщение об ошибке надо показывать.

**Comment by gsbelarus** [comment]
Для объектов, которые идут в ПИ желательно наличие поля с именем. Обязательно заполненного.

**Comment by gsbelarus** [comment]
@alexandra-gsoftware проверьте на новейшем экзешнике.

**Comment by NikolayUkleyko** [comment]
> _...поле USR$NAME - нет..._

Важное заполнять поля типа **NAME**.

**Comment by NikolayUkleyko** [comment]
При добавлении записей в ПИ из таблиц без полей типа **NAME** можно ли вручную выбрать другое(ие) поле(я) таблицы для заполнения поля **Наименование** ?

**Comment by NikolayUkleyko** [comment]
Проверено.
Сейчас при добавлении в ПИ записей с данными программа выполняет проверку на наличие подходящего наименования.
Пример.
При отсутствии заполненного поля типа **NAME** программа добавляет в ПИ запись следующим образом →
**_локализованное наименование таблицы_**, **_RUID записи_**:
```ruby
Тестовая таблица, РУИД: 149293878_1153275497
```

@Polfath , спасибо !
@gsbelarus , пожалуйста, закройте тему.
