### ISSUE TITLE
TFilesFrame - можно ли сделать его доступным в скриптах?

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3918]
TFilesFrame используется для сравнения текстов (например, на панели истории ф-й). 
Сделайте его доступным из скриптов и редактора форм, плз.

**Comment by ShlTanya** [comment]
Александра, я добавила в редактор форм на палитру Дополнительно.

**Comment by ShlTanya** [comment]
И в скриптах уже доступен

**Comment by alexandra-gsoftware** [comment]
мерси @ShlTanya !

**Comment by alexandra-gsoftware** [comment]
спасибо, все работает! можно еще сделать доступным в скриптах его методы поиска FindClick, FindNextClick и класс TCodeEdit ? (но это совершенно не срочно, если время будет)

**Comment by ShlTanya** [comment]
Александра, для каких целей класс TCodeEdit. Остальное доделала.

**Comment by alexandra-gsoftware** [comment]
да можно без него,  спасибо! Остальное завтра проверю.

**Comment by alexandra-gsoftware** [comment]
Спасибо, поиск работает, только выделяет как-то странно (я меняла размеры шрифта. может поэтому). На картинках: искалось слово "upper":
![find1](https://cloud.githubusercontent.com/assets/11487200/23669599/ccbc1a6e-0375-11e7-914b-5420e0c94b6f.png)
![find2](https://cloud.githubusercontent.com/assets/11487200/23669602/ce59286c-0375-11e7-8534-96f9ecb5a37d.png)

**Comment by ShlTanya** [comment]
Действительно странно. Я проверю что может быть.

**Comment by alexandra-gsoftware** [comment]
я пользовалась вот так:

```
        dim pnl
        set pnl = frm.GetComponent("usrg_FilesFrame")

        call pnl.Setup
        call pnl.Compare(SFu, SHi)
        pnl.Components(14).Font.Size = 10
        pnl.Components(15).Font.Size = 10
        pnl.GetComponent("pnlCaptionLeft").Caption = CFu
        pnl.GetComponent("pnlCaptionRight").Caption = CHi
```

Может, чего-то не хватает?
В любом случае, еще раз большое спасибо, @ShlTanya !

**Comment by gsbelarus** [comment]
Шрифт обязательно должен быть моноспейс. Например Courier New и т.п.
