### ISSUE TITLE
В диалоговых окнах применяются значения ИД удаленных записей

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3919]
> У меня частенько возникает ошибка типа "Нарушение ссылочной целостности. Внешний ключ "USR$FKGD_DOCUMENT592" в таблице "GD_DOCUMENT"
> Foreign key reference target does not exist
> Problematic key value is ("USR$MGAZ_CALCUL" = 21)". В чем причина. У пользователя установлен режим "Сохранять значения полей в диалоговых окнах". Как я понимаю, в этом случае в режиме диалога в процессе создания новой записи в поля документа заносятся сохраненные ранее значения этих полей из хранилища. Каким-то образом (каким?) так получилось, что в хранилище сохранилась ссылка на несуществующий объект - внешний ключ. Возможно, объект был объединен с его аналогами, позиция справочника была удалена, а ссылка на эту позицию осталась в хранилище. Т.е. в процессе создания новой записи вполне возможна ситуация, когда в поле стоит ссылка на несуществующий объект. Почему-то в этот момент не срабатывает защита на наличие ссылочной целостности. Она сработает на методе Post этой записи. Что и вызовет сообщение об ошибке. Беда еще в том, что пользователь не видит неверное (аварийное) значение в поле документа, т.к. ссылка то есть, но значение внешнего объекта в поле не отображается (объекта же нет). Как в таком случае можно доработать функционал (на уровне методов документа или EXE), чтобы он обнаруживал такие аварийные ситуации?

**Comment by alexandra-gsoftware** [comment]
ИДшник сохранился после Ctrl + Alt + E в форме.
Да, это известная проблема, лучше вообще не сохранять значение ссылок.

**Comment by gsbelarus** [comment]
А где он мог сохраниться по Ctrl + Alt + E? Я имею ввиду в каком свойстве какого компонента?

**Comment by alexandra-gsoftware** [comment]
Уже не помню, давно такое видела, у меня везде эта галочка снята. 
И вот, в примере странно такое: Problematic key value is ("USR$MGAZ_CALCUL" = 21)"
"21" не похоже на идшник, даже удаленный.

**Comment by gsbelarus** [comment]
Проверил. Повторить не могу.
