### ISSUE TITLE
Ограничение в параметре типа Множество ссылок

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#3920]
Если в отчет добавлен параметр типа "Ссылка на элемент", то в поле "Таблица" для этого параметра мы можем указать что-то типа 
`gd_contact c join gd_contact cp on cp.id = <RUID XID = "147052176" DBID = "2033878884"/>`
При этом все будет работать.
Если что-то подобное сделать для параметра типа "Ссылка на множество", то при попытке заполнить такой параметр в отчете получим ошибку 
![error](https://cloud.githubusercontent.com/assets/11484894/22881835/51d89008-f1f9-11e6-9d4c-60a5c49f691e.jpg)

**Comment by alexandra-gsoftware** [comment]
Да, для параметра Множество свои правила построения запроса, хитрые и нелогичные. Например, в запросе таблица получает алиас gg1 (не спрашивайте, почему)
Обходится так:
Таблица: gd_contact
Поля: id, name
Условие: ID IN (тут любой запрос)
или
EXISTS( SELECT * FROM GD_CONTACT c......... WHERE c.ID = gg1.ID)

**Comment by gsbelarus** [comment]
Тогда трогать пока ничего не надо. Тронем -- еще перестанет работать то, что работает сейчас.

**Comment by alexandra-gsoftware** [comment]
добавьте это в описание paramwindow, плз.

**Comment by ShlTanya** [comment]
Посмотрела код. Для построения формы множественного выбора **важно**, чтобы в поле "Таблица" было чистое название таблицы, которому присваивается алиас gg1. Поэтому правильный вариант Александры.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by gsbelarus** [comment]
"добавьте это в описание paramwindow, плз."

сделать это и можно закрывать. или кнопку Справка, которая будет вести на страницу wiki  с описанием.

**Comment by gsbelarus** [comment]
Добавлено:

http://gsbelarus.com/gs/wiki/index.php/GetNewParamWindow
