### ISSUE TITLE
Скорректировать печатные формы приходного кассового ордера.

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#3921]
1) Как я упоминал в issue #3919, если написано в форме подписи "фио", то выводить фио из полей sure name firsname middlename, а не gd_contact.name.

2) Не влазит в правой части ПКО фио в поле "Принято от", сделать на 2 строки

3) Ставка НДС если отсутствует, то не писать 0%, а ставить прочерк

![image](https://cloud.githubusercontent.com/assets/8355925/22885688/93ed75a0-f20b-11e6-8240-b316f89181b5.png)

**Comment by PiuPauTralala** [comment]
Ветка не та. Это в apps.
