### ISSUE TITLE
Бухгалтерия. Валютные счета. Бухгалтерские формы. Конструктор функций

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3922]
**Исследователь / Бухгалтерия / План счетов / Типовые хоз. операции / Автоматические хоз. операции / Журнал-ордер / Карта счета и другие**.

В плане счетов есть реквизит **Валютный счет (субсчет)**.

В **_Журнале хоз. операций_** при выборе счета с данным реквизитом будут доступны поля для ввода данных по валюте. В противном случае - не будут доступны. Это вполне логично и  работает корректно.

В параметрах **_Журнала-ордера_** при выборе счета без данного реквизита будут доступны реквизиты для формирования формы в валюте. Это не совсем логично.

В **_конструкторе функций_** при выборе счета без данного реквизита будут доступны реквизиты для формирования формы в валюте.

Я к тому, что не мешало бы предусмотреть **проверку на принадлежность счетов/субсчетов к валютным с соответствующей блокировкой полей/компонентов**.

@MIchaelShoihet , пожалуйста, изложите, Вашу, точку зрения.

**Comment by MIchaelShoihet** [comment]
Журнал-хозяйственных операций  - форма ввода данных, где важно обеспечить максимально возможный контроль данных. Остальные формы такими не являются и я не вижу необходимости их усложнять.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , благодарю за беседу.
