### ISSUE TITLE
В ЖХО некорректно работает добавление\редактирование ручных проводок

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#3923]
В ЖХО некорректно работает добавление\редактирование ручных проводок, если на форме установлена галка **группировать по документу**.

Или запретить добавление\редактирование в таком случае, или корректно обработать эти операции.

**Comment by stasgm** [comment]
@gsbelarus В обычном работает корректно, проблема возникает только при "группировать по документу"

**Comment by NikolayUkleyko** [comment]
Проверил, есть такое:

1. При отключенных фильтрах (предопределенный и автофильтр) в случае редактирования ручной записи открывается **пустая диалоговая форма**.
2. При включенных фильтрах (предопределенный **_ЗА ПЕРИОД_** и автофильтр **_ПО СЧЕТУ_**) и добавлении и последующем сохранении программа отображает **окно с сообщением об ошибке**.

![2017-02-18_010213](https://cloud.githubusercontent.com/assets/11497453/23084959/0708fbfa-f576-11e6-977f-d2c3d010102c.jpg)

**Comment by stasgm** [comment]
@NikolayUkleyko Коля, проверь, пожалуйста. И закрой вопрос если всё ок.

**Comment by NikolayUkleyko** [comment]
Проверено.

По вопросу:
>При отключенных фильтрах (предопределенный и автофильтр) в случае редактирования ручной записи открывается пустая диалоговая форма.

Работает корректно.

----

По вопросу:
>При включенных фильтрах (предопределенный ЗА ПЕРИОД и автофильтр ПО СЧЕТУ) и добавлении и последующем сохранении программа отображает окно с сообщением об ошибке.

Ошибка не устранена.
Реально она изрядно напрягает не только нас, но и пользователей.

@ShlTanya , пожалуйста, разберись раз и навсегда с этой проблемой.
Подскажу, что она стала появляться, когда в грид записей Журнала хоз. операций добавили автоматическое обновление данных после выхода из диалоговой формы записи.
Ранее без такого обновления данных ошибки не было.

**Comment by ShlTanya** [comment]
Николай, что значит автофильтр по счету.  И можете проверить при просто включенном фильтре.

**Comment by NikolayUkleyko** [comment]
>Николай, что значит автофильтр по счету. И можете проверить при просто включенном фильтре.

![2](https://cloud.githubusercontent.com/assets/11497453/23164920/ad957ec2-f84a-11e6-8f8a-1ac8d8257bf5.png)

Где:

1. В правом нижнем углу заглавия колонки нажать на треугольник (как в Excel).
2. Из списка выбрать искомое значение.
Это и есть автофильтр.

3. Предопределенные фильтры.

**Comment by ShlTanya** [comment]
Исправила:
1) при включенном фильтре грида после редактирования ручной хоз. операции появлялась ошибка Record not found
2) после изменения счета в ручной хоз. операции в журнале отображались записи до и после изменений.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

@gsbelarus , пожалуйста, закройте тему.
