### ISSUE TITLE
Общее. Предусмотреть горячие клавиши для сворачивание/разворачивания грида

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3925]
Пожалуйста, предусмотрите горячие клавиши (например, Ctrl + курсор) для быстрого сворачивание/разворачивания грида.
Сейчас это можно сделать только при помощи мышки, что не совсем удобно.
Не всегда можно быстро найти этот мелкий компонент.

![2017-02-21_161418](https://cloud.githubusercontent.com/assets/11497453/23166522/03b02e4a-f852-11e6-93af-f8cce14f3950.png)

![2017-02-21_161525](https://cloud.githubusercontent.com/assets/11497453/23166523/03e92d62-f852-11e6-9d81-bebb002a9ac2.png)

![2017-02-21_161706](https://cloud.githubusercontent.com/assets/11497453/23166524/040ed72e-f852-11e6-8eea-2713fb06af1a.png)

![2017-02-21_161759](https://cloud.githubusercontent.com/assets/11497453/23166525/0424aa9a-f852-11e6-89fb-a7a9d707a585.png)

**Comment by MIchaelShoihet** [comment]
Насколько часто это необходимо, что бы делать горячие клавиши? Потом пользователи как посворачивают будем только отвечать куда делись их таблицы.

**Comment by gsbelarus** [comment]
сворачивание сомнительная операция. если убрать мастер, то тогда не
очевидно чьи именно записи отображаются в дитэйле. если дитэйл, то
возникает вопрос а зачем он вообще нужен. может стоит перепроектировать
форму?

2017-02-21 16:30 GMT+03:00 MIchaelShoihet <notifications@github.com>:

**Comment by MIchaelShoihet** [comment]
Иногда просто надо посмотреть весь список позиций или всех клиентов (без групп). Но это бывает достаточно редко и достаточно имеющейся функциональности.

**Comment by NikolayUkleyko** [comment]
>сворачивание сомнительная операция. если убрать мастер, то тогда не
очевидно чьи именно записи отображаются в дитэйле. если дитэйл, то
возникает вопрос а зачем он вообще нужен. может стоит перепроектировать
форму?

По поводу перепроектирования формы скажу, что не надо убирать возможность ручного сворачивание/разворачивания.
Это очень удобный функционал.
Можно быстро выяснить какому Parent (группе) принадлежит та или иная запись.

----

Пример № 1.
Береза МКК / Услуги оказываемые.
Если, акт создан без выбора договора, то соответствующая запись не будет отображена согласно древовидной структуры типов договоров.
Для ее поиска как раз и требуется свернуть грид.

Пример № 2.
Как-то раз Наталья меня попросила в остатках документа списания найти требуемые ОС.
Везде искали, включая и ОС. Остатки на дату, Остатки по материалам и МБП.
Ни в одной из групп ТМЦ требуемый ОС найден не был.
Получилось, что в справочнике ТМЦ искомая запись есть.
При редактировании группы ТМЦ, в которую входит данная запись программа выдавала окно о том, что неверно создана запись и типа нельзя отобразить диалоговую форму.
Как раз помогло сворачивание грида в форме выбора остатков документа списания ОС.
По итогу все успешно было отражено.

**Comment by NikolayUkleyko** [comment]
>Иногда просто надо посмотреть весь список позиций или всех клиентов (без групп). Но это бывает достаточно редко и достаточно имеющейся функциональности.

Не скажу, что редко я этим пользуюсь.
Хорошо.
Обсудили - не будем ничего делать по данной теме.

**Comment by MIchaelShoihet** [comment]
Еще раз повторю, что операция не частая и пользователи ей вообще пользуются очень редко. Поэтому горячие клавиши, могут принести больше вреда чем пользы.

**Comment by NikolayUkleyko** [comment]
ОК.
