### ISSUE TITLE
Форма выбора из множества. 'Enter' и кнопка 'Поиск'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3926]
Пожалуйста, предусмотрите в форме выбора из множества при заполненном поле **Наименование** после нажатия на **Enter** выбор кнопки **Поиск**, то есть, отображение отфильтрованных значений.
Сейчас, при нажатии на кнопку **Enter** форма выбора выбирается кнопка **OK**, что ведет к закрытию формы выбора из множества.

Я про это уже давно писал и общался с @iamchrisep , @zholnerovich .
Вроде, было сделано.
Проверьте.
Может что-нибудь найдете.
Если, нет, то надо сделать.

![2017-02-21_163950](https://cloud.githubusercontent.com/assets/11497453/23167361/29da6e52-f855-11e6-8597-861efd193761.png)

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
