### ISSUE TITLE
Невозможно обновить метаданные при установке ПИ

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3927]
Я знаю два случая, когда метаданные не обновляются при установке пи.
1) поменялся тип поля, домена, признак not null и т.д.
2) поменялась процедура, с которой работают юзеры. Если мы вручную попытаемся поменять ее, то получим сообщение о конфликте. Но если она меняется через ПИ, то никакого сообщения не будет, а процедура не обновится.

Можно ли в этих случаях добавить предупреждение в контрол центр?

**Comment by gsbelarus** [comment]
1. тип поля не всегда можно изменить. тоже и с доменами.
2. ставить пи надо в монопольном режиме

**Comment by alexandra-gsoftware** [comment]
>>>тип поля не всегда можно изменить. тоже и с доменами.

я не предлагаю менять, я предлагаю добавить в лог сообщение, что изменить невозможно.

>>>ставить пи надо в монопольном режиме

только если есть поля-ссылки

**Comment by alexandra-gsoftware** [comment]
п.2 больше не актуален
п.1 актуален

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@alexandra-gsoftware
