### ISSUE TITLE
GDCC. Усовершенствование (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3928]
**1**. Можно ли предусмотреть по-умолчанию активный параметр **Параметры / Обновлять лог автоматически** ?

### На практике постоянно вручную выбираешь данный параметр + кнопка **Обновить**.
Как вариант предусмотреть дополнительно настраиваемый параметр в gdcc.exe.

**2**. Можно ли в строке подключений дополнительно через **( ) или /** отображать наименование БД из списка БД в Гедымине ?

### Сейчас, только, перебирая подключения можно найти требуемую БД.

**3**. Можно ли предусмотреть автоматический переход на самое новое подключение к БД ?

### Как вариант предусмотреть дополнительно настраиваемый параметр в gdcc.exe.

**4**. Можно ли предусмотреть возможность очистки строки подключений по отключенным БД ?

### Как вариант предусмотреть дополнительно настраиваемый параметр в gdcc.exe.

![2017-02-21_155411](https://cloud.githubusercontent.com/assets/11497453/23165653/475f58f4-f84e-11e6-8508-7bd44b143c9e.png)

**Comment by hirurg-lybitel** [comment]
4. Или хотя бы вынести их на отдельную вкладку. А то люди не могут отличить закладки активных подключений от неактивных.

**Comment by NikolayUkleyko** [comment]
>Или хотя бы вынести их на отдельную вкладку. А то люди не могут отличить закладки активных подключений от неактивных.

Согласен.
Крайне неудобно.
Обращались по данному вопросу неоднократно.
Надо решить данный вопрос.
