### ISSUE TITLE
Бухгалтерия. Конструктор функций. В блоках запросов слетает очередность параметров

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3929]
**Исследователь / Бухгалтерия / Автоматические хоз. операции, Типовые хоз. операции....**

В блоках типа SQL-запрос, SQL-цикл и т.д. ввели запрос с перечислением ряда параметров.
При переключении закладок (**_SQL-запрос / Параметры / SQL-запрос_**) очередность параметров на закладке **Параметры** становится наоборот по отношению к очередности параметров в тексте запроса.
Неудобно.

Пожалуйста, исправьте.

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
