### ISSUE TITLE
Все объекты в окне редактора скрипт-объектов должны добавляться в ПИ по-отдельности

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3930]
Сделать:

1. Добавление в ПИ группы (папки) макросов. Соответствующую команду добавить в контекстное меню.

2. Добавление в ПИ TgdcDelphiObject (объекты, скрывающиеся в ветке Методы)

3. Добавление в ПИ шаблона отчета (добавить команду на панель инструментов, на вкладке отчет)

4. Добавление в ПИ только скрипт-функции (добавить команду в контексное меню, которое вызывается по правой кнопке мыши при редактировании текста функции)

**Comment by ShlTanya** [comment]
По п.2.. Я сделала вот так: 
![ns](https://cloud.githubusercontent.com/assets/24572314/23667431/de633ed4-036e-11e7-8fc3-f936402736c4.JPG)
 В данном случае я ПИ для TgdcInvBaseRemains. Вы так хотели?

**Comment by gsbelarus** [comment]
Теперь всё можно добавлять по-отдельности. Чтобы добавить СФ ивента (или макроса, или метода), откройте панель ивента, переместитесь на вкладку **Скрипт** и по правой кнопке мыши -- **Добавить в ПИ**. Чтобы добавить сам объект (ивент, макрос и т.п.) надо: 
1. выделить его в дереве и выбрать команду из контекстного меню
2. или открыть его панель и выбрать команду из контекстного меню на любой вкладке, кроме вкладки с тектом скрипт-функции.
