### ISSUE TITLE
Бухгалтерия. Автоматические проводки. Отображение входимости

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3932]
**Исследователь / Бухгалтерия / Автоматические хоз. операции.**

Пожалуйста, добавьте поле для отображения входимости Автоматической проводки в Автоматическую хоз. операцию.
Сейчас неудобно.

![2017-03-03_115423](https://cloud.githubusercontent.com/assets/11497453/23544806/83aceeee-0009-11e7-82c1-5ae154ef0a13.png)

Подобное реализовано в Типовых проводках .

![2017-03-03_115513](https://cloud.githubusercontent.com/assets/11497453/23544807/83db555e-0009-11e7-851f-d72182ce413a.png)

@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
Форма автоматической проводки небольшая.. за ней видно на какой ветке дерева стоим. 
Но.. если неудобно.. можно посмотреть.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

**Comment by ShlTanya** [comment]
:) я тут ничего не делала.
