### ISSUE TITLE
Ошибки в карточке ТМЦ

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#3933]
Если в параметрах карточки ТМЦ задать параметры "Документы прихода" или "Документы расхода", то при построении карточки получим ошибку
![error](https://cloud.githubusercontent.com/assets/11484894/23799522/e0e5411e-05b9-11e7-8cbb-9c481be16781.jpg)
При этом выбор документа работает только через лукап. Если нажать кнопку для выбора нескольких документов ![button](https://cloud.githubusercontent.com/assets/11484894/23799533/e9d2e75e-05b9-11e7-8900-45aee0d8ea17.jpg), то получим ошибку Invalid index

**Comment by alexandra-gsoftware** [comment]
а еще она очень медленно открывается.

**Comment by AliakseiDanilchyk** [comment]
Это такая форма (gdv_frmInvCard), в которой можно задать параметры и получить список движений по ТМЦ в виде грида.
Конфигурации настраиваются в "Исследователь - Сервис - Складские параметры - Настройка карточки товара"

**Comment by ShlTanya** [comment]
Попутный вопрос Как должно быть: 
Если определен документ Прихода и Не определен Документ Расхода, то в отбор попадают: 
- по приходу записи по документу Прихода
 - по расходу.. Все записи.
И наоборот также.

Сейчас отбираются только записи по документу Прихода. По расходу движения не видно.

**Comment by ShlTanya** [comment]
Исправила ошибки. 
+ При множественном выборе ТМЦ отображалась только 1 выбранная запись. Исправила.

**Comment by NikolayUkleyko** [comment]
Дополнительно выявлено следующее.
При нажатии на квадрат для множественного выбора документов **нет складских документов**.

![2017-03-13_095632](https://cloud.githubusercontent.com/assets/11497453/23844534/c961e77e-07d3-11e7-99a3-cf1bd3b907f1.png)

По-моему это неверно.

@ShlTanya , пожалуйста, посмотри.

**Comment by ShlTanya** [comment]
Николай, а посмотрите внимательно в Сервисе Типовые документы. Может у Вас так заведена структура??

**Comment by NikolayUkleyko** [comment]
Татьяна, смотрю на эталонной тестовой демо БД.
Реально в вышеприведенной форме не отображаются складские типовые документы.

![2017-03-14_104212](https://cloud.githubusercontent.com/assets/11497453/23890510/380e5aa2-08a3-11e7-912c-962548739d1b.png)

**Comment by alexandra-gsoftware** [comment]
люди, у меня по-прежнему сама карточка очень медленно открывается, и не поймешь по профайлеру, почему. У кого-то есть похожая проблема?

**Comment by ShlTanya** [comment]
Добавлены кнопки Ok, Отмена. Сохранение введенных параметров.

**Comment by ShlTanya** [comment]
И остались ли еще вопросы, связанные с карточкой ТМЦ.

**Comment by NikolayUkleyko** [comment]
Как-то специфично работает форма карточки, задав ограничение по конкретному документу, как в приходе, так и в расходе.
Указав документ, данные должны быть отображены строго по нему.
@ShlTanya , пожалуйста, проверь.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , можно ли предусмотреть вызов главной формы карточки,

![2017-04-11_180440](https://cloud.githubusercontent.com/assets/11497453/24916064/c0091aec-1ee1-11e7-932f-63206d9b47ad.png)

минуя первичную форму

![2017-04-11_180524](https://cloud.githubusercontent.com/assets/11497453/24916085/d27dfbfc-1ee1-11e7-9676-1c12f2ca6eeb.png)

?

**Comment by ShlTanya** [comment]
> Как-то специфично работает форма карточки, задав ограничение по конкретному документу, как в приходе, так и в расходе.
> Указав документ, данные должны быть отображены строго по нему.

Это то о чем я спрашивала ранее: 
Если определен документ Прихода и Не определен Документ Расхода, то в отбор попадают:
- по приходу записи по документу Прихода
- по расходу.. Все записи.
И наоборот также.

На Вашей картинке как раз такая ситуация: указан документ Прихода - переоценка и не указан документ Расхода - отобрались все записи по расходу.

Михаил, как Вы считаете. Как в таком случае д.б.

**Comment by MIchaelShoihet** [comment]
Логика правильная. Но возможно надо добавить возможность указания, что строим только по документам прихода или только по документам расхода.

**Comment by ShlTanya** [comment]
Если вместо знака равно выбрать Не существует.. то как раз и получится исключить Приход или Расход.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, подскажи, каково функциональное различие кнопок **_Автоматически (1)_** и **_В виде дерева (2)_**:
![image](https://user-images.githubusercontent.com/11497453/149796188-1e961b73-8123-4e84-ab5e-d6a927f5ab87.png)

**Comment by ShlTanya** [comment]
Есть 2 представления данных в этой форме: в виде таблицы и в виде дерева. Автоматически (по умолчанию) отображает в виде дерева.

**Comment by NikolayUkleyko** [comment]
> _Есть 2 представления данных в этой форме: в виде таблицы и в виде дерева. Автоматически (по умолчанию) отображает в виде дерева._

@ShlTanya , автоматически выбирается тип отображения данных согласно бизнес-класса соответствующего справочника или, как в Инспекторе объектов значение в параметре **_ViewType_** ?:
![image](https://user-images.githubusercontent.com/11497453/150310755-17c18195-f61f-4e50-80fa-c68aa3c861be.png)

**Comment by NikolayUkleyko** [comment]
> > _Есть 2 представления данных в этой форме: в виде таблицы и в виде дерева. Автоматически (по умолчанию) отображает в виде дерева._
> 
> @ShlTanya , автоматически выбирается тип отображения данных согласно бизнес-класса соответствующего справочника или, как в Инспекторе объектов значение в параметре **_ViewType_** ?: ![image](https://user-images.githubusercontent.com/11497453/150310755-17c18195-f61f-4e50-80fa-c68aa3c861be.png)

@ShlTanya , пожалуйста, подскажи и тему закроем.

**Comment by gsbelarus** [comment]
@NikolayUkleyko закрываем?

**Comment by NikolayUkleyko** [comment]
Да, пожалуйста, @gsbelarus .
