### ISSUE TITLE
Общие. Свойства. Добавить прокрутку списка полей скроллом мышки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3935]
@ShlTanya , пожалуйста, добавь для свойств записи возможность прокрутки списка полей скроллом мышки.

![1](https://cloud.githubusercontent.com/assets/11497453/23853688/c58ed578-07fe-11e7-945e-d4e583711774.png)

![2](https://cloud.githubusercontent.com/assets/11497453/23853689/c78d1650-07fe-11e7-81b8-d64a53a3574d.png)

Шрифт мелкий.
Так будет удобнее искать требуемые поля.

Вопрос !
Подскажите, пожалуйста, зачем здесь предусмотрен реквизит **Параметры** ?

![3](https://cloud.githubusercontent.com/assets/11497453/23853692/ca605e0a-07fe-11e7-8301-1088199a5f29.png)

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

----

@ShlTanya , пожалуйста, подскажи, зачем здесь предусмотрен реквизит **Параметры** ?
