### ISSUE TITLE
Справочники. Валюты. Назначение реквизита 'Эквивалент' (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3936]
**Исследователь / Справочники / Курсы валют / Валюты.**

@MIchaelShoihet , пожалуйста, подскажите, для чего в справочнике валют предусмотрен реквизит **Эквивалент** ?
В руководства пользователя информации мало.

![2017-03-13_155412](https://cloud.githubusercontent.com/assets/11497453/23855522/0278e3fe-0807-11e7-916c-ae738ca26812.png)

В Журнале-ордере и других бухгалтерских формах не предусмотрен выбор конкретной стоимостной единицы, как эквивалент.

![2017-03-13_160350](https://cloud.githubusercontent.com/assets/11497453/23855562/1e4f6788-0807-11e7-8f3e-cfb26f9b4d91.png)

**Comment by MIchaelShoihet** [comment]
Эквивалент выбран - как возможность ведения учета в параллельной валюте одной конкретной. В справочнике она выбирается и затем при надлежащей настройке все можно пересчитывать в эту валюту, уже больше нигде ее явно не выбирая. К сожалению - надлежащей настройки не было создано до конца. Хотя в стандартной торговле есть практически все для этого...

**Comment by NikolayUkleyko** [comment]
Например, учет в RUB, EUR и в других.
В качестве эквивалентной (параллельной) валюты выбрана USD.
@MIchaelShoihet , так ведь ?

Может ли быть несколько эквивалентных (параллельных) валют для одной основной валюты ?

**Comment by MIchaelShoihet** [comment]
Эквивалент может быть только один. Обычно раньше он выбирался USD, Но практически это ни где не использовалось. Смысла нескольких эквивалентов нет и поддержки их ведения в программе то же нет. Впрочем возможно исходя из истории использования нет смысла и в одном эквиваленте.

**Comment by alexandra-gsoftware** [comment]
мне кажется, есть клиенты, которые им активно пользуются, но их не очень много...
