### ISSUE TITLE
Бухгалтерия. Типовые хоз. операции. Отображение входимости списком, а не деревом

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3937]
**Исследователь / Бухгалтерия / Типовые хоз. операции.**

Почему-то сейчас в типовых хоз. операциях в поле **Входит в** записи отображаются списком, а не деревом ?

![1](https://cloud.githubusercontent.com/assets/11497453/23856047/1fd4556c-0809-11e7-9ec2-b72814b2bb0e.png)

По-моему ранее было в виде дерева.
Не забыть предусмотреть сортировку по возрастанию.

@ShlTanya , пожалуйста, посмотри.

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
