### ISSUE TITLE
Наследование. Не переносятся предопределенные фильтры (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3938]
При наследовании документа не переносятся предопределенные фильтры.
По-моему это надо учесть.
@gsbelarus , не так ли ?

**Comment by gsbelarus** [comment]
Тут спорный вопрос. Можно много примеров привести, когда такой перенос автоматом будет плох.

**Comment by NikolayUkleyko** [comment]
У меня на Витебск МК создан наследуемый документ по учету входящих услуг.
Скажу, что в данном случае, как раз, не хватает переноса всех предопределенных фильтров.
Если, вопрос спорный, то может быть, предусмотреть выбор - переносить фильтры или нет ?

**Comment by MIchaelShoihet** [comment]
Чаще всего фильтры нужны.

**Comment by NikolayUkleyko** [comment]
Если, отчеты перенеслись, то, почему бы и фильтры не перенести.

**Comment by gsbelarus** [comment]
@ShlTanya надо изучить вопрос и предложить решение. возможны варианты:

1. При формировании меню фильтров мы учитываем наследование классов и добавляем в меню фильтры из наследованных классов.
2. То же, что и предыдущее, но реализуем возможность скрыть наследованный фильтр в меню класса наследника, чтобы он не появлялся.
3. При создании нового класса однократно предлагаем скопировать фильтры из класса родителя. Механизм формирования меню не трогаем. (Мне кажется наименее предпочтительный вариант).

Какая может возникнуть проблема при подхватывании фильтров родителя: в следствие изменения структуры данных в наследнике будут возникать ошибки SQL запросов.

**Comment by ShlTanya** [comment]
У меня при 1 и 2 варианте сразу возник вопрос: Есть фильтр родителя, открываем наследника видим его там.. меняем значение фильтра.. открываем Родителя и видим измененный фильтр?? Насколько удобно такое наследование для пользователя.. не думаю, что  они знают о наследовании документов.
По реализации 1 и 2 пункт можно сделать.. но наверное с оговоркой на изменение наследуемых фильтров. Еще вызывает сомнение по п. 2. скрыть 1 из нескольких наследуемых фильтров. Сразу все .. думаю что можно.
Про ошибки SQL запросов.. в наследуемых документах есть возможность изменения как таблицы шапки так и позиции.. значит ошибки теоретически могут быть.
Могу предложить еще 1 вариант: это копирование фильтров родителя в самом фильтре.

**Comment by NikolayUkleyko** [comment]
Моя точка зрения на это следующая.
Достаточно **по требованию** перенести фильтры базового документа в наследуемый.
При этом, все внесенные изменения в фильтры наследуемого документа не должны отразиться в фильтрах базового документа.

----

При обновлении ПИ в части функционала базового документа **могут добавиться новые фильтры**.
Соответственно, необходимо учесть возможность по требованию копирования конкретно выбранных фильтров из базового документа в наследуемый.
Возможность наследования изменений по существующим фильтрам я думаю не нужна.

----

Аналогично можно и сделать для отчетов.
Сейчас в наследуемых документах в списке отчетов по умолчанию отображается папка с наименованием базового документа с перечнем отчетов.
Отображение таких отчетов в наследуемых документах особо не требуется.
Много отчетов - пользователь может растеряться.

**Comment by NikolayUkleyko** [comment]
При создании документов-наследников фильтры не перенесены и настройки грида тоже.
Проверено на различных gedemin.exe.

**Comment by NikolayUkleyko** [comment]
Недавно с @yoannawx обсуждали данный вопрос.
Актуально.
@ShlTanya , пожалуйста, посмотри.

**Comment by gsbelarus** [comment]
Если делать, то так:

1. Фильтры родителя видны в списке фильтров наследника.
2. Фильтры родителя можно применить к наследнику.
3. При попытке редактировать фильтр родителя из окна наследника выдается сообщение, что этот фильтр создан в окне родителя и менять его можно только там.
4. При включении в ПИ наследника автоматически должны подтягиваться ТОЛЬКО фильтры НАСЛЕДНИКА. Фильтры родителя не должны  трогаться. Они принадлежат родителю и попадают в ПИ родителя.

**Comment by NikolayUkleyko** [comment]
Достаточно хорошие варианты.

**Comment by Polfath** [comment]
сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
В целом функционал работает корректно.
Необходимо внести некоторые правки.

**Comment by Polfath** [comment]
Поправил

**Comment by NikolayUkleyko** [comment]
https://github.com/GoldenSoftwareLtd/gedemin/issues/3938#issuecomment-1019500196

Проверено.

Пункты 1 и 2 – так и реализовано.
Пункт 3 – в документе наследнике предусмотрена деактивация клавиш редактирования и удаления фильтров базового документа без отображения дополнительных сообщений.
Пункт 4 – в документе наследнике предусмотрена деактивация клавиш добавления в ПИ фильтров базового документа без отображения дополнительных сообщений.

@Polfath , благодарю !
