### ISSUE TITLE
Общие. В позиции документа предусмотреть возможность выбора точного документа 'Ctrl + D'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3939]
В диалоговых формах, в частности в шапке документа в полях типа **Документ** предусмотрена замечательная возможность выбора конкретной записи по выбранному типовому документу через команду **_Ctrl + D_**.
В позициях документа такое сочетание не работает.
Не во всех документах для позиции есть отдельная настроенная диалоговая форма.
Если, можно, пожалуйста, предусмотрите такую возможность.

----

Возможность выбора конкретной записи по документу используется в случае задания значения по аналитике **Документ**.

**Comment by ShlTanya** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
