### ISSUE TITLE
Общие. Реквизит 'Разрешать более одного подключения под одним логином'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3940]
**Сервис / Параметры / Аудит и безопасность / Разрешать более одного подключения под одним логином.**

Скажите, пожалуйста, на учетную запись Administrator такая опция не распространяется ?
У Жанны к этому режиму есть вопросы.

**Comment by gsbelarus** [comment]
Скорее всего нет. На то он и администратор, чтобы иметь всегда возможность вмешаться и разрешить возникшие проблемы. У простых пользователей **НЕ ДОЛЖНО** быть доступа к этой учетной записи.

**Comment by NikolayUkleyko** [comment]
По непривилегированным пользователям понятно.
Вопрос в том, стоит ли запретить **несколько подключений к БД под Администратором** ?

**Comment by YRozmysl** [comment]
@NikolayUkleyko А для чего нужно такое вот ограничение для администратора? на практике именно, если. Просто, вот взять ту же удаленную нашу работу с мк, там же могут сидеть ОДНОВРЕМЕННО много наших сотрудников и всем нужны права админа, как быть в такой ситуации?

**Comment by NikolayUkleyko** [comment]
>много наших сотрудников и всем нужны права админа, как быть в такой ситуации?

Вопросы к Жанне.
