### ISSUE TITLE
Наследование. В базовом документе предусмотреть сортировку по документу

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3941]
Пожалуйста, предусмотрите в базовом документе сортировку по наименованию добавляемого документа.

![2017-03-17_174833](https://cloud.githubusercontent.com/assets/11497453/24048653/9bb2c856-0b3a-11e7-905c-2ef14d838dc6.png)

![2017-03-17_175010](https://cloud.githubusercontent.com/assets/11497453/24048654/9bb9903c-0b3a-11e7-83db-1170a0a73890.png)

**Comment by stasgm** [comment]
И хорошо бы табулляцию сохранять

**Comment by ShlTanya** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
