### ISSUE TITLE
Режим редактирования формы: показать и закрепить панель компонентов и  инспектор объектов 

### ISSUE THREAD

**Issue by arthur-latunov** [GoldenSoftwareLtd/gedemin#3942]
Трудно найти панель компонентов и  инспектор объектов, если производилось редактирование на большем экране и было смещение далеко вправо. Повесить на **Ctrl+F11** приведение панели компонентов и  инспектора объектов _примерно_ в следующее положение и размер  с включением признаков 'Всегда сверху'.
![image](https://cloud.githubusercontent.com/assets/11484233/24135254/0f0a3adc-0e1a-11e7-9ca4-8873320678e1.png)

**Comment by gsbelarus** [comment]
Лишних горячих клавишь не надо. Даже существующие известны не более 10% пользователей. Достаточно просто проверять формы помещаются на экран или нет, и, при необходимости, автоматом менять их позиции.

**Comment by NikolayUkleyko** [comment]
@arthur-latunov ,
**_Сервис / Хранилище / Администратор / Поиск / Inspect / dlg_gsResizer_ObjectInspector._**

![2017-03-21_101603](https://cloud.githubusercontent.com/assets/11497453/24136477/0544c3d6-0e20-11e7-9eba-bab04724f81b.png)

**Внести правки в координаты с наибольшими значениями / Сохранить / Проверить.**

**Comment by MIchaelShoihet** [comment]
Только без включения признака "Всегда сверху". Я постоянно его отключаю, мне лично он совсем не удобен.

**Comment by arthur-latunov** [comment]
@MIchaelShoihet тоже не против, я согласен на без включения признака "Всегда сверху".
@gsbelarus для разработчиков, а не пользователей. Да даже, если и не выходит за границы, то положение и размеры к некоторому '_по умолчанию_' привести было бы удобно.
Давайте послушаем ещё мнения...

**Comment by arthur-latunov** [comment]
@NikolayUkleyko Инспектор понятно, а панель компонентов?

**Comment by PiuPauTralala** [comment]
Да, было бы здорово, если бы были места и размер "по умолчанию" для  инспектора и панельки.

**Comment by NikolayUkleyko** [comment]
>Да, было бы здорово, если бы были места и размер "по умолчанию" для инспектора и панельки.

Было бы хорошо.

**Comment by alexandra-gsoftware** [comment]
Кстати, было бы неплохо про настройки инспектора в хранилище сделать документацию, а то вечно вспоминаешь, как эта ветка называлась..

**Comment by ShlTanya** [comment]
Андрей, можно узнать решение по этому вопросу. Сейчас панельки возвращаются при выходе за экран левой (верхней) границы.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
