### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Эквивалент и группировка колонок (QQ)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3943]
**Исследователь / Бухгалтерия / Журнал-ордер.**

При формировании формы по национальной валюте, иностранной валюте и эквиваленту колонки группируются **_друг над другом_**.
Для анализа это удобная компоновка данных.

При формировании формы по иностранной валюте и эквиваленту колонки группируются **_одна за одной_**.
Это неудобная компоновка данных.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet и @ShlTanya , пожалуйста, изложите свои точку зрения.

**Comment by MIchaelShoihet** [comment]
Я согласен... Но может есть что-то более важное на данный момент. Я не знаю сейчас клиентов, которые используют эквивалент...

**Comment by NikolayUkleyko** [comment]
Я тщательно проверяю корректность работы заложенного бухгалтерского функционала в платформу.
Мне не все равно.
Есть недоработки и их стоит устранить.
Речь не идет о высоком приоритете данной темы.
Но, при возможности будет не лишним внести доработки.

**Comment by alexandra-gsoftware** [comment]
Можно поставить priority-low, и пусть ждет своего часа.

**Comment by NikolayUkleyko** [comment]
Конечно.
