### ISSUE TITLE
Прочие. Редактор скрипт-объектов. Неконтрастное начертание выделенного метода в проводнике

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3944]
![2017-03-29_121000](https://cloud.githubusercontent.com/assets/11497453/24447825/e9cec230-147a-11e7-9533-ac1781bca9ed.png)

По-умолчанию в редактор скрипт-объектов неконтрастное начертание выделенного метода в проводнике.
То есть, не читается вовсе.
После перевыбора метода начертание выделенного метода становится контрастным.

@ShlTanya , пожалуйста, поправь.

**Comment by gsbelarus** [comment]
Ничего не править! Я только вернул чтобы работало нормально! Надо зайти в настройки цветовой схемы виндоуз и выставить нормальные цвета для выделенного текста и фона. Это не проблема Гедымина. Так настроены цвета на конкретном компьютере, значит человеку так нравится.

**Comment by gsbelarus** [comment]
Для примера, так это выглядит у меня на компьютере:

![image](https://cloud.githubusercontent.com/assets/5175764/24448465/f9979c44-147c-11e7-83a0-a613a698dff4.png)

**Comment by NikolayUkleyko** [comment]
> Я только вернул чтобы работало нормально!

Значит что-то было ?
