### ISSUE TITLE
Общие. Адаптация интерфейса Гедымина к разрешению 1920x1080 и выше

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3945]
У Евгения на экране с разрешением 1920x1080 интерфейс Гедымина очень мелкий.
Впрочем это естественно.
Делая разрешение экрана меньше и при необходимости используя другие настройки не удается получить интерфейс платформы нормального размера с четкой прорисовкой.
При этом интерфейс других приложений и программ не мелкий и с четкой прорисовкой.

Такое же замечено и у Михаила Васильева.
Такое все мелкое.
Крайне неудобно.

**Comment by gsbelarus** [comment]
И так будет. Именно поэтому в операционной системе есть режим масштабирования. Миллионы программ (к которым относится и Гедымин) полагаются на размер экранных объектов в пикселях. Можно централизованно увеличить размер шрифта, но при этом все экранные формы будут искажены. Весь код, который внутренне полагается на определенные отступы в пикселях перестанет работать. Можно долго спорить плохо это или хорошо, но в конце девяностых средства разработки работали именно так и не позволяли ничего другого.

**Comment by alexandra-gsoftware** [comment]
у меня на одном из новых компов была та же проблема не только с гедымином, но и с большинством программ, т.ч. это везде так.
