### ISSUE TITLE
добавление в ПИ с зависимыми

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3946]
Добавляю в ПИ табличку со всеми связанными объектами. Все события компонентов на форме просмотра добавляются, а события самой формы (типа OnLoadSettingsAfterCreate, OnShow, etc) - не добавляются.

**Comment by alexandra-gsoftware** [comment]
также не добавились
- настройки гридов
- MacrosGroup и ReportGroup  (напоминаю, что добавить их руками отдельно достаточно проблематично)

Кроме того, два объекта имеют порядковый номер "2" - таблица и ее первое поле

**Comment by alexandra-gsoftware** [comment]
триггеры таблиц также не добавляются

**Comment by gsbelarus** [comment]
Новым экзешником макрос гроуп и репорт гроуп прекрасно добавляются

**Comment by alexandra-gsoftware** [comment]
проверила еще раз - да, макросгрупы и репортгруппы добавляются. часть событий и триггеры - нет.

**Comment by alexandra-gsoftware** [comment]
Еще такое. Ставлю 2 ПИ:
1) C:\Golden\gedemin-apps\Категории\GS.Категории ТМЦ.Сохраненные параметры.yml
2) C:\Golden\gedemin-apps\Прочее\GS.Общие.Запросы к RDB-таблицам.yml
без зависимых. (1) зависит от (2), но Гедымин все равно ставит его первым. Мне кажется, раньше он разбирал зависимости в этом случае....

**Comment by alexandra-gsoftware** [comment]
Настраиваю гриды. Сохраняю ПИ. Проверяю на другой БД - Гриды не изменились. Переподключаюсь к исходной БД. Запускаю сравнение ПИ. У моего ПИ стоит значок =>, но если нажать Сравнить, видно, что на базе гриды новее.

**Comment by NikolayUkleyko** [comment]
>Настраиваю гриды. Сохраняю ПИ. Проверяю на другой БД - Гриды не изменились. 

@alexandra-gsoftware , недавно с таким столкнулся.

**Comment by NikolayUkleyko** [comment]
Недавно столкнулись снова с проблемой, при которой с зависимыми не добавляются в ПИ такие объекты, как:
> события самой формы (типа OnLoadSettingsAfterCreate, OnShow, etc).

**Comment by NikolayUkleyko** [comment]
Недавно разработал новый документ и сохранил в ПИ.
В целом в ПИ все объекты были автоматически добавлены.
Установка ПИ прошла успешно и документ работает корректно.

@alexandra-gsoftware ?

**Comment by NikolayUkleyko** [comment]
1. Добавил в ПИ типовой документ со связанными объектами.
2. Из основного ПИ выделил в отдельное ПИ типовые проводки.

В результате в ПИ с типовыми проводками были переброшены не только типовая проводка (типовая хоз. операция) и функция типовой проводки, но и:
- таблицы документа;
- TgdcMacrosGroup;
- TgdcReportGroup;
- TgdcExplorer.

В данной ситуации в ПИ должны были быть добавлены только типовая проводка (типовая хоз. операция) и функция типовой проводки.

Вопрос не глобальный поэтому можно его закрыть.
Вряд ли этим уже будут заниматься.
@alexandra-gsoftware , каково твое мнение ?

**Comment by alexandra-gsoftware** [comment]
я думаю, это фигня какая-то, так быть не должно.
Раньше вроде работало нормально.

**Comment by NikolayUkleyko** [comment]
#4191 
Пожалуйста, подобная тема.

**Comment by gsbelarus** [comment]
@alexandra-gsoftware @NikolayUkleyko разработчик не может приступить, так как из описания выше не ясно что работает, а что нет. там в коментариях то все ок, то что-то не ок, но что не понятно. пожалуйста, или закрываем оба ишью как неактуальные, или конкретно пропишем список что надо человеку сделать, какие еще объекты должны быть добавлены.

жду пару дней, потом, если нет движения, то закрываю.

**Comment by NikolayUkleyko** [comment]
https://github.com/GoldenSoftwareLtd/gedemin/issues/4191#issuecomment-1254962912
