### ISSUE TITLE
Бухгалтерия. Не формируется проводка по количественным показателям без суммы

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3947]
**Исследователь / Бухгалтерия / Типовые хоз. операции.**

Сейчас не формируются бухгалтерские проводки по документам только по количественным показателям без суммы.
При этом в гриде проводок не отображаются корреспонденции счетов.
Однако, аналогичная ручная проводка в Журнале хоз. операций корректно обрабатывается в бухгалтерских формах: Журнал-ордер, Карта счета и т.д.
Раньше это обсуждалось.

Несколько лет назад соответствующую правку вносили в gedemin.exe.
Потом выявили, столкнулись со следующей проблемой
https://github.com/GoldenSoftwareLtd/gedemin/issues/3851

Необходимо, взвесить все **за** и **против** и аккуратно внести правки в gedemin.exe в части функционала формирования бухгалтерских проводок, бухгалтерских форм по количественным показателям.
Чтобы в результате не повредить существующий функционал и учесть изложенные здесь предложения.

----

При формировании Карты счета по проводкам по количественным показателям без суммы с выбранным реквизитов **Группировать** программа отображает пустую форму.
Необходимо разобраться.
На мой взгляд в данном случае форма должна быть сформирована с данными.

----

Пожалуйста, напомните, в типовой проводке каково предназначение реквизита **_Сохранять нулевую проводку_** ?

![2017-04-19_123008](https://cloud.githubusercontent.com/assets/11497453/25173446/c927ede4-24fc-11e7-9ac9-13d45ca0091a.png)

@MIchaelShoihet , @ShlTanya , пожалуйста, изложите ваши мнения по данной теме.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.
Это важный вопрос.
Раньше работало, теперь - нет.

**Comment by ShlTanya** [comment]
Смоделировала ситуацию.. Поправьте, если не так. Делаем документ, по которому проводки Только по  количественным показателям. В гриде с проводками действительно нет проводок.
![1](https://cloud.githubusercontent.com/assets/24572314/25481331/556debf6-2b55-11e7-82e9-520fa2eb2331.JPG)

Но по Переходу на данную проводку видим ее присутствие 
![2](https://cloud.githubusercontent.com/assets/24572314/25481362/7a7cb5bc-2b55-11e7-9167-41acf9bf4805.JPG)
 
Вас этот момент смущает??

**Comment by NikolayUkleyko** [comment]
@ShlTanya , теперь, пожалуйста, сформируй Журнал-ордер по счету 10.11 (10.12) за 30.11.2016 по аналитике Счета и субсчета и укажи количественный показатель Кол-во (это условно универсальный количественный показатель).
Будет пусто по количеству.
Это не есть верно.
Здесь необходимо очень аккуратно предусмотреть отображение таких данных.
Чтобы не испортить формирование Журнала-ордера без количественных показателей.
Повторюсь, что уже были попытки.

**Comment by ShlTanya** [comment]
![3](https://cloud.githubusercontent.com/assets/24572314/25481775/60a0b2e0-2b57-11e7-84cc-57783940918b.JPG)

**Comment by NikolayUkleyko** [comment]
@ShlTanya , а чего в колонках не отображаются корреспондирующие счета ?
Сейчас **К -**.
Здесь надо **К - 10.12**.

**Comment by ShlTanya** [comment]
Я ужимала колонки

**Comment by NikolayUkleyko** [comment]
@ShlTanya , теперь надо проверить Журнал-ордер на проводках во всех вариантах:
- только сумма;
- только количество;
- сумма и количество.

Для точности сравни результат на одной БД под разными gedemin.exe (с учетом сегодняшних изменений и без изменений).

На всякий случай это надо будет учесть в других бухгалтерских формах (Карта счета, Анализ счета и т.д.).

**Comment by ShlTanya** [comment]
Проблема есть, если делать выборку только по **Количественным показателям** (без сумм). 
![4](https://cloud.githubusercontent.com/assets/24572314/25486363/9553270e-2b69-11e7-8528-b7ef25bd840d.JPG)
Обсудите и скажите как д.б.

**Comment by NikolayUkleyko** [comment]
>Обсудите и скажите как д.б.

Согласно вышеприведенного скриншота значение по количественному показателю без суммового должно быть.
Сейчас пусто.
Форма Журнал-ордер, как и другие бухгалтерские формы универсальные.

@ShlTanya , я, то, писал, как должно быть.
Бухгалтерские формы должны одинаково хорошо работать как с суммовыми, так и с количественными показателями.
Ведь наряду с суммовыми показателями, количественные показатели тоже полноценные.
Может и недостаточно такого объяснения.
Здесь необходимо детализация языком программиста.
Кроме @MIchaelShoihet , никто не подскажет.

**Comment by ShlTanya** [comment]
@MIchaelShoihet , посмотрите, пожалуйста, мой коммит по 3947.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
