### ISSUE TITLE
Общие. Копирование значений ячеек из Excel и вставка в Гедымин

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3948]
Можно ли предусмотреть возможность копирования значений ячеек из Excel и вставки в Гедымин (позиция документа) ?
Ведь, в Гедымине есть возможность копирования значений ячеек в буфер и последующий вставки в Excel.
Следует отметить, здесь идет речь не о простом копировании строк, а о копировании конкретных выделенных данных из ячеек.
Все это предусмотреть через горячие клавиши Ctrl + C и Ctrl + V и через соответствующие команды контекстного меню.

----

Вариант с макросом с параметрами координат пока не рассматриваем.

**Comment by hirurg-lybitel** [comment]
Лейбл **Фантастика** прикрепить забыл

**Comment by NikolayUkleyko** [comment]
>Лейбл Фантастика прикрепить забыл

@hirurg-lybitel , а чего бы и нет ?

**Comment by gsbelarus** [comment]
В гедымине ссылка, в экселе строка. Дальше что делать? искать? создавать объект? Это можно делать чистый человеко-месяц разработчика. Это действительно так надо?

**Comment by NikolayUkleyko** [comment]
Я исхожу из разумных соображений.
Пообщались и выяснили что да как.
Если, предполагаемая разработка весьма трудоемка, тогда ее не реализуем.
