### ISSUE TITLE
Мастер установок. Ошибка при сохранении в шаблон при использовании расширенного отображения

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3949]
В Мастере установок выявлена ошибка при сохранении в шаблон настроек грида при **использовании расширенного отображения**.

![2017-04-21_133354](https://cloud.githubusercontent.com/assets/11497453/25274186/99d74c0a-2697-11e7-8ec8-23acfd8a5a07.png)

Без **использовании расширенного отображения** сохранение шаблона выполняется успешно.

@ShlTanya , пожалуйста, реши данный вопрос.

**Comment by NikolayUkleyko** [comment]
Снова столкнулся с данной проблемой при настройке форм и документов по учету основных средств.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , скажи, пожалуйста, что, ты, можешь сказать по данному вопросу ?

**Comment by NikolayUkleyko** [comment]
В частности вышеприведенное имеет силу для грида позиции документа.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
Данный вопрос актуален.

![image](https://user-images.githubusercontent.com/11497453/135485447-4c653dc6-db26-462c-9171-291f4c65def3.png)

На мой взгляд возможен один из 2-х вариантов:

1. Доработать алгоритм сохранения настроек расширенного грида в шаблон.
2. Выводить следующее сообщение: _Нельзя выполнить сохранение настроек расширенного грида в шаблон. Пожалуйста, снимите галку по использованию расширенного отображения и заново пересохраните шаблон_.

**Comment by ShlTanya** [comment]
Проверила сохранение и установку настроек расширенного грида - работает. Можно мне точные настройки грида, при котором появляется ошибка.

**Comment by NikolayUkleyko** [comment]
Посмотрел в
**_Исследователь → Основные средства → Графики лизинговых платежей → ОС. График лизинговых платежей → Позиция документа → Мастер установок → Закладка "Шаблоны" → Сохранить шаблон_**:
![image](https://user-images.githubusercontent.com/11497453/150761782-847dcadf-555c-4075-8010-99a7e12165d3.png)

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
