### ISSUE TITLE
Мастер установок. Сплющивание грида при использовании расширенного отображения

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3950]
При вызове из Исследователя документа, в котором в гриде шапки используется расширенное отображение получаем сплющенный грид.
Принудительно нажав F5 (Обновить), грид приходит в нормальное состояние.
Так, приходится делать каждый раз.

![2017-04-21_134041](https://cloud.githubusercontent.com/assets/11497453/25274373/71065180-2698-11e7-8088-e3d8e984db97.png)

![2017-04-21_134054](https://cloud.githubusercontent.com/assets/11497453/25274374/71109104-2698-11e7-8b29-77c78eba36a2.png)

@ShlTanya , пожалуйста, реши вопрос.

Данную проблему обсуждали много-много лет назад.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
