### ISSUE TITLE
Мастер установок. Одновременное использование расширенного отображения и 2-х и более строчек (E/V)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3951]
![2017-04-21_134730](https://cloud.githubusercontent.com/assets/11497453/25274632/a007a9a6-2699-11e7-8aea-e7176e846c53.png)

@ShlTanya , пожалуйста, предусмотри возможность одновременного использования расширенного отображения и 2-х и более строчек.

На практике реально необходимо.
Удобно, когда в гриде много колонок с длинными названиями (даже сокращенными).
Данную проблему обсуждали много-много лет назад.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
