### ISSUE TITLE
Не работает поиск в скриптах. Опять.

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#3952]
Ищем так:
![image](https://cloud.githubusercontent.com/assets/11487200/25437916/897b77e8-2aa0-11e7-94fc-c93a7c1e859e.png)
Получаем
![image](https://cloud.githubusercontent.com/assets/11487200/25437952/9f2760de-2aa0-11e7-903e-d37b6f021be3.png)

А теперь так
![image](https://cloud.githubusercontent.com/assets/11487200/25437990/cab13eaa-2aa0-11e7-9bc8-73888b59c864.png)

Получаем
![image](https://cloud.githubusercontent.com/assets/11487200/25438063/f8952a16-2aa0-11e7-887a-38ab634640ec.png)

Ничего не замечаете?
А если так
```
SELECT
  TRIM(f.NAME) AS Name
FROM GD_FUNCTION f
WHERE  UPPER(f.SCRIPT)   SIMILAR TO '%[^[:ALNUM:]|&_]' || :N || '[^[:ALNUM:]|&_]%' ESCAPE ''
```

с параметром SAN_SUBTYPE_REQUEST,
получаем
```
NAME
usrg_actEditPermitOnExecute
htConst
usrg_actCreateRequestOnExecute
```

**Comment by gsbelarus** [comment]
А что не так? запрос вроде нашел тоже самое что и в окне показывается.

**Comment by alexandra-gsoftware** [comment]
самый первый вариант (который с галкой слово целиком) не находит один результат, который htConst

**Comment by alexandra-gsoftware** [comment]
Вот вам еще картинка
![image](https://cloud.githubusercontent.com/assets/11487200/25930090/dec1c46a-360c-11e7-8067-9b9bc19d9506.png)
Поиск нашел все инклюды ф-и Rebuild, но не нашел ни ее саму, ни где она вызывается

**Comment by gsbelarus** [comment]
@ShlTanya гляньте что там с этим поиском не так

**Comment by ShlTanya** [comment]
Исправила.. попробуйте.

**Comment by gsbelarus** [comment]
Проверить. Закрыть.

**Comment by alexandra-gsoftware** [comment]
вроде ошибка больше не была замечена, поиск работает.
