### ISSUE TITLE
Фильтры. Доработки по настройке при использование формул (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3956]
Пожалуйста, предусмотрите следующие возможности по настройке фильтров при использовании формул:

**1**. Необрезанное отображение наименований кнопок в форме **Условие пользователя**.
![1](https://cloud.githubusercontent.com/assets/11497453/25694267/7d27d812-30b6-11e7-94fc-b4928b046a71.png)
![2](https://cloud.githubusercontent.com/assets/11497453/25694303/a68ad36c-30b6-11e7-9253-822d64569df2.png)

----

**2**. Перечень признаков.
Например, при поиске нескольких различных цен их можно найти в разных частях отображаемого списка.
• Добавить сортировка признаков по возрастанию.
• Увеличить ширину отображаемого окна (автоматически или дать возможность ручной настройки) и увеличить шрифт до 9.
• Предусмотреть возможность прокрутки списка записей скроллом мышки.
• Увеличить размер записей.
• Предусмотреть возможность поиска поля по локализованному наименованию и/или по оригинальному. Как вариант, через сочетание клавиш **Ctrl + F**.

Все это вызывает неудобства при работе.
![3](https://cloud.githubusercontent.com/assets/11497453/25694346/dfa538b8-30b6-11e7-8c1b-88e4cb5aac9a.png)

Так, будет гораздо удобнее выполнять настройку фильтров.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри здесь.

**Comment by Polfath** [comment]
Сделал
