### ISSUE TITLE
Регистрация ошибок и пожеланий, обратная связь с пользователем

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3957]
1. Периодически, при загрузке Гедымина, мы спрашиваем у пользователя доволен ли он работой с программой. Если пользователь отвечает да, то пишем ответ в базу и на некоторое время не тревожим его, до следующего опроса.

2. Если пользователь ответил нет, то спрашиваем его, что именно не так: ошибка в программе, неудобно/медленно, пожелание/замечание, запрос на новый функционал.

3. В зависимости от предыдущего выбора просим дополнительную информацию. Например, если это ошибка, то с каким документом/окном/отчетом она связана. Какие шаги приводят к ее появлению и т.п. Пользователь может прикрепить файлы (я бы реализовывал это во втрую очередь).

4. Введенная информация записывается в базу данных. Назовем это Issue.

5. Периодически Гедымин связывается с нашим центральным сервером (скорее всего это будет тот же сервер, который раздает новые экзешники), но может быть и другой. Т.е. информацию о сервере надо отдельно получить. Из базы клиента передаются на центральную базу все непереданные записи. В базу клиента загружаются записи из центральной базы данных.

6. По каждому Issue может вестить дискуссия. Т.е. пользователь написал жалобу. Мы ему ответили -- запросили доп информацию. Он ответил нам, сообщил необходимые сведения. Мы ответили ему.

7. Каждый такой ответ может изменить статус записи. Статусы: **Открыто**, **Решено**, **Отклонено**, **Не актуально**.

8. Если пользователю пришел ответ, то при очередной загрузке Гедымина мы выводим ему на экран окно с перепиской. Показываем что ответ пришел. Если ответ закрывает Issue, то пользователь может или согласиться с этим, или переоткрыть, если проблема все еще не решена.

9. Получив ответ, пользователю может понадобиться время на проверку, тогда мы будем показывать ему следующий раз переписку, пока он не закроет Issue или не предоставит дополнительную информацию.

10. Одновременно на пользователя может быть открыто несколько Issue.

11. Предоставлять ответ (вести с пользователем переписку) мы можем как на своей центральной базе данных, так и на месте, на предприятии клиента. Т.е. должен быть режим администратора, где мы видим список Issue, можем поднять переписку по каждому.

12. Подсистема может использоваться и в обратную сторону, как доска объявлений и система обмена сообщениями, когда мы можем послать на конкретное предприятие, конкретному пользователю или группе пользователей некоторое сообщение.

Зачем все это надо:

-- В любой момент понять насколько довольны пользователи на предприятии программой.
-- Руководству клиента предоставить отчет. Например, на такое-то число 80% рабочих мест не имели замечаний к качеству ПО. На остальных были такие-то и такие-то вопросы.
-- Иметь прямой канал обратной связи с пользователем.

**Comment by NikolayUkleyko** [comment]
Идея весьма интересная и оригинальная.
Я предполагаю, что @ShlTanya это сделает без особых вопросов.

Я изложу свою точку зрения.

----

Существующая система регистрирования ошибок и отправки на e-mail.
По идее каждый сотрудник должен прорабатывать свои вопросы.
Я предполагаю, что эти письма сотрудникам не интересны по ряду причин (нет времени, не удобно представлены данные и т.д.).
Следует учесть, что помимо текущих задач не остается времени на проработку каждой присланной на e-mail ошибки.
Для нормального решения текущих ошибок необходимы отдельные специалисты, прошедшие достаточную подготовку.
Подразумевается, что такие специалисты будут только этим и заниматься.
Соответственно можно это проецировать и на новый функционал предоставления ошибок, предложений.

----

>Периодически, при загрузке Гедымина, мы спрашиваем у пользователя доволен ли он работой с программой. Если пользователь отвечает да, то пишем ответ в базу и на некоторое время не тревожим его, до следующего опроса.

Будет ли предусмотрена возможность настройки с полным отключением такого оповещения как глобально, так и отдельно на каждом рабочем месте ?
Это актуально.
Так как, на практике не каждый пользователь будет изъявлять желание заполнять форму.
Она будет попросту закрыта.
К тому же на практике любые программные сообщения сердят пользователей.
Они выбирают вариант **Больше не показывать** или что-то подобное.

----

>По каждому Issue может вестить дискуссия. Т.е. пользователь написал жалобу. Мы ему ответили -- запросили доп информацию. Он ответил нам, сообщил необходимые сведения. Мы ответили ему.

Это уже похоже на существующий форум.

----

>Подсистема может использоваться и в обратную сторону, как доска объявлений и система обмена сообщениями, когда мы можем послать на конкретное предприятие, конкретному пользователю или группе пользователей некоторое сообщение.

Это отличный функционал.
Про подобный функционал я давно писал.
Тогда эту идею не приняли.

**Comment by ShlTanya** [comment]
Задание приняла.. Вопросов уже много. Буду по мере необходимости их задавать.

**Comment by gsbelarus** [comment]
Issue со всей своей перепиской должно быть б/о. Механизм передачи должен
быть обобщен. Потом его применим к другим б/о, например, справочникам
товаров, клиентов, валют и т.п.

**Comment by ShlTanya** [comment]
б/о ??

**Comment by gsbelarus** [comment]
Бизнес объект

**Comment by YRozmysl** [comment]
Вот хорошая задумка  реализована, как связь конечного пользователя ПО и специалиста https://charter97.org/ru/news/2017/5/4/248808/

**Comment by gsbelarus** [comment]
Со скриншотом идея отличная.

Нет. Нельзя будет полностью выключить этот механизм. В известных пределах
можно будет регулировать период.

У нас постоянные конфликты с клиентами, когда высшее руководство не хочет
подписывать договора. Нас обвиняют, что "ничего не работает". Теперь у нас будет 
технический механизм спокойно парировать такие выпады. Вот вам отчет:
95% рабочих мест не высказали никаких претензий по остальным ситуация
такая-то и такая-то.

**Comment by gsbelarus** [comment]
Задача спокойно разбивается на две подзадачи. Первая: реализация б/о и пользовательского интерфейса. Эту часть спокойно можно будет ставить и работать в автономном режиме. Т.е. в таком режиме, когда все записи остаются в самой базе. В режиме администратора можно просматривать, давать ответыпользователям и т.п.

Вторая часть -- реализация обмена данными через интернет, синхронизация с центральной базой данных.

В таком порядке и надо делать.

Сейчас жду проработку структур данных и вперед!
