### ISSUE TITLE
Витебск МК. Склад. Формирование остатков по организации с холдингом

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3961]
По основной рабочей организации на закладке **Холдинг** выбрано дочернее предприятие.
В диалоге дочернего предприятия не заполнены реквизиты **Головное предприятие** и **Холдинг**.
При формировании остатков на дату по основной рабочей организации **пусто**.
Аналогично и по новым созданным формам остатков.

По идее так быть не должно.
Результат должен быть положительный.

----

В данной ситуации достаточно было в диалоге дочернего предприятия в реквизите **Головное предприятие** выбрать основную рабочую организацию.
Остатки сформировались корректно.

@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by MIchaelShoihet** [comment]
Надо исправить. Если в настройках остатков, документов стоит ограничение на рабочую компанию, то ни к какому холдингу мы обращаться не должны.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, не откладывай данный вопрос в долгий ящик.
Он приоритетный.

----

Не всегда на предприятии есть возможность часто обновлять gedemin.exe.
Все текущие правки и данная правку войдут в устанавливаемый gedemin.exe.

**Comment by ShlTanya** [comment]
Посмотрела. Поправьте как д.б.
Рабочая организация является холдингом (содержит дочерние предприятия):
Ситуация 1. В настройках остатков установлен признак Ограничение на раб. компанию - в остатках отображаются данные только по раб. организации (без дочерних)
Ситуация 2. В настройках остатков НЕ установлен признак Ограничение на раб. компанию - в остатках отображаются данные и по раб. организации и по дочерним.

Сейчас:  и в ситуации 1 и в ситуации 2  в остатках отображаются только остатки по дочерним (без рабочей организации).

**Comment by MIchaelShoihet** [comment]
Все правильно!

**Comment by NikolayUkleyko** [comment]
OK !

**Comment by ShlTanya** [comment]
Прошу еще 1 уточнение. Рабочая организация - это что??? (организация, которая выбрана в форме остатков или "основная" организация в программе (указана на главной форме)). Почему спрашиваю.
Признак в настройках остатков  Ограничение на раб. компанию  ограничивает выбор остатков именно по "основной" организации (с главной формы). 
Насколько я понимаю, в качестве холдинга может выступать любая организация. В таком случае данный признак будет дополнительным  для ограничения остатков. На самой форме остатков есть признак Не включать вложенные подразделения. Вот он и ограничивает остатки только по выбранной организации на форме остатков.

**Comment by MIchaelShoihet** [comment]
Рабочая организация и холдинг имеется ввиду только наш. Т.е. список организаций gd_ourcompany. Если выбрана любая другая организация, то остатки по ней строятся как по подразделению. Отдельно обрабатывается только наша организация.

**Comment by NikolayUkleyko** [comment]
>На самой форме остатков есть признак Не включать вложенные подразделения. Вот он и ограничивает остатки только по выбранной организации на форме остатков.

@ShlTanya , данный реквизит предназначался для того, чтобы при формировании остатков по верхнему подразделению исключить вложенные подразделения.
Это в силу специфики структуры справочников подразделений (сотрудников) на том или ином предприятии.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Теперь, остатки формируются по текущей рабочей организации с холдингом.
Если, в настройке остатков снять галку с реквизита **Ограничение на рабочую компанию** и программа выдаст следующее окно с сообщение об ошибке:

![2017-05-22_172935](https://cloud.githubusercontent.com/assets/11497453/26313930/11e4c8ea-3f15-11e7-97d1-f2c14e7f3a72.png)

**Comment by ShlTanya** [comment]
Николай... опишите, пожалуйста, ситуацию с ошибкой подробно.. Не могу ее повторить у себя.

**Comment by NikolayUkleyko** [comment]
>Николай... опишите, пожалуйста, ситуацию с ошибкой подробно.. Не могу ее повторить у себя.

1. По рабочей организации добавил на закладке **Холдинг** выбрал некую организацию.

2. В настройках остатков снял галку с реквизита **Ограничение на рабочую компанию**.

3. При формировании форма остатков программа выдает вышеприведенное окно с сообщением.

**Comment by ShlTanya** [comment]
Николай,  можете запрос получившийся мне дать??

**Comment by NikolayUkleyko** [comment]
@ShlTanya , не получится, так как в форме остатков при нажатии на кнопку **Сформировать (F5)** программа тут же выдает вышеприведенное окно с сообщением об ошибке.

**Comment by ShlTanya** [comment]
Посмотрела демо БД. Для ОС надо изменить скрипт **GetFromClause**. Достаточно след. кода: 
option explicit
function TgdcInvRemains147470194_50219829GetFromClause(Self, ARefresh)
  TgdcInvRemains147470194_50219829GetFromClause = _
    Inherited(Self, "GetFromClause", Array(Self, ARefresh))

  **dim Result
  Result = TgdcInvRemains147470194_50219829GetFromClause
  Result = Result & _
    " LEFT JOIN usr$fa_p_getrealamortterm( C_USR$FA_INVCARDKEY.ID , :REMAINSDATE  ) realamortterm ON 1 = 1 "
  TgdcInvRemains147470194_50219829GetFromClause = Result**
end function 

У Вас он переписан своим кодом.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , большое спасибо ! :trophy:
