### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Дублирование записи и позиционирование грида (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3966]
**Исследователь / Бухгалтерия / Журнал хоз. операций.**

При дублировании записи и нажатии на кнопку OK курсор автоматически произвольно становится на середину грида.
В данном случае курсор должен автоматически позиционироваться на новую добавленную запись.

Данная тема особенно актуальна для Витебск БПФ, эталона и для всех других БД.

----

@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
