### ISSUE TITLE
Витебск БПФ. Очень длительная синхронизация ПИ

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3971]
На БД Витебск БПФ очень длительная синхронизация ПИ.

![2017-05-12_104323](https://cloud.githubusercontent.com/assets/11497453/25988357/52401e5c-3700-11e7-8224-0c0a5edadf6b.png)

Данный процесс занимает часы.
Это нездоровое явление.
На других БД МК синхронизация выполняется в течение нескольких минут.
@gsbelarus , пожалуйста, решите данный вопрос.

----

Добавлю.
Ситуация.
Необходимо установить определенные ПИ.
Это могут быть ПИ, которые вообще не установлены на БД.
Также могут это могут быть ПИ, которые будут установлены с выбранным реквизитом **Всегда перезаписывать**.
В данном случае нет намеренной необходимости сравнивать устанавливаемые ПИ и ПИ на БД.
@gsbelarus , пожалуйста, предусмотрите режим простой установки ПИ.
Как с настройками  - выбрал и установил без лишних действий.

**Comment by gsbelarus** [comment]
Что-то же уже правили в данном направлении. Там последний экзешник?

**Comment by NikolayUkleyko** [comment]
>Что-то же уже правили в данном направлении. Там последний экзешник?

Предположительно ничего не меняли.
Скинул Вам путь к офисной БД.
Для примера можно выбрать папку **Основные средства**.

**Comment by alexandra-gsoftware** [comment]
буквально вчера синхронизировали на бро по удаленке - минут 20.

**Comment by NikolayUkleyko** [comment]
>буквально вчера синхронизировали на бро по удаленке - минут 20.

Юра, подтвердит, что долго на офисе и на удаленке.
20 минут это тоже не вариант.
Предусмотреть простой вариант установки ПИ.

**Comment by YRozmysl** [comment]
да, не быстро, но тут зависит еще и того какие объекты в ПИ.

**Comment by gsbelarus** [comment]
Сейчас уже не будет  зависеть. Экзешник надо будет обновить. Скоро выложу.

**Comment by NikolayUkleyko** [comment]
>Сейчас уже не будет зависеть. Экзешник надо будет обновить. Скоро выложу.

Ждем с нетерпением.
