### ISSUE TITLE
Грид. Позиция документа. Выпадающий список с древовидной структурой данных

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3974]
**Исследователь / Зарплата и Отдел кадров / Зарплата / Ручной ввод.**

Напомню, что это пользовательский документ.

На gedemin.exe
Дата файла           = 27.01.2017
Версия файла         = 2.9.3.8971

В позиции документа в поле при вызове выпадающего списка получаем **_древовидную структуру данных_**:

![1](https://cloud.githubusercontent.com/assets/11497453/26098453/7580d1f8-3a30-11e7-9702-33c503846ddc.png)

На gedemin.exe
Дата файла           = 12.05.2017
Версия файла         = 2.9.3.9145

В позиции документа в поле при вызове выпадающего списка получаем **_данные в виде списка_**:

![2](https://cloud.githubusercontent.com/assets/11497453/26098474/7e362f8c-3a30-11e7-97c7-47874777c4df.png)

В редакторе объектов в свойствах колонки следующие параметры:

![3](https://cloud.githubusercontent.com/assets/11497453/26099054/43d4c2ca-3a32-11e7-98d1-1423eecd4495.png)

Здесь же указано, как отображать данные - по классу.
Класс, как дерево.
В чем же дело ?

@ShlTanya , пожалуйста, предусмотри, чтобы грид **пользовательских , складских документов, справочников и в остальных случаях** корректно работал согласно настроек в редакторе объектов.

На практике приходится принудительно прописывать как отображать данные в выпадающем списке (вид, фильтрация, сортировка и т.д.).
Это крайне неудобно.

Данная проблема встречалась давно в некоторых формах.
Напрягает.
Необходимо основательно разобраться.
Если, в платформе предусмотрен один из нескольких существующих вариантов визуальной настройки грида, то он должен работать корректно.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Теперь структура данных в выпадающем списке соответствует заданным параметрам.

----

@ShlTanya , скажи, пожалуйста, работает ли сортировка ?
Указал **SotrOrder - SoAsc**.
Сортировки нет.
Должно работать корректно.

----

@ShlTanya , что по фильтрации данных с указанием условия в **Condition** ?

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
