### ISSUE TITLE
Грид. Позиция документа. ColumnEditors. Добавить описание колонок и поиск

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3975]
![1](https://cloud.githubusercontent.com/assets/11497453/26099881/c8cbedda-3a34-11e7-80d3-6209a907946e.png)

Абсолютно не информативно.
На практике крайне неудобно искать требуемое поле.

@ShlTanya , пожалуйста добавь описание колонок и предусмотри возможность поиска.

**Comment by NikolayUkleyko** [comment]
@ShlTanya .

**Comment by ShlTanya** [comment]
Уточните, как вызывается данное окно.

**Comment by NikolayUkleyko** [comment]
Ctrl + Alt + M → кликаем мышкой по гриду позиции документа → Column editors.


вт, 15 мар. 2022 г., 8:00 ShlTanya ***@***.***>:

**Comment by ShlTanya** [comment]
Сейчас данное окно (при редактировании колонок грида из редактора форм) выглядит так: 
![Снимок](https://user-images.githubusercontent.com/24572314/161258981-aa57f2de-54e7-4365-a0bb-83d8c1191c89.JPG)

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, обрати внимание на две похожие команды и их свойства.
В ColumnEditors можно выполнить настройки look-up, в Columns — нет.
При этом в ColumnEditors и в Columns разное количество записей.
То есть, это не одно и тоже.
![image](https://user-images.githubusercontent.com/11497453/161264577-01764a3e-e228-4b95-b182-fdc07971b802.png)
![image](https://user-images.githubusercontent.com/11497453/161264725-56253db2-1a63-4be8-a434-40f6b160244c.png)

-----

Если, это сложно или по другим аргументам не сделать, то хотя бы для окна со списком полей ![image](https://user-images.githubusercontent.com/11497453/161265550-37f7adf9-54f8-4ed2-a96a-025036343d87.png)
предусмотри следующее:
1. По умолчанию увеличить размер открываемого окна.
2. Добавить строку или меню и т.д. для поиска поля по его наименованию.

**Comment by NikolayUkleyko** [comment]
@DonPhantom000 , пожалуйста, посмотри.

**Comment by DonPhantom000** [comment]
Изменен редактор для списка колонок на такой формат: 
№ - Описание поля - ИМЯ_ПОЛЯ

![image](https://user-images.githubusercontent.com/111727555/186933441-d7d91311-a9e6-47de-9756-7e5a08ea3f12.png)

Поиск строки по нажатию ENTER будет работать и для других списков

**Comment by NikolayUkleyko** [comment]
> Изменен редактор для списка колонок на такой формат: № - Описание поля - ИМЯ_ПОЛЯ
> 
> ![image](https://user-images.githubusercontent.com/111727555/186933441-d7d91311-a9e6-47de-9756-7e5a08ea3f12.png)
> 
> Поиск строки по нажатию ENTER будет работать и для других списков

@DonPhantom000 , пожалуйста, уточни, вышеприведенное актуально для команды **ColumnEditors** в Инспекторе объектов.
Так ли ?

**Comment by NikolayUkleyko** [comment]
Проверено.
Сейчас это сделано для команды **Columns**, а не для **ColumnEditors**.
При возможности необходимо реализовать детальное отображение имен полей для команды **ColumnEditors**.

**Comment by NikolayUkleyko** [comment]
Следующие замечания и предложения для поиска колонок для **ColumnEditors**:
1. Предусмотреть поиск колонок.
2. Предусмотреть команду **F3** для выполнения перехода к следующей найденной колонке.
3. Найденные колонки выделяются светло-серым цветом и едва заметны. Предусмотреть выделение цветом по аналогии как в Мастере установок или другой вариант.

Для примера можно рассмотреть документ: 
_**Исследователь / Материальный склад / 01. Накладная на получение материалов, ОС, МБП**_.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
