### ISSUE TITLE
Бухгалтерия.  Предусмотреть унифицированный механизм добавления кнопки 'Проводки' (Q) (E/V)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3978]
Пожалуйста, предусмотрите стандартный механизм добавления кнопки **Проводки**.
Предположительно, в типовой документ добавьте реквизит **Отображать кнопку 'Проводки'**.
Так, будет проще при разработке документов и выполнении настроек по данной кнопке.

**Comment by PiuPauTralala** [comment]
Да, это было бы отлично, а то сейчас множество примерно одинаковых функций в разных модулях. Это нужно и полезно как признак типового д-та. Возможно неплохо бы, вывести эту галку для доступа в коде.
