### ISSUE TITLE
GETCOMPLEXCASE не определяет мужской род прилагательного по окончанию -ой

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#3979]
Есть база конкретная на которой некорректно склоняется наименование. Причем  непонятна закономерность, например, "**по 12.Кишечному участку**", НО почему-то  **"по 14.Жировому участок"**   Как поиск причины, и цифра из наименования убиралась, и копировалось слово целиком из того наименования в котором    все корректно.  Результат тот же - неверный.

**Comment by gsbelarus** [comment]
Это же тебе не искусственный интеллект.

**Comment by YRozmysl** [comment]
так и отвечу на ММК)

**Comment by gsbelarus** [comment]
И чтобы два раза не ходить:

http://www.gsbelarus.com/gs/wiki/index.php/Gedemin_TLB.IgsApplication.GetComplexCase
