### ISSUE TITLE
Общие. SQL-редактор. Как работает кнопка 'Заменить РУИД'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3980]
**SQL-редактор / кнопка 'Заменить РУИД'**

![2017-05-25_183457](https://cloud.githubusercontent.com/assets/11497453/26457661/af224a68-4179-11e7-9986-38da1e490915.png)

Пожалуйста, подскажите, как работает данная кнопка ?

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by gsbelarus** [comment]
http://gsbelarus.com/gs/wiki/index.php/%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80_SQL
