### ISSUE TITLE
Кнопка "Только отмеченные"

### ISSUE THREAD

**Issue by hirurg-lybitel** [GoldenSoftwareLtd/gedemin#3981]
@ShlTanya

Не в первый раз сталкиваюсь с тем, что клиенты открывают документ, а в нём либо не все записи, либо нет их вовсе.  И всё из-за того, что активна кнопка **Только отмеченные**. 
Хотелось бы, чтобы при открытии формы эта кнопка сбрасывалась. 
Ну или выдавать сообщение вроде того, что выпадает при активном фильтре.

**Comment by stasgm** [comment]
О, да. Истерики "у нас все пропало!!!" не один раз слышал)

**Comment by NikolayUkleyko** [comment]
>Хотелось бы, чтобы при открытии формы эта кнопка сбрасывалась.

Не соглашусь.
Не будем делать поспешных выводов.
Ведь на практике некоторым пользователям удобно, чтобы по умолчанию отображались только отмеченные записи.
Кому-то удобно, а кому-то нет.
Необходимо найти общий вариант решения вопроса.

----

По кнопке **Только отмеченные** могу сказать то, что в случае добавления некоторых записей в отмеченные, а потом удаление таких записей из документов (не из отмеченных), то при открытии формы документа с активной кнопкой **Только отмеченные** грид будет пуст.
Это предсказуемое поведение программы.
Как раз здесь, можно предусмотреть окно с предупреждением.

----

Как вариант, можно в глобальных параметрах программы и/или для каждого пользователя предусмотреть параметры для настройки поведения кнопки **Только отмеченные** при открытии формы документа.

**Comment by hirurg-lybitel** [comment]
> Как вариант, можно в глобальных параметрах программы и/или для каждого пользователя предусмотреть параметры для настройки поведения кнопки Только отмеченные при открытии формы документа.

Это уже перебор.

Тогда просто информационное сообщение об активности этой кнопки.

**Comment by NikolayUkleyko** [comment]
>Это уже перебор.

Момент.
У нас есть параметр **Всегда запрашивать параметры для текущего фильтра и предупреждать о фильтрации данных**.

![2017-05-26_171731](https://cloud.githubusercontent.com/assets/11497453/26498456/c7a0a15c-4237-11e7-8fa8-ce64a1d10271.png)

В случае ее активации, при загрузке рабочего стола и открытии форм документов программа будет выдавать окно с параметрами фильтрации.
Это в случае, когда фильтры до закрытия БД уже были применены.

@hirurg-lybitel , я же не говорю, что надо сделать именно так.
Мы просто обсуждаем данную тему.

**Comment by gsbelarus** [comment]
Два варианта:

0) оставить как есть
1) предупреждать всегда, если есть отмеченные

**Comment by NikolayUkleyko** [comment]
Вариант с предупреждением хороший.

**Comment by ShlTanya** [comment]
Сделала предупреждение перед открытием формы. Посмотрите, достаточно ли.

**Comment by NikolayUkleyko** [comment]
Проверено.
![image](https://user-images.githubusercontent.com/11497453/151332869-3b3187e4-d818-4d46-be38-66f7eac55bff.png)
@ShlTanya , пожалуйста, поправь следующее:

1. Слово **Внимание !** перемести в заголовок окна сообщения.
2. Для позиции документа не работает такая проверка (пример, **_Исследователь → Материальный склад → 01. Накладная на получение материалов, ОС, МБП_**).

**Comment by gsbelarus** [comment]
Это окно появляется до открытия самой формы. Поэтому в заголовке должно присутствовать название документа/справочника, к которому относится это окно.

Другое дело что лишняя тут путаница отмеченные/выбранные. У пользователя позникнет вопрос одно ли это и тоже.

**Comment by NikolayUkleyko** [comment]
Хорошо.
Тогда, порядок.
Оставляем, как есть.
При работе с документами, справочниками не забываем про отдельное добавление записей из позиции в отмеченные и их отображение.

**Comment by ShlTanya** [comment]
Доделаю. Не закрывайте.

**Comment by ShlTanya** [comment]
Доработано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
