### ISSUE TITLE
Основные средства. Выбор из остатков в документах. Не показывать уже выбранные позиции (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3985]
В подсистеме **Материальный склад** при выборе из остатков в документах **_предусмотрено скрытие_** уже выбранных позиций.
Это логично и понятно.
Работает корректно.
В данном случае в основе лежит таблица INV_CARD.

В подсистеме **Основные средства** при выборе из остатков в документах (**ОС. Изменение свойств, ОС. Допоступление/Списание затрат, ОС. Начисление амортизации и т.д.** ) **_не предусмотрено скрытие_** уже выбранных позиций.
Это не логично.
В данном случае в основе лежат таблицы INV_CARD и USR$FA_INVCARD.

Как временная и некорректная мера в методах дописать определенные условия на скрытие уже выбранных позиций.
Необходимо это реализовать основательно и верно на уровне gedemin.exe.

Это является важным вопросом.
Кто работает с подобными задачами, тот понимает.
Все это имеет место и для подсистемы **Учет спецодежды** и других.

Коллеги, пожалуйста, изложите, Ваши, точки зрения по рассматриваемой теме.

**Comment by MIchaelShoihet** [comment]
Абсолютно не понятно что вы имеете ввиду под скрытием позиций. ОС и материальный склад и спецоджеда работают на одних и тех же документах. Позиции ни где специально не скрываются, все с чем вы работаете это остатки и если на указанном подразделении их нет, то они не отображаются, если они есть то они отображаются и нет больше никаких ограничений. Поэтому естественно при выборе в документах не изменяющих остатки позиции будут видны всегда сколько бы вы их не выбирали в документ. И тут любое изменение может вызвать кучу побочных эффектов. Поэтому лучше не трогать.

**Comment by PiuPauTralala** [comment]
Имеется ввиду, что один и тот же ОС можно выбрать бесконечное количество раз в одном и том же документе, например, амортизации. Это дает просторное поле для ошибок пользователям. Если как-то разрешить такую ситуацию, то и форма выбора остатков станет логичнее: мы в ней не будем видеть уже выбранные ОС, и ошибочно выбрать дважды один и тот же объект будет нельзя.

**Comment by MIchaelShoihet** [comment]
Я понимаю, что имеется в виду. Но решения в общем виде я не вижу... Форма отображает остатки и выбор товара в форму еще не означает, что его нельзя выбрать еще раз в общем случае. В документе можно настроить проверку,  что бы не выбирать. А любое вмешательство в форму просмотра остатков может привести к еще большему замедлению их построения

**Comment by PiuPauTralala** [comment]
Получается как с ускорением построения остатков на старом exe - придётся писать костыли.

**Comment by MIchaelShoihet** [comment]
Что значит костыли? В данном случае - это функциональность конкретного документа. Если в документе нельзя выбрать одну позицию два раза, то это функциональность конкретного документа и обрабатывать ее надо нормально, программируя нормальный код.

**Comment by ShlTanya** [comment]
Можно сделать в форме выбора из остатков проверку на добавление позиции в выбранные значения на уже существующую позицию.

**Comment by MIchaelShoihet** [comment]
В общем случае как вы это сделаете? Ведь можно выбрать не весь остаток, а только часть. Можно выбрать из одного остатка несколько позиций с разными значениями и это тоже может иметь место...
Плюс сама идентификация, что этот остаток соответствует выбранной позиции в общем случае не простая задача.

**Comment by NikolayUkleyko** [comment]
>Плюс сама идентификация, что этот остаток соответствует выбранной позиции в общем случае не простая задача.

В части ОС проверка на количество = 1.

**Comment by MIchaelShoihet** [comment]
В части ОС да. Но гедемин про ОС ничего не знает. Это надо выносить уже на уровень самого документа.

**Comment by ShlTanya** [comment]
Михаил, а если ставить задачу не полной идентификации позиции.. а сравнение только по Goodkey или Cardkey. И при наличии выводить только сообщение (не запрещать). И данную проверку сделать как опцию в настройках типовых документов. 
Либо можно подумать про вариант проверки на дубли позиций при выходе из выбора из остатков. А не на каждую позицию. И при наличии тоже выводить только сообщение.

**Comment by NikolayUkleyko** [comment]
>И при наличии выводить только сообщение (не запрещать). И данную проверку сделать как опцию в настройках типовых документов.

Хороший вариант тем, что он включаемый/отключаемый и только информативный.
То есть, нет жесточайшего запрета.

**Comment by MIchaelShoihet** [comment]
Скажем так идентификацию можно проводить по полю, которое мы указали для ускорения вывода остатков и goodkey, в случае когда поля откуда и куда совпадают, (если они не совпадают, у нас это контролируется количеством и проверка будет лишней) и только с выводом сообщения.

**Comment by ShlTanya** [comment]
Что делать с документами, в которых отсутствует поле куда или откуда.

**Comment by MIchaelShoihet** [comment]
Поля такие всегда есть они либо в шапке либо в позиции и проверять вы можете только на то, если поле откуда и куда одно и то же.

**Comment by ShlTanya** [comment]
Немного не так спросила. Я имела в виду, например, Отпуск на сторону. Куда - это Клиент.. В данном документе откуда не будет равно куда. Значит в таких документах не делать проверку??

**Comment by MIchaelShoihet** [comment]
в таких документах у нас остаток списывается и это само отражается. Проблема только там где остаток не изменяется, а меняются только свойства.

**Comment by ShlTanya** [comment]
Спасибо. Я поняла.
