### ISSUE TITLE
Бухгалтерия. Создать блокировку периода только по бухгалтерским счетам (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3986]
Можно ли предусмотреть простую блокировку данных до даты по всем бухгалтерским счетам кроме указанных, как исключение ?
Существующая блокировка периода по документа и группам пользователям менее удобна.

Коллеги, какова, ваша, точка зрения ?

**Comment by NikolayUkleyko** [comment]
Предполагаемая здесь

Блокировка периода (постановка) — GedeminWiki
http://gsbelarus.com/gs/wiki/index.php/%D0%91%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0_%D0%BF%D0%B5%D1%80%D0%B8%D0%BE%D0%B4%D0%B0_(%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0)

блокировка периода имеет массу настроек.
Можно ли сюда добавить блокировку по критерию **Бухгалтерский счет** ?

На практике каждый бухгалтер сдает Журналы-ордера и прочие отчеты со своими бухгалтерскими счетами.
Блокировка по критерию **Тип документа, Группа пользователей** не всегда гибка.

@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by NikolayUkleyko** [comment]
@ShlTanya сказала, что у нее есть выполненное задание по теме глобальной блокировки периода (ссылка приведена выше).
@gsbelarus , @MIchaelShoihet , пожалуйста, посмотрите наработки @ShlTanya и по возможности включите данный функционал в gedemin.exe.
На МК данная тема актуальна.
Можно уточнить у коллег.
Сейчас используются различные локальные блокировки, что не есть хорошо.

**Comment by ShlTanya** [comment]
:) NikolayUkleyko.. я не говорила про выполненное.. я говорила, о том, что посылала документ для проработки. Там много нюансов.

**Comment by NikolayUkleyko** [comment]
Хорошо, @ShlTanya .

**Comment by NikolayUkleyko** [comment]
Снова возвращаемся к данной теме.
На Витебск МК и других МК это актуально.
Бухгалтера сверив отчеты, переходят к следующему периоду.
Спустя, некоторое время кто-то из пользователей на производстве меняет цену, что приводит к искажениям в уже проверенном периоде.
Потом начинаются поиски расхождений.

@gsbelarus , пожалуйста, изложите Вашу точку зрения.

**Comment by gs7600300** [comment]
Да, подтверждаю - актуально. И если есть возможность, нужно уделить этому вопросу особое внимание.

**Comment by NikolayUkleyko** [comment]
Тем более, что @ShlTanya очень желает доделать данную разработку.
Только ей нужны подсказки для правильной реализации.

**Comment by NikolayUkleyko** [comment]
По ходу рассматриваемая тема не будет реализована.
Поэтому, ее закроем.
