### ISSUE TITLE
Бухгалтерия. Конструктор функций. Множественное отображение окна результата поиска (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3987]
**Исследователь / Бухгалтерия /  Типовые хоз. операции, Автоматические хоз. операции, Настройка функций / Конструктор функций.**

При неоднократном нажатии на кнопку поиска каждый раз появляется дублирующееся окно с результатами поиска.

![2017-06-05_121703](https://cloud.githubusercontent.com/assets/11497453/26778545/5f1ddf18-49ea-11e7-815b-32b203996d07.png)

Для выхода из конструктора функций необходимо закрыть каждое такое окно.

Пожалуйста, предусмотрите, чтобы в подобном случае отображалось одно окно с результатами поиска.

**Comment by gsbelarus** [comment]
Так может один раз нажимать?

**Comment by NikolayUkleyko** [comment]
Для точности приходится нажимать несколько раз.
В других программах такого нет.
Если, это очень сложно - не делайте.
