### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Предусмотреть прокрутку панели параметров скроллом мышки (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3988]
**Исследователь / Бухгалтерия / Журнал-ордер, Карта счета, Анализ счета, Оборотная ведомость, Главная книга.**

Пожалуйста, предусмотрите следующее:

1. **Добавить** возможность прокрутки панели параметров скроллом мышки

![2017-06-09_145654](https://user-images.githubusercontent.com/11497453/26975027-bf343d22-4d26-11e7-9cc0-c682842c2ab8.png)

----

2. **Убрать** возможность прокрутки значение в поле **Счет**

![2017-06-09_145820](https://user-images.githubusercontent.com/11497453/26975069-f403f07e-4d26-11e7-96b4-7c181db67a54.png)

----

3. **Убрать** возможность прокрутки значений в полях аналитик

![2017-06-09_150020](https://user-images.githubusercontent.com/11497453/26975094-0809f7da-4d27-11e7-8424-ac7259c14749.png)

----

Так, будет гораздо удобнее работать с бухгалтерскими формами.

**Comment by PiuPauTralala** [comment]
Прокрутка скроллом не так уж и плоха, если сделать ее в выпадающем списке, а не в выделенном поле.

**Comment by NikolayUkleyko** [comment]
@MBurakina , я так и имею в виду: убрать прокрутку из поля, оставить ее в списке.

**Comment by NikolayUkleyko** [comment]
Сейчас можно случайно прокрутить скролл мышки на любом реквизите параметров формирования формы: Счет, Аналитика и другие.
Что не есть хорошо.
Так как, будет разница между уже сформированной формой и указанными параметрами.
