### ISSUE TITLE
Firebird v.2.5. Назначение PDB-файлов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3990]
@gsbelarus , пожалуйста, подскажите, зачем в Snapshot Firebird v.2.5 следующие **PDB-файлы**:

![2017-06-13_200653](https://user-images.githubusercontent.com/11497453/27094937-881fa67c-5074-11e7-8af8-6cbe07696816.png)

**Comment by stasgm** [comment]
Это не сборка такая. Это ты скачал архив с файлами для отладки (64\32-bit Debug Kits (Binary + PDB components))
А качать надо из раздела 64\32-bit Classic, Superclassic & Superserver

**Comment by NikolayUkleyko** [comment]
@stasgm , это понятно.
Snapsot брался именно этот:

![2017-06-14_105242](https://user-images.githubusercontent.com/11497453/27121641-c8c7f8d8-50f0-11e7-9658-2632d5102e04.png)

**Comment by stasgm** [comment]
Чтобы было понятно, что за сборка качай отсюда https://www.firebirdsql.org/en/firebird-2-5/

**Comment by NikolayUkleyko** [comment]
@stasgm , я веду речь про Snapshot, а не инсталляцию.
Меня интересует именно Snapshot.
Я могу скинуть архивы с файлами и разница очевидна.

**Comment by gsbelarus** [comment]
Это отладочная информация. В повседневной работе она не нужна, но и ничем не мешает.

**Comment by NikolayUkleyko** [comment]
>Это отладочная информация. В повседневной работе она не нужна, но и ничем не мешает.

Это я и хотел узнать.
@gsbelarus , большое спасибо !
