### ISSUE TITLE
Бухгалтерия. Скорость формирования 'Оборотной ведомости, Главной книги' на крупных БД (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3991]
**Исследователь / Бухгалтерия / Оборотная ведомость / Главная книга.**

На практике на БД крупных предприятий скорость формирования таких форм невысокая.
Да, у нас предусмотрен режим **Переход на новый месяц**:

![2017-06-13_201333](https://user-images.githubusercontent.com/11497453/27095214-86986572-5075-11e7-85d0-e099858059f3.png)

В случае внесения изменений в месяце, то, как обновить результаты расчета по данному месяцу ?

----

Существуют ли возможности, не используя функционал по переходу на новый месяц, значительного ускорения формирования вышеприведенных бухгалтерских форм ?
Firebird v.3.0 имеет свои недостатки на маломощных серверах.
Память, одна БД и т.д. и т.п
Что предполагается в Firebird v.4.0 ?

Мощный сервер это не есть качественное ускорение формирования форм.
Нельзя ли предусмотреть кардинальное изменение алгоритма формирования бухгалтерских форм ?

**Comment by MIchaelShoihet** [comment]
Каким образом. Во всех ситемах скорость работы достигается только за счет именно расчета промежуточного сальдо, что и делает переход на новый месяц. Я им пользуюсь на бройлерах и скорость построения стандартных отчетов на порядок быстрее. Другие методики могут убыстрить на проценты все равное везде где надо считать сальдо - его надо посчитать.

**Comment by NikolayUkleyko** [comment]
>Я им пользуюсь на бройлерах и скорость построения стандартных отчетов на порядок быстрее.

Как удалить расчет за месяц ?
Или как обновить данные за месяц ?
