### ISSUE TITLE
FastReport 4 и моб. устройства

### ISSUE THREAD

**Issue by hirurg-lybitel** [GoldenSoftwareLtd/gedemin#3993]
При отправке отчёта FastReport 4 в PDF формате и попытке открыть его на моб. устройстве, русские буквы исчезают. Хотя при открытии этого же файла на компьютере всё хорошо.

@stasgm 
@ShlTanya 
@gsbelarus

**Comment by arthur-latunov** [comment]
при экспорте в PDF признак [Встроить шрифты] была "птица"?

21 июня 2017 г., 12:17 пользователь hirurg-lybitel <notifications@github.com

**Comment by hirurg-lybitel** [comment]
Речь идёт об отправке на email. Там такого признака нет.

**Comment by gsbelarus** [comment]
На мобильном есть разные просмотрщики. Во всех неправильно выводится?

On Jun 21, 2017 16:51, "hirurg-lybitel" <notifications@github.com> wrote:

Речь идёт об отправке на email. Там такого признака нет.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/GoldenSoftwareLtd/gedemin/issues/3993#issuecomment-310084924>,
or mute the thread

**Comment by hirurg-lybitel** [comment]
Все стандартные

**Comment by stasgm** [comment]
У меня на в pdf на месте текста пустота

**Comment by hirurg-lybitel** [comment]
@gsbelarus так что с решением этой проблемы? Клиенты негодуют

**Comment by gsbelarus** [comment]
решения не будет. надо пробовать другие шрифты. и на чем я могу потестить?

**Comment by gsbelarus** [comment]
ну и 25 секундное гугление приводит сюда:

https://stackoverflow.com/questions/6844831/any-good-pdf-export-filter-that-works-with-fast-report

**Comment by gsbelarus** [comment]
простого решения нет. не простое:

1. купить фр 5 и посмотреть может иэ экспортер подойдет к четвертому. может и не подойти.
2. купить https://www.gnostice.com/nl_article.asp?id=249&t=Export_From_FastReport_To_PDF_And_Other_Formats и встроить их экспортер. Не известно на сколько это утяжелит экзешник.

**Comment by hirurg-lybitel** [comment]
Так если сохранять в файл pdf с признаком **Встроенные шрифты**, то всё нормально отображается.

Нельзя ли просто при отправке по почте из фастрепорта делать тоже самое?

**Comment by gsbelarus** [comment]
конечно можно. посмотрю сегодня-завтра

2017-09-15 12:18 GMT+03:00 hirurg-lybitel <notifications@github.com>:

**Comment by NikolayUkleyko** [comment]
>купить фр 5 и посмотреть может иэ экспортер подойдет к четвертому. может и не подойти.

Если, это нам требуется для работы, то почему нет ?

**Comment by gsbelarus** [comment]
> Так если сохранять в файл pdf с признаком **Встроенные шрифты**, то всё нормально отображается.
> 
> Нельзя ли просто при отправке по почте из фастрепорта делать тоже самое?

надо так и сделать

**Comment by gsbelarus** [comment]
@ShlTanya гляньте. по идее в одну строчку исправление.

**Comment by gsbelarus** [comment]
@hirurg-lybitel проверяй на бета версии экзешника. я поставил по умолчанию встраивать шрифты для PDF экспорта из FR4.

**Comment by gsbelarus** [comment]
@hirurg-lybitel проверил? закрываем?

**Comment by hirurg-lybitel** [comment]
да, норм
