### ISSUE TITLE
Витебск БПФ. Бухгалтерия. Ошибка External exception...

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3994]
**Исследователь / Бухгалтерия / Типовые хоз. операции.**

На RDP-подключении ошибка при работе с типовыми проводками:

![2017-06-28_170730](https://user-images.githubusercontent.com/11497453/27641435-772754a8-5c24-11e7-84f7-2303b3ff1a4b.png)

Такое часто замечал на Витебск БПФ и при работе с другими объектами.
Подобное иногда имеет место и для других МК.

Gedemin.exe на данном предприятии не совсем актуальный.

**Comment by gsbelarus** [comment]
Много раз обсуждалось:

http://gedemin.blogspot.com.by/2016/12/external-exception-c0000006.html
