### ISSUE TITLE
Витебск БПФ. Бухгалтерия. Журнал хоз. операций. Сторнирование проводок за период (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3996]
**Исследователь / Бухгалтерия / Журнал хоз. операций / Сторнировать проводку.**

Пожалуйста, предусмотрите возможность формирования сторнирующих проводок по выделенным записям (проводкам).
Хорошо бы дополнительно предусмотреть параметр **Период сторнируемых проводок**.
На практике, например, для расчетов по расходам будущих периодов по лизингу такие возможности очень кстати.

**Comment by PiuPauTralala** [comment]
т.е. сначала они насоздают доки на пять лет вперед, а потом хотят сторно за период.
на практике это усложнение, неизбежно приводящее к ошибкам.

**Comment by NikolayUkleyko** [comment]
>т.е. сначала они насоздают доки на пять лет вперед, а потом хотят сторно за период.

Доки они создавали еще в 2010 г. и позже.
Это был другой бухгалтер и методика была иная.

>на практике это усложнение, неизбежно приводящее к ошибкам.

Если, это делать аккуратно, то результат верный.

**Comment by NikolayUkleyko** [comment]
Скажу проще.
Есть такая ситуация.
В принципе нормальная, исходя из вышеизложенных данных.

----

Если, нет, то есть ли иное решение подобных вопросов ?

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.
Это же все-таки Витебск БПФ.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by gsbelarus** [comment]
Она в отпуске до 25.

**Comment by NikolayUkleyko** [comment]
>Она в отпуске до 25.

Хорошо.
Позже продолжим.

**Comment by NikolayUkleyko** [comment]
На Витебск БПФ снова подняли данный вопрос.
Нам крайне очень не хватает возможности сторнирования проводок за указанный период.
Существующего функционала сторнирования проводок по документу недостаточно, так как сторнируются все проводки, а удаление лишних сторнирующих проводок приводит к удалению всех созданных сторнирующих проводок.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by NikolayUkleyko** [comment]
Хм, интересно, а это же просит Витебск БПФ, а не другие менее приоритетные клиенты.

**Comment by NikolayUkleyko** [comment]
Мне не первый раз звонит бухгалтер с Витебск БПФ и просит предусмотреть данную возможность.
Сейчас они не могу нормально работать с НДС по 18-м счетам.
Соответственно здесь задействованы и ЭСЧФ.
Им необходимо ежемесячно отражать данные.
Сейчас они сводно вводят данные вручную предварительно посчитав.
Объем данных увеличивается, что только усложняет ситуацию.

@gsbelarus дайте @ShlTanya отмашку на то, что предусмотреть данную возможность или есть другие причины, по которым это нельзя сделать ?
