### ISSUE TITLE
Проверка допустимого сабтайпа в лукапе раньше, чем присваивается класс

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#3997]
На новейшем gedemin.exe выявлены следующие ошибки:

![2017-07-11_095807](https://user-images.githubusercontent.com/11497453/28055006-de2f1f00-661f-11e7-9969-c47663d48c97.png)

![2017-07-11_095849](https://user-images.githubusercontent.com/11497453/28055013-e0ee9f68-661f-11e7-96a8-6658c0707ea8.png)

при добавлении/редактировании записей в следующие документы Взаимозачет, 01. Накладная на получение материалов, ОС, МБП и другие.

@gsbelarus , пожалуйста, устраните вопросы.

----

**На gedemin.exe, где дата файла = 06.07.2017, версия файла = 2.9.3.9281 таких ошибок нет.**

**Comment by gs7600300** [comment]
Актуально на СКХП.

**Comment by NikolayUkleyko** [comment]
Городок ПФ и другие клиенты, обновившие gedemin.exe до новейшего с вопросами.

**Comment by gsbelarus** [comment]
есть у нас бд где проверить?

**Comment by NikolayUkleyko** [comment]
>есть у нас бд где проверить?

Абсолютно любая БД.

**Comment by alexandra-gsoftware** [comment]
С этім контрактом всекда былі проблемы. Там есть два договора, и два домена, и настройки доменов постоянно слетали, один договор менялся на другой...

**Comment by NikolayUkleyko** [comment]
>настройки доменов постоянно слетали, один договор менялся на другой...

То есть, сами по себе ?

**Comment by NikolayUkleyko** [comment]
Не первый раз замечаю у нас дублирующиеся поля.
Как в тех же бланках и услугах оказанных.

**Comment by alexandra-gsoftware** [comment]
да, сами по себе. В настройках домена или поля, где выбирался бизнес объект.

**Comment by gsbelarus** [comment]
А есть такой тип документа в базе?

Если нет, то смотреть что прописано в домене и в поле таблицы. Экзешник тут
не причем. Раньше просто игнорировали несуществующий тип, с теперь выдаем
предупреждение.

**Comment by NikolayUkleyko** [comment]
>Экзешник тут не причем.

Как не причем.
Если, я сравнил на разных exe.
Разница очевидна.
Теперь надо все всем везде перепроверить ?

**Comment by gsbelarus** [comment]
Еще раз. Такого типа нет в бд. Это ошибка. Раньше она игнорировалась.
Теперь выдается предупреждение. Надо поправить ошибку.

**Comment by alexandra-gsoftware** [comment]
>>>А есть такой тип документа в базе?
да есть

**Comment by gsbelarus** [comment]
На какой базе можно посмотреть?

**Comment by sunnycreature** [comment]
brutto/3053:k:Bases\Westa\WESTA.FDB форма бронирования..например

**Comment by NikolayUkleyko** [comment]
Можно на Эталоне:
india/3053:k:\Etalon\ETALON_COMPLETE.FDB

**Исследователь / Материальный склад / 01. Накладная на получение материалов, ОС, МБП.**

**Исследователь / Услуги входящие / 01. Расчеты за услуги оказанные.**

**Comment by gsbelarus** [comment]
Обновить экзе. Проверяйте.

Там где ошибка будет выскакивать внимательно проверить тип-подтип. например, если создан на базе подтип MY_TABLE к типу TgdcContact, то если в лукапе прописать TgdcBaseContact - MY_TABLE -- это будет ошибка, так как MY_TABLE подтип к TgdcContact, но не к TgdcBaseContact.

Для полей атрибутов класс-подтип берется из домена или из поля таблицы. Чуть что проверяйте там.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.

@gsbelarus , спасибо !
