### ISSUE TITLE
Необходимые доработки по подсистеме Бухгалтерия и Налоги

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#400]
Originally reported on Google Code with ID 400

```
1.  Задокументировать тхо (проводки) по настройкам материального 
склада, оптово-розничного склада, банка, бухгалтерии, исправить план 
счетов в соответствии с Проектом типового плана счетов для Гедемин 
комплекс.
2.  Скорректировать аналитику по проводкам в соответствии с Проектом 
типового плана счетов для Гедемин комплекс.
3.  Найти все новые шаблоны для налогов, добавить новые формы налогов, 
скорректировать расчет показателей.

```

Reported by `inna.scorpio` on 2007-02-26 13:19:41

<hr>
- _Attachment: [Налоги.rar](https://storage.googleapis.com/google-code-attachments/gedemin/issue-400/comment-0/Налоги.rar)_

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2014-03-19 16:11:30
- **Labels added**: Accountancy
- **Labels removed**: Бухгалтерия

**Comment by NikolayUkleyko** [comment]
Мною проделана большая работа по данной теме.
  Пожалуйста, закройте тему.

**Comment by gsbelarus** [comment]
Закрывать можно, если все это в ПИ и ставится на чистую БД.

@MIchaelShoihet @alexandra-gsoftware

**Comment by NikolayUkleyko** [comment]
Все это есть в ПИ. Ставится на чистую БД не первый месяц.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
