### ISSUE TITLE
Добавить поддержку DATABASE TRIGGERS

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4006]
Научить бизнес-объект работать с дб триггерами, как определено тут:

https://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-psql-triggers.html#fblangref25-psql-dbtriggers

Для этого надо:

1. В структуре таблицы at_triggers убрать обязательную привязку к таблице
2. Адаптировать хранимые процедуры синхронизации триггеров at_p_sync...
3. Создать БО (TgdcDBTrigger). Подложить абстрактный базовый класс TgdcBaseTrigger от которого наследовать TgdcTrigger и TgdcDBTrigger.
4. Адаптировать диалоговое окно. Я думаю не имеет смысла создавать новое диалоговое окно, а моэно существующее научить работать как с TgdcTrigger, так и с TgdcDBTrigger.
5. В исследователь добавить в раздел Сервис-Атрибуты команду Триггеры ДБ. Соответственно, создать форму просмотра.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , звучит красиво.
Каковы преимущества данного функционала на практике ?

**Comment by gsbelarus** [comment]
https://gedemin.blogspot.com.by/2017/07/database-triggers.html

**Comment by ShlTanya** [comment]
Выполнила

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, поправь соответствие пиктограмок в следующих пунктах:

![1](https://user-images.githubusercontent.com/11497453/33126345-38e82d7c-cf95-11e7-90c3-858670eb6b5a.png)

![2](https://user-images.githubusercontent.com/11497453/33126346-3918dcb0-cf95-11e7-9c4c-e1dd9e956e2f.png)

![3](https://user-images.githubusercontent.com/11497453/33126347-394f0006-cf95-11e7-8a14-00bafdffce5d.png)

![4](https://user-images.githubusercontent.com/11497453/33126349-397d94c0-cf95-11e7-82e1-b9710ad8bcfb.png)

----

Мелочь, а приятно.
