### ISSUE TITLE
Витебск МК. Банковская выписка. Одинаковые реквизиты. Добавить проверку на код филиала (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4007]
**Исследователь / Банк и касса / Банковская выписка.**

Обновили gedemin.exe.
В БД в справочниках контактов много подведомственных контрагентов с абсолютно одинаковыми **банковскими счетам, кодом (БИКом) и УНП**.
Только различные **коды филиалов**.

Успешно загрузили банковскую выписку в БД Гедымина.
Далее, редактируем позиции выписки (проставляем бухгалтерские счета и прочее).
При сохранении программа выдает следующее диалоговое окно:

![2017-07-28_172534](https://user-images.githubusercontent.com/11497453/28721753-1b6a3c18-73ba-11e7-85d1-11a8e3832243.png)

Предлагаю доработать проверку.
Чтобы программа позволяла сохранять внесенные изменения в позицию банковской выписки даже когда, по контактам одинаковые **банковский счет, код (БИК) и УНП** и при этом различные **коды филиалов**.

На предприятии не могут дальше разносить банковскую выписку.
@gsbelarus , пожалуйста, оперативно внесите соответствующие изменения в gedemin.exe.

**Comment by gsbelarus** [comment]
Проверка сделана как предлагал В.И. У таких организаций (филиалов) надо выставить единую головную организацию в справочнике клиентов.

**Comment by NikolayUkleyko** [comment]
>У таких организаций (филиалов) надо выставить единую головную организацию в справочнике клиентов.

Хорошо.
Будем пробовать.
@gsbelarus , спасибо !

----

Как проверим, тогда и закроем данную тему.

**Comment by NikolayUkleyko** [comment]
На Витебск МК следующая ситуация.
Оплата процентов осуществляется с банковского счета предприятия и специального банковского счета банка.
При этом, по рабочей организации и по некоторым банкам абсолютно одинаковые пары банковских счетов, БИК.
Реквизит **Код филиала** не заполняем, так как это не филиалы.
Это сделано намеренно.

@gsbelarus , пожалуйста, решите данную проблему.
Просто, отключите проверку и отображение соответствующего окна приведенного здесь в начале темы.
Бухгалтер по банковской выписке не может закрыть месяц.
Следовательно, расчеты с контрагентами и т.д.
Люди ругаются.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , скажите, пожалуйста, как быть на Витебск МК (очень сильно ругаются):

- ждать нового gedemin.exe без проверки на дублирование IBAN, BIC;
- вернуться на старый gedemin.exe ?

**Comment by gsbelarus** [comment]
старый экзе тут не причем. проверка на сервере бд в триггере. если мега срочно -- отключить триггер. если нет, то завтра будет экзе.

**Comment by NikolayUkleyko** [comment]
По-хорошему, лучше новый gedemin.exe.
