### ISSUE TITLE
Экспорт данных из таблицы

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4008]
У нас есть команда **добавить ячейки в буфер**. Переработать её следующим образом:

1. при вызове на экране открывается диалоговое окно, где показаны все поля в двумерной матрице. Пользователь может выбрать как выводить имена полей: имя поля в таблице, его метка из структуры базы данных или название колонки в гриде. Если выбраны имена полей, то в хинте -- локализованное название. Если локализованное, то в хинте -- имя поля.
2. чекбоксами отмечены поля для копирования в буфер (по-умолчанию, отмечены все, видимые в гриде). Хорошо бы иметь возможность упорядочивать поля: а) как они стоят в гриде, б) по алфавиту (по названию поля и его метке), в) группировать по таблицам из запроса и внутри группы выстраивать по алфавиту.
3. кнопки для быстрого управления чекбоксами: Выделить все, Снять выделение, Только видимые.
4. выбор записей для экспорта: Текущая запись, выделенные записи, все записи.
5. формат экспорта: CSV (Excel), значение поля через запятую (если выбрано только одно поле. Это удобно, например, когда нужен список ИД, который потом можно добавить в SQL запрос), табулированный текст, HTML (таблица), SQL (SELECT запрос, который можно выполнить в SQL редакторе и получить аналогичную выборку), SQL (INSERT запросы, для вставки таких данных в БД).
6. порядок полей (колонок) в экспортированном файле (фрагменте). а) исходный, как они идут в гриде, б) заданный вручную.
7. форматы для типов данных дата, число, денежный. Разделитель дробной части. Разделитель тысяч. Наверное, не стоит вводить форматы для каждого поля по-отдельности, а только для типов данный. Предусмотреть переключатель "как на экране", когда в буфер или файл данные попадут в таком же виде, как они отображаются на экране.
8. назначение экспорта: в буфер, в файл, на адрес электронной почты.
9. экспортировать все записи или только уникальные (неповторяющиеся). При этом пользователь может выбрать из списка поле, по которому будет проверка уникальности.

Экспорт стоит реализовать отдельным компонентом (т.е. не внутри грида). Предусмотреть два переходника-коннектора для подключения к источникам данных. Один для подключения только к дата-сету, второй -- для подключения к TgsIBGrid.

**Comment by gsbelarus** [comment]
Один из сценариев использования. У нас есть режим в форме просмотра **Только отмеченные** и, соответственно, команда **Добавить в отмеченные**. Расширить данную команду, чтобы на вход можно было подать список ИД. Тогда, выполняем запрос в SQL редакторе, вызываем экспорт, выбираем колонку с ИД, формат экспорта -- список ИД и копируем в буфер. Переходим в форму просмотра и добавляем в отмеченные список ИД.

**Comment by ShlTanya** [comment]
Андрей.. сделала почти все. Остановилась на Расширить команду Добавить в отмеченные. Как Вы это видите: сделать отдельный пункт в контекстном меню Добавить в отмеченные из буфера.. или спрашивать текущая запись/буфер.

**Comment by gsbelarus** [comment]
наверно отдельную.

Добавить выделенные в отмеченные
Добавить из буфера в отмеченные

2017-08-23 10:46 GMT+03:00 ShlTanya <notifications@github.com>:

**Comment by ShlTanya** [comment]
Андрей, уточните еще, пожалуйста, пункт 9. По какому принципу выбрать уникальную запись по 1 полю, если для экспорта выбрано несколько полей.

**Comment by ShlTanya** [comment]
Андрей, вопрос по **SQL (SELECT запрос, который можно выполнить в SQL редакторе и получить аналогичную выборку)**.
Есть 2 варианта: 
- используя sql-запрос самого датасета  (ограничить выборку допустим по ключевому полю ID)
или
- вернуть выборку типа: Select Знач1, Знач2 union Select Знач3, Знач4
или Ваш вариант.
Сейчас реализовала 2 вариант.. но там есть ограничения по количеству экспортируемых записей из-за union.

**Comment by gsbelarus** [comment]
а зачем тут юнион? вы же при экспорте только колонки можете указывать, а не строки. т.е. это запрос SQL  у которого в SELECT части будут те колонки, которые выбраны в диалоговом окне.

**Comment by ShlTanya** [comment]
Значит 1-ый вариант. В результате д.б. SQL-запрос с отмеченными полями и ограничением по выбранным записям (если выбран режим текущая запись или выделенная). 
2-й вариант предполагал экспорт уже самих данных. Например: 
select 'Иванов', '01.01.2012' from RDB$DATABASE
union
select 'Петров', '01.01.2013' from RDB$DATABASE и т.д.

**Comment by gsbelarus** [comment]
первый

2017-08-29 20:08 GMT+03:00 ShlTanya <notifications@github.com>:

**Comment by gsbelarus** [comment]
Надо или запретить растягивать окно, или растягивать его внутренности:

![image](https://user-images.githubusercontent.com/5175764/31280390-db4ae2f4-aab4-11e7-8b8a-e49ec6d3ac09.png)

**Comment by gsbelarus** [comment]
1. Объекты остаются в памяти. Проверил с помощью memproof. Вы точно уверены, что все что создается у вас потом удаляется? Вот, например, где этот iWriter удалится?

`  iWriter:= TExportWriterFactory.CreateWriter(TExportWriter(Writer), Filename, SMTPKey, Recipients, Subject, Body, true);`

вообще, мы избегаем такого кода, как очень не надежного. Не надо использовать интерфейсы. Только объекты с четко очерченным жизненным циклом. Объект создается, используется, уничтожается в рамках одного кода. Стиль программирования, когда что-то где-то создалось, а потом куда-то передалось в надежде что там все правильно отработает и удалится, ни к чему хорошему не приведет.

2. мы используем MessageBox вместо ShowMessage.

**Comment by gsbelarus** [comment]
3. если экспортировать в HTML кириллические строки, то откроются кракозябры. Надо в заголовке укаказывать кодировку WIN1251.

**Comment by NikolayUkleyko** [comment]
В целом данный функционал реализован успешно.
Есть отдельная тема, где обсуждается усовершенствование такого функционала https://github.com/GoldenSoftwareLtd/gedemin/issues/4039.
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
