### ISSUE TITLE
На последнем exe не открывается форма в Positive Cash

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#4011]
Фронт Для розницы. С сайта.
usrf_select_good как DFM для просмотра открывается, а как форма нет. В старый exe всё работает.

![image](https://user-images.githubusercontent.com/8355925/29428055-7b08a486-8394-11e7-9a8a-d1b968858e25.png)

**Comment by gsbelarus** [comment]
Смотри в тексте dfm что указано как subtype

**Comment by alexandra-gsoftware** [comment]
может там сабтайп маленькімі буквамі, ему надо чтоб капслоком

**Comment by stasgm** [comment]
Вот и представьте, делается обновление и у клиента беда. Как бы заранее нам надо знать, что в exe ограничения добавляются несрвместимые с предыдущими версиями

**Comment by gsbelarus** [comment]
Раньше была ошибка

**Comment by hirurg-lybitel** [comment]
@gsbelarus  Нет, не было.

Вот dfm, который прекрасно открывается на exe версии 2.9.3.9032.

Сейчас последняя версия 2.9.3.9379 кидает ошибку из описания.

```
  object usrg_gdcAttrUserDefined1: TgdcAttrUserDefined
    Tag = 0
    ForcedRefresh = False
    AutoCalcFields = True
    ObjectView = False
    AllowStreamedActive = False
    SubType = 'GD_GOOD'
    MasterSource = nil
    MasterField = 'ID'
    DetailField = 'MASTER_RECORD_ID'
    SetTable = ''
    Active = False
    CachedUpdates = False
    Filtered = False
    Left = 119
    Top = 181
  end
```

**Comment by alexandra-gsoftware** [comment]
странно, мне кажется, это не прокатывает уже года два

**Comment by gsbelarus** [comment]
TgdcAttrUserDefined это класс для пользовательских справочников. Имя таблицы должно начинаться с USR$. Сабтайп GD_GOOD тут явная ошибка. Для таблицы GD_GOOD есть класс TgdcGood. Используй его, а не TgdcAttrUserDefined.

**Comment by hirurg-lybitel** [comment]
@gsbelarus  Что некорректно написано - это понятно. Вопрос в том, что это резко вылезло. 
Что-то поменяли в новой версии ехе? Если да, то что ещё поменялось, чтобы  не было таких сюрпризов?

**Comment by gsbelarus** [comment]
это не резко а уже пол года минимум или год. сейчас система проверяет
подтипы на корректность.
например у TgdcAttrUserDefined подтип только пользовательская таблица,
которая реально существует в БД.

у документа подтип -- реально существующий РУИД в таблице GD_DOCUMENTTYPE и
т.п.

2017-08-21 21:38 GMT+03:00 hirurg-lybitel <notifications@github.com>:

**Comment by alexandra-gsoftware** [comment]
Вот та же проблема, только в банке.
https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/236
Была выявлена 4 ноября 2016 г.

**Comment by alexandra-gsoftware** [comment]
не понимаю, как эта штука в меню до сих пор работала, если ехе поменялся год назад...
