### ISSUE TITLE
ПИ. Переименование файла. Изменение места хранения файла. Перенос каталога

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4014]
Через контекстное меню TortoiseGit выполнено **переименование файла**.
Затем, сохранение изменений.
Все прошло успешно.

Перечитали файлы.
При этом, в проводнике наименование файла отображается с учетом изменений, а в Гедымине без учета изменений.
В окне синхронизации наименование файла отображается без учета изменений, а в диалоговом окне синхронизации с учетом изменений.
Я считаю, что наименование файла везде должно отображаться с учетом изменений.

----

Как корректно выполнить изменение:
1. Расположения файла из одного каталога в другой.
2. Расположения каталога с файлами в другой подкаталог.

**Comment by gsbelarus** [comment]
Откуда гедымин знает что там на диске поменялось. Надо перечитать.

**Comment by NikolayUkleyko** [comment]
>Надо перечитать.

Это само собой разумеется.
Даже несколько раз на БД устанавливал ПИ с измененным наименованием.
На выходе следующая картина:

![2017-08-23_200123](https://user-images.githubusercontent.com/11497453/29628568-91be0a3c-883e-11e7-9bd6-7e44a444c675.png)

В БД и на диске имя файла старое, а в диалоговом окне имя файла новое.
Везде должно быть актуальное наименование файла.

**Comment by gsbelarus** [comment]
Так может тут дело в том, что имя файла одно, а имя пи (оно записано в
файле) другое

**Comment by NikolayUkleyko** [comment]
Переименование файла в проводнике было выполнено через TortoiseGit при помощи контекстного меню и команды **Rename**.
Принудительно наименование файла в проводнике не менялось.
То есть, корректно.

По идее, помимо изменения наименования файла для ПИ, изменение наименования файла должно быть и для формы синхронизации ПИ.
Ведь на выходе наименование файла в проводнике тоже измененное.

Видим одно, на выходе другое.
Изменения наименований файлов могут быть и более существенные.
Тогда, можно запутаться в файлах ПИ.

На мой взгляд, или TortoiseGit некорректно обрабатывает изменения наименований файлов и/или Гедымин некорректно работает с переименованными файлами.
Необходимо решить данный вопрос.

**Comment by gsbelarus** [comment]
Имя файла это одно,имя пи, которое хранится в бд и записано внутри этого
файла -- другое. Поменяй имя в бд и созрани файл с новым именем а старый
удали.

**Comment by NikolayUkleyko** [comment]
>Имя файла это одно,имя пи, которое хранится в бд и записано внутри этого
файла -- другое.

Это само собой разумеется.

>Поменяй имя в бд и созрани файл с новым именем а старый
удали.

Поменял имя в БД.
Такой файл при сохранении автоматически перетер существующий файл ПИ.
То есть, в данном случае при сохранении вариантов выбора пути сохранения не было.

Поэтому через контекстное меню TortoiseGit удалил файл (можно с каталогом).
Потом, заново его пересохранил с соответствующим указанием пути.

Вывод:
**Rename** корректно не работает.
Правильный вариант - это удаление файлов (можно с каталогом) и пересохранение файла с указанием каталога.
