### ISSUE TITLE
Общие. Использование 2-х кавычек при написании XID и DBID

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4016]
Пожалуйста, подскажите, какой вариант написания наиболее правильный:
1.     " doc.DOCUMENTTYPEKEY = <RUID XID = ""147004989"" DBID = ""45137928""/> "
2.     " WHERE d.DOCUMENTTYPEKEY = <RUID XID = 147023202 DBID = 3974129/> "

Какое предназначение 2-х кавычек в первом варианте ?

@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , @alexandra-gsoftware, все же, как верно ?

**Comment by alexandra-gsoftware** [comment]
мне второй больше нравится

**Comment by gsbelarus** [comment]
только 1-й вариант. так определено стандартом:

https://www.w3schools.com/xml/xml_attributes.asp

**Comment by NikolayUkleyko** [comment]
@gsbelarus , спасибо !
Будем придерживаться стандарта.
