### ISSUE TITLE
Бухгалтерия. Конструктор функций. Предусмотреть проверку на наименования блоков SQL-запросов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4017]
Не первый раз сталкиваемся с тем, что в конструкторе функций можно успешно добавить 2-а и более блока SQL-запроса с одинаковыми наименованиями.
Потом, полученные переменные используются в других блоках.
В результате настроенный алгоритм работает некорректно.
Поэтому, настоятельно предлагаю добавить проверку на наименования блоков SQL-запросов.

**Comment by MIchaelShoihet** [comment]
А вот не надо. Надо контролировать что делаешь.. Я специально пользуюсь этой возможностью. Просто надо проверять, после того как изменяешь такой важный механизм как проводка.

**Comment by NikolayUkleyko** [comment]
OK !
