### ISSUE TITLE
Бухгалтерия. Конструктор функций. Предусмотреть скрытие незаполненных полей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4019]
**Исследователь / Бухгалтерия / Типовые хоз. операции, Автоматические хоз. операции, Настройка функций.**

Пожалуйста, предусмотрите кнопку для скрытия незаполненных полей **при указании счета, как переменная**.
Сейчас, программа автоматически скрывает неиспользуемые аналитики только **при выборе конкретного счета**.
Сейчас программа отображает весь перечень аналитик.
По умолчанию данная кнопка не активна.
Так будет гораздо удобнее работать с аналитиками в проводках.
На больших БД обширный перечень аналитик.
Сейчас приходится прокручивать весь перечень аналитик в поисках требуемой.
Замечу, что здесь речь идет именно о заполненных аналитиках и изменении значения аналитики или вовсе очистка.

![2017-09-20_110301](https://user-images.githubusercontent.com/11497453/30633414-37ae1ff2-9df4-11e7-9e13-8a35db381327.png)

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by MIchaelShoihet** [comment]
Я не вижу смысла тратить на это время и деньги.

**Comment by NikolayUkleyko** [comment]
Хорошо.
Пришли к общей точке зрения.
