### ISSUE TITLE
Рассчетные счета

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4021]
В окне редактирования компании расчетные счета выводятся с фильтром, который установлен в разделе справочники Расчетные счета. Соответственно счетов не видно, пока там не снимешь фильтр.

**Comment by NikolayUkleyko** [comment]
С такой проблемой я тоже сталкивал, только не мог идентифицировать причину.
Фильтры для справочника банковских счетов добавлял я.
Так удобнее анализировать и при необходимости вносить изменения в записи.

----

Вот то, что имеет место связь между фильтрованием данных в справочнике банковских счетов и в гриде банковских счетов по рабочей организации это очень интересно.
На мой взгляд данную проверку необходимо вовсе отключить.
@MIchaelShoihet , что, Вы, скажете ?

**Comment by gs7600300** [comment]
Сегодня столкнулся с этой проблемой на БММК. Я так понимаю в данной проблеме уже разбирались, сообщите решение...

**Comment by NikolayUkleyko** [comment]
>Сегодня столкнулся с этой проблемой на БММК. Я так понимаю в данной проблеме уже разбирались, сообщите решение...

Кирюша, мало разбираться с проблемой, необходимо еще и решить ее на 100 %.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
Проблема есть.. Исправила.

**Comment by gsbelarus** [comment]
Проверить. Закрыть.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
