### ISSUE TITLE
Гомельобои. gdcc.exe. Удаленный доступ. Отключение приложения через командную строку (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4023]
Вопрос возникает при удаленном доступе, если прописывать автоматический запуск Гедымина в свойствах соединения.
Выскакивает еще окно про запуск gdcc.exe, а при завершении сеанса, сеанс и окно удаленного доступа автоматически не закрываются, приходится закрывать принудительно.
При повторном подключении (сразу после закрытия) сервер не успевает сбросить сеанс и клиент попадает в пустой голубой экран.

Предложение по добавлению параметра командной строки /nogdcc ^

**Comment by NikolayUkleyko** [comment]
Данная тема случайно не связана с
https://github.com/GoldenSoftwareLtd/gedemin/issues/4009
?

**Comment by gsbelarus** [comment]
Скорее всего она.

**Comment by NikolayUkleyko** [comment]
Данная проблема вновь весьма актуальна.
На Гомельобоях наладили работу с БД коллегам из Минска.
Есть технические вопросы приведенные выше.
@gsbelarus , пожалуйста, решите.

**Comment by NikolayUkleyko** [comment]
С БД ГомельОбои по RDP-подключению активно работают пользователи из минского филиала.
Люди настойчиво просят.
Данный вопрос сейчас очень актуален:

>Вопрос возникает при удаленном доступе, если прописывать автоматический запуск Гедымина в свойствах соединения.
Выскакивает еще окно про запуск gdcc.exe, а при завершении сеанса, сеанс и окно удаленного доступа автоматически не закрываются, приходится закрывать принудительно.
При повторном подключении (сразу после закрытия) сервер не успевает сбросить сеанс и клиент попадает в пустой голубой экран.

>Предложение по добавлению параметра командной строки /nogdcc ^

@gsbelarus , пожалуйста, решите вопрос.
