### ISSUE TITLE
Наименование триггеров в таблице

### ISSUE THREAD

**Issue by PiuPauTralala** [GoldenSoftwareLtd/gedemin#4024]
1. Выделено красным цветом на рисунке: ТРИ разных варианта наименования триггеров. Сделайте единообразно, пожалуйста (таблица называется USR$BN_ORDERTRIPSUBLINE).
2. Выделено синем цветом. Раньше позиция автоматически подставлялась. 
3. Наверное, преобразование из дерева в грид обоснованно как-то, но раньше было удобнее. Визуально лучше воспринималось.

![untitled](https://user-images.githubusercontent.com/11497771/31954114-6265b890-b8ed-11e7-83b9-e5adda55af05.png)

**Comment by gsbelarus** [comment]
1. Позицию разработчик должен выбирать обдумано, так как есть случаи когда надо солюдать очередность.
2. грид правильно, дерево лишнее.
3. имя сейчас формируется корректно, раньше в него просачивался лишний префикс.

**Comment by alexandra-gsoftware** [comment]
В дереве было сразу видно, какие триггеры есть (например, что есть after insert & before delete). Теперь, чтобы определить тип триггера, надо его открыть (ведь назвать его могли как угодно), а триггер тайп -  интежер.
