### ISSUE TITLE
Создание процедуры

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4025]
Если к базе подключено более 1 пользователя, то нельзя создать процедуру.  Это все имеет место быть на последнем exe, на более старом таких проблем нет и не было никогда.

**Comment by NikolayUkleyko** [comment]
Юра, я предполагаю, что такое наблюдается из-за того, что мы не отключая пользователей в таблицу добавили поле-ссылку.
Программа при переподключении не просила отключить всех пользователей от БД.

----

Юра, не забудь вопрос к обсуждению, когда в Гедымине при редактировании процедуры не работает добавление новых строк через кнопку **Enter**.

**Comment by YRozmysl** [comment]
Я еще раз проверял на простой чистой базе, причем перед созданием процедуры я не создавал поля ссылки. Просто сделал 2 коннеекта и попробовал создать процедуру.

**Comment by YRozmysl** [comment]
нее, снимаем вопрос, муть какая-то, все ок теперь, и на локальной и рабочей цбк

**Comment by YRozmysl** [comment]
> Юра, не забудь вопрос к обсуждению, когда в Гедымине при редактировании процедуры не работает добавление новых строк через кнопку Enter.

Эта ошибка есть.

**Comment by NikolayUkleyko** [comment]
>Эта ошибка есть.

Продолжение обсуждения в https://github.com/GoldenSoftwareLtd/gedemin/issues/4026

**Comment by NikolayUkleyko** [comment]
Юра, закрывай данную тему.
