### ISSUE TITLE
Общие. Фильтр по биноклю. Добавить сортировку отображаемых полей согласно грида

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4027]
Пожалуйста, в фильтр по биноклю, добавьте сортировку отображаемых полей согласно грида.
Поле в начале списка.
Если полей очень много, то для поиска требуемого поля приходится прокручивать весь список полей.
@ShlTanya  сделает, если позволите.

**Comment by ShlTanya** [comment]
Я посмотрю...

**Comment by ShlTanya** [comment]
Поправила

**Comment by NikolayUkleyko** [comment]
Проверено.
Сортировка работает корректно.

----

Выявлено следующее.
Не правильно работает табуляция: **Tab, Shift+Tab**.
На практике удобен переход по близко расположенным поля без мышки.
Сейчас **_произвольный_** переход с поля на поле.
@ShlTanya , пожалуйста, по возможности, поправь это.

![2017-11-30_142222](https://user-images.githubusercontent.com/11497453/33428633-9ab6aaec-d5da-11e7-8945-a4054966c578.jpg)

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
Видела. Исправлю.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
На какой-то из версий gedemin.exe рассматриваемый функционал работал корректно.
Сейчас, снова не работает.
@ShlTanya , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
