### ISSUE TITLE
Общие. В справочник констант добавить тип 'Ссылка'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4028]
Пожалуйста, в справочник констант добавьте тип **Ссылка**.

**Comment by YRozmysl** [comment]
Да, не помешало бы.

**Comment by NikolayUkleyko** [comment]
Как вариант в справочник констант добавить тип ссылка с последующим выбором **бизнес-класса**.
Это позволяет выбирать требуемую запись практически из любой таблицы.
Подобное реализовано в конструкторе функций:

![1](https://user-images.githubusercontent.com/11497453/33165610-7ca4ffb4-d048-11e7-978f-ff318a1618b5.png)

![2](https://user-images.githubusercontent.com/11497453/33165611-7cd15b0e-d048-11e7-945f-99dd119653bd.png)

![3](https://user-images.githubusercontent.com/11497453/33165612-7cf9dc3c-d048-11e7-9caf-85799cdd7a1b.png)

![4](https://user-images.githubusercontent.com/11497453/33165614-7d2e7eba-d048-11e7-94d0-8c9441e8e0d0.png)

![5](https://user-images.githubusercontent.com/11497453/33165615-7d6f7ed8-d048-11e7-847e-cf3ea5b487bd.png)

Коллеги, что скажете ?

**Comment by NikolayUkleyko** [comment]
Очередной раз подтверждается актуальность данной тему.
Пример: на дату для конкретного подразделения задать значение ставки рассчитанного ТН и НДС.
При этом на одну может быть несколько различных подразделений с разными ставками ТН и НДС.
Коллеги, пожалуйста, изложите ваши точки зрения.

**Comment by yoannawx** [comment]
хотелось бы ускорить рассмотрение данного вопроса. очень актуально

**Comment by NikolayUkleyko** [comment]
@stasgm тоже интересуется данной темой.

**Comment by MIchaelShoihet** [comment]
Я не совсем понимаю, как вы это себе представляете. Что такое ссылка на произвольный справочник?

**Comment by NikolayUkleyko** [comment]
Пример.
Подсистема ЗП и ОК.
Формирование бухгалтерских проводок по счету **_76.02 (Расчеты по имущественному и личному страхованию)_**.
В типовой проводке по счету 76.02 по аналитике **Клиент** задается конкретное значение (Белгосстрах...области...району).
Со временем с определенной даты может быть выбрана совершенно другая организация.
Для того, чтобы в типовой проводке не прописывать условия на дату или не перебивать значение аналитики **Клиент** достаточно будет создать новую запись (**выбор из справочника Организаций**) в соответствующей константе и воспользоваться функцией **Acc_calcTaxRate**.

Подобных примеров много.
Ссылки могут быть не только на GD_CONTACT, но и на другие таблицы, документы и т .д.

@YRozmysl , не так ли ?

**Comment by MIchaelShoihet** [comment]
В том то и дело. Если это ссылка значит надо контролировать целостность данных. А это значит на каждую ссылку нужно создавать отдельное поле с ссылкой. Это усложнит данный справочник и сам механизм. Поэтому для таких вещей давайте другие варианты использовать.

**Comment by alexandra-gsoftware** [comment]
Нет, ну можно хранить не ссылку в прямом смысле, а класснэйм + сабтайп + ИД

**Comment by MIchaelShoihet** [comment]
Тогда не будет целостности... Но конечно можно... Но это не передашь настройкой, ПИ...

**Comment by alexandra-gsoftware** [comment]
Ок, руид вместо ид хранить. Мы такое на кисе делали.

**Comment by MIchaelShoihet** [comment]
Да так наверное возможно... Что в принципе можно делать и сейчас (правда не визуально) :)

**Comment by alexandra-gsoftware** [comment]
Народ требует визуально😁

**Comment by NikolayUkleyko** [comment]
>Мы такое на кисе делали.

Это уже весьма интересно.

**Comment by alexandra-gsoftware** [comment]
Там можно было сделать ф-ю которая запускалась по таймеру, типа нашей автозадачи, и к ней любые параметры, в том числе, ссылки. Они так хранились.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
