### ISSUE TITLE
AT_P_SYNC_TRIGGERS_ALL после добавления триггеров уровня БД

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4029]
При модифае и поеследующем подключении к базе БМКК последним exe возникает ошибка.
![modifai](https://user-images.githubusercontent.com/11507129/32939102-8cca82b4-cb8f-11e7-855e-063e491e079b.jpg)

**Comment by YRozmysl** [comment]
исправлено, данной ошибки больше нет

**Comment by YRozmysl** [comment]
пока осталась ошибка, судя по всему это касается конкретной базы, а именно последней бмкк

**Comment by NikolayUkleyko** [comment]
Это рабочая БД или нет ?

**Comment by YRozmysl** [comment]
это не рабочая база, локальная, последняя. В том то все и дело, чтобы менять exe на рабочей базе, надо устранить ее тут и разобраться в причине, чтобы на рабочей не было проблем.

**Comment by ilonaand** [comment]
Надо в процедуре AT_P_SYNC_TRIGGERS_ALL в запросе, который добавляет новые тригеры сменить условие  WHERE 
     (t.triggername IS NULL) and (r.id IS NOT NULL)  на 
 WHERE 
     (t.triggername IS NULL) 
     and (((r.id IS NOT NULL) and (rdb$trigger_type <=114)) 
       or (rdb$trigger_type >=8192)) 

и ошибка исчезнет. Я так делала на нашей локальной базе brutto/3053:k:\Bases\BMKK\GDBASE_2017_08_24.FDB  после модифая

**Comment by YRozmysl** [comment]
так это, наверное, лучше делать на уровне exe, эта процедура же системная какая-то, не входит ни в какие ПИ.

**Comment by NikolayUkleyko** [comment]
>так это, наверное, лучше делать на уровне exe, эта процедура же системная какая-то, не входит ни в какие ПИ.

Пожалуйста, @MIchaelShoihet , @gsbelarus , @alexandra-gsoftware , изложите Ваши точки зрения и примите решение.

**Comment by gsbelarus** [comment]
Пробуем новейшим экзешником.
