### ISSUE TITLE
Общие. Бухгалтерия. Работа с бизнес-классами

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4030]
1. Можно ли на прикладном уровне (не gedemin.exe) создавать новые бизнес-классы ?
Если, да, то - как ?
Если, нет, то - почему ?

2. Давно обращался с просьбой создания бизнес-класса для отображение только подразделений и сотрудников.
Изменений нет.
Технически сложно реализовать ?

----

Давно с @MIchaelShoihet решили уйти от одновременного использования 2-х дублирующихся аналитических признаков Подразделение, Сотрудник.
Взяли за основу аналитику Подразделение (Сотрудник) (бывшее Подразделение).

По аналитике Подразделение (Сотрудник) прописан бизнес-класс TgdcBaseContact.
При работе с Журналом хоз. операций (Журналом-ордером и т.д.) в поле Подразделение (Сотрудник) доступны все контакты БД.
Не совсем это корректно.
Не нужно отображать лишние контакты.
При выборе бизнес-класса TgdcDepartment доступны только подразделения.
Необходимо предусмотреть бизнес-класс для отображение только подразделений и сотрудников.

**Comment by NikolayUkleyko** [comment]
Коллеги, пожалуйста, подскажите и создайте бизнес-класс для отображения только подразделений и сотрудников.
На Береза МКК и не только это весьма актуально.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , @ShlTanya , пожалуйста, изложите Ваши точки зрения на данную тему ?
Все просто, но это необходимо, особенно при работе с Журналом хоз. операций.

**Comment by ShlTanya** [comment]
Есть же отдельно класс подразделений TgdcDepartment и сотрудников TgdcEmployee. Если для аналитики указан в типе правильный класс (не общий TgdcBaseContact).. то и при вводе вручную проводок в аналитике идет правильная выборка (на основе указанного класса). Проверила.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , все верно.
Только я прошу добавить бизнес-класс, сочетающий в себе бизнес-классы TgdcDepartment и TgdcEmployee.
То есть, в Look-up отображать и подразделения, и сотрудников.

В чем суть ?
Есть аналитика **Подразделение (Сотрудник)**.
Ранее, данная аналитика называлась **Подразделение**.
В ходе общения с @MIchaelShoihet пришли к тому, с целью избежания неточности при формировании бухгалтерских форм (Журнал-ордер, Карта счета и т.д.) необходимо в складских подсистемах использовать не аналитику **Сотрудник**, а **Подразделение (Сотрудник)**.
На практике на предприятии могут вести учет, например, по 10-м в только в разрезе:

- сотрудников;
- подразделений;
- сотрудников и подразделений.

Как таковая аналитика **Сотрудник** используется в следующих подсистемах:

- заработная плата (70-е счета);
- расчеты с подотчетными лицами (71-е счета);
- другие подсистемы (например, кроме 10-х счетов).

**Comment by ShlTanya** [comment]
@MIchaelShoihet.. а может в таких случаях можно использовать **Условие выбора значений на языке SQL** (при построении лукап поля).  Т.е. можно проверить.. если Условие по бизнес-классу пустое, использовать условие выбора..

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, уточни на примере.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, сориентируйте @ShlTanya.

**Comment by MIchaelShoihet** [comment]
Бизнес класс такой создать нельзя. Т.к. это совсем разные сущности. И да "Условие выбора значений на языке SQL" нужно использовать при настройки лукапа в окне ввода журнала хозяйственных операций. Тогда для аналитики подразделение (сотрудник) можно указать contacttype in (2, 4) и все будет красиво. При этом в данном поле класс лучше убрать вообще.

**Comment by NikolayUkleyko** [comment]
Хорошо.
Какие действия (1, 2, 3...) для того, чтобы в Журнале хоз. операций в поле **Подразделение (Сотрудник)** в выпадающем списке отображались только подразделения и сотрудники ?

**Comment by ShlTanya** [comment]
Дело в том, что в коде при построении лукапа в окне ввода хоз. операций Условие выбора значений на языке SQL не учитывается совсем.  Это можно исправить.

**Comment by MIchaelShoihet** [comment]
Все правильно. Тогда в домене подразделение достаточно прописать contacttype in (2, 4). И в данном лукапе будут доступны и сотрудники и подразделения.

**Comment by NikolayUkleyko** [comment]
Все просто.
В свойствах домена:

**1**. Бизнес-класс не выбираем вовсе.
Чтобы не путал.
Он только удобен при добавлении соответствующей записи в справочник.

**2**. В поле **Условие выбора значений на языке SQL** прописываем **_contacctype in (2, 4)_**.

----

В ходе беседы выяснилось, что требуемые бизнес-классы не так просто создавать.
Порой даже невозможно.
Я уже хотел сам создавать. :-)

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@MIchaelShoihet , @ShlTanya , спасибо !
