### ISSUE TITLE
Проблема с восстановлением базы

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4032]
gbak: do not recognize table attribute 0

**Comment by gsbelarus** [comment]
1. отключить пользователей
2. обновить фб до новейшей версии (если у них 2.5, то до 2.5.7)
3. прогнать gfix -mend для устранения ошибок
4. сделать бэкап бд
5. еще раз попытаться восстановить

**Comment by NikolayUkleyko** [comment]
>обновить фб до новейшей версии (если у них 2.5, то до 2.5.7)

А такое как раз можно было не исключить.
Ведь когда возле gedemin.exe расположены файлы Firebird более актуальные, чем в папке С / Program Files / Firebird.
Я про это писал не раз.
Файлы Firebird должны быть одной версии в обеих папках.

----

Список обновляемых файлов в папке рядом с gedemin.exe указан в пункте № 5

http://gsbelarus.com/gs/wiki/index.php/%CF%E5%F0%E5%F5%EE%E4_%ED%E0_Firebird_2.5._%CC%ED%EE%E3%EE%EF%EE%EB%FC%E7%EE%E2%E0%F2%E5%EB%FC%F1%EA%E8%E9_%F0%E5%E6%E8%EC

**Comment by YRozmysl** [comment]
ок, актуализируем еще dll и около exe

**Comment by NikolayUkleyko** [comment]
OK !

**Comment by YRozmysl** [comment]
Вопрос снят. Скорее всего был поврежденный архив. Последний bk восстановился без проблем.
