### ISSUE TITLE
Опция "Экспорт данных"

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4033]
В последнем exe появилась опция "Экспорт данных".  В данной функциональности она конечно же неплохая и может быть удобна, и полезна. Но, можно еще немного пойти дальше. Если бы при помощи ее можно было бы загружать из одной таблицы в другую, например, предварительно указав соответствие полей одной и другой таблицы (документов). Это всего лишь. мысли вслух, не более того.
Часто в зарплате надо разово загрузить какие то данные из одного документа в другой, например, выгрузить из ручного ввода в ведомость выдачи, либо в какой-то другой расчетный документ. Либо обратно и т.д. и т.п. Я думаю в других модулях такого тоже хватает.

**Comment by NikolayUkleyko** [comment]
<Если бы при помощи ее можно было бы загружать из одной таблицы в другую, например, предварительно указав соответствие полей одной и другой таблицы (документов).

Удобный универсальный функционал.
Например, когда БД перевалит планку в 1 Tb, придет время перебросить сальдовые (и другие требующиеся) данные из одной в БД (старой и огромной) в другую (новую и чистую).

Нечто подобное реализовано в IBExpert.
Для сложного переноса данных из справочников с полями-ссылками требуются дополнительные обработки.
Простой перенос данные из справочников без полей-ссылок работает корректно и не требует дополнительных обработок.

@ShlTanya , не стесняйся, пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
1. В Экспорте есть формат SQL(insert), который формирует sql-запрос для вставки.
2. Такая задача больше подходит к категории Импорта данных. Но тут все сложнее. Если таблица плоская.. то все вроде и просто. Во всех остальных случаях надо вести контроль целостности данных.

**Comment by NikolayUkleyko** [comment]
>В Экспорте есть формат SQL(insert), который формирует sql-запрос для вставки.

Татьяна, ты, имеешь в виду простые таблицы и поля типа текст (VARCHAR) ?

>Такая задача больше подходит к категории Импорта данных. Но тут все сложнее. Если таблица плоская.. то все вроде и просто. 

Например, в одной БД выгрузка перечня сотрудников из одной таблицы в другую ?
Аналогично и в разных БД.

**Comment by gsbelarus** [comment]
1. Между бд данные переносятся с помощью ПИ.
2. другого механизма перенести реляционные данные нет.
3. "выгрузка перечня сотрудников из одной таблицы в другую" -- wtf?

**Comment by gsbelarus** [comment]
4. для больших бд есть механизм "обрезки", но всегда следует помнить, что данные -- такой же актив предприятия как например, сырье на складе или автомобили в автопарке.

**Comment by NikolayUkleyko** [comment]
>"выгрузка перечня сотрудников из одной таблицы в другую" -- wtf?

@YRozmysl , пожалуйста, приведи примеры.

----

>для больших бд есть механизм "обрезки", но всегда следует помнить, что данные -- такой же актив предприятия как например, сырье на складе или автомобили в автопарке.

Это да.
Сравнение разных категорий.
В случае сбоя на МК не хватает 8-и часов для выполнения восстановления БД из архива.

На практике ни на одном из МК БД не была сжата при помощи соответствующей утилиты и полученная БД принята к работе.
На сколько мне известно была выполнено очищение данных из таблиц INV_CARD, GD_DOCUMENT и  т.д.
Это полумеры.
Только Жанна пользовалась утилитой по чистке БД небольших от данных.
Как сказал @MIchaelShoihet : "Утилита по сжатию работает, можно и нужно ее использовать и она усовершенствоваться не будет".

**Comment by MIchaelShoihet** [comment]
Вообще обрезать базу до размера быстрого восстановления не возможно, потому что даже несколько последних лет содержат большой объем информации. Поэтому на больших комбинатах реализована система сохранения самого файла базы данных на резервном сервере и именно на нее предприятие переключается в случае сбоя работы основного сервера или проблем с рабочей базой данных. Я вообще не понимаю сути обсуждения. Экспорт данных - это выгрузка данных и все... Создание универсального импорта данных - это абсолютно другая задача и намного сложнее текущей...

**Comment by NikolayUkleyko** [comment]
> Я вообще не понимаю сути обсуждения. Экспорт данных - это выгрузка данных и все... Создание универсального импорта данных - это абсолютно другая задача и намного сложнее текущей...

Юра, спросил про:

>если бы при помощи ее можно было бы загружать из одной таблицы в другую, например, предварительно указав соответствие полей одной и другой таблицы (документов). Это всего лишь. мысли вслух, не более того.

Хорошо.
Обсудили.
Закрываем тему.
