### ISSUE TITLE
Общие. Скрыть неактуальную команду 'Системный лог...'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4034]
Пожалуйста, скройте неактуальную команду **Системный лог...**:

![1](https://user-images.githubusercontent.com/11497453/33126639-3fecaa16-cf96-11e7-9eb0-d8e112a2245e.png)

Сейчас за этот функционал отвечает утилита **gdcc.exe** со своим окном сообщений.

**Comment by gsbelarus** [comment]
Команда системный лог сейчас открывает окно gdcc.

**Comment by NikolayUkleyko** [comment]
>Команда системный лог сейчас открывает окно gdcc.

Не заметил, так как, при открытых формах и нажатии на кнопку **Системный лог...** окно gdcc.exe скрыто под всеми формами.

**Comment by gsbelarus** [comment]
Это зависит от версий виндоуз. В последних ОС не дает одному процессу открыть в foreground окно другого процесса. Но, по крайней мере, появится панелька на панели задач и подмигнет.
