### ISSUE TITLE
Переподстановка фром-карточки

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#4035]
Пример можем показать на базе ВМК.

Добавляем в док-те типа изменения свойств позицию из остатков,  
ИД позиции осатков - **1165631241**.  
Этот документ работает с ОС (ОС.Изменение свойств). Если посмореть баланс по этому ОСу, то получим ту же самую карточку **1165631241**, она единственная.
ищем
```
SELECT b.*
FROM INV_BALANCE b
LEFT JOIN INV_CARD c ON c.ID = b.CARDKEY
WHERE b.GOODKEY = 1126578355
  AND b.BALANCE <> 0
  AND c.USR$FA_INVCARDKEY = 1135212095
```

получаем
```
CARDKEY	        CONTACTKEY	BALANCE	GOODKEY	
**1165631241**	1123183454	1	       1126578355	
```
У этой карточки нет наследников и нет дальнейших движений.
При выборе никакие ТО-признаки не меняем. В итоге получаем в позиции документа
FROMCARDKEY = **1165631241**, TOCARDKEY = **1165631241**	

Все правильно.

Теперь меняем один из ТО-признаков в нашей позиции (USR$FA_OWNINGKEY). Нигде в дуфилдчейнджах или триггерах (кроме стандартного триггера на инвкард) это поле не используется. 

Что должно произойти? Должна создаться новая карточка, которая будет отличаться только признаком, который мы поменяли, с родителем **1165631241**. FROMCARDKEY  в документе должен остаться прежним, TOCARDKEY  - поменяться.
Получаем:
_FROMCARDKEY = **1155245954**_, TOCARDKEY = **1185093248**	
Новая карточка создалась (**1185093248**), но фромкард поменялась тоже (с **1165631241** на **1155245954**).

Посмотрим, чем отличаются эти карточки (FROMCARDKEY = **1155245954** и TOCARDKEY = **1185093248**	)
1) USR$FA_OWNINGKEY - логично
2) USR$FA_WEARSUMNCU (???) - там разные значения, оба заполнены.

Как связаны между собой эти карточки (и как они связаны с  **1165631241**) ?

Вот история возникновения **1185093248**	 (новой карточки). LVL - это уровень родителя (если отрицательный) или потомка (если положительный)

```
LVL	CARDKEY	DOCUMENTKEY
-7	1135212107	1135212096
-6	1135212109	1135212096
-5	1141883378	1141883376
-4	1148908850	1148908848
**-3	1155245954**	1155241515
-2	1157837705	1157837703
**-1	1165631241**	1165631239
**0	1185093248**	1185093231
```

Итого. Родитель новой карточки (**1185093248**)- это карточка, которую мы выбрали из остатков (**1165631241**). Так и должно быть, это правильно. Но во FROMCARDKEY в документе подставлен не прямой родитель TOCARD, а один из ее далёких предков. 

Если сравнить  **1185093248** и **1165631241**, они отличаются только полем USR$FA_OWNINGKEY (опять логично).

Если удалить запись и повторить, получим тот же результат (т.е. можно оценить на живой базе)

Почему?? Говорят, что это не первый случай

**Comment by alexandra-gsoftware** [comment]
* если сделать апдейт поля FROMCARDKEY, то никаких триггеров не вызывается, запись "исправляется"

**Comment by NikolayUkleyko** [comment]
>если сделать апдейт поля FROMCARDKEY, то никаких триггеров не вызывается, запись "исправляется"

Александра, пожалуйста, подскажи, в данном случае триггеры не должны вызываться ?

**Comment by alexandra-gsoftware** [comment]
Не должны. Это я к тому, что никаких доп.  триггеров там нет...

**Comment by MIchaelShoihet** [comment]
На следующей неделе будет представлена новая система складского учета. По идее все эти проблемы там решены.

**Comment by NikolayUkleyko** [comment]
Такие хорошие новости не могут не радовать.

----

Снова на Витебск МК с ОС что-то не то.
В остатках двоятся инвентарные номера.
В документа остатки другие.
Записи по документам ОС без ссылок и дальнейшего движения не удаляются.
Бухгалтера в недоумении.

**Comment by alexandra-gsoftware** [comment]
ой, в том документе и другие позиции кривые

**Comment by NikolayUkleyko** [comment]
Для примера можно рассмотреть инвентарный номер 10088 на 30.09.2017 г.

**Comment by NikolayUkleyko** [comment]
На Витебск МК ожидают новый gedemin.exe с новой системой складского учета.
