### ISSUE TITLE
Общие. Экспорт данных. Совершенствование

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4039]
Пожалуйста, изложите свои взгляды на следующее.
Необходимо скопировать из таблицы сумму из одной ячейки.

![2](https://user-images.githubusercontent.com/11497453/33365383-1582dc74-d4f9-11e7-93c5-1a518fb1082a.png)

По умолчанию в параметрах экспорта в блоке **_Уникальность записей_** не выбрано ни одного варианта.
Экспорт данных проходит без ошибок.
Здесь напрашивается исходный вариант **Не учитывать**.

@gsbelarus , @ShlTanya .

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

----

@ShlTanya , что по 1-у вопросу ?

**Comment by NikolayUkleyko** [comment]
@ShlTanya , хорошо бы еще добавить поиск по **Ctrl+F3** и **F3** (включая вызов через контекстное меню) по выбираемым полям по:
- полю;
- локализованному наименованию;
- заголовку колонки.

**Comment by NikolayUkleyko** [comment]
На практике нередко встречаются ситуации, когда необходимо скопировать данные из одной ячейки.
Функционал формы экспорта данных позволяет сделать это.
Для удобства хорошо бы добавить кнопку, которая бы снимала галки со всех полей кроме поля, на котором стоит курсор.
Предусмотреть вариант выделения полей через Ctrl и Shift.
Тогда, отпадет необходимость нажимать полную отмену выделения и поиска нужного поля и простановке галки.

@ShlTanya , пожалуйста, изложи свою точку зрения ?

**Comment by NikolayUkleyko** [comment]
В ходе использования данного функционала возникли следующие предложения:

**1. Предусмотреть отдельную настройку для формы экспорта данных символа-разделителя ?**
При копировании и вставке в качестве символа-разделителя берется значение из настроек Windows.
У любого пользователя может быть разделитель отличный от точки.
Тогда, при вставке в Excel и попытке дальнейшей обработки получаем сообщения о неверном типе (формате) данных.
Перебивать весь массив данных не вариант.

----

**2. В блоке 'Наименование поле' по умолчанию установить курсор на пункт 'Заголовок колонки в таблице'.**
Сейчас выбран пункт **Локализованное имя поля**.
На практике имена приведенных заголовков колонок могут быть кардинально переименованы, что сильно путает при работе с данными.

----

**3. Сохранение настроек формы.**
При выполнении различных вариантов экспорта каждый раз необходимо заново указывать все параметры.
Очень бы хотелось, чтобы предусмотрели возможность сохранения настроек формы экспорта.

@gsbelarus , @ShlTanya , пожалуйста изложите ваши точки зрения ?

**Comment by NikolayUkleyko** [comment]
> 3. Сохранение настроек формы.
> При выполнении различных вариантов экспорта каждый раз необходимо заново указывать все параметры.
> Очень бы хотелось, чтобы предусмотрели возможность сохранения настроек формы экспорта.

Сейчас по умолчанию подставляется формат из Мастера установок - отлично.
Необходимо предусмотреть параметры по хранению формата данных по числовым полям.
Чтобы по умолчанию было задано определенное форматирование или его не было вовсе.
Вряд ли это реализуете.
Хотя бы, предусмотрите возможность выделения нескольких колонок (кнопка Shift и / или Ctrl) для последующей настройки форматирования.

----

**4. Предусмотреть возможность переноса полей.**
Подобное сделано в Мастере установок - перенос колонок.

**Comment by NikolayUkleyko** [comment]
![image](https://user-images.githubusercontent.com/11497453/91184211-098f8c80-e6f5-11ea-885c-89f7fd05c88e.png)

Пожалуйста, предусмотрите следующие возможности:

1. Вариант **без наименований**.

2. Перетаскивание колонок.

3. Снятие форматирования по всем колонкам.

@ShlTanya ?

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
> @ShlTanya , хорошо бы еще добавить поиск по **Ctrl+F3** и **F3** (включая вызов через контекстное меню) по выбираемым полям по:
> 
> * полю;
> * локализованному наименованию;
> * заголовку колонки.

@ShlTanya @dmitranoid, хорошо бы предусмотреть такую возможность.

**Comment by ShlTanya** [comment]
Доработано: Вариант без наименований. Перетаскивание колонок. Снятие форматирования по всем колонкам. Реализован поиск.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо !

Тему пока не закрываем, так как посмотрю еще некоторый функционал.

-----

@ShlTanya , пожалуйста, посмотри следующее:

> 2. В блоке 'Наименование поле' по умолчанию установить курсор на пункт 'Заголовок колонки в таблице'.
> Сейчас выбран пункт Локализованное имя поля.
> На практике имена приведенных заголовков колонок могут быть кардинально переименованы, что сильно путает при работе с данными.

**Comment by ShlTanya** [comment]
Доработано

**Comment by NikolayUkleyko** [comment]
@ShlTanya , спасибо !
Проверяю.
Замечательные доработки.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
