### ISSUE TITLE
Выбор множества для таблицы типа Простое дерево

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4040]
Так специально сделано, что для таблицы типа "Простое дерево" в форме выбора множества записи выводятся простым списком? Для интервального дерева выводятся деревом.

![default](https://user-images.githubusercontent.com/11484894/33426020-81fcd2aa-d5d1-11e7-9520-f5d094fd13a5.jpg)

**Comment by NikolayUkleyko** [comment]
Да, кстати интересно.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте данную тему.
Она перенесена сюда https://github.com/GoldenSoftwareLtd/gedemin/issues/3442.
