### ISSUE TITLE
Типовые документы. Создание таблиц и их выбор с переподключением к БД

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4041]
Сейчас при создании нового типового документа можно создать новые таблицы и **нельзя их выбрать**.
Для этого необходимо переподключиться к БД и только тогда их выбрать.
Раньше такого не было.
@gsbelarus , скажите, пожалуйста, это так задумано ?

----

Про создание полей не спрашиваю, так как к этому добавили gdcc.exe.

**Comment by YRozmysl** [comment]
Да, не совсем понятно для чего сделано такое ограничение. Раньше такого не было. Уже и спрашивали не раз меня клиенты по этому вопросу, кто сам программирует. Такие есть, да.

**Comment by NikolayUkleyko** [comment]
@YRozmysl , нормальная тема.
Пообщались.
Как будто мы это сделали.

**Comment by gsbelarus** [comment]
Посмотрю.

**Comment by NikolayUkleyko** [comment]
@YRozmysl вновь столкнулся с вышеприведенной проблемой.
Так не должно быть.

@gsbelarus , пожалуйста, Ваша точка зрения ?

**Comment by NikolayUkleyko** [comment]
Сегодня при разработке нового документа столкнулся с такой проблемой.
Создавая типовой документ нельзя создать и выбрать таблицу.
Для сохранения нового типового документа необходимо выбрать левую таблицу и нажать на OK.
Затем, необходимо переподключиться и выбрать уже необходимую таблицу.

----

Не работает возможность добавления очереди полей-ссылок в существующую таблицу при помощи кнопки Новый.
Необходимо каждое поле добавлять через OK и Ins.

Ранее все это работало как полагается.
Сейчас все разломано.
Это неправильно.
Если, иное, то аргументируйте или запретите делать, что приведено выше.

@gsbelarus  , пожалуйста, изложите Вашу точку зрения.

**Comment by YRozmysl** [comment]
@stasgm  оно?

**Comment by stasgm** [comment]
Новый типовой документ не создать с первого раза.

**Comment by NikolayUkleyko** [comment]
>Новый типовой документ не создать с первого раза.

@stasgm , это очевидно.

**Comment by ShlTanya** [comment]
исправила

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:

----

@ShlTanya , пожалуйста, посмотри по возможности следующее: не работает возможность добавления очереди полей-ссылок в существующую таблицу при помощи кнопки **Новый**.
Необходимо каждое поле добавлять через **OK** и **Добавить (Ins)**.
