### ISSUE TITLE
Параметры. Выбор из множества. Двойной клик (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4042]
Сейчас в параметре типа Выбор из множества при двойном клике **выбирается запись и открывается/закрывается ветка**.
На практике удобнее, чтобы при намеренном выборе главной записи ветка не открывалась/закрывалась, а просто выбиралась.

У кого, какие предложения ?

**Comment by gsbelarus** [comment]
Надо проверить. Если это стандартное поведение дерева Windows то вряд ли что-то исправим.

**Comment by NikolayUkleyko** [comment]
Хорошо.
