### ISSUE TITLE
Номер документа в позиции не соответствует номеру в шапке

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4045]
У нас не гарантируется точная синхронизация номера документа в позиции и в шапке. Технически это сделать сложно и затратно по ресурсам. Нужны триггеры и на изменении позиции и на изменение шапки, да еще и с защитой от зацикливания. Такие триггеры будут выполнять SELECT из GD_DOCUMENT, а это таблица с десятками миллионов записей.

На практике обнаружено, что люди используют номер документа из позиции, полагаясь на его ТОЧНОЕ соответствие номеру из шапки.

Это ведет к трудновыявимым ошибкам.

Представляется правильнее, для позиции очищать номер документа. Чтобы не было соблазна его использовать.

Заодно и база станет чуть-чуть меньше по размеру.

@MIchaelShoihet

**Comment by alexandra-gsoftware** [comment]
Мне кажется, все отчеты, где был номер из позиции, уже поправили...

**Comment by gsbelarus** [comment]
@yoannawx во всю использует и теперь огребает.

**Comment by yoannawx** [comment]
не @yoannawx вовсю использует, а ac_record.DOCUMENTKEY, если проводки формируются по позициям

**Comment by MIchaelShoihet** [comment]
Но в ac_record есть специально masterdockey и он всегда ссылается на шапку.

**Comment by NikolayUkleyko** [comment]
@gsbelarus привел очевидные вещи в отношении GD_DOCUMENT: номер (дата) в шапке и позиции.

Напрашивается вопрос: зачем изначально сделали так, чтобы в позиции документа вообще был NUMBER и DOCUMENTDATE и при этом заполнялся аналогичным значением из шапки документа ?
Как преследовалась при этом цель ?
Это же было сделано намеренно ?

Как, написала @yoannawx , пользователи анализируют **Карту счета** и видят записи по одному реальному документу с различными NUMBER.

**Comment by MIchaelShoihet** [comment]
Ну где-то в начале ошиблись... Вообще есть как минимум два документа у которых должны различаться номера в шапке и позиции - это банковская выписка и кассовая книга... Как проектировали отталкивались от этого. Для других документов предполагали, что с вопросом синхронизации справится триггер. Но не учли не которых особенностей... Т.е. сейчас это уже свершившийся факт и работать надо из текущих реалий

**Comment by NikolayUkleyko** [comment]
>Вообще есть как минимум два документа у которых должны различаться номера в шапке и позиции - это банковская выписка и кассовая книга... Как проектировали отталкивались от этого. Для других документов предполагали, что с вопросом синхронизации справится триггер.

Я понял.

----

Следует учесть еще и такие документы, как кредитный договор, график лизинговых платежей и т. д.
Отличительной особенностью таких документов является то, что в позиции хранятся суммы соответствующие каждой отдельной дате.

На некоторых БД МК предусмотрен функционал, который позволяет в позиции документа намеренно указать NUMBER отличный от указанного в шапке документа.
В данном случае это верно.
На выходе корректные Журналы-ордера и прочие формы (отчеты).

Иначе бы пришлось создавать столько записей по отдельным шапкам документов, сколько периодов (позиций исходного документа).
Это крайне неудобно.
Лишний функционал по заполнению данных из позиции исходного документа в шапку дополнительного документа.
Ненужный (лишний) массив данных.

----

Согласно, вышеприведенного, очевидно, что в **_пользовательских документах_** (кредитный договор, график лизинговых платежей и другие) дата и номер в позиции могут быть отличны от даты и номера в шапке.
**Выдвигаю предложению: на уровне gedemin.exe предусмотреть такую возможность.**

Относительно **_складских документов_** (накладная на получение ТМЦ и другие) дата и номер в позиции должны быть едины с датой и номером в шапке.
На текущий момент есть некоторые ограничения на уровне gedemin.exe и прочих инструментов.
Поддерживаю предложение @gsbelarus:
>Представляется правильнее, для позиции очищать номер документа. Чтобы не было соблазна его использовать.

Заодно и база станет чуть-чуть меньше по размеру.

**Comment by NikolayUkleyko** [comment]
Дополнительно по рассматриваемой теме в части формирования **Карты счета** давным-давно просил сделать следующую небольшую доработку:
https://github.com/GoldenSoftwareLtd/gedemin/issues/3665

@MIchaelShoihet и @ShlTanya , пожалуйста, изложите ваши точки зрения.

**Comment by NikolayUkleyko** [comment]
Вопрос проработан.
@gsbelarus , пожалуйста, закройте тему.
