### ISSUE TITLE
Очистка ненужных уже РУИДов после обрезки БД

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4046]
Чуть позже я закину сюда запрос для быстрой очистки с использованием G_HIS_ARRAY. Надо будет добавить в программу.

**Comment by gsbelarus** [comment]
Соответствующий EXECUTE BLOCK приведен [здесь](http://gsbelarus.com/gs/wiki/index.php/%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B8%D0%B7_GD_RUID_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B5%D0%B9_%D0%B4%D0%BB%D1%8F_%D0%BD%D0%B5%D1%81%D1%83%D1%89%D0%B5%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%89%D0%B8%D1%85_%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2).

**Comment by NikolayUkleyko** [comment]
Ранее я предполагал, что при **BK-FDB** помимо всего еще и выполняется чистка RUID.
Теперь выяснилось, что - нет.
Как вариант, предлагаю добавить соответствующую опцию в параметры формы **создания архивной копии БД** и в параметры формы **восстановления БД их архива**.

@gsbelarus , что скажете ?

**Comment by gsbelarus** [comment]
на больших бд эта процедура может занять от часа и выше. хотя как опцию...

**Comment by NikolayUkleyko** [comment]
Да, как опцию.
По-умолчанию опция **не активна**.

**Comment by gsbelarus** [comment]
У нас уже есть отдельная утилита чистки РУИДов.

**Comment by NikolayUkleyko** [comment]
> _У нас уже есть отдельная утилита чистки РУИДов._

На сайте не нашел.
