### ISSUE TITLE
Нет процедур складского движения в эталоне

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4051]
В модуле **mdf_ModifyInvent**, в процедуре **CreateNewException** создаются\меняются триггеры по складскому движению. Но их нет в эталоне. Например, процедуры **INV_INSERT_CARD**.

Т.е. на старых базах, которые пройдут модифай они появятся, а на новых их нет.

**Comment by MIchaelShoihet** [comment]
Да добавлю.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
