### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Поле Number сделать обязательным для заполнения

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4054]
Не первый раз возвращаемся к данной теме.
Пожалуйста, предусмотрите в Журнале хоз. операций поле **Number** обязательным для заполнения.
Сейчас любая запись (проводка) с активной, но незаполненной аналитикой **Документ** заполняется пустой записью.
Это казалось бы мелочь, но - нет.
В результате затрачивается немало времени на поиски ошибок в данных.

**Comment by NikolayUkleyko** [comment]
Само собой разумеется не делать поле Number **Not Null**.
Сделать по аналогии **CreateFields**.

**Comment by MIchaelShoihet** [comment]
А если там будет 1 - будет легче? Поле Number как раз not null, и если он не заполнен то заполняется пробелом. Но смысл в его заполнении будет только тогда когда он будет осмысленным. Если человек будет просто ставить 1 то это будет то же самое что и пробел...

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , проблематика в том, что визуально пустой Number воспринимается пользователями, как реально пустое поле.
Для программы это заполненное поле, выглядещее, как пустое поле.
Пользователям не интересно, как устроена программа, им необходимо просто работать и понимать очевидные вещи, выходя на результат.

Раз в GD_DOCUMENT поля Number и Documentdate по умолчанию Not Null, то почему  изначально не сделали аналогично и в Журнале хоз. операций ?

**Comment by NikolayUkleyko** [comment]
Сегодня столкнулись с такой ситуацией на Береза МКК.
Возникли вопросы у бухгалтера по учета скота.

**Comment by MIchaelShoihet** [comment]
Сделали как раз наоборот. Сделали специально, что бы оно могло быть пустым. Предлагаю по умолчанию не пробел добавлять как сейчас а "б\н" тогда всем будет понятно.

**Comment by NikolayUkleyko** [comment]
>Предлагаю по умолчанию не пробел добавлять как сейчас а "б\н" тогда всем будет понятно.

Очень хорошо.
Б/н.

**Comment by MIchaelShoihet** [comment]
@ShlTanya сделайте пожалуйста. При вводе проводки, если номер не введен подставить б\н

**Comment by ShlTanya** [comment]
Ок

**Comment by ShlTanya** [comment]
Сделала

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
