### ISSUE TITLE
Установка хранилища vs. ПИ

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4056]
Возможно ли выводить  информационно при обновлении ПИ название документа, например под PARENT, например, "Штатное расписание". Мне, например, кто обновляет ежегодно профилактически зарплату, было бы очень удобно это. 
![default](https://user-images.githubusercontent.com/11507129/34714594-f9dc8d6e-f53a-11e7-8afd-9192b9d82728.jpg)

**Comment by NikolayUkleyko** [comment]
Хорошо бы.
Стоит только настроить грид документа и тогда при обновлении ПИ вышеприведенных сообщений будет целый набор.
Необходимо каждое сообщение подтверждать.
По сути алгоритм документа не меняется, а только визуализация.

**Comment by YRozmysl** [comment]
Тут даже не столько грида настройка, а формы. так как на ей могут быть сделаны какие -то специфические компоненты, и просто если знаешь в каком это было сделано документе, можно выбрать оставить   хранилище, то, которое в базе. В противном случае, приходится снимать хранилище со старой базы и загружать на обновленную базе.

**Comment by NikolayUkleyko** [comment]
Форма тоже.

**Comment by YRozmysl** [comment]
Ничего городить не надо, просто информационно выводить в окне , которое выслал выше название документа и все. механизм загрузки и прочее  категорически не надо трогать

**Comment by NikolayUkleyko** [comment]
>механизм загрузки и прочее категорически не надо трогать

Не намеревались.

**Comment by YRozmysl** [comment]
Какие-нибудь есть подвижки по этому вопросу, обновление просто идет полным ходом у клиентов

**Comment by gsbelarus** [comment]
Побыстрому пробовал, но не получилось. Буду смотреть позже.

**Comment by YRozmysl** [comment]
Если вопрос трудозатратный, то можно и закрывать.
