### ISSUE TITLE
Редактирование процедур vs ВВОД

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4060]
Снова нельзя при редактировании процедуры нажать ВВОД.  Вроде же это было исправлено ранее...

**Comment by gsbelarus** [comment]
Это было исправление по подписке. Ты за какой срок уплатил? Вот год истек -- все, исправление откатилось.

**Comment by YRozmysl** [comment]
В том-то все и дело, что это гарантийный случай еще и года не прошло еще

**Comment by YRozmysl** [comment]
Странно. Есть 2 базы. На каждой из их есть одна и та же процедура. На одной из баз пробел ставится при нажатии ввод, а на другой  - нет.

**Comment by alexandra-gsoftware** [comment]
хмм, а как там глобальный параметр Использовать Энтер как Таб? Может как-то он замешан?

**Comment by YRozmysl** [comment]
Да, все именно так и было, Вопрос закрыт

**Comment by YRozmysl** [comment]
хотя, правильно ли это, что этот параметр задействован и в редактировании процедуры, ну, да ладно.

**Comment by alexandra-gsoftware** [comment]
мне кажется, так всегда было

**Comment by YRozmysl** [comment]
ок, вопрос снят с повестки. просто я и не знал про существование таких параметров, теперь буду

**Comment by gsbelarus** [comment]
скажи спасибо вале со скота в березе, чтобы ей  на пенсии икалось.

**Comment by YRozmysl** [comment]
спасибо
