### ISSUE TITLE
Эксепшн в DoBeforePost срабатывает но Post проходит

### ISSUE THREAD

**Issue by PiuPauTralala** [GoldenSoftwareLtd/gedemin#4063]
На BeforePost объекта не работает call Exception.Raise("Exception", "Сообщение").

**Comment by gsbelarus** [comment]
On Error Resume Next ??

**Comment by alexandra-gsoftware** [comment]
нет. Эксепшн срабатывает но пост проходит

**Comment by gsbelarus** [comment]
Проверил. Post после исключения не срабатывает. Надо смотреть конкретную БД, где это проявлялось.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
