### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Сторнировать проводку. Количественные показатели

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4064]
**Исследователь / Бухгалтерия / Журнал хоз. операций**.

![2017-01-09_171353](https://cloud.githubusercontent.com/assets/11497453/21769629/c11ad55e-d690-11e6-9f83-7338c3731650.png)

![2018-01-22_111115](https://user-images.githubusercontent.com/11497453/35211068-e7dec552-ff65-11e7-9df0-8a96d8f90749.jpg)

@ShlTanya , пожалуйста, предусмотри сторнирование проводок еще и по **количественным показателям**.

**Comment by ShlTanya** [comment]
Сделала

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
