### ISSUE TITLE
Общие. Отмеченные. Вопросы по формам остатков и справочников (E/V)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4065]
**Исследователь / Основные средства / ОС. Остатки на дату.**

1. Выделяем несколько записей и в контекстном меню (правая кнопка мышки, можно и через главное меню формы **_Остатки / Добавить в отмеченные_**) выбираем пункт **Добавить выделенные в отмеченные**.
Выбираем **Только отмеченные** - будет отображена только последняя запись из выделенных.
Такого быть не должно.
В отмеченные должны быть добавлены все выделенные записи.

Это касается гридов любых форм и древовидных справочников.
В гридах документов добавление в отмеченные работает корректно.

----

2. Для чего предусмотрена команда **Добавить из буфера в отмеченные** ?

@gsbelarus , @ShlTanya , пожалуйста изложите Ваши точки зрения и выполните соответствующие доработки.

**Comment by MIchaelShoihet** [comment]
Все просто иногда запросом можно получить некоторый набор ID и скопировать его в буфер и на основании его сформировать отмеченные...

**Comment by ShlTanya** [comment]
1. Исправлено в формах остатков  и древовидных формах
2. Можно добавить в отмеченные из буфера строку, содержащую список ID (через запятую). Можно проверить: Экспорт данных - формат Поле в строку -  Получатель Буфер.

**Comment by NikolayUkleyko** [comment]
Проверено.

>1. Исправлено в формах остатков и древовидных формах

Не работает.
Очень важный функционал.
Чтобы не создавать однотипные отчеты.

Да и удалить из отмеченных несколько записей нельзя.

>2. Можно добавить в отмеченные из буфера строку, содержащую список ID (через запятую). Можно проверить: Экспорт данных - формат Поле в строку - Получатель Буфер.

Работает корректно.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , скажи, пожалуйста, где можно посмотреть функционал по добавлению записей в отмеченные ?
Мне для остатков по ОС крайне важно.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
