### ISSUE TITLE
Общие. Некорректное выделение записей в гриде через кнопку Shift

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4066]
В нашей программе в любом гриде выделение записей работает следующим образом.

При помощи кнопки Ctrl - выделение **только выбранных записей**.
Это верно.

При помощи кнопки Shift - выделение только выбранных записей.
Так быть не должно.
Сейчас крайне неудобно.
Пользователи часто путаются.
Выделятся должен диапазон записей **от начально выделенной записи до конечной**.

Scroll мышки не рассматриваем.

----

В Windows выделение записей через кнопку Shift работает корректно.

@gsbelarus , @ShlTanya , пожалуйста, изложите Ваши точки зрения и выполните соответствующие доработки.

**Comment by ShlTanya** [comment]
Такая доработка с разрешения @gsbelarus

**Comment by MIchaelShoihet** [comment]
Я против того, что бы что-то менять. На это мне не жаловался никто... А менять функциональность, которая работала 15 лет и на которую никто не жаловался, только потому что это не по фэншую... Мне кажется у нас есть чем заняться.

**Comment by NikolayUkleyko** [comment]
>Я против того, что бы что-то менять.

Не надо.
Просто услышал точки зрения коллег.
Это радует.
Порой на вопросы и предложения в ответ тишина.

> только потому что это не по фэншую...

Но, как говорил @gsbelarus , что Microsft с Windows является неким эталоном.
У нас противоречиво.

>Мне кажется у нас есть чем заняться.

Это само собой разумеется.
Вопросов очень много.
