### ISSUE TITLE
Журнал хозяйственных операций.

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4067]
В диалоговом окне ввода проводке надо сделать, что бы в лукапы (которые создаются для выбора аналитик) в поле Fields подставлялось значение "Поле для расширенного отображения", которое указано для таблицы которая указана в ListTable данного лукапа.

**Comment by ShlTanya** [comment]
Выполнено

**Comment by MIchaelShoihet** [comment]
То что надо.

**Comment by NikolayUkleyko** [comment]
Хотел посмотреть на реализацию и не нашел.
Интересно.

**Comment by MIchaelShoihet** [comment]
Что значит посмотреть? Надо что бы таблица была настроена соответствующим образом.

**Comment by MIchaelShoihet** [comment]
На сайте этих доработок еще нет.

**Comment by NikolayUkleyko** [comment]
>На сайте этих доработок еще нет.

Я предполагал, что gedemin.exe ежедневно компилируется со всеми текущими доработками.
Значит - нет.

**Comment by MIchaelShoihet** [comment]
Конечно нет. Доработки сначала проверяются и потом только идут в рабочую ветку.

**Comment by NikolayUkleyko** [comment]
>Конечно нет. Доработки сначала проверяются и потом только идут в рабочую ветку.

Хорошо.
Тогда, не совсем понятно назначение ежедневной компиляции gedemin.exe ?

**Comment by MIchaelShoihet** [comment]
Ежедневная компиляция идет из рабочей ветки. Доработки идут в тестовую ветку. В рабочую ветку изменения могут попадать ежедневно, могут реже, могут чаще. Компиляция стоит автоматически и она не проверяет были изменения или нет.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , благодарю за информацию.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Есть, один момент.

По умолчанию количество записей отображаемых в выпадающем списке = 16.
Например, аналитика Клиент.
В поле для расширенного отображения указано ADDRESS.
Поэтому сейчас выпадающий список составит 16 записей NAME + 16 записей ADDRESS.
Итого 32 записи в выпадающем списке.
Сейчас на большинстве мониторов выпадающий список выглядит перегруженным.
В таких случаях удобно поменять на меньшее количество записей отображаемых в выпадающем списке.

Подскажите, можно ли регулировать количество записей отображаемых в таких случаях ?
Если, да - то, как ?
Хорошо бы уменьшить количество записей отображаемых в выпадающем списке.

@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.
