### ISSUE TITLE
Фильтры. Добавить возможность использования полей, добавленных в методах

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4069]
@gsbelarus , @MIchaelShoihet , пожалуйста, подскажите, возможно ли в преодопределенных фильтрах предусмотреть работу с полями, добавленными в методах ?

**Comment by MIchaelShoihet** [comment]
Фильтры работают с данными на уровне таблиц, что к методам не имеет отношение. Но он имеет доступ ко всем полям и всем таблицам на которые ссылаются или которые ссылаются на таблицы бизнес объекта, а значит что даже если поле не добавлено в методе, к нему все равно фильтр имеет доступ, за исключением полей которые не являются полями таблиц, а прописаны в запросе как какое-то вычисление...

**Comment by NikolayUkleyko** [comment]
Хорошо, @MIchaelShoihet .
Пожалуйста, подскажите, можно ли предусмотреть возможность поиска среди доступных полей фильтра ?
Поиск по оригинальному названию и по локализованному.
Как результат поиска отображать только найденные поля (типа **Ctrl+S**), а не подсвечивать найденные среди всех других полей (типа **Ctrl+F**).
На практике порой не так просто отыскать требуемое поле.
Сложностей добавляет и то, что окно выбора полей фильтра невелико.
При прокручивании скроллом мышки список дергается и слетает.

**Comment by MIchaelShoihet** [comment]
Нет. Пока придется пользоваться теми фильтрами что есть.

**Comment by NikolayUkleyko** [comment]
Спасибо.

**Comment by NikolayUkleyko** [comment]
Хотя бы корректную (без дергания и слетания) прокрутку списка полей скроллом мышки реализовать.
@ShlTanya , пожалуйста, изложи свою точку зрения на данную тему ?

**Comment by NikolayUkleyko** [comment]
Пожалуйста, по возможности увеличьте окно выпадающего списка и шрифт отображаемых полей.
Сейчас, как будто в дверной глазок смотришь.
