### ISSUE TITLE
Ограничение на рабочую организацию в документах

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#4070]
У нас сейчас ограничение это выглядит как  z.COMPANYKEY in .... Если документ ведется только в одной рабочей организации, то файрберд игнорирует этот индекс. Если же этот тип документов ведут 2 и больше организаций, то ФБ  индекс использует, в итоге документ подвисает. От этого индекса нет пользы, один только вред. Предлагаю заменить на  z.COMPANYKEY + 0 in...

**Comment by YRozmysl** [comment]
Вопрос не утратил актуальность

**Comment by gsbelarus** [comment]
я поправил уже. обновить завтра экзе и проверить.

**Comment by YRozmysl** [comment]
Все ок.

**Comment by alexandra-gsoftware** [comment]
Тогда, как сменится ехе на бмкк, надо откатить подмену компаникея на компаникей + 0 в методах
@YRozmysl  @ilonaand

**Comment by YRozmysl** [comment]
его сегодня заменили на бмкк в обед, можно править
