### ISSUE TITLE
Общие. Поиск и удаление записей в GD_DOCUMENT без ссылок (QQ)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4071]
Можно ли найти и удалить записи в GD_DOCUMENT без ссылок ?
@gsbelarus , пожалуйста, изложите, Вашу точку зрения.

**Comment by alexandra-gsoftware** [comment]
в смысле без таблиц шапки\позиции? 
Вы только автоматические операции не прибейте случайно.

**Comment by NikolayUkleyko** [comment]
>Вы только автоматические операции не прибейте случайно.

Я про ситуации, когда создали проводку с аналитикой **Документ**.
Потом, удалили запись из AC_RECORD, а запись в GD_DOCUMENT осталась.
Вот про такие пустышки.
