### ISSUE TITLE
Параметры. Выбор из множества. Не отображать уже выбранные записи

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4072]
Пожалуйста, предусмотрите в форме выбора из множества скрытие уже выбранных записей.
На практике это вызывает неудобства при работе с большим массивом инвентарных номеров по ОС и прочему.
Выбор осуществляется вручную и случайно можно пропустить запись.
Вообще, это очевидно: есть доступные записи и есть выбранные записи.

@gsbelarus , @ShlTanya , пожалуйста, изложите Ваши точки зрения.

**Comment by alexandra-gsoftware** [comment]
хм, а еслі я хочу снять выделеніе с запісі?

**Comment by NikolayUkleyko** [comment]
>хм, а еслі я хочу снять выделеніе с запісі?

Тогда, снова ее вернуть из выбранных записей в доступные.
Как вариант можно предусмотреть реквизит, отвечающий за скрытие/отображение уже выбранных записей.

**Comment by NikolayUkleyko** [comment]
Как вариант ничего кардинально не менять, а просто в блок доступных записей добавить выделение **зеленым цветом** уже выбранных записей.

Коллеги ?

**Comment by ShlTanya** [comment]
Закоммитила вариант выделения (изменение пиктограммы) выбранных значений.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , большое спасибо !
Ждемс выпуска обновлений в gedemin.exe на сайте.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , спасибо !
Проверено.
Недоработок я не выявил.
Однако, коллеги выявили случаи, когда при выборе/удалении записей в форме выбора из множества программа отображает окно об ошибке с сообщением **Invalid index...**.
Такое поведение программы может быть обусловлено тем, что при работе с БД на старом gedemin.exe уже был выполнен выбор записей в форме выбора из множества.
Затем, обновили gedemin.exe и попытались добавить/удалить записи в форме выбор из множества.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:

**Comment by NikolayUkleyko** [comment]
В случае, если, в параметре выбора из множества указана ссылка на простую таблица (не древовидной структуры), то:

1. Для доступных записей неправильно отображаются пиктограммки. Белые (как для выбранных записей), а необходимо отображать желтые.
2. При удалении записей из выбранных по ним в блоке доступных записей по ним неправильно отображаются пиктограммки. Сперва желтые, после переоткрытия формы отображаются белые.
![image](https://user-images.githubusercontent.com/11497453/135481808-aea9f2ab-3cd4-4705-ad8d-068ebeeba8de.png)

@ShlTanya , пожалуйста, поправь.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри.

**Comment by ShlTanya** [comment]
Пиктограммы приведены в порядок.

**Comment by NikolayUkleyko** [comment]
Рассматриваемая тема перенесена сюда https://github.com/GoldenSoftwareLtd/gedemin/issues/3442.
