### ISSUE TITLE
Бухгалтерия. В конструкторе функций ошибка 'Stream read error'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4073]
**Исследователь / Бухгалтерия / Отчеты бухгалтерии / Настройка функций.**

Уже давно замечена ошибка **Stream read error**.
При которой полностью блокируется вход в конструктор дорабатываемых актуальных отчетов  бухгалтерии.
Аналогичное может быть и при работе с типовыми проводками.
Это не шутки, когда работаешь с очень большим массивом данных.
При этом пересохранение в ПИ (настройку) не всегда можно вовремя выполнить.
Самое интересное !
Что приходится заново делать, то что уже было сделано.
Нам такое надо ?

**Comment by gsbelarus** [comment]
нужна конкретная бд, где эта ошибка возникает.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, посмотрите в
Brutto/3053:k:/Bases/Broiler/GDBASE_2018_01_03.FDB

**_Исследователь / Бухгалтерия / Отчеты бухгалтерии / Настройка функций._**

В появившемся окне найти **Финансовый результат - Витебск БПФ (за месяц) - 2**.
В нижней части окна вызвать на редактирование запись и нажать на кнопку **Конструктор**.
Программа отображает следующее окно с сообщением об ошибке:

![2018-06-05_175024](https://user-images.githubusercontent.com/11497453/40983757-f8573468-68e8-11e8-8546-e3421a2f866f.jpg)
