### ISSUE TITLE
Мастер установок. Не работает цветовое выделение колонки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4075]
**_Мастер установок / Колонки / Визуальные / Колонка / Цвет_**.

Не работает.
Раньше данный функционал работал.

@ShlTanya , пожалуйста, посмотри.

**Comment by ShlTanya** [comment]
Выделение цветом колонки работает при **выключенном** Режиме отображения полос в таблице.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , странно.
Попробовал выполнить такие настройки и не получается целиком выделить колонку (не заголовок).

**Comment by NikolayUkleyko** [comment]
> Выделение цветом колонки работает при выключенном Режиме отображения полос в таблице.

Проверено.
Оказывается, так и есть.
В гриды изменений не вносим.
Большое спасибо, @ShlTanya ! :gift:
