### ISSUE TITLE
Бухгалтерия. Конструктор функций. Очередность параметров и способ передачи

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4076]
**1**. При изменении очередности параметров **снимается выделение** с текущей записи и соответственно **становятся неактивными кнопки Вверх, Вниз.**

Это крайне неудобно при работе с параметрами.
Хорошо бы еще предусмотреть возможность простого перетаскивания параметров.

![1](https://user-images.githubusercontent.com/11497453/37397730-640d8e98-278d-11e8-9caf-7893a4fd0d66.jpg)

@ShlTanya , пожалуйста, поправь.

----

**2**. Пожалуйста, подскажите, назначение функционала по выбору способа передачи данных (**пусто, ByVal, ByRef**) ?
Если, можно, приведите примеры.

![2](https://user-images.githubusercontent.com/11497453/37397813-9d661c0a-278d-11e8-9fe8-4d3c46355aae.png)

@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
@ShlTanya , заранее спасибо.
Ждем обновлений.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
