### ISSUE TITLE
Параметры. Выбор из множества. Предусмотреть отображение нескольких полей по записям (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4077]
На практике уже не первый раз сталкиваюсь, а также и с Витебск МК, Гомельобоев в следующем.

Пожалуйста, подскажите, можно ли в форме параметра **Выбор из множества** предусмотреть отображение нескольких полей по записям.
Например, основное поле **Наименование** может быть в списке одинаковым, а другой реквизит (как 1 или 0, или ссылка на другой справочник, или другие варианты) может быть отличным.
Учитывая это пользователям будет гораздо удобнее работать с отчетами.

@MIchaelShoihet , @gsbelarus , @ShlTanya , пожалуйста, изложите Вашу точку зрения.
Коротко и ясно (да, нет) + аргументы.

**Comment by ShlTanya** [comment]
Можно рассмотреть вариант с выводом нескольких полей из данной таблицы (например, перечислять в настройках имена полей через запятую). 
Или вместо таблиц работать с запросом (и тоже имена полей в пределах запроса).
Но для реализации ссылок на другой справочник необходимы еще и данные по связям.. Это достаточно много изменений.

**Comment by NikolayUkleyko** [comment]
Большое спасибо, @ShlTanya за отзыв.
Я предполагаю, что с учетом сказанного:
>Но для реализации ссылок на другой справочник необходимы еще и данные по связям.. Это достаточно много изменений.

Вряд ли это будет реализовано.

@MIchaelShoihet , @gsbelarus , пожалуйста, изложите ваши точки зрения.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , благодарю за изложение своих мыслей.
