### ISSUE TITLE
Общие. Установка ПИ (настроек), требующих отключения пользователей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4078]
Очередной раз на Слуцк МК столкнулись со следующей ситуацией.
Устанавливали простейшую настройку (поле ссылка).
При попытке загрузки программы и подключения к БД никакого ответа нет.
Выяснилось, что во время установки ПИ (настроек), к БД было подключено 2-а и более пользователя Administrator.
Кто-то выдвинул предположение о том, что первое подключение к БД может быть сделано под пользователем Administrator, который раньше другого Administrator был подключен к БД.

----

Существующий функционал по однопользовательскому подключению работает весьма специфично.
@gsbelarus , почему бы не предусмотреть функционал, при котором под Administrator можно устанавливать ПИ (настроек) с запретом на подключение других пользователей к БД в момент установки настроек или в любой другой заданный момент времени.

@gsbelarus , пожалуйста, изложите Вашу точку зрения.

**Comment by gsbelarus** [comment]
надо с начала точно установить что там произошло.

другого функционала по запрету подключений пока не будет.

**Comment by NikolayUkleyko** [comment]
>надо с начала точно установить что там произошло.

Коллеги, Кирилл, Юра, так что же на Слуцк МК ?

**Comment by YRozmysl** [comment]
Если бы я зннал точно причину, написал, а так  только предположения и домыслы.
