### ISSUE TITLE
Материальный склад. Настройка остатков. Округления в суммируемых полях (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4080]
В форме складских остатков значения в суммируемых полях не округляются.
Сейчас возможно только при помощи мастера установок сделать хоть какое-то округление.
По-хорошему для большей точности необходимо в форме складских остатков предусмотреть возможность настройки корректного округления по суммируемым полям (до 2-х знаков после запятой).
На практике встречаются расхождения.

@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by NikolayUkleyko** [comment]
Стоимость остатков ТМЦ хранится до 2-х знаков после запятой, а не 4-х.
При сверке данных по бухгалтерскому и складскому учету возникают неточности из наличия 4-х знаков после запятой.

**Comment by MIchaelShoihet** [comment]
Просто есть понятие существенное и не существенно ошибки. Часть клиентов ошибки округления возникающие из-за 4 знаков, относят как не существенные и не обращают на них внимание. Часть смотрит не остатки, а оборотную ведомость в которой уже настроено обычно нужное округление. Тем более что как раз оборотная ведомость является тем документом, который подтверждает журналы по 10 счетам.

**Comment by MIchaelShoihet** [comment]
Вообще настройку округления можно сделать, но это на уровне платформы, и туда необходимо перенести эту задачу.

**Comment by NikolayUkleyko** [comment]
По-хорошему даже очень маленьких расхождений быть не должно.
Со временем они накапливаются.
Раньше, когда не было копеек в программе было фиолетово есть/нет округления и на сколько оно корректны.
Сейчас, когда работаем с копейками округления получают большУю актуальность.

Оборотная ведомость это хорошо.
Это отчет, в котором в коде и/или в шаблоне могут быть округления.

На мой взгляд ко всему имеющемуся функционалу все же хорошо бы предусмотреть возможность настройки округлений по суммируемым полям в форме складских остатков.

----

>Вообще настройку округления можно сделать, но это на уровне платформы, и туда необходимо перенести эту задачу.

@MIchaelShoihet , рассматриваемая тема размещена в ветке gedemin, а не apps.
@ShlTanya можно попросить.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , большое спасибо за беседу.
