### ISSUE TITLE
Ошибка при сохранении хранимой процедуры

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#4084]
1) Открываем процедуру
2) Нажимаем OK и получаем 
![image](https://user-images.githubusercontent.com/8355925/38565142-3c84fdc2-3ce9-11e8-8a9b-b60252a46332.png)

**Comment by alexandra-gsoftware** [comment]
это на всех ілі на какой-то конкретной?

**Comment by ShlTanya** [comment]
Если не зайти на закладку Текст процедуры и сразу нажать ОК.. то на всех

**Comment by alexandra-gsoftware** [comment]
хммм странно, раньше вроде не было... ілі просто нікто так не делал))

**Comment by ShlTanya** [comment]
исправила

**Comment by YRozmysl** [comment]
Вроде, все ок в последнем exe
