### ISSUE TITLE
Бухгалтерия. Конструктор функций. Ошибка при выборе бизнес-класса

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4085]
**Исследователь / Бухгалтерия / Автоматические хоз. операции, Типовые хоз. операции / Конструктор функций.**

При выборе конкретного значения аналитики через **_Переменная / Свойства блока / Вставить / Добавить аналитику / Прочие справочники_**.

Пример, выбрали бизнес-класс Подразделение с выбором подразделения.
Потом, внесли коррективы, выбрав бизнес-класс Статьи затрат с выбором статьи затрат.
Можно и наоборот.
Программа отображает окно с сообщением об ошибке:

![2018-05-02_181230](https://user-images.githubusercontent.com/11497453/39532575-c36309ee-4e35-11e8-9e9d-cc357bf1ac3d.jpg)

Это имеет силу и при выборе других бизнес-классов.
@ShlTanya , пожалуйста, посмотри.

**Comment by gsbelarus** [comment]
Где-то там внутри для лукапа при смене класса не очищается поле саб тайп.

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
