### ISSUE TITLE
В документе в позициях не просчитывается итог по числовому полю

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#4086]
Видел сам в разных документах такое поведение, но есть база на которой проблема выявляется 100%

Открываем документ. Нет итога по полю выход
![image](https://user-images.githubusercontent.com/8355925/39627992-4218eb0c-4fb0-11e8-8826-493c5176554a.png)

Заходим в "мастер установок". Признак проставлен. 
![image](https://user-images.githubusercontent.com/8355925/39627953-26bb55fc-4fb0-11e8-9496-263495c99cf6.png)

Нажимаем "ок" в Мастере и итог появляется
![image](https://user-images.githubusercontent.com/8355925/39628017-5d00a860-4fb0-11e8-8e99-f48e78892c4d.png)

Домен поля Выход, на всякий случай
![image](https://user-images.githubusercontent.com/8355925/39628040-6fb44c00-4fb0-11e8-80e2-54279319c7ec.png)

**Comment by NikolayUkleyko** [comment]
@stasgm, пожалуйста, выполни единые настройки всех гридов позиции документа.

**Comment by stasgm** [comment]
@NikolayUkleyko Не припоминанию такой функции как "выполнить единые настройки")  Или я что-то 
 недопонял?

**Comment by alexandra-gsoftware** [comment]
Был такой баг: грид в форме редактирования подхватывает некоторые(!) настройки грида с формы просмотра. Может, и сейчас есть. Может, это он и есть.

**Comment by alexandra-gsoftware** [comment]
Настрой суммирование в форме просмотра и посмотри, что будет.

**Comment by stasgm** [comment]
@alexandra-gsoftware Остался, видимо, баг. В форме просмотра настроил подсчёт и в форме редактирования отобразилось.

**Comment by MIchaelShoihet** [comment]
Это не то что бы баг... Просто дата сет у обоих гридов один и тот же. Скажем - так запроектировано...

**Comment by NikolayUkleyko** [comment]
>Не припоминанию такой функции как "выполнить единые настройки") Или я что-то
недопонял?

@stasgm , я имею в виду один из следующих вариантов:
1. Сохранить в шаблон настройки позиции грида и загрузить их на всех гридах позиции документа.
2. На каждом гриде позиции выполнить одинаковые настройки форматирования.

Пример, складской документ.
Есть 3-и грида:
- в форме журнала документов;
- непосредственно в диалоговой форме;
- в форме выбора из остатков.

Так вот, настройки числовых полей во всех компонентах должны быть одинаковые.

----

@stasgm , такое мы уже давно очень интенсивно обсуждали:
https://github.com/GoldenSoftwareLtd/gedemin/issues/3706

Огромное спасибо @ShlTanya .
Как результат - кратко и точно:

>Просто дата сет у обоих гридов один и тот же. Скажем - так запроектировано...
