### ISSUE TITLE
Произвольное отображение окна с сообщением о таблице идентификаторов (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4087]
На различных БД МК при запуске Автоматических хоз. операций, установке ПИ и в любых других случаях не первый раз замечено появление следующего окна:

![default](https://user-images.githubusercontent.com/11497453/40048758-afeb0672-583b-11e8-8b3f-aa743a0a4414.jpg)

Нажав на **Отмена** расчет и прочие команды продолжают корректно выполняться.
@gsbelarus , очевидно, что данное сообщение не должно появляться в подобных ситуациях.

**Comment by YRozmysl** [comment]
Да, встречал такое тоже на некоторых базах, на ГМК в том числе

**Comment by gsbelarus** [comment]
это означает, что ИД там перешел за 1.6 миллиарда.

**Comment by gsbelarus** [comment]
как встретите -- говорите мне. хочу посмотреть где у нас еще такие базы взялись. или там какой-то старый экзе.

**Comment by alexandra-gsoftware** [comment]
на эталоне есть такое сообщение.
