### ISSUE TITLE
Бухгалтерия. Сложные проводки и реквизит 'Сохранять нулевую проводку'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4088]
**Исследователь / Бухгалтерия / Конструктор функций.**

Пожалуйста, подскажите, работает ли в сложных типовых проводках реквизит **Сохранять нулевую проводку** ?

**Comment by MIchaelShoihet** [comment]
Реквизит работает для любой проводки. Но после его установки надо зайти в конструктор и сохранить. Т.к. это галка влияет на код формирования проводки

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@MIchaelShoihet , спасибо !
