### ISSUE TITLE
Бухгалтерия. Конструктор функций. Ошибка при открытии блоков с указанным счетом

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4089]
**Исследователь / Бухгалтерия / Типовые хоз. операции.**

При редактировании в типовых проводках блоков (типовая проводка, позиция типовой проводки) с указанным счетом программа отображает следующее окно:

![2018-05-22_112223](https://user-images.githubusercontent.com/11497453/40350442-7ed8f9f0-5db2-11e8-9a7c-5f2416b645e2.jpg)

Имя файла            = gedemin.exe
Дата файла           = 20.05.2018
Версия файла         = 2.9.4.9963

----

Жанна просила к этой теме добавить слово "срочно".

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
