### ISSUE TITLE
Ошибка при выборе в окне множества

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4091]
@ilonaand может дать пояснения как ее вызвать.

Пока мне пришлось откатить сделанные изменения. Комит с откатом:

https://github.com/GoldenSoftwareLtd/gedemin-private/commit/3c11c3df2657f754923fb1f58b5282911b3b9433

**Comment by ShlTanya** [comment]
@ilonaand расскажите мне, пожалуйста, моменты, при которых возникает ошибка.

**Comment by ilonaand** [comment]
Добрый день. Ошибка возникает, если использовать выбор из множества, с которым уже работали до того, и сохранились старые выбранные значения. При попытке нажать стрелку возврата, то есть убрать из выбранных, кидает ошибку out of index Посмотреть можно на любой рабочей базе, где есть отчеты с выбором из множества

**Comment by ShlTanya** [comment]
Исправила. Ошибка была, если в источнике не было такой записи.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
