### ISSUE TITLE
Материальный склад. Форма 'Карточка ТМЦ'. Не отображаются выбранные ТМЦ...

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4093]
**Исследователь / Материальный склад / Отчеты по складу / Карточка ТМЦ (мат. склад).**

Не отображаются выбранные ТМЦ.
Попутно, пожалуйста, предусмотрите в выпадающем списке реквизита **ТМЦ**, **Подразделение** сортировку по возрастанию.
Это имеет силу, как для формы, появляющееся при вызове ярлыка из исследователя, так и для основной формы карточки ТМЦ.

----

Пожалуйста, предусмотрите в реквизите **Тип документа (прихода, расхода)** отображение только складских документов.
Согласитесь, пользовательские документы здесь не нужны.

----

При выборе конкретных документов прихода, расхода данные выводятся неверно.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , @ShlTanya , пожалуйста, изложите ваши точки зрения.

**Comment by alexandra-gsoftware** [comment]
А что значит "Не отображаются выбранные ТМЦ"?
Где они не отображаются?

**Comment by NikolayUkleyko** [comment]
В простой форме ввода параметров:

![2018-09-05_152015](https://user-images.githubusercontent.com/11497453/45093286-a2035f80-b120-11e8-9b31-7ca33cfc372e.jpg)

----

Выбрав требуемые ТМЦ, проставив CheckBox, сохраняем:

![2018-09-05_152113](https://user-images.githubusercontent.com/11497453/45093311-b5162f80-b120-11e8-855f-5e78916050d5.jpg)

----

Выбранные записи не видны:

![2018-09-05_152126](https://user-images.githubusercontent.com/11497453/45093329-bcd5d400-b120-11e8-9301-1f1f363ab595.jpg)

----

Аналогично и для сложной формы ввода параметров:

![2018-09-05_152159](https://user-images.githubusercontent.com/11497453/45093402-f4448080-b120-11e8-9b9d-280cb0e3554d.jpg)

**Comment by NikolayUkleyko** [comment]
Реально ж не работает.
Как будто никто не работает с карточкой ТМЦ ?

**Comment by ShlTanya** [comment]
Проверила.. все отображается
![default](https://user-images.githubusercontent.com/24572314/46406034-dd3e8180-c712-11e8-84e0-013fbe43c88b.JPG)

**Comment by NikolayUkleyko** [comment]
@ShlTanya , что же было ?

**Comment by ShlTanya** [comment]
Николай, проверьте у себя еще раз

**Comment by NikolayUkleyko** [comment]
Как только перекомплируют gedemin.exe, включая данную доработку.

**Comment by ShlTanya** [comment]
Я ничего не делала. Поэтому и прошу проверьте точно.

**Comment by alexandra-gsoftware** [comment]
Проверила. В AT_RELATIONS есть поле LISTFIELD. Если у GD_GOOD внести сюда, например, штрихкод, то в параметрах карточки тмц будут вместо названий штрихкоды, и тд. Кто-нибудь знает, для чего этот LISTFIELD? На что он еще влияет (я не нашла)?

**Comment by gsbelarus** [comment]
listfield из at_relations автоматом подставляется в лукапы, там где соответствующее свойство не настроено вручную.

**Comment by alexandra-gsoftware** [comment]
Хмм, может, карточка тмц (стандартная екзешная) не должна все же это поое подхватывать?

**Comment by NikolayUkleyko** [comment]
Перелопатил руководство пользователя.
Там сказано про использование  расширенного отображения полей таблиц в Журнал-ордере.
Да, это работает замечательно и удобно.
Но, не сказано, что настройки расширенного отображения полей таблиц влияют еще и на работу стандартной формы карточки ТМЦ.
Ведь не исключены ситуации, когда для Журнал-ордера необходимы одни настройки расширенного отображения полей таблиц, а для карточки ТМЦ и другого иные настройки.

**Comment by MIchaelShoihet** [comment]
Вообще расширенноые отображения работают практически везде. Это общая функция для всех режимов. В Журнале-ордере их можно не использовать...

**Comment by NikolayUkleyko** [comment]
Большое спасибо всем за беседу.
Узнали много чего интересного.
