### ISSUE TITLE
ОК. Перенос рабочих (выходных) дней

### ISSUE THREAD

**Issue by hjamesgs** [GoldenSoftwareLtd/gedemin#4095]
Необходимо в ОК создать новый документ, в котором будут фиксироваться переносы рабочих дней.
Необходим для корректного формирования табеля отработанного времени.

Республиканские переносы применяются только в отношении работников, которым установлена пятидневная рабочая неделя с выходными днями в субботу и воскресенье, и не распространяются на работников с суммированным учетом рабочего времени или шестидневной рабочей неделей (п. 1 Правил планирования и учета рабочего времени работников в связи с переносом Советом Министров Республики Беларусь отдельных рабочих дней, утвержденных Постановлением Министерства труда Республики Беларусь от 25.06.2001 N 75 (далее - Правила переноса)).

**Пример1**. Штатный преподаватель высшего учебного заведения работает в режиме шестидневной рабочей недели (понедельник - суббота). Республиканский перенос рабочих дней на него не распространяется.

**Пример2**. В 2014 году рабочий день 4 июля был перенесен на 12 июля. Работник, работающий в режиме пятидневной рабочей недели с выходными днями в субботу и воскресенье, находился в отпуске в период с 23 июня 2014 г. по 7 июля 2014 г. Поскольку перенесенный рабочий день (4 июля) для работника в связи с нахождением в отпуске не мог быть рабочим, то 12 июля 2014 г. для работника будет выходным днем.

Важно обработать такие варианты, как в примере2.

**Comment by YRozmysl** [comment]
Сразу напрашивается вопрос, как и где определять какой учет расчеты зп, вернее график. Ведь, графиков можно создать сколь угодно много.
