### ISSUE TITLE
ЗП. Осовременивание отпусков, при изменении должности.

### ISSUE THREAD

**Issue by hjamesgs** [GoldenSoftwareLtd/gedemin#4096]
Если работник переведен на **иную должность**, зарплата по прежней должности осовременивается исходя из оклада, действующего в месяце, предшествующем месяцу перевода.

**Пример**
Бухгалтеру предоставляется трудовой отпуск с 04.05.2018. На эту должность работник переведен 01.01.2018, а до этого он трудился в этой организации помощником бухгалтера. Средний заработок рассчитывается за период с 01.05.2017 по 30.04.2018.
Организация применяет гибкие условия оплаты труда (без ЕТС и тарифной сетки). Тарифный оклад (при его формировании повышения различного рода не применяются) установлен для должности:
- помощника бухгалтера:
до 01.07.2017 - 200 руб.;
с 01.07.2017 по 31.12.2017 - 300 руб.;
на 04.05.2018 - 400 руб.;
- бухгалтера:
на 01.01.2018 - 600 руб.;
с 01.03.2018 - 700 руб. (далее не изменялся).

Представим расчет поправочного коэффициента в таблице:

![image](https://user-images.githubusercontent.com/11534388/41041796-c270450e-69a8-11e8-9fdd-ec76bd422dd9.png)

**Comment by YRozmysl** [comment]
Я так понимаю, что речь идет  о переводе с 1 часла месяца? А если в середине то, что ?
