### ISSUE TITLE
После сообщения об ошибке, при формировании складского движения, документ можно сохранить.

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin#4097]
1) Пользователь делает перемещение с точки А на точку Б.
![image](https://user-images.githubusercontent.com/8355925/41086794-c261c3e4-6a43-11e8-9fbd-8bf4bc403d01.png)
2) Делает списание этого товара с точки Б
![image](https://user-images.githubusercontent.com/8355925/41086844-e0389f82-6a43-11e8-9c20-4df2aac1d059.png)
3) Замечает, что "ой, я не туда передала", и изменяет в перемещении получателя с Б на С
![image](https://user-images.githubusercontent.com/8355925/41086885-fb1a51ec-6a43-11e8-8412-155586fd14e4.png)
4) Нажимает "ок" в сообщении и сохраняет документ
![image](https://user-images.githubusercontent.com/8355925/41086915-099fd034-6a44-11e8-8ad4-6eb93e75a9c9.png)

Пользователь считает, что всё хорошо, что товар переместился. Но не задумывается, что было списано с точки Б.  Звонят и говорят, что на остатках в точке С нет товара, хотя документ на выдачу есть (если списать не всё, как в примере).  Пользователь, конечно, не расскажет, что он делал за манипуляции с товаром. И начинается расследование. 

По факту выходит, что товар не переместился с Б на С. Но в документе указана точка С.

Вопрос знатокам - как поступать в данном случае?

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@stasgm ?

**Comment by stasgm** [comment]
Тема актуальная. трабл в exe. Получатель в шапке и в позициях отличается.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, изложите Вашу точку зрения.

**Comment by MIchaelShoihet** [comment]
Какую точку зрения? Ошибка ее надо исправить. Это в работе

**Comment by MIchaelShoihet** [comment]
Смотреть на последнем exe
