### ISSUE TITLE
Бухгалтерия. Журнал-ордер. В расшифровке по Дт и по Кт пропали промежуточные итоги по количественным показателям

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4105]
**Исследователь / Бухгалтерия / Журнал-ордер.**

В расшифровке по Дт и по Кт пропали промежуточные итоги по количественным показателям:

![2018-07-24_110501](https://user-images.githubusercontent.com/11497453/43125132-cf5af242-8f31-11e8-9345-274c71dbef80.jpg)

Раньше работало корректно.

@ShlTanya , пожалуйста, поправь.

**Comment by NikolayUkleyko** [comment]
Очевидна недоработка.
Раньше работало корректно.

**Comment by NikolayUkleyko** [comment]
Напоминаю, что данный вопрос относится к реальной повседневной работе бухгалтера по учету ГСМ и другие.
Его следует сделать.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
