### ISSUE TITLE
Общие. Нельзя удалить таблицу без записей и ссылок

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4107]
Создаем новую таблицу с идентификатором и служебными полями.
Переподключаемся.
Пробуем удалить только что созданную таблицу.
Программа не позволяет это сделать и выдает следующее окно с сообщением об ошибке:

![2018-08-29_185815](https://user-images.githubusercontent.com/11497453/44799839-96aeb200-abbd-11e8-8997-566fdd749e82.jpg)

@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
исправила

**Comment by NikolayUkleyko** [comment]
@ShlTanya , что же было ?

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
