### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Аналитика 'Дата проводки', 'Товар' и количественные показатели

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4108]
**Исследователь / Бухгалтерия / Журнал-ордер.**

При формировании Журнал-ордера со следующими параметрами:
![2018-10-04_124844](https://user-images.githubusercontent.com/11497453/46466728-bb0d3800-c7d4-11e8-9b9e-3db1f62ab0ff.jpg)

Получаем следующий результат:
![2018-10-04_125047](https://user-images.githubusercontent.com/11497453/46466735-bd6f9200-c7d4-11e8-8721-7c0df8131b9b.jpg)

На конец периода сальдо по сумме и по количеству неверное.
В данном примере на конец периода должно быть сальдо по дебету на сумму оборота по дебету.
При этом входящего сальдо на начало периода не было.

----

Для сравнения можно сформировать Журнал-ордер со следующими параметрами:
![2018-10-04_125633](https://user-images.githubusercontent.com/11497453/46467177-c319a780-c7d5-11e8-801b-bfe613f2ebf0.jpg)

Получаем следующий результат:
![2018-10-04_125725](https://user-images.githubusercontent.com/11497453/46467250-f0feec00-c7d5-11e8-95d1-92d5adbbed6e.jpg)

На конец периода сальдо по сумме и по количеству верное.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet и @ShlTanya , пожалуйста, изложите ваши точки зрения.

**Comment by MIchaelShoihet** [comment]
Уже тысячу раз говорили, о том что нельзя комбинировать временную аналитику с качественной. Дата проводки, месяц, квартал - это временные и сальдо там переходящие... Такие аналитики можно совмещать только для анализа оборотов.

**Comment by NikolayUkleyko** [comment]
У меня Жанна про данный вопрос спрашивала.
Я ей изложил аналогичный ответ.
Теперь Жанна будет знать.

Большое спасибо за ответ, @MIchaelShoihet !
