### ISSUE TITLE
Бухгалтерия. Карта счета. Предусмотреть возможность отображения пользователя

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4110]
**Исследователь / Бухгалтерия / Карта счета.**

Пожалуйста, подскажите, можно ли добавить в данную форму колонки с отображением локализованного имени пользователя, выполнившего **создание** и **редактирование** соответствующей записи ?

**Comment by NikolayUkleyko** [comment]
@gsbelarus , что скажете по данной теме ?

**Comment by gsbelarus** [comment]
как только разберемся с ид, сделаем

чц, 31 сту 2019, 19:30: карыстальнік NikolayUkleyko <
notifications@github.com> напісаў:

**Comment by NikolayUkleyko** [comment]
@gsbelarus , благодарю.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Пока решили не делать.
Предусмотрены макросы отображающие свойства записи (проводки) с указанием имени пользователя и другой информации.
