### ISSUE TITLE
Поиск в скриптфункциях с заменой

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#4113]
Сейчас мы работаем над переходом на новый формат для ключей - int64.
В метаданных БД (триггеры, хранимые процедуры, представления) можно просто заменить INTEGER на BIGINT, и ничего не сломается (в 99% случаев в переменной с типом INTEGER хранится ключ, а если вдруг там хранится день недели - ну будет он BIGINT, ничего страшного.

В макросах не все так однозначно. INTEGER может относится к скрипту формирования какой-нибудь ДБФ-ки, и заменять его не глядя нельзя.

У нас есть классный поиск в скриптах. Результат поиска выводятся вот так:
![default](https://user-images.githubusercontent.com/11487200/51201697-ca406d80-190d-11e9-8d15-412b5cbec66e.png)
При клике по строке происходит переход на эту функцию, эту строку.

Я предлагаю аналогично сделать замену по всем скриптам.
1) задаем, что нужно найти и на что заменить. Поиск можно оставить таким же, или можно добавить возможность использовать регулярные выражения
2) видим такую же форму с результатами.
3) оттуда можно или открыть скрипт, или заменить.

Если сделаете, то будет полезно не только для вопроса bigint, но и вообще:)

**Comment by gsbelarus** [comment]
Поясню задачу. Нам предстоит на некоторых больших базах произвести трансформацию кода макросов в связи с переходом на 64 битные идентификаторы. В связи с этим хочется дать программисту в руки инструмент для упрощения этой работы.

## Улучшения в поиске

1. Поиск по регулярным выражениям
2. Не искать в тексте комментариев

![image](https://user-images.githubusercontent.com/5175764/51263183-cf142880-19c4-11e9-9794-3f8e2657908d.png)

## Поиск и замена

Смотрите сами как лучше окно организовать. Или вкладку отдельную "Поиск и замена" или увеличить эту вкладку и вставить еще поле для замены и сделать две кнопки вместо одной "Ок" -- "Поиск", "Поиск и замена".

## Список для замены

Операция "Поиск и замена" никогда не заменяет ничего сразу. Она выводит список найденного, но с тулбаром и чекбоксами против каждой строки.

![image](https://user-images.githubusercontent.com/5175764/51263570-9759b080-19c5-11e9-9bb6-36957d23bc11.png)

Пользователь может:

1. Кликом на любой строке в найденном открыть макрос на соответствующей вкладке. Если там курсор будет подведен к найденному тексту, вообще будет отлично.
2. Выделить все чекбоксы кнопкой на тулбаре. 
3. Снять все чекбоксы кнопкой на тулбаре.
4. Заменить для текущей записи.
5. Заменить для всех отмеченных чекбоксами записей.

При этом, изначально все чекбоксы сняты.

После замены, соответствующая позиция из списка убирается.

**Comment by ShlTanya** [comment]
Выполнено

**Comment by alexandra-gsoftware** [comment]
Спасибо, Татьяна!
Хотелось бы добавить:
1) чтобы новое окошко было доступно в меню редактора скрипт объектов \окна
2) если ф-я , где надо провести замену, сейчас в состоянии редактирования, то замена не произойдет, тк текст ф-и не перечитывается перед заменой, и в итоге после замены заново сохранится старый текст. Поэтому, если ф-я, в оторой надо провести замену, открыта, надо:
а) сохранить ее (если не сохранена)
б) заменить
в) закрыть (или обновить текст на тот, который с заменой)

**Comment by ShlTanya** [comment]
2 пункт. Думала над этим.. Для себя выбрала вариант только оповестить пользователя, что ф- я открыта и предложить сохранить ее. А вдруг вы нечаянно что-то там внесли/удалили и сами не заметили. А я все сохраню.

**Comment by ShlTanya** [comment]
Поговорите и скажите правильный вариант действий в данной ситуации.

**Comment by ShlTanya** [comment]
Доработано.

**Comment by alexandra-gsoftware** [comment]
Работает, спасибо!
