### ISSUE TITLE
Загадочные РУИДы: РУИД генерируется, хотя не должен

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#4114]
Замечено, что записям из INV_MOVEMENT могут соответствовать данные в GD_RUID!
И на клиентских базах, и на эталоне.
На эталоне я работаю под администратором, создаю\удаляю\редактирую разные документы. По некоторым движениям руиды есть, по другим - нет. От типа документа не зависит. По одной позиции одной шапки руид может быть, по другой - нет.

Вот  есть даже пример. Обратите внимание на выделенную часть: 4 движения созданы по одной и той же позиции, по одной паре руиды есть, по другой - нет.
![ruid](https://user-images.githubusercontent.com/11487200/51203662-aaf80f00-1912-11e9-9f7b-6406dd2c1838.png)

Поискала в скриптах и метаданных - не нашла, где может вставляться РУИД (где-то в ехе?).

Если мы перейдем на другой генератор, а руиды втихаря будут создаваться для мувментов и проводок, можем в итоге получить конфликт при записи в гд_руид.

Надо понять, где эти руиды вставляются, и зачем.

**Comment by MIchaelShoihet** [comment]
Это очень конечно странно. Но будем искать.

**Comment by ilonaand** [comment]
Мало того, замечены таблички, судя по виду, создающиеся чисто из скриптов, например в березе какая-то старая табличка для связи накладных и требований( не исп с 2005) года, и с записями в gd_ruid

**Comment by alexandra-gsoftware** [comment]
@ilonaand я немного переделаю поиск по руид и поиск по ид. Возможно, это дубликаты ИД.

Кстати-кстати, такие штуки появятся при использовании ИНТЕРВАЛОВ.
Надо как-то уничтожать руиды при удалении объектов.

**Comment by gsbelarus** [comment]
если через бо идет удаление, то руид удаляется помойму.

аў, 15 сту 2019, 22:30: карыстальнік alexandra-gsoftware <
notifications@github.com> напісаў:

**Comment by alexandra-gsoftware** [comment]
@gsbelarus 
хорошо, если так, спасибо.

Я модифицировала Поиск по ИД и поиск по РУИД. Теперь можно исключать из поиска некоторые таблицы. Т.е. можно искать и дубликаты ИД.

Проверила пример с эталона, где по 1 док-ту 4 движения и на них два руида. Один из айдишников, по которым есть руид, используется еще в GD_JOURNAL. Теоретически РУИД мог прийти оттуда. Второй ИД нигде больше не используется.

**Comment by NikolayUkleyko** [comment]
Актуальна ли данная тема ?
