### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Переход на карту счета по аналитике с противоречащими contacttype

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4128]
**Исследователь / Бухгалтерия / Журнал-ордер.**

Пример, формируем Журнал-ордер по счету, где есть только аналитика Подразделение (Сотрудник) (contacttype in (2, 4).
При этом, в качестве значения для данной аналитики могут быть выбраны записи с contacttype = 3.
В данном случае при переходе на Карту счета ничего отображено не будет.
Да, логично.
Но, можно ли предусмотреть отображение данных в Карте счета в случае наличия ограничения в домене (условие выбора значений на языке SQL) ?

**Comment by MIchaelShoihet** [comment]
Давайте не будем делать лишнюю работу, а будем настраивать аналитику так как она должна отображаться....

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , спасибо !
