### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Ошибка при редактировании конфигурации

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4132]
**Исследователь / Бухгалтерия / Журнал-ордер.**

**1.** Сформировали форму со следующими параметрами:
![2019-03-22_170355](https://user-images.githubusercontent.com/11497453/54828145-9a726500-4cc4-11e9-8628-4723d39628d1.jpg)

**2.** Сохранили в конфигурацию.

**3.** При попытке редактирования конфигурации ошибка:
![2019-03-22_170415](https://user-images.githubusercontent.com/11497453/54828186-b5dd7000-4cc4-11e9-8e27-33584ea1c726.jpg)

----

Могу предположить, что ошибка связана с так называемой аналитикой **Тип документа**.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , что же скажешь ?

**Comment by NikolayUkleyko** [comment]
Проверено на разных аналитиках.
Аналитика **Тип документа** не является причиной ошибки.
Выбор галки по одной из аналитик **_Договор, Клиент, Тип НДС и т.д._** и редактирование текущей конфигурации как раз и приводит к вышеприведенной ошибке.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, поправь.

**Comment by ShlTanya** [comment]
Проверьте, пжст, точно ли есть данная ошибка. Если есть, приложите скрин с настройками журнал-ордера.

**Comment by NikolayUkleyko** [comment]
> _Проверьте, пжст, точно ли есть данная ошибка. Если есть, приложите скрин с настройками журнал-ордера._

@ShlTanya , посмотрел.
Ошибка на месте:
![image](https://user-images.githubusercontent.com/11497453/152312847-a35a4462-44bf-4b7f-862c-432ba3bb1c34.png)

Если, указать значение аналитики и пересохранить в конфигурацию, то на редактирование она открывается без ошибок.

**Comment by ShlTanya** [comment]
Исправлено. Ошибка возникала при отмеченной аналитики и не заполненном поле.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
