### ISSUE TITLE
Зависание при подключении через nssm

### ISSUE THREAD

**Issue by hirurg-lybitel** [GoldenSoftwareLtd/gedemin#4139]
Создана служба через nssm. [Вот ](http://gsbelarus.com/pw/articles/post/zapusk-prilozheniia-gedymin-v-vide-sluzhby-windows/) инструкция, если что.

При её работе, происходит подключение к базе, но почему-то всё на этом и останавливается. Не происходит загрузка списка автозадач, а, следственно, и их выполнение.

![image](https://user-images.githubusercontent.com/11502258/58639587-e7e00380-82ff-11e9-8f96-6d12c8ceaf12.png)

А вот так это должно выглядеть. 

![image](https://user-images.githubusercontent.com/11502258/58639633-02b27800-8300-11e9-95f7-b04f2df99ab3.png)

При этом подключение видно в списке пользователей. 
Хотелось бы узнать, что происходит после подключения к БД со списком автозадач.

**Comment by hirurg-lybitel** [comment]
Проблема в формате даты системной учётной записи.

 Необходимо добавить сообщение об этом в лог, например:

> `Неверный формат даты m/d/yyyy. Требуемый формат dd.mm.yy`

**Comment by gsbelarus** [comment]
так, а почему виснет из за формата даты?

ср, 5 чэр 2019, 23:24 карыстальнік hirurg-lybitel <notifications@github.com>
напісаў:

**Comment by hirurg-lybitel** [comment]
Из-за этой строки в exe и последующей обработки.
MessageBox понятное дело не выводится

`Pos('dd.mm.yy', AnsiLowerCase(ShortDateFormat)) <> 1`

**Comment by ShlTanya** [comment]
Виснет, потому что неверный формат и программа пытается спросить.. нужно ли его менять.. А т.к. запуск службы Гедымина идёт от имени системной учётной записи, то окно с вопросом не отображается, программа ждёт ответа.. а его нет. Я предлагаю менять именно пользователя от имени которого стартует служба. Ведь не только настройки времени могут не совпадать.. ещё денежные единицы..

**Comment by gsbelarus** [comment]
нет. лучше все такие места вычислить и не выводить messagebox, а писать в
лог, если мы в режиме службы запускаемся.

запуск от учетной записи не очень хорош тем, что стоит сменить пароль этой
записи или отключить ее, как все перестанет работать.

ср, 19 чэр 2019, 09:04 карыстальнік ShlTanya <notifications@github.com>
напісаў:

**Comment by gsbelarus** [comment]
я еще чуть позже допишу, что думаю по этому поводу.

ср, 19 чэр 2019, 09:22 карыстальнік AK <gs1994@gmail.com> напісаў:

**Comment by ShlTanya** [comment]
Только как узнать что запускается именно как служба.. в строке подключения нет такой информации.

**Comment by gsbelarus** [comment]
надо у юрия спросить как там полностью строка запуска выглядит. а вообще, у
нас есть ключ /q, когда программа работает в тихом режиме и не выводит
ничего на экран.

ср, 19 чэр 2019, 09:36 карыстальнік ShlTanya <notifications@github.com>
напісаў:

**Comment by ShlTanya** [comment]
Я пробовала сама.. там нет никакого признака.

**Comment by gsbelarus** [comment]
нет возможности определить. просто тот кто настраивает запуск службой
должен прописывать ключ /q. это надо документировать и все.

ср, 19 чэр 2019, 09:41 карыстальнік ShlTanya <notifications@github.com>
напісаў:

**Comment by ShlTanya** [comment]
А что делать с неправильным форматом даты.. просто выводить в лог сообщение??

**Comment by gsbelarus** [comment]
да

ср, 19 чэр 2019, 09:45 карыстальнік ShlTanya <notifications@github.com>
напісаў:

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@hirurg-lybitel
