### ISSUE TITLE
Мастер установок. Задублированный формат отображения данных

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4141]
Пожалуйста, подскажите, зачем предусмотрено два одинаковых формата отображения данных ?

![2019-07-18_190137](https://user-images.githubusercontent.com/11497453/61473449-163c9f80-a98f-11e9-819a-a7afa59b4009.jpg)

Если, так сделано намеренно-пожалуйста, поясните.
Если, так сделано ошибочно-пожалуйста, внесите правки.

**Comment by ShlTanya** [comment]
Формат продублирован. Исправила.

**Comment by NikolayUkleyko** [comment]
Предварительно.
Благодарю, @ShlTanya !
:trophy:

**Comment by NikolayUkleyko** [comment]
@gsbelarus , можно пожалуйста, перекомпилируйте gedemin.exe, учитывая данную доработку и прочие.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо !
