### ISSUE TITLE
Типовые документы. Возможность настройки по дате (как в типовых проводках)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4142]
Скажите, пожалуйста, можно ли в типовых документах предусмотреть возможность настройки по дате ?
Так, как реализовано в типовых проводках.

**Comment by MIchaelShoihet** [comment]
Нет. Настраивается документ в целом, а не какая-то его часть. Проводке надо просто функцию выбрать, а тут все намного сложнее

**Comment by NikolayUkleyko** [comment]
Благодарю за ответ, @MIchaelShoihet !
Теперь порядок.
