### ISSUE TITLE
Поиск в скриптах

### ISSUE THREAD

**Issue by hirurg-lybitel** [GoldenSoftwareLtd/gedemin#4144]
Опции установленные при использовании **Найти и заменить** начинают применяться и к поиску.

Так, например, установив опцию **С учётом регистра** при замене чего-то где-то, при последующем обычном поиске (в котором нет такой опции) в любой скрипт-функции также будет применяться эта опция. 

#4143 

@ShlTanya

**Comment by ShlTanya** [comment]
А что значит обычный поиск, в котором нет такой опции. Опция с учетом регистра есть везде.

**Comment by hirurg-lybitel** [comment]
Значит, что не установлена

**Comment by ShlTanya** [comment]
Не могу повторить ситуацию. Найти и заменить.. это пункт меню Поиск в базе данных или Замена..

**Comment by hirurg-lybitel** [comment]
Замена

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@hirurg-lybitel @ShlTanya
