### ISSUE TITLE
Данные в поле таблицы USR$BN_CASHREPORT

### ISSUE THREAD

**Issue by NightTramp** [GoldenSoftwareLtd/gedemin#4146]
Если возможно, прошу подсказать порядок действий:
Создал два дополнительных поля в таблице USR$BN_CASHREPORT для отображения в шапке документа "Кассовый отчет". В них хочу поместить данные из полей таблицы позиции документа USR$BN_CASHREPORTLINE (а именно: USR$BN_CARDSUMMA и USR$BN_BACKCARDSUMMA). Эти поля заполняются при создании очередного кассового отчета. Но дальше познаний не хватает как связать эти поля в таблицах. 
Понятно что это вопрос дилетанта, но не знаю куда еще обратиться за помощью.

**Comment by NikolayUkleyko** [comment]
Актуальна ли данная тема ?

**Comment by NikolayUkleyko** [comment]
Close.

**Comment by alexandra-gsoftware** [comment]
Раз уже не актуально, закрываю
