### ISSUE TITLE
Параметр "Окно дат, при проверке на корректность"

### ISSUE THREAD

**Issue by aer1k** [GoldenSoftwareLtd/gedemin#4148]
"Сервис" → "Параметры..." → Вкладка "Общие" → Параметр "Окно дат, при проверке на корректность"

Пример:
1. Устанавливаем значение равное 5 годам (т. е. система будет выдавать сообщение при попытке сохранить запись с датой больше или меньше, чем 5 лет от текущей даты).
![image](https://user-images.githubusercontent.com/11476517/69547098-0751a380-0fa6-11ea-98ce-9a206afbc59f.png)
2. Пытаемся сохранить запись с датой **31.12.1899**.
3. Система не выдает никаких сообщений

Такая же история с датами меньше, чем **31.12.1899** (01.01.1000, 01.01.0200 и т. д.)
Исключение, когда год начинается с **00YY** (01.01.0044, 01.01.0098). В этом случае год преобразуется в **20YY** или **19YY** (01.01.2044, 01.01.1998).

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@aer1k , пожалуйста, проверь.
