### ISSUE TITLE
Конструктор функций / Добавить возможность поиска функций по сочетанию клавиш 'Ctrl + F'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4151]
![2020-02-04_104433](https://user-images.githubusercontent.com/11497453/73724067-96640000-473b-11ea-9d34-23619f19b5e9.jpg)

**Comment by stasgm** [comment]
@NikolayUkleyko может лучше строку поиска (типа фильтр) добавить сверху как в форме выбора бизнес-объектов?

**Comment by NikolayUkleyko** [comment]
@stasgm , пожалуйста, можно сделать поиск по значению в поле **Фильтр**.
Подобное реализовано в **_Сервис / Редактор экранных форм_**:

![2020-06-30_122035](https://user-images.githubusercontent.com/11497453/86109100-adc9ce00-bacc-11ea-8203-b5e78b6b7c66.jpg)

**Comment by ShlTanya** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
> Сделано

@ShlTanya , пожалуйста, уточни - без или с регулярными выражениями ?

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , подскажи, возможно ли предусмотреть поиск по регулярным выражениям ?

**Comment by NikolayUkleyko** [comment]
> Проверено. Работает корректно. @ShlTanya , подскажи, возможно ли предусмотреть поиск по регулярным выражениям ?

@gsbelarus , пожалуйста, подскажите можно ли предусмотреть такую возможность ?

**Comment by ShlTanya** [comment]
Доработано

**Comment by NikolayUkleyko** [comment]
Проверено.
Не работает.

**Comment by ShlTanya** [comment]
Что именно не работает

**Comment by NikolayUkleyko** [comment]
В конструкторе функций пробую выполнить поиск с регулярными выражениями
функции MatInv_GetVatType:
mat%type.
Не работает.

чт, 31 мар. 2022 г., 9:23 ShlTanya ***@***.***>:

**Comment by gsbelarus** [comment]
% это не регулярные выражения.

http://gsbelarus.com/gs/wiki/index.php/%D0%A0%D0%B5%D0%B3%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D1%8B%D0%B5_%D0%B2%D1%8B%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F

**Comment by NikolayUkleyko** [comment]
> _% это не регулярные выражения._

Хорошо.
Пожалуйста, просто предусмотрите подобный поиск:
![image](https://user-images.githubusercontent.com/11497453/161041309-c2903e87-90e3-4e5f-9332-077a70244883.png)

**Comment by ShlTanya** [comment]
А регулярные выражения уже убрать?

**Comment by NikolayUkleyko** [comment]
> _А регулярные выражения уже убрать?_

Как выяснилось, можно убрать.

**Comment by ShlTanya** [comment]
знак % используется в поиске в запросе с Like.. построение этой формы построено по-другому принципу. Точно ли надо переделывать весь алгоритм формирования.

**Comment by gsbelarus** [comment]
не надо

**Comment by gsbelarus** [comment]
там поддерживаются регулярные выражения которые в сотни раз мощней простых
шаблонов SQL

**Comment by gsbelarus** [comment]
конкретно этот пример:

mat%type

соответствует регулярное выражение:

mat.*type

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает.
Спасибо.
