### ISSUE TITLE
Теряются документы исключения из блокировки периода

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4154]
В базе после конвертации нет документов исключения из блокировки периода:
Главное меню Сервис\Параметры В окне Опции системы, закладка Аудит и безопасность.
Нижнее мемо, оно пустое, хотя в оригинале много документов.
![Опции системы](https://user-images.githubusercontent.com/11498750/80117574-042c0500-8590-11ea-9e50-5c989fc34782.jpg)

**Comment by MIchaelShoihet** [comment]
Не работает. Для проверки надо взять базу до конвертации. Посмотреть что там есть документы исключения, если нет добавить, сконвертировать и посмотреть. Сейчас не работает.

**Comment by ShlTanya** [comment]
исправила

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, подскажите верно ли работает рассматриваемый функционал ?
