### ISSUE TITLE
Кнопка справки на форме "Объединение записей"

### ISSUE THREAD

**Issue by MAliaksandr** [GoldenSoftwareLtd/gedemin#4155]
Можно ли добавить стандартную кнопку "Справка" на "Объединение записей"?
![image](https://user-images.githubusercontent.com/11478712/80205087-ba482b00-8632-11ea-9a9f-9ca38462bc27.png)

**Comment by gsbelarus** [comment]
По аналогии, как кнопка Справка сделана в диалоговых окнах.

**Comment by MAliaksandr** [comment]
Кнопка пока так и не появилась.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, добавь кнопку **Справка** и переход на http://gsbelarus.com/gs/wiki/index.php/Объединение_записей.

**Comment by DonPhantom000** [comment]
Кнопка добавлена
