### ISSUE TITLE
Неправильно считываются ID  в массив SelectedID

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4156]
После конвертации базы в ID64, при открытии любого документа из потока считывается массив ID SelectedID и похоже он считывается не верно... Получаются числа с количеством знаков > 15. Что бы повторить надо взять базу 32, на ней выделить несколько записей, желательно по больше, и добавить в отмеченные. После этого выйти сконвертировать базу и затем смотреть, как идет считывание в этом документе

**Comment by gsbelarus** [comment]
надо наверное конвертировать эти потоки утилитой конвертации бд

**Comment by ShlTanya** [comment]
Исправлено

**Comment by MIchaelShoihet** [comment]
Проверено
