### ISSUE TITLE
Ошибка в параметре отчета типа множество с руидом в условии

### ISSUE THREAD

**Issue by sunnycreature** [GoldenSoftwareLtd/gedemin#4157]
Добавила условие в параметр множества в отчете, содержащее руид "EXISTS  (SELECT t.ID FROM GD_DOCUMENTTYPE t  WHERE  t.ID=<RUID XID=147010777 DBID=119560140/> AND t.LB <= gg1.LB AND t.RB >= gg1.RB)". При добавлении значения в форме выбора записей бросает ошибку в запросе, где видно, что экзешник подставляет алиас таблицы, где не надо:  "t.ID=<gg1.RUID XID=147010777 DBID=119560140/>"
![image](https://user-images.githubusercontent.com/12336960/83615932-daeb9500-a58f-11ea-885e-0becde54c854.png)

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@sunnycreature @alexandra-gsoftware

**Comment by sunnycreature** [comment]
Проверено. Все работает.
