### ISSUE TITLE
Автозадача. 

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4158]
Если в автозадаче выбрана опция, что она должна выполнится при запуске системы, но еще и будет стоять время, то после запуска она еще смотрит и на время. Или такая и была логика? я как понимаю, что задача должна выполнится сразу после ЗАПУСКА системы.  Нет?

**Comment by NikolayUkleyko** [comment]
Могу предположить, что указанное время будет приоритетно.
