### ISSUE TITLE
Странная проверка прав в сложном диалоге

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4159]
У В. есть пример на БД С. Сложный диалог с несколькими БО внутри. При попытке работы с одним из них права проверяются не от БО, а от класса его диалогового окна. Надо подключиться из компилятора и посмотреть по коду, что там происходит.

**Comment by YRozmysl** [comment]
на эталоне все нормально, проблема была в частном решении.  можно закрывать

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
