### ISSUE TITLE
Загрузка ПИ. Справочник LBRBTree типа

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4160]
Есть конкретная настройка, в которой в хранилище прописано: 

object Detail: TgdcAttrUserDefinedLBRBTree
            MasterField = 'ID'
            DetailField = 'PARENT'
            SubSet = 'ByParent'
            Active = False

Однако после загрузки ее на базу, в хранилище мы получаем следующее, что сказывается на корректной работе
           object Detail: TgdcAttrUserDefinedLBRBTree
            MasterField = 'ID'
            DetailField = 'RootID'
            SubSet = 'ByRootID'
            Active = False
Что это может быть, где происходит эта подстановка в момент загрузки настройки?

**Comment by ShlTanya** [comment]
Смоделировала данную ситуацию на примере GS.Бухгалтерия.Статьи затрат.yml (object gdc_frmAttrUserDefinedLBRBTreeUSR_ACC_EXPENSES):

**Comment by ShlTanya** [comment]
object Detail: TgdcAttrUserDefinedLBRBTree
            MasterField = 'ID'
            DetailField = 'PARENT'
            SubSet = 'ByParent'
            Active = False
            Left = 436
            Top = 269
          end

**Comment by ShlTanya** [comment]
После загрузки ПИ в хранилище были верные данные. Также как и в ПИ. Можете ли мне дать свои данные для загрузки.

**Comment by YRozmysl** [comment]
вопрос утратил актуальность
