### ISSUE TITLE
Бухгалтерия. Автоматические проводки. Конструктор функций. Фильтр. Ошибка

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4162]
**Исследователь / Бухгалтерия / Автоматические хоз. операции.**

Добавляем блок, например, **Цикл по счету**.
При добавлении значения в фильтр и последующем сохранении блока программа выдает сообщение об ошибке:

![2020-09-24_155126](https://user-images.githubusercontent.com/11497453/94148188-f8b27200-fe7e-11ea-94be-95a966b26fb8.jpg)
![2020-09-24_155255](https://user-images.githubusercontent.com/11497453/94148203-fe0fbc80-fe7e-11ea-87cc-856a912dd169.jpg)

Достаточно убрать кавычки и блок сохраняется без ошибок.
Возможно, так было сделано намеренно ?
Если, нет — пожалуйста, уберите автоматическое добавление кавычек.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
@ShlTanya , спасибо !
Работает по другому.
Теперь без кавычек аналогичное сообщение.

**Comment by ShlTanya** [comment]
Так работает верно или нет?

**Comment by NikolayUkleyko** [comment]
При такой настройке программа отображает сообщение об ошибке:
![image](https://user-images.githubusercontent.com/11497453/155107469-44bc9ddd-ff2b-4759-90b6-708af4a5fd1d.png)
![image](https://user-images.githubusercontent.com/11497453/155107488-1ebafc7b-c618-44b4-9005-b58d975b92ab.png)

Если, заполнить параметры следующим образом, то ошибок нет:
![image](https://user-images.githubusercontent.com/11497453/155107561-22813896-975d-435f-992f-1ca395377144.png)

Ранее не было необходимости в заполнении параметра **Аналитика**.
Ладно, можно оставить как есть.

**Comment by gsbelarus** [comment]
![image](https://user-images.githubusercontent.com/5175764/155109125-ca0d03cf-373b-4145-8496-460191ea54a9.png)

ошибка осталась

**Comment by gsbelarus** [comment]
так как пользователь выбирает значение, как оно формируется и потом подставляется -- не должно кидать ошибок. с кавычками или без не важно. если пользователь выбрал аналитику и подставился руид в кавычках -- дальше программа не должна кидать ошибку. если приняли, что подставляем без кавычек, то дальше программа не должна кидать ошибок.

изначальная проблема в том, что одна кнопка программы формирует значение на которое другая кнопка этой же программы ругается.

**Comment by gsbelarus** [comment]
и заодно поправить выравнивание меток, а то они в разнобой идут:

![image](https://user-images.githubusercontent.com/5175764/155109715-b8bb05b2-5bc4-46f9-91f8-5f05d292adad.png)

**Comment by gsbelarus** [comment]
и тут кнопки убежали

![image](https://user-images.githubusercontent.com/5175764/155109850-39e43a77-ea1b-4288-bd9a-56aa13c5d94f.png)

**Comment by gsbelarus** [comment]
и еще важно, чтобы старый код продолжил работать без изменений. а то вы поправите сейчас с кавычек на безкавычек и старый код весь начнет кидать ошибки. будет катастрофа.

**Comment by ShlTanya** [comment]
Формы исправлены. Алгоритм обработки фильтра согласован с Михаилом Юрьевичем.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
