### ISSUE TITLE
Типовые документы. Для складских признаков предусмотреть реквизит EDITIONDATE

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4163]
Пожалуйста, предусмотрите в типовых документах для складских признаков отображение реквизита **EDITIONDATE**:
![2020-09-28_164743](https://user-images.githubusercontent.com/11497453/94441747-ccaf2d80-01ab-11eb-8080-d7a674e78b2e.jpg)

**Comment by Polfath** [comment]
Изменения в структуру таблиц БД пока вносить не будем. Хотя, если честно, не совсем понятно для чего это поле. Ну изменил ты, проставилась дата изменения, и для чего потом она нужна, кроме того, что есть информация об этом. От нее ни горячо, ни холодно.

**Comment by MIchaelShoihet** [comment]
Не будем.

**Comment by NikolayUkleyko** [comment]
> _”Изменения в структуру таблиц БД пока вносить не будем. Хотя, если честно, не совсем понятно для чего это поле. Ну изменил ты, проставилась дата изменения, и для чего потом она нужна, кроме того, что есть информация об этом. От нее ни горячо, ни холодно.”_

Смысл в том, чтобы видеть когда был добавлен тот или иной складской признак, изменен параметр контроля складских остатков и т.д.
Пусть, такое требуется не так часто, но тем не менее.
