### ISSUE TITLE
Добавление записей в GD_RUID

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4166]
Похоже, что у нас сейчас в любом случае добавляется запись в GD_RUID. На одной из баз эта табличка уже содержит 474 млн записей! Надо разобраться. Изначальная логика была в том, что РУИДЫ создаются автоматически только при работе под учетной записью Administrator. Под остальными -- не должны. 

Как вариант поиска -- сделать триггер на GD_RUID, который бы бросал исключение при добавлении записи и посмотреть, когда он будет срабатывать.

Даже поведение с добавлением РУИДов под Administrator тоже спорное. Иногда под этой учетной записью делают перепроведение, что тоже приведет к добавлению ненужных РУИДов в таблицу.

**Comment by gsbelarus** [comment]
Может вообще отключить автоматическое добавление в таблицу GD_RUID. Зачем оно было надо изначально? Кто помнит?

**Comment by gsbelarus** [comment]
Вроде исправили. Надо снести ненужные РУИДы и понаблюдать, так как возможны другие места где необосновано добавляются РУИДы.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
