### ISSUE TITLE
Удаление ненужных записей из GD_RUID

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4167]
Один из подходов, сформировать список используемых в базе РУИДов и оставить в таблице `GD_RUID` только записи из этого списка. Используемые РУИДы мы можем найти:

1. РУИДы объектов в таблицах пространств имен.
2. РУИДы в строковых константах (`GD_CONST`).
3. РУИДы типов документов.
4. РУИДы в исходных текстах макросов (подробнее -- ниже).
5. РУИДы в текстах DFM.

РУИДы в макросах и текстах SQL запросов:

1. Ввиде строки **"XID_DBID"** (внимание! у нас уже есть код подобного поиска. Проверить чтобы он не был привязан к максимальной длине XID/DBID, так как при переходе на 64-битные идентификаторы она изменится).
2. Ввиде двух целочисленных параметров например при обращении к функции `getIDByRUID` или при вызове хранимой процедуры.
3. Ввиде параметров тэга `<RUID>` в текстах SQL запросов.

Могут быть еще ситуации JOIN-а на таблицу GD_RUID или SELECT из этой таблицы, но мы их не будем рассматривать.

РУИДы в текстах DFM:

1. Ввиде параметров тэга `<RUID>` в текстах SQL запросов.

**Comment by MIchaelShoihet** [comment]
Есть еще ситуации, когда идет синхронизация в рамках нескольких баз данных. Это ситуации работы фронт и бэк офисов. В этом случае в gd_ruid должны быть еще id из справочников, которые участвуют в синхронизации... Это хорошо бы обсудить с Юрием.

Прямо сейчас у нас есть БД на 30 Гб, где больше половины занимают РУИДы и их индексы. Надо понять, в этой базе мы можем сократить список РУИДов?

**Comment by ShlTanya** [comment]
Дайте мне, пжст, такую базу.

**Comment by hirurg-lybitel** [comment]
> Есть еще ситуации, когда идет синхронизация в рамках нескольких баз данных. Это ситуации работы фронт и бэк офисов. В этом случае в gd_ruid должны быть еще id из справочников, которые участвуют в синхронизации... Это хорошо бы обсудить с Юрием.
> 
> Прямо сейчас у нас есть БД на 30 Гб, где больше половины занимают РУИДы и их индексы. Надо понять, в этой базе мы можем сократить список РУИДов?

О, да! Понимать, в каком документе лежит запись с таким id и руидом было бы просто великолепно!

**Comment by MIchaelShoihet** [comment]
`О, да! Понимать, в каком документе лежит запись с таким id и руидом было бы просто великолепно!`

Вообще пока речь идет о том что мы хотим из GD_RUID удалить ненужные руиды. Сейчас они удаляются по описанному выше алгоритму, не учитывая, что может быть настроена синхронизация, и значит какие-то еще РУИДЫ являются нужными. Нужна база для Татьяны и описание как можно узнать, какие справочники и документы участвуют в синхронизации и соответственно какие руиды удалять не стоит...

**Comment by hirurg-lybitel** [comment]
куда базу кидать?

**Comment by gsbelarus** [comment]
на имэйл отправил ФТП

**Comment by hirurg-lybitel** [comment]
Закинул в папку RUID_Synchronization_Example с описанием

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@hirurg-lybitel @ShlTanya
