### ISSUE TITLE
Фильтры. Ошибка при работе с формулами

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4168]
1. Создаем новый фильтр.
2. Фильтр → Формула → Условие пользователя.

Программа отображает следующее окно с ошибкой:
![2020-10-28_121957](https://user-images.githubusercontent.com/11497453/97417138-60ddf300-1918-11eb-9b09-2af7a519a4b5.jpg)

В случае нажатия на кнопку **Нет** — фильтр сохраняется и далее работает корректно.
В случае нажатия на кнопку **Да** — программа отображает следующее окно:
![2020-10-28_122038](https://user-images.githubusercontent.com/11497453/97417371-a7cbe880-1918-11eb-8837-539f5158c3e4.jpg)

@ShlTanya , пожалуйста, изложи свой мнение.

**Comment by ShlTanya** [comment]
Распишите, пжст, ошибку более подробно. Какое условие задаете. В какой момент времени появляется ошибка. До или после окна с Условиями пользователя.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пока не могу найти пример с ошибкой.

> _В какой момент времени появляется ошибка. До или после окна с Условиями пользователя._

При сохранении фильтра.

**Comment by ShlTanya** [comment]
Данное окно появляется когда введено неверное имя поля. Ошибка вполне читаемая и править ничего не  надо.

**Comment by NikolayUkleyko** [comment]
> _Данное окно появляется когда введено неверное имя поля. Ошибка вполне читаемая и править ничего не надо._

@ShlTanya , хорошо.
Пожалуйста, приведи пример с неправильным и правильным именем поля.

**Comment by ShlTanya** [comment]
![image](https://user-images.githubusercontent.com/24572314/151173671-52ed4a7b-a479-4cb1-a07b-e863290106ed.png)Надо проверить условие на корректность.

**Comment by ShlTanya** [comment]
Дайте, пжст, свой вариант условия.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , посмотрю.
Необходимо поискать.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри следующее.

Сообщение об ошибке выводится при настройке фильтров для **форм остатков**.
При настройке фильтров для **документов** сообщения об ошибке нет.

Пример, 
**Исследователь → Материальный склад → Отчеты по складу → Остатки по материалам и МБП.**
Можно посмотреть форму остатков для любого складского документа.

В настройках фильтра указываем следующее:

1. Закладка → **Фильтр**.
2. Наименование поля **ФОРМУЛА**.
3. Условие фильтра → **ввести условия**.
4. В форме **Условие пользователя** указали
```javascript
C.GOODKEY IN (147130035,147130039)
```
При нажатии на кнопку **Поля>>** такого поля нет.
5. Сохраняем условие пользователя **OK**.
6. Сохраняем фильтр **OK**.

![image](https://user-images.githubusercontent.com/11497453/155739013-f7c8e005-83a7-484a-985f-555afb4a292f.png)
![image](https://user-images.githubusercontent.com/11497453/155739241-e2ed6929-138e-4e32-bbc5-e6094dcff891.png)

Программа отобразит сообщение об ошибке.
При этом фильтр работает корректно.
При его запуске сообщений нет.
В SQL-запросе, формируемом по форме поле **C.GOODKEY** есть.

-----

Если, по пункту **3** выбрать **создать запрос** и далее ввести полный запрос, то при сохранении фильтра окно с сообщением об ошибке не отображается.

**Comment by ShlTanya** [comment]
Данная ошибка возникает когда запрос содержит подзапрос(ы). В данном случае я могу только выдать предупреждение, что запрос содержит подзапросы. Проверить правильность введенного условия/фильтра невозможно.

**Comment by gsbelarus** [comment]
да. так и сделайте.

пт, 11 сак 2022, 08:51 карыстальнік ShlTanya ***@***.***>
напісаў:

**Comment by ShlTanya** [comment]
Выполнено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
