### ISSUE TITLE
Неправильно отображается список подключенных пользователей на ФБ 3

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4169]
Показывает два подключения, когда в таблице MON$ATTACHMENTS запросом можно увидеть, что три активных подключения. Третье не под администратором.

Надо заглянуть в окно со списком подключений и посмотреть каким запросом строится этот список. Возможно, дело в нем. Возможно между 2.5 и 3 произошли какие-то изменения в логике MON$ таблиц.

Пример есть у @yoannawx

**Comment by ShlTanya** [comment]
Уточните: если не виден пользователь в форме вызываемой через База данных/Подключенные пользователи, то есть ли подключение (для невидимого пользователя) в Сервис/Монитор подключений. Если есть, то какое значение стоит в графе Mon$State.

**Comment by yoannawx** [comment]
подключение (для невидимого пользователя) в Сервис/Монитор подключений есть.  Mon$State = 0

**Comment by ShlTanya** [comment]
Mon$State = 0 это состояние простоя (Idle). А в программе стоит ограничение на отображение активных пользователей Mon$State = 1. Точно ли этот пользователь активен в данный момент. Может у него нет никаких открытых транзакций. Если пользователь действительно находится в состоянии простоя, то надо решить отображать ли их.

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
@yoannawx @ShlTanya

**Comment by gsbelarus** [comment]
"Если пользователь действительно находится в состоянии простоя, то надо решить отображать ли их." -- надо отображать всех подключенных пользователей.

**Comment by gsbelarus** [comment]
Сделано.

@ShlTanya будьте внимательны. в паскале строки начинаются с 1.
