### ISSUE TITLE
Файлы. Корневой каталог. Ошибка при смене накопителя

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4175]
**Исследователь / Сервис / Файлы.**

Сменили накопитель.
Путь сохранился прежний и нельзя указать новый.
При двойном клике по корневому каталогу или при выборе _Сервис → Корневой каталог_:

![image](https://user-images.githubusercontent.com/11497453/113315435-f6414100-9315-11eb-8c3d-8676cc104e64.png)
![image](https://user-images.githubusercontent.com/11497453/113315462-fb05f500-9315-11eb-973a-8656be8f4486.png)

Программа отображает окно с сообщением об ошибке:

![image](https://user-images.githubusercontent.com/11497453/113315479-00fbd600-9316-11eb-9eaa-f6c97e76009b.png)

**Comment by NikolayUkleyko** [comment]
![image](https://user-images.githubusercontent.com/11497453/123107757-7e7d4100-d442-11eb-9444-cd6f2a68535d.png)
![image](https://user-images.githubusercontent.com/11497453/123107780-84732200-d442-11eb-9ca5-ce16c97701c7.png)

**Comment by ShlTanya** [comment]
Не могу смоделировать данную ситуацию.  Дайте более подробную информацию, что меняли.

**Comment by NikolayUkleyko** [comment]
БД хранилась на одном USB-накопителе.
В параметрах синхронизации указали путь для сохранения файлов (кнопка 1) и периодически выполняли синхронизацию (кнопка 2).

![image](https://user-images.githubusercontent.com/11497453/123621868-52800800-d814-11eb-8ada-ef118440ba7b.png)
**Рис. 1**
![image](https://user-images.githubusercontent.com/11497453/123621356-c8d03a80-d813-11eb-9e75-aea6d43a92f0.png)
**Рис. 2 (кнопка 1 — указание корневого каталога для сохранения (синхронизации) файлов)**
![image](https://user-images.githubusercontent.com/11497453/123621370-ccfc5800-d813-11eb-8636-c5fa64b6e0ad.png)
**Рис. 3 (кнопка 2 — сохранения (синхронизация) файлов)**

Позже БД перенесли на другой USB-накопитель.
При этом путь к БД уже другой.
При выполнении сохранения (синхронизации) файлов программа отображает окно с сообщением об ошибке **Invalid filename**.
При этом возможность указания в параметрах пути для сохранения (синхронизации) файлов не помогает и приводит к вышеприведенной ошибке.
Предположение, что программа где-то еще хранит предыдущий путь к БД для сохранения файлов.

**Comment by Polfath** [comment]
посмотрю

**Comment by Polfath** [comment]
@NikolayUkleyko Попробовал воспроизвести ситуацию:
1.  Выполнил синхронизацию в каталог c:\Gedemin\Sync\
2.  Перенес БД
3.  Запустил синхронизацию в тот же каталог
4.  "Выполнена успешно"

или последовательность действий не такая?

**Comment by gsbelarus** [comment]
николай имеет ввиду, что пути уже нет такого. он синхронизировал на флэшку, а потом достал флэшку из компьютера. и нет пути. просто посмотрите что там по выборе этой команды происходит. диалоговое окно открывается или что? тогда try except взять и при возникновении исключения просто брать другой каталог. например текущий.

**Comment by NikolayUkleyko** [comment]
Смоделировал ситуация на новом компьютере с новым путем к файлам — ошибка не повторяется, работает верно.
