### ISSUE TITLE
Восстановление БД на ФБ4

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4176]
Не восстанавливаются триггеры и нет некоторых UDF. Надо подумать, что не будет работать без этих тригеров. На вскидку, они инкрементируют генератор версии структуру БД и от этого зависит перечитывать структуру или брать ее из кэшированного файла. 

По идее триггеры на изменение метаданных остались, чтолько они теперь имеют другой синтаксис.

```
gbak:Skipped trigger GD_AI_RDB_FIELDS on system table RDB$FIELDS
gbak:Skipped trigger GD_AU_RDB_FIELDS on system table RDB$FIELDS
gbak:Skipped trigger GD_AI_RDB_RELATIONS on system table RDB$RELATIONS
gbak:Skipped trigger GD_AU_RDB_RELATIONS on system table RDB$RELATIONS
gbak:Skipped trigger GD_AI_RDB_RELATION_FIELDS on system table RDB$RELATION_FIELDS
gbak:Skipped trigger GD_AU_RDB_RELATION_FIELDS on system table RDB$RELATION_FIELDS
gbak:Skipped trigger GD_AI_RDB_TRIGGERS on system table RDB$TRIGGERS
gbak:Skipped trigger GD_AU_RDB_TRIGGERS on system table RDB$TRIGGERS
gbak:Skipped trigger GD_AI_RDB_PROCEDURES on system table RDB$PROCEDURES
gbak:Skipped trigger GD_AU_RDB_PROCEDURES on system table RDB$PROCEDURES
gbak:Skipped trigger GD_AI_RDB_PROCEDURE_PARAMETERS on system table RDB$PROCEDURE_PARAMETERS
gbak:Skipped trigger GD_AU_RDB_PROCEDURE_PARAMETERS on system table RDB$PROCEDURE_PARAMETERS
gbak:Skipped trigger GD_AI_RDB_INDICES on system table RDB$INDICES
gbak:Skipped trigger GD_AU_RDB_INDICES on system table RDB$INDICES
gbak:Skipped trigger GD_AI_RDB_INDEX_SEGMENTS on system table RDB$INDEX_SEGMENTS
gbak:Skipped trigger GD_AU_RDB_INDEX_SEGMENTS on system table RDB$INDEX_SEGMENTS
gbak: WARNING:function G_M_ROUNDNN is not defined
gbak: WARNING:    module name or entrypoint could not be found
gbak: WARNING:function G_S_POS is not defined
gbak: WARNING:    module name or entrypoint could not be found
```

**Comment by MIchaelShoihet** [comment]
Так эти триггеры уже под 3.0 не восстанавливаются

сб, 3 апр. 2021 г., 20:06 Andrej Kirejeŭ ***@***.***>:

**Comment by YRozmysl** [comment]
при нажатии на "Справка" - ошибка

![Безымянный](https://user-images.githubusercontent.com/11507129/113543523-3bec5b00-95ef-11eb-8754-7f09c8db95ef.jpg)

**Comment by YRozmysl** [comment]
при открытии формы многих документов, например расчета отпуска - ошибка.

![444](https://user-images.githubusercontent.com/11507129/113546522-d3a07800-95f4-11eb-8d10-58e9dccc43e1.jpg)

**Comment by gsbelarus** [comment]
надо будет флаг совместимости с пред версиями выставить в конф файле

пн, 5 кра 2021, 09:54 карыстальнік Yury Rozmysl ***@***.***>
напісаў:

**Comment by YRozmysl** [comment]
во многих процедурах  ошибка 

![proc](https://user-images.githubusercontent.com/11507129/113550298-8673d480-95fb-11eb-8e01-db60a98f4e6f.jpg)

**Comment by YRozmysl** [comment]
причем текст процедуры не тот, что там изначально был, какой-то сгенерированный фб 4, это, как я понял

**Comment by YRozmysl** [comment]
режим совместимости решил  ошибку в Справке, остальные ошибки остались

**Comment by YRozmysl** [comment]
совместимость также решила вопрос с открытием форм документов.

**Comment by YRozmysl** [comment]
Если тема не актуальна, то можно закрывать.

**Comment by gsbelarus** [comment]
Дойдем до ФБ4 (хотя думаю уже на пятый сразу будем ориентироваться) тогда и займемся.
