### ISSUE TITLE
Константы. Добавление новой записи в режиме редактирования

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4177]
**Исследователь → Сервис → Константы.**

При редактировании записи и добавлении новой (кнопка **Новый**) становятся неактивными реквизиты с типом **CheckBox**.

**Comment by ShlTanya** [comment]
Дайте, пжст, картинку происходящего

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста.

![image](https://user-images.githubusercontent.com/11497453/123611357-337c7880-d80a-11eb-860f-e33c90235a43.png)
Исходная константа.

![image](https://user-images.githubusercontent.com/11497453/123611380-38d9c300-d80a-11eb-86a7-9a365185da98.png)
Новая константа, созданная из исходной при помощи кнопки **Новый**.

**Comment by ShlTanya** [comment]
Исправила

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо !
