### ISSUE TITLE
Очередность выполнения скрипта инициализации в АХО.

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4184]
При формировании АХО у которой установлен параметров не удалять результаты предыдущих периодов, для корректной обработки предлагается скрип инициализации делать раньше. Так как скрипт удаления проводок прописан выше в АХО.

**Comment by ShlTanya** [comment]
Уточните. Скрипт инициализации делать раньше чего.. удаления проводок? Так если стоит параметр Не удалять, то и скрипта удаления проводок нет.

**Comment by YRozmysl** [comment]
Вот примет АХО. Если использовать стандартный конструктор формирования АХО, то она имеет след вид 
![aho_miss](https://user-images.githubusercontent.com/11507129/122525792-44ff9c80-d022-11eb-8492-88cd679181ed.jpg)
и при таком варианта, если не стоит галка, то проводки каждый раз создаются новые при повторном выполнении АХО. 

А если сделать вот такой вот искусственный прием,
![aho_corr](https://user-images.githubusercontent.com/11507129/122525991-7bd5b280-d022-11eb-8e4c-b028e88eba3e.jpg)
то все отрабатывает корректно

**Comment by NikolayUkleyko** [comment]
Когда не проставлена галка по реквизиту **Не удалять результаты предыдущих расчетов**, то проводки удаляются и формируются снова.
Это верно.

На сколько я знаю, @MIchaelShoihet несколько лет назад поправлял алгоритмы работы АХО.
Наглядно было на БД Витебск БПФ.

----

@ShlTanya , попутно посмотри назначение реквизита **Возвращает результат** — только меняет _Sub → Function_ ?

**Comment by YRozmysl** [comment]
В том -то все и дело, галка не проставлена, а проводки создаются и создаются, не удаляются.

**Comment by NikolayUkleyko** [comment]
В данной ситуации наверное лучше отправить Татьяне БД или у нее удаленно смоделировать рассматриваемую ситуацию.

**Comment by YRozmysl** [comment]
@ShlTanya  как будет удобно так и  сделаем, могу удаленно у меня на примере, а могу и базу выслать.

**Comment by MIchaelShoihet** [comment]
Проблема в следующем: В данной автоматической операции убраны параметры Дата начала и Дата окончания вместо них добавлен параметр Итоговый расчет и дата начала и окончания получаются на основании этого итогового расчета уже в самой операции. Это было добавлено в скрипт инициализации операции, но оказалось, что данный скрипт выполняется уже после удаления проводок, т.е. когда они удаляются, дата начала и окончания не определена, поэтому ничего не удаляется. Вот и хочется, что скрипт инициализации шел перед удалением проводок, для большей гибкости

**Comment by ShlTanya** [comment]
![Снимок](https://user-images.githubusercontent.com/24572314/122566817-a63e6480-d050-11eb-9c4b-23f7e6311d10.JPG)
Вот так сделала

**Comment by NikolayUkleyko** [comment]
@YRozmysl , пожалуйста, подскажи, не смотрел ?

**Comment by YRozmysl** [comment]
Теперь все ок, закрываю
