### ISSUE TITLE
Не работает модифай базы

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4185]
1. Ставим комплексную автоматизацию с сайта. При установке выбираем установить демо базу данных.
2. Новейшим экзешником (скомпилированным без символа ID64) подключаемся к ней.
3. Он предложит обновить структуру.
4. Соглашаемся.
5. В процессе обновления будет ошибка.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, подскажите, актуальна ли данная тема ?
