### ISSUE TITLE
Типовые документы. Пользовательский документ и поле CHECKREMAINS

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4186]
Создали пользовательский документ и сразу добавили таблицу шапки документа и таблицу позиции документа.
В результате в таблице позиции документа существует поле **CHECKREMAINS**.
Пожалуйста, подскажите, каково его назначение для пользовательского документа ?

**Comment by MIchaelShoihet** [comment]
Пока это поле не используется (имеется в виду складской документ). а в пользовательском документе оно и не нужно, я посмотрю как оно туда попало.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , благодарю за информацию.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри, если, можно.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

Пожалуйста, подскажи, что было неправильно ?
