### ISSUE TITLE
Перестал работать режим показать сетевые имена компьютеров

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4187]
![image](https://user-images.githubusercontent.com/5175764/122178242-14d3c480-ce8f-11eb-87d5-b10e2edf300e.png)

Очевидно, проблема из-за того, что теперь в адресе файреберд передает еще и порт подключения. Перед определением имени компьютера порт надо убрать из строки.

**Comment by ShlTanya** [comment]
Исправлено
