### ISSUE TITLE
Добавить колонку "Старейшая транзакция"

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4188]
![image](https://user-images.githubusercontent.com/5175764/122178950-ba873380-ce8f-11eb-9b4f-2e9e40e41259.png)

После колонки **Время подключения** добавить колонку **Старейшая тр.** где выводить возраст старейшей активной транзакции на изменение данных. Информация извлекается из таблицы `MON$TRANSACTIONS` вкупе с `MON$ATTACHMENTS`. Форматировать строку как `HH:MM:SS`. Часов может быть и больше чем двузначное число, тогда выводить столько цифр, сколько надо. Если открытой транзакции на запись нет для данного подключения, то выводить пустую строку. Ширину окна можно увеличить, чтобы поместить данную колонку.

**Comment by ShlTanya** [comment]
Выполнено

**Comment by NikolayUkleyko** [comment]
Доработка выполнена.
Если, вопросов нет, то данную тему можно закрыть.
