### ISSUE TITLE
Параметры. Выбор из множества. Ошибка

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4189]
_Отчет → Параметры → Выбор из множества → Условие и сортировка → Условие отбора → accounttype in ('A', 'S')._

Где, таблица и поля:
• таблица → AC_ACCOUNT;
• поле для отображения → ALIAS;
• поле ИД → ID.

Программа отображает окно с сообщением об ошибке:
![image](https://user-images.githubusercontent.com/11497453/122245152-26888c80-cece-11eb-8e80-90cbf4ca5274.png)

-----
На предыдущем **gedemin.exe** работает корректно.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо !
