### ISSUE TITLE
Конструктор функций. Наименование функции DebibValue

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4190]
_Конструктор функций → Редактор выражений → Добавить функцию → DebibValue._

Пожалуйста, переименуйте функцию в **DebitValue**.

**Comment by ShlTanya** [comment]
А что делать с кодом, в котором уже есть DebibValue? Может добавить DebitValue  с таким же функционалом.

**Comment by gsbelarus** [comment]
да, наверное так будет лучше всего. чтобы не полезли ошибки.

пт, 18 чэр 2021, 08:29 карыстальнік ShlTanya ***@***.***>
напісаў:

**Comment by NikolayUkleyko** [comment]
Для наглядности: существует аналогичная функция, но для кредита — **CreditValue**.

**Comment by NikolayUkleyko** [comment]
Функция **DebibValue** почти не используется.
Если, возникнет ошибка, то можно поправить в конструкторе функций.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, поправьте (**_DebibValue → DebitValue_**) и тему можно закрывать.

**Comment by NikolayUkleyko** [comment]
https://github.com/GoldenSoftwareLtd/gedemin/issues/4190#issuecomment-1290229792

**Comment by gsbelarus** [comment]
1. существующую функцию не трогаем
2. добавляем новую функцию DebitValue

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
