### ISSUE TITLE
ПИ. При сохранении в ПИ типового документа не все его объекты добавляются

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4191]
При сохранении типового документа в ПИ не все объекты хранилища сохраняются.
Можно посмотреть грид проводок.

**Comment by gsbelarus** [comment]
Надо конкретный четкий пример. Вот документ. Вот сохраняется. Вот именно это не сохранилось.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, связанная тематика https://github.com/GoldenSoftwareLtd/gedemin/issues/3946.
Разработали новый документ (типовой), кнопку проводок, настроили грид проводок, типовые проводки и т.д.
После добавления в ПИ типового документа со связанными объектами следующий результат:

> _Добавляю в ПИ табличку со всеми связанными объектами. Все события компонентов на форме просмотра добавляются, а события самой формы (типа OnLoadSettingsAfterCreate, OnShow, etc) - не добавляются._

**Comment by NikolayUkleyko** [comment]
Перенесено в https://github.com/GoldenSoftwareLtd/gedemin/issues/3946.

**Comment by NikolayUkleyko** [comment]
Смоделирована ситуация на базе документа с **гридом отображения бухгалтерских проводок**.
При сохранении в ПИ типового документа не добавляются следующие объекты:

№ п/п  | OBJECTCLASS  | OBJECTNAME 
------------ | ------------- | -------------
1                 | TgdcEvent | ONCREATE
2                 | TgdcFunction  | gdc_frmUserComplexDocument148990521_1153275497OnCreate.
3                 |  TgdcStorageFolder  | 
3.1                 |  TgdcStorageFolder  | DFM
3.2                 |  | GLOBAL
3.3                 |  | Tgdc_dlgUserComplexDocument
3.4                 |  | Tgdc_frmUserComplexDocument
3.5                 |  | USER - Administrator
3.6                 |  | usrg_ibgrEntry(TgsIBGrid)
3.7                 |  | usrg_ibgrEntry(TgsIBGrid)
4                 | TgdcStorageValue | data
5                 | TgdcComponentFilter | 1V\GEDEMIN\TGDCUSERDOCUMENT\FLT_148990521_1153275497GDCUSERD
6                 | TgdcSavedFilter  | Отобразить записи за период

**Comment by YRozmysl** [comment]
так, может,  они уже входят в какие-то другие ПИ?

**Comment by NikolayUkleyko** [comment]
Нет.
Они не входят в другие ПИ.

**Comment by Polfath** [comment]
Постарался исправить. Нужно попробовать.

**Comment by NikolayUkleyko** [comment]
Проверено.
Методы, функции документа теперь подтягиваются.
Хранилище грида проводок и фильтры по документу еще нет.

**Comment by Polfath** [comment]
Сделал для проводоки и фильтры

**Comment by NikolayUkleyko** [comment]
Проверено.
Фильтры автоматически не добавляются в ПИ.

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста, поправь, чтобы в ПИ добавлялись фильтры.

**Comment by Polfath** [comment]
Гляну

**Comment by NikolayUkleyko** [comment]
Проверено.
Фильтры и связанные объекты добавляются.
В целом функционал работает корректно.
@Polfath , большое спасибо !

**Comment by Polfath** [comment]
сделано

**Comment by TechAnton** [comment]
@NikolayUkleyko  Хорошего дня!
А в чем задача?

**Comment by TechAnton** [comment]
Если меня не обманывают глаза, то задача сделана, проверена и закрыта. Сомневаюсь, что у меня будет желание делать что-то дополнительное на свой вкус.
