### ISSUE TITLE
Бухгалтерия. Карта счета. Возможность перехода в журнал документов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4192]
**Исследователь → Бухгалтерия → Карта счета, Журнал хоз. операций.**

Пожалуйста, предусмотрите возможность перехода в журнал документов на соответствующую запись.
Добавить новую кнопку к существующим.

![image](https://user-images.githubusercontent.com/11497453/122574536-67aca800-d058-11eb-93ae-bf99961adb12.png)
![image](https://user-images.githubusercontent.com/11497453/122574559-6da28900-d058-11eb-9bdd-5cbcff33583d.png)

**Comment by NikolayUkleyko** [comment]
@ShlTanya .

**Comment by ShlTanya** [comment]
Выполнены доработки

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо !

Пожалуйста, поправь следующее:

1. Переименовать всплывающую подсказку: _Журнал документов → Перейти в журнал документов_.
2. В контекстное меню добавить команду **Перейти в журнал документов**.
3. Для вышеприведенных пунктов предусмотреть горячие клавиши **Ctrl + J**.
4. При фильтрации данных при помощи **бинокля** и/или **автофильтра** предусмотреть сообщение о фильтрации данных.

![image](https://user-images.githubusercontent.com/11497453/157431626-18244c0a-5cae-49d3-9379-de69f29b38e2.png)

**Comment by ShlTanya** [comment]
Доработано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Все пункты реализованы, кроме пункта 4.
Я так понимаю, что это затрагивает другие объекты платформы и усложняет реализацию.
Поэтому, доработку можно считать сделанной.
@ShlTanya ?

**Comment by NikolayUkleyko** [comment]
По пункту 4 предусмотреть такой функционал нельзя.
Хорошо.
В целом доработка работает корректно.
Закрываем тему.
@ShlTanya , благодарю !
