### ISSUE TITLE
Склад. Карточка ТМЦ. Не отображается движение по документам

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4193]
На панели инструментов любого складского документа нажимаем на кнопку **Карточка ТМЦ** и в форме не отображается движение по документам.

-----
На предыдущем **gedemin.exe** работает корректно.

**Comment by NikolayUkleyko** [comment]
Ошибки при формировании карточки нет, но она пустая.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста.

**Comment by NikolayUkleyko** [comment]
@yoannawx , пожалуйста.

**Comment by ShlTanya** [comment]
Исправила

**Comment by gsbelarus** [comment]
@NikolayUkleyko экзешник на сайте. надо проверять и закрывать.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , благодарю.
По ходу посмотрим.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
