### ISSUE TITLE
Склад. Карточка ТМЦ. Возможность перехода в журнал документов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4194]
**Складские документы → Карточка ТМЦ.**

Пожалуйста, предусмотрите возможность перехода в журнал документов на соответствующую запись.
Добавить новую кнопку к существующим.

![image](https://user-images.githubusercontent.com/11497453/123119081-e2583780-d44b-11eb-8735-6f5830e8756f.png)
![image](https://user-images.githubusercontent.com/11497453/123119103-e71ceb80-d44b-11eb-9425-afacb3967ea2.png)

**Comment by ShlTanya** [comment]
Выполнено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо !

Можно ли предусмотреть такой функционал и для формы карточки (карточка по ТМЦ, карточка по холдингу...), открывающейся при переходе из любого складского документа и / или формы остатков ?

**Comment by ShlTanya** [comment]
Доработано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо !

Пожалуйста, посмотри следующее:

1. В контекстное меню добавить команду **Перейти в журнал документов**.
2. При переходе на журнал документов на некоторых документах (например, _**01. Накладная на получение материалов, ОС, МБП**_) небольшое зависание.
То есть, форма журнала документов не модальная, а курсор по документам не переходит.

**Comment by ShlTanya** [comment]
1. Выполнено.
2. Такое поведение, когда из самой формы вызывается карта счетов.. а из нее уже Журнал документов для такого же типа.

**Comment by NikolayUkleyko** [comment]
Проверено.
1 — в контекстном меню необходимо поправить наименование (как сделано в карте счета) _Журнал документов → Перейти в журнал документов_.
2 — необходимо уточнение.
Смоделировал переход из карты счета в журнал документов **_01. Накладная на получение материалов, ОС, МБП_** — зависаний нет.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:

**Comment by NikolayUkleyko** [comment]
Проверено.
1 — не поправлено.
2 — зависание есть.

**Comment by NikolayUkleyko** [comment]
@DonPhantom000 , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.

_”1 — в контекстном меню необходимо поправить наименование (как сделано в карте счета) Журнал документов → Перейти в журнал документов.”_
Сделано.

_”2 — необходимо уточнение.
Смоделировал переход из карты счета в журнал документов 01. Накладная на получение материалов, ОС, МБП — зависаний нет.”_
Зависание есть, как по приходной накладной, так и по другим документам.

**Comment by NikolayUkleyko** [comment]
2-й вопрос пока не будем смотреть.
Доработки выполнены и работают корректно.
@Polfath , спасибо !
