### ISSUE TITLE
ПИ. Синхронизация. Сравнение. Ошибка

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4196]
Синхронизировали ПИ.
При нажатии на кнопку **Сравнить** программа отображает окно с сообщением об ошибке:

![image](https://user-images.githubusercontent.com/11497453/123928552-afa3c700-d996-11eb-8798-88d73b0ab4f2.png)
Рис. 1.

![image](https://user-images.githubusercontent.com/11497453/123928577-b5011180-d996-11eb-8a1c-6d8971db17cc.png)
Рис. 2.

**Comment by YRozmysl** [comment]
причем замечено, что если  сделать двойной клик по ПИ, то сравнение работает (открывается окно сравнения)

**Comment by NikolayUkleyko** [comment]
иначе, в окне с ошибкой нажимаем на кнопку **OK** и переходим к окну сравнения

**Comment by gsbelarus** [comment]
Какая-то ошибочная проверка в коде. Так как это не класс бизнес объекта и его и не должно быть в списке gdcClassList.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@gsbelarus , спасибо !
