### ISSUE TITLE
Бухгалтерия. Заполнение аналитики "Документ"

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4197]
В типовой проводке в SQL-запросе определяем наличие аналитики **Документ** по счету.
В условии на аналитику **Документ** прописали, что она заполняется соответствующим значением, иначе Null.
При формировании _Журнала-ордера_, _Журнале хоз. операций_ видно, что аналитика **Документ** заполняется и по тем счетам, по которым она не выбрана.

Пожалуйста, подскажите, в чем смысл заполнения аналитики, в которой нет необходимости и она не участвует в учете ?
С точки зрения хранения ненужных данных и соответственно, объема базы данных и т.д.

**Comment by MIchaelShoihet** [comment]
Аналитика документ заполняется автоматически по тем счетам по которым стоит
она настроена и в этом и есть смысл, что она не должна быть пустой, если
она не нужна надо снять галку

чт, 1 июл. 2021 г., 13:57 NikolayUkleyko ***@***.***>:

**Comment by MIchaelShoihet** [comment]
Если она заполняется по всем счетам, значит кто-то свой триггер написал

чт, 1 июл. 2021 г., 13:57 NikolayUkleyko ***@***.***>:

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , хорошо.

В случае, если:
• дополнительного триггера нет;
• в типовой проводке аналитика **Документ** не заполняется вовсе;
• в плане счетов не установлена галка по аналитике **Документ**.

В параметрах Журнал-ордер не указывая счет (т.е., по всем счетам) по аналитике _Счета и субсчета_, _Документ_ (можно еще указать конкретный типовой документ).
В результате, по конкретному счету видно, что аналитика **Документ** заполнена.

@MIchaelShoihet , пожалуйста, подскажите, это правильно ?

**Comment by MIchaelShoihet** [comment]
Exe сам эту аналитику не заполняет. Может вы путаете аналитику с документом который создал проводку поле documentkey,  а аналитика usr$gs_document

**Comment by MIchaelShoihet** [comment]
Типовой документ берется не по аналитике, а по документу который его создал

**Comment by MIchaelShoihet** [comment]
В любом случая аналитка документ заполняется только в ТХО или на триггере в AC_ENTRY. ну либо кто-то запросом заполнил

**Comment by NikolayUkleyko** [comment]
> Exe сам эту аналитику не заполняет. Может вы путаете аналитику с документом который создал проводку поле documentkey, а аналитика usr$gs_document

Про аналитику **USR$GS_DOCUMENT**.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , по триггерам посмотрели еще.
Есть информация.
Получается, что для всех типов документов заполнение аналитики **Документ** определяется не в типовой проводке, а наличием соответствующей галки в плане счетов.
Это хорошо для ручных проводок в Журнале хоз. операций.
Для других документов такое условие не совсем нужно.
@MIchaelShoihet , пожалуйста, подскажите, можно ли поправить нижеприведенные триггеры, чтобы они работали только для типового документа Журнал хоз. операций ?

√ USR$AC_BU_ENTRY28018

```javascript
AS
  DECLARE VARIABLE USR$GS_DOCUMENT DBOOLEAN;
BEGIN
/*Тело триггера*/
  SELECT USR$GS_DOCUMENT FROM AC_ACCOUNT WHERE ID = NEW.ACCOUNTKEY
  INTO :USR$GS_DOCUMENT;
  IF ((USR$GS_DOCUMENT = 1) AND (NEW.USR$GS_DOCUMENT IS NULL)) THEN
  BEGIN
    SELECT DOCUMENTKEY FROM AC_RECORD
    WHERE ID = NEW.RECORDKEY
    INTO NEW.USR$GS_DOCUMENT;
  END
END
```

√ USR$AC_BI_ENTRY28018

```javascript
AS
  DECLARE VARIABLE USR$GS_DOCUMENT DBOOLEAN;
BEGIN
/*Тело триггера*/
  SELECT USR$GS_DOCUMENT FROM AC_ACCOUNT WHERE ID = NEW.ACCOUNTKEY
  INTO :USR$GS_DOCUMENT;
  IF ((:USR$GS_DOCUMENT = 1) AND (NEW.USR$GS_DOCUMENT IS NULL)) THEN
  BEGIN
    SELECT DOCUMENTKEY FROM AC_RECORD
    WHERE ID = NEW.RECORDKEY
    INTO NEW.USR$GS_DOCUMENT;
  END
END
```

Такие триггеры входят в ПИ **Общие данные бухгалтерии**.

**Comment by MIchaelShoihet** [comment]
Николай вы же сами знаете, что не заполненная аналитика это плохо. В ТО вы
можете заполнить не стандартно эту аналитику и это так и останется, но если
кто-то забыл прописать программа сама заполнит. В общем случае это
правильно, если в частном случае у вас другая ситуация правьте триггер

чт, 1 июл. 2021 г., 17:22 NikolayUkleyko ***@***.***>:

**Comment by NikolayUkleyko** [comment]
Благодарю за информацию, @MIchaelShoihet .
