### ISSUE TITLE
ПИ. Доработки по загрузке и сохранению файлов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4199]
Пожалуйста, предусмотрите следующие возможности при работе с пространствами имен:

1. Отображение пути расположения файла:
а. В окне ПИ для загрузки не отображать путь к файлу и отображать только имя файла.
б. Отображаемые файлы сортировать по возрастанию.

![image](https://user-images.githubusercontent.com/11497453/124471260-53c9ab80-dda5-11eb-94ec-c44bb2c83b1e.png)
![image](https://user-images.githubusercontent.com/11497453/124471309-647a2180-dda5-11eb-81c6-6322723eb421.png)

Чтобы не отвлекаться на путь к файлу.
Наглядное отображение только имени файла.

-----

2. При точечном выборе файлов для сохранения убрать автоматическое проставление кнопки ">>".
Это ни к чему при точечном сохранении набора файлов.

![image](https://user-images.githubusercontent.com/11497453/124471484-93909300-dda5-11eb-822a-c15c7df3a951.png)

Очередность действий:
1 – выбрали файл для сохранения.
2 – нажали на кнопку **Пометить для сохранения**.
3 – автоматически была выбрана кнопка **В БД новее, чем на диске**, которую, затем снимаем.

Для устранения лишних повторяющихся нажатий клавиш.

**Comment by NikolayUkleyko** [comment]
С функционалом ПИ работаем постоянно.
Почему бы не посмотреть данную и другие доработки по теме ПИ ?

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри.

**Comment by ShlTanya** [comment]
Точно ли надо убрать отображение путей файлов? Обсудите данное предложение. Может кому-то так удобно.

**Comment by ShlTanya** [comment]
Окно так и называется: Список файлов для загрузки.. Считаю, что в данном случае, неправильно убрать отображение пути файла.

**Comment by NikolayUkleyko** [comment]
Путь к файлам указываем в основной форме, выше.
Какой смысл его повторять ?
Таня, можно сделать как опция: по умолчанию без отображения путей к файлам,
иначе, с отображением.

ср, 19 янв. 2022 г., 17:16 ShlTanya ***@***.***>:

**Comment by NikolayUkleyko** [comment]
> _Точно ли надо убрать отображение путей файлов? Обсудите данное предложение. Может кому-то так удобно._

@ShlTanya , да, точно или опционально.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , по данной теме вносим доработки или закрываем ее.

**Comment by ShlTanya** [comment]
Закрываем. Убирать отображение файлов в данном случае неправильно.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , это понятно.
Пожалуйста, что, ты, думаешь, про следующее:

> _б. Отображаемые файлы сортировать по возрастанию._

> _3 — автоматически была выбрана кнопка В БД новее, чем на диске, которую, затем снимаем._

**Comment by NikolayUkleyko** [comment]
Уточним:

> _а. В окне ПИ для загрузки не отображать путь к файлу и отображать только имя файла._

Путь указывается в основной форме синхронизации ПИ.
Сейчас для каждого файла в целом повторяется путь к папке с ПИ.
Необходимо предусмотреть наглядное отображение только выбранных ПИ.

> _б. Отображаемые файлы сортировать по возрастанию._

Хорошо бы отображать перечень выбранных ПИ отсортированными по возрастанию.
Может быть здесь есть идея отображения ПИ в порядке их выбора.

> _При точечном выборе файлов для сохранения убрать автоматическое проставление кнопки **">>" (в БД новее, чем на диске)**._

При работе с набором ПИ это очень актуально.

**Comment by NikolayUkleyko** [comment]
Дополнительно предусмотрите при открытии формы синхронизации ПИ по умолчанию проставленную галку по реквизиту **Скрыть каталоги**.

**Comment by NikolayUkleyko** [comment]
@DonPhantom000 , пожалуйста, посмотри.

**Comment by gsbelarus** [comment]
не трогать сортировку! файлы должны быть отсортированы в порядке зависимости и именно в таком порядке они будут грузиться. важно чтобы разработчик видел этот порядок.

**Comment by NikolayUkleyko** [comment]
По сортировке хорошо, понятно.
По данной теме есть еще ряд других пожеланий.

**Comment by DonPhantom000** [comment]
Полные пути из списка файлов убраны. 
Флажок "Скрыть каталоги" выставлен по умолчанию. 
Отменено автоматическое проставление кнопки >>
Заблокированы пункты меню с выпадающими списками при отсутствии в них доступных команд
![image](https://user-images.githubusercontent.com/111727555/187385534-cbed6bcd-2e81-485b-8f39-92c4e0ffe112.png)

**Comment by NikolayUkleyko** [comment]
@DonPhantom000 , замечательно !
Посмотрим в работе.

**Comment by gsbelarus** [comment]
пожалуйста. каждое изменение по ПИ приведет к тому, что что-то рухнет. не смешивайте все в кучу. если и трогать ПИ то только ПО ОДНОМУ мелкому шагу за раз. Иначе будет пустая работа, которую потом выкинуть в мусорку. Многие списки файлов используются и на экране и внутренне. Нельзя менять в них порядок или убирать пути.

**Comment by gsbelarus** [comment]
Многие замечания тут субъективны. Я например нормально отношусь к пути в имени файла. Мне не надо убирать.

**Comment by NikolayUkleyko** [comment]
> _Многие списки файлов используются и на экране и внутренне. Нельзя менять в них порядок или убирать пути._

Хорошо.
Оставляем.

Из перечня пожеланий остается:

> _При точечном выборе файлов для сохранения убрать автоматическое проставление кнопки ">>"._

@gsbelarus , пожалуйста, посмотрите.
