### ISSUE TITLE
Прочие. При закрытии программы сообщение TheMethodInherited

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4200]
Иногда при закрытии программы на экране отображается окно со следующим сообщением:

![2021-07-01_175521_При закрытии программы](https://user-images.githubusercontent.com/11497453/124472707-1c5bfe80-dda7-11eb-8f33-8d8622ba128f.jpg)

-----
На предыдущем **gedemin.exe** работает корректно.

**Comment by NikolayUkleyko** [comment]
![image](https://user-images.githubusercontent.com/11497453/125805905-61b531dd-3723-46e9-9371-328a2ca7718a.png)

**Comment by gsbelarus** [comment]
Это только в специальном DEBUG экзешнике появляется. Доделал более информативное сообщение.
