### ISSUE TITLE
GDCC vs log

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4201]
Обрезается текст запроса на gedemin64
![GDCC](https://user-images.githubusercontent.com/11507129/124490094-5f739d00-ddba-11eb-91c8-434abcfdc95c.png)

**Comment by gsbelarus** [comment]
увеличил до 160 символов. помещать в лог весь запрос целиком мы не можем, т.к. может не хватить памяти. весь текст запроса можно посмотреть на вкладке профайлер.
