### ISSUE TITLE
Namespace. Сравнение

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4202]
На gedemin64 при сравнение NS ошибка 
![NS_1](https://user-images.githubusercontent.com/11507129/124718548-e043ad80-df0e-11eb-9d48-ea09f080c437.jpg)
![NS_2](https://user-images.githubusercontent.com/11507129/124718568-e5086180-df0e-11eb-9715-3247f0109903.jpg)

**Comment by NikolayUkleyko** [comment]
Юра, про это еще есть одна заметка:
https://github.com/GoldenSoftwareLtd/gedemin/issues/4196

**Comment by YRozmysl** [comment]
точно, не заметил.
