### ISSUE TITLE
Отчеты, макросы. Не отображаются папки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4203]
Было так:
![image](https://user-images.githubusercontent.com/11497453/124766485-a343df00-df3f-11eb-8eae-c9824ec15773.png)
Рис. 1.

Сейчас так:
![image](https://user-images.githubusercontent.com/11497453/124766518-ad65dd80-df3f-11eb-8e08-a85bcc012367.png)
Рис. 2.

-----
На предыдущем **gedemin.exe** работает корректно.

**Comment by ShlTanya** [comment]
Уточните, пжст, откуда вызывается это контекстное меню.

**Comment by gsbelarus** [comment]
я так понимаю, это меню со списком отчетов, которое вызывается с любой формы просмотра по нажатию на принтер на панели инструментов. уже как-то раньше было, что вывод древовидных папок слетал и все выводилось просто списком.

**Comment by NikolayUkleyko** [comment]
_> ... это меню со списком отчетов, которое вызывается с любой формы просмотра по нажатию на принтер на панели инструментов ..._

Да, так.
Такое меню доступно и при нажатии на кнопку **Макросы и события** на панели инструментов любого документа, объекта и т.д.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Изменений нет.
@ShlTanya , пожалуйста, глянь.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
