### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Сторнировать проводку. Не заполняется поле "Дата создания"

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4205]
**Исследователь → Бухгалтерия → Журнал хоз. операций → Сторнировать проводку.**

При выполнении данной команды не заполняется поле **Дата создания**.
Необходимо его заполнять.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
