### ISSUE TITLE
Бухгалтерия. Кнопка "Перейти на проводку" и позиционирование курсора в Журнале хоз. операций

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4208]
При нажатии на кнопку **Перейти на проводку**, пожалуйста, предусмотрите по умолчанию позиционирование курсора непосредственно на проводке (записи в Журнале хоз. операций) вместо позиционирования на типовой хоз. операции.

**Comment by gsbelarus** [comment]
@MIchaelShoihet

**Comment by MIchaelShoihet** [comment]
Оно сейчас так и работает или я чего-то не понимаю?

**Comment by NikolayUkleyko** [comment]
Пожалуйста, @MIchaelShoihet:
![image](https://user-images.githubusercontent.com/11497453/150312740-5530a960-0103-4f4e-b089-6d835c09a399.png)

**Comment by ShlTanya** [comment]
Исправлено. Сейчас при вызове Карты счетов из Журнал-ордера, Главной книги и Оборотной ведомости сразу активна основная таблица. При вызове Журнала хоз. операций из Карты счетов активна проводка.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
