### ISSUE TITLE
Гомельобои. Перевод с ФБ 2.5 на ФБ 4.0

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4210]
Местный АСУ сам изъявил желание протестировать базу под ФБ 4.0  При восстановлении базы вылезли вот такие вот ошибки и предупреждения. Возможно, будет полезно

Закончен процесс восстановления базы данных: 17:23:59, 01 Сентябрь 2021
Ошибка при присвоении нового идентификатора базы данных
gbak: WARNING:    module name or entrypoint could not be found 
gbak: WARNING:function ABS is not defined 
gbak: WARNING:    module name or entrypoint could not be found 
gbak: WARNING:function ABS is not defined 
gbak:Skipped trigger GD_AD_RDB_RELATION_FIELDS on system table RDB$RELATION_FIELDS 
gbak:Skipped trigger GD_AU_RDB_RELATION_FIELDS on system table RDB$RELATION_FIELDS 
gbak:Skipped trigger GD_AI_RDB_RELATION_FIELDS on system table RDB$RELATION_FIELDS 
gbak:Skipped trigger GD_AD_RDB_INDEX_SEGMENTS on system table RDB$INDEX_SEGMENTS 
gbak:Skipped trigger GD_AU_RDB_INDEX_SEGMENTS on system table RDB$INDEX_SEGMENTS 
gbak:Skipped trigger GD_AI_RDB_INDEX_SEGMENTS on system table RDB$INDEX_SEGMENTS 
gbak:Skipped trigger GD_AD_RDB_INDICES on system table RDB$INDICES 
gbak:Skipped trigger GD_AU_RDB_INDICES on system table RDB$INDICES 
gbak:Skipped trigger GD_AI_RDB_INDICES on system table RDB$INDICES 
gbak:Skipped trigger GD_AD_RDB_PROCEDURE_PARAMETERS on system table RDB$PROCEDURE_PARAMETERS 
gbak:Skipped trigger GD_AU_RDB_PROCEDURE_PARAMETERS on system table RDB$PROCEDURE_PARAMETERS 
gbak:Skipped trigger GD_AI_RDB_PROCEDURE_PARAMETERS on system table RDB$PROCEDURE_PARAMETERS 
gbak:Skipped trigger GD_AD_RDB_PROCEDURES on system table RDB$PROCEDURES 
gbak:Skipped trigger GD_AU_RDB_PROCEDURES on system table RDB$PROCEDURES 
gbak:Skipped trigger GD_AI_RDB_PROCEDURES on system table RDB$PROCEDURES 
gbak:Skipped trigger GD_AD_RDB_TRIGGERS on system table RDB$TRIGGERS 
gbak:Skipped trigger GD_AU_RDB_TRIGGERS on system table RDB$TRIGGERS 
gbak:Skipped trigger GD_AI_RDB_TRIGGERS on system table RDB$TRIGGERS 
gbak:Skipped trigger GD_AD_RDB_RELATIONS on system table RDB$RELATIONS 
gbak:Skipped trigger GD_AU_RDB_RELATIONS on system table RDB$RELATIONS 
gbak:Skipped trigger GD_AI_RDB_RELATIONS on system table RDB$RELATIONS 
gbak:Skipped trigger GD_AD_RDB_FIELDS on system table RDB$FIELDS 
gbak:Skipped trigger GD_AU_RDB_FIELDS on system table RDB$FIELDS 
gbak:Skipped trigger GD_AI_RDB_FIELDS on system table RDB$FIELDS 
Начат процесс восстановления базы данных: 16:30:56, 01 Сентябрь 2021

**Comment by gsbelarus** [comment]
я бы делал в последовательности:

1) бэкап ФБ 2.5
2) рестор ФБ 3
3) бэкап ФБ 3
4) рестор ФБ 4

не перепрыгивал бы через версию

**Comment by MIchaelShoihet** [comment]
Триггера отвалятся еще на 3 ФБ

**Comment by MIchaelShoihet** [comment]
И это нормально

**Comment by YRozmysl** [comment]
ок, так и попробуем

**Comment by YRozmysl** [comment]
И при последовательном переходе, без перескакивания версий, получаем такую же картину.

Закончен процесс восстановления базы данных: 10:39:27, 03 Сентябрь 2021
Ошибка при присвоении нового идентификатора базы данных
gbak: WARNING:    module name or entrypoint could not be found 
gbak: WARNING:function ABS is not defined 
gbak: WARNING:    module name or entrypoint could not be found 
gbak: WARNING:function ABS is not defined 
gbak:Skipped trigger GD_AD_RDB_RELATION_FIELDS on system table RDB$RELATION_FIELDS 
gbak:Skipped trigger GD_AU_RDB_RELATION_FIELDS on system table RDB$RELATION_FIELDS 
gbak:Skipped trigger GD_AI_RDB_RELATION_FIELDS on system table RDB$RELATION_FIELDS 
gbak:Skipped trigger GD_AD_RDB_INDEX_SEGMENTS on system table RDB$INDEX_SEGMENTS 
gbak:Skipped trigger GD_AU_RDB_INDEX_SEGMENTS on system table RDB$INDEX_SEGMENTS 
gbak:Skipped trigger GD_AI_RDB_INDEX_SEGMENTS on system table RDB$INDEX_SEGMENTS 
gbak:Skipped trigger GD_AD_RDB_INDICES on system table RDB$INDICES 
gbak:Skipped trigger GD_AU_RDB_INDICES on system table RDB$INDICES 
gbak:Skipped trigger GD_AI_RDB_INDICES on system table RDB$INDICES 
gbak:Skipped trigger GD_AD_RDB_PROCEDURE_PARAMETERS on system table RDB$PROCEDURE_PARAMETERS 
gbak:Skipped trigger GD_AU_RDB_PROCEDURE_PARAMETERS on system table RDB$PROCEDURE_PARAMETERS 
gbak:Skipped trigger GD_AI_RDB_PROCEDURE_PARAMETERS on system table RDB$PROCEDURE_PARAMETERS 
gbak:Skipped trigger GD_AD_RDB_PROCEDURES on system table RDB$PROCEDURES 
gbak:Skipped trigger GD_AU_RDB_PROCEDURES on system table RDB$PROCEDURES 
gbak:Skipped trigger GD_AI_RDB_PROCEDURES on system table RDB$PROCEDURES 
gbak:Skipped trigger GD_AD_RDB_TRIGGERS on system table RDB$TRIGGERS 
gbak:Skipped trigger GD_AU_RDB_TRIGGERS on system table RDB$TRIGGERS 
gbak:Skipped trigger GD_AI_RDB_TRIGGERS on system table RDB$TRIGGERS 
gbak:Skipped trigger GD_AD_RDB_RELATIONS on system table RDB$RELATIONS 
gbak:Skipped trigger GD_AU_RDB_RELATIONS on system table RDB$RELATIONS 
gbak:Skipped trigger GD_AI_RDB_RELATIONS on system table RDB$RELATIONS 
gbak:Skipped trigger GD_AD_RDB_FIELDS on system table RDB$FIELDS 
gbak:Skipped trigger GD_AU_RDB_FIELDS on system table RDB$FIELDS 
gbak:Skipped trigger GD_AI_RDB_FIELDS on system table RDB$FIELDS 
Начат процесс восстановления базы данных: 09:51:47, 03 Сентябрь 2021

**Comment by NikolayUkleyko** [comment]
@YRozmysl , в результате к базе данных можно подключиться и работает ли она ?

**Comment by gsbelarus** [comment]
триггеры на системные таблицы в 3 и 4 нельзя создавать. так что это не ошибки. а функцию ABS надо глянуть. она же вроде встроенная теперь, а там наверное из UDF подулючается. Надо убрать ее DROP FUNCTION и перекомпилировать тригера и процедуры где она используется.

**Comment by YRozmysl** [comment]
нет, к базе нельзя подключится, только  экспертом

**Comment by gsbelarus** [comment]
что значит нельзя? какую ошибку выдает?

**Comment by YRozmysl** [comment]
При подключении бета экзе (gedemin noId64 вот такая вот 
![miss_4](https://user-images.githubusercontent.com/11507129/131972092-ec6a3769-19fc-41da-86fe-7bc1cc934703.jpg)

Однако, при подключении текущим стандартным,  подключается

**Comment by YRozmysl** [comment]
при нажатии справка, о системе вот такая вот 

![system](https://user-images.githubusercontent.com/11507129/131972641-c47ba594-8a66-49ea-96ef-70eb5bee93e4.jpg)

**Comment by NikolayUkleyko** [comment]
Ясно.
Только для экспериментов - не более.
Уже и FB v.5 есть: http://web.firebirdsql.org/download/snapshot_builds/win/5.0/

**Comment by YRozmysl** [comment]
Если сделать уже потом бк под ФБ 4 и восстановить, то ненужные триггеры открутились,  и осталось только с ABS разобраться, там у ее 3 зависимости, это уже надо смотреть и править эти процедуры после комментирования.

Закончен процесс восстановления базы данных: 12:37:18, 03 Сентябрь 2021
Присвоен новый идентификатор базы данных
gbak: WARNING:    module name or entrypoint could not be found 
gbak: WARNING:function ABS is not defined 
gbak: WARNING:    module name or entrypoint could not be found 
gbak: WARNING:function ABS is not defined 
Начат процесс восстановления базы данных: 11:55:05, 03 Сентябрь 2021

![ABS](https://user-images.githubusercontent.com/11507129/131985244-bb144d1c-dd22-48e4-aeb7-5391d6c9141e.jpg)

**Comment by YRozmysl** [comment]
@gsbelarus  В config совместимость  вот тут надо устанавливать? 
DataTypeCompatibility = 2.5
Или тут надо сделать переход на 3.0 и сделать вот так?
DataTypeCompatibility = 3.0

**Comment by gsbelarus** [comment]
да

**Comment by NikolayUkleyko** [comment]
Актуальна ли данная тема ?
