### ISSUE TITLE
Отчеты. Ошибка при удалении

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4211]
![image](https://user-images.githubusercontent.com/11497453/132001116-50b2de7e-867c-4e6c-808a-e166b83db929.png)

Пожалуйста, поправьте или оставьте, как есть.
:wink:

**Comment by ShlTanya** [comment]
Опишите более подробно ошибку, откуда и что удаляете.

**Comment by NikolayUkleyko** [comment]
> _Опишите более подробно ошибку, откуда и что удаляете._

@ShlTanya , пожалуйста:

1. Открываем редактор скрипт-объектов.
2. Создаем новый отчет и коммитим его.
3. Пробуем выполнить удаление созданного отчета.

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
