### ISSUE TITLE
Кнопка "Справка" из основных бух.форм не перенаправляет на соответствующий раздел в WIKI

### ISSUE THREAD

**Issue by MAliaksandr** [GoldenSoftwareLtd/gedemin#4212]
Кнопка "Справка" из основных бухгалтерских форм, таких как: журнал ордер, карта счета, анализ счета, главная книга, оборотная ведомость не работает. 

![image](https://user-images.githubusercontent.com/11478712/134500760-b5d73cc3-b584-4107-9156-5ffb765850d2.png)

Хотелось бы, чтобы "Справка" работала аналогично стандартного варианта. 
Пример:
![image](https://user-images.githubusercontent.com/11478712/134501352-693675a9-a1f7-4301-8443-e3d2d75ba026.png)
перенаправляет на

![image](https://user-images.githubusercontent.com/11478712/134501458-a51e9594-efd0-4b02-ae6e-e579845febf7.png)

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, поправь ссылку на справку для Журнала-ордера:
http://gsbelarus.com/gs/wiki/index.php/Журнал-ордер

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.

**Comment by NikolayUkleyko** [comment]
Данную тему можно закрыть.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
