### ISSUE TITLE
Общие. Ошибка при двойном клике на выпадающих списках

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4215]
В любой форме, документе и т.д. на любом выпадающем списке пробуем дважды кликнуть мышкой.

![image](https://user-images.githubusercontent.com/11497453/135237794-a062f33e-16e8-49db-8fd4-dcd0519b4e83.png)

**Comment by ShlTanya** [comment]
Проверьте, есть ли сейчас эта ошибка.

**Comment by NikolayUkleyko** [comment]
Посмотрел в
**_Исследователь → Торговля → 01. Накладная на получение товара → 2-й клик на любом поле с выпадающим списком в шапке документа_**:
![image](https://user-images.githubusercontent.com/11497453/150760562-2a964036-c44e-40bb-89c6-cc10bf7a40f6.png)

**Comment by NikolayUkleyko** [comment]
@yoannawx , такая тема тоже интересна.

**Comment by gsbelarus** [comment]
Сделано. Надо обновить экзешник.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@gsbelarus , спасибо !
