### ISSUE TITLE
Общие. В свойства объекта добавить отображение IP-адреса (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4216]
_**Запись по документу → Контекстное меню → Свойства... → Общие.**_

@ShlTanya , пожалуйста, для реквизитов **Кто создал**, **Кто изменил** добавь отображение IP-адреса:
![image](https://user-images.githubusercontent.com/11497453/135404146-f9a7f6a2-b1ed-49e9-89b7-dd14376e173b.png)

**Comment by ShlTanya** [comment]
Думаю, что это невозможно. Пользователь программы никак не связан с компьютером, на котором он работает.

**Comment by NikolayUkleyko** [comment]
Хорошо, Татьяна.
Андрей Петрович уточнял, если в табличке **GD_JOURNAL** хранится IP (да, IP хранится в поле **CLIENTADDRESS**), то можно отображать IP.

**Comment by gsbelarus** [comment]
editorkey, creatorkey это просто ссылки на справочник контактов. IP никакой мы туда не впишем. Разве что в запись GD_JOURNAL, при включенном логировании, можно добавлять информацию (если она еще туда не добавляется).

**Comment by NikolayUkleyko** [comment]
Внесите правки или закройте тему.
