### ISSUE TITLE
Общие. Заголовок в свойствах записи

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4217]
В **диалоговой форме** любого типа документа (складской, пользовательский, прайс) поправьте заголовок в свойствах записи:

сейчас так →
![image](https://user-images.githubusercontent.com/11497453/135856569-8263db69-bec6-42d4-a7f9-cbbbd8adac7b.png)

было так →
![image](https://user-images.githubusercontent.com/11497453/135856979-e3d76c4c-7a24-43f2-9731-5ae27149b492.png)

**Comment by gsbelarus** [comment]
не надо поправлять. сейчас экзешник компилируется с ключем DEBUG. Поэтому и
данная запись появляется. как закончим тестирование, мы ее уберем.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , хорошо.
Не было информации по отличительным признакам gedemin.exe debug, поэтому и не знали. :smiley:

**Comment by gsbelarus** [comment]
![image](https://user-images.githubusercontent.com/5175764/135865722-eddea6a0-a097-4725-85f8-eb78dc0d1743.png)
