### ISSUE TITLE
Общие. Ошибка при добавление поля с доменом DBOOLEAN и пустом значении для существующих записей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4218]
1. В любую таблицу добавляем поле с доменом **DBOOLEAN**.
2. При появлении сообщения об установке значения поля для существующих записей нажимаем на кнопку **Да**.
3. Очищаем поле со значением.
4. На экране программа отображает сообщение об ошибке.
При этом можно продолжить сохранение нового поля, нажав на кнопку **OK**.

Если, при появлении сообщения об установке значения поля для существующих записей нажать на кнопку **Нет**, то программа не отобразит сообщения об ошибке.

----

Рис. 1.
![image](https://user-images.githubusercontent.com/11497453/136349787-f13d1392-2ba9-4877-b8ae-532a1cb9fe44.png)
Рис. 2.
![image](https://user-images.githubusercontent.com/11497453/136349814-542d1cf7-edb8-4de8-9f7e-15d4417297c9.png)
Рис. 3.
![image](https://user-images.githubusercontent.com/11497453/136349829-96fa1d8d-fff6-40da-b930-17b358db02ff.png)

----

Как вариант, достаточно предусмотреть обязательное заполнение параметра для ввода значения по существующим записям.

**Comment by ShlTanya** [comment]
А зачем вы очищаете поле со значением, если отвечаете на вопрос Да.. какое значение тогда должно проставиться для существующих записей. Соглашусь, что в таком случае вообще программа не должна пустить дальше.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , по ходу добавления поля подумали, что необходимо не заполнять значение нового поля для существующих записей и наверняка очистили значение — **Null**.
При этом, программа позволяет это сделать.

> какое значение тогда должно проставиться для существующих записей.

Как вариант **0**.

> Соглашусь, что в таком случае вообще программа не должна пустить дальше.

@ShlTanya , пожалуйста, предложи варианты.

**Comment by gsbelarus** [comment]
Пустую строку не давать ввести или дальше не пропускать. Если надо именно null вести в БД, то человек должен  набрать null  в строке.

**Comment by ShlTanya** [comment]
Доработано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
