### ISSUE TITLE
Грид. Добавление записи и сообщение "Список для выбора пуст"

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4219]
**а.** Формируем документ, добавляем несуществующую запись в справочник и нажимаем на **кнопку выпадающего списка (треугольник)** — программа выдаст сообщение:
![image](https://user-images.githubusercontent.com/11497453/136386348-43f3dffa-dd64-4330-ab84-8d01ac53d64b.png)

Нажимаем на кнопку **Нет**.
Вносим данные в справочник.
После сохранения записи в справочник программа выдаст сообщение:
![image](https://user-images.githubusercontent.com/11497453/136386523-f20e3e56-c8ca-4191-a2b7-45e2a8576110.png)

Необходимо закрыть такое сообщение и перевыбрать только что созданную запись в справочнике.

-----

**б.** Формируем документ, добавляем несуществующую запись в справочник и нажимаем на кнопку **Tab** или **мышкой кликаем по другому полю документа** — программа выдаст сообщение:
![image](https://user-images.githubusercontent.com/11497453/136386348-43f3dffa-dd64-4330-ab84-8d01ac53d64b.png)

Нажимаем на кнопку **Нет**.
Вносим данные в справочник.
После сохранения записи в справочник сообщения о пустом списке программа не выдаст.

-----

**в.** Формируем документ, добавляем несуществующую запись в справочник и нажимаем на кнопку **Курсор вниз** — программа выдаст сообщение:
![image](https://user-images.githubusercontent.com/11497453/136386523-f20e3e56-c8ca-4191-a2b7-45e2a8576110.png)

----

@ShlTanya , пожалуйста, посмотри, можно ли внести правки, чтобы не было сообщения о пустом списке для выбора при нажатии на кнопку:
1. **Выпадающего списка (треугольник)**.
2. **Курсор вниз**.

Для внесения минимальных изменений можно рассмотреть следующий вариант.
При нажатии на кнопки согласно пунктов 1 и 2 необходимо, чтобы курсор переходил в другое поле (как, при нажатии на кнопку **Tab** или **ручном клике мышкой**).
@ShlTanya , не будет ли это противоречить другому функционалу платформы ?

----

Данный вопрос возник у Жанны.
Ее клиенты часто спрашивают, что же за такое сообщение о пустом списке для выбора, когда запись уже добавлена в справочник ?

**Comment by gsbelarus** [comment]
а что такое "добавляем несуществующую запись"?

**Comment by NikolayUkleyko** [comment]
То есть, новую запись, которой точно нет в справочнике.

**Comment by NikolayUkleyko** [comment]
По данному вопросу можно предполагать один из вариантов:

1. Выполнить приведенные доработки.
2. Не выполнять доработок и знать про кнопку **Tab** и **ручной клик мышкой** применительно к выпадающим спискам. Тогда рассматриваемую тему можно закрывать.

**Comment by NikolayUkleyko** [comment]
Пообщались с коллегами.
Решили не вносить правки по рассматриваемой теме.
