### ISSUE TITLE
Общие. Интересная кнопка по экспорту данных

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4220]
_Исследователь → Справочники → Справочник ТМЦ → Контекстное меню._

Такая кнопка встречается в различных объектах.
Пожалуйста, подскажите, для каких целей предназначена старая команда **Экспорт** ?
Вроде она не работает.
Тем более уже есть абсолютно другой гибкий функционал по экспорту данных.
Может имеет смысл скрыть данный пункт ?

![image](https://user-images.githubusercontent.com/11497453/136924553-f892d78c-bffa-4683-9186-5a23a92e538e.png)

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
