### ISSUE TITLE
ПИ. Окно хода загрузки и количество файлов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4221]
Выполняем установку только выбранных ПИ.
В данном примере их количество составляет 12.
В окне синхронизации ПИ выводится количество файлов для загрузки - 12.
В окне хода загрузки указано другое количество - 48.
Вероятно указано общее количество ПИ: выбранные ПИ и связанные ПИ.
Пусть.

Пожалуйста, для большей наглядности добавьте еще строку для только выбранных ПИ - согласно примера, установлено ... ПИ из 12 ПИ.
Сейчас непонятно сколько загружено только выбранных ПИ.
Иначе, в существующей строке отображать только выбранные для загрузки файлы без связанных - 12.
![image](https://user-images.githubusercontent.com/11497453/136929596-f54a703f-d468-4e0d-870c-b13e7e8647d0.png)

**Comment by gsbelarus** [comment]
Установить ПИ невозможно без установки ПИ, от которого оно зависит. Тут все логично и правильно. Выбрал 12, вместе с зависимыми 48. Так во всех системах и в этом нет ничего страшного.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , благодарю за ожидаемый ответ.
