### ISSUE TITLE
Ошибка при поиске с регулярными выражениями

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4223]
Заходим в Редактор скрипт-объектов. Вызываем поиск по базе данных. Ставим галку Регулярные выражения. Запускаем и получаем ошибку.

**Comment by dmitranoid** [comment]
не воспроизводится.
можно подробнее настройки поиска и скрин ошибки

**Comment by gsbelarus** [comment]
Ок. Завтра попробую повторить. Пока можно другое делать.

аў, 21 сне 2021, 21:03 карыстальнік dmitranoid ***@***.***>
напісаў:

**Comment by gsbelarus** [comment]
Да. На моем компьютере тоже не повторяется. Пока снимаем вопрос. Наверное что-то локальное. Единственное глянуть как там идет поиск. Если через внешний COM объект, то try..except-ом надо обрабатывать его создание и, если не создался, то выдавать на экран сообщение.

**Comment by gsbelarus** [comment]
Но, зато другая проблема вылезла. Если задать условие поиска которое приведет к очень большому количеству найденных значений (например, ищем просто букву a через регулярные выражения), то Гедымин зависнет на большой базе.

Надо ограничивать количество найденных значений разумным числом. Например, 1000. И в процессе поиска проверять. Как только перешли за порог, останавливаем поиск и на экран выдаем сообщение, что найдено слишком много, пересмотрите условия поиска. И отображаем 1000 найденных строк.
