### ISSUE TITLE
На вкладке с множеством в гриде не отображаются колонки

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4224]
Сейчас в диалоговых окнах, где есть атрибуты типа множество на вкладке с элементами множества грид по умолчанию отображается со всеми невидимыми колонками. Например, окно группа компаний:

![image](https://user-images.githubusercontent.com/5175764/146909382-cf602484-bfa5-424c-bb57-88ab75784ea4.png)

Надо посмотреть по коду. По умолчанию должна быть видима колонка с полем наименование для бизнес-класса. Получается методом getListField.

**Comment by ShlTanya** [comment]
исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :gift:
