### ISSUE TITLE
Все равно создаются РУИДы на проводки

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4225]
На базе А. после всех манипуляций и с бета экзешником. Надо сделать тригер на AC_ENTRY AFTER INSERT который будет проверять есть ли такой ИД в таблице GD_RUID и кидать исключение, если есть. Запустить Гедымин и делать разные действия, пока не будет исключение. Тогда поймем в какой именно момент и где создаются РУИДы.

**Comment by yoannawx** [comment]
на базе А руиды создаются на AC_ENTRY при вызове из макроса метода .CreateEntry

**Comment by NikolayUkleyko** [comment]
> на базе А руиды создаются на AC_ENTRY при вызове из макроса метода .CreateEntry

Актуально, когда по документу настроены проводки и по шапке, и по позиции.

**Comment by gsbelarus** [comment]
https://github.com/GoldenSoftwareLtd/gedemin-private/pull/40
