### ISSUE TITLE
Нельзя создать контакт, когда скрыто дерево папок в форме просмотра

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4226]
Если в справочнике Контактов скрыть дерево (т.е. задвинуть разделитель максимально влево):

![image](https://user-images.githubusercontent.com/5175764/147064398-88e2e757-b7e3-4e43-9609-eb070c749e69.png)

чтобы получилось вот так:

![image](https://user-images.githubusercontent.com/5175764/147064458-cc3e1412-62f3-4809-af61-d7e5089eaba3.png)

То на панели инструментов не доступна команда создания нового контакта:

![image](https://user-images.githubusercontent.com/5175764/147064582-495bf747-7fad-46ea-9d93-eba3b1865756.png)

Она должна быть доступна. 

@AliakseiDanilchyk

**Comment by DonPhantom000** [comment]
Сделано

**Comment by Polfath** [comment]
Если сплиттер сдвигается до левого края формы, кнопка "Добавить" Disabled. (неактивна)

**Comment by Polfath** [comment]
Сделал возможным добавлять записи при крайнем левом положении разделителя

**Comment by gsbelarus** [comment]
Так работает Гедымин. Не надо это менять. Потому что в одном месте будет одна логика, а в другом, другая. Закрываю.
