### ISSUE TITLE
При удалении группы контактов удаляются все входящие в нее контакты

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4228]
Такого не должно быть ни в коем случае! При удалении группы должна удаляться ТОЛЬКО сама группа и больше ничего.

**Comment by dmitranoid** [comment]
что должно произойти с контактами

**Comment by gsbelarus** [comment]
должны просто остаться в базе данных

**Comment by gsbelarus** [comment]
Надо сначала глянуть кто их удаляет. Это в коде бизнес-объекта группы такое или триггер у нас есть.

**Comment by dmitranoid** [comment]
![изображение](https://user-images.githubusercontent.com/3066236/147593933-25533004-85d4-4200-ae0e-86e989809cb2.png)
![изображение](https://user-images.githubusercontent.com/3066236/147594224-3ab98dba-3076-4dde-b876-a27db7fca48b.png)
на той версии базы что есть у меня, не дает папку если в ней есть контакты, там ли я смотрю ?

**Comment by gsbelarus** [comment]
Да, если контакт где-то задействован, то его не удастся удалить.

Вы создайте совершенно новый контакт (человека или организацию). Потом создайте новую группу. Включите этот контакт в группу. Удалите группу.

**Comment by AliakseiDanilchyk** [comment]
> 

@dmitranoid Вы не там смотрите. Проблема возникает не при удалении папки, а при удалении группы.
![group](https://user-images.githubusercontent.com/11484894/147729470-83be340d-7dc7-4031-8048-9ee92689b11a.jpg)

**Comment by NikolayUkleyko** [comment]
Дополнительно по рассматриваемой теме.
Контакт (организация) удаляется из базы данных даже при его удалении из правой части формы групп контактов.
В данном случае, контакт должен быть удален только из привязанной группы контактов и остаться в базе данных.

**Comment by gsbelarus** [comment]
Перенес в отдельную запись:

https://github.com/GoldenSoftwareLtd/gedemin/issues/4232
