### ISSUE TITLE
Поставить новую заставку

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4231]

**Comment by nemir1007** [comment]
добрый день) добавьте пожалуйста заставку в бету 
ОАО "ЦБК-Консалт"

**Comment by YRozmysl** [comment]
с сайта по ссылке взять новый exe   https://gsbelarus.com/pw/downloads/gedemin-beta/gedemin-noid64/ там уже есть заставка

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@gsbelarus , спасибо !
Пожалуйста, закройте тему.
