### ISSUE TITLE
Доработки по форме просмотра Группы контактов

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4232]
Группа контактов и Папка это разные вещи. Каждый контакт в Гедымине (юридическое лицо, физическое лицо, сотрудник предприятия и т.п.) должен и может находиться ТОЛЬКО в одной папке. Собственно, в таблице `GD_CONTACT` поле `PARENT` будет ссылаться на папку в которой находится контакт. Папка это тоже особый вид контакта. Т.е. для каждой папки есть запись в таблице GD_CONTACT. Папки могут образовывать иерархическую структуру, т.е. входить одна в другую. Папки мы видем ввиде дерева в левой части формы просмотра справочника контактов/организаций/людей.

Сейчас мы говорим не о Папке, а о Группе. Группа контактов (это тоже особый вид контакта) позволяет объединить несколько контаков для выполнения определенной задачи. Например, мы хотим поздравить некоторых клиентов с новым годом -- создали группу, поместили в нее клиентов, потом распечатали для них конверты и поздравления. Позже мы захотим некоторых клиентов пригласить на наш стенд на выставке. Мы сделаем другую группу и поместим в нее клиентов для того распечатать им пригласительные. При этом клиент может одновременно находиться и в двух группах -- на поздравление с новым годом и на выставку, только в одной группе или вообще не входить ни в какую группу.

Речь идет о следующих четырех доработках к форме просмотра групп:

![image](https://user-images.githubusercontent.com/5175764/147922552-9ce41748-d98c-4b01-9ea4-4567d773c7a3.png)

1. Форма просмотра групп (не путать с папками!!!)
2. При удалении группы должна удаляться ТОЛЬКО сама группа (т.е. одна запись в gd_contact). Входящие в эту группу контакты не должны удаляться из базы данных.
3. При удалении контакта в форме просмотра групп он должен только удаляться из этой группы, но НЕ ИЗ БАЗЫ ДАННЫХ.
4. При нажатии на кнопку Создать контакт надо задавать пользователю вопрос: Он хочет создать новый контакт в базе данных и добавить его в группу или Он хочет добавить в группу один или несколько уже существующих контактов.

Подобным образом у нас работает форма просмотра рабочих организаций. Если мы нажимаем там кнопку Создать, то появляется такой вопрос пользователю:

![image](https://user-images.githubusercontent.com/5175764/147922917-1e001acc-acdc-44b6-a981-0ed1ffc09b1b.png)

Единственное что, в форме рабочих организаций при выборе существующего контакта появляется окно одиночного выбора:

![image](https://user-images.githubusercontent.com/5175764/147923040-a2b609e1-7f4c-40d2-9521-75d582955078.png)

Это оправданно в данном случае, так как рабочих организаций в любом случае единицы и добавляются они по одной. В случае группы будет более оправдано применить тут окно выбора множества записей.

@AliakseiDanilchyk

**Comment by dmitranoid** [comment]
беру в работу

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@dmitranoid , спасибо !

По возможности посмотрите следующее:
1. При нажатии на кнопку добавления записей в группу и хорошо бы для удобства выбора 2-х и более записей предусмотреть **CheckBox**. Так реализовано при редактировании группы и выборе записей. 
2. При удалении записи из группы немного поправить сообщение:
    **_Сама запись удалена не будет → Запись останется в базе данных_**.

**Comment by NikolayUkleyko** [comment]
По данной теме были выполнены доработки.
Выше изложены предложения.
Внесите правки или закройте тему.
