### ISSUE TITLE
Бухгалтерия. Конструктор функций. Ширина блока по наименованию

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4233]
1. Открываем конструктор функций.
Неполное наименование блока.
![image](https://user-images.githubusercontent.com/11497453/148223933-916caf48-5ab0-4f4a-abad-0d4fe9aaf1c9.png)

2. Кликаем по блоку.
Полное наименование блока.
![image](https://user-images.githubusercontent.com/11497453/148223954-b351261a-4660-47fd-920d-c8762bcdad2c.png)

Пожалуйста, внесите доработку, чтобы ширина блоков была корректная.
@dmitranoid

**Comment by NikolayUkleyko** [comment]
Здесь еще есть некоторая задержка при переходе с блока на блок.
@DonPhantom000 , пожалуйста, посмотри.

**Comment by gsbelarus** [comment]
делалось это когда то под маленькие экраны. теперь можно сходу ширину левой
части и всех блоков раща в полтора увеличивать.

пт, 26 жні 2022, 14:16 карыстальнік NikolayUkleyko ***@***.***>
напісаў:

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста, посмотрите данную тему.
Основные моменты:

1. Корректная ширина блоков.
2. Задержка при переходе с блока на блок.

**Comment by Polfath** [comment]
@NikolayUkleyko Как через UI туда попасть?

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста:
_**Исследователь → Бухгалтерия → Типовые хоз. операции, Автоматические хоз. операции**_.
Далее, в гриде выбираем запись (типовая проводка или автоматическая проводка) → Редактирование → Конструктор.

**Comment by Polfath** [comment]
Попробую разобраться

**Comment by Polfath** [comment]
Сделал. Сэмулировал клик по блоку при открытии формы.

**Comment by NikolayUkleyko** [comment]
Проверено.
Сейчас ширина блоков не смещается, как при открытии конструктора функций, так и при клике по блоку.

При этом, в режиме конструктора функций нажать на клавишу **Ok** и в форме типовой проводки нажать на клавишу **Ok** — программа отображает окно со следующей ошибкой:
![image](https://user-images.githubusercontent.com/11497453/193233360-4baf9c6e-3978-41b8-9137-1f2d344e4201.png)

**Comment by Polfath** [comment]
Исправил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
