### ISSUE TITLE
Конструктор функций. Свойства параметров. Упорядочить типы данных по возрастанию

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4234]
![image](https://user-images.githubusercontent.com/11497453/148250611-f84e63f4-4b6d-4c80-8a75-73454babfb46.png)
Пожалуйста, упорядочите типы данных по возрастанию.
@dmitranoid

**Comment by ShlTanya** [comment]
Упорядочить по какому признаку.. по наименованию типа данных.. по принадлежности к типам. Дайте, пожалуйста, точный список желаемого.

**Comment by NikolayUkleyko** [comment]
> _Упорядочить по какому признаку.. по наименованию типа данных.. по принадлежности к типам. Дайте, пожалуйста, точный список желаемого._

@ShlTanya , по наименованию типа данных (по алфавиту) по возрастанию.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, подскажите один из вариантов:

1. Сортировка по наименованию по возрастанию.
2. Сортировка по типам данных.
3. Не сортировать. Оставить без доработок.

**Comment by NikolayUkleyko** [comment]
> @gsbelarus , пожалуйста, подскажите один из вариантов:
> 
> 1. Сортировка по наименованию по возрастанию.
> 2. Сортировка по типам данных.
> 3. Не сортировать. Оставить без доработок.

@gsbelarus , пожалуйста, посмотрите.
Необходимо закрыть тему.

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, подскажите, какой вариант выбрали ?

**Comment by NikolayUkleyko** [comment]
Похоже выбрали вариант:
_Не сортировать. Оставить без доработок._
