### ISSUE TITLE
Общие. Мастер установок. Условия. Отображение параметров

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4235]
Выполняем следующие действия:
1. **_Использовать условия → Название и колонка условия и т.д. → Шрифт и цвет колонки._**
![image](https://user-images.githubusercontent.com/11497453/149108662-cbb05753-786e-435f-9ea5-269541f9415e.png)

2. Закладка **_Шрифт и цвет, колонки_**
![image](https://user-images.githubusercontent.com/11497453/149121803-d710965f-de12-4ca8-b58e-f4d73839af49.png)

Кнопки выбора шрифта, цвета и т.д. неактивны.
Нажатие кнопки **_Добавить_** приводит к очистке введенных условий.
Необходимо заново заполнять параметры условия.
Не вариант.

:green_circle: Для избежания подобной ситуации предлагаю сделать колонки условия активными только после нажатия на кнопку **_Добавить_** или в случае редактирования уже сохраненного условия.

-----

В случае снятия галки с реквизита **_Использовать условия_** при уже сохраненных условиях параметры условий очищаются:
![image](https://user-images.githubusercontent.com/11497453/149121131-268aca9e-a289-43f1-bf2a-1c0da7ae09d3.png)
![image](https://user-images.githubusercontent.com/11497453/149121151-aa6531a5-2be3-4a21-af33-5a0e7bf18ff7.png)

При установке галки по реквизиту **_Использовать условия_** параметры условий снова отображаются:
![image](https://user-images.githubusercontent.com/11497453/149121181-8af5bee3-5ca9-4e9d-83f5-c77c571ee3b8.png)
![image](https://user-images.githubusercontent.com/11497453/149121193-5b5c06ea-50f0-409b-a6a5-14cb331be919.png)

:green_circle: Хорошо бы предусмотреть видимость значений параметров условий при снятой галке с реквизита **_Использовать условия_**.

-----

![image](https://user-images.githubusercontent.com/11497453/149118844-2a170456-7c5d-4339-aebd-6fbeaa86c73c.png)

В каком порядке сортируются колонки в выпадающем списке параметров условий ?
Я так понимаю, что в порядке указанном в Мастере установок на закладке **_Колонки_**.
Так ли ?

:green_circle: Как отдельная опция можно предусмотреть сортировку колонок по алфавиту по возрастанию.

**Comment by ShlTanya** [comment]
Исправлено. Сортировку колонок не меняли, т.к. отсортировано по отображению колонок на форме (удобно).

**Comment by NikolayUkleyko** [comment]
> _Исправлено. Сортировку колонок не меняли, т.к. отсортировано по отображению колонок на форме (удобно)._

Замечательно, @ShlTanya !
Можно ли по выпадающему списку колонок внести некоторые доработки:
1. Сделать окно выбора больше. Много колонок в маленьком окне.
2. Добавить признак, что колонка не отображается. Так сделано в Мастере установок на закладке **_Колонки_** или в форме экспорта данных.
3. Добавить возможность поиска колонок по наименованию.

**Comment by ShlTanya** [comment]
2. Это же просто список колонок для составления условия. Действительно ли здесь нужен признак, что колонка не отображается? Это все-таки разные понятия.

**Comment by NikolayUkleyko** [comment]
> _2. Это же просто список колонок для составления условия. Действительно ли здесь нужен признак, что колонка не отображается? Это все-таки разные понятия._

Если, есть возможность при минимальных правках как-то выделять неактивные колонки.
То есть, не прямой признак, а выделять цветом.
При настройке условий для грида, например, 10 колонок активные, а другие 50 неактивные.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , проверено:
1. Добавление пустого условия — решено.
2. Видимость значений параметров условий при снятой галке с реквизита **_Использовать условия_** — при **закрытии → открытии** Мастера установок значения параметров условий не отображаются.

Все остальные пункты без изменений.

**Comment by NikolayUkleyko** [comment]
Проверено.
Реализованы вышеприведенные пожелания.
Работает корректно.
@Polfath , большое спасибо !
