### ISSUE TITLE
При добавлении фильтра в ПИ затягиваются лишние записи

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4237]
Например, пользователи системы. При добавлении фильтра, только сам фильтр и должен попасть в ПИ. Больше ничего.

**Comment by NikolayUkleyko** [comment]
Смоделировал ситуацию.
Под пользователем Administrator.
С проставленной или снятой галкой по реквизиту **_Включить связанные объекты_**.
Кроме объектов фильтра ничего другого в ПИ не добавилось: TgdcSavedFilter, TgdcComponentFilter.

-----

Под пользователем отличным от Administrator.
С проставленной галкой по реквизиту **_Включить связанные объекты_**.
При добавлении в ПИ под пользователем отличным от Administrator с проставленной галкой по реквизиту **_Только для меня_** (предполагаемо в таблице **FLT_SAVEDFILTER** поле **USERKEY**) добавляется объект TgdcUser.
Со снятой галкой по реквизиту **_Включить связанные объекты_** объект TgdcUser не добавляется.

На практике под пользователем отличным от Administrator есть ли смысл формировать ПИ ?

**Comment by yoannawx** [comment]
фильтр добавлялся в пи новый, только что созданный под администратором, для всех, с галкой "включить связанные объекты", поскольку нет возможности включать только нужные из списка (а именно TgdcComponentFilter).

![image](https://user-images.githubusercontent.com/11497358/149470023-7a3b3eb1-c820-4290-b469-3b89c6d03c6a.png)

![image](https://user-images.githubusercontent.com/11497358/149471151-094ec4e2-054a-4648-823d-73126c3a5ec5.png)

как видно, в пи добавились не все зависимые объекта, а выборочно

![image](https://user-images.githubusercontent.com/11497358/149471380-c5d3d63a-ad11-410d-bab3-cee29e9b7dae.png)

**Comment by yoannawx** [comment]
ехе 
![image](https://user-images.githubusercontent.com/11497358/149471786-231f591d-5617-4d77-bc3d-25bc25054016.png)

**Comment by NikolayUkleyko** [comment]
Хорошо бы посмотреть конкретный фильтр — **_ЭТТН за период_**.
Пока не могу на тестовую БД установить ПИ **_Электронный документооборот.Атлант_**.

**Comment by NikolayUkleyko** [comment]
@yoannawx , подсказала, что вышеприведенные проблемки возникают на рабочей БД при подключенных пользователях.

**Comment by Polfath** [comment]
так нужно?
![image](https://user-images.githubusercontent.com/112748962/201294608-f12ec3ae-c8f4-4bf3-ac45-5bf43852493c.png)

**Comment by Polfath** [comment]
так нужно?
![image](https://user-images.githubusercontent.com/112748962/201295019-c3494c7c-a886-4bad-8c34-f1214fd2104b.png)

**Comment by Polfath** [comment]
сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
При добавлении в ПИ одного из фильтров добавляются еще и лишние фильтры и пользователи базы данных.
Такое происходит в случае, когда по документу есть ряд фильтров и <ins>ни один их них не входит в ПИ</ins>.

**Comment by gsbelarus** [comment]
пользователи точно ни в коем случае не должны попадать

чц, 17 ліс 2022, 14:07 карыстальнік NikolayUkleyko ***@***.***>
напісаў:

**Comment by NikolayUkleyko** [comment]
Лишние (не выделенные для добавления в ПИ) фильтры также не должны попадать в ПИ.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

@gsbelarus , пожалуйста, закройте тему.
