### ISSUE TITLE
Грид. Добавить форматирование в подножие таблицы

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4238]
Пожалуйста, если, возможно, предусмотрите форматирование данных в подножии таблицы:
![image](https://user-images.githubusercontent.com/11497453/149925177-6180296c-65fd-4dfb-9188-e73814cf5bf7.png)
![image](https://user-images.githubusercontent.com/11497453/149924706-2bf940de-f2ad-4bbc-af30-61208ad18a8a.png)

**Comment by NikolayUkleyko** [comment]
Возможно раньше подобную доработку обсуждали.
Необходимо посмотреть, чтобы такие доработки не нарушили работоспособность грида в целом.
@ShlTanya

**Comment by ShlTanya** [comment]
Выделила жирным шрифтом числа в строке, т.к. подножие таблицы использует установленное форматирование таблицы

**Comment by gsbelarus** [comment]
Не надо жирным! Обычно суммы в подножии итак не влазят в ширину колонки, а жирным они станут ещё шире.

Не трогаем этот вопрос и закрываем.

**Comment by gsbelarus** [comment]
Т.е. николай хотел только, чтобы числа записей, текущая запись и т.п. выводились с разделителем тысяч.

**Comment by NikolayUkleyko** [comment]
> _Т.е. николай хотел только, чтобы числа записей, текущая запись и т.п. выводились с разделителем тысяч._

Да, верно.
Форматирование для строки итого предусмотрено давно, а вот для подножия таблицы такого нет:
![image](https://user-images.githubusercontent.com/11497453/151953636-0d55e325-5c1f-41bf-8ba9-7e916e07c0e4.png)

**Comment by NikolayUkleyko** [comment]
По данной теме выполнена доработка **_version 2_**.
Пока не включена в **gedemin.exe**.

**Comment by NikolayUkleyko** [comment]
Внесите правки или закройте тему.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
