### ISSUE TITLE
Бухгалтерия. Переход из выпадающего списка на карту счета с заполнение аналитики "Документ" и других

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4239]
Пожалуйста, предусмотрите возможность перехода из выпадающего списка на карту счета с заполнение аналитики **_Документ_**, **_Договор_** и других (где, для аналитики указан домен со ссылкой на **_GD_DOCUMENT_**).
Реализовать это можно на уровне сообщения **_Установить в карте счета текущее значение аналитики — Да/Нет/Отмена_**.
![image](https://user-images.githubusercontent.com/11497453/150121138-abe80e20-5f98-4107-a1d2-4bbc5b35e037.png)

-----

После закрытия карты счета программа отображает следующее сообщение:
![image](https://user-images.githubusercontent.com/11497453/150121988-204d4aa3-03dd-4f8d-a012-bee1293f03e6.png)

Самое интересное, что при нажатии на кнопку:
• **Да** — значение аналитики очищается;
• **Нет** — значение аналитики сохраняется.

Наверное необходимо поменять назначение кнопок в данном случае.

**Comment by ShlTanya** [comment]
1. Переход на карт-счет и выбор значения реализован в самом компоненте LookupComboBox, который знает только свои данные (например, только документ). Установить другие значения аналитик на форме карт-счета не вижу возможности. Есть ли смысл устанавливать в качестве аналитики уже ранее выбранное значение? 
2. По подтверждению выбора не увидела проблем. При нажатии Да - идет заполнение поля аналитики выбранным значением из формы карт-счета, при Нет -остается прошлое значение аналитики. Но надо помнить, что данный режим выбора заполняет значение аналитики только по Документу, т.е. в аналитику подставляется значение Documentkey из выбранной записи формы карт-счет. Поэтому, данный режим выбора работает корректно работает только для аналитики Документ.

**Comment by NikolayUkleyko** [comment]
С @ShlTanya уточнили возникшие вопросы.
Закрываем тему.
