### ISSUE TITLE
Грид. Настройка форматирования нескольких выделенных колонок

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4241]
@ShlTanya , пожалуйста, посмотри можно ли предусмотреть в Мастере установок возможность настройки форматирования нескольких выделенных колонок с одинаковым типом.
Например, числовые поля.
Сейчас настройки не сохраняются для всех выделенных колонок.

-----

Иногда программа отображает окно с сообщением об ошибке **_...violation_**.

**Comment by gsbelarus** [comment]
Надо конкретный повторяемый пример который приводит к ошибке.

**Comment by NikolayUkleyko** [comment]
Ошибки пока нет.
Не всегда она моделируется.

Пожалуйста, предусмотреть возможность настройки форматирования нескольких выделенных колонок с одинаковым типом.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
