### ISSUE TITLE
ЗП. Аналитика сотрудник. Карта счета.

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4242]
Есть проблема для  скрытия определенным бухгалтерам информации  по зарплате. Как можно программно, или иных методов ограничить доступ к просмотру проводок с аналитикой сотрудник. Если есть возможность, сделать для определенных групп пользователь. Это было бы идеальною. Проблема вполне реальная, а  местами и критичная.

**Comment by gsbelarus** [comment]
В принципе, в ac record есть дескрипторы безопасности.

**Comment by YRozmysl** [comment]
Как временное решение в плане счетов по сч.70 убрали аналитику сотрудник. Пока, как временное решение такое.

**Comment by NikolayUkleyko** [comment]
Смоделировал вариант настройки с настройкой прав доступа в таблицах **AC_ENTRY**, **AC_ENTRY_BALANCE** для поля **USR$GS_EMPLOYEE**.
Формирование бухгалтерских форм для пользователей выполняется без ограничений.
