### ISSUE TITLE
Обновлять параметры отчета по мере ввода символов номера счета

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4243]
![image](https://user-images.githubusercontent.com/5175764/151951726-748b788d-a9ad-4493-be21-2a5b721321f7.png)

В журнале-ордере, карте-счета, анализе счета есть такая проблемка. Если в поле ввода счета вводит счет с клавиатуры (набором номера), то все зависимые от него поля (например, список признаков аналитического учета) обновятся только после ухода курсора с поля. Это очень неудобно.

Надо сделать, чтобы по мере ввода номера, если введена последовательность для которой отыскивается в БД счет или субсчет, то сразу же обновлялись зависимые поля на экране.

Речь идет именно о панели в параметрами отчета в левой части окна.

**Comment by NikolayUkleyko** [comment]
Давно была выполнена похожая доработка @iamchrisep.
Выбрали вариант: _указали счет → нажали на кнопку **Enter** → перечень аналитики и другие параметры обновились_.

-----

Иногда бывает такое, что вводишь счет, например 10.10 и автоматически подставляется счет 10.10.1.
Счет не должен меняться на похожий (ранее выбранный, который есть в списке).
Раньше такую проблему тоже решали.

**Comment by ShlTanya** [comment]
Параметры обновляются по нажатию кнопки Ввод. Надо делать по вводу значений?

**Comment by gsbelarus** [comment]
да. так удобнее будет.

**Comment by gsbelarus** [comment]
Немного не так. Я проверил с последними изменениями. Например, выбран счет 51 и для него отображается аналитика. Я хочу счет 62. Я в поле счета начинаю удалять символы бэкспейсом. Удаляю 1 и у меня остается 5. И аналитика меняется. А не должна, потому что нет счета "5". 

Логика такая, если в поле введен номер счета который есть в справочнике, то мы меняем список аналитик, показываем там аналитики счета. Если введен счет, которого нет -- "5", "62." -- то не трогаем справочник аналитик, чтобы он не дергался лишний раз.

Номера счетов надо сравнивать как строки, а не числа. В базе есть счет "05", но это именно "05", а не "5".

**Comment by gsbelarus** [comment]
заодно сразу просьба поправить:

![image](https://user-images.githubusercontent.com/5175764/155103585-842fe645-3654-4049-ba3d-476a8b019338.png)

Увеличить в два раза высоту списка 1.
Слева и справ группы кнопок 2 промежутки сделать одинаковыми.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , это замечательно !
Как будет работать такой функционал, если указать 2-а и более счета через запятую (с пробелами и без) ?

**Comment by gsbelarus** [comment]
так же как сейчас должен работать

**Comment by gsbelarus** [comment]
по мере ввода, смотрим если в строке есть запятые, разбиваем такую строку на составляющие, из них оставляем те, которые представляют собой правильные номера счетов и для них строим список аналитик. как он сейчас строится я не знаю. теоретически это должно быть пересечение аналитических признаков счетов в списке.

т.е. "62,51" -- берем аналитики 62-го и 51-го счетов
"62,5" -- берем аналитики 62-го счета, т.к. нет номера счета 5.
"60,62." -- берем аналитики счета 60, т.к. нет счета "62."

**Comment by ShlTanya** [comment]
Выполнено

**Comment by NikolayUkleyko** [comment]
Проверено.
@ShlTanya , спасибо !

@ShlTanya , пожалуйста, попробуй указать счет 10.01.
Получается, вводим 10 и при этом автоматически выделяются символы 10.
Далее необходимо указать точку и для этого мышкой кликаем в правой части.
После простановки точки автоматически подставляется похожий счет, который до этого уже был выбран.

@ShlTanya , пожалуйста, внеси правки, для удобного ввода счетов в ЖО без вышеприведенных действий.

**Comment by ShlTanya** [comment]
Т.к. это Combobox, который содержит список из ранее выбранных счетов, то при вводе символов, будет подставляться значение из списка. Изменить стандартное поведение компонента нет возможности.

**Comment by gsbelarus** [comment]
немного прихожу в отчаяние. т.к. написано одно, а сделано немного другое ((

выше:
`
Удаляю 1 и у меня остается 5. И аналитика меняется. А не должна, потому что нет счета "5".`

Т.е. по мере ввода, если в строке получился существующий номер счета, то обновляем списки аналитики значениями, которые соответствуют этому номеру счета.

ЕСЛИ ЖЕ, в процессе ввода строка не соответствует номеру счета сущестувующему в БД, то НИЧЕГО НА ЭКРАНЕ не меняем, не дергаем экран.

Пошагово:

1. Строка ввода пустая. Ничего не трогаем в аналитике. По идее там должно быть пусто или наоборот вся доступная аналитика. Это не принципиально. Как сделано сейчас так можно и оставить.
2. Пусть, наша задача ввести счет 62.01
3. Начинаем с цифры 6. Счета "6" нет в плане счетов, так что ничего на экране не трогаем, не дергаем, не перерисовываем.
4. Продолжаем вводить -- "62". Такой счет есть, значит обновляем списки аналитических признаков под этот номер счета.
5. Продолжаем "62." -- Счета "62." нет в плане счетов, так что ничего на экране не трогаем, не дергаем, не перерисовываем.
6. Продолжаем "62.0" -- Счета "62.0" нет в плане счетов, так что ничего на экране не трогаем, не дергаем, не перерисовываем.
7. Продолжаем "62.01" -- есть такой субсчет. Берем и выводим его аналитические признаки.

Сейчас же списки аналитики дергаются при каждом введенном символе. Это неправильно и некрасиво.

**Comment by ShlTanya** [comment]
В таком случае будет несоответствие между введённым счетом и аналитикой.. а если пользователь остановился на вводе. Вот например .. вы ввели счет 15 - отобразилась его аналитика.. стерли 5.. на экране мы видим (в вашем варианте) счет 1 и аналитика от 15. Именно поэтому я и делала обновление посимвольно.

**Comment by NikolayUkleyko** [comment]
Посмотрел.
Выявлено следующее.
Хорошо бы в новой версии **gedemin.exe** с текущей доработкой (Issue № 4243) делать _очистку списка до этого выбранных счетов_.
Можно вручную:
![image](https://user-images.githubusercontent.com/11497453/156165145-2d2030eb-822a-4aec-8805-3dc15440d4c2.png)

1. _Ctrl + Alt + E → поле **Счета**_.
2. _Items → TStrings_.
3. _Ctrl + A → Delete_.

Тогда, ввод счетов и автоматическое обновление аналитических признаков будут работать корректно.
 
-----

Так как, доработка в части автоматического обновления аналитических признаков согласно введенных счетов переплетается с вопросом **неправильной автоматической произвольной подстановки до этого выбранных счетов** (которые есть в списке).

**Comment by MIchaelShoihet** [comment]
Тогда нет смысла в комбобоксе... оставить простой edit и все... Но иногда очень удобно просто мышкой выбрать, по которому ты обычно строишь журнал или карту... Надо  посмотреть какие есть варианты... Эта подстановка работает как-то странно, иногда не успеваешь набрать символ, она уже подставили, а иногда ничего не подставляет...

**Comment by NikolayUkleyko** [comment]
> _Эта подстановка работает как-то странно, иногда не успеваешь набрать символ, она уже подставили, а иногда ничего не подставляет..._

Да, так и есть.
Нет какого-то единого алгоритма.
Например, указываешь счет 10, а тут уже подставляется 10.01.

Как вариант, можно выполнить очистку записей в поле **Счета** (_Items → TStrings_).

**Comment by gsbelarus** [comment]
`на экране мы видим (в вашем варианте) счет 1`

в том то и дело, что счета "1" нет в плане счетов. Там есть счет "01". Это разные вещи. номера счетов это строки, а не числа. Перерисовка на каждое нажатие клавиши, как сейчас не нужна. Будет отвлекать и раздражать пользователя.

**Comment by gsbelarus** [comment]
`Как вариант, можно выполнить очистку записей в поле Счета (Items → TStrings).`

в чем тогда смысл списка последних счетов?

у меня работает нормально. в смысле подставляет по нажатию стрелки вниз, что и является поведением по умолчанию для выпадающего списка.

**Comment by ShlTanya** [comment]
Исправила

**Comment by gsbelarus** [comment]
Переоткрываю. Похоже надо вернуть в исходное состояние.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте данную тему.

**Comment by Polfath** [comment]
сделано
