### ISSUE TITLE
Бухгалтерия. Карта счета, Журнал хоз. операций. Добавить поле ”Дата создания проводки”

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4244]
**_Исследователь → Бухгалтерия → Карта счета, Журнал хоз. операций._**

Пожалуйста, подскажите, можно ли добавить поле **Дата создания проводки** (ENTRYCREATIONDATE) с отображением времени ?
Это удобно при анализе проводок по (существующим полям):

- дата документа (DOCUMENTDATE);
- дата изменения документа (EDITIONDATE);
- дата создания проводки (ENTRYCREATIONDATE).

Перепровели проводки по документам.
В результате: EDITIONDATE прежний, нет данных о дате создания проводок (ENTRYCREATIONDATE).

**Comment by gsbelarus** [comment]
Пока работаем над 2.9.6. Эта версия не предусматривает изменения структуры БД.

**Comment by NikolayUkleyko** [comment]
> _Пока работаем над 2.9.6. Эта версия не предусматривает изменения структуры БД._

Хорошо, @gsbelarus.
При этом точно не ясно, не повлияет ли добавление таких полей на работоспособность программы и БД.

**Comment by MIchaelShoihet** [comment]
Сейчас эта тема актуальна. Добавить в ac_record поле CREATIONDATE. Поле editiondate не нужно потому что оно не отличается от editiondate  в gd_document, А вот creationdate нужно для случая когда мы пересоздаем проводки по документа. В этом случае проводки создаются заново, а creationdate и editiondate  в документе не меняются (это и хорошо документ мы не трогаем в этом случае)

**Comment by Polfath** [comment]
Добавил поле AC_RECORD.CREATIONDATE

**Comment by Polfath** [comment]
Добавлено поле CREATIONDATE в запрос для карты счета

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
:thumbsup:
