### ISSUE TITLE
Общие. Домены. Визуальные настройки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4246]
**_Исследователь → Сервис → Атрибуты → Домены._**
![image](https://user-images.githubusercontent.com/11497453/152991566-a9824ced-6f32-4a9b-9767-f7028dec3ce3.png)

Достаточно интересный функционал.
Есть вопросы по его работе.

Смоделировал различные ситуации.
При указании значений параметров и обновлении всех полей изменений нет.

Только выравнивание работает, но специфически.
Указал выравнивание.
Выравнивание отражается в колонке ...KEY, а не в локализованной.
Для числовых полей выравнивание не отражается.

-----

Аналогично и для полей таблицы.
![image](https://user-images.githubusercontent.com/11497453/152992313-c35aa8c1-936f-434d-acba-8c2182330e88.png)

**Comment by gsbelarus** [comment]
это не трогаем.

**Comment by gsbelarus** [comment]
выравнивание сохраняется в настройках грида и берется только оттуда. отсюда оно возьмется только если это какой то грид без настроек, и только при первом его отображении.

**Comment by NikolayUkleyko** [comment]
Хорошо, @gsbelarus.
Интересная тема со своими особенностями.
