### ISSUE TITLE
Проблема загрузки из ПИ параметра хранилища типа D 

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4248]
Создали в хранилище параметр:
![image](https://user-images.githubusercontent.com/11497358/153597100-4593921b-63c0-47f7-a936-db00c96fc8ad.png)
и добавили в ПИ.
![image](https://user-images.githubusercontent.com/11497358/153597347-32a38c95-1054-4a54-873a-25c362bba89a.png)
[test.zip](https://github.com/GoldenSoftwareLtd/gedemin/files/8048849/test.zip)

При установке ПИ на другую базу ошибка:
![image](https://user-images.githubusercontent.com/11497358/153597202-49fc0d0c-3467-44e8-b013-9fb66d2c857a.png)

**Comment by DonPhantom000** [comment]
Сделано

**Comment by yoannawx** [comment]
![image](https://user-images.githubusercontent.com/11497358/187718011-4f3e3499-db26-4e5d-9096-e16c4222a01e.png)

та же ошибка

**Comment by gsbelarus** [comment]
проверьте у вас точно обновился экзешник? я вижу в исходниках исправление прошло.

**Comment by gsbelarus** [comment]
FILEVERSION 2, 5, 0, 142

**Comment by yoannawx** [comment]
![image](https://user-images.githubusercontent.com/11497358/187845683-c5d7e60a-e5a0-4802-8f23-b0e2bc8ced52.png)

**Comment by gsbelarus** [comment]
это старый экзешник

newest gedemin.exe version 12273...

а тут билд 12266

обновите

**Comment by yoannawx** [comment]
отработало автообновление. все то же самое

![image](https://user-images.githubusercontent.com/11497358/187847069-34cc695a-c690-4eb6-8d2e-3f539c41f417.png)


вручную скачать и обновить?

**Comment by gsbelarus** [comment]
вручную скачайте

**Comment by yoannawx** [comment]
все ок.
