### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Добавить сообщение при дублировании нескольких выделенных записей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4250]
**_Исследователь → Бухгалтерия → Журнал хоз. операций._**

Сейчас при редактировании нескольких выделенных записей программа отображает соответствующее сообщение:
![image](https://user-images.githubusercontent.com/11497453/154273553-4ba38cc2-80e6-4b0c-b6c7-83414a365316.png)

Пожалуйста, предусмотрите такое сообщение и для режима дублирования записей.
Только формулировку немного поправьте:
**Множественное дублирование записей не поддерживается.
Будет продублирована последняя выделенная запись. Продолжить?**

**Comment by gsbelarus** [comment]
лучше просто писать что не поддерживается и на этом все. никакого
редактирования последней записи. и объединения тоже. т.к. лишняя
возможность пользователю сделать что то не так.

ср, 16 лют 2022, 16:28 карыстальнік NikolayUkleyko ***@***.***>
напісаў:

**Comment by NikolayUkleyko** [comment]
Замечательно !
Так еще проще. :+1: 

Тогда, сообщение будет следующим:
**Множественное дублирование записей не поддерживается.**

**Comment by DonPhantom000** [comment]
При попытке сделать это будет выведено сообщение 

![image](https://user-images.githubusercontent.com/111727555/186939789-53656768-d02e-41a0-b404-260753a65719.png)

без альтернатив

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@DonPhantom000 , спасибо ! :trophy:
