### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Очищается поле "Конфигурация" при активном реквизите "Запрашивать значение" (Q)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4251]
**_Исследователь → Бухгалтерия → Журнал-ордер._**

1. Редактируем конфигурацию.
2. По одной из аналитик проставляем галку по реквизиту **Запрашивать значение**. Сохраняем конфигурацию.
3. Из Исследователя запускаем конфигурацию на формирование. В результате в реквизите **Конфигурация** не выбрана текущая конфигурация.

Пожалуйста, посмотрите, можно ли в данной ситуации корректно заполнять реквизит **Конфигурация**.
Вышеприведенное актуально и для других бухгалтерских форм (Карта счета, Анализ счета).

![image](https://user-images.githubusercontent.com/11497453/154289741-f02bf8af-a884-4dc8-86e8-7d17084844b3.png)

**Comment by NikolayUkleyko** [comment]
@DonPhantom000 , пожалуйста, посмотри.

**Comment by Polfath** [comment]
Посмотрю

**Comment by Polfath** [comment]
Поправил.

**Comment by NikolayUkleyko** [comment]
Проверено.
@Polfath , пожалуйста, поправь автоматическую очистку поля конфигурации при создании новой конфигурации с выбранной галкой для аналитики **Запрашивать значение**.

**Comment by Polfath** [comment]
@NikolayUkleyko Проверь

**Comment by gsbelarus** [comment]
@Polfath проверьте пожалуйста вместе с @MIchaelShoihet что-то много кода вы там закоментировали, который раньше работал. не пойму.

**Comment by Polfath** [comment]
@gsbelarus Проверили. Коля сказал, что нормально.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
