### ISSUE TITLE
Бухгалтерия. Карта счета. Добавить сообщение при редактировании нескольких выделенных записей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4253]
**_Исследователь → Бухгалтерия → Карта счета._**

Пожалуйста, предусмотрите сообщение при редактировании нескольких выделенных записей:
**Множественное редактирование записей не поддерживается.**

**Comment by DonPhantom000** [comment]
Выполнено 
![image](https://user-images.githubusercontent.com/111727555/187163791-be1b1b9e-33cd-4946-9228-ff42e7558194.png)

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@DonPhantom000 , спасибо !

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Хорошо бы дополнительно предусмотреть аналогичную проверку и при редактировании позиций документов.

**Comment by gsbelarus** [comment]
Лучше делать отдельный issue.

**Comment by NikolayUkleyko** [comment]
Хорошо, @gsbelarus .

Пожалуйста, https://github.com/GoldenSoftwareLtd/gedemin/issues/4312.
