### ISSUE TITLE
Бухгалтерия. Оборотная ведомость. Переход на журнал-ордер. Уточнение по аналитикам

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4255]
**Исследователь → Бухгалтерия → Оборотная ведомость.**

1. При попытке перехода по счету, у которого не выбраны аналитические признаки на экране появляется следующее сообщение:
![image](https://user-images.githubusercontent.com/11497453/157698040-0ad799b3-be2f-489e-99f3-89dcb8d2e8ff.png)

Может быть в такой ситуации предусмотреть переход на журнал-ордер с выбранной аналитикой **Счета и субсчета** ?

2. При переходе в журнал-ордер по счету, у которого выбрана аналитика, например, _договор, клиент, статья затрат_ переход выполняется не по первой аналитике.
Хорошо бы уточнить алгоритм.

**Comment by NikolayUkleyko** [comment]
По пункту № 2, как вариант можно предположить дополнительную команду для перехода на форму Журнала-ордера и его формирования по счетам и субсчетам.

**Comment by Polfath** [comment]
ОК посмотрю

**Comment by Polfath** [comment]
Сделал @NikolayUkleyko Коля, посмотри пожалуйста

**Comment by NikolayUkleyko** [comment]
Хорошо, Андрей.

**Comment by NikolayUkleyko** [comment]
Проверено.
Необходимо поправить следующее:
1. При переходе из оборотной ведомости в анализ счета подставлять соответствующее значение дат. Сейчас в анализ счета подставляется предыдущее значение.
2. При переходе из оборотной ведомости в журнал-ордер подставлять аналитики в алфавитном порядке. Сейчас они подставляются в обратном порядке.

**Comment by Polfath** [comment]
Исправил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо ! 🏆
