### ISSUE TITLE
Процедура AC_L_Q для построения журнала-ордера

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4259]
Параметр ENTRYKEY DMASTERKEY - нот нулл... Но в запросе может передаться entrykey null в этом случает получаем ошибку... Надо измененить на DFOREIGNKEY. И проверить другие процедуры ...

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, подскажи, есть ли новости по данной теме ?
На Гомельобоях поставили gedemin.exe предыдущей версии, в которой корректно работает такой функционал.

**Comment by gsbelarus** [comment]
Поправлено на новейшем экзешнике.

Но, надо на базе выполнить:
```sql
delete from fin_versioninfo where id > 279
```
и еще раз подключиться чтобы прошел апдейт.

**Comment by gsbelarus** [comment]
хорошо бы увеличить номер версии, чтобы у всех прошел апгрейд. но не хотим сейчас бро трогать. в будущий апгрейд (любой) можно перенести обновление хранимых процедур из  procedure Modify_StoredProc_ID64(IBDB: TIBDatabase; Log: TModifyLog);

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
Спасибо !

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, посмотрите, есть ли возможность закрыть рассматриваемую тему ?
С включением в модифай соответствующих обновлений.

**Comment by NikolayUkleyko** [comment]
https://github.com/GoldenSoftwareLtd/gedemin/issues/4259#issuecomment-1094847868
В gedemin.exe разные модифаи.
Желательно включить в платформу автоматический модифай для рассматриваемой темы.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.

**Comment by NikolayUkleyko** [comment]
Данную тему можно закрыть.
