### ISSUE TITLE
Проблема при выборе обязательных параметров для отчета или функции

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4260]
Если параметр для построения отчета или выполнения функции является обязательным для заполнения, но не заполнен пользователем, выдается предупреждение:
![image](https://user-images.githubusercontent.com/11497358/158776877-6766f4ba-4481-46d4-b5a6-b7e6c7454ea6.png)
После нажатия ОК в данном окне продолжить работу с вводом параметров невозможно. Только если нажать Esc и вызвать отчет (функцию) еще раз.

**Comment by ShlTanya** [comment]
Исправлено
