### ISSUE TITLE
Общие. Ошибка при поиске в базе данных с выбранной опцией "Поиск по ИД или RUID"

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4262]
1. _Типовые документы → 01. Накладная на получение материалов, ОС, МБП → Свойства → копируем ID или RUID_.
![image](https://user-images.githubusercontent.com/11497453/159005343-cb56f550-1bb4-47b7-808b-68faea489d15.png)
![image](https://user-images.githubusercontent.com/11497453/159005377-73ae9f07-ec34-4725-a1c8-cdcc5a6007df.png)

-----

2. _Редактор скрипт-объектов → Поиск в базе данных → Выбрать опцию "Поиск по ИД или RUID"_.
![image](https://user-images.githubusercontent.com/11497453/159005879-d2f9c242-1cbb-40a5-9c1e-6454dc8643e3.png)
![image](https://user-images.githubusercontent.com/11497453/159005899-df742a9f-93fc-4ec1-9d6b-05f169b8d623.png)

-----

3. _Сообщение об ошибке_.
![image](https://user-images.githubusercontent.com/11497453/159005399-f16480dc-c754-44db-a163-fd63dcb6fe24.png)

**Comment by ShlTanya** [comment]
Данная функция используется для поиска функций по их Id. Данная ошибка в показанном примере верная.

**Comment by NikolayUkleyko** [comment]
Поиск функций по RUID выполняется правильно.
Поиск функций по ID не совсем получается.

Может есть смысл переименовать опцию **_Поиск по ИД или RUID_** → **_Поиск функции по ID или RUID_**.
@ShlTanya ?

**Comment by ShlTanya** [comment]
Поиск работает и по Id и по RUID корректно. Смену названия опции обсудите.

**Comment by gsbelarus** [comment]
я бы поменял, чтобы не возникало вопросов. даже так:

*Поиск функции по её ID или RUID*

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@ShlTanya , спасибо ! :trophy:
