### ISSUE TITLE
Параметр Множество ссылок

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4265]
В старом exe выбрано 841 подразделение... В новом при изменении данного параметра выдается ошибка. В старом все работает нормально... Желательно что бы записи отображались только те, которые попадают под условие, сейчас если я установил ограничение на подразделение то отображается еще и сама организация и папка в которую она входит, и я так подозреваю, что скорость вывода списка из-за этого стала существенно ниже... На базе с большим количеством контактов работать почти не возможно... Надо либо разобраться с запросом либо вернуть назад как было...

**Comment by gsbelarus** [comment]
Запрос надо погонять в окне SQL редактора или в IBExpert. Посмотреть план. Нет ли там NATURAL scan. Если будут вопросы с оптимизацией запроса, можно сюда писать -- будем искать варианты.

**Comment by NikolayUkleyko** [comment]
_> На базе с большим количеством контактов работать почти не возможно..._ 

Возможно пользователи забыли про такой функционал.

**Comment by MIchaelShoihet** [comment]
Исправлено. Заодно отчет оптимизирован

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, уточните — правки в актуальном .exe (http://gsbelarus.com/pw/downloads/gedemin-beta/gedemin-noid64/) ?
