### ISSUE TITLE
Бухгалтерия. Переход на новый месяц. Доработки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4266]
_**Исследователь → Бухгалтерия → Переход на новый месяц.**_

Предлагаемые доработки существующего функционала:

1. **Не формировать обратные проводки** для проводок отраженных с датой < даты перехода на новый месяц.
2. При попытке добавления, изменения и удаления проводок с датой < даты перехода на новый месяц **выводить следующее сообщение**:
```ruby
Выполнен переход на новый месяц (дата перехода на новый месяц).
Внесение изменений в бухгалтерские проводки до указанной даты заблокировано.
```

Далее, нажатие на кнопку Ok и выход.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, посмотри _http://gsbelarus.com/gs/wiki/index.php/Закрытие_периода_(постановка)_.

**Comment by NikolayUkleyko** [comment]
> _Не формировать обратные проводки для проводок отраженных с датой < даты перехода на новый месяц._

Я, так, понимаю, что для этого достаточно в таблице **AC_ENTRY** отключить триггер **AC_ENTRY_DO_BALANCE**.
Верно ли, @MIchaelShoihet ?

**Comment by Polfath** [comment]
Посмотрю

**Comment by NikolayUkleyko** [comment]
Необходимо в модифай включить новые триггеры **AC_BI_ENTRY_IN_BALANCE**, **AC_BUD_ENTRY_IN_BALANCE** с сообщениями в верной кодировке.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо ! :trophy:

**Comment by MIchaelShoihet** [comment]
В триггере надо сделать проверку на объединение записей
IF (RDB$GET_CONTEXT('USER_TRANSACTION', 'GD_MERGING_RECORDS') IS NULL) THEN

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
