### ISSUE TITLE
Ошибка в Типовой проводке

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4267]
При формировании типовой проводки есть скрипт инициализации. Сейчас код который там написан в окончательный скрипт не попадает.
Желательно что бы этот код попадал в самое начало скрипта.
Окно инициализации
![изображение](https://user-images.githubusercontent.com/11498750/163547149-6f201ec3-d668-40b9-b211-fa5559716001.png)
Скрипт
![изображение](https://user-images.githubusercontent.com/11498750/163547239-450f9eed-e701-4b20-b580-fdd49305b14b.png)

**Comment by ShlTanya** [comment]
Исправлено

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, здесь посмотрите, верно ли.
