### ISSUE TITLE
Окно подключенных пользователей

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4269]
![изображение](https://user-images.githubusercontent.com/11498750/163705640-1a8327ba-987e-4e86-809f-1e4d92fcb602.png)
При попытке сортировки по последней колонке выдается ошибка
![изображение](https://user-images.githubusercontent.com/11498750/163705663-0740be41-54ec-4cac-83ff-5e2a01fc86b7.png)
Что бы не листать весь список, хочется видеть сразу самую старую транзанкцию...

**Comment by ShlTanya** [comment]
Исправлено
