### ISSUE TITLE
Ввод счета в ЖО, карта-счета

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4271]
Такая тема уже была. Сейчас при вводе счета сразу идет поиск и настройка доступных аналитик, что приводит к паузе после ввода каждого символа, из-за чего срабатывает стандартная функциональность ComboBox который пытается найти и подставить счет из списка, что представляет большое неудобство. На данный момент я бы отказался от поиска и настройки и оставил, как было раньше ввели счет ушли с этого поля и только после этого настроили все... Второй вариант отказаться от ComboBox, но будут недовольные, некоторые пользуются именно выбором нужного счета из списка...

**Comment by NikolayUkleyko** [comment]
Пожалуйста, исходная тема https://github.com/GoldenSoftwareLtd/gedemin/issues/4243.

**Comment by NikolayUkleyko** [comment]
Это еще более ранняя тема https://github.com/GoldenSoftwareLtd/gedemin/issues/3766 по рассматриваемой доработке.

**Comment by NikolayUkleyko** [comment]
Возможно пользователи забыли про такой функционал.
Я подключался на рабочую БД ВПБФ — в ЖО в параметрах счета скачут.

**Comment by MIchaelShoihet** [comment]
Здесь надо поэксперементировать... Дело в том, что это стандартное поведение ComboBox. При наборе когда возникает пауза он подставляет последнее значение из списка. Когда после набора не было поиска аналитик, паузы не возникало, а сейчас с поиском возникает, вот он успевает подумать что надо искать.

**Comment by NikolayUkleyko** [comment]
Самое оптимальный вариант — ввели счет(а) и нажатие кнопки **Enter**.

**Comment by DonPhantom000** [comment]
При вводе текста в поле сделали задержку на 1 секунду с последнего нажатия, и только по прошествии этого времени данные обновляются. При нажатии Enter, переключении стрелками или мышью - всё как и раньше, т.е. обновляются немедленно. Хорошо бы вынести задержку в параметр, чтобы можно было её настраивать

**Comment by NikolayUkleyko** [comment]
> _Хорошо бы вынести задержку в параметр, чтобы можно было её настраивать_

Это будет замечательная настройка. :+1: 
Я понимаю, что можно будет задать большое значение такого параметра и будет, как, прежде без динамического обновления перечня аналитик.
Так ли ?

**Comment by gsbelarus** [comment]
не надо лишних параметров. увеличили задержку, проверили, если устраивает,
то так оставляем. никаких доп настроек делать не надо.

пт, 26 жні 2022, 13:36 карыстальнік NikolayUkleyko ***@***.***>
напісаў:

**Comment by gsbelarus** [comment]
надо перепроверить. и возможно вообще отказаться от таймера. оставить только ENTER. но, в чем смысл таймера, что если только ENTER оставлять, то при вводе счета висит аналитика ПРЕЖНЕГО счета. Это сбивает с толку. И в общем-то на экране выглядит как ошибка. Счет один, аналитика не его...

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.

**Comment by NikolayUkleyko** [comment]
Данную тему можно закрыть.
