### ISSUE TITLE
Бухгалтерия. Ахо. Неверно работает параметр "Не удалять результаты предыдущих расчетов"

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4274]
**Исследователь → Бухгалтерия → Автоматические хоз. операции.**

Выполняем исходный расчет по Ахо с выбранным параметром **Не удалять результаты предыдущих расчетов** — пустой результат.
Последующий запуск Ахо за аналогичный период также приводит к пустому результату.

Выполняем исходный расчет по Ахо без выбранного параметра **Не удалять результаты предыдущих расчетов** — результат с данными.
Последующий запуск Ахо за аналогичный период приводит к результату с данными.

**Такое предположение, что сейчас вышеприведенный параметр работает наоборот.**
Пожалуйста, поправьте.

Привожу сравнение скриптов **_без выбора параметра_** на разных gedemin.exe:

![image](https://user-images.githubusercontent.com/11497453/174066635-30861528-2de5-48ee-bd61-09270f9dc28a.png)
_(слева старый .exe, справа новый .exe)_

-----

Привожу сравнение скриптов **_с выбором параметра_** на разных gedemin.exe:

![image](https://user-images.githubusercontent.com/11497453/174067034-8af6e233-64f9-4f99-bc69-9f49d2d2adf2.png)
_(слева старый .exe, справа новый .exe)_

**Comment by MIchaelShoihet** [comment]
Проблема не в этом. Проблема в том что скрипт финализации формируется только один раз и потом не перфомировывается (так это скрипт и в него могут быть внесены изменения) а в нем сейчас сохранилась старая строка для отображения проводок 
usrg_gdcAcctEntryRegister1.ExtraConditions.Add("z.delayed = 1 AND r.id IN (SELECT entrykey FROM ac_autoentry WHERE trrecordkey = :trrecordkey)"), которая предполагает что сохраненные проводки по АИ создается всегда, а сейчас это не так,
эту строку надо поменять на новую
usrg_gdcAcctEntryRegister1.ExtraConditions.Add("z.delayed = 1 AND z.trrecordkey = :trrecordkey")
Надо будет написать автоматическое обновление этой строки...

**Comment by NikolayUkleyko** [comment]
Да, теперь работает верно.
@MIchaelShoihet , большое спасибо !
