### ISSUE TITLE
Общие. В таблицу MON$DATABASE добавить поле с датой создания архива базы данных

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4276]
В таблице MON$DATABASE предусмотрено поле MON$CREATION_DATE, отображающее дату и время восстановления из архива файла базы данных.
@gsbelarus , пожалуйста, подскажите, можно ли предусмотреть поле, например, MON$BACKUP_DATE, отображающее дату и время формирования архива файла базы данных ?
Смотрел и такой информации не нашел.
Возможно такая информация хранится в других таблицах ?

**Comment by gsbelarus** [comment]
Все таблицы мониторинга тут описаны. Мы туда не можем вмешаться.

https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref30/fblangref30-appx05-montables.html
