### ISSUE TITLE
Склонение ФИО 

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4277]
В FastReport4 есть ф-ция GETFIOCASE (фамилия, имя, отчество, пол, падеж) и в случае, когда у человека нет отчества кидается ошибка.  На самом деле есть случаи, когда по паспорту нет отчества. Реально ли доработать эту ф-цию?

**Comment by gsbelarus** [comment]
да. сегодня сделаю.

ср, 3 жні 2022, 11:34 карыстальнік Yury Rozmysl ***@***.***>
напісаў:

**Comment by gsbelarus** [comment]
проверить на новейшем экзешнике.

**Comment by YRozmysl** [comment]
теперь всегда отчество обрубается, есть оно или нет. А надо если есть, то как и было, а если отчества нет, то склонять имя и фамилия. 
[GETFIOCASE(<LINE."EMPLF">,<LINE."EMPLI">,<LINE."EMPLO">,<LINE."EMPLSEX">,3)] <LINE."EMPLO"> может быть пустым

**Comment by gsbelarus** [comment]
а теперь?

**Comment by YRozmysl** [comment]
теперь все ок
