### ISSUE TITLE
Общие. Хранилище. Сделать более крупную строку поиска

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4279]
**_Сервис → Хранилище → Поиск:_**

![image](https://user-images.githubusercontent.com/11497453/184095056-6ab4f55a-f392-45ec-b7d0-235ee5c0352c.png)

Пожалуйста, предусмотрите более вместительную и наглядную строку поиска.

**Comment by gsbelarus** [comment]
увеличить окно по высоте. надпись "Текст для поиска:" расположить над полем ввода поиска. Соответственно длину поля можно будет увеличить.

можно даже "текст для поиска" и поле взять в рамку и растянуть на всю ширину окна, а кнопки Найти, Закрыть опустить ниже на уровень рамки Просмотреть.

**Comment by Polfath** [comment]
Изменил форму в st_dlgFind_unit

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
![image](https://user-images.githubusercontent.com/11497453/189906699-b5037bb5-08de-4998-ba7b-9d1e25630c98.png)
@Polfath , спасибо !
