### ISSUE TITLE
Слетают права доступа после загрузки ПИ/настроек

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4280]
На бройлерах очень жалуются, что после каких-то действий (предполагают загрузку настроек или ПИ) слетают права доступа на отдельные ветки. При этом визуально они остаются, но не действуют, т.е. надо удалить нужную группу, сохранить и потом опять добавить

**Comment by NikolayUkleyko** [comment]
Могу предположить, такое подобное было на Витебск Мк, ГомельДреве.


чт, 11 авг. 2022 г., 12:17 MIchaelShoihet ***@***.***>:

**Comment by gsbelarus** [comment]
надо попробовать смоделировать, повторить у нас на офисе. для начала точно установить на какие ветки слетают и какие точно группы им приходится переназначать.

**Comment by gsbelarus** [comment]
И еще точно установить речь идет о ПИ или настройках.

**Comment by MIchaelShoihet** [comment]
Исправлено. Проблема была не в ПИ и настройках. А в самом исследователе. При изменении (либо просто переприсвоении) парента права брались из этой ветки, а в нашей идеологии это не правильно. Обычно возникало при редактировании типового документа, он менял ветку включая и парент.
