### ISSUE TITLE
Общие. Инспектор объектов. Увеличить диалоговое окно поиска объектов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4281]
**_Ctrl + Alt + M → Инспектор объектов → Поиск:_**

![image](https://user-images.githubusercontent.com/11497453/184675517-37e6a6bd-2f33-425a-b261-33da6fcc7a34.png)

Пожалуйста, предусмотрите более вместительную строку поиска и окно результата поиска.

**Comment by gsbelarus** [comment]
Окно смело можно делать раза в полтора шире и в два выше.

**Comment by DonPhantom000** [comment]
Увеличено. Может сделать его растяжимым?

**Comment by NikolayUkleyko** [comment]
> _Увеличено. Может сделать его растяжимым?_

Да.
На мой взгляд будет хорошо.

**Comment by Polfath** [comment]
Добавление возможности растягивания диалога "Поиск  объектов"

**Comment by Polfath** [comment]
> Добавление возможности растягивания диалога "Поиск объектов"

Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
