### ISSUE TITLE
Общие. Таблицы. При последовательном добавлении полей не работает кнопка ”Новый”

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4282]
При добавлении в таблицу поля при помощи кнопки **Новый** после нажатия на кнопку **_OK_** добавляется только одной предыдущее поле.
В результате при добавлении ряда полей они не сохраняются.
Пожалуйста, сделайте неактивной или скройте кнопку **Новый**.

**Comment by DonPhantom000** [comment]
Сделано

**Comment by gsbelarus** [comment]
я бы не кнопку скрывал, а разобрался почему не работает. Потому что в стандартном варианте Новый как раз внутри себя и вызывает Ок и потом создает новую запись. Т.е. все должно работать как и при кнопке Ок.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , с кнопкой **Новый** не так все однозначно.
Одно дело, когда применяем кнопку **Новый** при работе с данными по документам, а другое – при работе с метаданными (создание внешних ключей, индексов).

Могу предположить, что описываемое поведение кнопки **Новый** при добавлении полей в таблицу появилось в **gedemin.exe** несколько лет назад.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
Доработки по данной теме не вошли в **gedemin.exe Delphi 7**.
@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
