### ISSUE TITLE
Общие. Формы. При сворачивании окна настройки хранилища выполняется ее закрытие

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4284]
**_Сервис → Хранилище._**

При сворачивании окна настройки хранилища выполняется ее закрытие.
Были открыто несколько окон настройки хранилища, введены параметры поиска, после сворачивания они закрылись.
Пожалуйста, подскажите можно ли поправить ?

**Comment by DonPhantom000** [comment]
Сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@DonPhantom000 , спасибо ! :trophy:
