### ISSUE TITLE
Настройки ЭТТН не добавляются в ПИ

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4285]
При добавлении настроек ЭТТН в пространство имен - ошибка

![image](https://user-images.githubusercontent.com/11497358/185340484-dd504da9-f2df-44a2-b710-4345a72fb4be.png)

![image](https://user-images.githubusercontent.com/11497358/185341539-c07c5ed3-01ea-4df5-a74b-8dd12371c90a.png)

**Comment by NikolayUkleyko** [comment]
Решение вопроса:
1. В таблице **AT_OBJECT** поле **OBJECTNAME** является обязательным для заполнения.
2. При просмотре свойств добавляемой записи в таблице **USR$ETTN_TTN_IN_SETTINGS** следует обратить внимание на отсутствие наименования в реквизите **Наименование**:
![image](https://user-images.githubusercontent.com/11497453/185385375-2cceaf54-ceef-4f89-b9ed-52e5d4c29240.png)
3. В таблицу добавляем текстовое поле.
4. Заполняем такое поле.
5. Просматриваем свойства записи:
![image](https://user-images.githubusercontent.com/11497453/185385813-2e205303-fae9-4c83-a9bc-c1ca405fad26.png)
6. Добавляем запись в ПИ.
7. Ошибок нет и запись в ПИ успешно добавлена:
![image](https://user-images.githubusercontent.com/11497453/185386300-760aad38-c297-4752-9cb7-4fd0024503cd.png)

:ok_hand::ok_hand::ok_hand::ok_hand::ok_hand:

**Comment by alexandra-gsoftware** [comment]
Это да, но по-хорошему экзе должен был сам дать имя этой штуке. Загнать в имя ид, если ничего похожего на имя нет...

**Comment by NikolayUkleyko** [comment]
_> Это да, но по-хорошему экзе должен был сам дать имя этой штуке. Загнать в имя ид, если ничего похожего на имя нет..._

Да, Александра, как вариант.

**Comment by gsbelarus** [comment]
посмотрим. вроде так и должен был, если нет текстового поля. скорее всего
там руид должен был быть, но потом начали борьбу с лишними руидами и
наверное выкинули.

чц, 18 жні 2022, 14:55 карыстальнік NikolayUkleyko ***@***.***>
напісаў:

**Comment by NikolayUkleyko** [comment]
С РУИДами понятно.
Тогда, добавлять ID, название таблицы.

**Comment by yoannawx** [comment]
1. Позиция настройки входящих эттн добавилась корректно (Настройки входящих ТТН, РУИД: 151877374_623967871)

![image](https://user-images.githubusercontent.com/11497358/187648423-08ffe35d-c28f-48ee-a6b3-25edfb4cf70f.png)

но при этом не подтянулись зависимости (как минимум, ПИ: Электронный документооборот.Настройки входящих ЭТТН, в которое входит subtype USR$ETTN_TTN_IN_SETTINGS)

![image](https://user-images.githubusercontent.com/11497358/187648276-4c52d6a8-3724-465f-82a9-df027827f0c8.png)


2. Позиция настройки исходящих эттн добавилась со странным наименованием 

![image](https://user-images.githubusercontent.com/11497358/187646925-334d52d4-fe23-4cd7-ad7d-b09e549dc7b0.png)

зависимости тоже не подтянулись

![image](https://user-images.githubusercontent.com/11497358/187655086-cfa34e6c-6319-47aa-9fe9-5d38d85ea86e.png)

**Comment by gsbelarus** [comment]
Добавьте туда поле с наименованием USR$NAME. Приходится выдумывать имя объекта из имени класса и прочей ерунды.

**Comment by gsbelarus** [comment]
"Позиция настройки исходящих эттн добавилась со странным наименованием" -- это не странное наименование. Так как наименования нет, система начинает искать хоть какое текстовое поле и находит вот с таким значением. Ничего нельзя сделать пока не будет в таблице нормального поля с именем записи.

**Comment by gsbelarus** [comment]
а насчет механизма зависимостей, его никто не трогал. проверьте еще раз.

**Comment by NikolayUkleyko** [comment]
_> Добавьте туда поле с наименованием USR$NAME. Приходится выдумывать имя объекта из имени класса и прочей ерунды._

Про такой вариант я Жанне говорил.
Наличие поля типа **NAME** логично.
Может быть использовано для хранения наименования или описания к таблице (справочнику).

**Comment by gsbelarus** [comment]
В документацию добавить обязательное требование наличия поля NAME или USR$NAME для объектов, добавляемых в ПИ. Возможно, при добавлении стоит проверять в программе и при отсутствии такого поля -- предупреждать и останавливать добавление.

**Comment by NikolayUkleyko** [comment]
> _”…при добавлении стоит проверять в программе и при отсутствии такого поля -- предупреждать и останавливать добавление.…”_

Хороший вариант.

**Comment by NikolayUkleyko** [comment]
Рассмотрение данной темы продолжено в теме https://github.com/GoldenSoftwareLtd/gedemin/issues/3915.
Данную можно закрыть.
