### ISSUE TITLE
загрузка ПИ. Неизвестное имя.

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4286]
Делалась разработка на клиентской базе для табеля мастера. Все работает там, проблем нет. Я решил перенести эту доработку в гит. Сформировал настройку ПИ, которую загрузил на  чистую эталонную базу с уже установленной  настройкой по ЗПиОк.
При загрузке ПИ ошибок не было. Однако при добавлении документа табеля мастера вот такая ошибка. С чем это связано и куда тут надо копать, что искать?
![Screenshot 2022-08-18 111748](https://user-images.githubusercontent.com/11507129/185346106-24bdb302-892f-4fb7-bfad-915ced9ad9d2.png)

**Comment by NikolayUkleyko** [comment]
Предполагаемо вопрос по хранилищу (гридам).
@YRozmysl , проверяй <ins>тщательно</ins> по данному документу все ли объекты хранилища (Administrator) добавлены в ПИ.

**Comment by YRozmysl** [comment]
По итогу, каких-то  поисков и  переформированию  Пи  все равно пришел к тому же.

![Screenshot 2022-08-18 143240](https://user-images.githubusercontent.com/11507129/185385282-8cfedcda-62e7-4649-8620-b7e08600bd5f.png)

**Comment by gsbelarus** [comment]
а можешь кнопку details нажать и раскрыть стек вызовов?

чц, 18 жні 2022, 13:34 карыстальнік Yury Rozmysl ***@***.***>
напісаў:

**Comment by YRozmysl** [comment]
Call stack:
:009ABB9F [gedemin.exe] TgdScriptFactory::ExecuteFunctionEx (gd_ScriptFactory.pas, line 536)
:7724CA42 [KERNELBASE.dll]
Recursive call (3 times):
:009ABB9F [gedemin.exe] TgdScriptFactory::ExecuteFunctionEx (gd_ScriptFactory.pas, line 536)
:009AC33E [gedemin.exe] TgdScriptFactory::ExecuteFunction (gd_ScriptFactory.pas, line 664)
:00653AF4 [gedemin.exe] TMethodControl::ExecuteMethodNew (mtd_Base.pas, line 1222)
:00DC04A2 [gedemin.exe] TgdcBase::GetWhereClause (gdcBase.pas, line 6318)
:00DC0223 [gedemin.exe] TgdcBase::GetSelectSQLText (gdcBase.pas, line 6270)
:00DC0970 [gedemin.exe] TgdcBase::InitSQL (gdcBase.pas, line 6392)
:00DBBF8F [gedemin.exe] TgdcBase::DoBeforeOpen (gdcBase.pas, line 5248)
:004F92E4 [gedemin.exe] TDataSet::SetActive (DB.pas, line 8240)
:00592B5F [gedemin.exe] TIBCustomDataSet::SetActive (IBCustomDataSet.pas, line 5937)
:00D2467E [gedemin.exe] TgdcUserBaseDocument::SetActive (gdcClasses.pas, line 3457)
:77CE4E9D [ntdll.dll]
:0041A1F0 [gedemin.exe] TList::Add (Classes.pas, line 1818)
:00E8F132 [gedemin.exe] TIBTransaction::AddSQLObject (IBDatabase.pas, line 1927)
:00402B81 [gedemin.exe] ReallocMem
:0041A7BB [gedemin.exe] TList::SetCapacity (Classes.pas, line 1985)
:0041A1F0 [gedemin.exe] TList::Add (Classes.pas, line 1818)
:00425C5C [gedemin.exe] TComponent::FreeNotification (Classes.pas, line 7521)
Recursive call (2 times):
:00425C79 [gedemin.exe] TComponent::FreeNotification (Classes.pas, line 7524)
:004F9160 [gedemin.exe] TDataSet::Open (DB.pas, line 8203)
:00DCC339 [gedemin.exe] TgdcDataLink::ActiveChanged (gdcBase.pas, line 9374)
:004F5590 [gedemin.exe] TDataLink::SetActive (DB.pas, line 6686)
:004F55EA [gedemin.exe] TDataLink::UpdateState (DB.pas, line 6701)
:004F57B5 [gedemin.exe] TDataLink::DataEvent (DB.pas, line 6762)
:004F60AC [gedemin.exe] TDataSource::NotifyLinkTypes (DB.pas, line 7050)
:004F60DB [gedemin.exe] TDataSource::NotifyDataLinks (DB.pas, line 7056)
:004F5E36 [gedemin.exe] TDataSource::SetState (DB.pas, line 6979)
:004F5EA5 [gedemin.exe] TDataSource::UpdateState (DB.pas, line 6992)
:004FAB0B [gedemin.exe] TDataSet::AddDataSource (DB.pas, line 8864)
:004F5F92 [gedemin.exe] TDataSource::SetDataSet (DB.pas, line 7017)
:00D148A7 [gedemin.exe] Tgdc_dlgUserComplexDocument::SetupDialog (gdc_dlgUserComplexDocument_unit.pas, line 220)
:00D44302 [gedemin.exe] Tgdc_dlgG::Setup (gdc_dlgG_unit.pas, line 379)
:00DB9719 [gedemin.exe] TgdcBase::CreateDialog (gdcBase.pas, line 4574)
:00DD14AD [gedemin.exe] TgdcBase::CreateDialog (gdcBase.pas, line 10775)
:7685F6B7 [USER32.dll]
:00D1C50F [gedemin.exe] TgdcDocument::GetCanCreate (gdcClasses.pas, line 1792)
:00D1C5EA [gedemin.exe] TgdcDocument::GetCanCreate (gdcClasses.pas, line 1792)
:7685F760 [USER32.dll]
:77CE2A0C [ntdll.dll]
:7686FA66 [USER32.dll]
:76867ACA [USER32.dll]
:0045E31D [gedemin.exe] TControl::WMLButtonDown (Controls.pas, line 4316)
:005E4902 [gedemin.exe] GetMessageHook (TB2Hook.pas, line 138)
:7686B5F6 [USER32.dll]
:004611DE [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5615)
:7686B449 [USER32.dll]
:004277AF [gedemin.exe] TObjectList::GetItem (Contnrs.pas, line 167)
:004279FF [gedemin.exe] TComponentList::GetItems (Contnrs.pas, line 237)
:0060252F [gedemin.exe] TTBCustomToolbar::MouseDown (TB2Toolbar.pas, line 1070)
:00DD1397 [gedemin.exe] TgdcBase::CreateDescendant (gdcBase.pas, line 10753)
:0045E31D [gedemin.exe] TControl::WMLButtonDown (Controls.pas, line 4316)
:005E4902 [gedemin.exe] GetMessageHook (TB2Hook.pas, line 138)
:7686B5F6 [USER32.dll]
:004611DE [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5615)
:7686B449 [USER32.dll]
:004277AF [gedemin.exe] TObjectList::GetItem (Contnrs.pas, line 167)
:004279FF [gedemin.exe] TComponentList::GetItems (Contnrs.pas, line 237)
:00CBE2ED [gedemin.exe] Tgdc_frmG::actNewExecute (gdc_frmG_unit.pas, line 502)
:008C7587 [gedemin.exe] Tgdc_frmMDHGR::actNewExecute (gdc_frmMDHGR_unit.pas, line 543)
:00426BA8 [gedemin.exe] TBasicAction::Execute (Classes.pas, line 8077)
:00472F44 [gedemin.exe] TContainedAction::Execute (ActnList.pas, line 321)
:00473C62 [gedemin.exe] TCustomAction::Execute (ActnList.pas, line 708)
:004038D5 [gedemin.exe] CallDynaInst
:004269FD [gedemin.exe] TBasicActionLink::Execute (Classes.pas, line 8012)
:005F54E2 [gedemin.exe] TTBCustomItem::Click (TB2Item.pas, line 1475)
:005F53C7 [gedemin.exe] TTBCustomItem::ClickWndProc (TB2Item.pas, line 1424)
:00449526 [gedemin.exe] StdWndProc (Forms.pas, line 1459)
:76870F1B [USER32.dll]
:76867ECA [USER32.dll]
:77CE2A0C [ntdll.dll]
:7686B3C6 [USER32.dll]
:76867CDE [USER32.dll]
:76865C3A [USER32.dll]
:76857DC0 [USER32.dll]
:00455085 [gedemin.exe] TApplication::ProcessMessage (Forms.pas, line 6630)
:004550CC [gedemin.exe] TApplication::HandleMessage (Forms.pas, line 6649)
:00455352 [gedemin.exe] TApplication::Run (Forms.pas, line 6732)
:00455376 [gedemin.exe] TApplication::Run (Forms.pas, line 6736)
:011BD790 [gedemin.exe] initialization (gedemin.dpr, line 734)
:011BD7AA [gedemin.exe] initialization (gedemin.dpr, line 744)
:011BD7C9 [gedemin.exe] initialization (gedemin.dpr, line 746)
:75D5FA29 [KERNEL32.DLL]
:77CD7A9E [ntdll.dll]
:77CD7A6E [ntdll.dll]

Modules:
$00400000 (00400000,00001000,00DBCA00) C:\Gedemin\gedemin.exe
$77120000 (77120000,00001000,001DB600) C:\WINDOWS\System32\KERNELBASE.dll
$77C70000 (77C70000,00001000,00120200) C:\WINDOWS\SYSTEM32\ntdll.dll
$76830000 (76830000,00001000,000A3600) C:\WINDOWS\System32\USER32.dll
$75D40000 (75D40000,00010000,00065000) C:\WINDOWS\System32\KERNEL32.DLL

**Comment by alexandra-gsoftware** [comment]
может, тупо база повреждена как раз в том месте, где хранилище формы лежит?

**Comment by alexandra-gsoftware** [comment]
@YRozmysl можешь скинуть пи это?

**Comment by YRozmysl** [comment]
снималось с бройлеров и пыталось перенестись на эталон.

**Comment by YRozmysl** [comment]
> @YRozmysl можешь скинуть пи это?

лови в телеге

**Comment by gsbelarus** [comment]
ясно. это ошибка при вызове какой то скрипт функции. но все равно должно
более понятно выводиться.

чц, 18 жні 2022, 15:30 карыстальнік Yury Rozmysl ***@***.***>
напісаў:

**Comment by alexandra-gsoftware** [comment]
разобралісь. на базе бро у одного із документов другой руід.

**Comment by gsbelarus** [comment]
Все равно сообщение должно быть более понятное.

**Comment by gsbelarus** [comment]
В исходниках гедымина такого сообщения нет. Значит это что-то в макросах.
