### ISSUE TITLE
Функция SUMCURRSTR2 возвращает результат в нижнем регистре

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4287]
Например, в справочнике валют указано "долларов США", а функция возвращает результат "долларов сша".

**Comment by DonPhantom000** [comment]
Сделано

**Comment by gsbelarus** [comment]
преобразования выполняются в модуле gd_convert в функции UpdateCache. Там все строки в нижний регистр приводятся.

есть вариант убрать приведение, тогда будет браться ровно так, как записано в справочнике. кому надо маленькими буквами, получит маленькими, кому большими -- введет в справочник большими.

но, этот вариант затронет всех существующих клиентов. Им надо будет пойти в справочник и откорректировать, так как скорее всего везде набрано с заглавной название валюты. Например, Доллар США.

Как делаем?

**Comment by AliakseiDanilchyk** [comment]
Я считаю, надо убрать приведение. Печатать как в справочнике. В стандартных ПИ у нас наименования валют в родительном падеже внесены с маленькой буквы, а именительный - с большой.
А доллар США в этом ПИ у нас вообще обозвали "американских долларов"/"американских доллара"

**Comment by NikolayUkleyko** [comment]
> _Как делаем?_

Добавить новое поле для хранения наименований валют в оговариваемом здесь формате.
Существующие отчеты и прочее не поменяются.
В новых отчетах и других объектах выполнить соответствующую настройку согласно нового реквизита без приведения строк в нижний регистр.
Возможно возникнет необходимость добавить новую функцию **SUMCURRSTR3**.

**Comment by gsbelarus** [comment]
будем брать как есть в справочнике и все. люди зайдут поменяют где надо

**Comment by Polfath** [comment]
убрал приведение к нижнему регистру в gd_convert

**Comment by gsbelarus** [comment]
нет. никаких полей добавлять не будем

**Comment by gsbelarus** [comment]
Перепроверить и закрыть. Окончательное решение не трогать регистр и выводить как введено в базе данных.

**Comment by NikolayUkleyko** [comment]
@AliakseiDanilchyk , пожалуйста, посмотри.
