### ISSUE TITLE
Общие. Добавление в отмеченные. Некорректное добавление записей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4288]
Не первый раз наблюдаю, что при добавлении в отмеченные добавляются лишние записи.

**Comment by NikolayUkleyko** [comment]
@DonPhantom000 , пожалуйста, посмотри.

**Comment by gsbelarus** [comment]
нужен конкретный пример

**Comment by NikolayUkleyko** [comment]
Пример, задача добавить в отмеченные следующие ПИ:

- Мат_склад - отчеты;
- Рублевые банковские документы 10;
- Рублевые банковские документы 20.

При их поиске через **бинокль** и последующем добавлении в отмеченные добавляются лишние ПИ.
При их поиске через автофильтр и/или горячие клавиши **Ctrl+F** в отмеченные лишние ПИ не добавляются.

**Comment by Polfath** [comment]
Дефект подтвердился. Посмотрю.

**Comment by Polfath** [comment]
Поправил

**Comment by gsbelarus** [comment]
@NikolayUkleyko проверь и закрой

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
