### ISSUE TITLE
Некорректное отображение товара на дисплее покупателя в ПО POSitive Cash

### ISSUE THREAD

**Issue by supportkkc** [GoldenSoftwareLtd/gedemin#4291]
Скачивал установщик POSitive Cash 24.08.2022 и устанавливал у клиента. 
Дисплей покупателя ATOL PD 2800 USB (Virtual COM Mode) https://clck.ru/vtQSF
Дисплей имеет две строки, но товар отображается только в одной.
При этом Итоговая сумма чека и "Добро Пожаловать!" используют две строки.

![image](https://user-images.githubusercontent.com/20512230/187188193-903faba2-0699-47a2-9ad6-1b8d2f93f12a.png)
![image](https://user-images.githubusercontent.com/20512230/187188232-68bb1bff-da02-40d1-b3b9-c913e151103d.png)

https://user-images.githubusercontent.com/20512230/187188506-ff4f7d24-735f-4a94-9e7f-20f78d884e73.mp4
![image](https://user-images.githubusercontent.com/20512230/187188535-b8f28e32-7c03-4a9c-a0eb-9720bfe7b153.png)
![image](https://user-images.githubusercontent.com/20512230/187188566-f6ea316b-7fec-4a08-8742-f95d2e718827.png)

**Comment by hirurg-lybitel** [comment]
Абсолютно неожиданное место для подобных вопросов.
Вроде же все знают, что по кассовым решениям есть отдельный репозиторий [check-and-cash](https://github.com/gsbelarus/check-and-cash/issues?q=is%3Aopen+is%3Aissue).

Туда и переношу этот вопрос
