### ISSUE TITLE
Отчеты. Макросы. Предусмотреть цветовое выделение записей не отображаемых в меню

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4293]
_Редактор скрипт-объектов → Макросы, Отчеты._

1. Для удобства и быстроты систематизации отчетов, макросов, пожалуйста, предусмотрите цветовое выделение записей не отображаемых в меню:
![image](https://user-images.githubusercontent.com/11497453/187214679-4472ad4d-2699-4dfe-80a7-135e5e2473cf.png)

Для записей, не отображаемых в меню предусмотреть синий цвет шрифта или другие варианты.

-----

2. Хорошо бы предусмотреть сортировку.
Сперва, сортировка по признаку отображения/не отображения в меню, затем, по наименованию.

Сейчас для выделения таких записей (можно сказать "отключенных") добавляем различные символы и т.д.

**Comment by gsbelarus** [comment]
сортировка будет сложно. цвет проще. но, самое простое это для невидимых отчетоы/макросов другую пиктограммку выводить. не желтую, а, например, серую.

**Comment by NikolayUkleyko** [comment]
_> сортировка будет сложно. цвет проще. но, самое простое это для невидимых отчетоы/макросов другую пиктограммку выводить. не желтую, а, например, серую._

Хорошо.
Пожалуйста, просто выводите черно-белую пиктограммку для неактивных отчетов и макросов.

**Comment by NikolayUkleyko** [comment]
![image](https://user-images.githubusercontent.com/11497453/188485831-3207d40d-1182-495f-95c6-dfe442986e51.png)

Проверено.
Замечательно !
Работает корректно.
Небольшое пожелание — можно ли для <ins>выбранных</ins> записей не отображаемых в меню сделать шрифт немного контрастнее ?

**Comment by NikolayUkleyko** [comment]
@yoannawx посмотрела следующее:
1. При копировании и вставке отчетов, макросов с выбранной галкой отображения в меню цвет шрифта серый.
После обновления (**F5**) списка отчетов, макросов цвет шрифта стандартный.

2. При добавлении отчетов, макросов в ПИ, настройку с выбранной галкой отображения в меню цвет шрифта серый.
После обновления (**F5**) списка отчетов, макросов цвет шрифта стандартный.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, поправьте, если, можно следующее:
1. Для выделенных мышкой записей не отображаемых в меню сделать шрифт немного контрастнее. Название не читается.
2. При добавлении, копировании отчетов, макросов в ПИ и/или настройку с выбранной галкой отображения в меню цвет шрифта серый. Необходимо установить стандартный цвет.

**Comment by NikolayUkleyko** [comment]
@yoannawx просит посмотреть данную тему.

**Comment by NikolayUkleyko** [comment]
Актуальный **_gedemin.exe_** и рабочая база данных Береза Мкк.
Не читается наименование отчета:
![image](https://user-images.githubusercontent.com/11497453/197148043-508c6e43-1f7d-4dbd-b56a-91afbaba9771.png)

@gsbelarus , пожалуйста, поправьте https://github.com/GoldenSoftwareLtd/gedemin/issues/4293#issuecomment-1269919516.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !

**Comment by NikolayUkleyko** [comment]
![image](https://user-images.githubusercontent.com/11497453/230125689-971f424d-eab6-4978-bac9-c5a9b3f031ba.png)

_”Серым выделяются отчеты, которые отключены? Странное поведение, отключаю один, серым становится не только он, но и другой, хоть у него стоит галка Отображать в меню отчетов. Переподключаюсь к базе, становится нормально.”_

**Comment by Polfath** [comment]
Баг не воспроизводится. Работает корректно

**Comment by NikolayUkleyko** [comment]
Проверено.
Не моделируются вышеприведенные недочеты.
Работает корректно.
@Polfath , спасибо !
