### ISSUE TITLE
визуальные настройки  в диалоговой  форме документов (кнопки)

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4294]
На последнем exe в диалоговых формах документов вот так
![Безымянный](https://user-images.githubusercontent.com/11507129/187230128-688f8b3a-cf62-45e5-90f7-35d3e3fc6723.jpg)

**Comment by YRozmysl** [comment]
на версии exe **2.9,5.12253** еще было все ок

**Comment by gsbelarus** [comment]
это кто-то преобразовал dfm в utf 8. я видел несколько таких. теперь только отлавливать и из старых комитов выковыривать. опять-таки следствие проблемы когда 80 файлов идут в один пул реквест и трудно понять что есть что.

**Comment by gsbelarus** [comment]
Должно исправиться с возвратом к старым исходникам.
