### ISSUE TITLE
Общие. Новый gedemin.exe в Исследователь к пиктограммкам добавляет лишние символы

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4295]
_Исследователь._

![image](https://user-images.githubusercontent.com/11497453/187385185-fbf34c0f-0852-4212-a807-0fc488215c1b.png)

Раньше такого не было.
@gsbelarus , пожалуйста, поправьте.

**Comment by gsbelarus** [comment]
можно закрывать?

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@gsbelarus , спасибо !
