### ISSUE TITLE
Бухгалтерия. Карта счета и другие. После обновления gedemin.exe появились вопросы по формам

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4296]
_Исследователь → Бухгалтерия → Журнал-ордер, Карта счета, Оборотная ведомость, Анализ счета, Главная книга._

![image](https://user-images.githubusercontent.com/11497453/187417749-450456ed-29e6-4fc1-acc8-ad692c19f037.png)

Высвеченные кнопки.
Проведите курсором.
![image](https://user-images.githubusercontent.com/11497453/187417843-36bd53df-d114-464b-8e7a-620968827868.png)

Позже это пропадает.
Раньше такого не было.

**Comment by NikolayUkleyko** [comment]
Пожалуйста, поправьте здесь.

**Comment by gsbelarus** [comment]
что пропадает? что не так? из написанного не понятно

**Comment by NikolayUkleyko** [comment]
_> что пропадает? что не так? из написанного не понятно_

1. При первом открытии форм в правой части на панели инструментов темная полоса.
2. На панели инструментов значки неактивные, бесцветные.
Достаточно провести курсором, чтобы значки деактивировались.

**Comment by gsbelarus** [comment]
можно закрывать? исходники мы откатили

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@gsbelarus , спасибо !
