### ISSUE TITLE
обновление exe  и дата файла

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4298]
При обновлении exe билд видно, что поменялся на актуальный, а дата файла осталась прежней. так и должно быть? При автоматическом обновлении, что происходит с прежним файлом?

![555](https://user-images.githubusercontent.com/11507129/187540148-aa998fee-7f3c-4349-aa53-b22762c550d1.jpg)

**Comment by gsbelarus** [comment]
да. странно. но номер версии ок. надо посмотреть какая дата на s5. может на сераерн часы неправильно идут.

**Comment by YRozmysl** [comment]
так получается только если автоматически  обновляется, а если принудительно скачать файл с сайта и руками заменить его, то дата правильная. Может это в винде у меня что-то.

**Comment by YRozmysl** [comment]
странная какая-то хронология.

![Screenshot 2022-08-31 093433](https://user-images.githubusercontent.com/11507129/187610097-9ebaf4d1-4de3-4214-989c-5f8df174f1a5.png)

**Comment by gsbelarus** [comment]
мы даты файла нигде не устанавливаем. это все ОС шалит.
