### ISSUE TITLE
& _     VS    & vbCrLf & _

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4301]
Это как пожелание  и просто спросить. Можно ли, при копировании и вставке SQL запроса в макрос сделать, чтобы вставлялось, не так
![Screenshot 2022-09-02 120328_old](https://user-images.githubusercontent.com/11507129/188105144-65d30623-fc75-45eb-8310-8d3ae617fc82.png)
 а вот так
![Screenshot 2022-09-02 120454_now](https://user-images.githubusercontent.com/11507129/188105190-3162d3e9-b5c2-4f3c-ae63-3ebbeee6304e.png)

Мне, кажется, что так удобнее было бы и копировать запрос из макроса в SQL редактор. Особенно большие запросы, которые потом надо  SQL приводить к визуально удобному виду. Нет?

**Comment by YRozmysl** [comment]
я вот про это имею ввиду 
![Безымянный](https://user-images.githubusercontent.com/11507129/188106428-21d3eb61-dbd4-44bd-9f45-97ebf6f5d984.jpg)

**Comment by MIchaelShoihet** [comment]
Поддерживаю

**Comment by NikolayUkleyko** [comment]
@YRozmysl , разница в переносе на новую строку:
```ruby
& _
и
& vbCrLf & _
```

**Comment by YRozmysl** [comment]
Все хорошо. Работает
