### ISSUE TITLE
Улучшения по добавлению контактов в группу 

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4302]
* [x] При нажатии на кнопку добавления записей в группу и хорошо бы для удобства выбора 2-х и более записей предусмотреть CheckBox. Так реализовано при редактировании группы и выборе записей.
* [x] При удалении записи из группы немного поправить сообщение:  *Сама запись удалена не будет → Запись останется в базе данных.*

**Comment by Polfath** [comment]
сделано

**Comment by NikolayUkleyko** [comment]
Проверено.
В целом функционал работает корректно.
Возможны некоторые правки.

**Comment by gsbelarus** [comment]
какие?

**Comment by NikolayUkleyko** [comment]
_> какие?_

При смещения грида при попытке удаления записи (контакта) появляется следующее сообщение:
![image](https://user-images.githubusercontent.com/11497453/201297234-dbd1bafd-a082-4f25-a002-bae6e5729bde.png)
Группа не определяется.
При попытке удаления запись не удаляется.
Решили в такой ситуации делать неактивной команду удаления записи.

-----

В исходном режиме при нажатии на клавишу удаления записи (контакта) появляется следующее сообщение:
![image](https://user-images.githubusercontent.com/11497453/201297409-ba975f87-6cb9-4d10-b846-3d00b0f6d0d8.png)
Группа определяется.
При попытке удаления запись удаляется корректно.

**Comment by gsbelarus** [comment]
Надо поправить.

**Comment by Polfath** [comment]
так попросил сделать @NikolayUkleyko 
Вернуть как было?

**Comment by Polfath** [comment]
поправил

**Comment by gsbelarus** [comment]
Не TgdcGroup должно быть, а название группы.

**Comment by NikolayUkleyko** [comment]
Проверено.
@Polfath , пожалуйста, посмотри следующее:
1. При смещении грида отображаем все дочерние записи по всем группам.
2. При попытке удаления дочерней записи по группе <ins>иногда (через раз)</ins> программа отображает окно с сообщением об ошибке:
![image](https://user-images.githubusercontent.com/11497453/202437656-ccbbb114-0e22-491c-9fc4-05f4f66d1527.png)
3. Поправить сообщение при добавлении дочерних записей.

**Comment by gsbelarus** [comment]
тут надо добавить проверку, что для оператора IN есть какие то ИД. если нет, то и запрос не стоит выполнять.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

@gsbelarus , пожалуйста, закройте тему.
