### ISSUE TITLE
Общие. Добавить горячую команду для приведения Исследователя к исходному состоянию

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4303]
При подключении к БД по RDP часто открыто немало документов, форм и т.д., что не видно верхней панели инструментов Гедымина.
В такой ситуации удобно последовательное применение следующих команд:

1. **Shift+Ctrl+F4** — закрытие всех окон.
2. **Ctrl+F11** — переключение на Исследователь.
3. **Ctrl+Q** — закрытие всех деревьев.

Возможно ли добавление горячих клавиш (например, **Ctrl+F12**) для выполнения таких команд друг за другом в приведенной очередности ?
В результате для приведения Исследователя к исходному состоянию будет достаточно одной команды.

**Comment by Polfath** [comment]
Посмотрю

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает замечательно.
@Polfath , большое спасибо !
