### ISSUE TITLE
Общие. Сервис → Параметры. Пересохранить форму на закладке 'Общие'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4304]
_**Сервис → Параметры.**_

Сейчас по умолчанию открывается закладка **Аудит и безопасность**:
![image](https://user-images.githubusercontent.com/11497453/189649196-bd9d56e2-9599-48fd-b425-74796ef7727f.png)

Пожалуйста, пересохраните форму на закладке **Общие**.

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста, поправь.

**Comment by Polfath** [comment]
Поменял

**Comment by gsbelarus** [comment]
проверяйте, пожалуйста, такие вещи перед комитом. прямо в тексте DFM файла TortoiseGit покажет вам что изменилось и вы сразу поймете что это правильное изменение или случайное. Если не знаете как, спросите меня. Это уже не первый раз, когда неверный DFM идет в комит. Вообще, если в DFM ничего специально не менялось, то скидывать его не надо. Делайте REVERT.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
