### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Перестала работать команда 'Дубликат'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4305]
_**Исследователь → Бухгалтерия → Журнал хоз. операций.**_

![image](https://user-images.githubusercontent.com/11497453/189676919-220d5702-60d2-4c75-bbf6-eacdb0da1460.png)
![image](https://user-images.githubusercontent.com/11497453/189676945-6b69f669-442b-4e60-8f5d-3cb03cedb599.png)

Пожалуйста, восстановите работоспособность стандартной команды **Дубликат (Ctrl+D)**.

**Comment by gsbelarus** [comment]
Поскольку раньше работало, то я бы сравнил PAS и DFM файлы с предыдущей версией и попытался понять из-за чего отвалилось. Возможно в DFM просто action отвалился.

**Comment by Polfath** [comment]
В actDetailDuplicateExecute не было inherited

**Comment by gsbelarus** [comment]
Дубликат: https://github.com/GoldenSoftwareLtd/gedemin/issues/4308

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
