### ISSUE TITLE
Фильтры. Ошибка при выборе команды 'Создать' и 'Изменить'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4306]
На любом документе, справочнике и т.д. открываем меню фильтров:
![image](https://user-images.githubusercontent.com/11497453/189680304-66d54e05-545e-4137-8941-b1af903b15e8.png)
![image](https://user-images.githubusercontent.com/11497453/189680343-7651a93a-a866-4988-a88e-ddee344fb5fc.png)
![image](https://user-images.githubusercontent.com/11497453/189680360-d32aaeb9-bbba-498f-8975-18255e75abdf.png)
![image](https://user-images.githubusercontent.com/11497453/189680656-ddcd02fd-c5fb-496b-b45e-00b4a0fbce1d.png)

-----
Call stack:
:004045F4 [gedemin.exe] LStrAsg
:005323D6 [gedemin.exe] TTreeNode::SetText (ComCtrls.pas, line 6150)
:00402B16 [gedemin.exe] GetMem
:00404688 [gedemin.exe] LStrFromPCharLen
:00E60E7D [gedemin.exe] TdlgShowFilter::ShowFilter (flt_dlgShowFilter_unit.pas, line 1880)
:00441F33 [gedemin.exe] TCustomCheckBox::Click (StdCtrls.pas, line 3016)
:00442023 [gedemin.exe] TCustomCheckBox::SetState (StdCtrls.pas, line 3045)
:00E6037B [gedemin.exe] TdlgShowFilter::EditFilter (flt_dlgShowFilter_unit.pas, line 1685)
:0060E5C9 [gedemin.exe] TdlgFilterList::acEditExecute (flt_dlgFilterList_unit.pas, line 142)
:00426BA8 [gedemin.exe] TBasicAction::Execute (Classes.pas, line 8077)
:00472F44 [gedemin.exe] TContainedAction::Execute (ActnList.pas, line 321)
:00473C62 [gedemin.exe] TCustomAction::Execute (ActnList.pas, line 708)
:004038D5 [gedemin.exe] CallDynaInst
:004269FD [gedemin.exe] TBasicActionLink::Execute (Classes.pas, line 8012)
:0045E1D8 [gedemin.exe] TControl::Click (Controls.pas, line 4286)
:00441AE0 [gedemin.exe] TButton::Click (StdCtrls.pas, line 2885)
:00441C47 [gedemin.exe] TButton::CNCommand (StdCtrls.pas, line 2937)
:0045DFCE [gedemin.exe] TControl::WndProc (Controls.pas, line 4227)
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:76E1810F [user32.dll]
:77BCC7BC [ntdll.dll]
:76E20F1B [user32.dll]
:76E17ECA [user32.dll]
:77BCC7BC [ntdll.dll]
:76E38982 [user32.dll]
:76E20F1B [user32.dll]
:76E17ECA [user32.dll]
:76E1810F [user32.dll]
:76E17F0C [user32.dll]
:00441A2B [gedemin.exe] TButtonControl::WndProc (StdCtrls.pas, line 2865)
:0045DD51 [gedemin.exe] TControl::Perform (Controls.pas, line 4152)
:00458919 [gedemin.exe] FindControl (Controls.pas, line 1615)
:00461829 [gedemin.exe] DoControlMsg (Controls.pas, line 5774)
:00462006 [gedemin.exe] TWinControl::WMCommand (Controls.pas, line 5950)
:0045DFCE [gedemin.exe] TControl::WndProc (Controls.pas, line 4227)
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:76E175A7 [user32.dll]
:76E040AB [user32.dll]
:004617AD [gedemin.exe] TWinControl::DefaultHandler (Controls.pas, line 5755)
:0045DFCE [gedemin.exe] TControl::WndProc (Controls.pas, line 4227)
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:67F4C18A [comctl32.dll]
:67F4C11A [comctl32.dll]
:004611C7 [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5612)
:00449526 [gedemin.exe] StdWndProc (Forms.pas, line 1459)
:76E20F1B [user32.dll]
:76E17ECA [user32.dll]
:00430829 [gedemin.exe] FreeMemoryContexts (Graphics.pas, line 4566)
:004611C7 [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5612)
:004611DE [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5615)
:77BCC7BC [ntdll.dll]
:76E17CDE [user32.dll]
:76E17ACA [user32.dll]
:76E71408 [user32.dll]
:76E1B68F [user32.dll]
:77BF4E9D [ntdll.dll]
:75A5107C [win32u.dll]
:76E1742B [user32.dll]
:76E1B6A7 [user32.dll]
:76E158EF [user32.dll]
:76E3A2DB [user32.dll]
:76E39FE0 [user32.dll]
:76E394E8 [user32.dll]
:77C1E7EC [ntdll.dll]
:77BDBE5F [ntdll.dll]
:76E38982 [user32.dll]
:76E20F1B [user32.dll]
:76E17ECA [user32.dll]
:71D225B2 [pshook.dll]
:71D2210F [pshook.dll]
:71D220D7 [pshook.dll]
:76E17CDE [user32.dll]
:76E175A7 [user32.dll]
:76E040AB [user32.dll]
:004617AD [gedemin.exe] TWinControl::DefaultHandler (Controls.pas, line 5755)
:0045E688 [gedemin.exe] TControl::WMLButtonUp (Controls.pas, line 4410)
:00464ACD [gedemin.exe] TWinControl::GetHandle (Controls.pas, line 7208)
:75A5100C [win32u.dll]
:76E1F0C6 [user32.dll]
:0045DFCE [gedemin.exe] TControl::WndProc (Controls.pas, line 4227)
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:005E49A2 [gedemin.exe] GetMessageHook (TB2Hook.pas, line 138)
Recursive call (2 times):
:76E1B5F6 [user32.dll]
:76E1B449 [user32.dll]
:77BF2A0C [ntdll.dll]
:76E1B3C6 [user32.dll]
:77BF4E9D [ntdll.dll]
:76E157A5 [user32.dll]
:00441A2B [gedemin.exe] TButtonControl::WndProc (StdCtrls.pas, line 2865)
:004611C7 [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5612)
:004611DF [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5615)
:00449526 [gedemin.exe] StdWndProc (Forms.pas, line 1459)
:76E20F1B [user32.dll]
:76E17ECA [user32.dll]
:77BF2A0C [ntdll.dll]
:76E1B3C6 [user32.dll]
:76E17CDE [user32.dll]
:76E15C3A [user32.dll]
:76E07DC0 [user32.dll]
:00455085 [gedemin.exe] TApplication::ProcessMessage (Forms.pas, line 6630)

Modules:
$00400000 (00400000,00001000,00DBD800) C:\Golden Software\Gedemin\gedemin.exe
$76DE0000 (76DE0000,00001000,000A3600) C:\WINDOWS\System32\user32.dll
$76A10000 (76A10000,00001000,000BFA00) C:\WINDOWS\System32\MSCTF.dll
$77AB0000 (77AB0000,00001000,000B0600) C:\WINDOWS\System32\msvcrt.dll
$67F10000 (67F10000,00001000,00071E00) C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_c0da534e38c01f4d\comctl32.dll
$77B80000 (77B80000,00001000,00120200) C:\WINDOWS\SYSTEM32\ntdll.dll
$767E0000 (767E0000,00001000,001DB600) C:\WINDOWS\System32\KERNELBASE.dll
$75A50000 (75A50000,00001000,00005400) C:\WINDOWS\System32\win32u.dll
$71D20000 (71D20000,00001000,0000E400) C:\Program Files (x86)\Yandex\Punto Switcher\pshook.dll
$77910000 (77910000,00010000,00065000) C:\WINDOWS\System32\KERNEL32.DLL

-----
Main Thread ID = 00005C40, Current Thread ID = 00005C40
Registers:
EAX = 00000008  CS = 0023  EIP = 004045F4  Flags = 00010202
EBX = 00E75024  SS = 002B  ESP = 0019EDB8    EBP = 0019EDEC
ECX = 00000002  DS = 002B  ESI = 00E6111C    FS  = 0053
EDX = 1255CF58  ES = 002B  EDI = 123F902C    GS  = 002B
Code at CS:EIP
87 10 85 D2 74 14 8B 4A F8 49 7C 0E F0 FF 4A F8 
Stack:
005323D6 00000001 0EB6AEC0 12502818 00E75024 
00000000 00000000 0F6ADE78 0000000B 000019E6 
00403A00 12486138 0040360B 00000000 0508B470 
00455085 0000001B 00004F39 00004D27 000019E6 

Пожалуйста, восстановите работоспособность стандартных команд **Создать** и **Изменить**.

**Comment by Polfath** [comment]
Посмотрю

**Comment by Polfath** [comment]
@NikolayUkleyko Попробовал на нескольких справочниках и документах получить ошибку. Не вышло. Может на каком-то конкретном попробовать?

**Comment by NikolayUkleyko** [comment]
Проверено на актуальном **gedemin.exe**.
Работает корректно.
Спасибо, @Polfath , @gsbelarus .
Правок не было, а заработало.
Хммм, странно. 😃
