### ISSUE TITLE
перевод настройки из gsf  в NS через кнопку OneSet2NS

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4307]
Поставил настройку (поле в документ) в формате gsf все установилось, все ок.

![изображение](https://user-images.githubusercontent.com/11507129/190365350-a08d75c8-4094-4ef1-a3fd-b868c5c8a7cc.png)

После этого я  из этой настройки делаю namespace  через кнопку OneSet2NS и получается вот что

![Screenshot 2022-09-15 121602](https://user-images.githubusercontent.com/11507129/190365771-0ab74c0d-3a15-4ad2-b179-3c5bf9acc389.png)

Однако, если я руками  создаю настройку namespace   все ок 

![Screenshot 2022-09-15 121804](https://user-images.githubusercontent.com/11507129/190366218-89346863-de47-4242-a64f-7d5a1e9859c9.png)

Раньше этот механизм работал корректно, я часто пользовался, когда надо было сформирвоать ПИ из уже существующей gsf настройки

**Comment by NikolayUkleyko** [comment]
Вероятно подтягиваются связанные объекты или объекты, которые прямо не входят в настройку (не видны), но они учитываются.
@YRozmysl , пробовал ли, ты, установить сконвертированное ПИ без правок на базу данных ?
Нет ли ошибок при установке и в целом ?

**Comment by NikolayUkleyko** [comment]
@YRozmysl , что можешь добавить по данной теме ?

**Comment by YRozmysl** [comment]
эта ошибка странная, вот именно с этой настройкой такое, а вот если  другие какие -то  - все норм
