### ISSUE TITLE
Общие. Редактор скрипт-объектов. Ошибки при закрытии всех объектов и закрытии формы

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4309]
**_Редактор скрипт-объектов_**

При выполнении команды **Закрыть все** на экране отображается окно со следующей ошибкой:
![image](https://user-images.githubusercontent.com/11497453/191499200-a5876b30-3b4b-4c35-b15e-bac15239d4bd.png)

-----

Call stack:
:004045D0 [gedemin.exe] LStrAsg
:009A51F4 [gedemin.exe] TBaseFrame::GetName (prp_BaseFrame_unit.pas, line 1031)
:009A54ED [gedemin.exe] TBaseFrame::CloseQuery (prp_BaseFrame_unit.pas, line 1110)
:00E92957 [gedemin.exe] IBError (IB.pas, line 402)
:77318B32 [ntdll.dll]
:77318B04 [ntdll.dll]
:772F91DF [ntdll.dll]
:77304FA6 [ntdll.dll]
:7596CC12 [KERNELBASE.dll]
:00E92957 [gedemin.exe] IBError (IB.pas, line 402)
:00411907 [gedemin.exe] Exception::Create
Recursive call (3 times):
:7596CC12 [KERNELBASE.dll]
:00E92957 [gedemin.exe] IBError (IB.pas, line 402)
:00411907 [gedemin.exe] Exception::Create
Recursive call (2 times):
:00E92957 [gedemin.exe] IBError (IB.pas, line 402)
:0058AB6B [gedemin.exe] TIBCustomDataSet::CheckEditState (IBCustomDataSet.pas, line 1788)
:0058B6E4 [gedemin.exe] TIBCustomDataSet::GetActiveBuf (IBCustomDataSet.pas, line 2136)
:00591448 [gedemin.exe] TIBCustomDataSet::InternalSetFieldData (IBCustomDataSet.pas, line 5189)
:00DE3E48 [gedemin.exe] TgdcBase::InternalSetFieldData (gdcBase.pas, line 15578)
:00592546 [gedemin.exe] TIBCustomDataSet::SetFieldData (IBCustomDataSet.pas, line 5757)
:004FA11E [gedemin.exe] TDataSet::SetFieldData (DB.pas, line 8602)
:746C6664 [windows.storage.dll]
:756E43F8 [gdi32full.dll]
:756E48A4 [gdi32full.dll]
:723FC3FB [TextShaping.dll]
:723FC68F [TextShaping.dll]
:7570C7B6 [gdi32full.dll]
:7570C310 [gdi32full.dll]
:756F03FF [gdi32full.dll]
:756EFD89 [gdi32full.dll]
:757070B7 [gdi32full.dll]
:72429BFD [TextShaping.dll]
:7242D7C8 [TextShaping.dll]
:7242D955 [TextShaping.dll]
:756E74E6 [gdi32full.dll]
:72426DF4 [TextShaping.dll]
:724229FA [TextShaping.dll]
:7242974A [TextShaping.dll]
:72423225 [TextShaping.dll]
:724294C5 [TextShaping.dll]
:7570CF87 [gdi32full.dll]
:723FD10E [TextShaping.dll]
:72426450 [TextShaping.dll]
:7242645F [TextShaping.dll]
:724296A2 [TextShaping.dll]
:7242645F [TextShaping.dll]
:723FCF2E [TextShaping.dll]
:724224DA [TextShaping.dll]
:7242254A [TextShaping.dll]
:72421F9B [TextShaping.dll]
:7240E343 [TextShaping.dll]
:723FD217 [TextShaping.dll]
:7240AEBC [TextShaping.dll]
:7240AECF [TextShaping.dll]
:746C6664 [windows.storage.dll]
:756E43F8 [gdi32full.dll]
:756E48A4 [gdi32full.dll]
:76E0152C [win32u.dll]
:723FC3FB [TextShaping.dll]
:723FC68F [TextShaping.dll]
:7570C7B6 [gdi32full.dll]
:7570C310 [gdi32full.dll]
:756F03FF [gdi32full.dll]
:756EFD89 [gdi32full.dll]
:757070B7 [gdi32full.dll]
:7595C287 [KERNELBASE.dll]
:761C3A94 [GDI32.dll]
:756E74C7 [gdi32full.dll]
:756E74E6 [gdi32full.dll]
:7570AF90 [gdi32full.dll]
:746C6664 [windows.storage.dll]
:756E7369 [gdi32full.dll]
:757021EE [gdi32full.dll]
:7240AF3B [TextShaping.dll]
:723FBB5E [TextShaping.dll]
:723FBB6D [TextShaping.dll]
:756F9E46 [gdi32full.dll]
:756F9E57 [gdi32full.dll]
:756F9E6A [gdi32full.dll]
Recursive call (2 times):
:746C6664 [windows.storage.dll]
:72D50DD7 [uxtheme.dll]
:72D50FDB [uxtheme.dll]
:005FCCEF [gedemin.exe] TTBView::DrawItem (TB2Item.pas, line 5236)
:005FCCF7 [gedemin.exe] TTBView::DrawItem (TB2Item.pas, line 5237)
:756FBB61 [gdi32full.dll]
:756FB91A [gdi32full.dll]
:756FB726 [gdi32full.dll]
:756FB739 [gdi32full.dll]
:75E66767 [user32.dll]
:75E63F97 [user32.dll]
:75E63FAF [user32.dll]
:75E786AD [user32.dll]
:75E761A3 [user32.dll]
:75E75E27 [user32.dll]
:72D5042F [uxtheme.dll]
:72D4FC46 [uxtheme.dll]
:75E634EC [user32.dll]
:72D4FAEE [uxtheme.dll]
:75706C7F [gdi32full.dll]
:75706CC2 [gdi32full.dll]

Modules:
$00400000 (00400000,00001000,00DBD800) C:\Golden Software\Gedemin\gedemin.exe
$76E00000 (76E00000,00001000,00005400) C:\WINDOWS\System32\win32u.dll
$75E40000 (75E40000,00001000,000A3000) C:\WINDOWS\System32\user32.dll
$77290000 (77290000,00001000,00120400) C:\WINDOWS\SYSTEM32\ntdll.dll
$76360000 (76360000,00010000,00065000) C:\WINDOWS\System32\KERNEL32.DLL
$75840000 (75840000,00001000,001DB800) C:\WINDOWS\System32\KERNELBASE.dll
$744F0000 (744F0000,00001000,00597800) C:\WINDOWS\SYSTEM32\windows.storage.dll

-----

Main Thread ID = 00008AA0, Current Thread ID = 00008AA0
Registers:
EAX = 0019FC58  CS = 0023  EIP = 004045D0  Flags = 00010202
EBX = 009A54C9  SS = 002B  ESP = 0019CDD4    EBP = 0019CDE0
ECX = 00000000  DS = 002B  ESI = 00000000    FS  = 0053
EDX = 65747379  ES = 002B  EDI = 0019FC24    GS  = 002B
Code at CS:EIP
8B 4A F8 41 7F 1A 50 52 8B 42 FC E8 5C 00 00 00 
Stack:
009A51F4 0019FC58 0F5108B0 0019FC8C 009A54ED 
00000000 00000000 75706CC2 00000005 03653738 
00403A0B 036533D8 0040360B 00000000 0F3DE670 
75706CC2 FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF 

-----
-----

При закрытии формы редактора скрипт-объектов на экране отображается окно со следующей ошибкой:
![image](https://user-images.githubusercontent.com/11497453/191499904-05e0283e-0fd0-45ed-8d94-d46bee15776b.png)

-----

Call stack:
:004036F8 [gedemin.exe] TObject::Free
:009C6A3D [gedemin.exe] TReportFrame::DoOnDestroy (prp_ReportFrame_Unit.pas, line 916)
:009A4649 [gedemin.exe] TBaseFrame::Destroy (prp_BaseFrame_unit.pas, line 634)
:004036FB [gedemin.exe] TObject::Free
:009DC14E [gedemin.exe] TfrmGedeminProperty::BeforeDestruction (prp_frmGedeminProperty_Unit.pas, line 3717)
:00403AC4 [gedemin.exe] BeforeDestruction
:009DB9C3 [gedemin.exe] TfrmGedeminProperty::Destroy (prp_frmGedeminProperty_Unit.pas, line 3544)
:004036FB [gedemin.exe] TObject::Free
:00EC8E1C [gedemin.exe] TfrmGedeminMain::actCloseFormExecute (gd_main_form.pas, line 1726)
:00426BA8 [gedemin.exe] TBasicAction::Execute (Classes.pas, line 8077)
:00472F44 [gedemin.exe] TContainedAction::Execute (ActnList.pas, line 321)
:00473C62 [gedemin.exe] TCustomAction::Execute (ActnList.pas, line 708)
:004038D5 [gedemin.exe] CallDynaInst
:004269FD [gedemin.exe] TBasicActionLink::Execute (Classes.pas, line 8012)
:0046E9B9 [gedemin.exe] TMenuItem::Click (Menus.pas, line 1738)
:004703FC [gedemin.exe] TMenu::DispatchCommand (Menus.pas, line 2446)
:0047176C [gedemin.exe] TPopupList::WndProc (Menus.pas, line 3135)
:75E75465 [user32.dll]
:004716A8 [gedemin.exe] TPopupList::MainWndProc (Menus.pas, line 3116)
:00449526 [gedemin.exe] StdWndProc (Forms.pas, line 1459)
:75E80BCB [user32.dll]
:75E77B8A [user32.dll]
:77302ACC [ntdll.dll]
:75E7B096 [user32.dll]
:75E7799E [user32.dll]
:75E758FA [user32.dll]
:75E67A90 [user32.dll]
:00455085 [gedemin.exe] TApplication::ProcessMessage (Forms.pas, line 6630)
:004550CC [gedemin.exe] TApplication::HandleMessage (Forms.pas, line 6649)
:00455352 [gedemin.exe] TApplication::Run (Forms.pas, line 6732)
:00455376 [gedemin.exe] TApplication::Run (Forms.pas, line 6736)
:011BE6B8 [gedemin.exe] initialization (gedemin.dpr, line 734)
:011BE6D2 [gedemin.exe] initialization (gedemin.dpr, line 744)
:011BE6F1 [gedemin.exe] initialization (gedemin.dpr, line 746)
:7637FA29 [KERNEL32.DLL]
:772F7B5E [ntdll.dll]
:772F7B2E [ntdll.dll]

Modules:
$00400000 (00400000,00001000,00DBD800) C:\Golden Software\Gedemin\gedemin.exe
$76E00000 (76E00000,00001000,00005400) C:\WINDOWS\System32\win32u.dll
$75E40000 (75E40000,00001000,000A3000) C:\WINDOWS\System32\user32.dll
$77290000 (77290000,00001000,00120400) C:\WINDOWS\SYSTEM32\ntdll.dll
$76360000 (76360000,00010000,00065000) C:\WINDOWS\System32\KERNEL32.DLL
$75840000 (75840000,00001000,001DB800) C:\WINDOWS\System32\KERNELBASE.dll
$744F0000 (744F0000,00001000,00597800) C:\WINDOWS\SYSTEM32\windows.storage.dll
$756B0000 (756B0000,00001000,000B9200) C:\WINDOWS\System32\gdi32full.dll
$723A0000 (723A0000,00001000,0008F000) C:\WINDOWS\SYSTEM32\TextShaping.dll
$761C0000 (761C0000,00001000,0001A800) C:\WINDOWS\System32\GDI32.dll
$72D20000 (72D20000,00001000,00065800) C:\WINDOWS\system32\uxtheme.dll
$76070000 (76070000,00001000,000B0600) C:\WINDOWS\System32\msvcrt.dll
$76640000 (76640000,00001000,000BFA00) C:\WINDOWS\System32\MSCTF.dll
$76610000 (76610000,00001000,00018A00) C:\WINDOWS\System32\imm32.dll
$73870000 (73870000,00001000,00064800) C:\WINDOWS\SYSTEM32\CoreMessaging.dll
$72930000 (72930000,00001000,0016C000) C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
$74CF0000 (74CF0000,00001000,00071E00) C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_c0da534e38c01f4d\comctl32.dll
$73C10000 (73C10000,00001000,00045C00) C:\WINDOWS\system32\mswsock.dll
$75300000 (75300000,00001000,00046400) C:\WINDOWS\System32\WS2_32.dll
$10000000 (10000000,00001000,0005A000) C:\Golden Software\Gedemin\fbclient.dll

-----

Main Thread ID = 00008AA0, Current Thread ID = 00008AA0
Registers:
EAX = 05FB8AC0  CS = 0023  EIP = 004036F8  Flags = 00010206
EBX = 05114898  SS = 002B  ESP = 0019FBD0    EBP = 0019FBD8
ECX = 00000000  DS = 002B  ESI = 000F02A6    FS  = 0053
EDX = 009C2F01  ES = 002B  EDI = 00000111    GS  = 002B
Code at CS:EIP
FF 51 FC C3 53 56 57 89 C3 89 D7 AB 8B 4B D8 31 
Stack:
009C6A3D 0F5108B0 0019FBE8 009A4649 015108B0 
00000000 00000000 772F7B2E 00000005 0369FEE8 
00403A0B 036537D8 0040360B 00000000 08554720 
772F7B2E FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF

**Comment by NikolayUkleyko** [comment]
При этом подключение к базе данных не закрывается.
:man_shrugging:

**Comment by gsbelarus** [comment]
Не повторяется. Надо хотя бы приблизительно какие вкладки открыты, что делалось до этого.

**Comment by NikolayUkleyko** [comment]
Смоделировал ситуацию — ошибка не повторяется.
Были открыты отчеты по документам _**Исследователь → Основные средства → Акт ввода в эксплуатацию или Акты ввода в эксплуатацию (новые) → ОС. Акт ввода в эксплуатацию, ОС. Акт ввода в эксплуатацию остатков**_.
