### ISSUE TITLE
Типовой документ. После удаления документа в Исследователе сохраняется ярлык

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4310]
@yoannawx смоделировала пример, я проверил.
При удалении типового документа в Исследователе остается ярлык документа.
Применимо для пользовательских и складских документов.
При создании и удалении таблиц ярлык в Исследователе не сохраняется.

**Comment by Polfath** [comment]
Посмотрю

**Comment by Polfath** [comment]
Сделал. Только реализовал в 4266.

**Comment by NikolayUkleyko** [comment]
Проверено.

1. При удалении типового документа программа отображает окно со следующим сообщением:
![image](https://user-images.githubusercontent.com/11497453/195040659-23e52d00-c165-479c-a852-34a1a755ca92.png)

Call stack:
:00D588F1 [gedemin.exe] TgdClassList::Get (gd_ClassList.pas, line 2909)
:7596CC12 [KERNELBASE.dll]_
:00D588F1 [gedemin.exe] TgdClassList::Get (gd_ClassList.pas, line 2909)
:00D55EA0 [gedemin.exe] TgdClassList::_Find (gd_ClassList.pas, line 2120)
_Recursive call (2 times):
:00D588F1 [gedemin.exe] TgdClassList::Get (gd_ClassList.pas, line 2909)
:00653F6F [gedemin.exe] TMethodControl::ExecuteMethodNew (mtd_Base.pas, line 1141)
:008C6986 [gedemin.exe] Tgdc_frmMDHGR::SaveSettings (gdc_frmMDHGR_unit.pas, line 143)
:00DF7773 [gedemin.exe] TCreateableForm::SaveSettingsEvent (gd_createable_form.pas, line 1662)
:00DF4D89 [gedemin.exe] TCreateableForm::DoDestroy (gd_createable_form.pas, line 663)
:0044BC62 [gedemin.exe] TCustomForm::BeforeDestruction (Forms.pas, line 2605)
:00403AC4 [gedemin.exe] BeforeDestruction
:00AF885F [gedemin.exe] Tgdc_frmMDH::Destroy (gdc_frmMDH_unit.pas, line 504)
:004036FB [gedemin.exe] TObject::Free
:00EC716D [gedemin.exe] TfrmGedeminMain::FormCloseQuery (gd_main_form.pas, line 725)
:00EC719E [gedemin.exe] TfrmGedeminMain::FormCloseQuery (gd_main_form.pas, line 730)
:00450663 [gedemin.exe] TCustomForm::CloseQuery (Forms.pas, line 4515)
:0045055F [gedemin.exe] TCustomForm::Close (Forms.pas, line 4487)
:75E6522C [user32.dll]
:0044F6CC [gedemin.exe] TCustomForm::WMClose (Forms.pas, line 4099)
:00DF7621 [gedemin.exe] TCreateableForm::WMClose (gd_createable_form.pas, line 1628)
:0045DFCE [gedemin.exe] TControl::WndProc (Controls.pas, line 4227)
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:75E63457 [user32.dll]
:772DC87C [ntdll.dll]
:75E80BCB [user32.dll]
:75E77B8A [user32.dll]
:75E77DCF [user32.dll]
:75E77BCC [user32.dll]
:75E7799E [user32.dll]
:75E77DCF [user32.dll]
:0044CE7F [gedemin.exe] TCustomForm::WndProc (Forms.pas, line 3063)
:00DFE9FA [gedemin.exe] TgsResizeManager::FormWindowProc (gsResizer.pas, line 1491)
:004611C7 [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5612)
:004611DF [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5615)
:00449526 [gedemin.exe] StdWndProc (Forms.pas, line 1459)
:75E80BCB [user32.dll]
:75E77B8A [user32.dll]
:772EAC49 [ntdll.dll]
:75E7799E [user32.dll]
:75E77267 [user32.dll]
:75E7540B [user32.dll]
:74D0998A [comctl32.dll]
:74D09EDB [comctl32.dll]
:74D09D27 [comctl32.dll]
:74D0B4F2 [comctl32.dll]
:74D09EDB [comctl32.dll]
:74D09DDB [comctl32.dll]
:772DDD94 [ntdll.dll]
:75E7B2C6 [user32.dll]
:75E80BCB [user32.dll]
:75E77B8A [user32.dll]
:77302ACC [ntdll.dll]
:75E7B00B [user32.dll]
:77304F5D [ntdll.dll]
:75E7799E [user32.dll]
:75E7778A [user32.dll]
:75ED10A8 [user32.dll]
:75E7B35F [user32.dll]
:77304F5D [ntdll.dll]
:76E0107C [win32u.dll]
:75E75FF6 [user32.dll]
:738D042F [uxtheme.dll]
:75E634EC [user32.dll]
:738D3665 [uxtheme.dll]
:738CBEBA [uxtheme.dll]
:738CFB91 [uxtheme.dll]
:738C8C08 [uxtheme.dll]
:75E6348C [user32.dll]
:75E80BCB [user32.dll]
:75E77B8A [user32.dll]
:72D68162 [CoreMessaging.dll]
:75E7799E [user32.dll]
:75E77267 [user32.dll]
:75E63D7B [user32.dll]
:004617AD [gedemin.exe] TWinControl::DefaultHandler (Controls.pas, line 5755)
:0044E6F1 [gedemin.exe] TCustomForm::DefaultHandler (Forms.pas, line 3687)
:00463698 [gedemin.exe] TWinControl::WMSysCommand (Controls.pas, line 6599)
:0044F7FE [gedemin.exe] TCustomForm::WMSysCommand (Forms.pas, line 4130)
:00DF6A04 [gedemin.exe] TCreateableForm::WMSysCommand (gd_createable_form.pas, line 1382)
:75E77B8A [user32.dll]
:75E77DCF [user32.dll]
:75E77BCC [user32.dll]
:72D935BC [CoreMessaging.dll]
:772EAC49 [ntdll.dll]
:760EAC1F [msvcrt.dll]
:7595451B [KERNELBASE.dll]
:75E7799E [user32.dll]
:75E77DCF [user32.dll]
:75E77267 [user32.dll]
:75E63D7B [user32.dll]
:0045DFCE [gedemin.exe] TControl::WndProc (Controls.pas, line 4227)
Recursive call (2 times):
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:7594B6A2 [KERNELBASE.dll]
:724A3121 [pshook.dll]
:0044CE7F [gedemin.exe] TCustomForm::WndProc (Forms.pas, line 3063)
:772C84D1 [ntdll.dll]
:0044CE7F [gedemin.exe] TCustomForm::WndProc (Forms.pas, line 3063)
:772C8528 [ntdll.dll]
Recursive call (2 times):
:00DFE9FA [gedemin.exe] TgsResizeManager::FormWindowProc (gsResizer.pas, line 1491)
:004611C7 [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5612)_

_Modules:
$00400000 (00400000,00001000,00DBE800) C:\Golden Software\Gedemin\gedemin.exe
$75840000 (75840000,00001000,001DB800) C:\WINDOWS\System32\KERNELBASE.dll
$75E40000 (75E40000,00001000,000A3000) C:\WINDOWS\System32\user32.dll
$77290000 (77290000,00001000,00120400) C:\WINDOWS\SYSTEM32\ntdll.dll
$74CF0000 (74CF0000,00001000,00071E00) C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_c0da534e38c01f4d\comctl32.dll
$76E00000 (76E00000,00001000,00005400) C:\WINDOWS\System32\win32u.dll
$738A0000 (738A0000,00001000,00065800) C:\WINDOWS\system32\uxtheme.dll
$72D60000 (72D60000,00001000,00064800) C:\WINDOWS\SYSTEM32\CoreMessaging.dll
$76070000 (76070000,00001000,000B0600) C:\WINDOWS\System32\msvcrt.dll
$724A0000 (724A0000,00001000,0000E400) C:\Program Files (x86)\Yandex\Punto Switcher\pshook.dll_

_Main Thread ID = 000127EC, Current Thread ID = 000127EC
Registers:
EAX = 0019D5C0  CS = 0023  EIP = 7596CC12  Flags = 00000216
EBX = 00000000  SS = 002B  ESP = 0019D5C0    EBP = 0019D618
ECX = 00000007  DS = 002B  ESI = 0019DCF4    FS  = 0053
EDX = 00000000  ES = 002B  EDI = 0019DAF4    GS  = 002B
Code at CS:EIP
8B 4C 24 54 33 CC E8 A3 4D 00 00 8B E5 5D C2 10 
Stack:
0EEDFADE 00000001 00000000 7596CC12 00000007 
00000000 00000000 0B0E7E58 0000000B 000015EC 
00403A00 0B1D4B10 0040360B 00000000 0526B470 
004611C7 0000001C 000051C1 0000501E 000015EC_

2. Закрыли программу и снова подключились к базе данных.
    Ярлык остался.

@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

Необходимо в модифай включить обновленный триггер **GD_AD_DOCUMENTTYPE** с сообщениями в верной кодировке.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
