### ISSUE TITLE
Фильтры. Клавиша ”Esc”

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4311]
1. В списке фильтров нажатие клавиши **Esc** выполняет команду <ins>редактирования</ins> текущего фильтра, а не закрытие формы.
2. При создании, редактировании фильтра нажатие на клавишу **Esc** выполняет команду <ins>удаления</ins> настроек текущей закладки, а не выход из настроек фильтра.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Пункт 1 – работает корректно.
Пункт 2 – при активной закладке **_Сортировка_** нажатие клавиши **Esc** очищает настройки параметров текущей закладки.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
