### ISSUE TITLE
Бухгалтерия. Карта счета. Сообщение при редактировании позиций нескольких выделенных записей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4312]
**_Исследователь → Бухгалтерия → Карта счета._**

Пожалуйста, при редактировании **позиций** нескольких выделенных записей
![image](https://user-images.githubusercontent.com/11497453/192732444-aba07322-da63-419f-a237-875ee405ff63.png)
_Рис. 1._

![image](https://user-images.githubusercontent.com/11497453/192732463-e6a1c21b-a058-4ecd-b4e8-3ed7c11c4c0c.png)
_Рис. 2._

предусмотрите сообщение **Множественное редактирование записей не поддерживается.**
![image](https://user-images.githubusercontent.com/11497453/192761598-9a1b133a-6a16-48ec-9d38-02a664e27fc4.png)
_Рис. 3._

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
