### ISSUE TITLE
Шрифт в лукапе путевого листа

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4313]
Шрифт  в лукапе, а конкретно путевого листа, выглядит некорректно, в именно вот так, на более поздней версии exe все было корректно.

![Screenshot 2022-09-28 125709](https://user-images.githubusercontent.com/11507129/192750349-d9e6b256-ca01-4342-9fd3-48b7c8761e81.png)

**Comment by gsbelarus** [comment]
а сейчас как? со шрифтами не трогали ничего.

**Comment by gsbelarus** [comment]
это во всех лукапах или одном?

**Comment by YRozmysl** [comment]
это конкретно я наблюдаю в одном лукапе, в конкретном документе

**Comment by gsbelarus** [comment]
тогда надо в дизайнере открыть и смотреть что за шрифт там прописан

**Comment by YRozmysl** [comment]
вопрос можно снимать, наверное.  Я перекомпелирвоал конкретную процедуру, которая используется в этом конкретно проблемном лукапе, все стало ок. Но, как такое получилось, не знаю.
