### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Сообщение при редактировании позиций нескольких выделенных записей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4314]
_**Исследователь / Бухгалтерия / Журнал хоз. операций.**_

Пожалуйста, при редактировании **позиций** нескольких выделенных записей
![image](https://user-images.githubusercontent.com/11497453/192761006-dcc16bbc-ab24-44eb-af40-29f05993a59f.png)
_Рис. 1._

![image](https://user-images.githubusercontent.com/11497453/192761039-ed12c9d1-af16-4214-a99e-9f4097ee3193.png)
_Рис. 2._

предусмотрите сообщение **Множественное редактирование записей не поддерживается.**
![image](https://user-images.githubusercontent.com/11497453/192759883-51662b38-8fef-43ca-afbe-bfaa285b552d.png)
_Рис. 3._

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
