### ISSUE TITLE
Column Editors. Поиск

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4316]
Если я правильно понял, тут должна быть кнопка поиска, или что-то в этом роде? Или для чего это поле?

![444](https://user-images.githubusercontent.com/11507129/194585952-78059bb4-500f-4ea7-8217-0edf33c3bb2f.jpg)

**Comment by gsbelarus** [comment]
а она как фильтр не работает?

**Comment by YRozmysl** [comment]
Я полагаю, что нет. 

![Screenshot 2022-10-07 184246](https://user-images.githubusercontent.com/11507129/194594287-f57ee96c-56ab-491f-beb2-dd78759b6830.png)

**Comment by gsbelarus** [comment]
тогда баг

**Comment by MIchaelShoihet** [comment]
На сколько я понял набираешь и нажимаешь Enter и он ищет без кнопки

**Comment by MIchaelShoihet** [comment]
Просто переходит на найденное поле. По хорошему конечно надо предусмотреть поиск следующего...

**Comment by MIchaelShoihet** [comment]
Ищет не по вхождению а по начальным символам и только первое, хотелось бы что бы искало по вхождению и можно было бы искать следующее. Если уже есть такой функционал

**Comment by gsbelarus** [comment]
надо искать по вхождению. добавить кнопку Поиск, которая работает от текущего положения курсора в списке  вперед. Если доходит до конца списка, то начинает просмотр сначала. Если найдено значение, то курсор помещается на него.

Если при нажатии на кнопку значение не найдено, то выводится MessageBox с соответствующим сообщением.

**Comment by NikolayUkleyko** [comment]
Данная тема рассматривается и здесь https://github.com/GoldenSoftwareLtd/gedemin/issues/3975.

**Comment by YRozmysl** [comment]
Все Ок. Работает корректно
