### ISSUE TITLE
Сохранение ошибочного пользователя в databases.ini

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4317]
Запускаем Гедымин. 
В окне "Вход в систему" вводим не существующего в базе данных пользователя и нажимаем "Войти". 
Введенный ошибочный пользователь сохраняется в списке пользователей.
Правильное поведение - сохранять пользователя при успешном подключении к базе данных.

Особенно неприятная ситуация, когда ввели пользователя и его пароль в поле "Пользователь" и нажали "Войти". В этом случае раскрывается пароль.

**Comment by NikolayUkleyko** [comment]
Это замечательное предложение.
Это усовершенствование существующего функционала.
При необходимости приведения в порядок перечня пользователей можно выполнить редактирование строки **_Data0_** в файле **databases.ini**.

Может имеет смысл добавить проверку на заглавные буквы при вводе наименования пользователя ?
Пользователь **Иванов**.
Гедымин пропускает ввод наименования пользователя **иванов**.

**Comment by gsbelarus** [comment]
а у нас разве чувствительно к регистру имя пользователя?

**Comment by NikolayUkleyko** [comment]
_> а у нас разве чувствительно к регистру имя пользователя?_

Нет.
Предусмотрено только при вводе пароля.

**Comment by gsbelarus** [comment]
это так и запроектировано в гедымине, что имена пользователей не
чувствительны к регистру.
не надо ничего менять в этом плане.

**Comment by NikolayUkleyko** [comment]
Хорошо, @gsbelarus .

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
