### ISSUE TITLE
Общие. Восстановление базы данных из архива. Добавить кнопку быстрой вставки путей

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4318]
_База данных → Восстановление из архива._

Пожалуйста, предусмотрите кнопку для удобного заполнения полей формы восстановление БД из архива.
Пример:
1. Скопировали путь к **.bk** файлу.
2. Открыли форму восстановления базы данных их архива.
3. Нажали на предполагаемую кнопку вставки расположения архива БД.
4. Автоматически заполнились следующие поля:
• **_Архивные файлы → Имя файла_** — вставка скопированного пути к архиву БД.
• **_Сервер_** — оставляем без изменений.
• **_База данных_** — вставка скопированного пути к архиву БД, но расширение **.bk** заменяем на **.FDB**.

**Comment by MIchaelShoihet** [comment]
Нет. Эта операция не такая частая, требует вдумчивости, и ничего здесь добавлять не будем.

**Comment by NikolayUkleyko** [comment]
Хорошо, @MIchaelShoihet .
