### ISSUE TITLE
Слетела кодировка в названиях колонок в ЖО 

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4320]
![жо](https://user-images.githubusercontent.com/11507129/198574807-22112bee-e0ca-46d8-9caf-8da732606ed4.png)

вот так отображается на последнем exe

**Comment by NikolayUkleyko** [comment]
Да, есть такое.
@Polfath поправит.

**Comment by YRozmysl** [comment]
Все ок.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
