### ISSUE TITLE
Databases.ini и подстановка пароля со снятой галкой ”Запомнить пароль”

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4323]
При выборе базы данных со снятой галкой **_Запомнить пароль_** подставляется пароль из предыдущей базы данных.
В такой ситуации необходимо очищать поле **_Пароль_**.

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста, посмотри.

**Comment by Polfath** [comment]
сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
