### ISSUE TITLE
Типовые документы. При создании документа наследника параметры хранилища не переносятся

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4326]
_**Типовые документы.**_
При создании документа наследника параметры хранилища не переносятся.
Распространяется на все гриды документа.
@gsbelarus , пожалуйста, посмотрите.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.

1. При работе с пользовательскими типовыми документами хранилище **_копируется_** в документ наследник.
Работает верно.

2. При работе со складскими типовыми документами хранилище **_не копируется_** в документ наследник.
Работает не верно.

**Comment by Polfath** [comment]
Поправил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
