### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Не сохраняется очередность выбранных аналитик

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4328]
_**Исследователь → Бухгалтерия → Журнал-ордер.**_

В блоке **Группировать по аналитике** выбранные аналитики не подставляются в той <ins>очередности</ins>, в которой они выбраны.
Пример, выбираем аналитики _Счета и субсчета_, _Подразделение_.
Сохраняем в конфигурацию.
В настройках конфигурации указана верная очередность аналитик _Счета и субсчета_, _Подразделение_.
В сформированном Журнале-ордере указано иначе, _Подразделение_, _Счета и субсчета_.

@Polfath , пожалуйста, посмотри.

**Comment by Polfath** [comment]
сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
