### ISSUE TITLE
Двойной поиск в лукапе

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4329]
Есть такие случаи, когда поиск в лукапе происходит по двум полям, например, стандартно по наименованию  организации и второй режим по УНП там же в том же поле. Джоинится таблица для этого, в поле feilds добавляем cc.taxid.  тут, вроде, все как понятно.

![Screenshot 2022-11-24 120402](https://user-images.githubusercontent.com/11507129/203741506-0d04d0dc-33e7-489c-9426-836691728b63.png)

Когда в этом поле вбиваем наименование и стрелку вниз, то мы видим все такие похожие организации. Когда мы вбиваем в это же поле  УНП конкретной организации и нажимаем вниз -  сообщение, что нет ничего, но если мы нажмем ввод, то подставиться организация с таким унп. 
Может, есть смысл на будущее сделать одинаковый подход к поиску, т.е. стандартно, как и по наименованию. Не знаю, как этот вопрос актуален в других задачах.

**Comment by NikolayUkleyko** [comment]
Подобную тему рассматривали с @Polfath .
Такой функционал применяется во многих объектах программы и является взаимосвязанным.
Вряд ли это будет дорабатываться. :shrug:
