### ISSUE TITLE
Галка Сохранять значения полей в диалоговых окнах

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4330]
Если установлен режим "Сохранять значения полей в диалоговых окнах", то значения этих полей сохраняются в хранилище при сохранении документа, а потом, при создании нового, достаются из хранилища.
Создаем документ, заполняем поле, сохраняем документ.
Это - первый шаг.
Создаем новый документ, в нем это поле заполняется автоматически предыдущим содержанием.
Пока нормально.
Очищаем это поле.
Сохраняем документ.
Это второй шаг.
Создаем новый документ и видим, что это поле заполнено, как во втором шаге, т.е. тем содержимым, которым было заполнено в первом шаге.
А надо, чтобы оно было пустым, как после второго шага.

**Comment by NikolayUkleyko** [comment]
Проверено на примере документов **01. Накладная на получение материалов, ОС, МБП** и **ОС. Акт ввода в эксплуатацию остатков**.
Моделировались ситуации по добавлению полей (ссылок) в таблицу GD_DOCUMENT и в таблицы документов с последующим заполнением данными.
Работает корректно.
Возможно на БД клиента установлены не самые актуальные ПИ.

@gsbelarus , пожалуйста, закройте тему.
