### ISSUE TITLE
Общие. При наследовании документа фильтры из шапки документа копируются в фильтры позиции

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4332]
При наследовании документа фильтры из шапки документа копируются в фильтры позиции.
Не надо копировать фильтры из шапки в позицию документа.
Такие фильтры являются отдельными.
@Polfath , пожалуйста, посмотри.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
