### ISSUE TITLE
SUMSTR2 в ФР4

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4333]
можно ли сделать ф-цию, аналогичную ф-ции SUMSTR2, добавив туда еще параметр true/false, чтобы дробную часть после запятой можно было бы выводить либо прописью, либо цифрами. Как это сделано в SUMCURRSTR2.
Чтобы было, например, сорок две целых и три сотых, либо сорок две целых и 3 сотых, если надо.

**Comment by AndreiKireyeu** [comment]
тогда уже не булевский тип. там же еще и род указать надо. если в общем случае делать.

**Comment by YRozmysl** [comment]
можно и не булевский
