### ISSUE TITLE
Сбрасывать кэш параметров складских документов

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4336]
В скрипте меняются параметры типового документа (набор признаков существующей карточки). Но они, видимо, где-то кэшируются и изменения вступают в силу только после переподключения к базе.

**Comment by NikolayUkleyko** [comment]
> _”В скрипте меняются параметры типового документа (набор признаков существующей карточки).”_

Обычно достаточно переоткрытия формы документа.
