### ISSUE TITLE
FB3. Исключение.

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4337]
Под FB3 под пользователем ругается на исключение USR$WG_E_BLOCK 

![Screenshot 2023-01-04 183052](https://user-images.githubusercontent.com/11507129/210590648-1edc6a48-081f-435c-b35f-fd90343b6578.png)

**Comment by YRozmysl** [comment]
понятно, что вопрос решает запрос GRANT USAGE ON EXCEPTION  USR$WG_E_BLOCK to public
но, как обойтись без этого, если ставится настройка на чистую базу под FB3

**Comment by MIchaelShoihet** [comment]
Никак. Надо будет в exe проверять на версию и для 3.0 и выше выполнять этот грант. Но это уже после перехода на Delphi7

**Comment by Polfath** [comment]
Сделал в делфи 7
