### ISSUE TITLE
Функция ”gs_GetCurrRate”

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4338]
_**Исследователь → Банк и касса → Банковская выписка.**_

Справочник курсов валют заполнен по соответствующей валюте на разные даты.

1. В банковскую выписку добавили запись.
2. Изменили дату.
3. Программа отображает сообщение об ошибке:
![image](https://user-images.githubusercontent.com/11497453/210813620-1c3355e1-4253-45bf-9136-37f096320b42.png)

Для документа **_Банковская выписка_** добавлен метод **TgdcBankStatementDoFieldChange** с зависимостью от функции **gs_GetCurrRate**.

Такое не работает:
```ruby
  gs_GetCurrRate = System.GetCurrRate(DocumentDate, -1, _
    -1, CurrKey, 200010, -1, 1, False, False, False)
```

Функция **gs_GetCurrRate** применяется в различных документах, автоматических проводках и т.д.

-----
https://gsbelarus.com/gs/wiki/index.php/Gedemin_TLB.IGedemin.GetCurrRate

**Comment by gsbelarus** [comment]
где же здесь ошибка? просто сообщение.

надо знать:

1. чему равен currkey
2. содержимое справочника курсов на дату
3. чему равно documentdate

инвертированный курс и кросскурс отключены. скорее всего нет в справочнике прямого курса.

и проверить чтобы currkey был числом, а не строкой

**Comment by sunnycreature** [comment]
Я смотрела, currkey передается в функцию как integer. 

k2 = ibsql.FieldByName("BSCURRKEY").AsInteger - k2 здесь будет = ид валюты
d = gs_GetCurrRate(k, k2, Self.Transaction)

В таком случае функция вернет 0, как-будто не нашла курс 
![image](https://user-images.githubusercontent.com/12336960/210824222-2765e701-09d1-4e93-bf7f-87acaf148ba0.png)

Если же вручную поставлю ид, то все норм
![image](https://user-images.githubusercontent.com/12336960/210824751-cfa7a3ed-f833-48b7-9b2a-21184de7db66.png)

**Comment by gsbelarus** [comment]
это какая то другая функция? я не вижу чтобы в getcurrrate надо было транзакцию передавать

**Comment by gsbelarus** [comment]
в любом случае, проще всего запустить из под делфи и посмотреть что и куда передается

**Comment by gsbelarus** [comment]
Это все последствия перехода на ИД 64.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , @sunnycreature , благодарю за быстрое решение интересного вопроса !
👍 👍 👍 👍 👍

**Comment by Polfath** [comment]
В крайней версии гедемина этот баг не воспроизвоидтс. Я в модуле, в котором возникал он уже кое-что правил по какой-то другой причине. Возможно это лекарство подействовало и на него. Нужно перепроверить.
