### ISSUE TITLE
Сортировка TgdcInvGoodRemains

### ISSUE THREAD

**Issue by Mikle88** [GoldenSoftwareLtd/gedemin#4341]
Добрый день.
Подскажите как можно организовать сортировку остатков при автоматической выборке остатков для списания, нужно как-то в sql код добавить order by с моим критерием отбора: 

`     set InvRemains = creator.getObject(nil,"TgdcInvGoodRemains","")
      InvRemains.Transaction = InvDocLine.Transaction

      CONDITION = CONDITION & " AND c.usr$vm_for_orderkey is null "  

      InvRemains.Close
      InvRemains.ExtraConditions.Clear
      InvRemains.ExtraConditions.Add(CONDITION)`
 

     а дальше мне нужно отсортировать данные перед открытием или после для выбора, чтобы забирать остатки в том порядке, в котором мне нужно, как-то прописать в sql код 

`order by IIF(c.usr$vm_productkey = :pk and c.USR$VM_FOR_ORDERKEY=:ok, 1, iif(c.usr$vm_productkey is null, 2, 3))` 

буду очень признателен любой информации

**Comment by NikolayUkleyko** [comment]
Добрый день, @Mikle88 !
Попробуйте указать Ваш код в форме выбора из остатков документа списания:
_Свойства → Методы класса → Метод **GetOrderClause**_.

Добавьте:
_TgdcInvRemains147012388_486813904GetOrderClause = _
" order by IIF(c.usr$vm_productkey = :pk and c.USR$VM_FOR_ORDERKEY=:ok, 1, iif(c.usr$vm_productkey is null, 2, 3)) "_

**Comment by Mikle88** [comment]
Я думал об этом, но если я укажу данный в **GetOrderClause**, то во всех документах, где вызывается форма вызова остатков будет присутствовать данный код, а это не желательно.

**Comment by Mikle88** [comment]
Или я ошибаюсь?

**Comment by NikolayUkleyko** [comment]
Указываем не в общей функции, а в функции для документа списания **TgdcInvRemains147012388_486813904GetOrderClause**.
Выше поправил https://github.com/GoldenSoftwareLtd/gedemin/issues/4341#issuecomment-1466134972.

**Comment by Mikle88** [comment]
Спасибо, всё получилось.
А я думал, что если я укажу в GetOrderClause , то во всех документах, работающих с остатками, будет то же самое. 
Спасибо.

**Comment by NikolayUkleyko** [comment]
В функции указан RUID документа, для которого предусматривается сортировка.
Пожалуйста.
При возможности закрывайте тему.

-----

@Mikle88 , текущие вопросы по разработке (не рассматривая платформу ”Гедымин” (gedemin.exe)) создавайте здесь https://github.com/GoldenSoftwareLtd/gedemin-apps/issues.
