### ISSUE TITLE
Бухгалтерия. Журнал хозяйственных операций. Изменение даты записи при активной блокировке периода

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4342]
_**Исследователь → Бухгалтерия → Журнал хоз. операций.**_

1. Блокировка периода активна (пример, на 01.03.2023 г.):
    **_Сервис → Параметры → Аудит и безопасность → Блокировка периода..._**.

2. В Журнале хоз. операций добавляем запись от 01.02.2023 г.
    При сохранении записи программа отображает сообщение об ошибке:
![image](https://user-images.githubusercontent.com/11497453/225599061-623f000a-93ab-4401-8bc9-124f66c1b7b0.png)
Это верно.

3. Пробуем поменять дату записи на 05.03.2023 г.
    При сохранении записи программа отображает сообщение об ошибке:
![image](https://user-images.githubusercontent.com/11497453/225599539-d969de17-a04f-4db7-a5c3-4edb09690ab6.png)
Пожалуйста, предусмотрите возможность изменения даты записи в данной ситуации.

**Comment by Polfath** [comment]
Исправил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
