### ISSUE TITLE
Вызов автоматической функции при запуске макроса

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4343]
Пример.
При запуске итогового начисления,  вываливается окно с запросом параметров. И так во многих докумнтах, где идет расчет. Скрин прилагаю.
![Screenshot 2023-03-20 103310](https://user-images.githubusercontent.com/11507129/226274640-74a972e8-c190-40f9-a264-97eeccd55a5d.png)

**Comment by Polfath** [comment]
баг пофиксил

**Comment by gsbelarus** [comment]
Загружайте сразу новый экзе для проверки.

**Comment by YRozmysl** [comment]
там, где используются не prolog ф-ции, вопрос решился, а там где используется пролог при вызове и расчете, есть ошибка.
возникает, например, при расчете в итоговом начислении сотрудника у которого есть алименты, они и рассчитываются как раз в прологе.  на клиентской базе покажу.
![Screenshot 2023-03-23 152308](https://user-images.githubusercontent.com/11507129/227203600-27fd0406-323a-43e3-906d-57325fc9d4a7.png)

**Comment by Polfath** [comment]
починил

**Comment by YRozmysl** [comment]
исправлено
