### ISSUE TITLE
Ошибка при запуске нового экзешника

### ISSUE THREAD

**Issue by Witalia** [GoldenSoftwareLtd/gedemin#4344]
При загрузке новым exe на некоторых базах (Слуцк, Гомель) кидает ошибку
![Снимок экрана 2023-03-21 131906](https://user-images.githubusercontent.com/11479218/226577492-f053c564-9a09-46e0-8b72-0db30f121c8f.png)

**Comment by YRozmysl** [comment]
Такая же ошибка и бройлерах, однако ее нет на базе колхозов белкалия.

**Comment by NikolayUkleyko** [comment]
Разница в версиях класса **TCreator**.
Ниже представлены только фрагменты отличий при сравнении версий:
_• Новая (2021)_

```ruby
'оно происходит автоматически при завершению скрипт-функции.

Private NextCreatorID
Private CreatorCnt

NextCreatorID = 0
CreatorCnt = 0

Class TCreator
  Private FCount
  Private FObjectArray()
  Private FID

  Public Sub DestroyAllObjects
    for I = UBound(FObjectArray) to LBound(FObjectArray) step -1
      if VarType(FObjectArray(I)) = vbObject then
        Designer.DestroyObject(FObjectArray(I))
        Set FObjectArray(I) = Nothing
      end if
    next
      if VarType(FObjectArray(I)) = vbObject then
        if Addr(FObjectArray(I)) = Addr(Object) then
          Designer.DestroyObject(FObjectArray(I))
          Set FObjectArray(I) = Nothing
          exit sub
        end if
    ReDim FObjectArray(7)
    FCount = -1
    FID = NextCreatorID
    CreatorCnt = CreatorCnt + 1
    NextCreatorID = NextCreatorID + 1
    System.AddLogRecord "TCreator", "Created #" & FID & ", Total: " & CreatorCnt, 1, -1, "", False
  End Sub

  Private Sub Class_Terminate
    DestroyAllObjects
    CreatorCnt = CreatorCnt - 1
    System.AddLogRecord "TCreator", "Destroyed #" & FID & ", Total: " & CreatorCnt, 1, -1, "", False
  End Sub
End Class
```

_• Старая (2004)_
```ruby
'оно происходит автоматически при завершению скрипт-функции.







Class TCreator
  Private FCount
  Private FObjectArray()


  Public Sub DestroyAllObjects
    for I = UBound(FObjectArray) to LBound(FObjectArray) step -1
      if VarType(FObjectArray(I)) = vbObject then
        FObjectArray(I).DestroyObject
        FObjectArray(I) = Empty
      end if
    next
      if VarType(FObjectArray(I)) = vbObject then
        if Addr(FObjectArray(I)) = Addr(Object) then
          FObjectArray(I) = Empty
          Object.DestroyObject
          exit sub
        end if
    ReDim FObjectArray(7)
    FCount = -1




  End Sub

  Private Sub Class_Terminate
    DestroyAllObjects


  End Sub
End Class
```

**Comment by gsbelarus** [comment]
на новом классе кидает ошибку, на старом нет?  а на старом экзешнике никогда не кидало? и при загрузке чего?

**Comment by Witalia** [comment]
[image: изображение.png]



вт, 21 мар. 2023 г. в 14:28, Andrej Kirejeŭ ***@***.***>:

**Comment by NikolayUkleyko** [comment]
_> на новом классе кидает ошибку, на старом нет? а на старом экзешнике никогда не кидало? и при загрузке чего?_

При простом подключении к базе данных на новом классе есть ошибка, а на старом – нет.

**Comment by Witalia** [comment]
Шаг 1.
![Снимок экрана 1](https://user-images.githubusercontent.com/11479218/226633009-e2217aa9-4ec6-4ed1-a693-66b85ba5b0c1.png)
Шаг 2.
![Снимок экрана 2](https://user-images.githubusercontent.com/11479218/226633165-203a259e-c220-41b1-9367-69ac0dba844e.png)
Шаг 3.
![Снимок экрана 2023-03-21 131906](https://user-images.githubusercontent.com/11479218/226633291-f38c1703-1e2b-4a9a-88f1-c3f46c79035b.png)
Старыми экзешниками никогда не кидало. Все окна свернуты.

**Comment by gsbelarus** [comment]
вот почему важно подробно описывать. я думал, что речь идет о загрузке ПИ на базу.

**Comment by YRozmysl** [comment]
![Screenshot 2023-03-31 173347](https://user-images.githubusercontent.com/11507129/229150317-95ef2c31-1601-4440-92c0-77ae5c2c0f04.png)
при загрузке ошибка осталась

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.

Коллеги, пожалуйста, проверьте.
При возможности закрывайте текущую тему.
