### ISSUE TITLE
Не отображаются пиктограммы в исследователе

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4345]
![image](https://user-images.githubusercontent.com/11497358/226586837-a1b8218f-1f61-4b74-81ae-b48f93cef028.png)

**Comment by yoannawx** [comment]
в ехе от 23.03 все ок, пиктограммы отображаются, можно закрывать

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
