### ISSUE TITLE
Gedemin_D7. Форма документов. Шапка. Неверный цвет панели и шрифт в полях

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4346]
_**Исследователь → Материальный склад → 01. Накладная на получение материалов, ОС, МБП.**_

На форме шапки документа указан неверный цвет панели и шрифт в полях:
![image](https://user-images.githubusercontent.com/11497453/226600589-f4973284-aba4-472c-9d0a-d98fe8d9d430.png)
_**Рис. 1.**_

**Comment by gsbelarus** [comment]
Напишите разработчику что именно неверное.

**Comment by NikolayUkleyko** [comment]
На старом **Gedemin** на форме и полях установлен шрифт ”Tahoma” и он отображается верно.
В **Gedemin_D7** шрифт формы и полей по умолчанию ”MS Sans Serif”.

На старом **Gedemin** цвет панелей темно серый, а в **Gedemin_D7** – светло серый.
Не могу найти параметр для настройки.

**Comment by NikolayUkleyko** [comment]
Проверено.
@Polfath , спасибо !

Вопрос по шрифтам форм и полей решен.
Вопрос по цветам панелей не решен.

**Comment by NikolayUkleyko** [comment]
По цветам панелей.
@Polfath мне подсказал, что это особенность Delphi7.
Если, так и есть – тему можем закрывать.
@gsbelarus , пожалуйста, что скажете ?

**Comment by MIchaelShoihet** [comment]
Пока работаем над этим вопросом

**Comment by AliakseiDanilchyk** [comment]
По шрифтам тоже не везде решено. Вот пример. Там раньше был шрифт Tahoma. Сейчас из-за того, что шрифт поменялся, не вмещается label. Возможно, здесь не исправилось, потому что установлен стиль Bold
![Без имени](https://user-images.githubusercontent.com/11484894/231471296-8b638998-fd62-4ed3-9929-3eaa8c8cb7a4.jpg)

**Comment by Polfath** [comment]
Сделал. Только с жирным воспроизвести не удалось. Просьба, у кого всплывет похожая картинка сказать на какой базе и в каком документе. Я посмотрю. Светом закладок и шрифтом поменял везде, где нашел. Если куда-то не добрался, говорите, поправлю и там.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

Есть недочет.
На формах документов, где в структуре указана только шапка (без позиции) шрифты не оригинальные:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/3afc483c-c2e2-4628-9c90-05e85fbb4534)
_**Рис. 1.**_

**Comment by NikolayUkleyko** [comment]
_**Исследователь → Справочники → Справочник ТМЦ → закладка ”Статистика”, ”Общепит”.**_

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/fdf19b2f-cd7e-4343-bba1-df9072768df0)
_**Рис. 1.**_

Другие закладки отображаются корректно.
@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста, поправь и **gdc_frmAttrUserDefined**.

**Comment by Polfath** [comment]
Сделал

**Comment by gsbelarus** [comment]
@NikolayUkleyko проверь, закрой

**Comment by NikolayUkleyko** [comment]
Проверено.
@Polfath , пожалуйста, поправь.

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/1268d657-aba7-420e-8beb-483e05226d8c)
_**Рис. 1.**_

По шрифтам.
Если, цвет шрифта **_clWindowText_**, то жирное начертание не передается.
Иначе, передается.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста, поправь для формы **gdc_dlgBankStatement** цвет панели.

**Comment by Polfath** [comment]
Поправил

**Comment by NikolayUkleyko** [comment]
> _”Поправил”_

Проверено.
Работает корректно.
@Polfath , спасибо !

@Polfath , пожалуйста, посмотри **gdc_dlgUserDocumentLine**.
_Исследователь → Банк и касса → Выписки по р/с → Позиция → Разноска позиции выписки_:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/6ab578eb-609d-4cd3-a61c-201fcc240d99)

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
Проверено на текущем **gedemin.exe** (_https://discord.com/channels/1104433152576991282/1105765965398024204/1183738866079903864_).

Неверные шрифты по некоторым документам следующих типов:
1. _Банковская выписка → Позиция разноски выписки_ – **UserDocumentLine**.
2. _Взаимозачет_ – **UserSimpleDocument**.

@Polfath , пожалуйста, посмотри.
