### ISSUE TITLE
Перемещение по форме в режиме ее редактирования

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4350]
Перемещение по форме в режиме ее редактирования
В режиме редактирования экранной формы (комбинация клавиш Ctrl + Alt +E).
Если нужный нам компонент не попадал в видимую область формы, то мы выделяли на форме какой-либо компонент в видимой области формы и щелкали мышью по стрелке в полосе прокрутки. При этом перемещались по форме в направлении стрелки.
В новом exe этого не происходит. Сейчас при щечке по стрелке в полосе прокрутки перемещается только на пару пикселей.
![Редактор форм](https://user-images.githubusercontent.com/11484894/226630188-c9be6933-40f9-4b94-8a4a-49be34d9c097.jpg)

**Comment by NikolayUkleyko** [comment]
Вероятно что-то новое с панелями на формах.
Сейчас полоса прокрутки не перемещается при клике по стрелке (1).
Для перемещения полосы прокрутки можно нажимать на область под полосой прокрутки (2).
![image](https://user-images.githubusercontent.com/11497453/226649790-fcefa09d-a703-4bbb-9bda-e34f9a90386e.png)

**Comment by Polfath** [comment]
Коля прав. Нужно кликать не по стрелкам перемещения, а полосе. И будет счастье)))

**Comment by gsbelarus** [comment]
а что со стрелками случилось?

**Comment by Polfath** [comment]
ХЗ. Это at_container. Я туда лазил только для изменения Font-a, Ctl3D и Color на OnCreate

**Comment by gsbelarus** [comment]
надо глянуть. это стандартный контрол. он не может просто так перестать работать. может там шаг для стрелки нулевой стоит?

**Comment by Polfath** [comment]
Сделал даже лучше, чем было. Раньше скролить можно было только вниз, сейчас - вниз и вверх.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
