### ISSUE TITLE
Не работает копирование и вставка в SQL редакторе

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4351]
Ctrl + C
Ctrl + V
Ctrl + X
не работают в окне "SQL редактор"

**Comment by NikolayUkleyko** [comment]
Пожалуйста, дополнительный вариант:
• **Ctrl + Insert** – скопировать фрагмент;
• **Shift + Insert** – вставить фрагмент;
• **Shift + Delete** – вырезать фрагмент.

**Comment by alexandra-gsoftware** [comment]
Также, если в скрипте сделать "скопировать sql", то в sql редакторе во всплывающем меню кнопка "вставить" неактивна.

**Comment by Polfath** [comment]
Сделал. В понедельник отдам

**Comment by NikolayUkleyko** [comment]
Проверено.

> _Ctrl + C
> Ctrl + V
> Ctrl + X
> не работают в окне "SQL редактор"_

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/0d167abe-185a-4657-875e-c444c8387d31)

Не работает.

-----

> _”Также, если в скрипте сделать "скопировать sql", то в sql редакторе во всплывающем меню кнопка "вставить" неактивна.”_

Работает корректно.

**Comment by gsbelarus** [comment]
@NikolayUkleyko перепроверь и закрой

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

@gsbelarus , закрывайте.
