### ISSUE TITLE
В редакторе скрипт-объектов пропадает введенная несохраненная информация при переходе на другую вкладку

### ISSUE THREAD

**Issue by SadovskayaNatalia** [GoldenSoftwareLtd/gedemin#4352]
Если что-нибудь ввести редакторе скрипт объектов
![image](https://user-images.githubusercontent.com/118506567/226831544-f22aa50f-c3df-4f33-a975-46cf9871d53f.png)

и перейти на другую вкладку 

![image](https://user-images.githubusercontent.com/118506567/226831714-bcec26d9-de6b-44ac-b13b-63d2f83e1855.png)

А потом вернутся, то вся введенная несохраненная информация пропадает

![image](https://user-images.githubusercontent.com/118506567/226831915-c9111ff8-dad4-4d32-b6fb-2859b07a7f9b.png)

**Comment by gsbelarus** [comment]
Если есть изменения на вкладке, то при переходе надо спрашивать: Сохранять или нет. Сохранят молча будет плохо, так как можно случайно сохранить ошибку в макросе и она вылезет у пользователя в самый не нужный момент.

**Comment by SadovskayaNatalia** [comment]
А так как работало на старом экзешнике не подходит? В процессе можно было переключаться на другие вкладки и копировать с них часть скриптов, а потом, когда нужно, сохраниться.  А сейчас нельзя оставить часть недописанного скрипта, что бы добавить в него что-то еще, потому что когда переключаешься - все пропадает. А сохранять неготовый скрипт тоже совсем плохо, и писать вручную то что можно взять откуда-то готовое нерационально.

**Comment by YRozmysl** [comment]
согласен, то как работало это на старом exe вполне устраивало

**Comment by gsbelarus** [comment]
тогда вернем как было на старом

чц, 13 кра 2023, 08:07 карыстальнік Yury Rozmysl ***@***.***>
напісаў:

**Comment by NikolayUkleyko** [comment]
Проверено.
Сейчас при переходе с одной вкладки на другую вкладку выполняется автоматическое сохранение изменений.
Просили в такой ситуации изменения на вкладках не сохранять.

@Polfath , пожалуйста, посмотри.

**Comment by gsbelarus** [comment]
при переходе между вкладками не надо автоматом сохранять в бд. там может быть недописанный код, который начнет кидать ошибки у всех пользователей.

**Comment by NikolayUkleyko** [comment]
> _”при переходе между вкладками не надо автоматом сохранять в бд. там может быть недописанный код, который начнет кидать ошибки у всех пользователей.”_

Верно.

**Comment by Polfath** [comment]
Переделал без поста
