### ISSUE TITLE
После редактирования экранной формы новым exe она не открывается на старом

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4353]
При открытии такой формы старым exe возникает ошибка
![errror](https://user-images.githubusercontent.com/11484894/226836223-7aa75b7c-ffb4-488a-81e7-1780f210f3c1.jpg)
Это происходит из-за того , что свойство **Caption**  записывается в хранилище таком виде:
![Хранилище](https://user-images.githubusercontent.com/11484894/226836907-301c493c-35e4-40ba-91bd-23e99783358a.jpg)

**Comment by gsbelarus** [comment]
Надо определить на какое именно проперти ругается. Посмотреть что с ним не так.

**Comment by gsbelarus** [comment]
Если вопрос со строками, то как вариант, при сохранении сначала вызывать функцию преобразования DFM в текст. Затем в этом тексте последовательности #XXXX менять на кириллические символы. Например, #1042 это большая буква В.

https://www.codetable.net/decimal/1042

Не забыть про буквы белорусского алфавита! и украинского.

**Comment by Polfath** [comment]
Можно тестить

**Comment by AliakseiDanilchyk** [comment]
Последим exe ошибка не воспроизводится. Можно закрывать.

**Comment by yoannawx** [comment]
та же проблема с формами при обновлении / установке пи на базу новым ехе
![image](https://user-images.githubusercontent.com/11497358/230887662-f00b54f5-afab-4e06-98dc-eb9a216bfa1e.png)

**Comment by gsbelarus** [comment]
@Polfath 

После исправления в одном месте поищите функцию по всем исходникам. Там, насколько я помню, что-то типа DFM2Text была. Вы в одном месте исправили, а она еще и в других использовалась. Теперь вылазит.

**Comment by Polfath** [comment]
Это исправлено предыдущим исправлением. Сейчас баг не воспроизводится.
