### ISSUE TITLE
Gedemin_64. Гриды. Форма остатков. После формирования формы возникли вопросы

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4354]
_**Исследователь → Материальный склад → Отчеты по складу → Остатки по материалам и МБП.**_

1. Подключились к БД под Gedemin_64.
2. Сформировали указанную форму.
3. Закрыли БД.
4. Подключились к БД под Gedemin.
5. При формировании указанной формы:
• программа отображает окно с сообщением об ошибке;
• грид слетает, т.е., возвращается в состояние по умолчанию.

![image](https://user-images.githubusercontent.com/11497453/226852173-d13e1cab-f6e3-43e2-954a-8d6e33971727.png)

**Comment by MIchaelShoihet** [comment]
Это все то что нашел Алексей issue  #4353. Пока нет совместимости, сохраненные формы в новом не откроются в старом. Будет исправлено

**Comment by NikolayUkleyko** [comment]
_> Это все то что нашел Алексей issue #4353. Пока нет совместимости, сохраненные формы в новом не откроются в старом. Будет исправлено_

Хорошо, Михаил Юрьевич.
