### ISSUE TITLE
Проблемы с формой, вызванной из документа

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4355]
Примеры, на которых можно увидеть: 
1.Комплит (lepel/3053:g:\Etalon\ETALON_COMPLETE.FDB): макрос "Добавить форму в настройку", который можно вызвать из любого документа.
2.Общепит (lepel/3053:g:\Etalon\ETALON_MENU_BACK.FDB). макрос "Подобрать цены", который можно вызвать, например, из документа Общепит-Производство-Заказ-наряд.

Рассмотрим на втором примере.
Из макроса создается форма (set Form = Creator.GetObject(OwnerForm, "usrf_MN_PILOTGOOD", "usrf_MN_PILOTGOOD").
При открытии формы ее события, которые пытаются вызвать Sender.Owner, выдают ошибку 
![image](https://user-images.githubusercontent.com/11497358/226852448-23dd1bb7-ff5a-4488-97a6-11a6d9b879e4.png)
![image](https://user-images.githubusercontent.com/11497358/226852555-40b423f6-13ad-4c81-aa61-7622d1b35b13.png)

**Comment by Polfath** [comment]
Можно пробовать проверять

**Comment by yoannawx** [comment]
проверено
