### ISSUE TITLE
Переход на строку по ошибке в редакторе скрипт-объектов

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4357]
Если при работе программы возникает ошибка, переходим в редактор скрипт-объектов по кнопке Редактировать окна Ошибка.

![image](https://user-images.githubusercontent.com/11497358/227243335-34813815-972b-4026-9001-ad432448a4f4.png)

 При этом оказываемся на выделенной строке, на которой произошла ошибка. 

![image](https://user-images.githubusercontent.com/11497358/227243409-1208db19-794a-436e-b887-e4a0ed7e5f5f.png)

Дальше мы уходим с этой строки и двигаемся по скрипту.

![image](https://user-images.githubusercontent.com/11497358/227243513-9e85c1d9-ba1a-48ad-bd61-fd10be306bc9.png)

Чтобы вернуться на ошибку, кликаем в окне Сообщения на строку с текстом ошибки. При этом курсор возвращается в начало скрипта, а не на строку с ошибкой, как раньше.

**Comment by AliakseiDanilchyk** [comment]
Такое же поведение при выполнении операции "Поиск в базе данных" в редакторе скрипт-объектов.  В окне результатов поиска выполняем двойной клик. При этом переходит на первую строку скрипта, а не на строку содержащую искомый результат.

**Comment by Polfath** [comment]
Готово

**Comment by yoannawx** [comment]
проверено
