### ISSUE TITLE
Общие. При смене рабочего стола другие открытые формы остаются открытыми

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4358]
При смене рабочего стола остаются открытыми другие открытые формы.
Я понимаю, что при смене рабочего стола ожидаем закрытие всех форм и открытие только форм из выбранной конфигурации рабочего стола.
Пожалуйста, подскажите, так сделано намеренно ?

**Comment by gsbelarus** [comment]
надо проверить. какие именно формы остаются?

**Comment by NikolayUkleyko** [comment]
Открыли любые документы, формы.
Например.
1. **_01. Накладная на получение материалов, ОС, МБП_**, **_Остатки по материалам и МБП_**.
2. Затем, переключаем рабочий стол, в котором сохранены документы **_03. Отпуск товара на сторону (оптовая торговля)_**, **_11. Реализация товаров в розницу_**.

В результате, открыты документы и формы **_01. Накладная на получение материалов, ОС, МБП_**, **_Остатки по материалам и МБП_** и **_03. Отпуск товара на сторону (оптовая торговля)_**, **_11. Реализация товаров в розницу_**.

По идее, при переключении рабочего стола документы и формы **_01. Накладная на получение материалов, ОС, МБП_**, **_Остатки по материалам и МБП_** должны закрыться и открыться только **_03. Отпуск товара на сторону (оптовая торговля)_**, **_11. Реализация товаров в розницу_**.

**Comment by AliakseiDanilchyk** [comment]
Когда-то давно я поднимал такой вопрос. Возможно, даже было issue. Тогда было сказано, что так задумано

**Comment by NikolayUkleyko** [comment]
> _”Тогда было сказано, что так задумано”_

Ясно.
Можно предусмотреть настройку – соответствующую галку ”Закрывать все формы при смене рабочего стола” в параметрах платформы (_**Сервис → Параметры... → Подтверждения**_).

**Comment by Polfath** [comment]
Сделать настройку  ”Закрывать все формы при смене рабочего стола”? @NikolayUkleyko

**Comment by NikolayUkleyko** [comment]
> Сделать настройку ”Закрывать все формы при смене рабочего стола”? @NikolayUkleyko

Да, верно.
Закрыли открытые формы и открыли новые формы из рабочего стола.

**Comment by Polfath** [comment]
Сделал настройку

**Comment by NikolayUkleyko** [comment]
@Polfath , спасибо за доработку.
Проверено.
Пожалуйста, предложения:

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/8a715556-79ee-49c4-9c7e-4fa953268c75)
_**Рис. 1.**_

1. По умолчания галка проставлена по рассматриваемому реквизиту.
   При смене рабочего стола сообщения о закрытии открытых форм нет.
   После, снятия/простановки галки программа выдает соответствующее сообщение.
2. Возможно стоит предусмотреть возможность при переключении рабочего стола не отображать сообщение о закрытии открытых форм.

**Comment by Polfath** [comment]
Сделал п.п. 1, 2

**Comment by NikolayUkleyko** [comment]
По умолчанию в параметре **Закрывать все формы при смене рабочего стола** галка не будет установлена.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
Доработки по данной теме не вошли в **gedemin.exe Delphi 7**.
@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
