### ISSUE TITLE
Грид. Отображение в автофильтре фрагмента текста для полей с доменом ”DBLOBTEXT80_1251”

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4359]
Можно ли в гриде для полей с доменом **DBLOBTEXT80_1251** предусмотреть отображение в автофильтре записей с первыми 100 символами ?
Сейчас автофильтр не отображает записи, но поиск работает корректно:
![image](https://user-images.githubusercontent.com/11497453/227251368-08260567-6bea-4fce-a638-97b11b77db5c.png)

**Comment by gsbelarus** [comment]
надо быть осторожным с размером блобов. они могут быть очень большими и их считывание для отображения в выпадающем списке сожрет много памяти. может добавить какой счетчик и прекращать считывание после определенного размера. собственно, именно по этим соображениям и не делали изначально. и не факт, что надо делать сейчас.

**Comment by NikolayUkleyko** [comment]
Хорошо, @gsbelarus .
