### ISSUE TITLE
Грид. Предусмотреть сообщение при копировании нерассчитанных итогов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4362]
**_Грид → Контекстное меню → Скопировать итоги…_**

При невыполненном расчете итоговой строки копируется только итоговая сумма по видимой части грида:
![image](https://user-images.githubusercontent.com/11497453/227258901-f0c50caf-c136-4c12-8e1f-42cb39794a76.png)

При копировании нерассчитанных итогов предлагаю добавить следующее сообщение:
```ruby
”Пожалуйста, в итоговой строке нажмите ”Рассчитать...” и повторите копирование.”.

**Comment by Polfath** [comment]
@NikolayUkleyko Поясни

**Comment by Polfath** [comment]
Добавил сообщение

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
