### ISSUE TITLE
Инспектор объектов. Items. Увеличить размеры окна выбора команд

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4363]
_**Ctrl + Alt + E → Инспектор объектов → Items.**_

Пожалуйста, увеличьте размеры (по высоте и ширине) окна выбора команд:
![image](https://user-images.githubusercontent.com/11497453/227263685-3a91cf05-46f2-40ae-a9d5-70b4260051ff.png)

**Comment by gsbelarus** [comment]
а как потом такая длинная команда в меню выглядит? у любой системы есть
технические пределы  в тч и по длине команд в меню.

чц, 23 сак 2023, 17:04 карыстальнік NikolayUkleyko ***@***.***>
напісаў:

**Comment by NikolayUkleyko** [comment]
Здесь достаточно немного поменять размеры.

**Comment by Polfath** [comment]
Увеличил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
