### ISSUE TITLE
Склад. Выбор из остатков ТМЦ. Предусмотреть возможность отмены при множественном выборе недостающих остатков

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4364]
_**Исследователь / Материальный склад / 02. Внутренние перемещения материалов, МБП.**_

При множественном выборе из остатков ТМЦ, которых недостаточно предусмотреть вариант, **отмены выбора из остатков** или **выбор только достаточных остатков**.
Таким образом, не надо будет нажимать в окне сообщения по каждой записи на кнопку **OK**:
![image](https://user-images.githubusercontent.com/11497453/227268827-b1b378d7-5a20-41cb-ae02-319f327dbbbc.png)

**Comment by Polfath** [comment]
Обсудили. Вроде как это разумно. @NikolayUkleyko Коля, прикрой таску, а то я об нее спотыкаюсь.
