### ISSUE TITLE
Gedemin.exe под Delphi 7 и файлы FireBird x64

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4365]
Я понимаю, что новый Gedemin.exe компилируется, как 64-х разрядный файл.
Соответственно, в папке с Gedemin.exe необходимо рядом располагать и 64-х разрядные файлы, а не 32-х.
Верно ли, @gsbelarus ?

**Comment by gsbelarus** [comment]
Нет. Новый Гедымин 32-х битное приложение. Просто откомпилирован с помощью Delphi 7, а не Delphi 5. FB файлы все остаются прежними.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , благодарю за интересную информацию !
👍
