### ISSUE TITLE
Слетают права на исключения после обновления ехе для базы под фб3

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4366]
На ВолкМК выявлена потеря прав пользователей на EXCEPTIONы:
- INV_E_DONTREDUCEAMOUNT
- INV_E_INSUFFICIENTBALANCE

**Comment by YRozmysl** [comment]
тут дело, вроде как, только в том, что ФБ 3.0

**Comment by MIchaelShoihet** [comment]
Да под 3.0 надо делать grant для exception. Просто exception появился а грант не сделался и это должен делать Гедымин

**Comment by Polfath** [comment]
Сделал создание грантов на Exception при создании его и при восстановлении базы, если версия Firebird >= 3
