### ISSUE TITLE
Общие. Мастер установок. Ошибка при открытии документов после пересохранения настроек

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4367]
**Очередность действий:**
1. Подключились к БД под gedemin.exe → открыли документ (любой документ, форма остатков и т.д.) → F10 → выполнили настройку, включая заполнение закладки ”Условия” → Ok.
2. Подключились к БД под gedemin_D7.exe → открыли документ → F10 → Ok. **Выполнили только пересохранение грида.**
3. Подключились к БД под gedemin.exe → открыли документ → сообщение об ошибке (см. **Рис. 1**) → Ok → документ открывается:
![image](https://user-images.githubusercontent.com/11497453/229153528-c6538eca-653b-441a-9890-52a70391f2ea.png)
**Рис. 1.**

**Перечень недочетов:**
1. Закладка ”Таблица”. Почему-то снята галка по реквизиту ”Горизонтальные линии таблицы” и установлена галка на реквизите ”Показывать строку итого”.
2. Закладка ”Колонки”. Почему-то добавляются для отображения ненужные колонки (некоторые колонки).
3. Закладка ”Колонки”. Почему-то снята галка по реквизиту ”Расширенное заглавие колонки”.
4. На закладке ”Условия” добавляется пустое условие (см. **Рис. 2**):
![image](https://user-images.githubusercontent.com/11497453/229488536-aff18b01-a99c-463c-b6ec-dc317730e306.png)
**Рис. 2**

При сохранении настроек мастера установок программа отображает соответствующее сообщение (см. **Рис. 3**):
![image](https://user-images.githubusercontent.com/11497453/229488696-1b631f4e-9e37-454a-b76a-189131e3b67b.png)
**Рис. 3**

**Comment by AliakseiDanilchyk** [comment]
Похоже, новый exe некорректно сохраняет грид.
В моем случае это выглядит так (все шаги на exe Delphi 7).

1. Есть грид с количеством видимых колонок 10.
2. Через мастер установок делаю видимой еще одну колонку.
3. Переоткрываю форму - теперь в гриде только 5 видимых колонок.

**Comment by AliakseiDanilchyk** [comment]
Есть подозрение, что подхватывается грид другого пользователя.

**Comment by NikolayUkleyko** [comment]
Обновил https://github.com/GoldenSoftwareLtd/gedemin/issues/4367#issue-1649499656.

**Comment by Polfath** [comment]
Проверьте

**Comment by AliakseiDanilchyk** [comment]
С видимостью колонок проверил. Все ок.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
