### ISSUE TITLE
Ошибка SQL редактора на вкладке Транзакция

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4368]
В окне SQL редактора при переключении на вкладку "Транзакция" возникает ошибка.
![Без имени](https://user-images.githubusercontent.com/11484894/230574657-3ed7f403-e2a4-4483-a3d7-827df912e682.jpg)

**Comment by AliakseiDanilchyk** [comment]
Но возникает не всегда. Из 4-х баз, где проверялось выскакивает на 2-х

**Comment by gsbelarus** [comment]
Надо будет показать @Polfath конкретные БД, где появляется.

**Comment by Polfath** [comment]
@AliakseiDanilchyk дайте базы

**Comment by gsbelarus** [comment]
@AliakseiDanilchyk нужны базы

**Comment by AliakseiDanilchyk** [comment]
Пробую повторить на 5-ти разных базах - ошибка не возникает. Может полечилось в какой-то из предыдущих версий exe. Наверное, можно закрыть
