### ISSUE TITLE
Проблема с передачей в отчет параметров массивом

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4369]
Можно посмотреть на любой базе, где используется конструкция 
call System.ReportSystem.BuildReportWithParam(), в которую передается массив.
Отчет не строится, ошибка
![image](https://user-images.githubusercontent.com/11497358/230612894-d0b05e29-218e-4e8c-813c-36b16474efa2.png)

Например, на базе brutto/3053:k:\Bases\belkalii\restoran\BOFFICE_49.FDB

Пример 1. Общепит - 05.Закрытие дня - Накопитель
Вызываем отчет Отчет по накопителю за период
![image](https://user-images.githubusercontent.com/11497358/230613169-8274cba3-651f-40cc-a21c-21b6460f1dbf.png)

Пример 2. Общепит - 01.Складской учет - Общепит остатки - Остатки общепит с ценами продаж
Формируем остатки (**в момент построения остатков можно увидеть проблему переключения на другое окно, которая встречается на новом ехе при выполнении долговыполняющихся функций, таких как синкронизация пи, например**) 
и вызываем отчет Карточка по сырью
![image](https://user-images.githubusercontent.com/11497358/230613559-f9c27399-cb9d-44f5-b16d-85af18ba8145.png)

**Comment by Polfath** [comment]
Ошибку поправил

**Comment by yoannawx** [comment]
проверено
