### ISSUE TITLE
Ошибка при определении AsVariant

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4370]
После выполнении запроса
ibsqlGetID.SQL.Text = "SELECT DATEDIFF(MILLISECOND, CAST('01.01.1900  00:00' AS TIMESTAMP), CURRENT_TIMESTAMP)  FROM RDB$DATABASE"
вычисление ibsqlGetID.Fields(0).AsVariant кидает ошибку
![image](https://user-images.githubusercontent.com/11497358/230634462-618cf8d7-5853-4cf1-b3ee-9af847d82471.png)

Пример. brutto/3053:k:\Bases\belkalii\restoran\BOFFICE_49.FDB
функция web_callHandReference

**Comment by Polfath** [comment]
Поправил

**Comment by yoannawx** [comment]
проверено
