### ISSUE TITLE
Передача параметров в функцию ExecSingleQueryResult

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4371]
Раньше при передаче в конструкцию типа:
  call gdcBaseManager.ExecSingleQueryResult("select FIELD from TABLE WHERE ID = :id", ID, Res, ReadTransaction)
одиночного параметра функция возвращала результат. 
В новом ехе для передачи даже одиночного параметра требуется массив:
  call gdcBaseManager.ExecSingleQueryResult("select FIELD from TABLE WHERE ID = :id", Array(ID), Res, ReadTransaction),
иначе - ошибка
![image](https://user-images.githubusercontent.com/11497358/231397389-8ae5a38c-3967-4936-8188-9e96fda3507a.png)

Пример: на любой торговой базе (напр., brutto/3053:k:\Bases\belkalii\restoran\BOFFICE_49.FDB)
Торговля - Накладная на получение товара: зайти в редактирование документа и изменить ценовой показатель. Функция inv_socRound, использующая данную конструкцию, выдаст ошибку.

**Comment by gsbelarus** [comment]
Надо вернуть как было. Менять нельзя, может много кода старого полететь.

**Comment by Polfath** [comment]
починил

**Comment by yoannawx** [comment]
проверено
