### ISSUE TITLE
Проблема с обновлением панелей и кнопок на форме Закрытие дня

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4373]
Форма есть на любой базе общепита.
![image](https://user-images.githubusercontent.com/11497358/232011049-aa98fa25-ff41-4dc7-939f-5a516493bdfc.png)
На новом ехе некорректно работает обновление панелей и кнопок (видимость, состояние) при открытии формы и при выполнении экшенов,

**Comment by Polfath** [comment]
В 7 версии Delphi у компоненты TAction появилось св-во GroupIndex. Если Action привязан к компоненте со своим GrouopIndex, он перекрывается тем, который у Action и работать как хотелось бы не будет. Для корректной работы SpeedButton нужно Action-ам, которые к ним привязаны присвоить такой же GroupIndex

**Comment by gsbelarus** [comment]
@Polfath 

надо поиском пройтись по всем ПИ в gedemin-apps и поискать все формы со SpeedButton. составить список здесь, включая и эту форму жанны. потом пройтись и подправить их. и только потом можно будет закрывать issue.

получается, что эта форма старым экзешником уже потом не откроется? ругнется на несуществующее свойство?

**Comment by Polfath** [comment]
Старой не откроется не только эта. Там у многих компонент новы свойства появились

**Comment by gsbelarus** [comment]
тогда надо какая-то стратегия как мы будем на новый экзешник и новые ПИ переходить

**Comment by Polfath** [comment]
Формы со SpeedButton.GroupIndex <> 0:

\gedemin_apps\Гостиница\GS.Гостиница.Общие документы.yml                 
    gdc_dlgAttrUserDefinedUSR_HT_NUMBERSTATEDOC: Tgdc_dlgAttrUserDefined
\gedemin_apps\Меню\2014 Бэк-офис\GS new. Общепит бэк. Закрытие дня.yml   
    usrf_bri_endday: TgdcCreateableForm
\gedemin_apps\Общие\GS.Общие.Setting_Helper.yml
    usrf__gsD_AddFrmInSetting: TgdcCreateableForm
\gedemin_apps\Санаторий\GS.Санаторий.П.Документы.yml
    gdc_dlgAttrUserDefinedUSR_HT_RES_POSTINGLIST: Tgdc_dlgAttrUserDefined
\gedemin_apps\Санаторий\WESTA\VESTA.Отдел продаж.Форма резервирования RAChart.yml
    usrf_san_admin_RAChart: TgdcCreateableForm
\gedemin_apps\Санаторий\WESTA\VESTA.Отдел продаж.Форма резервирования.yml
    usrf_san_admin: TgdcCreateableForm

**Comment by yoannawx** [comment]
После присвоения  Action-ам GroupIndex, соответствущие SpeedButton, на новом ехе форма работает корректно.

**Comment by yoannawx** [comment]
!!! На ехе от 10.07 изменение у Action-ов значения GroupIndex не сохраняется после сохранения формы

**Comment by yoannawx** [comment]
все работает корректно. мой косяк.
