### ISSUE TITLE
При поиске в базе данных в редакторе скрипт-объектов невозможно перейти на найденную строку

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#4374]
Запускаем поиск в базе данных в редакторе скрипт-объектов, с галочкой Поиск в тексте. Получаем список того, что найдено в окне "поиск и замена".

Раньше двойным кликом можно было перейти на конкретную найденную строку, а сейчас открывается нужная скрипт-функция, но курсор стоит на первой строке, а не на той, которую нашли :(

**Comment by AliakseiDanilchyk** [comment]
Это уже есть в  #4357

**Comment by NikolayUkleyko** [comment]
https://github.com/GoldenSoftwareLtd/gedemin/issues/4357#issuecomment-1504823612
