### ISSUE TITLE
TgdcInvGoodRemains: после переприсвоения gdcDocumentLine значения параметов типа Currency конветируются в строки

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#4375]
Вот такой код работает:
```vb
  dim gdcInvRemains
  set gdcInvRemains = Creator.GetObject(nil, "TgdcInvGoodRemains", "")
  gdcInvRemains.ExtraConditions.Add(" C.USR$INV_COSTBUYNCU = :Cost ")
  '.......
  gdcInvRemains.ParamByName("Cost").AsVariant = 6.66
  gdcInvRemains.Open 
```
А вот такой уже нет:
```vb
  dim gdcInvRemains
  set gdcInvRemains = Creator.GetObject(nil, "TgdcInvGoodRemains", "")
  gdcInvRemains.ExtraConditions.Add(" C.USR$INV_COSTBUYNCU = :Cost ")
  '.......
  gdcInvRemains.ParamByName("Cost").Value = 6.66
  '.......
    gdcInvRemains.Close
    gdcInvRemains.gdcDocumentLine = nil
    gdcInvRemains.gdcDocumentLine = gdcDO
    gdcInvRemains.GoodKey = GoodKey
    
  gdcInvRemains.Open 
```
Причем ошибка звучит как Conversion error from string "6,66" и происходит на  gdcInvRemains.Open. Если вместо 6.66 будет целое число, все пройдет без ошибки.
Параметр можно присваивать AsVariant, AsCurrency - не важно. После перевязывания остатков к новой шапке 6.66 превратится в "6,66".

Ошибка всегда была, просто обычно дробные параметры перебиваются после перехода на новую шапку в соответствии с логикой скрипта.

Разделитель дроби на компе — запятая.

**Comment by gsbelarus** [comment]
т.е. проблема именно в Value?

**Comment by alexandra-gsoftware** [comment]
Проблема в том, что значение параметра с дробной частью после перепривязывания остатков к новой шапке из числа превратилось в строку. Скорее всего, целые числа тоже превращаются в строки, но потом успешно конвертируются обратно.

**Comment by Polfath** [comment]
@alexandra-gsoftware На какой базе и в какой задаче исследователя возникает баг? Нужно попытаться воспроизвести его, чтобы пофиксить.

**Comment by gsbelarus** [comment]
@MIchaelShoihet может с примером кода помочь

**Comment by Polfath** [comment]
Я воспроизвел на произвольной базе код:
```vb
sub ScriptFunction265360837_2031603836
  set Creator = new TCreator
  dim gdcInvRemains
  set gdcInvRemains = Creator.GetObject(nil, "TgdcInvGoodRemains", "")
    gdcInvRemains.ExtraConditions.Add(" C.USR$INV_COSTBUYNCU = :Cost ")
  gdcInvRemains.ParamByName("Cost").Value = 6.66
  gdcInvRemains.Open
end sub
```
bug не воспроизводится. Вероятно он был устранен при лечении какого-то из предыдущих. Нужно перепроверить

**Comment by gsbelarus** [comment]
@alexandra-gsoftware можете перепроверить?
