### ISSUE TITLE
Замена шрифта в триггерах и процедурах при разархивировании бд с галками Перекомпилировать процедуры (фб3)

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4376]
При восстановлении базы из архива на фб3 с галками Перекомпилировать процедуры русский шрифт в триггерах и процедурах заменяется на ???????????

**Comment by gsbelarus** [comment]
Только эксперементируйте на самой маланькой БД. На эталоне. А то будете какой мясокомбинат бэкапить-ресторить -- по три дня на круг терять.

**Comment by Polfath-gsbelarus** [comment]
Можно проверять

**Comment by gsbelarus** [comment]
тэгайте человека @yoannawx

**Comment by yoannawx** [comment]
проверено, шрифт не заменяется
