### ISSUE TITLE
Общие. Хранилище. Предусмотреть параметр для перехода на указанную строку

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4377]
**_Сервис → Хранилище → Параметры._**

Пожалуйста, предусмотрите параметр для перехода на указанный номер строки:
![image](https://user-images.githubusercontent.com/11497453/232103080-8a01523b-8c78-4565-8e6b-478c3fd49fbd.png)
**_Рис. 1._**

Такое реализовано в Редакторе скрипт-объектов:
![image](https://user-images.githubusercontent.com/11497453/232103233-4fc1951d-59b7-435f-bf3a-02c8fdbbd7df.png)
**_Рис. 2._**

![image](https://user-images.githubusercontent.com/11497453/232103260-399a9af6-c295-4f57-9cda-8aba53ab7dbf.png)
**_Рис. 3._**

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
