### ISSUE TITLE
Общие. Поиск в базе данных. Предусмотреть отображение уникальных результатов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4378]
**_Редактор скрипт-объектов → Поиск в базе данных._**

Пожалуйста, предусмотрите дополнительную возможность поиска – отображение найденных функций, методов, классов и т.д. единожды.
То есть, не отображать фрагмент текста, в котором используется та или иная функция, метод, класс и т.д.

![image](https://user-images.githubusercontent.com/11497453/232463318-f4d230a2-2627-47b9-8a1b-739b54e80d1d.png)
**_Рис. 1._**

![image](https://user-images.githubusercontent.com/11497453/232463283-1673198f-6b4f-482f-b525-97ffa65ee0b2.png)
**_Рис. 2._**

Согласно данного примера, хорошо бы единожды отображать следующие объекты:
• FA_CalcAmort;
• FA_Options;
• TVBFA_Options.

**Comment by Polfath** [comment]
@NikolayUkleyko "хорошо бы единожды отображать следующие объекты " не камельфо. Искомый текст может встречаться в нескольких строчках кода

set Creator = new TCreator
set ibsql = Creator.GetObject(NULL, "TIBSQL", "")

показать нужно все, поскольку по двойному клику ты переходишь на нужную строку.
А вот чтобы одна и та же строка не отображалась несколько раз, если искомый текст там много раз встречается, это наверное разумно. Если такой вариант устроит, скажи, сделаю.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
После поиска очищается поле ”Искомый текст”.
В выпадающем списке перечень искомых значений сохраняется.

**Comment by Polfath** [comment]
Неоднократно повторял поиск. Всегда появляется предыдущий "Искомый текст"
???

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
