### ISSUE TITLE
Общие. Слияние. Доработки функционала

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4379]
Можно доработать стандартный функционал или предусмотреть отдельный функционал слияния (краткий).
Стандартное слияние вызывается через соответствующую кнопку на панели инструментов или при помощи ”горячих клавиш” **Ctrl+R**.
Краткий вариант слияния предполагается не делать доступным на панели инструментов, а сделать доступным только через отдельную комбинацию ”горячих клавиш”, например **Ctrl+Y**.

Предполагаемые доработки для функционала слияния записей:
1. **Увеличить размер формы просмотра данных**.
Исключаются накладки текста при просмотре.
![image](https://user-images.githubusercontent.com/11497453/232467235-bf48d3a7-1a6d-4845-8a3c-dd603af2f915.png)
**_Рис. 1._**

2. **Возможность быстрого слияния**.
Без дополнительных форм и сообщений:
![image](https://user-images.githubusercontent.com/11497453/232470120-e5876a77-e509-437a-a0d8-486119fb31bb.png)
**_Рис. 2._**
![image](https://user-images.githubusercontent.com/11497453/232470143-daa86630-de46-463f-8381-9a42b6c5f1d0.png)
**_Рис. 3._**
![image](https://user-images.githubusercontent.com/11497453/232470160-c328b6b8-493e-4f09-a13d-21af4acd206a.png)
**_Рис. 4._**
![image](https://user-images.githubusercontent.com/11497453/232470176-4874a906-da3e-4247-849f-d681eed92309.png)
**_Рис. 5._**
![image](https://user-images.githubusercontent.com/11497453/232470192-2744357a-2d91-431a-a699-4279ccaed662.png)
**_Рис. 6._**

В данном режиме будет достаточно указать:
• запись для слияния;
• сохранение или удаление исходной записи;
• кнопка выполнения слияния **OK** или **Отмена**.

Таким образом, уменьшится количество подтверждаемых форм с 6 до 1.

**Comment by Polfath** [comment]
Сделал
