### ISSUE TITLE
Бухгалтерия. Конструктор функций. Блок ”Пользовательский”. Пересохранить форму

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4380]
**_Исследователь → Бухгалтерия → Типовые хоз. операции._**

При выборе блока ”**Пользовательский**” по умолчанию открывается закладка ”**Скрипт**”.
Пожалуйста, пересохраните форму, чтобы умолчанию открывалась закладка ”**Общие**”.

![image](https://user-images.githubusercontent.com/11497453/232479426-10d3fa45-2f69-4234-b13f-043e4b7d9dec.png)
**_Рис. 1._**

![image](https://user-images.githubusercontent.com/11497453/232479497-21d1bf0f-b480-4b5d-8d82-03b380be5700.png)
**_Рис. 2._**

**Comment by Polfath** [comment]
Готово

**Comment by gsbelarus** [comment]
@NikolayUkleyko проверь, закрой

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

@gsbelarus , пожалуйста, закройте.
