### ISSUE TITLE
В редакторе скрипт-объектов не работает подстановка по ctrl + пробел

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#4381]
Раньше можно было ввести первые буквы глобального объекта или метода, нажать ctrl+space  , выбрать имя из списка и подставить. Например, набираем gdcBase, и можно выбрать gdcBaseList или gdcBaseManager.

Сейчас по ctrl+space открывается выпадающий список для выбора, как раньше, но при выборе ничего не выбирается, а несохраненные изменения в редакторе откатываются

**Comment by Polfath** [comment]
Сделал

**Comment by gsbelarus** [comment]
@alexandra-gsoftware проверьте и закройте
