### ISSUE TITLE
Пропала пиктограмма

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4382]
Delphi5 

![Screenshot 2023-04-26 160240_new](https://user-images.githubusercontent.com/11507129/234584672-1b75834d-4ffe-4a96-81f4-7b67996706de.png)

Delphi7

![Screenshot 2023-04-26 160355_old](https://user-images.githubusercontent.com/11507129/234584726-bfdff888-9070-41d1-ac5b-55280f640491.png)

**Comment by gsbelarus** [comment]
@Polfath всегда проверяйте пиктограмму и иконки в Исследователе. Они иногда слетают. Их надо руками возвращать на место.

**Comment by Polfath** [comment]
Здесь не понятно почему. Вероятно потому, что два проекта с одной иконкой компилятся практически из одной папки. Я поднял Гедемин 7 на виртуалке, там с иконкой все норм. Думаю, что после окончательного перехода разницы в иконках никакой не будет. Ждем перехода. Там посмотрим.

**Comment by YRozmysl** [comment]
исправлено
