### ISSUE TITLE
SQL редактор, выпадающий список полей

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4383]
Delphi7
![Screenshot 2023-04-27 093310_new](https://user-images.githubusercontent.com/11507129/234779405-5cb000d8-4f1f-4577-b166-d01fc68658ce.png)

Delphi5
![Screenshot 2023-04-27 093409_old](https://user-images.githubusercontent.com/11507129/234779457-71bbe50f-2302-4867-9abc-21144394e04b.png)

не раскрывается список доступных полей в таблице, после того, как поставил "."

**Comment by Polfath** [comment]
Сделал. Солью после вых.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
