### ISSUE TITLE
Ошибка при открытии экранных форм старым экзешником

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4384]
1. Снимаем последние настройки с github.
2. Загружаем их Delphi_7 на чистую, пустую эталонную базу. Например, пакет комплексную автоматизацию, или зарплату
3. Проверяем старым экзе Delphi_5. открываем в ветке исследователя любой документ и нажимаем создать. Например,    Итоговое начисление.  при открытии формы - ошибка.

![Screenshot 2023-04-27 103650](https://user-images.githubusercontent.com/11507129/234792842-cee73016-c868-4d83-a04b-5c13a831e92d.png)

4 .Если проводить проверку по п.3 новым экзе Delphi_7, то ошибок нет.

Причем, предварительно никакие настройки не снимались Delphi_7  и не забрасывались в репозиторий github. Там все настройки сформированы Delphi_5. По крайней мере, ЗПиОК - точно.

**Comment by gsbelarus** [comment]
Это вопрос со строковыми полями в DFM. Возможно мы не сможем обеспечить обратную совместимость. Перешел на новый экзешник -- работаешь уже только с ним.

**Comment by gsbelarus** [comment]
@YRozmysl перепроверить новейшим экзешником

**Comment by gsbelarus** [comment]
@YRozmysl проверь и закрой

**Comment by YRozmysl** [comment]
проблема осталась, проверял на 

Имя файла            = gedemin_7.exe
Расположение         = C:\Gedemin\
Дата файла           = 16.08.2023
Версия файла         = 2.9.5.11993
Описание             = Gedemin

**Comment by gsbelarus** [comment]
подойди к @Polfath и покажи ему прямо сейчас

**Comment by YRozmysl** [comment]
ошибку смоделировали с @Polfath пошагово.

**Comment by Polfath** [comment]
Похожая трабла была у @yoannawx (#4400). Если ПИ загрузили новым EXE?, в старом оно работать уже не сможет. Однако ПИ, сформированное новым EXE, прекрасно дружится со старым.

**Comment by YRozmysl** [comment]
получается, что, по-хорошему, надо будет, когда переход состоится  все пи пересохранить новым eхe, и закинуть в репозиторий.

**Comment by gsbelarus** [comment]
> Похожая трабла была у @yoannawx (#4400). Если ПИ загрузили новым EXE?, в старом оно работать уже не сможет. Однако ПИ, сформированное новым EXE, прекрасно дружится со старым.

ничего не понял. в этом предложении какие-то противоречивые утверждения. у нас есть новый экзе и старый экзе, пи полностью сделанные в новом и пи сделанные в старом, сохраненные на диске пи из старого и из нового, загруженные на базу пи старым и новым.

оформите это все в матрицу (таблицу) и в каждой клетке распишите что будет происходить. чтобы мы представляли что нас ждет при переходе.

так просто это оставлять нельзя. тогда надо вводить версию ПИ и проверять ее и блокировать загрузку.

жду таблицу.

@Polfath

**Comment by Polfath-gsbelarus** [comment]
Сохраняем ПИ старым EXE, запускаем новый, загружаем ПИ -- в новом все работает в старом перестает
Сохраняем ПИ новым EXE, запускаем старый, загружаем ПИ -- работает в обоих EXE
Сохраняем ПИ новым EXE, загружаем новым EXE -- в новом работает, в старом нет

**Comment by gsbelarus** [comment]
оформите как табличку. разберитесь как в маркдауне делаются таблички

**Comment by NikolayUkleyko** [comment]
№ п/п  | Сохранение ПИ | Загрузка ПИ | Результат
------------ | ------------- | ------------- | -------------
1                 | Сохраняем ПИ старым EXE или новым EXE | запускаем новый EXE, загружаем ПИ | в новом все работает в старом перестает
2                 | Сохраняем ПИ новым EXE | запускаем старый EXE, загружаем ПИ | работает под любым EXE
3                 |  Сохраняем ПИ новым EXE | загружаем новым EXE | в новом работает, в старом нет

**Comment by gsbelarus** [comment]
опять не понятно ничего. что значит "в новом все работает в старом перестает"? как перестает? в какой момент?

**Comment by YRozmysl** [comment]
Под "не работает" понимается то, что  не открывается форма документа и диалоговая форма не открывается. вываливается вот такое вот предупреждение 

![234792842-cee73016-c868-4d83-a04b-5c13a831e92d](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/b2b9d3c2-9f26-49c7-83af-90b8b4e55f54)

**Comment by gsbelarus** [comment]
Вот в эту таблицу разнесите что произойдет в каждом случае и почему.

|Операция | Старый EXE | Новый EXE|
|-----------|--------------|------------|
|Создание ПИ|      |      |
|Загрузка с диска старого ПИ|  |  |
|Загрузка с диска нового ПИ| | |
|Сохранение ранее загруженного старого ПИ| | |
|Сохранение ранее загруженного нового ПИ| | |

**Comment by NikolayUkleyko** [comment]
Операция  | Старый EXE | Новый EXE
------------ | ------------- | -------------
Создание ПИ | + | +
Загрузка с диска старого ПИ | + | + (далее работать с БД только под новым EXE)
Загрузка с диска нового ПИ |  + | +
Сохранение ранее загруженного старого ПИ | + | +
Сохранение ранее загруженного нового ПИ | + | +

**Comment by gsbelarus** [comment]
по этой таблице все выглядит ок. везде плюсы. но проблема то есть. напишите:

1) когда именно, при какой ситуации она возникает
2) почему? (технически описать)
3) какие могут быть решения

**Comment by YRozmysl** [comment]
1. Проблема возникает только в случае, если загружать новым exe  ПИ, которое было сформировано старым exe. В процессе загрузки такого ПИ новым exe нет ошибок, как и в работе этого ПИ под новым exe.  Однако, если подключиться старым exe к базе, на которую было установлено такое ПИ новым exe, то вываливаются при открытии формы предупреждения, см. прикрепленные выше скрины.

**Comment by gsbelarus** [comment]
уже лучше. теперь @Polfath должен объяснить почему так происходит и придумаем что делать.

**Comment by Polfath** [comment]
1. ошибка возникает в старом EXE после загрузки ПИ новым EXE
2. кодировка строковых данных отличается
3. либо работать в новом EXE, либо, если нужно работать в старом EXE, перезагрузить это ПИ старым EXE

**Comment by gsbelarus** [comment]
уже ближе:

1) что именно отличается в кодировке и вызывает ошибку?
2) в какой именно момент происходит перекодировка в другой формат?

**Comment by MIchaelShoihet** [comment]
Мне кажется что ничего не надо делать. Если ПИ загружено новым exe значит клиент работает с таким exe и все хорошо. Главное что ПИ созданное новым exe может быть загружено и правильно работает со старым exe.

**Comment by NikolayUkleyko** [comment]
> _”Главное что ПИ созданное новым exe может быть загружено и правильно работает со старым exe.”_

Это основное.
