### ISSUE TITLE
Ошибка в триггере BEFORE UPDATE документов трансформации

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4385]
В триггере BEFORE UPDATE, формируемом ехе для документов трансформации, переменной fc (DECLARE VARIABLE fc DINTKEY) в конце присваивается fc = NULL; (очевидно, забыли закомментировать).
Соответственно, ошибка на посте позиции.

**Comment by Polfath** [comment]
Закоментировал

**Comment by yoannawx** [comment]
проверено
