### ISSUE TITLE
Общие. Увеличить окно результата выполнения скрипта

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4387]
> _Редактор скрипт объектов → Основная функция → Скрипт → Результат выполнения скрипта._

Пожалуйста, по возможности сделайте такое окно больше:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/b19fe2dc-5110-4416-a471-c641af6d583e)

**Comment by Polfath** [comment]
Увеличил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

Андрей, пожалуйста, предусмотри по умолчанию активную первую закладку.

**Comment by Polfath** [comment]
Активной после создания формы принудительно делается последняя закладка. Эта команда прописана в коде. Видимо так нужно

**Comment by NikolayUkleyko** [comment]
Хорошо, @Polfath . 👌 
Спасибо !
