### ISSUE TITLE
Общие. Увеличить окно доступных функций

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4388]
> _Редактор скрипт объектов → Шаблон FastReport 2 → Редактор текста → Функция → Доступные функции._

Пожалуйста, по возможности сделайте такое окно больше:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/05915f88-e087-43bb-a0f9-a8c7d53ce45f)

**Comment by Polfath** [comment]
Увеличил

**Comment by NikolayUkleyko** [comment]
Проверено.
Изменений нет.

**Comment by Polfath** [comment]
Это интерфейс FastReport

**Comment by NikolayUkleyko** [comment]
Хорошо, @Polfath . 👌 
Спасибо !
