### ISSUE TITLE
Типовые документы. Складские. Наложение текста на значение параметра

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4389]
_**Типовые документы → Материальный склад → 10. Отпуск на доработку (переработку) → закладка ”Расход”.**_

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/0b2673be-25ff-40cd-9051-d6f3d4ced236)
_**Рис. 1.**_

Наложение текста на значение параметра.
Как вариант, выпадающий список перенести ниже, а строку с наименованием параметра сделать шире.

**Comment by Polfath** [comment]
Сделал перенос

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

Андрей, пожалуйста, сделай аналогичное и для закладки ”Приход”.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
