### ISSUE TITLE
Общие. Меню. В диалоговую форму документа добавить команду ”Печать”

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4390]
_**Документ → ”Меню” и/или контекстное меню.**_

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/e441c2e7-d8b6-4fb2-ab92-7cd392afbea5)
_**Рис. 1.**_

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/9ec50a0f-6331-4244-8ddd-81a7930e75f5)
_**Рис. 2.**_

Добавить команду **Печать** и возможность формирования отчетов.
Не во всех документах конструкции _**шапка-позиция**_ или _**шапка**_ в диалоговой форме на панели инструментов доступна команда **Печать**.

**Comment by NikolayUkleyko** [comment]
С @Polfath рассмотрели пример.
Небольшой функционал, но требующий немалые доработки.
Решили не реализовывать предложение.

**Comment by Polfath** [comment]
Для форм Tgdc_dlgUserSimpleDocument, Tgdc_dlgUserComplexDocument в меню добавил пункт "Печать" @NikolayUkleyko посмотри

**Comment by gsbelarus** [comment]
а почему динамически идет добавление? почему не добавить на уровне базовой формы?

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
@yoannawx, @Polfath , пожалуйста, посмотрите.

**Comment by NikolayUkleyko** [comment]
В свое время @yoannawx что-то желала реализовать.
Пока нет предложений.
Тему закрываем.
