### ISSUE TITLE
Общие. Сервис → Параметры. Предусмотреть возможность вызова из скрипта

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4391]
_**Гедымин → Сервис → Параметры.**_

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/9265056c-a841-4d49-ae20-db6be2bdcba8)
_**Рис. 1.**_

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/723dc506-c316-4492-9241-72f00a062e61)
_**Рис. 2.**_

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/1c3d3d6f-87da-41c6-9ca8-3a315a664d02)
_**Рис. 3.**_

Пожалуйста, предусмотрите возможность вызова из скрипта.

**Comment by MIchaelShoihet** [comment]
Она и сейчас есть 
Application.MainForm.GetComponent("actOptions").Execute

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@MIchaelShoihet , благодарю !
