### ISSUE TITLE
Не формируется проводка

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4392]
К документу подключена такая типовая операция операция.
![Типовая операция](https://github.com/GoldenSoftwareLtd/gedemin/assets/11484894/bfa21b38-80a4-4e7c-b060-057107e73536)
Проводка "Формирование розничной цены" по определенным позициям документа не сформировалась - она там получается нулевая.
Включаю для этой типовой проводки признак "Сохранять нулевую проводку" и для верности перезагружаю Гедымин.
Перебиваю позицию документа, по которой не сформировалась нулевая проводка (в диалоге документа перебиваю количество и перехожу на др. строку).
Проверяю ЖХО - проводка не сформировалась.
Ставлю точку остановки в конструкторе проводки на строке gdcEntry.Insert. И снова перебиваю позицию документа.
Попадаю в код, нажимаю "Выполнить" - теперь проводка формируется.

**Comment by Polfath** [comment]
@AliakseiDanilchyk проверьте, если все ОК, закройте пожалуйста
