### ISSUE TITLE
Банковская выписка

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4393]
Убрать проверку на обязательное заполнение поля в рублях, если заполнено поле в валюте. Может прийти 1 рос.копейка она 0 бел рублей...

**Comment by NikolayUkleyko** [comment]
Были такие ситуации.
Если, не вносить правки в платформу, то вариант – доработанный макрос загрузки данных из файла банковской выписки укажет сумму в бел. руб. = 0.0001.

**Comment by MIchaelShoihet** [comment]
Потом эта мелачевка может вылезти где-то боком...

**Comment by Polfath** [comment]
Убрал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, тему можете закрывать.
