### ISSUE TITLE
Мастер установок. Сохранение шаблона. Наименование формируемых файлов

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4394]
_**Мастер установок → Шаблоны → Сохранить в шаблон.**_

<ins>Пример.</ins>
Сохраняем шаблон настройки грида позиции документа ”01. Накладная на получение материалов, ОС, МБП” в файл.
Автоматически формируемое название файла следующее:
**gdc_frmInvDocument147012468_486813904 - ibgrDetail.dbg**.

@Polfath , пожалуйста, поправь автоматически формируемое название файлов на:
**01. Накладная на получение материалов, ОС, МБП.Позиция.dbg**.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
> _”Сделал”_

Проверено.
Работает корректно.
Превосходно ! 👍 
@Polfath , спасибо !

@Polfath , пожалуйста, посмотри формы карточек, при переходе на которые <ins>из документов</ins>, шаблон не сохраняется и нет ошибок:
1. _Исследователь → Материальный склад → 01. Накладная на получение материалов, ОС, МБП → Шапка → Драг.металлы по позиции → Добавляем или редактируем запись → Позиция → Сохранить шаблон._

2. _Исследователь → Материальный склад → 01. Накладная на получение материалов, ОС, МБП → Карточка по ТМЦ →  Сохранить шаблон._

При отдельном вызове таких карточек сохранение в шаблон работает корректно.

**Comment by NikolayUkleyko** [comment]
Проверено.
Не работает сохранение в шаблон файлов из форм карточек.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
При сохранении шаблона **диалоговой формы складского документа** не верно формируется название файла:
01 Накладная на получение материалов, ОС, МБП-**ibgrdTop**.dbg

Верно так:
01 Накладная на получение материалов, ОС, МБП-**ibgrDetail**.dbg

Для пользовательских документов сохранение шаблонов работает корректно.

**Comment by Polfath** [comment]
Да вроде правильно сохраняет:
01 Накладная на получение материалов, ОС, МБП-ibgrMain.dbg
01 Накладная на получение материалов, ОС, МБП-ibgrDetail.dbg
01 Накладная на получение материалов, ОС, МБП-usrg_ibgrEntry.dbg
?

**Comment by Polfath** [comment]
В диалоговой форме грид называется ibgrdTop
![Grid](https://github.com/user-attachments/assets/4b719409-f713-4eb4-9f38-3c015709fed6)
имя файла формируется как Caption диалога - имя грида.dbg

**Comment by MIchaelShoihet** [comment]
Почему не верное. Грид в диалоге так называется, поэтому так и сохраняется... Detail там вообще нет. Просто в складском документе может быть один грид и он назывется ibgrdTop и может быть два грида (Акт переработки например) то второй грид называется ibgrdBottom.

**Comment by NikolayUkleyko** [comment]
> _”Почему не верное. Грид в диалоге так называется, поэтому так и сохраняется... Detail там вообще нет. Просто в складском документе может быть один грид и он назывется ibgrdTop и может быть два грида (Акт переработки например) то второй грид называется ibgrdBottom.”_

Хорошо.
Спасибо, @MIchaelShoihet .
