### ISSUE TITLE
Мастер установок. Условия. Реквизит ”Использовать условие” при их отсутствии

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4395]
_**Мастер установок → Условия.**_

При отсутствии условий установка галки на реквизите **Использовать условие** делает неактивным кнопку **Добавить**:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/2d7162c5-b32b-4080-b641-6669a3e95913)

Переоткрытие мастера установок решает такую проблему.
@Polfath , пожалуйста, посмотри.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
