### ISSUE TITLE
Мастер установок. Условия. Реквизит ”Название” сделать обязательным и уникальным

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4396]
_**Мастер установок → Условия.**_

Пожалуйста, сделайте реквизит **Название** обязательным и уникальным:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/186280f9-16c9-4af5-8ae3-aac91f6eaf4a)

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
