### ISSUE TITLE
Общие. Инспектор объектов. Редактор строк. Правки

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4397]
_**Ctrl + Alt + E → Инспектор объектов → DataSet → SelectSQL → Редактор строк.**_

Пожалуйста:
1. Поправьте расположение кнопок на панели.
2. Сделайте немного больше исходное окно с SQL-запросом.

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/e83e3736-b476-4fd5-8645-c21e36b1961d)

**Comment by Polfath** [comment]
Поправил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
