### ISSUE TITLE
Неверная передача в AsVariant логического параметра 

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4399]
Пример. GEDEMIN:Check. Оплата заказа

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/34b2eac4-cf34-47ba-b870-e201481a33f3)
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/6e7a0392-163f-4a07-80e1-6f329fb739be)
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/d5f47df0-449f-4972-bfee-1ec230169ea8)

на старом ехе переменной ibsqlChList.ParamByName("printed").AsVariant присваивается значение 1 при isFiscal = True

**Comment by gsbelarus** [comment]
при присваивании булевского значения через AsVariant надо смотреть, если в базе это числовое поле, то использовать 0 -- false, +1 -- true.

**Comment by Polfath** [comment]
Поправил

**Comment by yoannawx** [comment]
проверено
