### ISSUE TITLE
Ломается хранилище при обновлении пи новым ехе

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4400]
Выявлено на базе Cash, пи "GS.PositiveCash.06Настройки.
1. Подключаемся новым ехе. Смотрим через сравнение пи на базе и в гите: нет различий.
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/2e4bb6d8-6005-4800-af22-b5baa326b856)
2. Загружаем пи в базу
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/64a7c62c-9039-447e-b5d1-fbfe283702f7) 
3. Опять сравниваем 
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/8865de0f-2b0c-4f8c-8030-74e9a0dcbc40)
4. если открыть эту базу старым ехе, соответственно, ошибка при открытии формы 01.Параметры. А сравнение этого пи показывает другую картинку, чем сравнение новым ехе
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/b56352f0-1f34-41c1-b5aa-afd8c2c9d068)

**Comment by Polfath** [comment]
Готово

**Comment by gsbelarus** [comment]
@yoannawx проверьте и закройте, если все ок.

**Comment by yoannawx** [comment]
п.3 не показывает различий.
п.4 - все осталось так же: старым ехе форма не открывается и сравнение показывает отличие.

**Comment by gsbelarus** [comment]
подойдите к @Polfath и покажите ему прямо сейчас

**Comment by yoannawx** [comment]
продолжение тестирования:
5. новым ехе сохраняем пи
6. подключаемся старым ехе и загружаем пи в базу
7. сравнение не показывает различий и форма открывается

**Comment by Polfath-gsbelarus** [comment]
ПИ, сформированное старым EXE и загруженное новым в старой версии уже открыться не сможет. После перехода на новый EXE нужно будет уже работать в нем. Но ПИ, сохраненный новым EXE прекрасно грузится старым.
