### ISSUE TITLE
Ошибка с обработкой значения Empty в варианте при записи в базу данных

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4401]
При расчете итогового начисления, на последнем еще delphi 7_0, на текущем exe такой ошибки нет, настройки стандартные. Если надо пример покажу-укажу.

![Screenshot 2023-06-12 111607](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/2cb426a3-0896-456e-9fb6-d5633edebbc5)

**Comment by YRozmysl** [comment]
Выяснилось, что была ошибка в коде, но которую переваривал  делфи5 и не ругался, вот тут в ф-ции передавался не null, а nul.   
![Screenshot 2023-06-27 155555_old](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/1d68715f-6a13-4a2e-ae06-47a1369dff1d)

делфи 7 на этот параметр уже ругался, поправили на null и все ок

![Screenshot 2023-06-27 155658_incorr](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/7e4e0c9a-1d9d-4b0d-aabd-a43c7fc62591)

**Comment by Polfath** [comment]
В D7 параметр nul передается как Empty, а после присвоения параметру запроса этого значения (...ParamByName('param').AsVariant = Empty) преобразовывается в 0. Отсюда ошибка о нарушении ссылочной целостности.

**Comment by gsbelarus** [comment]
> В D7 параметр nul передается как Empty, а после присвоения параметру запроса этого значения (...ParamByName('param').AsVariant = Empty) преобразовывается в 0. Отсюда ошибка о нарушении ссылочной целостности.

Надо сделать чтобы Empty трактовалось как NULL внутри IBX

**Comment by Polfath** [comment]
Как-то так

**Comment by YRozmysl** [comment]
проверено, все корректно обрабатывается

**Comment by YRozmysl** [comment]
теперь эта ошибка появилась на последнем  exe Delphy 5, на предыдущих ее не было точно. Пример и база есть

**Comment by YRozmysl** [comment]
Надо исправить эту ошибку на том exe, который компилируется автоматически, ее раньше не было.

**Comment by AndreiKireyeu** [comment]
@Polfath в каком файле вы это исправляли. я посмотрю.

**Comment by Polfath** [comment]
Gedemin/Property/obj_WrapperIBXClasses.pas

**Comment by AndreiKireyeu** [comment]
этот файл соответствует делфи5 сейчас. значит вы что-то неправильно исправили. разберитесь так чтобы работало и для делфи7 и для делфи5

**Comment by gsbelarus** [comment]
основная причина тут, что не стоит Option Explicit

если бы стоялр, то на nul выскочила бы ошибка Неопределенный идентификатор

**Comment by YRozmysl** [comment]
исправлено
