### ISSUE TITLE
Сообщение о необходимости заполнения таблицы идентификаторов

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4402]
выскочило при обновлении пи на базе позитивчека.

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/dd2f0fd2-81b8-4f54-9ea1-0caaaff10f5d)

**Comment by Polfath** [comment]
Сделал

**Comment by gsbelarus** [comment]
Эта ошибка (если это ошибка) проявляется у нас и в делфи 5. Надо поправить без условной компиляции.

**Comment by Polfath** [comment]
Убрал условную компиляцию

**Comment by gsbelarus** [comment]
```
          //{$IFNDEF DELPHI7}
          if FIDCurrent > IDGeneratorMaxThreshold then
          begin
            FIDLimit := -1;
            FIDCurrent := 0
          end;
          //{$ENDIF}
```

мне кажется проблема не в этом месте. это код извлечения ранее закешированного интервала из системного реестра. естественно, что он может быть более границы максимального ИД генератора, если на базе уже настроены интервалы и ИД берется из них.

**Comment by MIchaelShoihet** [comment]
Проблема скорее всего здесь, потому что больше просто не где. А здесь есть вероятность что из реестра идет что-то не то, мы просто скидываем значение и потом значение возьмем из генератора (или из интервалов, если они настроены) и там уже проверим.

**Comment by Polfath-gsbelarus** [comment]
Я могу сбросить алгоритм или сделать блок-схему. Мы с М.Ю. вопрос о том, откуда у проблемы ноги обсуждали.
