### ISSUE TITLE
Общие. Инспектор объектов. Увеличить размер окна с командами для контекстного меню (pmMain, pmDetail)

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4403]
_**Исследователь → Банк → Банковская выписка → Ctrl+Alt+E → ...TPopupMenu → Двойной клик мышкой.**_
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/a31b4905-ca49-467b-a43c-a9dccc5af966)
Пожалуйста, увеличьте размер окна **pmMain**, **pmDetail**.

**Comment by Polfath** [comment]
Увеличил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
