### ISSUE TITLE
Округление удержаний при расчете итогового

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4404]
При расчете итогового начисления на В_7, все удержания округляются до целого, на D_5. Покажу, расскажу на конкретных примерах. 

D_5
![Screenshot 2023-06-28 110929_D_5](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/a42c9d16-112b-4758-8926-ab1040a2e5c9)

D_7
![Screenshot 2023-06-28 110831_D_7](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/0a0e20b5-90e0-4ed7-ad56-d9ec69a8d765)

**Comment by YRozmysl** [comment]
Проблема, где-то вот тут в классе 
FSQLAddCharge.ParamByName("CREDIT").AsVariant = aCredit
В нашем случае aCredit = 36,75, а FSQLAddCharge.ParamByName("CREDIT").AsVariant = 37

**Comment by gsbelarus** [comment]
Проблему с передачей чисел через параметры надо решить системно:

https://github.com/GoldenSoftwareLtd/gedemin/issues/4405

**Comment by Polfath** [comment]
Сделал

**Comment by YRozmysl** [comment]
Проверено, работает верно.
