### ISSUE TITLE
Мастер установок. Ошибка при выделении нескольких колонок с форматированием

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4406]
_**Исследователь / Основные средства / Акт ввода в эксплуатацию / ОС. Акт ввода в эксплуатацию.**_

1. Мастер установок (F10).
2. Перетаскиваем колонку ”Остаточная стоимость” (RESTPRICE) и располагаем ее под колонкой ”Полн. сум. аморт.” (USR$FA_WEARSUMNCU).
3. Выбираем колонку ”Баланс. цена” (USR$FA_PRICENCU) и при попытке выделения нижестоящих колонок программа отображает окно с сообщением об ошибке:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/5fd3bdcb-2df6-42b9-91e4-6ead4d045d0f)

_<ins>Call Stack</ins>_
Call stack:
:0062DD49 [gedemin.exe] TdlgMaster::EditColumn (gsDBGrid_dlgMaster.pas, line 1061)
:00631BA6 [gedemin.exe] TdlgMaster::lvColumnsSelectItem (gsDBGrid_dlgMaster.pas, line 2605)
:0054186D [gedemin.exe] TCustomListView::CNNotify (ComCtrls.pas, line 13040)
:76F846F7 [user32.dll]
:76F8470F [user32.dll]
:72F36AD7 [uxtheme.dll]
:72F36AC2 [uxtheme.dll]
:76F96963 [user32.dll]
:76F965E7 [user32.dll]
:0045DFCE [gedemin.exe] TControl::WndProc (Controls.pas, line 4227)
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:72F33605 [uxtheme.dll]
:72F2B270 [uxtheme.dll]
:72F2FB31 [uxtheme.dll]
:005418D8 [gedemin.exe] TCustomListView::CNNotify (ComCtrls.pas, line 13047)
:72F2F7A8 [uxtheme.dll]
:76F96507 [user32.dll]
:76F96522 [user32.dll]
:76F964C9 [user32.dll]
:752370D3 [comctl32.dll]
:00541D1A [gedemin.exe] TCustomListView::WndProc (ComCtrls.pas, line 13163)
:0045DD51 [gedemin.exe] TControl::Perform (Controls.pas, line 4152)
:00458919 [gedemin.exe] FindControl (Controls.pas, line 1615)
:00461829 [gedemin.exe] DoControlMsg (Controls.pas, line 5774)
:00462038 [gedemin.exe] TWinControl::WMNotify (Controls.pas, line 5955)
:0045DFCE [gedemin.exe] TControl::WndProc (Controls.pas, line 4227)
Recursive call (2 times):
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:778EC81C [ntdll.dll]
:778E5E4E [ntdll.dll]
:76FA137B [user32.dll]
:76F9834A [user32.dll]
:76F9858F [user32.dll]
:76F9838C [user32.dll]
:73AB2368 [CoreMessaging.dll]
:00541D1A [gedemin.exe] TCustomListView::WndProc (ComCtrls.pas, line 13163)
:0045DD51 [gedemin.exe] TControl::Perform (Controls.pas, line 4152)
:0041ABEB [gedemin.exe] TThreadList::UnlockList (Classes.pas, line 2125)
:00430829 [gedemin.exe] FreeMemoryContexts (Graphics.pas, line 4566)
:004611C7 [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5612)
:00449526 [gedemin.exe] StdWndProc (Forms.pas, line 1459)
:76FA137B [user32.dll]
:76F9834A [user32.dll]
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:73A7B19E [CoreMessaging.dll]
:77912C16 [ntdll.dll]
:77548513 [KERNELBASE.dll]
:76F9815E [user32.dll]
:100043A5 [AnvirHook8.dll]
:76F97F4A [user32.dll]
:76FF1B58 [user32.dll]
:76F9BB0F [user32.dll]
:76F9838C [user32.dll]
:77914F6D [ntdll.dll]
:7660107C [win32u.dll]
:76F978AB [user32.dll]
:76F9C577 [user32.dll]
:76F95D6F [user32.dll]
:7521F091 [comctl32.dll]
:76F9BB0F [user32.dll]
:77912ABC [ntdll.dll]
:76F9BB27 [user32.dll]
:752348AD [comctl32.dll]
:7523C95A [comctl32.dll]
:7523CF77 [comctl32.dll]
:75239A77 [comctl32.dll]
:7523E475 [comctl32.dll]
:75239DD5 [comctl32.dll]
:7523750B [comctl32.dll]
:76F844DB [user32.dll]
:004617AD [gedemin.exe] TWinControl::DefaultHandler (Controls.pas, line 5755)
:0045DFCE [gedemin.exe] TControl::WndProc (Controls.pas, line 4227)
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:76FF482D [user32.dll]
:76F9BB0F [user32.dll]
:77912ABC [ntdll.dll]
:76F9BB27 [user32.dll]
:77914F6D [ntdll.dll]
:100042FE [AnvirHook8.dll]
:7660107C [win32u.dll]
:76F9787A [user32.dll]
:004512D8 [gedemin.exe] DispatchShortCut (Forms.pas, line 4867)
:778EDD34 [ntdll.dll]
:76FA137B [user32.dll]
:76F9834A [user32.dll]
:0046401F [gedemin.exe] TWinControl::CNKeyDown (Controls.pas, line 6892)
:76F9815E [user32.dll]
:76F97A27 [user32.dll]
:76F844DB [user32.dll]
:004617AD [gedemin.exe] TWinControl::DefaultHandler (Controls.pas, line 5755)
:00463006 [gedemin.exe] TWinControl::WMKeyDown (Controls.pas, line 6406)
:0045DFCE [gedemin.exe] TControl::WndProc (Controls.pas, line 4227)
:0046167F [gedemin.exe] TWinControl::WndProc (Controls.pas, line 5731)
:0041ABEB [gedemin.exe] TThreadList::UnlockList (Classes.pas, line 2125)
:00430829 [gedemin.exe] FreeMemoryContexts (Graphics.pas, line 4566)
:004611C7 [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5612)
:004611DE [gedemin.exe] TWinControl::MainWndProc (Controls.pas, line 5615)
:778EC81C [ntdll.dll]
:00449526 [gedemin.exe] StdWndProc (Forms.pas, line 1459)
:76FA137B [user32.dll]
:76F9834A [user32.dll]

Modules:
$00400000 (00400000,00001000,00DC4600) C:\Golden Software\Gedemin\gedemin.exe
$76F60000 (76F60000,00001000,000A4000) C:\WINDOWS\System32\user32.dll
$72F00000 (72F00000,00001000,00065600) C:\WINDOWS\system32\uxtheme.dll
$778A0000 (778A0000,00001000,00120000) C:\WINDOWS\SYSTEM32\ntdll.dll
$73A60000 (73A60000,00001000,00064800) C:\WINDOWS\SYSTEM32\CoreMessaging.dll
$77410000 (77410000,00001000,001FA600) C:\WINDOWS\System32\KERNELBASE.dll
$10000000 (10000000,00001000,0000BE00) C:\Program Files (x86)\AnVir Task Manager\AnvirHook8.dll
$76600000 (76600000,00001000,00005400) C:\WINDOWS\System32\win32u.dll
$75200000 (75200000,00001000,00071E00) C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_c0da534e38c01f4d\comctl32.dll
$72A70000 (72A70000,00001000,0016C000) C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
$72380000 (72380000,00001000,0000E400) C:\Program Files (x86)\Yandex\Punto Switcher\pshook.dll
$77100000 (77100000,00001000,000B0600) C:\WINDOWS\System32\msvcrt.dll

_<ins>Registers</ins>_
Main Thread ID = 00008D00, Current Thread ID = 00008D00
Registers:
EAX = 00000000  CS = 0023  EIP = 0062DD49  Flags = 00010246
EBX = 0B5312D0  SS = 002B  ESP = 0019EB68    EBP = 0019EBB8
ECX = 0EE0C760  DS = 002B  ESI = 000E0A7A    FS  = 0053
EDX = 00562008  ES = 002B  EDI = 0000004E    GS  = 002B
Code at CS:EIP
8A 40 34 88 45 DF EB 39 8B 45 FC 8B 80 18 04 00 
Stack:
0019EB74 00403EA8 0019EBB8 0019EBE0 00403EA8 
00000000 00000000 76F9834A 00000005 0EC7CE80 
00403A0B 0F0535D8 0040360B 00000000 0EBAEBC0 
76F9834A FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF 

-----

Проверено на других документах.
**Ошибка появляется, при перемещение в Мастере установок любой из колонок, а затем выделение нескольких колонок, для которых указано форматирование.**

**Comment by NikolayUkleyko** [comment]
Это одна из старых ошибок типа **_EAccess Violation_**, которые не удавалось смоделировать.

**Comment by Polfath** [comment]
Починил

**Comment by Polfath** [comment]
@NikolayUkleyko Коля, проверь, плиз

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
