### ISSUE TITLE
Не поддерживается тип из ФБ3

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4407]
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/5175764/dc04a9cd-1d78-41e7-9add-9de1f9c0640b)

**Comment by Polfath** [comment]
Хорошо бы локализовать этот баг. Строка 402 в модуле IB только инициализирует сообщение об ошибке.

**Comment by gsbelarus** [comment]
ищите где разбирается массив типов полей и создаются объекты для полей типа
tibintegerfield, tibstringfield и тп



пт, 15 вер 2023, 08:42 карыстальнік Polfath ***@***.***>
напісаў:

**Comment by gsbelarus** [comment]
посмотрите что это за поле, какой у него тип и подумаем что делать. скорее всего преобразовывать в один из существующих.

**Comment by MIchaelShoihet** [comment]
Это из FB3 или FB5?

**Comment by gsbelarus** [comment]
В любом случае надо сделать поддержку. Получается повторить?

**Comment by Polfath-gsbelarus** [comment]
Повторить не удалось

**Comment by gsbelarus** [comment]
а вы к базе на пятом фб подключаетесь?

**Comment by Polfath-gsbelarus** [comment]
ФБ3. Так было написано в теме

**Comment by Polfath** [comment]
Если речь про ФБ5, кажется как-то давновато столкнулся с тем, что возникает ошибка с тем, что появился тип BOOLEAN. Нужно попробовать воспроизвести тот баг и обработать его.

**Comment by gsbelarus** [comment]
пока закроем. столкнемся еще раз -- будем думать.
