### ISSUE TITLE
Конструктор типовой операции для типового документа

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4409]
В скрипте инициализации присутствует код 
if not gdcDocument.FieldByName("transactionkey").IsNull then _
  gdcDocument.FieldByName("transactionkey").Clear
Однако в саму функцию он не подставляется. Причем это начало происходить до 7 делфи, но именно с измененным exe

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/52f3154e-2416-4eb7-b601-0f67e75bccd7)

**Comment by Polfath** [comment]
Поправил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
Если, нет вопросов, то данную тему можно закрывать.
