### ISSUE TITLE
Бухгалтерия. Конструктор функций. Добавить переменную ”Сальдо (SDK)”

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4410]
_**Исследователь → Бухгалтерия → Автоматические хоз. операции.**_

Пожалуйста, добавьте переменную ”Сальдо (SDK)”, как разница между сальдо по дебету (SD) и сальдо по кредиту (SK).

**Comment by Polfath** [comment]
Добавил ф-ции:
SDK - рублевые
V_SDK - валютные
K_SDK - количественные
E_SDK - эквивалент

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
