### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Ошибка при формировании с указанным уровнем аналитики

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4411]
_**Исследователь → Бухгалтерия → Журнал-ордер.**_

В параметрах указали:
• счет ”42.01”;
• аналитика ”Подразделение”;
• указали уровень аналитики.

Следующая ошибка моделируется не на каждой БД:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/a44136da-2c65-4e90-ac4a-87a3c598c0f3)

**Comment by Polfath** [comment]
На базе с ошибкой процедура AC_LEDGER_GD_CONTACT была отличная от эталона

create or alter procedure AC_LEDGER_GD_CONTACT (
    **L  DINTKEY,
    NODEKEY DINTKEY**)

правильно же

create or alter procedure AC_LEDGER_GD_CONTACT (
    **L integer,
    NODEKEY integer**)

**Comment by Polfath** [comment]
Поправил

**Comment by gsbelarus** [comment]
тут по хорошему надо модифай делать чтобы такие процедуры привести в соответствие к эталону на всех бд

**Comment by YRozmysl** [comment]
У меня на какой-то базе тоже была такая ошибка с уровнями аналитик по статье затрат при построении ЖО  и ошибка была в процедуре AC_LEDGER_USR$ACC_EXPENSES. Такого рода процедуры с префиксом AC_LEDGER_ входят разве в какие-то ПИ?

**Comment by YRozmysl** [comment]
Как они вообще на базах появляются? Макрос какой-то создает, exe?

**Comment by Polfath** [comment]
Сделал Modify

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
