### ISSUE TITLE
gdcBaseManager.ExecSingleQuery

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4413]
Функция gdcBaseManager типа ExecSingleQuery, ExecSingleQueryParam и т.д. обрабатывают ошибки FB внутри и выдают MessageBox,,, Получается их нельзя использовать в авто задачах, возникает окно и автозадача зависает. Может добавить свойство Silent в gdcBaseManager, по умолчанию False, и все работает как сейчас, Но если его установить в True то MessageBox не выводить, ошибку не обрабатывать, тогда ее можно будет обработать в скрипте...

**Comment by gsbelarus** [comment]
а где вообще может понадобиться, чтобы функция кинула не исключение, а именно MessageBox на экран? я не могу представить такой ситуации. может забыл уже...

можно сейчас попробовать убрать подавление исключения ФБ внутри этих функций. пусть идет наружу.

**Comment by gsbelarus** [comment]
@Polfath если будете исправлять, то исправляйте в ветке Delphi7.

**Comment by Polfath** [comment]
Сделал

**Comment by gsbelarus** [comment]
Нет. Так нельзя делать. Никаких новых свойств в бизнес-класс сейчас мы не добавляем. Уберите и давайте обсудим другие возможные решения. Распишите их тут.

**Comment by Polfath** [comment]
Убрал Silent и закомментировал сообщение.@MIchaelShoihet считает, что оно лишнее

**Comment by gsbelarus** [comment]
я вижу что свойство silent осталось

**Comment by Polfath** [comment]
Уже убрал. Просто сначала убрал не везде и поторопился закомитить. Потом сразу убрал везде. Будет в комите.
