### ISSUE TITLE
Ошибка при открытии формы.

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4417]
К чистому эталону, сформированному под exe_5 из текущих настроек из репозитория, подключаюсь exe_7, запрашивается модифай, он проходит. НО, возникает ошибка при открытии формы. 
![Screenshot 2023-09-19 121021](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/1e7e5c45-dba6-4789-bbf1-5cefb3a8434c)

**Comment by YRozmysl** [comment]
При подключении exe_5 после модифая, все ок

**Comment by Polfath** [comment]
Исправил

**Comment by YRozmysl** [comment]
Ошибки нет, все хорошо.
