### ISSUE TITLE
Бухгалтерия.Журнал хоз.операций.

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4420]
Надо отображать записи в ЖХО только по указанной операции. ЖХО служит для точечного решения проблемы, просмотр всех проводок с учетом вложенных в нем не требуется.

**Comment by MIchaelShoihet** [comment]
Возможно главную таблицу в нем сделать ac_entry у нее есть индекс по дате и есть transactionkey, получаться наиболее оптимальные фильтры.

**Comment by NikolayUkleyko** [comment]
Получается, что параметр ”Связь по LB и RB...” для Журнала хоз. операций уже не актуален.
Верно, @MIchaelShoihet ?

**Comment by MIchaelShoihet** [comment]
Не имеет смысла, и скорость замедляет в разы

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , если, нет вопросов, пожалуйста, тему можно закрыть.
