### ISSUE TITLE
Общие. Функции ”acc_GetCurrRate”, ”GetCurrRate”, ”gs_GetCurrRate” не возвращают курс валюты

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4421]
Функция **acc_GetCurrRate** не возвращает курс валюты.
Подобно было _https://github.com/GoldenSoftwareLtd/gedemin/issues/4338_.
Пожалуйста, поправьте.

-----
_https://gsbelarus.com/gs/wiki/index.php/Gedemin_TLB.IGedemin.GetCurrRate_

**Comment by Polfath** [comment]
В крайней версии гедемина этот баг не воспроизвоидтс. Я в модуле, в котором возникал он уже кое-что правил по какой-то другой причине. Возможно это лекарство подействовало и на него. Нужно перепроверить.

**Comment by NikolayUkleyko** [comment]
Проверил.
Функции **acc_GetCurrRate**, **GetCurrRate**, **gs_GetCurrRate** не возвращают курс валюты.
На примере покажу.

При подключении к БД под gedemin.exe Delphi 5 такие функции работают корректно.

**Comment by Polfath** [comment]
Сделал @NikolayUkleyko Проверь

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
