### ISSUE TITLE
Мастер установок. После выбора нескольких колонок очищается форматирование

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4425]
После выбора нескольких колонок очищается форматирование.
Актуально для числовых полей и полей с датой.

**Comment by Polfath** [comment]
Проблема возникала, если среди выбранных колонок были с форматом и без. Поправил.

**Comment by NikolayUkleyko** [comment]
> _”…если среди выбранных колонок были с форматом и без…”_

Да, наличие колонок с форматом и без является ключевым.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
