### ISSUE TITLE
Материальный склад. Цены округляются до целого

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4428]
_https://discord.com/channels/1104433152576991282/1105765965398024204/1159746207032287302_

Цены округляются до целого.
Это неверно.
Пожалуйста, поправьте.

**Comment by Polfath** [comment]
Поправил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
