### ISSUE TITLE
Материальный склад. Округляется до целого значение ставки НДС

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4431]
_**Исследователь → Материальный склад → 01. Накладная на получение материалов, ОС, МБП.**_

При вводе ставки НДС со знаками после запятой программа автоматически округляет до целого.
Это неверно.

@Polfath , пожалуйста, поправь.

**Comment by Polfath** [comment]
Поправил @NikolayUkleyko проверяй

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
