### ISSUE TITLE
Бухгалтерия. Анализ счета. Убрать ограничение для счета 00

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4432]
_**Исследователь → Бухгалтерия → Анализ счета.**_

Пожалуйста, уберите из запроса формирования данных ограничение для счета 00:

```ruby
AND e.accountkey <> 300003
```

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
