### ISSUE TITLE
DCU7, BPL7...

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4434]
Порядок разворачивания исходников для компиляции такой:

1. Взять исходники.
2. Запустить файлы `prepare_sources.bat` в папках `Comp5` and `Gedemin`.
3. Открыть группу проектов `gedemin.bpg` и поочередно перекомпилировать и инсталлировать проекты и библиотеки.

Файл  `prepare_sources.bat` делает следующее:

1. Создает папки DCU, BPL.
2. Делает копии из файлов с расширением `.sample`. Эти копии нужны нам чтобы разработчик мог менять проекты у себя на компьютере и они не попадали в общий гит.

Необходимо в ветке `Delphi7` отказаться от использования папок DCU7, BPL7 и восстановить вышеописанную процедуру разворачивания исходников и компиляции проекта.

**Comment by Polfath** [comment]
Сделал
