### ISSUE TITLE
Общие. Задержка при вызове документов из Исследователя, произвольное переключение форм и т.д.

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4435]
При работе с некоторыми БД замечена задержка при вызове документов из Исследователя, кратковременное подвисание программы (Не отвечает), произвольное переключение форм и т. д.

@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Произвольное переключение между формами бывает в формах с длительным выполнением, обработкой данных.
Например, документ начисления амортизации.
Странно, формы же модальные.

Подобное иногда встречается при выполнении коммита в редакторе скрипт-объектов.

**Comment by NikolayUkleyko** [comment]
Пользователи запускают на формирование отчет и получают корректные данные.
Время формирования отчета 3-5 секунд.
При этом в стандартном окне формирования (построения) отчета указано ”Не отвечает”.

**Comment by gsbelarus** [comment]
так и будет работать. идет ожидание ответа от сервера базы данных. оно идет в основной нити программы. так сделано и поменять это приблизительно год работы.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, уточните – вышеприведенное связано с переходом **gedemin.exe** Delphi 5 » Delphi 7 ?

**Comment by NikolayUkleyko** [comment]
По заголовку окон это пустяк.

Произвольное переключение форм, окон и т.д. интереснее.
Пользователь выполняет расчет в одной форме и при этом произвольно выполняется переключение на другие уже открытые формы.

На Витебск ВБПФ и других МК интересно посмотреть.

@yoannawx в курсе такой темы.

**Comment by gsbelarus** [comment]
нужен конкретный повторяемый пример без этого ничего исправить невозможно. что такое произвольное переключение непонятно. 

нажмите Alt-Win-G и запишите видео с экрана когда такое происходит.
