### ISSUE TITLE
Общие. Поправить текст сообщения при поиске формы

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4436]
@Polfath , пожалуйста, поправь сообщение в следующей форме:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/50c4456f-5e1a-44f1-aee5-0b0f09d06cdb)

_...Пожалуйста, откройте форму и повторите свои действия..._

**Comment by Polfath** [comment]
Поправил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
