### ISSUE TITLE
Отчеты. При вставке отчета не сохраняется уникальное наименование

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4437]
1. Скопировали отчет с наименование функции _rp_InvOpis_OS_2008149361720_123456789_.
2. Вставили отчет из буфера.
3. Скорректировали имена скрипт-функций.
4. Выбрали закладку **_Основная функция → Скрипт_** и указали курсор в текст запроса.
5. Пробуем закоммитить отчет.

В результате программа отображает сообщение об ошибке:
![image](https://github.com/GoldenSoftwareLtd/gedemin-apps/assets/11497453/d81af71b-d672-4f53-b1a4-302b42b6ad0e)

Исправить функцию на закладке **_Основная функция → Скрипт_** программа не позволяет.

-----

Такая проблема возникает на **gedemin.exe Delphi 7**.

После вставки отчета с наименованием функции более **55 символов** программа автоматически сокращает наименование отчета до исходного наименования скопированного отчета.

Если, после вставки отчета перейти на закладку **_Основная функция → Скрипт_** и выполнить коммит, то сохранение выполняется корректно.

**Comment by Polfath** [comment]
Сделал. @NikolayUkleyko Проверь пожалуйста

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
@yoannawx, @Polfath , пожалуйста, посмотрите.

**Comment by Polfath** [comment]
Да вроде как исправлял. У меня не воспроизводится. @yoannawx посмотри то, что у меня
