### ISSUE TITLE
Для cesValueList не сохраняются значения 

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4438]
Если мы заходим в редактирование формы в ColumnEditors выбираем поле для которого используется cesValueList, редактируем, нажимаем ок.  Как показано на картинке.

![1_грид](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/0eb7fbd4-d1ac-4058-bc6e-f83bf39e599e)

 После чего переоткрываем документ, то видим, что значения не сохранились. 

![2_грид](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/4e597015-ba96-45c9-82b6-c684682eb817)

**Comment by MIchaelShoihet** [comment]
Судя по эксперименту, который мы провели, новый exe почему-то не записывает в DFM эти значения. Потому что когда старым exe добавили и сохранили, новый нормально все считал.

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста, при возможности посмотри.

**Comment by NikolayUkleyko** [comment]
Если, под Delphi 7 корректно сохраняется в ПИ и устанавливается на БД, возможно доработок и не потребуется.

@MIchaelShoihet , пожалуйста, добавьте комментарии.

**Comment by Polfath** [comment]
Сделал

**Comment by YRozmysl** [comment]
проверено, все ок
