### ISSUE TITLE
ПИ. Настройки удаления объектов при установке

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4439]
При установке ПИ возможны следующие настройки:
1. В окне настройки устанавливаемых ПИ в базу данных есть опция **Не удалять объекты, отсутствующие в загружаемом файле**
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/1f5ab07f-036d-4d3e-9856-a76f6c810504)

2. Окно выбора объектов для удаления
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/57ab501c-d95e-4ff5-bd71-d95dcaf23a92)

@gsbelarus , пожалуйста, подскажите, такие параметры являются взаимосвязанными ?
Если, не указали галку по параметру из пункта 1, то программа может отобразить окно из пункта 2.
Если, указали галку по параметру из пункта 1, то программа не отобразит окно из пункта 2.
Верно ли ?

-----

При установке ПИ удаление объектов из ПИ не должно касаться непосредственно метаданных.
Не первый раз встречается ситуация, при которой выполняется удаление объектов с данными, например, таблиц, полей.

Данную интересную тему могут дополнить @MIchaelShoihet и @yoannawx.

**Comment by Polfath** [comment]
Сделал в https://github.com/GoldenSoftwareLtd/gedemin/issues/4445
