### ISSUE TITLE
Зачем дублировать код?

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4441]
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/5175764/180f9251-9ade-4b08-a48e-f17454a8d3b8)

в TIBDatabase уже есть метод, который возвращает версиб сервера.
надо использовать его.

только в него я бы добавил кэширование, чтобы не дергать сервер постоянно.

**Comment by gsbelarus** [comment]
я убрал и заодно убрал вывод версии фб в главной форме. он там неправильно сделан. если хотите правильно сделать, то найдите, где в NotifierThread возвращается путь к БД и там прибавляйте номер версии ФБ.

**Comment by Polfath** [comment]
Переделал
