### ISSUE TITLE
Не активируются настройки формата gsf под delphi_7

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4443]
Не активируются настройки gsf, "зависает" окно активации. Причем не имеет значения каким exe создавалась gsf настройка. 
 
![Screenshot 2023-12-04 113504](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/06aebc37-ddd4-41a1-ade9-547ae9132b60)

**Comment by Polfath** [comment]
Сделал

**Comment by YRozmysl** [comment]
проверено, все  ок

**Comment by gsbelarus** [comment]
У нас есть TgdAutoTaskThread которая отвечает за запуск автозадач. Она создается в процессе логина к базе данных. В процессе загрузки настроек несколько раз происходит релогин к базе данных и каждый раз будет создаваться нить автозадач. Это неправильно. Надо сделать так:

1. До загрузки настроек останавливаем и удаляем эту нить.
2. Загружаем настройки. При релогинах к базе данных в процессе загрузки настроек не создаем нить авто задач.
3. По завершении загрузки настроек делаем финальный релогин с загрузкой нити автозадач.

**Comment by Polfath** [comment]
Сделано

**Comment by YRozmysl** [comment]
исправлено
