### ISSUE TITLE
Лишний код

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4444]
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/5175764/cd5d46b2-e190-41da-b7c1-d0174aab17c3)

у нас есть окно со списком пользователей и в нем есть специальная функция, которая позволяет проверить, есть текущие подключения к бд или нет. именно это окно и надо вызывать, а не дублироват код в окне опций.

**Comment by Polfath** [comment]
Поправил (см. #4442)
