### ISSUE TITLE
ПИ. В форму удаления объектов добавить группировку записей по типам

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4445]
При установке ПИ может появится окна удаления объектов:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/6bf1dbeb-d9ff-426a-85e0-b9ef53ff9e32)
**_Рис. 1. Окно удаления объектов._**

Пожалуйста, сгруппируйте записи по типам.
Подобное реализовано в окне добавления записей в ПИ:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/c4f7d95b-92e1-469b-b9c4-9028654771b1)
**_Рис. 2. Окно добавления записей в ПИ. Типы записей._**

**Comment by NikolayUkleyko** [comment]
Такой функционал удобен тем, что наглядно видно, какие объекты могут быть удалены – метаданные, функции и т.д.
Взаимосвязанная тема рассматривается здесь https://github.com/GoldenSoftwareLtd/gedemin/issues/4439.

**Comment by Polfath** [comment]
Добавил. @NikolayUkleyko Посмотри плз, Так нормально?

**Comment by NikolayUkleyko** [comment]
@Polfath , спасибо за доработку.
Проверено.
Пожалуйста, предложения:

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/174b03a8-b824-4bc6-8378-882d42d92c13)
_**Рис. 1.**_

1. Локализовать наименования закладок.
2. Предусмотреть кнопки для выбора/снятия галок по записям текущей вкладки.

**Comment by Polfath** [comment]
Добавил кнопки

**Comment by NikolayUkleyko** [comment]
Доработки по данной теме не вошли в **gedemin.exe Delphi 7**.
@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
При этом названия закладок не локализованные:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/e57ceb90-58d5-4bcb-9a4a-d9c81fa5359c)
**_Рис. 1._**

@Polfath , спасибо !
