### ISSUE TITLE
Добавление ссылки на новостную ленту в меню Справка

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4446]
Есть предложение в меню "Справка" после "О системе..." добавить пункт типа "Дайджест новостей" со ссылкой на новостную ленту на нашем сайте, чтобы пользователи их просматривали и определяли, актуальны ли доработки для них, и обращались к нам за обновлениями.

**Comment by Polfath** [comment]
Добавил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/5a502151-87ac-4dd8-a3d9-e02669389edc)
_**Рис. 1.**_

_https://gsbelarus.com/pw/articles/news/_
