### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Добавить ограничение на перетаскивание проводок, созданных по документу

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4447]
_**Исследователь → Бухгалтерия → Журнал хоз. операций.**_

Пожалуйста, предусмотрите <ins>ограничение</ins> на перетаскивание проводок, созданных по документу.
Проводки, созданные через автоматические хозяйственные операции, отчеты бухгалтерии, ручные проводки и т.д. <ins>не ограничивать</ins> при перетаскивании.

1. Выполнили перетаскивании проводок, созданных по документу.
2. Открыли и/или перепровели проводки по такому документу.
3. В результате проводок нет.

@MIchaelShoihet , пожалуйста, посмотрите.

**Comment by NikolayUkleyko** [comment]
Добавлю.
В программе предусмотрено ограничение на удаление проводок из Журнала хоз. операций, созданных по документу.
Работает верно.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.

Если, среди перетаскиваемых проводок, созданных по документу, есть еще и ручные проводки, то программа позволяет выполнить перетаскивание всех проводок, как созданных по документу, так и ручных.

**Comment by Polfath** [comment]
Сделал так, что если среди перетаскиваемых есть ходя бы одна, созданная по документу, их перетащить нельзя.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
