### ISSUE TITLE
ID  в справочнике LBRBTree

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4448]
В таких типах справочников отсутствует триггер  на создание ID. Выяснилось. когда выполнялся  запрос на INSERT

**Comment by Polfath** [comment]
Можно какой-нибудь конкретный справочник?

**Comment by YRozmysl** [comment]
USR$WG_FEETYPE

**Comment by Polfath** [comment]
Баг не воспроизводится. При инсерте ID создается в стандартном методе TgdcBase.GetNextID. Он общий для всех объектов.

**Comment by MIchaelShoihet** [comment]
Иногда в таблицы идет добавление командами SQL и во всех таблицах поэтому есть триггер на создание ID и никто ручками его не создает (если не надо дальше использовать). Вопрос был в том, что при создании новой таблицы типа Интервальное дерево такой триггер не создается.

**Comment by Polfath** [comment]
Добавил добавление триггера на присвоение ID

**Comment by YRozmysl** [comment]
Проверено, триггер добавляется.
