### ISSUE TITLE
Лишние переоткрытия датасета

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4449]
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/5175764/ec9c436c-be6a-4c38-b386-1038dd766f83)

при каждом изменении размера будет переоткрываться датасет. зачем?

сначала посмотрите какой новый размер и какой вам нужен сабсет.
потом сравните с текущим сабсетом.
и только если будет различаться, то начинайте переоткрывать.

**Comment by Polfath** [comment]
Поправил
