### ISSUE TITLE
недостаточно проверок

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4450]
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/5175764/33cd4e6d-fde2-41a6-93d3-a4a2a3e2beaf)

пусть мы теперь пропускаем и параметры типа вариант, но что будет если придет строка в варианте? тут нужна дополнительная проверка, что именно содержит этот вариант.

**Comment by Polfath** [comment]
Добавил проверку
