### ISSUE TITLE
Исследователь уходит за пределы видимой области экрана

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4451]
Периодически возникает такая проблема. Возможно, при работе на мониторах с разным разрешением.

**Comment by NikolayUkleyko** [comment]
_> ”Периодически возникает такая проблема. Возможно, при работе на мониторах с разным разрешением.”_

Также, при работе на нескольких мониторах.

**Comment by Polfath** [comment]
Добавил контроль расположения формы на экране при ее перемещении и при изменении размеров
