### ISSUE TITLE
Зависание ЖХО

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4453]
некорректно подставляется sybset Из-за чего  ЖХО долго открывапется
Сейчас вот так. Неправильно
![неверно](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/09c5fd9f-adf4-4c78-9678-1bde650cb847)

А надо вот так. 
![правильно](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/60097fc3-1071-4688-86ab-e209f898a190)

**Comment by YRozmysl** [comment]
Это все имеет место быть в exe под delphi5 под delphi5  все сделано, и работает корректно

**Comment by Polfath** [comment]
Под 7 все вроде нормально.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
