### ISSUE TITLE
Ошибка создания счета и субсчета под пользователем

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4455]
На чистой базе создал пользователя , включил его в группу Администраторы и пытаюсь создать счет, субсчет. Вылезает ошибка. Это все на последнем exe D_5
![Screenshot 2024-01-24 125006](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/78cbdb6b-02d1-484a-8068-449fb8b0206c)

Под администратором все работает.

**Comment by AliakseiDanilchyk** [comment]
На старом exe тоже самое. Пробовал exe за июль 2022 года.
База отсюда https://gsbelarus.com/pw/downloads/gedemin-platform/etalon/

**Comment by YRozmysl** [comment]
https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/2346

**Comment by Polfath** [comment]
По какой-о причине при создании эталонной базы не попала команда на создание гранта для таблицы AC_ACCANALYTICSEXT. Я добавил ее в скрипт на создание таблицы и сделал модифай на его добавление, если база уже используется. Но это только после перехода на версию из D7. Пока, ка временный вариант, при выползании этой ошибки в SQL редакторе выполнить
grant all on AC_ACCANALYTICSEXT to ADMINISTRATOR
и будет все норм

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
