### ISSUE TITLE
Ошибка с обработкой значения Empty в варианте при записи в базу данных на DELPHY_5

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4456]
точно такая же ошибка, которую исправили успешно на  DELPHI_7, 

[https://github.com/GoldenSoftwareLtd/gedemin/issues/4401](url)

Но, она появилась на DELPHI_5, пример есть

**Comment by Polfath** [comment]
В версии для Delphi 5 я уже ничего не исправлю. Нужно ждать, когда выйдет из-под Delphi 7.
