### ISSUE TITLE
Бухгалтерия. Журнал-ордер. Формировании с указанным уровнем аналитики. Статьи затрат. Delphi 7

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4457]
В параметрах указали:
• счет ”26”;
• аналитика ”Статья затрат”;
• указали уровень аналитики.

Если  в  справочнике аналитика самого верхнего уровня без вложенности ( PARENT  пустой) , то при формировании ЖО вид вот такой, по-идее их тоже надо заполнять. Вся проблема вот в этой процедуре, наверное, AC_LEDGER_USR$ACC_EXPENSES     

![Screenshot 2024-02-06 153033_1](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/dd5dcde8-585b-4e1a-8066-867ea42a1ae4)

Справочник имеет такой вот вид.
![Screenshot 2024-02-06 153131_2](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/73b1abe6-a4cc-42af-ac10-b3a7fbc3ad5f)

**Comment by MIchaelShoihet** [comment]
Цифра 2 означает, что будет выведен 2-й уровень из дерева аналитик для данных записей 2-го уровня нет, они находятся на 1-м уровне и у них нет вложенности, поэтому ничего там и не выводится
