### ISSUE TITLE
UserStorage.BuildComponentPath дает разный результат в разных методах формы

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin#4458]
Форма создается:
Creator.GetObject(nil, "usrf_FA_dlgReappReport", "dlgReappReport")

В OnSaveSetting делаем UserStorage.BuildComponentPath( Sender, "")

Получаем
"dlgReappReport (TgdcCreateableForm)"

А когда в OnLoadSettingsAfterCreate это же делаем, получаем 
"usrf_FA_dlgReappReport (TgdcCreateableForm)"

Хотелось бы, чтоб везде было одинаково.

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста, посмотри.

**Comment by Polfath** [comment]
Здесь ситуация такая. На создании формы (Create) ей присваивается имя usrf_FA_dlgReappReport, поэтому на событии OnLoadSettingsAfterCreate оно такое. При отрисовке формы идет переприсвоение имени на dlgReappReport, поэтому при закрытии на событии OnSaveSetting оно уже другое. Если смущает, что они разные, поменяйте в скрипте команду на Creator.GetObject(nil, "usrf_FA_dlgReappReport", "usrf_FA_dlgReappReport") 
или
 Creator.GetObject(nil, "usrf_FA_dlgReappReport", "")

**Comment by alexandra-gsoftware** [comment]
Я могу вообще не использовать getcomponentpath. Проблема в том, что он в разных методах формы дает разный результат. Это неправильно.

**Comment by MIchaelShoihet** [comment]
Конечно не правильно. Попытаемся разобраться. Причина в том, что почему-то в LoadSettingAfterCreate имя формы еще не поменялось, на то, что указано при создании, оно осталось еще оригинальным....

**Comment by Polfath** [comment]
Исправил. Будет в версии из-под Delphi 7.
