### ISSUE TITLE
Обрезаются экранные формы при изменении масштаба в параметрах экрана

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4460]
Например, окно входа и главное окно
![login](https://github.com/GoldenSoftwareLtd/gedemin/assets/11484894/2d1164cd-a9ce-4816-a223-f48c963d076c)
![главное окно](https://github.com/GoldenSoftwareLtd/gedemin/assets/11484894/ca523060-5d32-4139-8eb4-aee83c3c3453)

**Comment by NikolayUkleyko** [comment]
Это имеет силу и для диалоговых форм любых документов, справочников и т.д.

**Comment by NikolayUkleyko** [comment]
_https://discord.com/channels/1104433152576991282/1104433152576991285/1205448487026827284_
_https://discord.com/channels/1104433152576991282/1104433152576991285/1205449010039496725_

**Comment by AliakseiDanilchyk** [comment]
> Это имеет силу и для диалоговых форм любых документов, справочников и т.д.

Нет, не для любых. Я сейчас у себя изменил масштаб и пооткрывал с десяток разных форм. Пока заметил баг только в двух

**Comment by AliakseiDanilchyk** [comment]
Из Гедымина видно, что для главного окна Constraints формы MaxHeight прописан 85

**Comment by Polfath** [comment]
Сделал

**Comment by AliakseiDanilchyk** [comment]
Проверил. Формы не обрезаются
