### ISSUE TITLE
Общие. Добавить команду ”Переоткрыть форму”

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4461]
Пожалуйста, предусмотрите команду **Переоткрыть форму** для выполнения закрытия, затем, открытия выбранной формы.
Предусмотрите горячие клавиши **Ctrl + F5**.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
Пример:
_**Исследователь → Материальный склад → Отчеты по складу →  Остатки по материалам и МБП.**_

При попытке выполнения переоткрытия формы (при помощи соответствующей команды или горячих клавиш ”Ctrl+F5”) получаем неактивную форму:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/97ee63c3-b3d8-4520-872b-0c65af538d77)

@Polfath , пожалуйста, посмотри.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
> _”Сделал”_

Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
1. **_Исследователь → Бухгалтерия → Закрытие месяца → 01.02. Реализация по оплате → 01. Разноска по покупателям_**.
2. **_Исследователь → Основные средства → Отчеты по ОС → Карточка по ОС_**.

При попытке переоткрытия вышеприведенных форм программа отображает следующее сообщение об ошибке:
![image](https://github.com/user-attachments/assets/20698a60-f619-463a-8256-6c3023a2571a)
**_Рис. 1._**

**Comment by Polfath** [comment]
@NikolayUkleyko Переоткрытие всех видов форм представляется затруднительным.
Потребует много ресурсов, времени.
Острой нужды в этом функционале нет (чего проще "Закрыть форму" - "Открыть форму").
Я сделаю уже сделанную реализацию недоступной для пользователей, а то, что сделано оставлю, может на будущее пригодится.

**Comment by NikolayUkleyko** [comment]
@Polfath , спасибо !
