### ISSUE TITLE
Хранилище. Инспектор объектов. После сохранения настроек автоматически меняется шрифт на MS Sans Serif

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4464]
1. Открываем диалоговую форму документа _**”Исследователь → Материальный склад → 01. Накладная на получение материалов, ОС, МБП”**_.
2. Переходим в режим инспектора объектов (**Ctrl + Alt + E**).
3. Выполняем выход из инспектора объектов с сохранением (**F2**).

В результате в шапке документа шрифт по всем полям автоматически поменялся с текущего **Tahoma** на **MS Sans Serif**.
Работает не верно.

@Polfath , пожалуйста, поправь.

**Comment by Polfath** [comment]
Поправил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
Доработки по данной теме не вошли в **gedemin.exe Delphi 7**.
@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
