### ISSUE TITLE
Бухгалтерия. Автоматические хоз. операции. Конструктор функций. Блок ”Цикл по проводкам”

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4465]
_**Исследователь → Бухгалтерия → Автоматические хоз. операции → Конструктор функций → Дополнительные → Цикл по проводкам.**_

Для работы с проводками достаточно блока **Цикл по счету**.
Каково практическое применение блока **Цикл по проводкам** ?
Возможно есть смысл скрыть такой блок ?

**Comment by Polfath** [comment]
Так сделано в #4469. А смысла скрывать нет. Не нужно - не пользуйтесь.

**Comment by MIchaelShoihet** [comment]
Лучше скрыть. Он такую ерунду делает....

**Comment by Polfath** [comment]
Скрыл

**Comment by NikolayUkleyko** [comment]
Доработки по данной теме не вошли в **gedemin.exe Delphi 7**.
@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
