### ISSUE TITLE
Общие. Выбор из множества. Результат поиска отображать с первой записи

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4466]
В форме выбора из множества результат поиска отображать с первой записи.

**<ins>Пример.</ins>**
Параметр – счет.

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/d98ba46b-5cf3-4dd9-8b66-e610240309cf)
**_Рис. 1. Существующий результат поиска_**

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/1133e416-81a3-4b4f-9ba3-8bd22c47e7e6)
**_Рис. 2. Желаемый результат поиска_**

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
Доработки по данной теме не вошли в **gedemin.exe Delphi 7**.
@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
