### ISSUE TITLE
Бухгалтерия. Оборотная ведомость. Сохранять параметры формирования

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4467]
_**Исследователь → Бухгалтерия → Оборотная ведомость.**_

Пожалуйста, предусмотрите возможность сохранения параметров для формирования данных.
Например, выбранный раздел плана счетов.
Такое в конфигурацию сохранить нельзя.

**Comment by Polfath** [comment]
Если в конфигурации сохранять раздел плана счетов, будет возникать ошибка "Счет не найден в активном плане счетов.". Поэтому сохранение конфигурации с заданным разделом не представляется возможным.

**Comment by NikolayUkleyko** [comment]
> _”Если в конфигурации сохранять раздел плана счетов, будет возникать ошибка "Счет не найден в активном плане счетов.". Поэтому сохранение конфигурации с заданным разделом не представляется возможным.”_

Спасибо за информацию, @Polfath !
Закрываем тему.
