### ISSUE TITLE
ПИ. FB 5.0. Ошибка при синхронизации ПИ

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4468]
Ошибка при синхронизации ПИ:
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/8e87c959-3917-4625-a84f-b1e515a7a547)

@Polfath , пожалуйста, посмотри.

**Comment by Polfath** [comment]
При загрузке ПИ выполняется запрос:

merge into at_object o
using (select ...)
on ...
when matched then update ...
  
В Firebird 3.0 и более ранних версиях, когда строка в целевой таблице (INTO) оператора MERGE соответствовала нескольким
строкам из выражения исходного запроса (USING), строка была обновлена несколько раз (в недетерминированном порядке).
В целях соответствия требованиям стандарта SQL в более поздних версиях будет возникать ошибка “Multiple source
records cannot match the same target during MERGE”  

Поправил @NikolayUkleyko проверь плиз

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
