### ISSUE TITLE
Бухгалтерия. Автоматические хоз. операции. Цикл по счету. Деактивируется грид

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4469]
_**Исследователь → Бухгалтерия → Автоматические хоз. операции.**_

1. Открыли цикл по счету.
2. Через несколько минут грид для выбора счета деактивируется.

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/de2773d7-40d1-41d4-8a13-917688a10d22)

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Доработки по данной теме не вошли в **gedemin.exe Delphi 7**.
@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
