### ISSUE TITLE
Общие. Редактор скрипт-объектов. Функция не добавляется в '#include

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4470]
_**Сервис → Редактор скрипт-объектов.**_

1. Выделяем функцию и пробуем ее добавить в _**'#include**_ (Ctrl + Enter).

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/dfb16628-a941-4f41-873c-567fc2dce806)
_**Рис. 1.**_
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/9e8481df-79de-4fa5-9abd-ed94e6b98f65)
_**Рис. 2.**_

2. В результате функция в _**'#include**_ не добавлена.

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/267bd041-4367-47a8-a3f3-b5728d848693)
_**Рис. 3.**_

Необходимо получить следующее:

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497453/f06bb676-0365-48eb-a150-61bccad64930)
_**Рис. 4.**_

**Comment by Polfath** [comment]
Вроде сделал, @NikolayUkleyko Проверь пожалуйста

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
Доработки по данной теме не вошли в **gedemin.exe Delphi 7**.
@Polfath , пожалуйста, посмотри.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
