### ISSUE TITLE
Фильтры. Поменять ограничение на доступ к фильтрам

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4472]
Для любого документа, справочника и т.д. сейчас доступны только 10 фильтров.
В списке фильтров хранится весь их перечень.
То есть, их может быть больше.
Пожалуйста, поменяйте ограничение на доступ к фильтрам с 10 до 25 фильтров.

**Comment by Polfath** [comment]
Поменял на 25 @NikolayUkleyko проверь пожалуйса

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !

**Comment by NikolayUkleyko** [comment]
Тема актуальна.

**Comment by Polfath** [comment]
Сделал 50
