### ISSUE TITLE
Бухгалтерия. Конструктор функций. Переменная из SQL-цикла в качестве значения параметра в функции

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4474]
1.Отдельное значение переменной из SQL-цикла выглядит следующим образом:
```ruby
SQLCycle_1.FieldByName("SUMMA").Value
```

2.Переменная из SQL-цикла в качестве значения параметра в функции выглядит так:
```ruby
[GS.MulDiv(SQLCycle_1_SUMMA, 1, 1, 1, 2)]
```

Не работает и ошибок нет.

Необходимо внести правки, чтобы в такой ситуации верно передавалось значение переменной:
```ruby
[GS.MulDiv(SQLCycle_1.FieldByName("SUMMA").Value, 1, 1, 1, 2)]
```

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
