### ISSUE TITLE
Modify базы Delphi_5, либо Delphi_7 

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4475]
Вопрос скорее всего в конкретной базе, при модифае вот такая вот ошибка, причем не имеет значения под каким экзе  идет модифай

![Screenshot 2024-06-11 123101](https://github.com/GoldenSoftwareLtd/gedemin/assets/11507129/f49054e6-9557-4de5-b78e-0e7916bba841)

**Comment by YRozmysl** [comment]
@MIchaelShoihet После восстановления под фб 3.0 и последующим подключением к ней, такая же ошибка при модифае базы.

**Comment by NikolayUkleyko** [comment]
Вероятно проблема в определенной базе данных.

**Comment by MIchaelShoihet** [comment]
Проблема в базе. Параметр процедуры и поле в таблице получили один и тот же RDB$ домен. Когда мы хотим изменить процедуру, firebird пытается удалить домен, который используется для входящего параметра (он там описан ENTRYKEY INTEGER), но удалить его нельзя, потому что он используется для поля USR$GS_SALETAXKEY в таблице AC_ENTRY_BALANCE и возникает ошибка... Получается исправить только, сначала изменив тип поля USR$GS_SALETAXKEY потом закоментировав тело процедуры, откомпилировать ее и потом запускать modify

**Comment by YRozmysl** [comment]
надо последовательно на старой базе выполнить два запроса:
ALTER TABLE AC_ENTRY_BALANCE ALTER COLUMN USR$GS_SALETAXRATE TYPE DINTEGER;

Потом
create or alter procedure AC_GETSIMPLEENTRY
returns (
    ID integer,
    DEBIT numeric(15,4),
    CREDIT numeric(15,4),
    DEBITCURR numeric(15,4),
    CREDITCURR numeric(15,4),
    DEBITEQ numeric(15,4),
    CREDITEQ numeric(15,4))
as
BEGIN                                                               
/*$$IBEC$$   ID = :ENTRYKEY;                                                   
  SELECT                                                            
    SUM(iif(corr_e.issimple = 0, corr_e.creditncu, e.debitncu)),    
    SUM(iif(corr_e.issimple = 0, corr_e.debitncu, e.creditncu)),    
    SUM(iif(corr_e.issimple = 0, corr_e.creditcurr, e.debitcurr)),  
    SUM(iif(corr_e.issimple = 0, corr_e.debitcurr, e.creditcurr)),  
    SUM(iif(corr_e.issimple = 0, corr_e.crediteq, e.debiteq)),      
    SUM(iif(corr_e.issimple = 0, corr_e.debiteq, e.crediteq))       
  FROM                                                              
    ac_entry e                                                      
    JOIN ac_entry corr_e on e.recordkey = corr_e.recordkey and      
      e.accountpart <> corr_e.accountpart                           
  WHERE                                                             
    [e.id](https://e.id/) = :entrykey AND                                            
    corr_e.accountkey + 0 = :acorraccountkey                        
  INTO :DEBIT,                                                      
       :CREDIT,                                                     
       :DEBITCURR,                                                  
       :CREDITCURR,                                                 
       :DEBITEQ,                                                    
       :CREDITEQ;                                                   
  SUSPEND;     $$IBEC$$*/
END
