### ISSUE TITLE
Различное поведение с принятием значения null в разных версиях exe-файла

### ISSUE THREAD

**Issue by maximsnkv** [GoldenSoftwareLtd/gedemin#4480]
В версии exe 2.9.5.12159 работоспособны конструкции следующих типов:
1) с объявлением значения null для поля, в котором возможны значения типа int и null
`_query_name_.ParamByName("_some_key_name_").AsVariant = ""`
2)  с использованием переменной без объявленного значения
```
dim var1
Call gdcBaseManager.ExecSingleQueryParam(_
"_some_sql_text_",  var1,  _Transaction_name_)
```
В версии exe 2.9.6.12476 в обоих вариантах происходят ошибки.
1) Для работоспособности кода необходимо изменить код на 
`_query_name_.ParamByName("_some_key_name_").AsVariant = null`
2) Необходимо присвоить переменной значение или убрать её.

**Comment by gsbelarus** [comment]
Выглядит как раньше была ошибка, а теперь работает правильно.

@MIchaelShoihet

**Comment by MIchaelShoihet** [comment]
Я то же считаю, что раньше было не правильно. Таких мест не очень много и возможно лучше их подправить
