### ISSUE TITLE
Ошибка при нажатии "Удалить" в окне "Выбора объектов для удаления" при установке ПИ

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4481]
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/a5049456-068a-419b-abd5-3368cf103c9b)

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/7bc9eefe-5c1f-4d80-b284-26fe5ff27e64)

Ошибка при удалении любого объекта, независимо от типа

**Comment by Polfath** [comment]
Поправил

**Comment by gsbelarus** [comment]
я написал комментарий в пул реквесте. разберитесь еще раз, так как в вашем исправлении возможно ошибка

**Comment by Polfath** [comment]
Добавил проверку
if (not TListItem(ListItems[I]).Checked) and (RemoveList.IndexOf(ListItems[I].RR) >= 0) then
      RemoveList.Delete(RemoveList.IndexOf(ListItems[I].RR));
