### ISSUE TITLE
Еще какая-то ошибка с типами FB3

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4483]
В случае, если переменной (с) присваивается результат выполнения запроса с определением count(l.DOCUMENTKEY):

если с = 0, то при проверке "if c = 0 then" ошибка 
"Переменная использует не поддерживаемый в VBScript тип программирования объектов".

Пример. База  192.168.0.78/3054:k:\bases\VolkMK\TORG_BAK_2024_06_27_01.fdb
Банк и касса - Касса -  Приходный ордер
Пост позиции, на методе DoAfterPost

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/ae7f5b3c-2de6-4abf-9b93-89cc805bd19a)

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/d9bd41f8-68fb-48cf-9d2f-900c5893365c)

На этой же базе при работе старым ехе состояние переменных такое:

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/4a94fcba-6369-4c11-ae98-eb2dbd6798f9)

На базе под FB2.5 в этом же месте при таком же состоянии переменных (с = 0) ошибки нет.

**Comment by gsbelarus** [comment]
@Polfath посмотрите из делфи что за тип. скорее всего так получается:

1. из запроса возвращается INT64
2. в Res записывается вариант varInt64
3. VBScript такой тип не поддерживает

надо подумать в какой момент преобразовывать. напрашивается сделать это в обертке для TLB. смотреть если вариант 64 бит, то переделывать в дабл.

и потом надо аналогично все остальные места проверить. например обращение через AsVariant, через Value...

**Comment by Polfath** [comment]
Сделал
