### ISSUE TITLE
Проверка качества сети

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#4484]
У нас часто возникают ситуации, когда программа работает нестабильно из-за плохого сетевого соединения. 

Предлагается следующее:

1. Добавить в главное меню команду проверка сети.
2. При ее вызове выводить сообщение:

> Сейчас будет выполнена проверка сетевого соединения.
Если количество потерянных пакетов отлично от 0%
или время ожидания ответа более 1 мс, значит в вашей
локальной сети сущесттвуют проблемы с коммутационным
оборудованием или кабелями. Свяжитесь с системным
администратором для их решения.

3. По нажатию на кнопку Ок запускать в отдельных окнах ping операционной системы для:
    1. сервера базы данных 
    2. кассового сервера, если программа работает в режиме кассы
    3. сервера мобильного приложения, если программа работает в режиме сервера для мобильных устройств
    
Вот здесь описано как вызвать команду чтобы окно потом осталось открытым на экране:

https://stackoverflow.com/questions/7526598/how-to-keep-the-vbscript-command-window-open-during-execution

Таким образом можно всегда зайти и посмотреть сеть и связь со всеми серверами.

Команда должна быть доступна под любой учетной записью.

**Comment by Polfath** [comment]
Добавил проверку

**Comment by AliakseiDanilchyk** [comment]
После запуска команды появляется окно с описанным выше сообщением. В этом сообщении две опечатки:
1.	будет выполнен проверка
2.	время ожидания ответо

**Comment by yoannawx** [comment]
на Cash не работает: 
1. окно подтверждения не модальное, скрывается за открытыми вкладками
2. не понимает сервер: не выделяет сервер из пути

**Comment by AliakseiDanilchyk** [comment]
После первого окна, где отображается описание действий, выполняемых командой, последовательно открывается 3 диалоговых окна (не модальных) с наименованием проверяемого сервера и кнопкой Ок.
Если на момент запуска команды в Гедымине открыты какие-либо окна кроме Исследователя
1.	В окне с наименованием сервера БД нажимаем Ок.
2.	Открывается окно командной строки с пингом сервера и сразу же под ним окно наименованием кассового сервера и кнопкой Ок.
3.	Дожидаемся окончания пинга сервера БД и закрываем окно командной строки.
4.	Окно с наименованием кассового сервера (из пункта 2) заваливается под открытые окна Гедымина.

**Comment by Polfath** [comment]
Попытался устранить замечания @AliakseiDanilchyk и @yoannawx. Коллеги, при возможности посмотрите пожалуйста.

**Comment by AliakseiDanilchyk** [comment]
Проверил. Все ок. Можно закрывать.
