### ISSUE TITLE
Ошибка при обновлении ПИ.

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4485]
Ошибка из-за неверного синтаксиса скл-запроса. ехе от 02.07.24

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/b1dca859-05d5-48fb-ab3f-7b659b93325a)

**Comment by MIchaelShoihet** [comment]
Странно запрос правильный. А какой там сервер firebird?

**Comment by yoannawx** [comment]
да, не FB3, a FB2.5

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/d24caaee-7385-4781-b4dc-038a37e4be50)

**Comment by MIchaelShoihet** [comment]
На нем это вообще не должно выполняться... Проверка версий FB должна быть

**Comment by Polfath** [comment]
Там есть проверка на версию при загрузке ексепшинов и гранты раздаются только, если версия >= 3

**Comment by MIchaelShoihet** [comment]
Если есть почему под 2.5 выполняется, надо проверить

**Comment by Polfath** [comment]
Я проверил. У меня на той же базе тоже ПИ, что и у @yoannawx загрузка ПИ отработала (версия вернулась 2). Как мне поймать этот баг?

**Comment by gsbelarus** [comment]
а как вы версию определяете?

**Comment by Polfath** [comment]
procedure AddGrant;
  begin
    Database.
    //Для FB версии >= 3 нужны гранты на EXCEPTION
    if Active and (not IsEmpty) and (Database.ServerMajorVersion >= 3) then
      S.Add('GRANT USAGE ON EXCEPTION ' + FirebirdObjectName + ' TO ADMINISTRATOR');
  end;

**Comment by Polfath** [comment]
procedure AddGrant;
  begin
    //Для FB версии >= 3 нужны гранты на EXCEPTION
    if Active and (not IsEmpty) and (Database.ServerMajorVersion >= 3) then
      S.Add('GRANT USAGE ON EXCEPTION ' + FirebirdObjectName + ' TO ADMINISTRATOR');
  end;

**Comment by Polfath** [comment]
TgdcException.GetMetadataScrip

**Comment by yoannawx** [comment]
Отловила, как получается ошибка.
Работала на базе под ФБ3.
Сделала База данных - Отключиться. 
Потом База данных - Подключиться и подключилась к другой базе, которая под ФБ 2.5.
И вот в этом случае получила ошибку при установке пи.

**Comment by Polfath** [comment]
Для корректной работы при переключении между БД, если версия ФБ была 2.5, а хотите подключиться к 3+ лучше переоткрыть Гедемин.

**Comment by NikolayUkleyko** [comment]
> _”Для корректной работы при переключении между БД, если версия ФБ была 2.5, а хотите подключиться к 3+ лучше переоткрыть Гедемин.”_

Как в данной ситуации и ряде других надежнее выполнять закрытие программы и новое подключение к базе данных.
Варианты переподключения и прочие (может быть их убрать вовсе) могут не давать должного эффекта.

**Comment by AndreiKireyeu** [comment]
@Polfath это ошибка у нас. не сбрасываются какие-то закэшированные переменные.

**Comment by gsbelarus** [comment]
@Polfath  это ошибка у нас. не сбрасываются какие-то закэшированные переменные.

**Comment by MIchaelShoihet** [comment]
Мы нашли место. Оно IBDatabase. Там один раз считывается версия firebird. Надо лезть внутрь его, а зачем? Там все переменные ReadOnly один раз инициализируются. Я думаю, что нет смысла, в этом копаться

**Comment by AndreiKireyeu** [comment]
там надо афтер дисконнект поставить очистку этих переменных.

**Comment by Polfath** [comment]
Сделал
