### ISSUE TITLE
Ошибка при просмотре ТХО с отменой сохранения

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4486]
Воспроизводится не на всех тхо, но на многих.
Например, на эталоне (lepel/3053:g:\Etalon\ETALON_COMPLETE.FDB) можно посмотреть тхо Списание товаров.

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/be299f20-e443-4626-baae-5437c8a7d499)

Далее нажимаем Отмена. Сохранить - нет.

![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/02efbe01-1ded-49c3-989d-a57e91779f21)

**Comment by YRozmysl** [comment]
Подтверждаю, в зарплате такие  есть тоже тхо. Не все, но есть. Например, Доп.дни отпуска

**Comment by gsbelarus** [comment]
все ошибки сразу на @Polfath ассайнте. пусть сидит, ищет.

**Comment by Polfath** [comment]
Сделал

**Comment by yoannawx** [comment]
проверено
