### ISSUE TITLE
Не корректируется имя функции при создании макроса на основе существующего

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4488]
При создании нового макроса путем копирования уже существующего не корректируется имя функции при нажатии Да в сообщении 
![image](https://github.com/GoldenSoftwareLtd/gedemin/assets/11497358/9e907af6-3ad9-4493-b0d7-e12eef9c7b9d)

**Comment by NikolayUkleyko** [comment]
@yoannawx , подобный вопрос был рассмотрен здесь _https://github.com/GoldenSoftwareLtd/gedemin/issues/4437_.

@Polfath внес правку для скрипт-функции отчетов, а для макросов вероятно нет.

**Comment by Polfath** [comment]
Сделал

**Comment by yoannawx** [comment]
проверено
