### ISSUE TITLE
Склад. Настройка остатков. Предусмотреть дублирование со всеми складскими признаками

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4491]
_**Исследователь → Сервис → Складские параметры → Настройка остатков.**_

Пожалуйста, предусмотрите дублирование записей со всеми объектами, включая, складские признаки и прочие параметры.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
