### ISSUE TITLE
Не сохраняются изменения в скрипте при переходе в окно поиска

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4493]
Пример.
Нужно найти и поменять значения .AsVariant = ""
на .AsVariant = null
Находим с помощью поиска все такие места.

![image](https://github.com/user-attachments/assets/ebcc4f65-aa00-4c87-99db-bfc8e8cd4ee5)

В функции Sf_export_gd_good несколько таких мест.
Переходим на первое и меняем:

![image](https://github.com/user-attachments/assets/2fd39346-2d95-4bec-9cae-3fe0205666ce)

Переходим на второе. При этом изменения в первом откатываются: 

![image](https://github.com/user-attachments/assets/e11320f4-dccc-4666-986b-eb3873108442)

**Comment by Polfath** [comment]
Баг не воспроизводится. Нечто подобное я уже правил. @yoannawx Посмотри, к примеру https://github.com/GoldenSoftwareLtd/gedemin/issues/4470

**Comment by yoannawx** [comment]
База lepel/3054:K:\BASES\Hlebroznica\BACK_2024_07_11.FDB, пароль admin
пример тот же

**Comment by Polfath** [comment]
Ввела в заблуждение. Для Пароля регистр важен (не admin)

**Comment by Polfath** [comment]
Щас проверю баг

**Comment by Polfath** [comment]
@yoannawx Я попытался воспроизвести баг на твоей базе Hlebroznica. Все корректно работает, .AsVariant = "" поменялся на .AsVariant = null. Сброшу тебе в личку в дискорде ехе, который у меня.

**Comment by NikolayUkleyko** [comment]
Очевидно, что необходимо проверять на **gedemin.exe**, полученном из одного источника.
Кто куда.

**Comment by yoannawx** [comment]
на ехе из дискорда все то же самое (

**Comment by gsbelarus** [comment]
а почему с сайта не берете экзе?

**Comment by yoannawx** [comment]
Ошибка выявлена на ехе, взятом с сайта. Поскольку Андрей не смог воспроизвести на своей версии ехе, взяла его версию, там ошибка также воспроизводится

**Comment by Polfath** [comment]
Я воспроизвел. Спасибо за подсказку. Сделаю.

**Comment by Polfath** [comment]
Вроде как сделал

**Comment by yoannawx** [comment]
Изменения сохраняются, но чтобы ввести изменения, можно удалить заменяемое значение только с помощью Backspace, перезапись выделенного фрагмента и Delete его не работают

**Comment by Polfath** [comment]
Починил
