### ISSUE TITLE
Редактор скрипт объектов. Удаление. 

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4496]
Если в редакторе выделить текст и нажать backspace на клавиатуре, то ничего не происходит. На старом  exe все работает.
![Screenshot 2024-08-02 161515](https://github.com/user-attachments/assets/3fa33bd0-7e4a-4d3b-9429-3feb1670c9cd)

**Comment by YRozmysl** [comment]
Уточнение.  Выделенный текст не удаляется и по кнопке Del

**Comment by gsbelarus** [comment]
сразу ставь @Polfath ответственным

**Comment by YRozmysl** [comment]
нет прав у меня в этой ветке, чтобы проставить "Assignees"

**Comment by Polfath** [comment]
Поправил

**Comment by YRozmysl** [comment]
Проверено, все ок
