### ISSUE TITLE
Бухгалтерия. Оборотная ведомость. Количество аналитик для формирования развернутого сальдо

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4497]
_**Исследователь → Бухгалтерия → Оборотная ведомость.**_
_**Исследователь → Бухгалтерия → План счетов.**_

При формировании оборотной ведомости с указанием по счету (субсчету) более 3-х аналитик для развернутого сальдо программа отображает сообщение об ошибке:
![image](https://github.com/user-attachments/assets/abf8af10-b864-4471-9537-4f2f9ea07368)
_Рис. 1._

В плане счетов при выборе по счету (субсчету) более 3-х аналитик для развернутого сальдо добавить соответствующее сообщение.

**Comment by MIchaelShoihet** [comment]
Точно нужно 3 уровня аналитики?

**Comment by NikolayUkleyko** [comment]
Достаточно 2-3 аналитик.
Давно Стас просил реализовать такую возможность.
Татьяна сделала.
Заметил по счетам, где пользователь указал 4 аналитики для развернутого сальдо.

**Comment by MIchaelShoihet** [comment]
Мне кажется что достаточно 2-х уровней... Чаще всего дальше они избыточны... Может просто запретить больше 2-х?

**Comment by NikolayUkleyko** [comment]
Я полагаю, что достаточно не более 2-х аналитик для развернутого сальдо.

**Comment by gsbelarus** [comment]
@Polfath поставь ограничение на 3 уровня. чтобы больше нельзя было выбрать

**Comment by Polfath** [comment]
По согласованию с "инициатором" - @NikolayUkleyko при выборе больше 3-х аналитик для развернутого сальдо просто выдается предупреждение. @NikolayUkleyko проверь плз

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
