### ISSUE TITLE
Процедура GD_P_GETNEXTID_EX исправить...

### ISSUE THREAD

**Issue by MIchaelShoihet** [GoldenSoftwareLtd/gedemin#4498]
Зачем-то в процедуре GD_P_GETNEXTID_EX закоментировано часть кода:
    IF (id = -1) THEN
    BEGIN
      id_to = GEN_ID(gd_g_unique, 1);

/*      id = :id_to - 100 + 1;
      RDB$SET_CONTEXT('USER_SESSION', 'GD_CURRENT_ID', :id + 1);
      RDB$SET_CONTEXT('USER_SESSION', 'GD_LIMIT_ID', :id_to); */

    END
Из-за чего ID никогда не присвоится если нет интервалов...  Хотели наверное убрать кэширование, но сломали всю процедуру.

**Comment by MIchaelShoihet** [comment]
Это надо сделать прямо сейчас. Ни одна база с сайта не рабочая!!!

**Comment by gsbelarus** [comment]
@Polfath  и в скриптах исправьте и модифай сделайте. жду пул реквест.

**Comment by Polfath** [comment]
Поправил
