### ISSUE TITLE
Проблема с использованием функции "Закомментировать" по выделенному тексту в Редакторе скрипт-объектов

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4499]
В Редакторе скрипт-объектов выделяем текст и выбираем "Закомментировать".

![image](https://github.com/user-attachments/assets/0d92644a-4cdc-4c83-abaa-f4c390b004d5)

В результате создается копия выделенного текста, после которой комментируется исходный текст.

![image](https://github.com/user-attachments/assets/5e1c62f0-1086-4161-bbdc-609fc63349fe)

Та же беда с использованием функции "Откомментировать".

exe от 09.08 с сайта

возможно, у проблемы те же корни, что и здесь https://github.com/GoldenSoftwareLtd/gedemin/issues/4493#issuecomment-2268483376

**Comment by Polfath** [comment]
Поправил
