### ISSUE TITLE
Общие. Формы, отчеты. Произвольные элементы

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4500]
Бухгалтера не первый раз спрашивают про произвольные элементы на различных формах, отчетах и т.д.
Вероятно, что при компиляции **gedemin.exe** что-то лишнее было сохранено.
![image](https://github.com/user-attachments/assets/6a6faf70-77a2-49cf-ba0e-ae649189383d)
_Рис. 1._

Скроллы роли не играют.

**Comment by Polfath** [comment]
Не удается воспроизвести. Нужна реальная ситуация, когда это возникает.

**Comment by NikolayUkleyko** [comment]
У клиента такое есть, а локально нет.
