### ISSUE TITLE
Некорректная работа комбинации клавиш Ctrl + v в SQL редакторе

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4502]
1. Копируем в буфер обмена имя какой-либо таблицы (например GD_GOOD)
2. В окне SQL редактора на панели инструментов устанавливаем фокус на лук-ап "Таблицы" и нажимаем комбинацию клавиш Ctrl + v.
3. Вставка производится не в поле лук-апа, а в поле, где вводится текст запроса

![bug](https://github.com/user-attachments/assets/eb4e4538-fe77-4bfe-a316-06ac3b262cd9)

Команда "Вставить" из контекстного меню лук-апа работает.

**Comment by Polfath** [comment]
Сделал

**Comment by YRozmysl** [comment]
В дополнение. Не работает "Вставить, Копировать, Вырезать" в контекстном меню SQL-редактора в области ввода запроса.

**Comment by YRozmysl** [comment]
![Безымянный](https://github.com/user-attachments/assets/7b9ab35b-d676-4ba7-a7eb-8ebe8ab7fd76)

**Comment by AliakseiDanilchyk** [comment]
Теперь комбинация клавиш Ctrl + C в SQL-редакторе срабатывает с третьего раза.
Проверяли на 2-х компах с разных клавиатур, если что.

**Comment by Polfath** [comment]
Поправил

**Comment by YRozmysl** [comment]
Вроде, как исправилось
