### ISSUE TITLE
Хранилище. Наименование сохраняемого DFM файла

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4503]
**Хранилище.**

Пример.
_**Исследователь → Материальный склад → 01. Накладная на получение материалов, ОС, МБП.**_

При сохранении DFM файла программа автоматически формирует его наименование следующим образом:
**Tgdc_frmInvDocument.dfm**

![image](https://github.com/user-attachments/assets/d22422aa-d978-4f3d-a34f-b380cab2f48f)
**_Рис. 1._**

Можно ли предусмотреть при сохранении DFM файла добавление к его наименованию имени документа, справочника и т.д.:
**01. Накладная на получение материалов, ОС, МБП-Tgdc_frmInvDocument.dfm**.

**Comment by Polfath** [comment]
Имя самой формы не хранится в DFM. Чтобы его вытащить, нужно большой огород городить. 
Сделал вида147012468_486813904-TdlgInvDocument.DFM

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
