### ISSUE TITLE
Некорректное сохранение истории SQL

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [GoldenSoftwareLtd/gedemin#4504]
Раньше SQL редактор сохранял в историю только запросы, которые запускали на выполнение.
Сейчас если ввести любой текст и закрыть редактор или переключиться на вкладку История, то этот текст сохранится в истории.
Это появилось в exe от 12.09.2024

**Comment by MIchaelShoihet** [comment]
Я бы сказала что это и хорошо. Я столько раз терял запросы, потому что не доходило до запуска :)
