### ISSUE TITLE
Ошибка открытия DFM-форм (не всех, некоторых) при повторной загрузке на базу.

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4505]
Ошибка открытия DFM-форм (не всех, некоторых) при повторной загрузке на базу.
Столкнулся с такой проблемой, что если формировать чистый эталон ЗПиОК из ПИ, которые лежат в репозитории на данный момент, то все формируется и все формы открываются. 
Действия:
1) Собираем базу из пи. Проверяем, открывается ли из исследователя Зарплата и отдел кадров/ зарплата / параметры. Должно открываться. 
2) снимаем с базы пи зарплата - хранилище. В него как раз входит эта форма
3) ставим это же пи (которое только что сняли) на эту же базу с галкой всегда перезаписывать
4) повторяем пункт 1.

Р.S. после выполнения пункта 2, сравниваем есть ли отличия у снятого пи с ПИ, которое установлено на базу. Видим, что их нет.
![Screenshot 2024-09-23 114549](https://github.com/user-attachments/assets/407cb97e-6ce2-431b-a176-cc86c8648ece)

**Comment by YRozmysl** [comment]
после выполнения п.3 видим, что уже конкретно у этой формы есть различия. Не знаю, влияет ли это  на ошибку, просто наблюдение.
![Screenshot 2024-09-23 130553](https://github.com/user-attachments/assets/acff91d0-26fb-40a3-85d1-65a4815ad76e)

**Comment by YRozmysl** [comment]
кое-что выяснилось конкретно вот с этой формой для примера. В репозитории  сейчас лежит ПИ, где caption для нее выглядит вот так  **Caption = 'Параметры подсистемы '#39'Зарплата и Отдел кадров'#39**   С таким кэпшном все грузится   хорош. А, когда мы снимаем с базы  это ПИ то caption уже имеет вот такой вот вид с двойной кавычкой в конце  **Caption = 'Параметры подсистемы 'Зарплата и Отдел кадров''** из-за которой и возникает проблема с формой

**Comment by Polfath** [comment]
Поправил

**Comment by YRozmysl** [comment]
проверил, ошибок не было
