### ISSUE TITLE
Склад. Новое поле в позиции документа и его свойства

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4508]
При добавлении нового поля (ссылка на подразделения, сотрудников) в позицию таблицы складского документа автоматически присваиваются следующие свойства:
![image](https://github.com/user-attachments/assets/228f4e2d-2b03-4481-98f2-8adceef8c80d)
**_Рис. 1._**

В настройках поля, домена ограничений нет.
При этом, вручную внесенные изменения настроек такого поля не сохраняются.
Решением может быть только указание в коде свойств поля.

Можно ли предусмотреть, чтобы свойства поля брались из настроек поля, домена.
Ручные изменения свойств грида также корректно сохранялись.

Для пользовательских документов таких вопросов нет.
Это давняя тема.

**Comment by MIchaelShoihet** [comment]
Происходит автоматическая настройка полей Откуда и Куда. Домен тут совсем не причем.

**Comment by NikolayUkleyko** [comment]
Посмотрел.
Порядок.
Спасибо, @MIchaelShoihet !
