### ISSUE TITLE
Бухгалтерия. Конструктор функций. Сложные проводки. Формирование проводок на нулевые суммы

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4509]
_**Исследователь → Бухгалтерия → Типовые хоз. операции.**_

Пример.
По документу не указана сумма НДС.
Предполагается формирование проводок на сумму без НДС **Дт 10... – Кт 60...**

![image](https://github.com/user-attachments/assets/a7042dd7-94d5-488e-9916-fbf1f0b1a40e)
**_Рис. 1. Конструктор функций. Сложная проводка._**

![image](https://github.com/user-attachments/assets/b940ab95-b337-4649-aaa6-0fd9ee8bd21e)
**_Рис. 2. Журнал хоз. операций._**

Зеленым цветом выделена проводка на нулевую сумму.
Она не должна быть сформирована.

-----

![image](https://github.com/user-attachments/assets/ae7e695c-072a-4f36-88c1-3e2b83e8d986)
**_Рис. 3. Конструктор функций. Простая проводка._**

![image](https://github.com/user-attachments/assets/012175e5-166d-4dd3-b112-53ac3a648cfe)
**_Рис. 4. Журнал хоз. операций._**

Проводки сформированы верно.

**Comment by MIchaelShoihet** [comment]
Так всегда была. Сложная проводка не проверяет на 0 отдельные ее части. Это не влияет на результат. В последствии можно сделать
