### ISSUE TITLE
Бухгалтерия. Журнал хоз. операций. Группировать по документу. Ошибка

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4511]
_**Исследователь → Бухгалтерия → Журнал хоз. операций.**_

При отключенной фильтрации данных при простановке галки по параметру **”Группировать по документу”** программа отображает следующие окна об ошибке:
![image](https://github.com/user-attachments/assets/0d26465a-0c6c-4384-bb14-17cc0552a759)
**_Рис. 1._**

![image](https://github.com/user-attachments/assets/cd410466-ae1f-4f80-8333-115a58b11cdf)
**_Рис. 2._**

![image](https://github.com/user-attachments/assets/c55b3a8c-3e68-4996-b91d-4ef48846f1b2)
**_Рис. 3._**

![image](https://github.com/user-attachments/assets/56d4b7ff-a892-413c-a7e5-d604c9aa9ff9)
**_Рис. 4._**

Закрыть такие окна не получается.
Выручает Диспетчер задач.

**Comment by MIchaelShoihet** [comment]
А если эту галку вообще убрать? Или ей часто пользуются? На больших данных она может очень долго выводиться

**Comment by NikolayUkleyko** [comment]
На мой взгляд широкого применения такой параметр не нашел.
Можно его просто скрыть.

В Журнале хоз. операций анализируем проводки как есть без переформатирования.

Подобный параметр есть в карте счета.
По необходимости можно его применять.

**Comment by Polfath** [comment]
Скрыл группировку по документу.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
