### ISSUE TITLE
как отключить функцию проверки подключенных пользователей

### ISSUE THREAD

**Issue by Mikle88** [GoldenSoftwareLtd/gedemin#4512]
Добрый день.
Подскажите как отключить функцию проверки подключенных пользователей, после создания или изменения процедуры, либо изменения или создания нового триггера. Не совсем удобно что-то делать, когда всех нужно отключать постоянно.
 
![12355](https://github.com/user-attachments/assets/24b56ad5-ab68-4638-ad0b-f85f0b803a82)

**Comment by MIchaelShoihet** [comment]
Добрый день. Никак нельзя отключить.

**Comment by Mikle88** [comment]
так а в предыдущей версии 2.6  данного сообщения не было.
Где логика, если нужно что-то по-быстрому поправить, я должен отключить кучу пользователей. Т.е. остановить все жизненные процессы: никто ничего не отгрузит, не посчитает и т.д.  А если будет много поправок? БД же не однопользовательская всё-таки!
Есть какой-то выход?

**Comment by MIchaelShoihet** [comment]
FireBird с версии 2.5 не дает исправлять процедуру, если ее кто-то хоть один раз выполнял... Поэтому Гедемин не дает их исправлять в многопользовательском режиме. Вы всегда можете скопировать запрос из окна редактирования процедуры и выполнить его в SQL редакторе и там как вам повезет, никто эту процедуру не выполнял, то она измениться

**Comment by Mikle88** [comment]
так если я платформу запускаю версии 2.6 и подключаюсь модифицированной БД под платформу 2.9, у меня всё сохраняется без отключения пользователей. А на серваке как стоял FireBird версии 2.5.8, так и стоит. Дело, наверное, всё таки не в FireBird

**Comment by MIchaelShoihet** [comment]
Если кто-то процедуру выполнил, то ее поменять нельзя ни в какой версии. В 2.9 мы стали строже к этому относится, потому что механизм работает не только при ручном изменении, но и при загрузке настроек и пространства имен, возникнет ошибка, все прервется. Надо изменить и вы знаете, что никто процедуру не выполнял, можно через sql редактор, как я писал выше

**Comment by Mikle88** [comment]
Хорошо, через sql подойдет. Спасибо.
