### ISSUE TITLE
Бухгалтерия. Отчеты бухгалтерии. Не удаляются проводки после удаления расчета

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4513]
_**Исследователь → Бухгалтерия → Отчеты бухгалтерии → Расчет.**_

Не удаляются проводки после удаления расчета.
Ранее они удалялись.

**Comment by fiatikrb** [comment]
> _**Исследователь → Бухгалтерия → Отчеты бухгалтерии → Расчет.**_
> 
> Не удаляются проводки после удаления расчета. Ранее они удалялись.

прошу прощения, а можно сделать видео с экрана, как происходит всё это удаление?
что-то типа вот такого, как во вложении

https://github.com/user-attachments/assets/6b834b32-b37d-4f5d-b86d-f2c6d29297d7

(у меня нет инструмента для видео с экрана, пользовался онлайн-рекордером вот по этой ссылке: https://online-screen-recorder.com/ru)
честно провозился полдня, но без каких-либо знаний бухгалтерии в целом и гедымина в частности мне не помогли ни usergd.pdf, ни newdevguide.pdf, ни тд
мне [MIchaelShoihet](https://github.com/MIchaelShoihet) показал, как это сделать, но я не запомнил, увы

**Comment by NikolayUkleyko** [comment]
Возможно текущая тема связана с такими доработками _https://github.com/GoldenSoftwareLtd/gedemin/issues/4420#issuecomment-1735951075_.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
