### ISSUE TITLE
Бухгалтерия. Формы. Возврат на предыдущую форму

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4514]
**_Исследователь → Бухгалтерия → Главная книга._**
При переходе из Главной книги в Журнал-ордер не активна кнопка возврата на предыдущую форму (в Главную книгу).

**_Исследователь → Бухгалтерия → Оборотная ведомость._**
При переходе из Оборотной ведомости в Анализ счета или Журнал-ордер не активна кнопка возврата на предыдущую форму (в Оборотную ведомость).

![image](https://github.com/user-attachments/assets/61f8031d-fddb-4e8c-b49b-69afc4310e12)
_Рис. 1._

![image](https://github.com/user-attachments/assets/d3f1b1f5-e4c3-4bb3-9776-c8c874814cbd)
_Рис. 2._

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !
