### ISSUE TITLE
Множественное добавление в кэпшн при сохранении диалоговой формы справочника ТНВЭД

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin#4515]
Замечено только на спрвочнике Коды ТНВД (в исследователе Справочники - Справочник ТМЦ - Коды ТНВД). На любой базе нужно установить ПИ "GS.Общее.Локализация.Для электронных документов.yml"  со всеми зависимыми.
Если открыть запись на редактирование, зайти в режим редактирования диалоговой формы и сохранить (не обязательно что-то редактировать), то в кэпшн каждый раз добавится:

![image](https://github.com/user-attachments/assets/5419f4bc-f29c-4b45-b204-40e574916d7a)

**Comment by NikolayUkleyko** [comment]
Аналогично и для справочника типовых хоз. операций.

**Comment by Polfath** [comment]
Такая ситуация возникала при редактировании форм с BorderStyle = bsDialog. В этом случае каждый раз при открытии формы в Caption автоматически добавлялся префикс "Добавление", "Редактирование", "Просмотр" и при сохранении формы в редакторе форм он сохранялся, а при последующем открытии формы в Caption добавлялся очередной префикс. Так было и в версии D5. Я убрал добавление префиксов. Теперь заголовок будет выглядеть, например так: было - "Редактирование: Типовая хоз. операция", станет - "Типовая хоз. операция" по аналогии с формами с BorderStyle = bsSizeable. В тех формах, где Caption уже поменялся на "некрасивый", нужно зайти в редактор форм и подкорректировать его.
