### ISSUE TITLE
Группировка макросов в папки не по полю MACROSGROUPKEY

### ISSUE THREAD

**Issue by gs7600300** [GoldenSoftwareLtd/gedemin#4517]
1. Скачал с сайта базу кассового сервера с exe;
2. В глобальных макросах увидел 2 папки "Файлообмен";
3. Добавил свой макрос "Экспорт прайса в zPOS (csv)";
4. Папок стало 3.
5. В таблице EVT_MACROSLIST, поле MACROSGROUPKEY у всех одинаковый. Я ожидал группировку по этому полю.

![image](https://github.com/user-attachments/assets/0a7e7fc3-5197-4bed-9f38-14f4d98e82ed)

**Comment by gs7600300** [comment]
* Очистка базы тоже 2 раза, как видно на скрине

**Comment by NikolayUkleyko** [comment]
Актуально и для локальных макросов.
@Polfath , пожалуйста, посмотри.

**Comment by Polfath** [comment]
Исправил

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
