### ISSUE TITLE
Общие. В контекстном меню в диалоговой форме документа отсутствуют команды по копированию данных

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4520]
Вопрос от бухгалтера, работавшего с 1С Предприятием.
Можно ли в контекстном меню в диалоговой форме документа предусмотреть команды по копированию данных:
• Копировать;
• Вставить;
• Вырезать.

Про выполнение таких команд при помощи горячих клавиш известно.
Чтобы не бегать по клавиатуре, а работать с мышкой.
Принципиально наличие таких команд в контекстном меню.

![image](https://github.com/user-attachments/assets/6f496ba9-bcab-43c9-9e17-d66aca5fd240)
_**Рис. 1.**_

**Comment by MIchaelShoihet** [comment]
Надо добавить. Согласен с бухгалтером

**Comment by Polfath** [comment]
Добавил

**Comment by NikolayUkleyko** [comment]
@Polfath , пожалуйста, уточнение.
Верно отображать команды по копированию данных в отдельном меню.
Не нагружать существующее основное меню.

**Comment by Polfath** [comment]
@NikolayUkleyko У формы может быть только одно меню. Как вызывать второе?

**Comment by NikolayUkleyko** [comment]
Вряд ли можно реализовать отдельное меню.

**Comment by MIchaelShoihet** [comment]
Добавьте команды в текущее меню

**Comment by NikolayUkleyko** [comment]
Проверено.

1. При копировании наименований записей из текстовых полей соответствующие команды **_активны_** в контекстном меню.
Работает верно.
![image](https://github.com/user-attachments/assets/0b629a1e-1298-4aa0-983e-ceb9d2b5bdae)
**_Рис. 1._**

2. При копировании наименований записей из полей ссылок соответствующие команды **_не активны_** в контекстном меню.
Работает не верно.
![image](https://github.com/user-attachments/assets/0d6281ac-664b-4269-bb65-517df29b9e5b)
**_Рис. 2._**

**Comment by Polfath** [comment]
Для копирования, вставки, вырезания использовались стандартные делфийские TEditAction (TEditCopy, TEditPaste, TEditCut), а они работают только с компонентами наследниками TCustomEdit. ComboBox таким не является, поэтому не работало. Переделал TEditAction на стандартный TAction и сделал для них свою обработку.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , спасибо !
