### ISSUE TITLE
Ошибка при  открытии диалоговой формы складских документов

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin#4522]
На самом последнем exe не открывается ни один складской документ.  вот такая вот ошибка
![Screenshot 2024-12-12 150852](https://github.com/user-attachments/assets/2e0b3ce4-782d-4074-952a-01f42eb37f46)

**Comment by YRozmysl** [comment]
![Screenshot 2024-12-12 151238](https://github.com/user-attachments/assets/d86b1d90-1f68-43c5-a102-f5eef5bb8002)

**Comment by Polfath** [comment]
Поправил

**Comment by YRozmysl** [comment]
Проверено, все исправлено.
