### ISSUE TITLE
Типовые документу. Прайс на услуги. Добавление новой цены

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin#4523]
_**Исследователь → Сервис → Типовые документы → Прайс на услуги.**_

1. Редактируем документ.
2. Выбираем закладку **”Позиция”**.
3. Пробуем добавить признак **”Цена учета”**. В результате цену добавить нельзя. Не активна стрелка.

**Comment by Polfath** [comment]
При выборе поля с типом CURRENCY необходимо обязательно указывать валюту, в которой ведется учет.

**Comment by MIchaelShoihet** [comment]
Да правильно, обязателен выбор валюты

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath, @MIchaelShoihet, спасибо !
