### ISSUE TITLE
Создание дескрипторов безопасности

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#56]
Originally reported on Google Code with ID 56

```
В диалоговое окно создания новой пользовательской таблицы добавить чек
боксы для создания дескрипторов безопасности и, возможно, иных системных
полей (например, CREATORKEY, CREATIONDATE).
```

Reported by `gs1994` on 2006-11-17 23:01:42

**Comment by gsbelarus** [comment]
Reported by `flakekun` on 2009-03-26 10:59:11
- **Labels added**: GedeminExe

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
