### ISSUE TITLE
Сохранять настройки гридов

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#581]
Originally reported on Google Code with ID 581

```
Сделать так, чтобы загрузка пакетов настроек на перезаписывала настройки
гридов, сделанные пользователем.


```

Reported by `gs1994` on 2007-04-18 07:22:34

**Comment by gsbelarus** [comment]
```
А разве это хорошо, а если мы добавили фукционяльное поле, которое должно 
отображаться или заполняться, что тогда делать. Предлагаю обсудить этот вопрос.
```

Reported by `Alexander.GoldenSoft` on 2007-04-18 16:15:56

**Comment by gsbelarus** [comment]
```
Пусть лучше человек еще раз перенастоит грид, чем не узнает, что добавилось поле, имхо
```

Reported by `alexandra.gsoftware` on 2007-04-18 16:18:04

**Comment by gsbelarus** [comment]
```
а если он настроил 20-30 гридов?? 
```

Reported by `gs1994` on 2007-04-18 16:20:10

**Comment by gsbelarus** [comment]
```
А если мы добавили 5-10 полей?
```

Reported by `Alexander.GoldenSoft` on 2007-04-18 16:22:01

**Comment by NikolayUkleyko** [comment]
Весьма актуальны вопрос.
Как вариант, предусмотреть глобальный режим настройки.
У кого какие будут предложения ?

**Comment by NikolayUkleyko** [comment]
Коллеги, если, на ваш взгляд данная тема уже неактуальна, пожалуйста, закройте ее.
