### ISSUE TITLE
Дата поступления товара

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#614]
Originally reported on Google Code with ID 614

```
Материальный склад. Или в оборотной ведомости или в акте на списание (а 
лучше всего и там и там) показывать дату поступления товара (если в 
оборотке группируется несколко поступлений в одну строку, то показывать 
дату последнего поступления). Это необходимо, чтобы бухгалтер мог 
отследить такие ситуации, когда товар поступает и его сразу же пытаются 
списать.


```

Reported by `gs1994` on 2007-05-03 13:43:22

**Comment by NikolayUkleyko** [comment]
Добавив признак **Дата поступления**, то в форме выбора остатков ТМЦ позиции с одной ценой будут разбиты на n-е число строк согласно даты поступления. Это усложнит и замедлит работу пользователя и БД.
  Предположительно, под датой поступления имеется в виду не дата непосредственного **_поступления на склад предприятия**_ (документ **01. Накладная на получение материалов, ОС, МБП**), а дата **_передачи**_ с центрального склада на конечный склад (сотрудника) (документ **02. Внутренние перемещения материалов, МБП**).
  Вопрос: на сколько реально необходим данный признак ?
@MIchaelShoihet

**Comment by MIchaelShoihet** [comment]
Если бы он был бы так необходим его бы уже добавили :)
