### ISSUE TITLE
ОС и драгметаллы

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#617]
Originally reported on Google Code with ID 617

```
Доукомплектация ОС и демонтаж не отражаются в драг металлах.


```

Reported by `gs1994` on 2007-05-03 13:49:26

**Comment by gsbelarus** [comment]
```
Я так понимаю, проблема в том, что эти док-ты могут менять содержание драгметаллов в
ОС. Тогда нужно сделать, как в док-те "ОС. Изменение свойств": добавить в позицию
ТО-признак "карточка драгметаллов" и в шапке сделать грид с драгметаллами
```

Reported by `alexandra.gsoftware` on 2007-05-05 08:41:51
- **Labels added**: Type-Task
- **Labels removed**: Type-Defect

**Comment by gsbelarus** [comment]
```
Нет просто в отчетах по драгметалах не отражалось их движения связанное с 
документами докомплектация и разукомпектация. Сейчас это вроде сделали - проверяю.
```

Reported by `mikleshoihet` on 2007-06-15 13:34:51

**Comment by gsbelarus** [comment]
```
>Сейчас это вроде сделали - проверяю
Так правильно сделали?
```

Reported by `alexandra.gsoftware` on 2008-03-10 13:34:52

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2015-06-29 13:23:25
- **Labels added**: Precious
- **Labels removed**: Драгметаллы

**Comment by NikolayUkleyko** [comment]
Данная тема рассматривается в https://github.com/GoldenSoftwareLtd/gedemin/issues/618#issuecomment-184563033
  Пожалуйста, закройте здесь.
