### ISSUE TITLE
Инвентаризация по драгметаллам

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#618]
Originally reported on Google Code with ID 618

```
Как ее провести в программе?
```

Reported by `gs1994` on 2007-05-03 13:50:45

**Comment by gsbelarus** [comment]
```
Если имеется в виду изменение кол-ва драгметаллов у ТМЦ, то инвентаризацию
драгметаллов можно провести в документе "ОС. Изменение свойств"
```

Reported by `flakekun` on 2007-05-14 11:51:30

**Comment by gsbelarus** [comment]
```
Самое главное чтобы в инвентаризационной ведомости было видно кол-во по данным 
бухучета (это то что было до инвентариации) и фактическое кол-во отличается (это то

что стало после инвентаризации) причем не только по ОС, но и по материалам.
```

Reported by `mikleshoihet` on 2007-06-15 13:31:04

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2015-06-29 13:23:25
- **Labels added**: Precious
- **Labels removed**: Драгметаллы

**Comment by NikolayUkleyko** [comment]
**а**. В программе можно сформировать **только отчеты** по инвентаризации драгоценных металлов. Я не встречал в программе **документы**, в которых можно было бы отразить инвентаризацию драгоценных металлов как по материальному складу, так и по основным средствам.
**б**. Документ **ОС. Изменение свойств** совершенно не подходит для отражения инвентаризации драгоценных металлов.
**в**. На практике достаточно отчета с графами **факт.** и **по документам**. Где, в графе **факт.** бухгалтер вручную вносит требуемые данные.

  У кого какие есть предложения по данной теме ?
  Если, нет - закройте данную тему.

**Comment by alexandra-gsoftware** [comment]
мне кажется, что все равно нужен док-т, где вносятся реальные данные по ДМ... А Изменение св-в почему не подходит?

**Comment by MIchaelShoihet** [comment]
На самом деле - что значит реальные данные по драг металлам - они могут быть известны только после переплавки и это идет отдельным отчетом, а пока предмет используется просчитать кол-во драг. металлов в нем не возможно. Поэтому отчетов обычно хватает. Но бывают ошибки, бывает что по какому-то наименованию забыли внести и для того что бы старые отчеты не ломались можно в докменте изменения свойств добавить закладку Драг металлы с возможностью формирования новой карточки - т.е. не изменения предудущей а именно формирование новой. Это учесть в отчетах по драг металлам.

**Comment by NikolayUkleyko** [comment]
**а**. Документ **ОС. Изменение свойств** предназначен для отражения изменений по **относительным значениям**. Количество драгоценных металлов является **абсолютным значением**. Поэтому, данный документ не к месту.

**б**. По хорошему необходим **реальный документ** инвентаризации драгоценных металлов по основным средствам. Я бы взял за основу из материального склада документ **09. Инвентаризация материалов** и в шапку добавил бы закладку **Драг. металлы**. На данной закладке был бы грид с полями:
- наименование ДМ;
- количеством ДМ по документам;
- фактическое количество ДМ;
- отклонение.
  
  Еще бы и не мешало отразить стоимость драгоценных металлов.
  У конкурентов существует даже два документа : **_Инвентаризация ОС**_ и **_Инвентаризация ОС по ДМ**_.

**в**.

> реальные данные по драг металлам - они могут быть известны только после переплавки и это идет отдельным отчетом, а пока предмет используется просчитать кол-во драг. металлов в нем не возможно

  Не согласен.

**г**.

> для того что бы старые отчеты не ломались можно в докменте изменения свойств добавить закладку Драг металлы с возможностью формирования новой карточки - т.е. не изменения предудущей а именно формирование новой

  Это уже давно реализовано.

**д**. Для удобства работы с драгоценными металлами хорошо бы в форме **Остатков ОС по драг. металлам** и / или **документах учета основных средств** предусмотреть кнопку для формирования **карточки по драгоценным металлам**. Нажав на данную кнопку программа отобразила бы за период остатки на начало и на конец, все движение драгоценных металлов по выбранному основному средству (аналог стандартной карточки ТМЦ и карточки по холдингу).

  Это моя точка зрения.

**Comment by MIchaelShoihet** [comment]
Все конечно хорошо, но движение драг металлов у нас не ведется (как складское движение) и я считаю это лишним. Как часто изменяется кол-во драг металлов - единицы, для этого достаточно того что уже есть, в документе изменения свойств мы создаем новую карточку с новыми значениями и этого нам хватит что бы увидеть изменения, которые произошли с драгметаллами. Основное движение драгметаллов это все-таки комплектация и разукомплектация. Поэтому необходимо проверить как будут вести себя отчеты в случае появления новой карточки в Документе изменения св-в (с случае если была старая и в случае если старой не было), сделать что бы они вели себя правильно, т.е. разница старой и новой карточки должна отражаться как движение драг металлов если документ попадает в период построения отчетов, на этом остановиться.

**Comment by NikolayUkleyko** [comment]
**а**. Сейчас в документе **ОС. Изменение свойств** присутствует закладка **Драг. металлы**:
![1](https://cloud.githubusercontent.com/assets/11497453/13077872/8e15bf82-d4cc-11e5-8ac8-f00d799041ce.png)

  Работает весьма **_специфично**_. Для того, чтобы ввести **иное количество** драгоценных металлов необходимо нажать на кнопку **Изменить** и кнопка **ОК**. Тогда, в документе **Карточка ТМЦ по драг.металлам** будет создана новая запись с новым количеством.
  При повторном редактировании записи по документу кнопка **Изменить** уже отжата. При очередном нажатии на нее программа выводит сообщение:
![2](https://cloud.githubusercontent.com/assets/11497453/13078034/b6f53fee-d4cd-11e5-809b-d97629e51520.png)

  Если, уж и реализованы драгоценные металлы в документе **ОС. Изменение свойств**, то надо доработать грид и его поведение. Добавить поля и соответствующий пересчет:
- наименование ДМ;
- количеством ДМ по документам;
- фактическое количество ДМ;
- отклонение.

**б**. В документе **ОС. Изменение свойств** выбраны признаки **TO** и **FROM** карточки драгоценных металлов. Работает корректно. В отчеты по основным средствам по драгоценным металлам **попадают** данные из документа **ОС. Изменение свойств**.

**в**. Из документов **ОС. Комплектация** и **ОС. Разукомплектация** данные по драгоценным металлам **не попадают** в отчеты по основным средствам по драгоценным металлам.
