### ISSUE TITLE
Блокировка периода на переменную дату

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#687]
Originally reported on Google Code with ID 687

```
Было бы неплохо сделать автоматическую блокировку (на дату), установить 
кол-во дней, так, чтобы дата блокировки менялась, относительно 
установленного кол-ва дней.
```

Reported by `hjamesGS` on 2007-06-21 21:47:16

**Comment by gsbelarus** [comment]
```

  Не совсем удобно будет работать такая блокировка, если пользователи не успели отразить
операции. В таком случае придеться каждый раз увеличивать период.
  Чем не устраивает стандартная блокировка: Сервис > Параметры > Аудит и безопасность
> Блокировка периода распространяется на документы и проводки ?

```

Reported by `NikolayUkleyko` on 2014-04-02 11:06:18

**Comment by gsbelarus** [comment]
```
Это больше не для баз с бух.учетом,  а например, для торговли.
Сформировали продажи, и вчерашние, или позавчерашние уже были заблокированы.
Были такие просьбы от клиентов. ЧТобы не надо было человеку с правами Администратора
каждый день заходить, и блокировать период.
```

Reported by `hjamesGS` on 2014-04-02 14:23:30

**Comment by gsbelarus** [comment]
```

  Идея ясна.
  Но ! Как это можно реализовать, учитывая другие механизмы блокировок ?

```

Reported by `NikolayUkleyko` on 2014-04-08 14:22:46

**Comment by NikolayUkleyko** [comment]
Как вариант, существует ПИ **GS.Безопасность.Разграничение прав пользователя**.
Описание смотрите здесь http://gsbelarus.com/pw/articles/post/global-filter/.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
По данному вопросу было задание.
По ходу - глухо.

Коллеги, если, на ,ваш, взгляд данная тема уже неактуальна, пожалуйста, закройте ее.

**Comment by NikolayUkleyko** [comment]
На сегодня разработан функционал по блокировке изменений данных по счетам.
ПИ **Блокировка по бухгалтерским счетам**.

----

@gsbelarus , пожалуйста, закройте тему.

**Comment by NikolayUkleyko** [comment]
Такая доработка рассматривается здесь https://github.com/GoldenSoftwareLtd/gedemin/issues/4214.
@gsbelarus , пожалуйста, закройте тему.
