### ISSUE TITLE
Разноска по счетам

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#732]
Originally reported on Google Code with ID 732

```
Хочется иметь стандартный механизм удаления всей разноски перед ее
построением , как в автоматических операциях.
```

Reported by `mikleshoihet` on 2007-08-31 12:57:18

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, расскажите подробнее.
Эталонный функционал разноски предусматривает отдельную форму просмотра разноски с возможностью удаления выбранных записей.

**Comment by NikolayUkleyko** [comment]
Close.
