### ISSUE TITLE
Суммы в эквиваленте в автоматических операциях

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#753]
Originally reported on Google Code with ID 753

```
Когда мы создаем проводку по документу, в конструкторе проводок мы можем 
задать сумму проводки в рублях, в валюте и в эквиваленте. Если же мы 
создаем автоматическую операцию, то сумму проводки можно задать только в 
рублях и в валюте. А в эквиваленте как задать?
```

Reported by `kovli.gs` on 2007-10-04 05:18:09

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2012-10-09 16:27:25
- **Labels added**: Priority-High, GedeminEXE, Accountancy
- **Labels removed**: Priority-Medium

**Comment by gsbelarus** [comment]
```

  Да-да, вопрос актуальный.
  Как в АХО отразить сумму в эквиваленте ?

```

Reported by `NikolayUkleyko` on 2014-01-09 13:18:55

**Comment by NikolayUkleyko** [comment]
Пожалуйста, реализуйте такую возможность.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by Polfath** [comment]
Сделал

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !

@gsbelarus , пожалуйста, закройте тему.

**Comment by NikolayUkleyko** [comment]
Close.

**Comment by NikolayUkleyko** [comment]
Проверено.
Работает корректно.
@Polfath , большое спасибо !

**Comment by NikolayUkleyko** [comment]
Если, нет вопросов, то данную тему можно закрывать.
