### ISSUE TITLE
Форма Choose

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#825]
Originally reported on Google Code with ID 825

```
Пожелание:
  Добавить еще одну форму выбора в которой можно будет указывать
количество, а не просто ставить галочку
```

Reported by `nkornachenko` on 2007-12-06 12:35:08

**Comment by gsbelarus** [comment]
```
тут не форму добавлять надо, а в грид залезть. раз уж мы добавляем в колонку галочку,
то почему бы туда же не добавить Edit?
```

Reported by `gs1994` on 2007-12-06 17:01:14

**Comment by NikolayUkleyko** [comment]
В форме выбора остатков ТМЦ, ОС и т. д. в поле **Выбрать** помимо указания галки (выбор всех остатков) предусмотрен ввод **требуемого количества**.
  Если, ни у кого нет вопросов, пожалуйста, закройте данную тему.
