### ISSUE TITLE
Книга покупок

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#847]
Originally reported on Google Code with ID 847

```
При формировании книги покупок по определенной конфигурации в нее попадают
данные (проводки)из других конфигураций. То есть нет ограничения по счету
проводки типа 'Проводка с НДС' из конфигурации книги.
```

Reported by `danilchyk` on 2007-12-22 08:48:45

**Comment by gsbelarus** [comment]
```
Тестовый пример бы. По коду процедуры работает правильно, проверяется на ключ конфигурации,
и входящие в нее счета.
```

Reported by `flakekun` on 2010-10-04 08:39:50
- **Labels added**: Priority-Medium
- **Labels removed**: Priority-High

**Comment by gsbelarus** [comment]
Reported by `gs1994` on 2015-06-29 13:57:56
- **Labels added**: Accountancy
- **Labels removed**: Бухгалтерия

**Comment by NikolayUkleyko** [comment]
В документе **Книга покупок образца 2015 г.** в шапке документа можно выбрать необходимую конфигурацию.
  Работает корректно.
  Если, ни у кого нет вопрос, пожалуйста, закройте данную тему.
