### ISSUE TITLE
Удаление множества записей

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#867]
Originally reported on Google Code with ID 867

```
При удалении множества записей в форме просмотра, курсор переключать в часы.


```

Reported by `gs1994` on 2008-01-09 17:27:47

**Comment by gsbelarus** [comment]
Reported by `alexandra.gsoftware` on 2008-05-14 15:37:52
- **Labels added**: Type-Enhancement
- **Labels removed**: Type-Defect

**Comment by gsbelarus** [comment]
```

  Ничего подобного я не заметил.
  Было бы хорошо предусмотреть такую возможность.

```

Reported by `NikolayUkleyko` on 2014-01-16 07:26:01

**Comment by NikolayUkleyko** [comment]
@ShlTanya , пожалуйста, изложи свою точку зрения.

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
