### ISSUE TITLE
Удалить - Исключить

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#868]
Originally reported on Google Code with ID 868

```
В форме в режиме выбора, кнопку Удалить лучше переименовать в Исключить.


```

Reported by `gs1994` on 2008-01-09 17:28:36

**Comment by gsbelarus** [comment]
```

  К чему это ?

```

Reported by `NikolayUkleyko` on 2014-01-16 07:26:54

**Comment by gsbelarus** [comment]
```
Потому что она не удаляет объект, а исключает его из списка выбранных.
```

Reported by `gs1994` on 2014-01-16 07:42:21
- **Labels added**: GedeminEXE

**Comment by NikolayUkleyko** [comment]
Да.
Верно.
Корректно будет **Исключить** из отмеченных, а не **Удалить**.

**Comment by NikolayUkleyko** [comment]
В режиме выбора документов на форме в правом нижнем углу расположены кнопки **Ok**, **Отмена** и **Удалить**.
Необходимо переименовать кнопку **Удалить** в **Исключить**.
