### ISSUE TITLE
Создание домена из окна создания поля аналитики

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#905]
Originally reported on Google Code with ID 905

```
Запретить, так как не всегда отрабатывает правильно.


```

Reported by `gs1994` on 2008-01-28 17:48:37

**Comment by gsbelarus** [comment]
Reported by `alexandra.gsoftware` on 2009-03-26 11:39:04
- **Labels added**: GedeminExe

**Comment by NikolayUkleyko** [comment]
Из не сложных вариантов можно в инспекторе объектов на форме **gdc_acct_dlgAnalysis** очистить значение в реквизите **gdClassName**.
Сейчас выбран бизнес-класс **TgdcField**.

**Comment by NikolayUkleyko** [comment]
Close.
