### ISSUE TITLE
MessageBox в бизнес-объекте

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#908]
Originally reported on Google Code with ID 908

```
Хорошо было бы в gdcBase добавить свойство, установив которое не 
выводились MessageBox. Конечно надо будет во всех БО проверять это св-во, 
но если бы оно было бы общее, то проще было бы это сделать.


```

Reported by `mikleshoihet` on 2008-02-04 10:53:40

**Comment by gsbelarus** [comment]
Reported by `flakekun` on 2008-05-14 16:11:30
- **Labels added**: Type-Enhancement
- **Labels removed**: Type-Defect

**Comment by gsbelarus** [comment]
Reported by `alexandra.gsoftware` on 2009-03-26 11:38:03
- **Labels added**: GedeminExe

**Comment by NikolayUkleyko** [comment]
@MIchaelShoihet , пожалуйста, подскажите, это еще актуально ?
