### ISSUE TITLE
Инспектор классов всегда появляется при запуске Редактора СО

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#935]
Originally reported on Google Code with ID 935

```
Инспектор классов всегда теперь появляется при запуске редактора СО.
```

Reported by `gs1994` on 2008-03-02 17:10:43

**Comment by gsbelarus** [comment]
```
не всегда, а только, если последний раз он был задокирован. там в коде так прописано.
надо смотреть...
```

Reported by `gs1994` on 2008-03-02 19:20:25

**Comment by gsbelarus** [comment]
```
Так может, так и надо? В чем проблема?
```

Reported by `alexandra.gsoftware` on 2008-03-06 11:38:33

**Comment by gsbelarus** [comment]
```
проблема есть. я сам разберусь.
```

Reported by `gs1994` on 2008-03-06 11:45:16

**Comment by gsbelarus** [comment]
Reported by `alexandra.gsoftware` on 2009-03-26 11:13:16
- **Labels added**: GedeminExe

**Comment by NikolayUkleyko** [comment]
@gsbelarus , пожалуйста, закройте тему.
