### ISSUE TITLE
Порядок элементов для поля типа перечисление

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#982]
Originally reported on Google Code with ID 982

```
В выпадающем списке для поля типа перечисление отменить фильтрацию, чтобы
порядок элементов соответствовал введенному программистом при создании типа
данных.

Например: дни недели.


```

Reported by `gs1994` on 2008-05-07 13:34:49

**Comment by gsbelarus** [comment]
Reported by `Alexander.GoldenSoft` on 2008-05-07 16:24:28
- **Status changed**: `Fixed`

**Comment by NikolayUkleyko** [comment]
Перепроверил, получается, что это уже реализовано.
@gsbelarus , пожалуйста, закройте тему.
